DROP TABLE IF EXISTS IFRS_DECISION_LOGS;

CREATE TABLE IF NOT EXISTS IFRS_DECISION_LOGS (
  PKID SERIAL PRIMARY KEY,
  DOWNLOAD_DATE DATE,
  RUN_ID VARCHAR(100) NOT NULL,
  MAX_STEP BIGINT,
  STEP BIGINT,
  PROCESS_ID BIGINT NOT NULL,
  PROCESS_DATE TIMESTAMP WITHOUT TIME ZONE
)