CREATE TABLE "PSAK413_BSI"."BSI_SUPER_CIF_FINAL" 
   (	"DOWNLOAD_DATE" DATE, 
	"GLOBAL_CUSTOMER_NUMBER" VARCHAR2(100), 
	"CUSTOMER_NUMBER" VARCHAR2(100), 
	"CO_CODE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
