CREATE TABLE "PSAK413"."EIR" 
   (	"VALUATION_DATE" TIMESTAMP (8), 
	"DEAL_ID" NVARCHAR2(25) NOT NULL ENABLE, 
	"EIR" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
