CREATE TABLE "PSAK413"."GTMP_TERM_STRUCTURE" 
   (	"EFF_DATE" DATE, 
	"BASE_DATE" DATE, 
	"MODEL_ID" NUMBER, 
	"PD_RULE_ID" NUMBER, 
	"FL_SEQ" NUMBER, 
	"INCREMENT_PERIOD" NUMBER, 
	"BUCKET_GROUP" VARCHAR2(50), 
	"BUCKET_ID" NUMBER, 
	"PD" NUMBER, 
	"PD_METHOD" VARCHAR2(50), 
	"PD_RULE_NAME" VARCHAR2(250), 
	"MAX_BUCKET_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
