CREATE TABLE "PSAK413_BSI"."HASIL" 
   (	"DOWNLOAD_DATE" VARCHAR2(50), 
	"CUSTOMER_NUMBER" NUMBER(*,0), 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(50), 
	"ACCOUNT_STATUS_ORI" VARCHAR2(50), 
	"OUTSTANDING" NUMBER(*,0), 
	"PRODUCT_TYPE" VARCHAR2(50), 
	"COLUMN8" VARCHAR2(50), 
	"LOAN_START_DATE" VARCHAR2(50), 
	"LOAN_DUE_DATE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
