CREATE TABLE "PSAK413"."IFRS_LGD_RULES_CONFIG_S_00000_0000" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"DEFAULT_RULE_ID" NUMBER(20,0), 
	"LGD_RULE_NAME" NVARCHAR2(250), 
	"SEGMENTATION_ID" NUMBER(20,0), 
	"LGD_METHOD" NVARCHAR2(50) NOT NULL ENABLE, 
	"LGW_HISTORICAL_DATA" NUMBER(5,0), 
	"POW_HISTORICAL_DATA" NUMBER(5,0), 
	"CURED_DEFINITION" NUMBER(5,0), 
	"WORKOUT_PERIOD" NUMBER(5,0), 
	"MIN_VALUE" BINARY_DOUBLE, 
	"MAX_VALUE" BINARY_DOUBLE, 
	"CUT_OFF_DATE" DATE, 
	"ACTIVE_FLAG" NUMBER(10,0), 
	"IS_DELETE" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"LAG_1MONTH_FLAG" NUMBER(10,0), 
	"EXCLUDE_RESTRUCTURE_FLAG" NUMBER(10,0), 
	"CALC_METHOD" NVARCHAR2(20), 
	"RUNNING_STATUS" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
