CREATE TABLE "PSAK413"."IFRS_LGD_POW_HEADER" 
   (	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER(20,0), 
	"EAD_DEFAULT" NUMBER(32,6), 
	"EAD_CURED" NUMBER(32,6), 
	"POC" BINARY_DOUBLE, 
	"POW" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
