CREATE TABLE "PSAK413"."IFRS_MASTER_LIMIT_CORP_UPLOAD" 
   (	"DOWNLOAD_DATE" DATE, 
	"DATA_SOURCE" NVARCHAR2(20), 
	"LIMIT_FLAG" NUMBER(10,0), 
	"BRANCH_CODE" NVARCHAR2(10), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CURRENCY" NVARCHAR2(3), 
	"BI_COLLECTABILITY" NUMBER(10,0), 
	"MATURITY_DATE" DATE, 
	"PLAFOND" NUMBER(32,6), 
	"UNUSED_LIMIT" NUMBER(32,6), 
	"OUTSTANDING" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_IFRS_SYNC_CORPORATE_DATA', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
