CREATE TABLE "PSAK413"."IFRS_AC_BM_HEADER" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMMONCODEID" NVARCHAR2(20), 
	"BM_NAME" NVARCHAR2(100) NOT NULL ENABLE, 
	"SPPI_CLASS" NVARCHAR2(1000) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"STATUS" NVARCHAR2(50), 
	"BM_RSLT" NVARCHAR2(50), 
	"REMARKS" NCLOB, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(36), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" DATE, 
	"APPROVEDHOST" NVARCHAR2(36), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "PK__IFRS_AC___5E02827214B45119" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("REMARKS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
/
