CREATE TABLE "PSAK413"."IFRS_ME_FORECAST_SCN" 
   (	"EFF_DATE" DATE, 
	"ME_CODE" VARCHAR2(100), 
	"ME_PERIOD" DATE, 
	"SCENARIO_NO" NUMBER(10,0), 
	"STDDEV" NUMBER, 
	"ME_VALUE" NUMBER, 
	"CREATEDBY" VARCHAR2(30), 
	"CREATEDDATE" DATE, 
	"CREATEDHOST" VARCHAR2(36), 
	"UPDATEDBY" VARCHAR2(30), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(36), 
	"MEAN" NUMBER, 
	"MODEL_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
