CREATE TABLE "PSAK413"."IFRS_IMP_OVERRIDE_MASTER" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"OVERRIDE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"PRODUCT_ENTITY" NVARCHAR2(1), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"CURRENCY" NVARCHAR2(5), 
	"IPP" NUMBER(32,6), 
	"IPD" NUMBER(32,6), 
	"IIP" NUMBER(32,6), 
	"FSV_COLL_AMOUNT" NUMBER(32,6), 
	"DCFSTATUS" NVARCHAR2(1), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"UPDATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
