CREATE TABLE "PSAK413"."IFRS_SCENARIO_SEGMENT_GENERATE_QUERY" 
   (	"RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"GROUP_SEGMENT" NVARCHAR2(50), 
	"SUB_SEGMENT" NVARCHAR2(50), 
	"SEGMENT" NVARCHAR2(50), 
	"TABLE_NAME" NVARCHAR2(30), 
	"CONDITION" NCLOB, 
	"SEGMENT_TYPE" NVARCHAR2(50), 
	"SEQUENCE" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"PRC_FLAG" NVARCHAR2(1), 
	 CONSTRAINT "PK__IFRS_SCE__E103520C559E74AF" PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONDITION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
/
