CREATE TABLE "PSAK413"."IFRS_DIM_GEOGRAPHICAL_SECTORS" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"GEOGRAPHICAL_ID" NVARCHAR2(20) NOT NULL ENABLE, 
	"PULAU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PULAU_NAMA" NVARCHAR2(30) NOT NULL ENABLE, 
	"PROVINSI_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PROVINSI_NAMA" NVARCHAR2(40) NOT NULL ENABLE, 
	"KABUPATEN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KABUPATEN_NAMA" NVARCHAR2(70) NOT NULL ENABLE, 
	"BRANCH_CODE" NVARCHAR2(6) NOT NULL ENABLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
