CREATE TABLE "PSAK413"."IFRS_IAP_PARAM_SCENARIO" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"HEADER_ID" NUMBER(20,0), 
	"SCENARIO_ID" NUMBER(5,0), 
	"SCENARIO_NAME" NVARCHAR2(50), 
	"PROBABILITY_OUTCOME" BINARY_DOUBLE, 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"WORKOUT_PERIOD" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
