CREATE TABLE "PSAK413_BSI"."IFRS_PD_TERM_FL" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"MODEL_ID" NUMBER(19,0), 
	"MODEL_SEQ" NUMBER(19,0), 
	"SCENARIO_NO" NUMBER(5,0), 
	"SEQ" NUMBER(5,0), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"FL_YEAR" NUMBER(5,0), 
	"FL_MONTH" NUMBER(5,0), 
	"PD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
