CREATE TABLE "PSAK413"."IFRS_MASTER_SURVIVE" 
   (	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"PREVIOUS_MASTERID" NVARCHAR2(50), 
	"MASTERID" NVARCHAR2(50), 
	"PREVIOUS_ACCOUNT_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"SURVIVE_FLAG" NVARCHAR2(1), 
	"CREATEDBY" NVARCHAR2(100) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20) DEFAULT 'LOCALHOST'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
