CREATE TABLE "PSAK413_BSI"."IFRS_LGD_RULE_DATA_S_00000_0000" 
   (	"PKID" NUMBER(19,0) NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"RULE_ID" NUMBER(19,0), 
	"MASTERID" NUMBER(19,0), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(20), 
	"OUTSTANDING" NUMBER(32,6), 
	"IMPAIRED_FLAG" VARCHAR2(5), 
	"LOAN_START_DATE" DATE, 
	"LOAN_DUE_DATE" DATE, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"CURRENCY" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
