CREATE TABLE "PSAK413"."IFRS_ME_MODEL_SCENARIO" 
   (	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_SEQ" NUMBER(10,0), 
	"MODEL_FORMULA" NCLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MODEL_FORMULA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
/
