CREATE TABLE "PSAK413"."IFRS_PD_EXTERNAL_TREASURY" 
   (	"DOWNLOAD_DATE" DATE, 
	"SEGMENT" NVARCHAR2(20), 
	"RATING_CODE" NVARCHAR2(10), 
	"REMAINING_TENOR_YEAR" NUMBER(10,0), 
	"CUMMULATIVE_PD" BINARY_DOUBLE, 
	"MARGINAL_PD" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_IFRS_SYNC_CORPORATE_DATA', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50) DEFAULT 'LOCALHOST', 
	"PEFINDO_RATING_CODE" NVARCHAR2(20), 
	"SNP_RATING_CODE" NVARCHAR2(20), 
	"PEFINDO_PD_RATE" BINARY_DOUBLE, 
	"SNP_PD_RATE" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
