CREATE TABLE "PSAK413"."IFRS_LI_STG_TRANSACTION_DAILY" 
   (	"DOWNLOAD_DATE" NVARCHAR2(20), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"BRANCH_CODE" NVARCHAR2(20), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"PRD_CODE" NVARCHAR2(20), 
	"TRX_CODE" NVARCHAR2(20), 
	"TRANSACTION_REFERENCE_NUMBER" NVARCHAR2(50), 
	"TRANSACTION_DATE" NVARCHAR2(20), 
	"EFFECTIVE_DATE" NVARCHAR2(20), 
	"POSTING_DATE" NVARCHAR2(20), 
	"START_DATE" NVARCHAR2(20), 
	"DUE_DATE" NVARCHAR2(20), 
	"CURRENCY" NCHAR(3), 
	"AL_FLAG" NCHAR(1), 
	"DEBIT_CREDIT_FLAG" NCHAR(1), 
	"TERMINATE_FLAG" NCHAR(1) DEFAULT 'N', 
	"HOLD_AMOUNT" NVARCHAR2(50), 
	"INITIAL_COST_AMOUNT" NVARCHAR2(50), 
	"TRX_SEQUENCE" NVARCHAR2(20), 
	"FILENAME" NVARCHAR2(100), 
	"SOURCE_PROCESS" NVARCHAR2(50) DEFAULT 'DWH Process'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
