CREATE TABLE "PSAK413"."IFRS_LI_ACCT_NOCF" 
   (	"MASTERID" NVARCHAR2(100), 
	"DOWNLOAD_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
