CREATE TABLE "PSAK413"."IFRS_PAYM_SCHD_ALL" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"PMTDATE" DATE, 
	"MARGIN_RATE" NUMBER(12,6), 
	"OSPRN" NUMBER(32,6), 
	"PRINCIPAL" NUMBER(32,6), 
	"MARGIN" NUMBER(32,6), 
	"DISB_PERCENTAGE" NUMBER(12,6), 
	"DISB_AMOUNT" NUMBER(32,6), 
	"PLAFOND" NUMBER(32,6), 
	"I_DAYS" NUMBER(20,0), 
	"COUNTER" NUMBER(20,0), 
	"ICC" NVARCHAR2(1), 
	"OUTSTANDING" NUMBER(32,6), 
	"SOURCE_PROCESS" NVARCHAR2(20), 
	"SCH_FLAG" NVARCHAR2(2), 
	"GRACE_DATE" DATE, 
	"STATUS" NVARCHAR2(2), 
	"END_DATE" DATE, 
	"CREATED_DATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
