CREATE TABLE "PSAK413"."IFRS_PAYM_CORE_SRC" 
   (	"MASTERID" NVARCHAR2(100), 
	"ACCTNO" NVARCHAR2(70), 
	"PREV_PMT_DATE" DATE, 
	"PMT_DATE" DATE, 
	"MARGIN_RATE" NUMBER(12,6), 
	"I_DAYS" NUMBER(20,0), 
	"OS_PRN_PREV" NUMBER(32,6), 
	"PRN_AMT" NUMBER(32,6), 
	"INT_AMT" NUMBER(32,6), 
	"OS_PRN" NUMBER(32,6), 
	"DISB_PERCENTAGE" NUMBER(12,6), 
	"DISB_AMOUNT" NUMBER(32,6), 
	"PLAFOND" NUMBER(32,6), 
	"COUNTER" NUMBER(10,0), 
	"ICC" NUMBER(10,0), 
	"GRACE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
