CREATE TABLE "PSAK413"."IFRS_MASTER_RESTRU_COLLECT" 
   (	"DOWNLOAD_DATE" DATE, 
	"RESTRUCTURE_DATE" DATE, 
	"PREVIOUS_MASTERID" NVARCHAR2(100), 
	"MASTERID" NVARCHAR2(100), 
	"PREVIOUS_ACCOUNT_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(150), 
	"BRANCH_CODE" NVARCHAR2(4), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"TGL_CAIR_BARU" DATE, 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
