CREATE TABLE "PSAK413"."IFRS_PD_VAS_ZSCORE" 
   (	"EFF_DATE" DATE, 
	"BASE_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"SCENARIO_NO" NUMBER, 
	"ODR" NUMBER, 
	"MEAN_ODR" NUMBER, 
	"STDEV_ODR" NUMBER, 
	"ZSCORE" NUMBER, 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"ME_CODE" VARCHAR2(100), 
	"FL_SEQ" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
