CREATE TABLE "PSAK413"."IFRS_FACILITY_SELLDOWN_FLAG" 
   (	"DOWNLOAD_DATE" DATE, 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"OLD_FACILITY_NUMBER" NVARCHAR2(50), 
	"SELLDOWN_PERCENTAGE" NUMBER(32,6), 
	"SELLDOWN_OR_CANCELATION_FLAG" NVARCHAR2(2), 
	"SELLDOWN_DATE" TIMESTAMP (8), 
	"AMOUNT_SELLDOWN" NUMBER(32,6), 
	"CURRENCY_SELLDOWN" NVARCHAR2(12), 
	"INCREASE_FLAG" NVARCHAR2(20), 
	"INCREASE_AMOUNT" NUMBER(20,4), 
	"INCREASE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
