CREATE TABLE "PSAK413"."IFRS_EAD_CCF_DETAIL" 
   (	"DOWNLOAD_DATE" DATE, 
	"CCF_RULE_ID" NUMBER(20,0), 
	"CCF_UNIQUE_ID" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"EQV_PLAFOND_12M_BEFORE_DEFAULT" NUMBER(32,6), 
	"EQV_OS_12M_BEFORE_DEFAULT" NUMBER(32,6), 
	"EQV_AT_DEFAULT" NUMBER(20,0), 
	"EQV_PLAFOND_AT_DEFAULT" NUMBER(32,6), 
	"DRAWDOWN" BINARY_DOUBLE, 
	"HEADROOM" BINARY_DOUBLE, 
	"CCF" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"EXCLUDE" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
