CREATE TABLE "PSAK413"."IFRS_AC_BM_QUEST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMMONCODEID" NVARCHAR2(50), 
	"COMMONCODENAME" NVARCHAR2(50), 
	"QUESTION_TYPE" NUMBER(10,0), 
	"QUESTION_DESC" NVARCHAR2(100), 
	"SUPPORTING_FLG" NUMBER(10,0), 
	"SEQUENCE" NUMBER(10,0), 
	"OPTION_NUMBER" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(36), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "PK__IFRS_AC___5E028272DBD52AD7" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
