CREATE TABLE "PSAK413"."IFRS_JOURNAL_DATA_OUTPUT" 
   (	"DOWNLOAD_DATE" DATE, 
	"TRANS_DATETIME" DATE, 
	"ACCNT_CODE" NVARCHAR2(30), 
	"PERIOD" NVARCHAR2(10), 
	"AMOUNT" NUMBER(32,6), 
	"D_C" NVARCHAR2(1), 
	"JRNAL_TYPE" NVARCHAR2(10), 
	"JRNAL_SRCE" NVARCHAR2(15), 
	"JRNAL_REF_NUM" NVARCHAR2(100), 
	"JRNAL_DESC" NVARCHAR2(255), 
	"ENTRY_DATETIME" DATE, 
	"ENTRY_PERIOD" NVARCHAR2(10), 
	"DUE_DATETIME" DATE, 
	"CONV_CODE" NVARCHAR2(3), 
	"CONV_RATE" NUMBER(19,6), 
	"OTHER_AMT" NUMBER(32,6), 
	"ANAL_T0" NVARCHAR2(50), 
	"ANAL_T1" NVARCHAR2(50), 
	"ANAL_T2" NVARCHAR2(50), 
	"ANAL_T3" NVARCHAR2(50), 
	"ANAL_T4" NVARCHAR2(50), 
	"ANAL_T5" NVARCHAR2(50), 
	"ANAL_T6" NVARCHAR2(50), 
	"ANAL_T7" NVARCHAR2(50), 
	"ANAL_T8" NVARCHAR2(50), 
	"ANAL_T9" NVARCHAR2(50), 
	"REPORT_RATE" NUMBER(19,6), 
	"REPORT_AMT" NUMBER(32,6), 
	"MEMO_AMT" NUMBER(32,6), 
	"LINK_REFERENCE_1" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
