CREATE TABLE "PSAK413"."IFRS_LGD_ER_SCENARIO_DATA" 
   (	"DOWNLOAD_DATE" DATE, 
	"DEFAULT_DATE" DATE, 
	"RECOVERY_DATE" DATE, 
	"CALC_METHOD" NVARCHAR2(10), 
	"LGD_UNIQUE_ID" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"LGD_METHOD" NVARCHAR2(50), 
	"LGD_RULE_ID" NUMBER(10,0), 
	"LGD_RULE_NAME" NVARCHAR2(50), 
	"PRODUCT_GROUP" NVARCHAR2(50), 
	"SEGMENT" NVARCHAR2(50), 
	"SUB_SEGMENT" NVARCHAR2(50), 
	"GROUP_SEGMENT" NVARCHAR2(50), 
	"CURRENCY" NVARCHAR2(3), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"RECOVERY_AMOUNT" NUMBER(32,6), 
	"EIR_AT_DEFAULT" BINARY_DOUBLE, 
	"JAP_FLAG" NUMBER(10,0), 
	"NPV_RECOVERY" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
