CREATE TABLE "PSAK413"."IFRS_LGD_REC_WO_DETAIL" 
   (	"DOWNLOAD_DATE" DATE, 
	"TRX_DATE" DATE, 
	"TRX_REFERENCE_NUMBER" NVARCHAR2(100), 
	"MASTERID" NUMBER(10,0), 
	"ORG_CCY_AMT" NUMBER(32,6), 
	"EQV_LCY_AMT" NUMBER(32,6), 
	"CREATED_DATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
