CREATE TABLE "PSAK413"."IFRS_LGD_TERM_STRUCTURE" 
   (	"DOWNLOAD_DATE" DATE, 
	"LGD_RULE_ID" NUMBER(10,0), 
	"LGD_RULE_NAME" NVARCHAR2(50), 
	"DEFAULT_RULE_ID" NUMBER(10,0), 
	"MODEL_ID" NUMBER(20,0), 
	"FL_SEQ" NUMBER(10,0), 
	"FL_YEAR" NUMBER(5,0), 
	"FL_MONTH" NUMBER(5,0), 
	"LGD" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
