CREATE TABLE "PSAK413"."IFRS_PD_MAA_FLOWRATE_S_00000_0000" 
   (	"PKID" NUMBER NOT NULL ENABLE, 
	"EFF_DATE" DATE NOT NULL ENABLE, 
	"BASE_DATE" DATE NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" VARCHAR2(30) NOT NULL ENABLE, 
	"BUCKET_FROM" NUMBER, 
	"BUCKET_TO" NUMBER, 
	"FLOWRATE" NUMBER, 
	"CREATEDBY" VARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" DATE NOT NULL ENABLE, 
	"CREATEDHOST" VARCHAR2(36) NOT NULL ENABLE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
