CREATE TABLE "PSAK413"."IFRS_ACCT_EIR_ECF_T2" 
   (	"MASTERID" NVARCHAR2(100), 
	"PMTDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
