CREATE TABLE "PSAK413"."IFRS_LI_TRANSACTION_PARAM" 
   (	"DATA_SOURCE" NVARCHAR2(50), 
	"PRD_TYPE" NVARCHAR2(50), 
	"PRD_CODE" NVARCHAR2(50), 
	"TRX_CODE" NVARCHAR2(50), 
	"CCY" NVARCHAR2(5), 
	"IFRS_TXN_CLASS" NVARCHAR2(5), 
	"AMORTIZATION_FLAG" NVARCHAR2(1), 
	"AMORT_TYPE" NVARCHAR2(10), 
	"GL_CODE" NVARCHAR2(50), 
	"TENOR_AMORTIZATION" NUMBER(10,0), 
	"TENOR_TYPE" NCHAR(1), 
	"TRANSACTION_TYPE" NVARCHAR2(7), 
	"GL_CODE_UAM" NVARCHAR2(50), 
	"FEE_MAT_TYPE" NVARCHAR2(10), 
	"FEE_MAT_AMT" NUMBER(32,6), 
	"COST_MAT_TYPE" NVARCHAR2(10), 
	"COST_MAT_AMT" NUMBER(32,6), 
	"SL_EXP_LIFE" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
