CREATE TABLE "PSAK413"."IFRS_PD_MAA_CORP_MMULT" 
   (	"DOWNLOAD_DATE" DATE, 
	"TO_DATE" DATE, 
	"PD_RULE_ID" NUMBER(10,0), 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"FL_SEQ" NUMBER(10,0), 
	"BUCKET_FROM" NUMBER(10,0), 
	"BUCKET_TO" NUMBER(10,0), 
	"MMULT" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
