CREATE TABLE "PSAK413_BSI"."IFRS_LGD_WORKOUT_HEADER2" 
   (	"EFF_DATE" DATE, 
	"WORKOUT_RULE_ID" NUMBER, 
	"EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"SEQ" NUMBER(5,0), 
	"EQV_REC_OS" NUMBER(32,6), 
	"CUM_REC_OS" NUMBER(32,6), 
	"MARGINAL_REC" NUMBER, 
	"CUM_REC" NUMBER, 
	"CREATEDBY" VARCHAR2(50), 
	"CREATEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
