CREATE TABLE "PSAK413"."IFRS_EXCLUDE_JENIUS" 
   (	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"AGREEMENT_DATE" DATE, 
	"COMMITMENT_REFERENCE" NVARCHAR2(100), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"PLAFOND" NUMBER(32,6), 
	"SEGMENT" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
