CREATE TABLE "PSAK413"."IFRS_TRANSACTION_PARAM" 
   (	"DATA_SOURCE" NVARCHAR2(50), 
	"PRD_TYPE" NVARCHAR2(50), 
	"PRD_CODE" NVARCHAR2(50), 
	"TRX_CODE" NVARCHAR2(50), 
	"CCY" NVARCHAR2(5), 
	"IFRS_TXN_CLASS" NVARCHAR2(5), 
	"AMORTIZATION_FLAG" NVARCHAR2(1), 
	"AMORT_TYPE" NVARCHAR2(10), 
	"GL_CODE" NVARCHAR2(50), 
	"TENOR_TYPE" NCHAR(1), 
	"TENOR_AMORTIZATION" NUMBER(5,0), 
	"TRANSACTION_TYPE" NVARCHAR2(7), 
	"GL_CODE_UAM" NVARCHAR2(50), 
	"SL_EXP_LIFE" NUMBER(5,0), 
	"FEE_MAT_TYPE" NVARCHAR2(10), 
	"FEE_MAT_AMT" NUMBER(32,6), 
	"COST_MAT_TYPE" NVARCHAR2(10), 
	"COST_MAT_AMT" NUMBER(32,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
