CREATE TABLE "PSAK413"."IFRS_MASTER_RESTRU_COVID" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"PREV_MASTERID" NVARCHAR2(100), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(100), 
	"PREV_ACCOUNT_NUMBER" NVARCHAR2(100), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"PREV_PRODUCT_CODE" NVARCHAR2(20), 
	"STAGE" NCHAR(1), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"SOURCE_SYSTEM" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
