CREATE TABLE "PSAK413"."IFRS_LGD_REC_DATA" 
   (	"DOWNLOAD_DATE" DATE, 
	"RULE_ID" NUMBER(10,0), 
	"MASTERID" NVARCHAR2(100), 
	"SEQ" NUMBER(*,0), 
	"REC_OS" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"REC_OS_INT" NUMBER(32,6), 
	"EQV_REC_OS_INT" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (6), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (6), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"CCY" CHAR(5), 
	"REC_TYPE" CHAR(2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
