CREATE TABLE "PSAK413"."IFRS_PD_LINEST_SMOOTHING" 
   (	"PD_RULE_ID" NUMBER, 
	"SLOPE" NUMBER(32,6), 
	"INTERCEPT" NUMBER(32,6), 
	"RSQUARE" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
