CREATE TABLE "PSAK413"."IFRS_FACILITY_REPORT_RECON" 
   (	"DOWNLOAD_DATE" DATE, 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"TRANSACTION_CODE" NVARCHAR2(20), 
	"CCY" NVARCHAR2(5), 
	"INITIAL_GL_FEE_AMT" NUMBER(32,6), 
	"INITIAL_GL_COST_AMT" NUMBER(32,6), 
	"UNALOC_GL_FEE_AMT" NUMBER(32,6), 
	"UNALOC_GL_COST_AMT" NUMBER(32,6), 
	"INITIAL_TRX_FEE_AMT" NUMBER(32,6), 
	"INITIAL_TRX_COST_AMT" NUMBER(32,6), 
	"UNALOC_TRX_FEE_AMT" NUMBER(32,6), 
	"UNALOC_TRX_COST_AMT" NUMBER(32,6), 
	"COUNTER_CHECK_FEE" NUMBER(32,6), 
	"COUNTER_CHECK_COST" NUMBER(32,6), 
	"FLAG_CF" NVARCHAR2(3)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
