CREATE TABLE "PSAK413"."IFRS_IMP_DEFAULT_STATUS" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(100), 
	"PRODUCT_CODE" NVARCHAR2(100), 
	"CUSTOMER_NUMBER" NVARCHAR2(100), 
	"BI_COLLECTABILITY" NUMBER(10,0), 
	"BI_COLLECT_CIF" NUMBER(10,0), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"DPD_CIF" NUMBER(10,0), 
	"DPD_FINAL" NUMBER(10,0), 
	"WO_FLAG" NUMBER(10,0), 
	"WO_FLAG_CIF" NUMBER(10,0), 
	"RESTRU_SIFAT_FLAG" NUMBER(10,0), 
	"RESTRU_SIFAT_FLAG_CIF" NUMBER(10,0), 
	"FP_FLAG" NUMBER(10,0), 
	"EXCHANGE_RATE" BINARY_DOUBLE, 
	"PLAFOND" NUMBER(32,6), 
	"OUTSTANDING" NUMBER(32,6), 
	"MARGIN_RATE" BINARY_DOUBLE, 
	"EIR" BINARY_DOUBLE, 
	"DPD_FINAL_CIF" NUMBER(10,0), 
	"DATA_SOURCE" NVARCHAR2(50), 
	"SUB_SEGMENT" NVARCHAR2(50), 
	"FP_FLAG_ORIG" NUMBER(10,0), 
	"FACILITY_NUMBER" NVARCHAR2(100), 
	"FLAG_RESTRU_COVID19" NUMBER(10,0), 
	"SURVIVE_FLAG" NUMBER(10,0), 
	"FLAG_RESTRU_COVID19_CIF" NUMBER(10,0), 
	"SURVIVE_FLAG_CIF" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
