CREATE TABLE "PSAK413"."IFRS_PD_TRANS_MATRIX_CONFIG" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"TM_RULE_NAME" NVARCHAR2(250), 
	"SEGMENTATION_ID" NUMBER(20,0), 
	"PD_METHOD" NVARCHAR2(50) NOT NULL ENABLE, 
	"CALC_METHOD" NVARCHAR2(20), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"EXPECTED_LIFE" NUMBER(5,0), 
	"INCREMENT_PERIOD" NUMBER(5,0), 
	"HISTORICAL_DATA" NUMBER(5,0), 
	"TRANSITION_DATA" NUMBER(5,0), 
	"POPULATION_MONTH" NVARCHAR2(50), 
	"IA_FLAG" NUMBER(10,0), 
	"THRESHOLD" NUMBER(32,6), 
	"CUT_OFF_DATE" DATE, 
	"MIG_LOSS_BUCKET" NUMBER(5,0), 
	"VIN_START_YEAR" NVARCHAR2(10), 
	"VIN_END_YEAR" NVARCHAR2(10), 
	"VIN_AVG_METHOD" NVARCHAR2(10), 
	"ACTIVE_FLAG" NUMBER(10,0), 
	"DERIVED_TM_MODEL" NUMBER(20,0), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_NEW" NUMBER(10,0), 
	"IS_DELETE" NUMBER(10,0), 
	 CONSTRAINT "PK_IFRS_PD_TRANS_MATRIX_CONFIG" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
