CREATE TABLE "PSAK413"."IFRS_CUSTOMER_GRADING_CORP" 
   (	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"SANDI_BANK" NVARCHAR2(10), 
	"OBLIGOR_GRADE" NVARCHAR2(5), 
	"JAP_NON_JAP_IDENTIFIER" NCHAR(1), 
	"WATCH_LIST_FLAG" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(100) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
