CREATE TABLE "PSAK413"."IFRS_STG_MASTER_ACCOUNT_TRSBND" 
   (	"DOWNLOAD_DATE" NVARCHAR2(20), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"DEAL_NO" NVARCHAR2(50), 
	"ACCOUNT_STATUS" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(50), 
	"SECURITY_CODE" NVARCHAR2(50), 
	"AMOUNT" NVARCHAR2(50), 
	"CURRENCY" NCHAR(3), 
	"MARGIN_RATE" NVARCHAR2(50), 
	"PURPOSE" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"START_DATE" NVARCHAR2(20), 
	"MATURITY_DATE" NVARCHAR2(20), 
	"MTM_PRICE" NVARCHAR2(50), 
	"EXRATE_TO_LCY" NVARCHAR2(50), 
	"BANK_NON_BANK" NVARCHAR2(50), 
	"LAST_INTEREST_DATE" NVARCHAR2(20), 
	"NEXT_INTEREST_DATE" NVARCHAR2(20), 
	"PREMIUM_DISCOUNT_AMOUNT" NVARCHAR2(50), 
	"CARRYING_AMOUNT" NVARCHAR2(50), 
	"FAIR_VALUE_BALANCE" NVARCHAR2(50), 
	"UNREALIZED_GAIN_LOSS_AMOUNT" NVARCHAR2(50), 
	"BRANCH_CODE" NVARCHAR2(50), 
	"RESIDENT_GROUP" NVARCHAR2(50), 
	"BI_CODE" NVARCHAR2(20), 
	"AL_FLAG" NCHAR(1), 
	"DEPT_UNIT" NVARCHAR2(50), 
	"EXTERNAL_RATING" NVARCHAR2(50), 
	"EXTERNAL_RATING_DATE" NVARCHAR2(20), 
	"EXTERNAL_RATING_INST" NVARCHAR2(20), 
	"FILENAME" NVARCHAR2(100), 
	"SOURCE_PROCESS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
