CREATE TABLE "PSAK413"."IFRS_IMP_OVERRIDE_HISTORY" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"OVERRIDE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"MASTER_ACCOUNT_ID" NVARCHAR2(75), 
	"BI_COLLECTABILITY" NUMBER(5,0), 
	"RATING_CODE" NVARCHAR2(5), 
	"PRODUCT_ENTITY" NCHAR(1), 
	"CURRENCY" NVARCHAR2(5), 
	"OUTSTANDING" NUMBER(32,6), 
	"IPW_AMOUNT" NUMBER(32,6), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"IMPAIRED_FLAG" NCHAR(1), 
	"REMARKS" NVARCHAR2(2000), 
	"DCFSTATUS" NVARCHAR2(1), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"AQAD_TYPE" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
