CREATE TABLE "PSAK413"."IFRS_EIL_INDIVIDUAL" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(50), 
	"EIL_AMOUNT" NUMBER(32,6), 
	"EIL_AMOUNT_BFL" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
