CREATE TABLE "PSAK413"."IFRS_EAD_RULES_CONFIG" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"EAD_RULE_NAME" NVARCHAR2(100) NOT NULL ENABLE, 
	"SEGMENTATION_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EAD_BALANCE" NVARCHAR2(250) NOT NULL ENABLE, 
	"CCF_FLAG" NUMBER(10,0), 
	"CCF_RULES_ID" NVARCHAR2(100), 
	"PREPAYMENT_FLAG" NUMBER(10,0), 
	"PREPAYMENT_RULES_ID" NVARCHAR2(100), 
	"ACTIVE_FLAG" NUMBER(10,0) DEFAULT 0, 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "IFRS_EAD_RULES_CONFIG_PKEY" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
