CREATE TABLE "PSAK413"."IFRS_STG_HOLIDAY" 
   (	"DOWNLOAD_DATE" NVARCHAR2(20), 
	"DESCRIPTION" NVARCHAR2(50), 
	"HOLIDAY_DATE" NVARCHAR2(20), 
	"FILENAME" NVARCHAR2(100), 
	"SOURCE_PROCESS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
