CREATE TABLE "PSAK413"."IFRS_LBM_LOAN_REPORT_RECON" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"UNAMORT_MASTER_ACCOUNT" NUMBER(32,6), 
	"INITIAL_BENEFIT_AMT" NUMBER(32,6), 
	"INITIAL_FAIR_VALUE_AMT" NUMBER(32,6), 
	"UNAMORT_BENEFIT_AMT" NUMBER(32,6), 
	"UNAMORT_FAIR_VALUE_AMT" NUMBER(32,6), 
	"AMORT_BENEFIT_AMT" NUMBER(32,6), 
	"AMORT_FAIR_VALUE_AMT" NUMBER(32,6), 
	"COUNTER_CHECK_BENEFIT" NUMBER(32,6), 
	"COUNTER_CHECK_FAIR_VALUE" NUMBER(32,6), 
	"COUNTER_CHECK_MOVEMENT_BENEFIT" NUMBER(32,6), 
	"COUNTER_CHECK_MOVEMENT_FAIR_VALUE" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
