CREATE TABLE "PSAK413"."IFRS_PD_CHR_GAMMA_PARAM" 
   (	"DOWNLOAD_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_ID" NUMBER(5,0), 
	"ALPHA_PARAM" BINARY_DOUBLE, 
	"BETA_PARAM" BINARY_DOUBLE, 
	"CONVERGENCE_VALUE" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
