CREATE TABLE "PSAK413"."IFRS_ME_FORECAST_HIST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"ME_CODE" NVARCHAR2(100) NOT NULL ENABLE, 
	"METHOD" NVARCHAR2(50) NOT NULL ENABLE, 
	"FL_PERIOD" NUMBER(10,0), 
	"FL_PERIOD_FROM" DATE, 
	"FL_PERIOD_TO" DATE, 
	"INPUT" NUMBER(10,0), 
	"APPROVAL_REMARKS" NCLOB, 
	"STATUS" NVARCHAR2(10), 
	"ACTION" NVARCHAR2(20), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("APPROVAL_REMARKS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
/
