CREATE TABLE "PSAK413_BSI"."IFRS_PD_RULES_CONFIG_S_00000_0000" 
   (	"PKID" NUMBER(19,0) NOT NULL ENABLE, 
	"SYSCODE_PD" VARCHAR2(22) NOT NULL ENABLE, 
	"PD_RULE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SEGMENTATION_ID" VARCHAR2(22) NOT NULL ENABLE, 
	"PD_METHOD" VARCHAR2(100) NOT NULL ENABLE, 
	"START_HISTORICAL_DATE" DATE, 
	"CALC_METHOD" VARCHAR2(100), 
	"HISTORICAL_DATA" NUMBER(19,0), 
	"EXPECTED_LIFE" NUMBER(19,0), 
	"INCLUDE_INDIVIDUAL_ACCOUNT" NUMBER(1,0), 
	"INCLUDE_WO" NUMBER(1,0), 
	"INCLUDE_CLOSE" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"CREATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	"DEFAULT_RATIO_BY" VARCHAR2(50), 
	"DEFAULT_RULE_ID" NUMBER(19,0), 
	"BUCKET_GROUP" VARCHAR2(22), 
	"ME_CODE" VARCHAR2(50), 
	"PERIOD_START_DATE" DATE, 
	"PERIOD_END_DATE" DATE, 
	"IS_DELETED" NUMBER(1,0), 
	"INCREMENT_PERIOD" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
