CREATE TABLE "PSAK413"."IFRS_PD_MAA_FLOWRATE_SMOOTH" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"BUCKET_GROUP" VARCHAR2(30), 
	"BUCKET_FROM" NUMBER, 
	"BUCKET_TO" NUMBER, 
	"FLOWRATE" NUMBER, 
	"SMOOTHED_PD" NUMBER, 
	"LOGIT_ODR" NUMBER, 
	"PREDICTED_LOGIT_ODR" NUMBER, 
	"PREDICTED_PD" NUMBER, 
	"FLOWRATE_SMOOTH_PD" NUMBER, 
	"CREATEDBY" VARCHAR2(30), 
	"CRATEDDATE" DATE, 
	"CREATEDHOST" VARCHAR2(36), 
	"UPDATEDBY" VARCHAR2(30), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(36)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
