CREATE TABLE "PSAK413"."IFRS_LI_PAYM_SCHD" 
   (	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(70), 
	"PMTDATE" DATE, 
	"MARGIN_RATE" NUMBER(12,6), 
	"OSPRN" NUMBER(32,6), 
	"PRINCIPAL" NUMBER(32,6), 
	"MARGIN" NUMBER(32,6), 
	"DISB_PERCENTAGE" NUMBER(12,6), 
	"DISB_AMOUNT" NUMBER(32,6), 
	"PLAFOND" NUMBER(32,6), 
	"I_DAYS" NUMBER(20,0), 
	"COUNTER" NUMBER(20,0), 
	"ICC" NVARCHAR2(1), 
	"OUTSTANDING" NUMBER(32,6), 
	"OUTSTANDING_KTL" NUMBER(32,6), 
	"DOWNLOAD_DATE" DATE, 
	"DATA_SOURCE" NVARCHAR2(20), 
	"SCH_FLAG" NVARCHAR2(2), 
	"GRACE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
