CREATE TABLE "PSAK413"."IFRS_LGD_LGW_HEADER" 
   (	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER(20,0), 
	"EQV_AT_DEFAULT" NUMBER(32,6), 
	"EQV_WO" NUMBER(32,6), 
	"NPV_EQV_WO" NUMBER(32,6), 
	"EQV_REC_WO" NUMBER(32,6), 
	"NPV_EQV_REC_WO" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"NPV_EQV_REC_OS" NUMBER(32,6), 
	"LGW" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
