CREATE TABLE "PSAK413_BSI"."IFRS_LGD_DATA2" 
   (	"PKID" NUMBER NOT NULL ENABLE, 
	"LGD_RULE_ID" NUMBER(20,0), 
	"DEFAULT_DATE" DATE, 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"MASTERID" NUMBER(20,0), 
	"CURRENCY" VARCHAR2(5), 
	"ACCOUNT_STATUS" VARCHAR2(1), 
	"CURE_FLAG" NUMBER(10,0), 
	"CURED_DATE" DATE, 
	"WO_DATE" DATE, 
	"CLOSED_DATE" DATE, 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"EQV_AT_DEFAULT" NUMBER(32,6), 
	"OS_WO" NUMBER(32,6), 
	"EQV_WO" NUMBER(32,6), 
	"EIR_AT_DEFAULT" FLOAT(126), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
