CREATE TABLE "PSAK413"."IFRS_TMP_PAYM_SCHD" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"PAYMENT_DATE" DATE, 
	"OUTSTANDING_AMT" NUMBER(32,6), 
	"PRINCIPAL_AMT" NUMBER(32,6), 
	"MARGIN_AMT" NUMBER(32,6), 
	"FACILITY_ID" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
