CREATE TABLE "PSAK413"."IFRS_TRANSACTION_DAILY" 
   (	"DOWNLOAD_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"MATURITY_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"BRANCH_CODE" NVARCHAR2(20), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"PRD_TYPE" NVARCHAR2(50), 
	"PRD_CODE" NVARCHAR2(20), 
	"TRX_CODE" NVARCHAR2(20), 
	"CCY" NVARCHAR2(3), 
	"EVENT_CODE" NVARCHAR2(50), 
	"TRX_REFERENCE_NUMBER" NVARCHAR2(100), 
	"ORG_CCY_AMT" NUMBER(32,6), 
	"EQV_LCY_AMT" NUMBER(32,6), 
	"DEBET_CREDIT_FLAG" NVARCHAR2(1), 
	"TRX_SOURCE" NVARCHAR2(50), 
	"INTERNAL_NO" NVARCHAR2(70), 
	"REVOLVING_FLAG" NVARCHAR2(3), 
	"CREATED_DATE" TIMESTAMP (8), 
	"SOURCE_TABLE" NVARCHAR2(100), 
	"TRX_LEVEL" NVARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
