CREATE TABLE "PSAK413"."IFRS_LI_EIR_ADJUSTMENT" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"IFRS9_CLASS" NVARCHAR2(50), 
	"LOAN_START_DATE" DATE, 
	"LOAN_DUE_DATE" DATE, 
	"OUTSTANDING" NUMBER(32,6), 
	"MARGIN_RATE" NUMBER(32,6), 
	"EIR" NUMBER(32,6), 
	"FAIR_VALUE_AMT" NUMBER(32,6), 
	"MARKET_RATE" NUMBER(32,6), 
	"TOTAL_PV_CF" NUMBER(32,6), 
	"TOT_ADJUST" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
