CREATE TABLE "PSAK413"."IFRS_IAP_PARAM" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"SEGMENTATION_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MIN_OS_VALUE" NUMBER(18,0), 
	"COLLECTION_COST" BINARY_DOUBLE, 
	"WORKOUT_PERIOD_MODE" NVARCHAR2(50), 
	"LGD_RULE_ID" NUMBER(20,0), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
