CREATE TABLE "PSAK413_BSI"."IFRS_PD_VAS_TTC" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"BUCKET_GROUP" VARCHAR2(30), 
	"INT_RATING" VARCHAR2(10), 
	"EXT_RATING" VARCHAR2(10), 
	"BUCKET_ID" NUMBER(10,0), 
	"TTC_PD" FLOAT(126), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (6), 
	"CORRELATION" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
