CREATE TABLE "PSAK413"."IFRS_IMPC_BUCKET_PARAM" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_DESCRIPTION" NVARCHAR2(255), 
	"OPTION_GROUPING" NVARCHAR2(30), 
	"BUCKET_ID" NUMBER(5,0), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"SUB_BUCKET_GROUP" NVARCHAR2(30), 
	"RANGE_START" NUMBER(5,0), 
	"RANGE_END" NUMBER(5,0), 
	"FLAG_DEFAULT" NCHAR(1), 
	"PD_DEFAULT" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"ACTIVE_FLAG" NUMBER(10,0), 
	 CONSTRAINT "PK__IFRS_IMP__5E028272E99C1D27" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
