CREATE TABLE "PSAK413"."IFRS_ME_FORECAST_TEMP" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"ME_CODE" NVARCHAR2(100) NOT NULL ENABLE, 
	"METHOD" NVARCHAR2(50) NOT NULL ENABLE, 
	"FL_PERIOD" NUMBER(10,0), 
	"FL_PERIOD_FROM" DATE, 
	"FL_PERIOD_TO" DATE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0), 
	"ME_CODE_UPLOAD" NVARCHAR2(100), 
	 CONSTRAINT "PK_IFRS_FL_FORECAST_TEMP" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
