CREATE TABLE "PSAK413"."IFRS_MASTER_INIT_CUST_GRADE" 
   (	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" NVARCHAR2(100), 
	"SANDI_BANK" NVARCHAR2(10), 
	"INITIAL_RATING_CODE" NVARCHAR2(30), 
	"CUSTOMER_NAME" NVARCHAR2(500), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
