CREATE TABLE "PSAK413"."IFRS_LINREG_STATS" 
   (	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_SEQ" NUMBER(10,0), 
	"TEST_NAME" NVARCHAR2(255), 
	"TEST_DESCR" NVARCHAR2(255), 
	"STATS_VALUE" BINARY_DOUBLE, 
	"P_VALUE" BINARY_DOUBLE, 
	"NULL_HYPOTHESIS" NVARCHAR2(255), 
	"ALTER_HYPOTHESIS" NVARCHAR2(255), 
	"FINAL_RESULT" NVARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
