CREATE TABLE "PSAK413_BSI"."IMPORT_MEV" 
   (	"PERIODE" VARCHAR2(50), 
	"ME_CODE" VARCHAR2(50), 
	"ME_CODE_NTT" VARCHAR2(50), 
	"VALUE" NUMBER, 
	"SCENARIOTYPE" VARCHAR2(50), 
	"SCENARIONO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
