CREATE TABLE "PSAK413_BSI"."LIST_NASABAH_RESTRU_BENCANA" 
   (	"No. " NUMBER(*,0), 
	"NOLOAN" VARCHAR2(50), 
	"NOMORCIF" VARCHAR2(50), 
	"NAMA_NASABAH" VARCHAR2(64), 
	"NAMA_OUTLET_BSI" VARCHAR2(50), 
	"Kode_Outlet " VARCHAR2(50), 
	"AREA_BSI" VARCHAR2(50), 
	"REGIONAL_BSI" VARCHAR2(50), 
	"SEGMEN_BSI" VARCHAR2(50), 
	"PRODUK_BSI" VARCHAR2(50), 
	"NOMINALCKPN_DES" VARCHAR2(50), 
	"NOMINALCKPN_FEB" VARCHAR2(50), 
	"OS_PSAK_Des " VARCHAR2(50), 
	"OSPSAK_FEB" VARCHAR2(50), 
	"JENISPIUTANGPEMBIAYAAN" VARCHAR2(50), 
	"VALIDASI" VARCHAR2(50), 
	"BUCKET" VARCHAR2(50), 
	"NO_BUCKET" NUMBER(*,0), 
	"KETERANGAN" VARCHAR2(50), 
	"MASTERID" NUMBER(20,0), 
	"DOWNLOAD_DATE" DATE, 
	"EFFECTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
