CREATE TABLE "PSAK413"."LIST_WO_SKIP" 
   (	"MASTERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PRODUCT_CODE" NVARCHAR2(50), 
	"PRODUCT_TYPE" NVARCHAR2(50), 
	"PRODUCT_GROUP" NVARCHAR2(50), 
	"MAX_IMA" DATE, 
	"WRITEOFF_DATE" DATE, 
	"DOWNLOAD_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
