CREATE TABLE "PSAK413"."MAX_PD" 
   (	"OBLIGOR_GRADE" NVARCHAR2(5), 
	"DOWNLOAD_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
