CREATE TABLE "PSAK413"."MIR" 
   (	"DEAL_TYPE" NVARCHAR2(20), 
	"MARKET_INT_RATE" NVARCHAR2(10), 
	"DOWNLOAD_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
