CREATE TABLE "PSAK413"."STG_N3L_UNDRAWN" 
   (	"YMD" DATE, 
	"LIMIT_ID" NVARCHAR2(100), 
	"REPORT_LIMIT_ID" NVARCHAR2(100), 
	"LIMIT_PRODUCT" NVARCHAR2(100), 
	"LIMIT_CURRENCY" NVARCHAR2(3), 
	"LIMIT_CURRENCY_RATE" NUMBER(32,6), 
	"CIF_NO" NVARCHAR2(100), 
	"OLD_CIF_NUMBER" NVARCHAR2(100), 
	"EXPIRY_DATE" DATE, 
	"SECOND_AGREE_DT" DATE, 
	"STG_LIMIT_AMT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
