CREATE TABLE "PSAK413"."TBLM_USER" 
   (	"PKID" RAW(16) NOT NULL ENABLE, 
	"SCREENGROUPID" NUMBER(20,0) NOT NULL ENABLE, 
	"BRANCHGROUPID" NUMBER(20,0) NOT NULL ENABLE, 
	"USERNAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" NVARCHAR2(200) NOT NULL ENABLE, 
	"FULLNAME" NVARCHAR2(100) NOT NULL ENABLE, 
	"DEPARTEMENTGROUP" NVARCHAR2(50), 
	"EFFECTIVESTARTDATE" TIMESTAMP (8), 
	"EFFECTIVEENDDATE" TIMESTAMP (8), 
	"PASSWORDATTEMPTCOUNTER" NUMBER(10,0), 
	"PASSWORDEXPIREDDATE" TIMESTAMP (8), 
	"PASSWORDLASTUPDATEDDATETIME" TIMESTAMP (8), 
	"LASTLOGINDATE" TIMESTAMP (8), 
	"ISUSEREXPIRED" NUMBER(10,0), 
	"ISPASSWORDEXPIRED" NUMBER(10,0), 
	"ISUSERLOCKED" NUMBER(10,0), 
	"ISUSERACTIVE" NUMBER(10,0), 
	"COUNTRYID" NVARCHAR2(10), 
	"NPK" NVARCHAR2(50) NOT NULL ENABLE, 
	"THEME" NVARCHAR2(50), 
	"LOCKEDREASON" NVARCHAR2(50), 
	"CREATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLM_USER" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
