CREATE TABLE "PSAK413"."TBLT_APPLICATIONLOG" 
   (	"THREADID" NVARCHAR2(36) NOT NULL ENABLE, 
	"JOBID" NUMBER(20,0), 
	"MESSAGE" NVARCHAR2(2000), 
	"START" TIMESTAMP (8), 
	"FINISH" TIMESTAMP (8), 
	"STATUS" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
