CREATE TABLE "PSAK413"."TBLU_RETAIL_EAD" 
   (	"EAD_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_TYPE" NVARCHAR2(50) NOT NULL ENABLE, 
	"REMAINING_TENOR" NUMBER(10,0) NOT NULL ENABLE, 
	"EAD_YEAR" NUMBER(10,0) NOT NULL ENABLE, 
	"EAD_RATE" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLU_RETAIL_EAD" PRIMARY KEY ("EAD_DATE", "PRODUCT_TYPE", "REMAINING_TENOR", "EAD_YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
