CREATE TABLE "PSAK413"."TBLU_MARKET_INT_RATE" 
   (	"DOWNLOAD_DATE" NVARCHAR2(10), 
	"DEAL_TYPE" NVARCHAR2(20), 
	"MARKET_INT_RATE" NVARCHAR2(10), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
