CREATE TABLE "PSAK413"."TBLU_ASSET_CLASSIFICATION_CORP" 
   (	"DOWNLOAD_DATE" NVARCHAR2(8), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"SPPI_RESULT" NVARCHAR2(100), 
	"BM_RESULT" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(100) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20) DEFAULT 'LOCALHOST'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
