CREATE TABLE "PSAK413"."TBLU_EAD_CCF" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"ASSET_TYPE_PRODUCT1" NVARCHAR2(100) NOT NULL ENABLE, 
	"ASSET_TYPE_PRODUCT2" NVARCHAR2(100) NOT NULL ENABLE, 
	"ORIGINAL_TENOR_LOW" NUMBER(10,2) NOT NULL ENABLE, 
	"ORIGINAL_TENOR_HIGH" NUMBER(10,2) NOT NULL ENABLE, 
	"CCF" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLU_EAD_CCF" PRIMARY KEY ("EFF_DATE", "ASSET_TYPE_PRODUCT1", "ASSET_TYPE_PRODUCT2", "ORIGINAL_TENOR_LOW", "ORIGINAL_TENOR_HIGH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
