CREATE TABLE "PSAK413"."TBLU_NOSTRO_SWIFTCODE" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"BRANCH_CODE" NVARCHAR2(20) NOT NULL ENABLE, 
	"LINE" NVARCHAR2(20) NOT NULL ENABLE, 
	"GL" NVARCHAR2(10) NOT NULL ENABLE, 
	"CURRENCY" NCHAR(3) NOT NULL ENABLE, 
	"SWIFT_CODE" NVARCHAR2(20), 
	"BANK_NAME" NVARCHAR2(100), 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLU_NOSTRO_SWIFTCODE_1" PRIMARY KEY ("EFF_DATE", "BRANCH_CODE", "LINE", "GL", "CURRENCY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
