CREATE TABLE "PSAK413"."TBLU_RETAIL_LGD" 
   (	"LGD_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_TYPE" NVARCHAR2(50) NOT NULL ENABLE, 
	"LGD_SEGMENT" NVARCHAR2(100) NOT NULL ENABLE, 
	"LGD_RATE" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLU_RETAIL_LGD" PRIMARY KEY ("LGD_DATE", "PRODUCT_TYPE", "LGD_SEGMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
