CREATE TABLE "PSAK413"."TBLU_RECOVERY" 
   (	"DOWNLOAD_DATE" NVARCHAR2(8), 
	"DEFAULT_DATE" NVARCHAR2(8), 
	"OS_AT_DEFAULT" NVARCHAR2(20), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"PRODUCT_GROUP" NVARCHAR2(5), 
	"CURRENCY" NVARCHAR2(10), 
	"RECOVERY_DATE" NVARCHAR2(8), 
	"NETT_RECOVERY" NVARCHAR2(20), 
	"OEIR_AT_DEFAULT" NVARCHAR2(200), 
	"JAP_NON_JAP_IDENTIFIER" NCHAR(1), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
