CREATE TABLE "PSAK413"."TBLU_LGD_EXTERNAL_RECOVERY" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"LIEN_POSITION" NVARCHAR2(100) NOT NULL ENABLE, 
	"RECOVERY_RATE" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
