CREATE TABLE "PSAK413"."TMP_B2" 
   (	"MASTERID" NVARCHAR2(100), 
	"NPV_SUM" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
