CREATE TABLE "PSAK413"."TMP_JOURNAL" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCTNO" NVARCHAR2(70), 
	"DATASOURCE" NVARCHAR2(20), 
	"PRDTYPE" NVARCHAR2(50), 
	"PRDCODE" NVARCHAR2(20), 
	"TRXCODE" NVARCHAR2(20), 
	"BRANCH" NVARCHAR2(20), 
	"CCY" NVARCHAR2(10), 
	"JOURNALCODE" NVARCHAR2(20), 
	"DRCR" NVARCHAR2(2), 
	"FLAG_CF" NVARCHAR2(3), 
	"REVERSE" NVARCHAR2(3), 
	"VALCTR_CODE" NVARCHAR2(10), 
	"GLNO" NVARCHAR2(20), 
	"ORG_AMOUNT" NUMBER(32,6) DEFAULT 0, 
	"IDR_AMOUNT" NUMBER(32,6) DEFAULT 0, 
	"CLS_AMOUNT" NUMBER(32,6) DEFAULT 0, 
	"ACT_AMOUNT" NUMBER(32,6) DEFAULT 0, 
	"ORG_AMOUNT_SL" NUMBER(32,6) DEFAULT 0, 
	"IDR_AMOUNT_SL" NUMBER(32,6) DEFAULT 0, 
	"METHOD" NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
