CREATE TABLE "PSAK413"."TMP_IFRS_PD_MAA_CORP_DETAIL" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"BASE_DATE" DATE NOT NULL ENABLE, 
	"TO_DATE" DATE NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"SEGMENT" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"PD_UNIQUE_ID" NVARCHAR2(50), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"CALC_METHOD" NVARCHAR2(50), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"OUTSTANDING" NUMBER(32,6), 
	"BUCKET_TO_ORIG" NUMBER(5,0), 
	"BUCKET_FROM_NAME" NVARCHAR2(100), 
	"BUCKET_TO_NAME" NVARCHAR2(100), 
	"NEXT_DEFAULT_FLAG" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
