CREATE TABLE "PSAK413"."TMP_CFID2" 
   (	"MASTERID" NVARCHAR2(100), 
	"CF_ID" NUMBER(20,0), 
	"ITRCG_AMT" NUMBER(32,6), 
	"AMORT_AMT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
