CREATE TABLE "PSAK413_BSI"."TMP_IFRS_MASTER_ACCOUNT_PD_S_00000_0000" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(20,0), 
	"MASTERID" VARCHAR2(100) NOT NULL ENABLE, 
	"CUSTOMER_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(20), 
	"OUTSTANDING" NUMBER(32,6), 
	"CALC_METHOD" VARCHAR2(50), 
	"BI_COLLECTABILITY" NUMBER(10,0), 
	"RATING_CODE" VARCHAR2(10), 
	"EXT_RATING_CODE" VARCHAR2(50), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"DAY_PAST_DUE_CIF" NUMBER(20,0), 
	"EXCHANGE_RATE" FLOAT(126), 
	"IMPAIRED_FLAG" NCHAR(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
