CREATE TABLE "PSAK413_BSI"."TMP_PD_CLOSE" 
   (	"PD_RULE_ID" NUMBER(19,0), 
	"PD_UNIQUE_ID" VARCHAR2(100), 
	"PREVDATE" DATE, 
	"CURRDATE" DATE, 
	"CALC_METHOD" VARCHAR2(20), 
	"DEFAULT_RULE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
