CREATE TABLE "PSAK413"."TMP_IFRS_MODEL_FILTER_CORTEST" 
   (	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"CORRELATION_VAL" BINARY_DOUBLE, 
	"VARIABLENAME" NVARCHAR2(255), 
	"EXPECTED_TREND" NVARCHAR2(20), 
	"IN_SAMPLE_SET" NUMBER(10,0), 
	"CORR_SIGN" NCHAR(1), 
	"CORR_GT_FLG" NCHAR(1), 
	"PASS" NUMBER(10,0), 
	"VARIABLE_SELECTION" NUMBER(10,0), 
	"LOOKUPINITIAL" NVARCHAR2(20), 
	"CORRTEST_STAT" BINARY_DOUBLE, 
	"CORRTEST_PVAL" BINARY_DOUBLE, 
	"TRANSFORM_C" NUMBER(10,0), 
	"TRANSFORM_M" NUMBER(10,0), 
	"SUM_TRANSFORM" NUMBER(10,0), 
	"ABS_CORRELATION" BINARY_DOUBLE, 
	"ADJ_CORRELATION" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
