CREATE TABLE "PSAK413"."TMP_IFRS_ODR_DATA" 
   (	"PD_RULE_ID" NUMBER(20,0), 
	"EFF_DATE" DATE, 
	"ODR" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
