CREATE TABLE "PSAK413"."TMP_CCF_RULES_CONFIG" 
   (	"PKID" NUMBER(20,0), 
	"CCF_RULE_NAME" NVARCHAR2(250), 
	"SEGMENTATION_ID" NUMBER(20,0), 
	"CALC_METHOD" NVARCHAR2(20), 
	"AVERAGE_METHOD" NVARCHAR2(20), 
	"CUT_OFF_DATE" DATE, 
	"CCF_OVERRIDE" BINARY_DOUBLE, 
	"LAG_1MONTH_FLAG" NUMBER(10,0), 
	"OBSERV_PERIOD_MOVING" NUMBER(10,0), 
	"OS_DEF_ZERO_EXCLUDE" NUMBER(10,0), 
	"HEADROOM_ZERO_EXCLUDE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
