CREATE TABLE "PSAK413"."TMP_LI_T11" 
   (	"MASTERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"SEQ" NVARCHAR2(3), 
	"CURRDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
