CREATE TABLE "PSAK413"."TMP_MARKETRATE" 
   (	"EFF_DATE" DATE, 
	"PRD_CODE" NVARCHAR2(20), 
	"MKT_RATE" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
