CREATE TABLE "PSAK413"."TMP_IFRS_PD_CHR_BASE_DATA" 
   (	"DOWNLOAD_DATE" DATE, 
	"PROJECTION_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0), 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"PD_UNIQUE_ID" NVARCHAR2(100), 
	"SEGMENT" NVARCHAR2(50), 
	"CALC_METHOD" NVARCHAR2(5), 
	"BUCKET_ID" NUMBER(5,0), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"OUTSTANDING" NUMBER(32,6), 
	"DEFAULT_FLAG" NUMBER(10,0), 
	"BI_COLLECTABILITY" NUMBER(5,0), 
	"RATING_CODE" NVARCHAR2(30), 
	"DAY_PAST_DUE" NUMBER(5,0), 
	"NEXT_12M_DEFAULT_FLAG" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
