CREATE TABLE "PSAK413"."TMP_IFRS_VARCLUS_CLUSTER_DTL" 
   (	"MODEL_ID" NUMBER(20,0), 
	"CLUSTER" NUMBER(5,0), 
	"VARIABLENAME" NVARCHAR2(200), 
	"PC1" BINARY_DOUBLE, 
	"PC2" BINARY_DOUBLE, 
	"R_SQUARE_OWN" BINARY_DOUBLE, 
	"R_SQUARE_NEXT" BINARY_DOUBLE, 
	"R_SQUARE_RATIO" BINARY_DOUBLE, 
	"VAR_IDX" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
