CREATE TABLE "PSAK413_BSI"."TMP_SCENARIO_DATA" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" VARCHAR2(100), 
	"PD_RULE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"RULE_ID" NUMBER(18,0), 
	"SEGMENT" VARCHAR2(50), 
	"SUB_SEGMENT" VARCHAR2(50), 
	"GROUP_SEGMENT" VARCHAR2(50), 
	"RULE_TYPE" VARCHAR2(50), 
	"RATING_CODE" VARCHAR2(30), 
	"DAY_PAST_DUE" NUMBER(5,0), 
	"DPD_CIF" NUMBER(19,0), 
	"BI_COLLECTABILITY" NUMBER(3,0), 
	"WRITEOFF_FLAG" NUMBER(1,0), 
	"KEY_TMP_IMA" VARCHAR2(100), 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(2), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NAME" VARCHAR2(100), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"IMPAIRED_FLAG" VARCHAR2(1), 
	"OUTSTANDING" NUMBER(32,6), 
	"FAIR_VALUE_AMOUNT" NUMBER(32,6), 
	"EARLY_ALERT_FLAG" NUMBER(1,0), 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"CUSTOMER_GRADE" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
