CREATE TABLE "PSAK413"."TMP_SCHEDULE_MAIN_MTM" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(70), 
	"BRANCH_CODE" NVARCHAR2(20), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"START_DATE" DATE, 
	"DUE_DATE" DATE, 
	"START_AMORTIZATION_DATE" DATE, 
	"END_AMORTIZATION_DATE" DATE, 
	"FIRST_PMT_DATE" DATE, 
	"CURRENCY" NVARCHAR2(3), 
	"OUTSTANDING" NUMBER(32,6), 
	"PLAFOND" NUMBER(32,6), 
	"HOLD_AMOUNT" NUMBER(32,6), 
	"MARGIN_RATE" NUMBER(12,6), 
	"TENOR" NUMBER(10,0), 
	"PAYMENT_TERM" NVARCHAR2(1), 
	"PAYMENT_CODE" NVARCHAR2(20), 
	"MARGIN_CALCULATION_CODE" NVARCHAR2(1), 
	"NEXT_PMTDATE" DATE, 
	"NEXT_COUNTER_PAY" NUMBER(10,0), 
	"SCH_FLAG" NVARCHAR2(2), 
	"GRACE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
