CREATE TABLE "PSAK413_BSI"."TMP_IFRS_SCN_GENERATE_QUERY_S_00000_0000" 
   (	"ID" NUMBER, 
	"RULE_ID" NUMBER, 
	"SEQUENCE" NUMBER, 
	"SEGMENT_TYPE" VARCHAR2(50), 
	"TABLE_NAME" VARCHAR2(100), 
	"CONDITION" VARCHAR2(4000), 
	"DATA_DATE" DATE, 
	"SEGMENT" VARCHAR2(50), 
	"SUB_SEGMENT" VARCHAR2(50), 
	"GROUP_SEGMENT" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
