CREATE TABLE "PSAK413"."TMP_T13" 
   (	"MASTERID" NVARCHAR2(100), 
	"N_EFF_INT_RATE" NUMBER(18,10), 
	"ENDAMORTDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
