CREATE TABLE "PSAK413"."TMP_SCHEDULE_PREV_HIST" 
   (	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(70), 
	"MARGIN_RATE" NUMBER(12,6) DEFAULT 0, 
	"PMTDATE" DATE, 
	"OSPRN" NUMBER(32,6) DEFAULT 0, 
	"PRINCIPAL" NUMBER(32,6) DEFAULT 0, 
	"MARGIN" NUMBER(32,6) DEFAULT 0, 
	"DISB_PERCENTAGE" NUMBER(32,6) DEFAULT 0, 
	"DISB_AMOUNT" NUMBER(32,6) DEFAULT 0, 
	"PLAFOND" NUMBER(32,6) DEFAULT 0, 
	"I_DAYS" NUMBER(20,0) DEFAULT 0, 
	"COUNTER" NUMBER(10,0) DEFAULT 0, 
	"DATE_START" DATE, 
	"DATE_END" DATE, 
	"TENOR" NUMBER(10,0) DEFAULT 0, 
	"PAYMENT_CODE" NVARCHAR2(20), 
	"ICC" NVARCHAR2(1), 
	"NEXT_PMTDATE" DATE, 
	"NEXT_COUNTER_PAY" NUMBER(10,0), 
	"SCH_FLAG" NVARCHAR2(2), 
	"GRACE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
