CREATE TABLE "PSAK413"."TMP_U1" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"N_UNAMORT_FEE" NUMBER(32,6), 
	"N_UNAMORT_COST" NUMBER(32,6), 
	"ECFDATE" DATE, 
	"ENDAMORTDATE" DATE, 
	"ACCTNO" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
