CREATE TABLE "PSAK413_BSI"."TMP_PD_DATE_RUN_S_00000_0000" 
   (	"PERIOD" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
