CREATE TABLE "PSAK413"."TMP_B1" 
   (	"MASTERID" NVARCHAR2(100), 
	"N_OSPRN" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
