CREATE TABLE "PSAK413"."TMP_LI_AP" 
   (	"MASTERID" NVARCHAR2(100), 
	"FLAG_CF" NVARCHAR2(5), 
	"AMOUNT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
