CREATE TABLE "PSAK413"."TMP_IFRS_MULT_LINEAR_REGR_COEF" 
   (	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_SEQ" NUMBER(10,0), 
	"COEFF_NAME" NVARCHAR2(255), 
	"ESTIMATE_VAL" BINARY_DOUBLE, 
	"STD_ERROR" BINARY_DOUBLE, 
	"T_VALUE" BINARY_DOUBLE, 
	"PR_GT_T_VAL" BINARY_DOUBLE, 
	"SIG_FLAG" NVARCHAR2(255), 
	"SIG_LEVEL" NVARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
