CREATE TABLE "PSAK413"."TMP_IFRS_MACRO_ECONOMIC_MODEL" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_NAME" NVARCHAR2(100), 
	"PRC_DATE" DATE, 
	"REGRESSION_TYPE" NVARCHAR2(50), 
	"EXPONENT_VALUE" NUMBER(10,0), 
	"CUT_OFF_DATE" DATE, 
	"CORRELATION_TYPE" NVARCHAR2(50), 
	"CORRELATION_FILTER_VALUE" BINARY_DOUBLE, 
	"MAX_CLUSTER" NUMBER(10,0), 
	"EIGEN_VALUE_THRESHOLD" BINARY_DOUBLE, 
	"SIGNIFICANT_VARIABLE_VALUE" BINARY_DOUBLE, 
	"ADJUSTED_R_SQUARE_VALUE" BINARY_DOUBLE, 
	"VIF_VALUE" BINARY_DOUBLE, 
	"BACK_TEST_TOP_N_RESULT" NUMBER(10,0), 
	"ARIMA_THRESHOLD" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
