CREATE TABLE "PSAK413"."TMP_LI_T8" 
   (	"MASTERID" NVARCHAR2(100), 
	"DTMAX" DATE, 
	"CURRDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
