CREATE TABLE "PSAK413"."TMP_LOAN_REPORT" 
   (	"MASTERID" NVARCHAR2(100), 
	"INITIAL_FEE" NUMBER(32,6), 
	"INITIAL_COST" NUMBER(32,6), 
	"UNAMORT_FEE" NUMBER(32,6), 
	"UNAMORT_COST" NUMBER(32,6), 
	"AMORT_FEE" NUMBER(32,6), 
	"AMORT_COST" NUMBER(32,6), 
	"INITIAL_FEE_MTD" NUMBER(32,6), 
	"INITIAL_COST_MTD" NUMBER(32,6), 
	"AMORT_FEE_MTD" NUMBER(32,6), 
	"AMORT_COST_MTD" NUMBER(32,6), 
	"AMORT_FEE_YTD" NUMBER(32,6), 
	"AMORT_COST_YTD" NUMBER(32,6), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(50), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"CCY" NVARCHAR2(5), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"MARGIN_RATE" NUMBER(19,6), 
	"EIR" NUMBER(19,6), 
	"BRANCH_CODE" NVARCHAR2(20), 
	"OUTSTANDING" NUMBER(32,6), 
	"AMORT_TYPE" NVARCHAR2(10), 
	"UNAMORT_AMT_TOTAL" NUMBER(32,6), 
	"ACCUMULATIVE_ACCRUED" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
