CREATE TABLE "PSAK413_BSI"."X1" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER, 
	"BUCKET_GROUP" VARCHAR2(30), 
	"BUCKET_FROM" NUMBER, 
	"BUCKET_TO" NUMBER, 
	"FLOWRATE" NUMBER, 
	"SMOOTHED_PD" NUMBER, 
	"LOGIT_ODR" NUMBER, 
	"PREDICTED_LOGIT_ODR" NUMBER, 
	"PREDICTED_PD" NUMBER, 
	"PD_RESULT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
/
