CREATE TABLE "PSAK413_BSI"."X_IFRS_PD_TERM_STRUCTURE_20260316" 
   (	"PKID" NUMBER NOT NULL ENABLE, 
	"EFF_DATE" DATE NOT NULL ENABLE, 
	"BASE_DATE" DATE, 
	"SCENARIO_NO" NUMBER(10,0), 
	"PD_RULE_ID" NUMBER NOT NULL ENABLE, 
	"PD_RULE_NAME" VARCHAR2(255), 
	"MODEL_ID" NUMBER NOT NULL ENABLE, 
	"BUCKET_GROUP" VARCHAR2(100) NOT NULL ENABLE, 
	"BUCKET_ID" NUMBER(10,0), 
	"FL_SEQ" NUMBER(10,0), 
	"FL_YEAR" NUMBER(10,0), 
	"FL_MONTH" NUMBER(10,0), 
	"PD" BINARY_DOUBLE, 
	"PD_OVERRIDE" BINARY_DOUBLE, 
	"PD_METHOD" VARCHAR2(100), 
	"CREATEDBY" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATEDDATE" DATE NOT NULL ENABLE, 
	"CREATEDHOST" VARCHAR2(100) NOT NULL ENABLE, 
	"UPDATEDBY" VARCHAR2(100), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
