CREATE TABLE "PSAK413_BSI"."X_IFRS_LGD_UR_DETAIL3" 
   (	"PKID" NUMBER NOT NULL ENABLE, 
	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER, 
	"DEFAULT_DATE" DATE, 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"MASTERID" VARCHAR2(50), 
	"EIR_AT_DEFAULT" FLOAT(126), 
	"EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"REC_OS" NUMBER(32,6), 
	"NPV_EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"NPV_EQV_REC_OS" NUMBER(32,6), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"CCY" VARCHAR2(5), 
	"EXCHANGE_RATE" NUMBER(32,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
