CREATE TABLE "PSAK413_BSI"."X_IFRS_MASTER_ID_BACKUP" 
   (	"MASTERID" NUMBER(20,0) NOT NULL ENABLE, 
	"MASTER_ACCOUNT_CODE" NVARCHAR2(50) NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" NVARCHAR2(50) NOT NULL ENABLE, 
	"IAS_CLASS" NVARCHAR2(10) NOT NULL ENABLE, 
	"EFFDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (8) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/
