--1--SELECT COUNT(*) FROM IFRS_PAYM_SCHD_ALL
--2--SELECT COUNT(*) FROM IFRS_IMP_JOURNAL_DATA
--3--SELECT COUNT(*) FROM IFRS_LGD_CURE_LGL_HEADER
--4--SELECT COUNT(*) FROM IFRS_LGD_TERM_STRUCTURE
--5--SELECT COUNT(*) FROM IFRS_BUCKET_DETAIL
--6--SELECT COUNT(*) FROM IFRS_BUCKET_HEADER
--7--SELECT COUNT(*) FROM IFRS_SCENARIO_RULES_DETAIL
--8--SELECT COUNT(*) FROM IFRS_SCENARIO_RULES_HEADER
--9--SELECT COUNT(*) FROM IFRS_MSTR_SEGMENT_RULES_DETAIL
--10--SELECT COUNT(*) FROM IFRS_MSTR_SEGMENT_RULES_HEADER
--11--SELECT COUNT(*) FROM IFRS_ECL_RESULT_DETAIL
--12--SELECT COUNT(*) FROM IFRS_EAD_RESULT_NONPRK
--13--SELECT COUNT(*) FROM IFRS_ECL_MODEL_DETAIL_EAD
--14--SELECT COUNT(*) FROM IFRS_ECL_MODEL_DETAIL_LGD
--16--SELECT COUNT(*) FROM IFRS_ECL_MODEL_DETAIL_PD
--16--SELECT COUNT(*) FROM IFRS_ECL_MODEL_DETAIL_PF
--17--SELECT COUNT(*) FROM IFRS_ECL_MODEL_HEADER
--18--SELECT COUNT(*) FROM IFRS_IMP_PD_FL_TERM_YEARLY
--19--SELECT COUNT(*) FROM IFRS_IMP_PD_FL_TERM_STRUCTURE
--20--SELECT COUNT(*) FROM IFRS_PD_TERM_STRUCTURE_NOFL_YEARLY
--21--SELECT COUNT(*) FROM IFRS_PD_TERM_STRUCTURE_NOFL
--22--SELECT COUNT(*) FROM IFRS_MASTER_ACCOUNT_IMP



