CALL SP_IFRS_IMP_INITIAL_CONFIG(NULL, NULL, 'P');
---> RUNNING DAILY IMPAIRMENT
CALL SP_IFRS_IMP_INITIAL_UPDATE(NULL, NULL, 'P');
---> RUNNING MONTHLY IMPAIRMENT
---> CHECK STEP #1
CALL SP_IFRS_UPDATE_EIR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_SYNC_EXCLUSION(NULL, NULL, 'P'); ---> SP_IFRS_IMP_SYNC_RESTRU_COVID
CALL SP_IFRS_IMP_SYNC_WO_UPLOAD(NULL, NULL, 'P');
CALL SP_IFRS_IMPI_JOURNAL_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_FILL_IMA_PREV_CURR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_AVG_EIR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_INSERT_DEFAULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_DEFAULT_RULE(NULL, NULL, 'P'); ---> SP_IFRS_IMP_DEFAULT_RULE_NOLAG
CALL SP_IFRS_IMP_PD_SCENARIO_DATA(NULL, NULL, 'P'); ---> SP_IFRS_IMP_PD_SCENARIO_DATA_NOLAG
---> CHECK STEP #2
CALL SP_IFRS_IMP_DEFAULT_RATE(NULL, NULL, 'P'); ---> SP_IFRS_IMP_DEFAULT_RATE_NOLAG
CALL SP_IFRS_IMP_PD_CHR_SUMM(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_CHR_RESULT(NULL, NULL, 'P'); ---> SP_IFRS_IMP_PD_CHR_GAMMA_DIST
CALL SP_IFRS_IMP_PD_MAA_DETAIL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_ENR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_AVERAGE(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_MMULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_RESULT(NULL, NULL, 'P'); 
---> SP_IFRS_IMP_PD_MAA_CORP_DETAIL
---> SP_IFRS_IMP_PD_MAA_CORP_ENR
---> SP_IFRS_IMP_PD_MAA_CORP_AVERAGE
---> SP_IFRS_IMP_PD_MAA_CORP_FITTED
---> SP_IFRS_IMP_PD_MAA_CORP_MMULT
---> SP_IFRS_IMP_PD_MAA_CORP_RESULT
---> SP_IFRS_IMP_PD_MAA_CORP_EXTRAPOLATE
CALL SP_IFRS_IMP_PD_NFR_ENR(NULL, NULL, 'P');
---> SP_IFRS_IMP_PD_NFR_FLOWRATE
---> SP_IFRS_IMP_PD_NFR_FLOWLOSS
---> SP_IFRS_IMP_PD_NFR_RESULT
CALL SP_IFRS_IMP_PD_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_YEAR_TO_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_YEAR_TO_MONTH(NULL, NULL, 'P');

-- CALL SP_IFRS_IMP_BACKTEST_RESULT(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_UPDATE_WO_RECOVERY_PORTFOLIO(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_RECOVERY_SCENARIO_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_WO_SCENARIO_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_SCENARIO_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_CURE_LGL_DETAIL(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_CURE_LGL_HEADER(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_ER_SCENARIO_DATA_CORP(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_ER_DETAIL_CORP(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_LGD_ER_HEADER_CORP(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_CCF_SCENARIO_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_EAD_CCF_DETAIL(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_EAD_CCF_HEADER(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_SBLC_PRORATE(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_ECL_GENERATE_IMA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_DEFAULT_RULE_ECL(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_EXEC_RULE_STAGE(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_OVERRIDE_RESTRU_COVID(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_ECL_EAD_RESULT_NONPRK(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_ECL_EAD_RESULT_PRK(NULL, NULL, 'P');
-- CALL SP_IFRS_ECL_RESULT_DETAIL(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_SYNC_IMA_MONTHLY(NULL, NULL, 'P');
-- CALL SP_IFRS_IMPC_JOURNAL_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_GL_OUTBOUND(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_GL_OUTBOUND_SUMMARIZE(NULL, NULL, 'P');
-- CALL SP_IFRS_GL_OUTBOUND_SUMMARIZE(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_NOMINATIVE_OUTPUT(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_DASHBOARD_DATA(NULL, NULL, 'P');
-- CALL SP_IFRS_EXCEPTION_REPORT(NULL, NULL, 'P');