SELECT * FROM IFRS_MASTER_PRODUCT_PARAM WHERE PRD_CODE IN ('MAR',
'KPN',
'KRN',
'H1',
'LOC4')
-- 

-- SELECT DUPLICATE_TABLE('ifrs_master_account','ifrs_master_account_imp',FALSE)

SELECT DOWNLOAD_DATE, COUNT(*) FROM ifrs_master_account GROUP BY DOWNLOAD_DATE

SELECT * FROM IFRS_MSTR_SEGMENT_RULES_HEADER WHERE SEGMENT_TYPE = 'PORTFOLIO_SEGMENT'
AND SUB_SEGMENT IN ('MB',
'PUR - PENSION',
'PUR - PENSION',
'CORPORATE LOAN',
'CORPORATE LOAN')

SELECT * FROM IFRS_EAD_RULES_CONFIG WHERE PKID IN (5,
14)

SELECT * FROM IFRS_LGD_RULES_CONFIG WHERE PKID IN (32,
23,
33)

SELECT * FROM IFRS_PD_RULES_CONFIG WHERE PKID IN (3,
1,
1,
31,
31)

SELECT * FROM IFRS_ECL_MODEL_DETAIL_PD WHERE SEGMENTATION_ID IN (211,
3)

SELECT * FROM IFRS_ECL_MODEL_DETAIL_LGD WHERE SEGMENTATION_ID IN (211,
3)

SELECT * FROM IFRS_ECL_MODEL_DETAIL_EAD WHERE SEGMENTATION_ID IN (211,
3)

SELECT * FROM IFRS_ECL_MODEL_DETAIL_PF WHERE SEGMENTATION_ID IN (211,
3)

SELECT * FROM IFRS_BUCKET_HEADER WHERE BUCKET_GROUP IN ('DPD_CIF5_002',
'DPD_5_002',
'DPD_5_002',
'IR40_003',
'IR40_003')

SELECT BUCKET_ID FROM IFRS_BUCKET_DETAIL WHERE BUCKET_ID IN (3,4,38)

SELECT * FROM IFRS_SCENARIO_RULES_HEADER WHERE RULE_TYPE = 'STAGE'

SELECT DISTINCT RULE_ID FROM IFRS_SCENARIO_RULES_DETAIL WHERE RULE_ID IN (
SELECT PKID FROM IFRS_SCENARIO_RULES_HEADER WHERE RULE_TYPE = 'STAGE'
)

--- DUPLIKASI
-----> TABLE IMA MASTERID NYA DI BEDAIN DI TABLE IMA & PAYMENT SCHEDULE
-----> KALO MAU BEDA NILAI ECL NYA HARUS UPDATE OUTSTANDING NYA DI IMA

-- SELECT * FROM IFRS_ECL_MODEL_DETAIL_PD WHERE SEGMENTATION_ID IN (1,211,3)

---- CEK NILAI ECL
---> FIELD ECL_AMOUNT DI IMA & ECL DETAIL
---- CEK NILAI CKPN
---> STG_PSAK71 FIELD CKPN_LEV_NET


