-- SELECT * FROM VW_PD_RULES_CONFIG;
-- SELECT * FROM VW_LGD_RULES_CONFIG;
-- SELECT * FROM VW_EAD_RULES_CONFIG;
-- SELECT * FROM VW_CCF_RULES_CONFIG;

-- SELECT * FROM VW_MASTER_EXCHANGE_RATE;
-- SELECT * FROM VW_MASTER_PRODUCT_PARAM;

-- SELECT * FROM IFRS_PD_RULES_CONFIG

-- DROP TABLE IFRS_PD_RULES_CONFIG CASCADE

SELECT * FROM IFRS_CCF_RULES_CONFIG

-- DROP TABLE IFRS_PD_RULES_CONFIG CASCADE;--- vw_source_pd_rules_config 
-- DROP TABLE IFRS_LGD_RULES_CONFIG CASCADE; --- vw_lgd_fl_override 
-- DROP TABLE IFRS_EAD_RULES_CONFIG CASCADE; --- vw_source_ead_rules_config 
-- DROP TABLE IFRS_CCF_RULES_CONFIG CASCADE; --- vw_ccf_override 
-- SELECT DUPLICATE_TABLE('ifrs_pd_rules_config_orig','ifrs_pd_rules_config');
-- SELECT DUPLICATE_TABLE('ifrs_lgd_rules_config_orig','ifrs_lgd_rules_config');
-- SELECT DUPLICATE_TABLE('ifrs_ead_rules_config_orig','ifrs_ead_rules_config');
-- SELECT DUPLICATE_TABLE('ifrs_ccf_rules_config_orig','ifrs_ccf_rules_config');

-- DELETE FROM IFRS_PD_RULES_CONFIG WHERE PKID = 236 

-- TRUNCATE TABLE IFRS_CCF_RULES_CONFIG

SELECT * FROM IFRS_CCF_RULES_CONFIG

--- STEP #1
SELECT COUNT(*) FROM VW_LGD_RULES_CONFIG 

SELECT PKID
,DOWNLOAD_DATE
,CURRENCY
,CURRENCY_DESC
,RATE_AMOUNT
,MAINTAIN_DATE FROM VW_MASTER_EXCHANGE_RATE
EXCEPT
SELECT PKID
,DOWNLOAD_DATE
,CURRENCY
,CURRENCY_DESC
,RATE_AMOUNT
,MAINTAIN_DATE FROM IFRS_MASTER_EXCHANGE_RATE

-- SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vw_master_product_param'



