CALL SP_IFRS_IMP_EXEC_RULE_STAGE(NULL,NULL,'P')

-- SELECT SEQUENCE,QUERY_GROUPING,* FROM IFRS_SCENARIO_RULES_DETAIL WHERE RULE_ID = 69 AND DATA_TYPE = 'FLOAT'

-- UPDATE IFRS_SCENARIO_RULES_DETAIL
-- SET DATA_TYPE = 'DOUBLE PRECISION'
-- WHERE RULE_ID = 69 AND DATA_TYPE = 'FLOAT'

-- ALTER TABLE IFRS_SCENARIO_RULES_DETAIL
-- ALTER COLUMN DATA_TYPE TYPE VARCHAR(30);


-- UPDATE TMP_IFRS_ECL_IMA A SET STAGE = CASE   WHEN 2 = 2 THEN 2 END,          
-- SICR_RULE_ID = '69',          
-- SICR_FLAG = 
-- CASE WHEN 2 = CASE  WHEN 2 = 2 THEN 2 END THEN 0 ELSE 1 END 
-- WHERE A.DOWNLOAD_DATE = '20250831'  
-- AND ((A.WATCHLIST_FLAG IN  ('1')  AND  A.RATING_CODE NOT IN  ('G7R','G8','G9','G10','J7R','J8','J9','J10')) OR (A.WATCHLIST_FLAG IN  ('0')  
-- AND  A.RATING_CODE NOT IN  ('G1A','G1B','G1C','G2A','G2B','G2C','J1A','J1B','J1C','J2A','J2B','J2C','J3A','J3B','J3C')  
-- AND  A.RATING_CODE NOT IN  ('G7R','G8','G9','G10','J7R','J8','J9','J10 ')  AND  A.INITIAL_RATING_CODE IN  ('N/A')) OR (A.WATCHLIST_FLAG IN  ('0')  
-- AND  A.RATING_CODE NOT IN  ('G1A','G1B','G1C','G2A','G2B','G2C','J1A','J1B','J1C','J2A','J2B','J2C','J3A','J3B','J3C')  
-- AND  A.RATING_CODE NOT IN  ('G7R','G8','G9','G10','J7R','J8','J9','J10 ')  AND  A.INITIAL_RATING_CODE NOT IN  ('N/A')  
-- AND  A.RATING_DOWNGRADE >= 1  AND  4)) AND A.SEGMENTATION_ID = 211