CALL SP_IFRS_IMP_FILL_IMA_PREV_CURR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_YEAR_TO_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_IMP_ECL_GENERATE_IMA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_DEFAULT_RULE_ECL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EXEC_RULE_STAGE(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_TERM_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_ECL_RESULT_DETAIL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_SYNC_IMA_MONTHLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_NOMINATIVE_OUTPUT(NULL, NULL, 'P');



/*

TRUNCATE TABLE IFRS_RUNNING_LOGS
-- TRUNCATE TABLE IFRS_PD_RULES_CONFIG;
-- TRUNCATE TABLE IFRS_LGD_RULES_CONFIG;
-- TRUNCATE TABLE IFRS_EAD_RULES_CONFIG;
-- TRUNCATE TABLE IFRS_CCF_RULES_CONFIG;

*/

