-- TRUNCATE TABLE IFRS_PAYM_SCHD_ALL;
TRUNCATE TABLE IFRS_IMP_JOURNAL_DATA;
TRUNCATE TABLE IFRS_LGD_CURE_LGL_HEADER;
TRUNCATE TABLE IFRS_LGD_TERM_STRUCTURE;
TRUNCATE TABLE IFRS_BUCKET_DETAIL;
TRUNCATE TABLE IFRS_BUCKET_HEADER;
TRUNCATE TABLE IFRS_SCENARIO_RULES_DETAIL;
TRUNCATE TABLE IFRS_SCENARIO_RULES_HEADER;
TRUNCATE TABLE IFRS_MSTR_SEGMENT_RULES_DETAIL;
TRUNCATE TABLE IFRS_MSTR_SEGMENT_RULES_HEADER;
TRUNCATE TABLE IFRS_ECL_RESULT_DETAIL;
TRUNCATE TABLE IFRS_EAD_RESULT_NONPRK;
TRUNCATE TABLE IFRS_ECL_MODEL_DETAIL_EAD;
TRUNCATE TABLE IFRS_ECL_MODEL_DETAIL_LGD;
TRUNCATE TABLE IFRS_ECL_MODEL_DETAIL_PD;
TRUNCATE TABLE IFRS_ECL_MODEL_DETAIL_PF;
TRUNCATE TABLE IFRS_ECL_MODEL_HEADER;
TRUNCATE TABLE IFRS_IMP_PD_FL_TERM_YEARLY;
TRUNCATE TABLE IFRS_IMP_PD_FL_TERM_STRUCTURE;
TRUNCATE TABLE IFRS_PD_TERM_STRUCTURE_NOFL_YEARLY;
TRUNCATE TABLE IFRS_PD_TERM_STRUCTURE_NOFL;
-- TRUNCATE TABLE IFRS_MASTER_ACCOUNT_IMP;



