CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_IMP_INITIAL_CONFIG (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE,
 P_PRC			 IN VARCHAR2 DEFAULT '  S'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(22);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY VARCHAR2(32767);

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLESELECT2 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));
    V_SP_NAME := UPPER($$PLSQL_UNIT);

    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'GTMP_LGD_RUNNING_CONFIG_' || P_RUNID || '';
        V_TABLEINSERT2 := 'IFRS_LGD_RESULT_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_LGD_UR_HEADER_' || P_RUNID || '';
        V_TABLELGDCONFIG := 'IFRS_LGD_RULES_CONFIG_' || P_RUNID || '';
		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_' || P_RUNID || '';
    ELSE 
        V_TABLEINSERT1 := 'GTMP_LGD_RUNNING_CONFIG';
        V_TABLEINSERT2 := 'IFRS_LGD_RESULT';
        V_TABLESELECT1 := 'IFRS_LGD_UR_HEADER';
		V_TABLELGDCONFIG := 'IFRS_LGD_RULES_CONFIG';
		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY';
    END IF;


    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- BODY -------
    DBMS_OUTPUT.PUT_LINE('Procedure Name = ' || V_SP_NAME);
    -------- BODY -------

    -------- ====== LOG ======
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT2;
    V_COLUMNDEST := '-';
    V_SPNAME := V_SP_NAME;
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') AND (LGD_RULE_ID = ''' || V_MODEL_ID || ''' OR ''' || V_MODEL_ID || ''' = ''0'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END;