CREATE OR REPLACE PROCEDURE PSAK413.C_SP_IFRS_STAGE_BENCANA (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    V_STAGE_DETAIL   VARCHAR2(100);
    V_STR_SQL        VARCHAR2(4000);
    V_CURRDATE       DATE;
    V_IFRS_MASTER_ACCOUNT_MONTHLY VARCHAR2(100);
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_SP_NAME        VARCHAR2(100) := 'C_SP_IFRS_STAGE_BENCANA';
BEGIN
    ----------------------------------------------------------------
    -- INIT
    ----------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;


    IF P_PRC = 'S' THEN 
        V_IFRS_MASTER_ACCOUNT_MONTHLY   := 'IFRS_MASTER_ACCOUNT_MONTHLY_' || P_RUNID;
    ELSE
        V_IFRS_MASTER_ACCOUNT_MONTHLY   := 'IFRS_MASTER_ACCOUNT_MONTHLY';
    END IF;
  
    ----------------------------------------------------------------
    -- RESET STAGE (DYNAMIC UPDATE)
    ----------------------------------------------------------------
    V_STR_SQL :=
        'MERGE INTO ' || V_TAB_OWNER || '.' || V_IFRS_MASTER_ACCOUNT_MONTHLY || ' A
			USING (
				SELECT I.MASTERID ,I.ACCOUNT_NUMBER, I.STAGE  FROM ' || V_TAB_OWNER || '.' || V_IFRS_MASTER_ACCOUNT_MONTHLY || ' I 
				INNER JOIN (SELECT X.NOLOAN, MAX(NO_BUCKET) AS NO_BUCKET 
									FROM LIST_NASABAH_RESTRU_BENCANA X GROUP BY NOLOAN) J 
				ON I.ACCOUNT_NUMBER = J.NOLOAN 
				WHERE I.DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''' AND NVL(I.STAGE,0) < 2
			)B
			ON(A.DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''
				AND A.MASTERID = B.MASTERID)
			WHEN MATCHED THEN 
			UPDATE SET A.STAGE = 2,
					A.SICR_FLAG = 1';

    EXECUTE IMMEDIATE V_STR_SQL;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;