CREATE TABLE PSAK413.GTMP_LOOP 
   (	PERIOD DATE, 
	END_DATE DATE, 
	SEQ NUMBER, 
	SEQ1 NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
