CREATE TABLE "PSAK413"."IFRS_PRC_DATE_TEST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"CURRDATE" DATE, 
	"PREVDATE" DATE, 
	"BATCH_STATUS" NVARCHAR2(50), 
	"REMARK" NVARCHAR2(250), 
	"LAST_PROCESS_DATE" DATE, 
	"SESSIONID" NVARCHAR2(50), 
	"CREATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" DATE NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(36) NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" NVARCHAR2(36)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
