CREATE TABLE "PSAK413"."IFRS_LI_ACCT_CLOSED" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"ACCTNO" NVARCHAR2(50), 
	"FACNO" NVARCHAR2(50), 
	"CIFNO" NVARCHAR2(50), 
	"DATASOURCE" NVARCHAR2(20), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDBY" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
