CREATE TABLE "PSAK413"."IFRS_LINREG_VIF_DTL" 
   (	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_SEQ" NUMBER(10,0), 
	"VARNAME" NVARCHAR2(255), 
	"VIFVALUE" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
