CREATE TABLE PSAK413.IFRS_DEFAULT_NOLAG 
   (	DOWNLOAD_DATE DATE, 
	MASTERID NVARCHAR2(100), 
	RULE_ID NUMBER(20,0), 
	ACCOUNT_NUMBER NVARCHAR2(50), 
	CUSTOMER_NUMBER NVARCHAR2(50), 
	OS_AT_DEFAULT NUMBER(32,6), 
	EQV_AT_DEFAULT NUMBER(32,6), 
	EIR_AT_DEFAULT BINARY_DOUBLE, 
	CREATED_DATE TIMESTAMP (8), 
	PLAFOND_12M_BEFORE_DEFAULT NUMBER(32,6), 
	EQV_PLAFOND_12M_BEFORE_DEFAULT NUMBER(32,6), 
	OS_12M_BEFORE_DEFAULT NUMBER(32,6), 
	EQV_OS_12M_BEFORE_DEFAULT NUMBER(32,6), 
	PLAFOND_AT_DEFAULT NUMBER(32,6), 
	EQV_PLAFOND_AT_DEFAULT NUMBER(32,6), 
	FACILITY_NUMBER NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
