CREATE TABLE "PSAK413"."IFRS_LI_PRC_DATE_AMORT" 
   (	"CURRDATE" DATE, 
	"PREVDATE" DATE, 
	"RUNNING_FLAG_FROM_DW" NCHAR(1), 
	"BATCH_STATUS" NVARCHAR2(50), 
	"REMARK" NVARCHAR2(250), 
	"LAST_PROCESS_DATE" DATE, 
	"SESSIONID" NVARCHAR2(50), 
	"PRC_NAME" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
