CREATE TABLE "PSAK413"."IFRS_MIGRATION_CIF" 
   (	"NEW_CIF" NVARCHAR2(6) NOT NULL ENABLE, 
	"OLD_CIF" NVARCHAR2(15) NOT NULL ENABLE, 
	"T24_FLAG" NVARCHAR2(1), 
	"SUN_NUMBER" NVARCHAR2(35)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
