CREATE TABLE PSAK413.IFRS_CHECK_AMORT_NOCF 
   (	DOWNLOAD_DATE DATE, 
	MASTERID NVARCHAR2(100), 
	CCY NVARCHAR2(5), 
	JURNAL_AMORT_AMT NUMBER(32,6), 
	ACF_UNAMORT_AMT NUMBER(32,6), 
	CONTROL_AMT NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
