CREATE TABLE "PSAK413"."IFRS_RECOVERY_CORP" 
   (	"DOWNLOAD_DATE" DATE, 
	"DEFAULT_DATE" DATE, 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"PRODUCT_GROUP" NVARCHAR2(50), 
	"CURRENCY" NVARCHAR2(3), 
	"RECOVERY_DATE" DATE, 
	"NETT_RECOVERY" NUMBER(32,6), 
	"EIR_AT_DEFAULT" BINARY_DOUBLE, 
	"JAP_NON_JAP_IDENTIFIER" NCHAR(1), 
	"CREATEDBY" NVARCHAR2(100) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
