CREATE TABLE PSAK413.IFRS_CREDITLINE_JENIUS 
   (	DOWNLOAD_DATE DATE, 
	CUSTOMER_NUMBER NVARCHAR2(50), 
	CREDIT_LINE_REF NVARCHAR2(100), 
	ELIGIBILITY_STATUS NVARCHAR2(100), 
	AGREEMENT_DATE DATE, 
	EXPIRY_DATE DATE, 
	OVER_DUE_DAYS NUMBER(10,0), 
	REVOLVING_STATUS NVARCHAR2(50), 
	STATUS NVARCHAR2(100), 
	TYPE NVARCHAR2(100), 
	DEAL_TYPE NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
