CREATE TABLE PSAK413.IFRS_AC_SPPI_DETAIL 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	CLASSID NUMBER(20,0), 
	QUESTIONID NVARCHAR2(20), 
	SELECTED_VALUE NUMBER(10,0), 
	REMARK NCLOB, 
	CREATEDBY NVARCHAR2(36) DEFAULT 'SYSTEM', 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(36), 
	IS_DELETE NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT PK__IFRS_AC___5E028272F51FF246 PRIMARY KEY (PKID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
 LOB (REMARK) STORE AS SECUREFILE (
  TABLESPACE USERS ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
