CREATE TABLE PSAK413.IFRS_AC_MAIN_MAPPING 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	SPPI_RSLT NVARCHAR2(50), 
	BM_RSLT NVARCHAR2(50), 
	FV_OPTION NUMBER(10,0), 
	ASSET_CLASS NVARCHAR2(50), 
	CREATEDBY NVARCHAR2(36) DEFAULT 'SYSTEM', 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(36), 
	 CONSTRAINT PK__IFRS_AC___5E028272FCD21857 PRIMARY KEY (PKID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
