CREATE TABLE PSAK413.IFRS_ASSET_CLASSIFICATION_CORP 
   (	DOWNLOAD_DATE DATE, 
	FACILITY_NUMBER NVARCHAR2(50), 
	SPPI_RESULT NVARCHAR2(50), 
	BM_RESULT NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
