CREATE TABLE PSAK413.IFRS_EIL_MODEL_NON_MODEL_203 
   (	DOWNLOAD_DATE DATE, 
	EIL_MODEL_ID NUMBER(19,0), 
	EAD_RULE_ID NUMBER(19,0), 
	EAD_TYPE VARCHAR2(50), 
	SUB_SEGMENT_EAD VARCHAR2(60), 
	SEGMENTATION_ID NUMBER(19,0), 
	LGD_RULE_ID NUMBER(19,0), 
	LGD_ME_MODEL_ID NUMBER(19,0), 
	SUB_SEGMENT_LGD VARCHAR2(60), 
	LGD_DATE DATE, 
	LGD_OVERRIDE_FLAG NUMBER(1,0), 
	PD_RULE_ID NUMBER(19,0), 
	PD_ME_MODEL_ID NUMBER(19,0), 
	SUB_SEGMENT_PD VARCHAR2(60), 
	PD_DATE DATE, 
	BUCKET_GROUP VARCHAR2(30), 
	EAD_BALANCE VARCHAR2(250), 
	LT_RULE_ID NUMBER(19,0), 
	LT_EFF_DATE DATE, 
	LT_OVERRIDE_FLAG NUMBER(1,0), 
	FLAG_VAS NUMBER(1,0), 
	MODEL_TYPE NUMBER(10,0), 
	PRC CHAR(1), 
	CREATEDBY VARCHAR2(36) NOT NULL ENABLE, 
	CREATEDDATE DATE NOT NULL ENABLE, 
	CREATEDHOST VARCHAR2(36), 
	UPDATEDBY VARCHAR2(36), 
	UPDATEDDATE DATE, 
	EAD_BALANCE_INTEREST VARCHAR2(100), 
	LIFETIME NUMBER(5,0), 
	LGD NUMBER, 
	EAD_BALANCE_ADDITIONAL VARCHAR2(250), 
	EAD_BALANCE_INTEREST_ADDITIONAL VARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
