CREATE TABLE "PSAK413"."IFRS_PD_VAS_ZSCORE" 
   (	"EFF_DATE" DATE, 
	"BASE_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"SCENARIO_NO" NUMBER(10,0), 
	"ODR" FLOAT(126), 
	"MEAN_ODR" FLOAT(126), 
	"STDEV_ODR" FLOAT(126), 
	"ZSCORE" FLOAT(126), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (6), 
	"ME_CODE" VARCHAR2(100), 
	"FL_SEQ" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
