CREATE TABLE PSAK413.IFRS_LIFETIME_HEADER_S_00000_0000 
   (	PKID NUMBER(19,0) NOT NULL ENABLE, 
	EFF_DATE DATE, 
	LIFETIME_RULE_ID NUMBER(19,0), 
	LIFETIME NUMBER(10,4), 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
