CREATE TABLE PSAK413.IFRS_LIFETIME_RULE_DATA_S_00000_0000 
   (	PKID NUMBER(19,0) NOT NULL ENABLE, 
	DOWNLOAD_DATE DATE, 
	RULE_ID NUMBER(19,0), 
	MASTERID NUMBER(19,0), 
	CUSTOMER_NUMBER VARCHAR2(50), 
	FACILITY_NUMBER VARCHAR2(50), 
	ACCOUNT_STATUS VARCHAR2(20), 
	BI_COLLECTABILITY VARCHAR2(5), 
	RATING_CODE VARCHAR2(20), 
	EXT_RATING_CODE VARCHAR2(20), 
	DAY_PAST_DUE NUMBER(10,0), 
	DPD_CIF NUMBER(10,0), 
	IMPAIRED_FLAG VARCHAR2(5), 
	LOAN_START_DATE DATE, 
	LOAN_DUE_DATE DATE, 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
