CREATE TABLE "PSAK413"."IFRS_ME_FL_SCALAR_ACTUAL_ODR" 
   (	"PERIOD_DATE" DATE, 
	"BASE_PERIOD_FORECAST" DATE, 
	"SCALAR_ID" NUMBER(10,0), 
	"MODEL_ID" NUMBER(10,0), 
	"MODEL_SEQ" NUMBER(20,0), 
	"FL_YEAR" NUMBER(10,0), 
	"SCENARIO_NO" NUMBER(10,0), 
	"SCENARIO_NAME" NVARCHAR2(100), 
	"LOGIT_ACTUAL_ODR" BINARY_DOUBLE, 
	"ACTUAL_ODR" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
