CREATE TABLE "PSAK413"."IFRS_PD_VAS_MPD" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"FL_SEQ" NUMBER(10,0), 
	"BASE_DATE" DATE, 
	"BUCKET_GROUP" VARCHAR2(30), 
	"BUCKET_ID" NUMBER(10,0), 
	"TTC_PD" FLOAT(53), 
	"CORRELATION" FLOAT(53), 
	"ZSCORE" FLOAT(53), 
	"FPD" FLOAT(53), 
	"CPD" FLOAT(53), 
	"PD" FLOAT(53), 
	"CREATEDDATE" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(36), 
	"SCENARIO_NO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
