CREATE TABLE PSAK413.IFRS_IMP_MAIN_DASHBOARD 
   (	DATA_DATE DATE, 
	SEGMENT NVARCHAR2(250), 
	STAGE NVARCHAR2(1), 
	BRANCH NVARCHAR2(50), 
	CURRENCY NVARCHAR2(5), 
	CA_ECL_AMT_IDR NUMBER(32,6), 
	IA_ECL_AMT_IDR NUMBER(32,6), 
	EIL_AMT_IDR NUMBER(32,6), 
	CA_UNWINDING_AMT_IDR NUMBER(32,6), 
	IA_UNWINDING_AMT_IDR NUMBER(32,6), 
	UNWINDING_AMT_IDR NUMBER(32,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
