CREATE TABLE "PSAK413"."IFRS_MASTER_PARENT_LIMIT" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE, 
	"LIMIT_PARENT_NO" NVARCHAR2(20), 
	"LIMIT_START_DATE" DATE, 
	"LIMIT_EXPIRED_DATE" DATE, 
	"LIMIT_CURRENCY" NVARCHAR2(3), 
	"LIMIT_PLAFOND" NUMBER(32,6), 
	"CIF_ID" NVARCHAR2(50), 
	"SME_FLAG" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
