CREATE TABLE PSAK413.IFRS_HOLIDAY 
   (	HOLIDAY_DATE DATE, 
	INSERTDATE TIMESTAMP (8), 
	DESCRIPTION NVARCHAR2(200), 
	DOWNLOAD_DATE DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
