CREATE TABLE "PSAK413"."IFRS_PD_MAA_AVERAGE" 
   (	"DOWNLOAD_DATE" DATE, 
	"BASE_DATE" DATE, 
	"TO_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"CALC_METHOD" NVARCHAR2(50), 
	"AVERAGE_RATE" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
