CREATE TABLE PSAK413.IFRS_AC_SPPI_QUESTIONS 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	TEMPLATEID NUMBER(10,0) NOT NULL ENABLE, 
	SECTIONID NUMBER(10,0) NOT NULL ENABLE, 
	ITEMCODE NVARCHAR2(20) NOT NULL ENABLE, 
	QUESTION NCLOB, 
	SEQUENCE NUMBER(10,0), 
	DESCRIPTION NCLOB, 
	SCOREYES NUMBER(10,0), 
	SCORENO NUMBER(10,0), 
	REQUIRED NUMBER(10,0) NOT NULL ENABLE, 
	FOLLOWUP NUMBER(10,0) NOT NULL ENABLE, 
	PARENTID NUMBER(20,0) NOT NULL ENABLE, 
	CREATEDBY NVARCHAR2(36) DEFAULT 'SYSTEM', 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(30), 
	IS_DELETE NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT PK__IFRS_AC___5E02827278AE9351 PRIMARY KEY (PKID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
 LOB (QUESTION) STORE AS SECUREFILE (
  TABLESPACE USERS ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB (DESCRIPTION) STORE AS SECUREFILE (
  TABLESPACE USERS ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
