CREATE TABLE PSAK413.IFRS_ACCT_AMORT_RESTRU 
   (	DOWNLOAD_DATE DATE, 
	DATA_SOURCE NVARCHAR2(50), 
	MASTERID NVARCHAR2(100), 
	PREV_MASTERID NVARCHAR2(100), 
	ACCOUNT_NUMBER NVARCHAR2(100), 
	PREV_ACCOUNT_NUMBER NVARCHAR2(100), 
	RESTRUCTURE_DATE DATE, 
	PRODUCT_CODE NVARCHAR2(50), 
	PRODUCT_TYPE NVARCHAR2(50), 
	PRODUCT_GROUP NVARCHAR2(100), 
	BRANCH_CODE NVARCHAR2(50), 
	PREV_BRANCH_CODE NVARCHAR2(50), 
	CIFNO NVARCHAR2(100), 
	CCY NVARCHAR2(50), 
	EIR BINARY_DOUBLE, 
	PREV_EIR BINARY_DOUBLE, 
	METHOD NVARCHAR2(50), 
	OUTSTANDING NUMBER(32,6), 
	PREV_UNAMORT_FEE_AMT NUMBER(32,6), 
	PREV_UNAMORT_COST_AMT NUMBER(32,6), 
	UNAMORT_FEE_AMT NUMBER(32,6), 
	UNAMORT_COST_AMT NUMBER(32,6), 
	ADJ_VALUE NUMBER(32,6), 
	PRORATE_UNAMORT_FEE NUMBER(32,6), 
	PRORATE_UNAMORT_COST NUMBER(32,6), 
	CNT NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
