CREATE TABLE PSAK413.IFRS_FL_SCALAR_CONFIG 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	ME_MODEL_ID NUMBER(20,0) NOT NULL ENABLE, 
	SIMULATION_DATE TIMESTAMP (8), 
	ADJUSTMENT_METHOD NVARCHAR2(20) NOT NULL ENABLE, 
	RULE_TYPE NVARCHAR2(5), 
	RULE_ID NUMBER(20,0), 
	ACTIVE_FLAG NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	IS_DELETE NUMBER(10,0) DEFAULT 0, 
	CREATEDBY NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	CREATEDDATE TIMESTAMP (8) NOT NULL ENABLE, 
	CREATEDHOST NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
