CREATE TABLE PSAK413.IFRS_LGD_POW_DETAIL 
   (	EFF_DATE DATE, 
	LGD_RULE_ID NUMBER(20,0), 
	DEFAULT_DATE DATE, 
	MASTERID NUMBER(20,0), 
	EQV_AT_DEFAULT NUMBER(32,6), 
	CURE_FLAG NUMBER(10,0), 
	CURE_COUNTER NUMBER(5,0), 
	ACCOUNT_STATUS NCHAR(1), 
	DEFAULT_FLAG NUMBER(10,0), 
	CREATEDBY NVARCHAR2(36), 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(30), 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
