CREATE TABLE "PSAK413"."IFRS_ME_FORECAST_DETAIL_HIST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"ME_CODE" NVARCHAR2(100) NOT NULL ENABLE, 
	"FL_PERIOD" DATE, 
	"FL_VAL" BINARY_DOUBLE, 
	"REMARKS" NVARCHAR2(100), 
	"INPUT" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
