CREATE TABLE PSAK413.IFRS_DIM_INDUSTRY_SECTORS 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	INDUSTRY_SECTOR_ID NUMBER(10,0) NOT NULL ENABLE, 
	ECONOMIC_SECTOR NVARCHAR2(1500) NOT NULL ENABLE, 
	GROUP_SECTOR_ID NVARCHAR2(50) NOT NULL ENABLE, 
	GROUP_SECTOR_DESC NVARCHAR2(100) NOT NULL ENABLE, 
	INDUSTRY_SECTOR_DESC NVARCHAR2(100) NOT NULL ENABLE, 
	CREATEDBY NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	CREATEDDATE TIMESTAMP (8) NOT NULL ENABLE, 
	CREATEDHOST NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(30), 
	IS_DELETE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
