CREATE TABLE PSAK413.IFRS_BATCH_LOG_DETAILS 
   (	DOWNLOAD_DATE DATE, 
	SESSION_ID NVARCHAR2(50), 
	BATCH_ID NUMBER(10,0), 
	BATCH_ID_HEADER NUMBER(10,0), 
	BATCH_NAME NVARCHAR2(10), 
	PROCESS_NAME NVARCHAR2(100), 
	START_DATE DATE, 
	END_DATE DATE, 
	CREATEDBY NVARCHAR2(50), 
	COUNTER NUMBER(10,0), 
	REMARKS NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
