CREATE TABLE PSAK413.IFRS_CCF_SCENARIO_DATA_SUMM 
   (	DOWNLOAD_DATE DATE, 
	CCF_UNIQUE_ID NVARCHAR2(50), 
	CUSTOMER_NAME NVARCHAR2(100), 
	CCF_RULE_ID NUMBER(10,0), 
	DEFAULT_RULE_ID NUMBER(10,0), 
	DEFAULT_FLAG NUMBER(10,0), 
	SEQUENCE NUMBER(10,0), 
	SEGMENT NVARCHAR2(50), 
	SUB_SEGMENT NVARCHAR2(50), 
	GROUP_SEGMENT NVARCHAR2(50), 
	RULE_TYPE NVARCHAR2(50), 
	FACILITY_NUMBER NVARCHAR2(50), 
	PLAFOND NUMBER(32,6), 
	OUTSTANDING NUMBER(32,6), 
	EXCHANGE_RATE NUMBER(32,6), 
	SOURCE_PROCESS NVARCHAR2(50), 
	LAG_1MONTH_FLAG NUMBER(10,0), 
	CALC_METHOD NVARCHAR2(20), 
	CREATEDBY NVARCHAR2(36), 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(30), 
	CURRENCY NVARCHAR2(3), 
	LIMIT_CURRENCY NVARCHAR2(3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
