CREATE TABLE "PSAK413"."IFRS_LGD_REC_DETAIL" 
   (	"DOWNLOAD_DATE" DATE, 
	"RULE_ID" NUMBER(20,0), 
	"MASTERID" NUMBER(20,0), 
	"SEQ" NUMBER(5,0), 
	"REC_OS" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"REC_WO" NUMBER(32,6), 
	"EQV_REC_WO" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" BLOB, 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("UPDATEDBY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
