CREATE TABLE "PSAK413"."IFRS_MASTER_WO_RECOVERY" 
   (	"DOWNLOAD_DATE" DATE, 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_STATUS" NCHAR(1) NOT NULL ENABLE, 
	"BRANCH_CODE" NVARCHAR2(5), 
	"CURRENCY" NVARCHAR2(3) NOT NULL ENABLE, 
	"CUSTOMER_NAME" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"DATA_SOURCE" NVARCHAR2(5), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"EXCHANGE_RATE" NUMBER(10,0) NOT NULL ENABLE, 
	"MASTERID" NVARCHAR2(50), 
	"BI_COLLECTABILITY" NUMBER(10,0) NOT NULL ENABLE, 
	"OUTSTANDING_WO" NUMBER(32,6), 
	"PLAFOND" NUMBER(32,6), 
	"PRODUCT_CODE" NVARCHAR2(50), 
	"PRODUCT_GROUP" NVARCHAR2(50), 
	"PRODUCT_TYPE" NVARCHAR2(50), 
	"RECOVERY_DATE" DATE, 
	"RECOVERY_AMOUNT" NUMBER(32,6), 
	"TOTAL_RECOVERY" NUMBER(32,6), 
	"SOURCE_TABLE" NVARCHAR2(50), 
	"CREATEDBY" NVARCHAR2(15), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(15), 
	"SEGMENT" NVARCHAR2(100), 
	"SUB_SEGMENT" NVARCHAR2(50), 
	"GROUP_SEGMENT" NVARCHAR2(50), 
	"SEGMENT_FLAG" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
