CREATE TABLE PSAK413.IFRS_ASSET_CLASS_HEADER 
   (	PKID NUMBER(20,0) NOT NULL ENABLE, 
	CLASS_NAME NVARCHAR2(100) NOT NULL ENABLE, 
	CLASS_LEVEL NVARCHAR2(20), 
	CLASS_ID NVARCHAR2(50) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE, 
	STATUS NVARCHAR2(50), 
	SPPI_RSLT NVARCHAR2(50), 
	BM_RSLT NVARCHAR2(50), 
	ASSET_CLASS NVARCHAR2(50), 
	ASSET_CLASS_ORI NVARCHAR2(50), 
	RESULT_STATUS NUMBER(10,0), 
	CREATEDBY NVARCHAR2(36), 
	CREATEDDATE TIMESTAMP (8), 
	CREATEDHOST NVARCHAR2(30), 
	UPDATEDBY NVARCHAR2(36), 
	UPDATEDDATE TIMESTAMP (8), 
	UPDATEDHOST NVARCHAR2(30), 
	APPROVEDBY NVARCHAR2(36), 
	APPROVEDDATE TIMESTAMP (8), 
	APPROVEDHOST NVARCHAR2(30), 
	ACTIONS NVARCHAR2(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
