CREATE TABLE "PSAK413"."IFRS_STG_MASTER_ACCOUNT_TRSREP" 
   (	"DOWNLOAD_DATE" NVARCHAR2(20), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"DEAL_NO" NVARCHAR2(50), 
	"ACCOUNT_STATUS" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(50), 
	"SECURITY_CODE" NVARCHAR2(50), 
	"AMOUNT" NVARCHAR2(50), 
	"CURRENCY" NCHAR(3), 
	"MARGIN_RATE" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"TRX_DATE" NVARCHAR2(20), 
	"SETLE_DATE" NVARCHAR2(20), 
	"MATURITY_DATE" NVARCHAR2(20), 
	"COUPON_REINVEST" NCHAR(1), 
	"FIRST_SETTLEMENT" NVARCHAR2(50), 
	"SECOND_SETTLEMENT" NVARCHAR2(50), 
	"ACCRUED_INTEREST" NVARCHAR2(50), 
	"BANK_NON_BANK" NVARCHAR2(50), 
	"BRANCH_CODE" NVARCHAR2(50), 
	"RESIDENT_GROUP" NVARCHAR2(50), 
	"BI_CODE" NVARCHAR2(20), 
	"AL_FLAG" NCHAR(1), 
	"DEPT_UNIT" NVARCHAR2(50), 
	"FILENAME" NVARCHAR2(100), 
	"SOURCE_PROCESS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
