CREATE TABLE "PSAK413"."IFRS_ME_SCALAR_DETAIL_PENDING" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"SCALAR_ID" NUMBER(10,0), 
	"SCENARIO_NO" NUMBER(10,0), 
	"SCENARIO_NAME" NVARCHAR2(50), 
	"ADJUSTMENT_VALUE" BINARY_DOUBLE, 
	"ECONOMY_IMPACT" NUMBER(10,0), 
	"WEIGHTED_VALUE" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
