CREATE TABLE "PSAK413"."PSAK_MASTER_ACCOUNT_LOAN_DATE" 
   (	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"MASTER_ACCOUNT_ID" VARCHAR2(100), 
	"LOAN_START_DATE" TIMESTAMP (6), 
	"LOAN_DUE_DATE" TIMESTAMP (6), 
	"DAY_PAST_DUE_START_DATE" DATE, 
	"RESTRUCTURED_LOAN_FLAG" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
