CREATE TABLE "PSAK413"."STG_PSAK71" 
   (	"BUSS_DATE" TIMESTAMP (8), 
	"CIF" NVARCHAR2(10), 
	"COMMITMENT_REFERENCE" NVARCHAR2(50), 
	"DEAL_REF" NVARCHAR2(50), 
	"CUSTOMER_FULL_NAME" NVARCHAR2(100), 
	"BRANCH" NVARCHAR2(4), 
	"DEAL_TYPE" NVARCHAR2(10), 
	"CCY" NVARCHAR2(3), 
	"OUTSTANDING_ORI" NUMBER(32,6), 
	"OUTSTANDING_LEV" NUMBER(32,6), 
	"INITIAL_FEE" NUMBER(32,6), 
	"INITIAL_COST" NUMBER(32,6), 
	"UNAMORT_FEE_ORI" NUMBER(32,6), 
	"UNAMORT_FEE_LEV" NUMBER(32,6), 
	"UNAMORT_COST_ORI" NUMBER(32,6), 
	"UNAMORT_COST_LEV" NUMBER(32,6), 
	"FAIR_VALUE_ORI" NUMBER(32,6), 
	"FAIR_VALUE_LEV" NUMBER(32,6), 
	"INT_RATE" NUMBER(32,6), 
	"EIR_RATE" NUMBER(32,6), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"COLLECT" NVARCHAR2(1), 
	"CKPN_TYPE" NVARCHAR2(1), 
	"CKPN_ORI" NUMBER(32,6), 
	"CKPN_LEV" NUMBER(32,6), 
	"UNWINDING_ORI" NUMBER(32,6), 
	"UNWINDING_LEV" NUMBER(32,6), 
	"STAFF_LOAN_FLAG" NVARCHAR2(1), 
	"IFRS9_CLASS" NVARCHAR2(50), 
	"SEGMENTATION" NVARCHAR2(50), 
	"IFRS_STAGE" NVARCHAR2(1), 
	"DEFAULT_FLAG" NUMBER(10,0), 
	"SOURCE_SYSTEM" NVARCHAR2(20), 
	"PRODUCT_TYPE" NVARCHAR2(6), 
	"PLAFOND" NUMBER(32,6), 
	"UNUSED_AMOUNT" NUMBER(32,6), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"DPD_FINAL" NUMBER(6,0), 
	"CKPN_ORI_NET" NUMBER(32,6), 
	"CKPN_LEV_NET" NUMBER(32,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
