CREATE TABLE "PSAK413"."STG_TRX_PSAK71_LOG" 
   (	"PROCESS_ID" NVARCHAR2(20), 
	"PROCESS_NAME" NVARCHAR2(100), 
	"LAST_BUSS_DATE" TIMESTAMP (8), 
	"CREATED_DATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
