CREATE TABLE "PSAK413"."TMP_IFRS_ACCT_STOP_REV" 
   (	"MASTERID" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
