CREATE TABLE "PSAK413"."TMP_T6" 
   (	"FACNO" NVARCHAR2(50), 
	"CIFNO" NVARCHAR2(50), 
	"DOWNLOAD_DATE" DATE, 
	"DATASOURCE" NVARCHAR2(20), 
	"SUM_AMT" NUMBER(32,6), 
	"ACCTNO" NVARCHAR2(70), 
	"MASTERID" NVARCHAR2(100), 
	"BRCODE" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
