CREATE TABLE "PSAK413"."TMP_IFRS_PD_SCENARIO_DATA" 
   (	"PERIOD" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"BUCKET_GROUP" VARCHAR2(30), 
	"PD_UNIQUE_ID" VARCHAR2(50), 
	"CALC_METHOD" VARCHAR2(5), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"BUCKET_ID" NUMBER(5,0), 
	"OUTSTANDING" NUMBER(32,6), 
	"KEY_TMP" VARCHAR2(60), 
	"ACCOUNT_STATUS" VARCHAR2(2), 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"EFF_DATE" DATE, 
	"CUSTOMER_NAME" VARCHAR2(150)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
