CREATE TABLE "PSAK413"."TMP_PAYM_FUNDING" 
   (	"MASTERID" NVARCHAR2(100), 
	"DOWNLOAD_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
