CREATE TABLE "PSAK413"."TMP_PD_VAS_ZSCORE1" 
   (	"PD_RULE_ID" NUMBER, 
	"ME_CODE" VARCHAR2(100), 
	"PERIOD" DATE, 
	"SCENARIO_NO" NUMBER(10,0), 
	"ME_VAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
