CREATE TABLE "PSAK413"."TMP_SCHD1" 
   (	"MASTERID" NVARCHAR2(100), 
	"LAST_PAYMENT_DATE_PYM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
