CREATE TABLE "PSAK413"."TMP_IFRS_VARCLUS_CLUSTER_SUMM" 
   (	"MODEL_ID" NVARCHAR2(255), 
	"CLUSTER" NVARCHAR2(255), 
	"MEMBERS" NVARCHAR2(255), 
	"VAR_EXPL" NVARCHAR2(255), 
	"PROP_EXPL" NVARCHAR2(255), 
	"SECOND_EIGV" NVARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
