CREATE TABLE "PSAK413"."TMP_STG_CIF_IFTH" 
   (	"CIF" NVARCHAR2(100), 
	"CUSTOMER_TYPE" NVARCHAR2(100), 
	"SOURCE_SYSTEM" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
