CREATE TABLE "PSAK413"."TMP_ENR_MAA_BASE" 
   (	"DOWNLOAD_DATE" DATE, 
	"BASE_DATE" DATE, 
	"TO_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0), 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_FROM" NUMBER(5,0), 
	"CALC_AMOUNT" NUMBER(10,0), 
	"TOTAL_ACCOUNT" NUMBER(20,0), 
	"CALC_METHOD" NVARCHAR2(50), 
	"PERCENTAGE" NUMBER(10,0), 
	"CREATEDBY" NCLOB, 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CREATEDBY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
