CREATE TABLE "PSAK413"."X_GRIYA_OTO_PATCH" 
   (	"DATA_SOURCE" VARCHAR2(40), 
	"ACCOUNT_NUMBER" VARCHAR2(100), 
	"PRODUCT_CODE" VARCHAR2(40), 
	"PRODUCT_TYPE" VARCHAR2(100), 
	"DIVISI" VARCHAR2(60), 
	"SEGMENTASI" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
