CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_EIL_SEQ
AS
--declare
dtcurr DATE;
dtprev DATE;
BEGIN
	
	dtcurr := '31-JAN-2026';

	--EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_RESULT_DETAIL';
  	--EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_RESULT_HEADER';
  	--EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EAD_RESULT';
   	--EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_IMA';
  
--    COMMIT;
--	WHILE  dtcurr <= '31-DEC-2025' -- '31-DEC-2025'
--	LOOP 
		
--		SP_IFRS_EAD_RULES_CONFIG();
--
--	 	SP_IFRS_EIL_MODEL_HEADER();
--	 
--		SP_IFRS_EIL_MODEL_DETAIL_EAD();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_PF();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_PD();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_LGD();
--	
--		SP_IFRS_EIL_MODEL('S_00000_0000',dtcurr,'0','M');

--		SP_IFRS_UPDATE_STAGE(dtcurr);
		
--		SP_IFRS_EIL_GENERATE_IMA('S_00000_0000',dtcurr,'0','M');
		
--		SP_IFRS_EAD_RESULT('S_00000_0000',dtcurr,'0','M');
		
		SP_IFRS_EIL_RESULT_DETAIL_14('S_00000_0000',dtcurr,'0','M');
	
	 	SP_IFRS_EIL_RESULT_HEADER('S_00000_0000',dtcurr,'0','M');	
	 	
	 	SP_IFRS_UPDATE_IMA_RESULT('S_00000_0000', dtcurr, 'M');


--	dbms_output.put_line(dtcurr);
--	dtcurr := LAST_DAY(ADD_MONTHS(dtcurr, 1));
--	
--	END LOOP;

END