CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_EIL_GENERATE_IMA
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS 
	
	c               INTEGER;
	rows_processed  INTEGER;
	 
    V_CURRDATE       DATE;
    V_DATADATE       VARCHAR2(20);
    V_TABLE_NAME     VARCHAR2(50);
	V_PREVDATE       DATE;
    V_COUNT          NUMBER;
	V_MODEL_ID       NUMBER;

-- DYNAMIC NAMES / QUERY
    V_STR_QUERY      VARCHAR2(8000);

    -- TABLE NAMES
    V_TAB_OWNER     CONSTANT 		VARCHAR2(30) := 'PSAK413';
    V_PMA				  			VARCHAR2(100);
    V_TMP_PD  						VARCHAR2(100);
    V_IFRS_EIL_IMA					VARCHAR2(100);
    v_eil_model_id				 	NUMBER;
    v_maxrn			 				NUMBER;
    V_IFRS_SEGMENTATION_MAPPING 	VARCHAR2(100);
    V_TABLEPDCONFIG					VARCHAR2(100);

    -- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_EIL_GENERATE_IMA';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        VARCHAR2(8000);
    V_RETURNROWS2   NUMBER;
    
    V_STR_SQL        CLOB;
    V_STR_SQL_RULE   CLOB;
    V_RULE_ID        VARCHAR2(250);
    V_ID             NUMBER := 0;
    V_MAX_ID         NUMBER := 0;
    V_SEQUENCE       VARCHAR2(50);
    
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, -1));
    V_MODEL_ID := 0;

    -- CHOOSE TABLE NAMES BASED ON MODE
    IF P_PRC = 'S' THEN
        V_PMA  				:= 'IFRS_MASTER_ACCOUNT_MONTHLY_' || P_RUNID;
        V_TMP_PD  			:= 'TMP_PD_' || P_RUNID;
        V_IFRS_EIL_IMA		:= 'IFRS_EIL_IMA_' || P_RUNID;
    ELSE
        V_PMA  				:= 'IFRS_MASTER_ACCOUNT_MONTHLY';
        V_TMP_PD  			:= 'TMP_PD';
        V_IFRS_EIL_IMA		:= 'IFRS_EIL_IMA';
    END IF;

    BEGIN
        SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSTIMESTAMP);
    EXCEPTION
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('WARNING: SP_IFRS_RUNNING_LOG FAILED: ' || SQLERRM);
    END;
    COMMIT;

    IF P_PRC = 'S' THEN
        
        -- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_IFRS_EIL_IMA);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA || ' AS SELECT * FROM IFRS_EIL_IMA WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        COMMIT;
    ELSE
    	    
    	EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_IFRS_EIL_IMA || '';
	    COMMIT;
    
    END IF;

  -- Pilih nama tabel sesuai PRC
  v_table_name := V_PMA;

  -- Ambil EIL_MODEL_ID yang aktif atau persis p_model_id
  SELECT pkid
    INTO v_eil_model_id
    FROM IFRS_EIL_MODEL_HEADER
   WHERE pkid = v_model_id
      OR (v_model_id = 0 AND IS_EOM = 1);

  EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_QRY';

  -- Build query dinamis per baris model, mirip T-SQL Anda (masuk ke TMP_QRY)
  INSERT INTO TMP_QRY (RN, QRY)
  SELECT
    ROW_NUMBER() OVER (ORDER BY A.EIL_MODEL_ID) AS RN,
    
    'SELECT A.DOWNLOAD_DATE, A.MASTERID, A.GROUP_SEGMENT, A.SEGMENT, A.SUB_SEGMENT, '
      || TO_CHAR(A.SEGMENTATION_ID) || ', A.ACCOUNT_NUMBER, NVL(A.CUSTOMER_NUMBER, ''''), '
      || NVL(A.LT_RULE_ID,0) || ', A.DPD_CIF, A.DAY_PAST_DUE, A.RESTRUCTURE_FLAG, '
      || 'A.DATA_SOURCE, A.PRODUCT_CODE, A.PRODUCT_TYPE, A.PRODUCT_GROUP, A.IS_IMPAIRED, A.IFRS9_CLASS, '''
      || NVL(A.SUB_SEGMENT_PD, '') || ''', ''' || NVL(A.SUB_SEGMENT_LGD, '') || ''', ''' || NVL(A.SUB_SEGMENT_EAD, '') || ''', '
      || ' ''' || A.BUCKET_GROUP || ''', CASE WHEN D.BUCKET_ID > NVL(G.NO_BUCKET,0) THEN D.BUCKET_ID 
			ELSE 
			NVL(G.NO_BUCKET,0) END BUCKET_ID, A.STAGE, A.REVOLVING_FLAG, NVL(A.EIR, A.MARGIN_RATE) AS EIR, '
      || 'A.OUTSTANDING, NVL(A.UNAMORT_COST_AMT,0), NVL(A.UNAMORT_FEE_AMT,0), NVL(A.FAIR_VALUE_AMOUNT,0), '
      || 'NVL(A.PLAFOND,0) PLAFOND, ' || TO_CHAR(A.EIL_MODEL_ID) || ', ' || TO_CHAR(A.EAD_RULE_ID) || ', '''
      || TO_CHAR(A.EAD_TYPE) || ''', ' || NVL(A.LGD_RULE_ID,0) || ', '
      || NVL(A.LGD_ME_MODEL_ID,0) || ', ' || TO_CHAR(A.PD_RULE_ID) || ', ' || TO_CHAR(A.PD_ME_MODEL_ID)
      || ', A.CURRENCY, A.CREATEDBY, A.IMPAIRED_FLAG, A.CUSTOMER_NAME, A.ACCOUNT_STATUS, '
      || 'NVL(A.EIL_AMOUNT,0) AS EIL_AMOUNT,  '
      || ' A.RATING_CODE, NVL(A.EXCHANGE_RATE,0) AS EXCHANGE_RATE, A.LOAN_START_DATE, A.LOAN_DUE_DATE,  '
      || TO_CHAR(A.FLAG_VAS) || ', '
      || ' A.BI_COLLECTABILITY ,CASE WHEN LAST_DAY(NVL(A.LOAN_DUE_DATE,''31 JAN 1990'')) <= LAST_DAY(TO_DATE(''' || TO_CHAR(v_currdate, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')) THEN '
      || NVL(A.LIFETIME,0) || ' ELSE MONTHS_BETWEEN( LAST_DAY(NVL(A.LOAN_DUE_DATE,''31 JAN 1990'')), LAST_DAY(A.DOWNLOAD_DATE)) END AS LIFETIME, NVL(A.' 
      || TO_CHAR(A.EAD_BALANCE) || ',0) , ' || TO_CHAR(A.EAD_BALANCE_INTEREST) || ' AS EAD_BALANCE_INTEREST,'
      || TO_CHAR(A.EAD_BALANCE_ADDITIONAL) || ', 0 AS EAD_BALANCE_INTEREST_ADDITIONAL, A.MARGIN_ACCRUED '
      || 'FROM ' || v_table_name || ' A '
      || 'JOIN IFRS_SEGMENTATION_MAPPING B ON A.SEGMENTATION_ID = B.PKID '
      || 'LEFT JOIN IFRS_BUCKET_HEADER C ON ''' || A.BUCKET_GROUP || ''' = C.BUCKET_GROUP '
      || 'LEFT JOIN IFRS_BUCKET_DETAIL D ON C.BUCKET_GROUP = D.BUCKET_GROUP '
      || 'AND ( CASE '
      || '              WHEN C.OPTION_GROUPING = ''DPD_ACCT'' THEN A.DAY_PAST_DUE '
      || '              WHEN C.OPTION_GROUPING = ''DPD_CIF''  THEN A.DPD_CIF '
      || '              WHEN C.OPTION_GROUPING = ''BIC''      THEN A.BI_COLLECTABILITY '
      || '            END '
      || '           BETWEEN D.RANGE_START AND D.RANGE_END )'
      || 'LEFT JOIN VW_IFRS_MAX_BUCKET F ON C.BUCKET_GROUP = F.BUCKET_GROUP '
      || 'LEFT JOIN (SELECT X.DOWNLOAD_DATE,X.NOLOAN,X.MASTERID, MAX(NO_BUCKET) AS NO_BUCKET 
									FROM LIST_NASABAH_RESTRU_BENCANA X GROUP BY X.DOWNLOAD_DATE,X.NOLOAN,X.MASTERID) G ON A.MASTERID = G.MASTERID '
      || 'WHERE B.PKID = ' || TO_CHAR(A.SEGMENTATION_ID)
      || ' AND A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(v_currdate, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'') '
      || 'AND B.SEGMENT_TYPE = ''PORTFOLIO'' AND A.ACCOUNT_STATUS = ''A'' '
      || 'AND A.IAS_CLASS = ''A'' AND NVL(A.IFRS9_CLASS, '' '') <> ''FVTPL'' '
      || 'AND (C.BUCKET_GROUP IS NOT NULL) ' --AND A.IS_IMPAIRED = 1 
      || 'AND NVL(A.IMPAIRED_FLAG,''C'') = ''C'''
    AS QRY
  FROM IFRS_EIL_MODEL A
  WHERE A.DOWNLOAD_DATE = v_currdate
    AND A.EIL_MODEL_ID = v_eil_model_id;

  COMMIT; 

	  V_STR_SQL := '(' ||
	    'DOWNLOAD_DATE, MASTERID, GROUP_SEGMENT, SEGMENT, SUB_SEGMENT, SEGMENTATION_ID, ' ||
			'ACCOUNT_NUMBER, CUSTOMER_NUMBER, LT_RULE_ID, DAY_PAST_DUE_CIF, DAY_PAST_DUE, RESTRUCTURE_FLAG, DATA_SOURCE, PRODUCT_CODE, PRODUCT_TYPE, ' ||
			'PRODUCT_GROUP, IS_IMPAIRED, IFRS9_CLASS, PD_SEGMENT, LGD_SEGMENT, EAD_SEGMENT, BUCKET_GROUP, BUCKET_ID, ' ||
			'STAGE, REVOLVING_FLAG, EIR, OUTSTANDING, UNAMORT_COST_AMT, UNAMORT_FEE_AMT, FAIR_VALUE_AMOUNT, PLAFOND, ' ||
			'EIL_MODEL_ID, EAD_RULE_ID, EAD_TYPE, LGD_RULE_ID, LGD_ME_MODEL_ID, ' ||
			'PD_RULE_ID, PD_ME_MODEL_ID, CURRENCY, CREATEDBY, IMPAIRED_FLAG, CUSTOMER_NAME, ACCOUNT_STATUS, ' ||
			' EIL_AMOUNT, RATING_CODE, EXCHANGE_RATE, LOAN_START_DATE, LOAN_DUE_DATE, ' ||
			'FLAG_VAS, BI_COLLECTABILITY, LIFETIME, EAD_BALANCE, EAD_MARGIN,EAD_BALANCE_ADDITIONAL,EAD_BALANCE_INTEREST_ADDITIONAL,MARGIN_ACCRUED )';
	
	  FOR r IN (SELECT rn, qry FROM TMP_QRY ORDER BY rn) LOOP
		  
		V_STR_QUERY := 'INSERT INTO ' || V_IFRS_EIL_IMA || ' ' || V_STR_SQL || ' ' || r.qry;

		DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
		EXECUTE IMMEDIATE (V_STR_QUERY);
	
	    DELETE FROM TMP_QRY WHERE rn = r.rn;
	  END LOOP;
		
	  COMMIT;

    -----------------------------
    -- Log & insert final data
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_EIL_IMA;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA ||
                ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- ROLLBACK TO SAFE STATE AND RE-RAISE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR IN SP_IFRS_EIL_GENERATE_IMA: ' || SQLERRM);
        RAISE;

END