CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_LGD_WORKOUT_DETAIL
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0',
 P_PRC			 IN VARCHAR2 DEFAULT 'x'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(1000);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY VARCHAR2(32767);

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLESELECT2 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100) := 'SP_IFRS_LGD_WORKOUT_DETAIL';
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');
	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));
	
    IF P_PRC = 'S' THEN  
        V_TABLEINSERT1 := 'IFRS_LGD_WORKOUT_DETAIL_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_LGD_DATA_' || P_RUNID || '';
        V_TABLESELECT2 := 'IFRS_LGD_REC_DATA_' || P_RUNID || ''; 
    ELSE  
        V_TABLEINSERT1 := 'IFRS_LGD_WORKOUT_DETAIL';
        V_TABLESELECT1 := 'IFRS_LGD_DATA';
        V_TABLESELECT2 := 'IFRS_LGD_REC_DATA';  
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
 
 

	----TABLE PROCESS
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1);
        
		IF V_COUNT =  0 THEN 
		 
        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LGD_UR_REC_DETAIL WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
       END IF ; 
    END IF;
	COMMIT;
    -------- ====== PRE SIMULATION TABLE ======



   EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG' ; 
  
	 V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG
	               SELECT * FROM IFRS_LGD_WORKOUT_RULES_CONFIG
	               WHERE  IS_DELETED = 0  AND  (  
	                 UPPER(TRIM(SYSCODE_WORKOUT)) IN ( 
	                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
	                   FROM DUAL
	                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
	                 )
	                 OR :p2 = ''0'' 
	               )';
	 
	    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
 
 
	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_WORKOUT_DETAIL';
	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_DATA1';
	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_REC_DATA1';
	 

    IF V_MODEL_ID = '0' THEN 
    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    ELSE
	V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
    WHERE  EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE A.WORKOUT_RULE_ID = X.PKID)
    AND A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    END IF;
    EXECUTE IMMEDIATE (V_STR_QUERY);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	-- End Clear Session
  
   


V_STR_QUERY := '
INSERT INTO GTMP_IFRS_LGD_DATA1 (DOWNLOAD_DATE, MASTERID, LGD_SEGMENT_ID, CCY, EXCHANGE_RATE)
WITH CTE AS (SELECT MIN(DEFAULT_DATE) DOWNLOAD_DATE,
	MASTERID, A.LGD_SEGMENT_ID, CURRENCY CCY
	FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' A
	JOIN GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG B ON 
	A.LGD_SEGMENT_ID = B.SEGMENTATION_ID
	AND A.DEFAULT_DATE BETWEEN LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD''), -1*(B.HISTORICAL_DATA ))) 
	AND  TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 	
	GROUP BY MASTERID, A.LGD_SEGMENT_ID ,CURRENCY)
SELECT A.DOWNLOAD_DATE, A.MASTERID, A.LGD_SEGMENT_ID, A.CCY, B.RATE_AMOUNT 
FROM CTE A 
	JOIN IFRS_MASTER_EXCHANGE_RATE    B ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE  AND A.CCY = B.CURRENCY ' ; 
 DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
 EXECUTE IMMEDIATE (V_STR_QUERY);


V_STR_QUERY := ' 	
INSERT INTO GTMP_IFRS_LGD_REC_DATA1 (DOWNLOAD_DATE, LGD_SEGMENT_ID,MASTERID, CCY,EXCHANGE_RATE)
WITH CTE AS(
SELECT MAX(DOWNLOAD_DATE) DOWNLOAD_DATE,  LGD_SEGMENT_ID, MASTERID, CCY
	FROM IFRS_LGD_REC_DATA A 
	WHERE EXISTS (
	SELECT 1 
	FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG x  
	WHERE X.SEGMENTATION_ID = A.LGD_SEGMENT_ID 
	FETCH FIRST 1 ROWS ONLY) 
	GROUP BY MASTERID ,CCY, LGD_SEGMENT_ID
)
SELECT A.DOWNLOAD_DATE,A.LGD_SEGMENT_ID, A.MASTERID,  A.CCY, B.RATE_AMOUNT 
FROM CTE A 
	JOIN IFRS_MASTER_EXCHANGE_RATE    B ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE  AND A.CCY = B.CURRENCY ' ; 
 EXECUTE IMMEDIATE (V_STR_QUERY);
	

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO  GTMP_IFRS_LGD_WORKOUT_DETAIL (
	EFF_DATE, 
	 WORKOUT_RULE_ID,
	 DEFAULT_DATE,
	 FACILITY_NUMBER,
	 CUSTOMER_NUMBER,
	 MASTERID,
	 EIR_AT_DEFAULT,
	 RECOVERY_DATE,
	 EQV_OS_AT_DEFAULT,
	 EQV_REC_OS,
	 SUM_EQV_REC_OS,
	 OS_AT_DEFAULT,
	 REC_OS,
	 SUM_REC_OS,
CCY,
EXCHANGE_RATE)
WITH CTE AS (
SELECT DOWNLOAD_DATE, CCY, MASTERID, EXCHANGE_RATE, LGD_SEGMENT_ID
FROM GTMP_IFRS_LGD_REC_DATA1 A 
UNION
SELECT DOWNLOAD_DATE, CCY, MASTERID, EXCHANGE_RATE, LGD_SEGMENT_ID
FROM GTMP_IFRS_LGD_DATA1 B
WHERE NOT EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_REC_DATA1 X WHERE B.MASTERID = X.MASTERID AND B.LGD_SEGMENT_ID = X.LGD_SEGMENT_ID)
)
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') , C.PKID WORKOUT_RULE_ID, 
	 A.DEFAULT_DATE,
	 A.FACILITY_NUMBER,
	 A.CUSTOMER_NUMBER,
	 A.MASTERID,
	 A.EIR_AT_DEFAULT,
	 B.DOWNLOAD_DATE AS RECOVERY_DATE,
	 A.OS_AT_DEFAULT * D.EXCHANGE_RATE ,
	  NVL(B.REC_OS * D.EXCHANGE_RATE  ,0), 
	 SUM(NVL(B.REC_OS * D.EXCHANGE_RATE  ,0)) OVER (PARTITION BY A.LGD_SEGMENT_ID, A.MASTERID ORDER BY B.DOWNLOAD_DATE), 
	 A.OS_AT_DEFAULT, 
	 NVL(B.REC_OS,0), 
	 SUM(NVL(B.REC_OS,0)) OVER (PARTITION BY A.LGD_SEGMENT_ID, A.MASTERID ORDER BY B.DOWNLOAD_DATE) , d.CCY, D.EXCHANGE_RATE
	FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' A	
	JOIN GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG C ON A.LGD_sEGMENT_ID = C.SEGMENTATION_ID
	 LEFT JOIN ' || V_TAB_OWNER || '.' || V_TABLESELECT2 || ' B ON A.MASTERID = B.MASTERID 
		AND A.LGD_SEGMENT_ID = B.LGD_SEGMENT_ID
		AND B.DOWNLOAD_DATE BETWEEN LAST_DAY(ADD_MONTHS(A.DEFAULT_DATE,1)) AND TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	  JOIN CTE D ON A.MASTERID = D.MASTERID AND A.LGD_SEGMENT_ID = D.LGD_SEGMENT_ID
	WHERE EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_DATA1 X WHERE A.MASTERID = X.MASTERID AND A.LGD_SEGMENT_ID = X.LGD_SEGMENT_ID  AND A.DEFAULT_DATE = X.DOWNLOAD_DATE)
		';
DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;


    
	  
	-- CAP SUM_OS <= OS_AT_DEFAULT
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ( 
	 EFF_DATE,
	 WORKOUT_RULE_ID, 
	 DEFAULT_DATE,
	 FACILITY_NUMBER,
	 CUSTOMER_NUMBER,
	 MASTERID,
	 EIR_AT_DEFAULT,
	 RECOVERY_DATE,
	 SEQ , 
	 EQV_OS_AT_DEFAULT, 
	 EQV_REC_OS, 
	 OS_AT_DEFAULT, 
	 REC_OS, 
CCY, EXCHANGE_RATE,
	 CREATEDBY,
	 CREATEDDATE)  
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') AS EFF_DATE, 
	 A.WORKOUT_RULE_ID,  
	 A.DEFAULT_DATE,  
	 A.FACILITY_NUMBER, 
	 A.CUSTOMER_NUMBER, 
	 A.MASTERID,  
	 A.EIR_AT_DEFAULT,
	 A.RECOVERY_DATE,
	TRUNC(MONTHS_BETWEEN(a.RECOVERY_DATE, a.DEFAULT_DATE)),
	 A.EQV_OS_AT_DEFAULT, 
	 CASE 
	  WHEN A.EQV_OS_AT_DEFAULT - A.SUM_EQV_REC_OS > 0 
	   THEN A.EQV_REC_OS
	  ELSE 
	   CASE 
	    WHEN A.SUM_EQV_REC_OS - A.EQV_REC_OS > A.EQV_OS_AT_DEFAULT THEN 0 
	    ELSE A.EQV_OS_AT_DEFAULT - (A.SUM_EQV_REC_OS - A.EQV_REC_OS) 
	   END
	 END EQV_REC_OS, 
	 A.OS_AT_DEFAULT, 
	 CASE 
	  WHEN A.OS_AT_DEFAULT - A.SUM_REC_OS > 0 
	   THEN A.REC_OS
	  ELSE 
	   CASE 
	    WHEN A.SUM_REC_OS - A.REC_OS > A.OS_AT_DEFAULT THEN 0 
	    ELSE A.OS_AT_DEFAULT - (A.SUM_REC_OS - A.REC_OS) 
	   END
	 END REC_OS,  CCY, EXCHANGE_RATE,
	 ''SP_IFRS_LGD_WORKOUT_DETAIL1'' CREATEDBY,
	 SYSDATE CREATEDDATE
	FROM GTMP_IFRS_LGD_WORKOUT_DETAIL A ';


    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;
 
  
 

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
   
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT1; 
    V_COLUMNDEST := '-';
    
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') AND (WORKOUT_RULE_ID = ''' || V_MODEL_ID || ''' OR ''' || V_MODEL_ID || ''' = ''0'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END