CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_LIFETIME_RULES_CONFIG_GTMP
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AUTHID CURRENT_USER
AS
	V_TABLEINSERT1 VARCHAR2(100);
	V_TABLELGDCONFIG VARCHAR2(100);
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
	
	V_COUNT NUMBER; 

    V_QUERYS CLOB;
BEGIN
    
	V_TABLELGDCONFIG := 'IFRS_LIFETIME_RULES_CONFIG'  ;
	  
    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'GTMP_IFRS_LIFETIME_RULES_CONFIG_' || P_RUNID || ''; 
    ELSE 
        V_TABLEINSERT1 := 'GTMP_IFRS_LIFETIME_RULES_CONFIG';
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(P_DOWNLOAD_DATE, 'SP_IFRS_LIFETIME_RULES_CONFIG_GTMP', P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE CONFIG
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1); 
        
		IF V_COUNT > 0 THEN 
		 V_QUERYS := '';
         V_QUERYS := V_QUERYS || 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ';
        EXECUTE IMMEDIATE (V_QUERYS);
		END IF;

        V_QUERYS := '';
        V_QUERYS := V_QUERYS || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.GTMP_IFRS_LIFETIME_RULES_CONFIG WHERE 0=1';
        EXECUTE IMMEDIATE (V_QUERYS);
    END IF;
	COMMIT;
        
   V_QUERYS := 'TRUNCATE TABLE ' || V_TABLEINSERT1;
   
   EXECUTE IMMEDIATE (V_QUERYS) ; 
         
    V_QUERYS := 'INSERT INTO ' || V_TABLEINSERT1 || '
               SELECT * FROM ' || V_TABLELGDCONFIG || '
               WHERE (  
                 UPPER(TRIM(syscode_lifetime)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 IS NULL 
               )';
 
    EXECUTE IMMEDIATE V_QUERYS USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
        
  	COMMIT ; 
  

END