CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_PD_MAA_FLOWRATE_SMOOTH
    P_RUNID         VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE DATE,
    P_SYSCODE       VARCHAR2 DEFAULT '0',
    P_PRC           VARCHAR2 DEFAULT 'S'
)
AS
    -- Date variables
    V_CURRDATE      DATE;
    V_PREVDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);

    -- Loop & process variables
    V_LOOP1         PLS_INTEGER;
    V_LOOP2         PLS_INTEGER;
    V_LOOP3			PLS_INTEGER;
   
   	v_predpd1      NUMBER;
	v_predpd2      NUMBER;
	v_nextflowpd   NUMBER;

    V_CHECK         NUMBER(1);
    V_RESULTPD      BINARY_DOUBLE;
    V_FLOWRATE1     BINARY_DOUBLE;
    V_FLOWRATE2     BINARY_DOUBLE;
    V_PREDICTEDPD1  BINARY_DOUBLE;
    V_PREDICTEDPD2  BINARY_DOUBLE;
    V_NEXTFLOWRATEPD BINARY_DOUBLE;

    -- Count & dynamic SQL
    V_COUNT         NUMBER;
    V_STR_QUERY     CLOB;
    V_QUERYS		CLOB;

    -- Table names
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1  VARCHAR2(100);
    V_TABLEINSERT2  VARCHAR2(100);
    V_TABLESELECT1  VARCHAR2(100);
    V_TABLEPDCONFIG VARCHAR2(100);
    V_TMP_LOGIT_ODR VARCHAR2(100);
    V_LINEST_SMOOTHING VARCHAR2(100);

    -- Logging / result
    V_RETURNROWS2   NUMBER;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100);
BEGIN
	-- set procedure name
    V_SP_NAME := 'SP_IFRS_PD_MAA_FLOWRATE_SMOOTH';
    
    -- Set current and previous dates
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
    V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, -1));
    V_MODEL_ID := '0';

    -- Determine table names
    IF P_PRC = 'S' THEN
        V_TABLEINSERT1 := 'GTMP_PD_RUNNING_SMOOTH_CONFIG_' || P_RUNID;
        V_TABLEINSERT2 := 'IFRS_PD_MAA_FLOWRATE_SMOOTH_' || P_RUNID;
        V_TABLESELECT1 := 'IFRS_PD_MAA_FLOWRATE_SUM_' || P_RUNID;
        V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG_' || P_RUNID;
    	V_LINEST_SMOOTHING := 'IFRS_PD_LINEST_SMOOTHING_' || P_RUNID;
    ELSE
        V_TABLEINSERT1 := 'GTMP_PD_RUNNING_SMOOTH_CONFIG';
        V_TABLEINSERT2 := 'IFRS_PD_MAA_FLOWRATE_SMOOTH';
        V_TABLESELECT1 := 'IFRS_PD_MAA_FLOWRATE_SUM';
        V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG';
    	V_LINEST_SMOOTHING := 'IFRS_PD_LINEST_SMOOTHING';
    
    END IF;

    -----------------------------
    -- Record RUN_ID (log)
    -----------------------------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
   COMMIT;
  
    ----------------------------------------------------------------
    -- PRE-SIMULATION TABLE: create/drop temp tables if P_PRC = 'S'
    ----------------------------------------------------------------
    IF P_PRC = 'S' THEN
        -- drop table if exists V_TABLEINSERT1
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.GTMP_PD_RUNNING_SMOOTH_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- drop table if exists V_TABLEINSERT2
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT2);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT2;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.IFRS_PD_MAA_FLOWRATE_SMOOTH WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- drop table if exists V_TABLESELECT1
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLESELECT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLESELECT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLESELECT1 ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.IFRS_PD_MAA_FLOWRATE_SUM WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- drop table if exists V_TABLEPDCONFIG
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEPDCONFIG);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.GTMP_IFRS_PD_RULES_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
      END IF;
      COMMIT;
      
   	BEGIN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||'';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_LOGIT_ODR';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_SMOOTHING_BASE';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_PD_BASE';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_PD_RESULT';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_SMOOTH';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
   	COMMIT;
   
   
  	EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TABLEPDCONFIG || '' ; 
	 
    V_STR_QUERY := 'INSERT INTO ' || V_TABLEPDCONFIG || ' (PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)' ||
               'SELECT PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE' || 
					 	' FROM IFRS_PD_RULES_CONFIG ' ||
               'WHERE PD_METHOD = ''MAA'' AND NVL(IS_DELETED,0) = 0 AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0''
               )';
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
    COMMIT;
    -----------------------------
    -- UPDATE DEFF FLOWRATE
    -----------------------------
    V_STR_QUERY := 'UPDATE IFRS_PD_MAA_FLOWRATE_SUM A '||
					' SET (A.FLOWRATE) = A.FLOWRATE_ORI '||
						'WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') '||
						' AND EXISTS ( SELECT 1 FROM ' || V_TABLEPDCONFIG || 
						' Y WHERE A.PD_RULE_ID = Y.PKID )';		
    
	DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
   	-----------------------------
    -- Insert config data into GTMP
    -----------------------------
   	
    V_STR_QUERY := '
        INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' (
            PD_RULE_ID, BUCKET_GROUP, HISTORICAL_DATA,
            CURR_DATE, PREV_DATE, CUT_OFF_DATE
        )
        SELECT PKID, BUCKET_GROUP, HISTORICAL_DATA,
            TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''),
            LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), -1 * INCREMENT_PERIOD)),
            START_HISTORICAL_DATE
        FROM ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || '';
    
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
   	----------------------------------------------------------------
    -- Delete existing rows from target which match running_date
    ----------------------------------------------------------------
    
    V_STR_QUERY := '
        DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || 
        ' tgt WHERE tgt.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
          AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM ' || V_TABLEINSERT1 || ')';
         
	  EXECUTE IMMEDIATE V_STR_QUERY;
	  COMMIT;
    -----------------------------
    -- Initial smoothing base
    -----------------------------
    
    V_STR_QUERY := '
        INSERT INTO GTMP_SMOOTHING_BASE (EFF_DATE,PD_RULE_ID,BUCKET_GROUP,BUCKET_FROM,BUCKET_TO,FLOWRATE,SMOOTHED_PD,LOGIT_ODR)
        WITH CTE_INITIAL AS (
		  SELECT A.EFF_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, A.BUCKET_TO, A.FLOWRATE,
		  	LAG(A.FLOWRATE,1,0) OVER (PARTITION BY A.EFF_DATE,A.PD_RULE_ID ORDER BY A.BUCKET_FROM) FLOWRATE_PREV
		  FROM ' || V_TABLESELECT1 || ' A  
		  JOIN ' || V_TABLEINSERT1 || ' B ON A.PD_RULE_ID = B.PD_RULE_ID  
		  LEFT JOIN VW_IFRS_MAX_BUCKET C ON A.BUCKET_GROUP = C.BUCKET_GROUP AND A.BUCKET_TO = C.MAX_BUCKET_ID 
		  WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
		   AND A.BUCKET_TO = C.MAX_BUCKET_ID
		   AND A.BUCKET_FROM > 0  
		),
		CTE_MIN AS (
		  SELECT PD_RULE_ID, MIN(FLOWRATE) MIN_FLOWRATE
		  FROM CTE_INITIAL
		  WHERE FLOWRATE > 0
		  GROUP BY PD_RULE_ID  
		) 
		
		SELECT  A.EFF_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, A.BUCKET_TO, A.FLOWRATE, 
		  CASE WHEN A.FLOWRATE = 0 THEN B.MIN_FLOWRATE ELSE A.FLOWRATE END SMOOTHED_PD, 
		  CASE WHEN (1 - CASE WHEN A.FLOWRATE = 0 THEN B.MIN_FLOWRATE ELSE A.FLOWRATE END) = 0 THEN 0 
		 ELSE
		   LN( CASE WHEN A.FLOWRATE = 0 THEN B.MIN_FLOWRATE ELSE A.FLOWRATE END / (1 - CASE WHEN A.FLOWRATE = 0 THEN B.MIN_FLOWRATE ELSE A.FLOWRATE END) )
		  END AS LOGIT_ODR  
		FROM CTE_INITIAL A
		JOIN CTE_MIN B ON A.PD_RULE_ID  = B.PD_RULE_ID ';
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    ----------------------------------------------------------------
    -- Populate TMP_LOGIT_ODR
    ----------------------------------------------------------------
    BEGIN
    V_STR_QUERY := '
        INSERT INTO GTMP_LOGIT_ODR (PD_RULE_ID, BUCKET_ID, LOGIT_ODR)
        SELECT PD_RULE_ID, BUCKET_ID, LOGIT_ODR FROM (
            SELECT PD_RULE_ID, BUCKET_FROM AS BUCKET_ID,
                   MAX(BUCKET_FROM) OVER (PARTITION BY PD_RULE_ID) MAX_BUCKET,
                   LOGIT_ODR
            FROM GTMP_SMOOTHING_BASE
        ) A
        WHERE A.BUCKET_ID < A.MAX_BUCKET';

    	EXECUTE IMMEDIATE V_STR_QUERY;
    EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
    COMMIT;
	
    PSAK413.SP_IFRS_PD_LINEST_SMOOTHING(P_RUNID,P_PRC);
    ----------------------------------------------------------------
    -- Populate TMP_PD_BASE (add predicted logit & predicted pd)
    ----------------------------------------------------------------
    BEGIN
    V_STR_QUERY := '
        INSERT INTO GTMP_PD_BASE (EFF_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE, SMOOTHED_PD, LOGIT_ODR, PREDICTED_LOGIT_ODR, PREDICTED_PD)
        SELECT A.EFF_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, A.BUCKET_TO, A.FLOWRATE, A.SMOOTHED_PD, A.LOGIT_ODR,
               (B.INTERCEPT + B.SLOPE * A.BUCKET_FROM) AS PREDICTED_LOGIT_ODR,
               (1 / (1 + EXP((B.INTERCEPT + B.SLOPE * A.BUCKET_FROM)* -1))) AS PREDICTED_PD
        FROM GTMP_SMOOTHING_BASE A
        JOIN ' || V_TAB_OWNER || '.' || V_LINEST_SMOOTHING || ' B ON A.PD_RULE_ID = B.PD_RULE_ID';

    	EXECUTE IMMEDIATE V_STR_QUERY;
    EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
    COMMIT;

    ----------------------------------------------------------------
    -- Main loops: iterate BUCKET_FROM = 1 .. V_MAXBUCKET
    ----------------------------------------------------------------
    FOR DATA_PD IN (
		SELECT PD_RULE_ID, MAX(BUCKET_FROM) - 1 AS MAXBUCKET
		FROM GTMP_PD_BASE
		GROUP BY PD_RULE_ID 
		)
	LOOP
		
		V_RESULTPD := NULL;
	    V_CHECK := 1;
		v_loop1 := 1 ;
		
		WHILE V_LOOP1 <= DATA_PD.MAXBUCKET 
		LOOP
			
			v_loop2 := 1 ;
			
			SELECT A.FLOWRATE, A.PREDICTED_PD,
			   	CASE WHEN B.BUCKET_FROM IS NOT NULL THEN DATA_PD.MAXBUCKET  + 1 ELSE A.BUCKET_FROM END,
			   	CASE WHEN B.BUCKET_FROM IS NOT NULL OR A.FLOWRATE = 0 THEN A.PREDICTED_PD ELSE NULL END
		  	INTO v_flowrate1, v_predpd1, v_loop2, v_resultpd
		   	FROM GTMP_PD_BASE A
		  		LEFT JOIN GTMP_PD_RESULT B ON A.BUCKET_FROM = B.BUCKET_FROM + 1 AND A.FLOWRATE < NVL(B.PD_RESULT, 0) AND A.PD_RULE_ID = B.PD_RULE_ID
		  	WHERE A.BUCKET_FROM = v_loop1 AND A.PD_RULE_ID =  DATA_PD.PD_RULE_ID;
			
			WHILE v_LOOP2 <= DATA_PD.MAXBUCKET  
			LOOP
				
				SELECT NVL(FLOWRATE, 0),
			    	NVL(LEAD(FLOWRATE, 1, 999) OVER (ORDER BY BUCKET_FROM), 0),
					PREDICTED_PD
				INTO V_FLOWRATE2, v_nextflowpd, v_predpd2 
			   	FROM GTMP_PD_BASE
			   	WHERE BUCKET_FROM = V_LOOP2 AND PD_RULE_ID = DATA_PD.PD_RULE_ID ;
				
				IF V_FLOWRATE2 < V_FLOWRATE1 OR V_FLOWRATE2 > v_nextflowpd
				THEN
					V_CHECK := 0;
				END IF;
				
				IF V_CHECK = 0
			   	THEN
			    	V_LOOP2 := DATA_PD.MAXBUCKET  + 1;
			   	ELSE
			    	V_LOOP2 := V_LOOP2 + 1;
			   	END IF;
	    
				
			END LOOP ;-- END LOOP2
			
		  	IF V_RESULTPD IS NULL AND V_CHECK = 1
		  	THEN V_RESULTPD := V_FLOWRATE1;
		  	ELSE V_RESULTPD := v_predpd1;
		  	END IF;
	
		  	INSERT INTO GTMP_PD_RESULT
		  	SELECT EFF_DATE, PD_RULE_ID, BUCKET_GROUP, V_LOOP1 BUCKET_FROM, BUCKET_TO, V_FLOWRATE1 FLOWRATE, 
		  		SMOOTHED_PD, LOGIT_ODR, PREDICTED_LOGIT_ODR, v_predpd1 PREDICTED_PD, V_RESULTPD PD_RESULT
		  	FROM 	GTMP_PD_BASE
		  	WHERE BUCKET_FROM = V_LOOP1 AND PD_RULE_ID= DATA_PD.PD_RULE_ID ; 
	  		
		  	COMMIT ; 
	
	  	V_LOOP1 := V_LOOP1 + 1;
	
		END LOOP ;  
		 			
	
		
		EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_SMOOTH'; 
			
		INSERT INTO GTMP_SMOOTH
		SELECT BUCKET_FROM, FLOWRATE, PREDICTED_PD, PD_RESULT,
	  		LAG(PD_RESULT, 1, 0) OVER (PARTITION BY PD_RULE_ID ORDER BY BUCKET_FROM) LAGPD,
	  		LEAD(PD_RESULT, 1, 999) OVER (PARTITION BY PD_RULE_ID ORDER BY BUCKET_FROM) LEADPD, PD_RULE_ID
	 	FROM GTMP_PD_RESULT
	 	ORDER BY BUCKET_FROM;
		
		COMMIT ; 
		
		SELECT COUNT(*) 
		INTO V_LOOP3
		FROM GTMP_SMOOTH
		WHERE FLOWRATE <> PD_RESULT
   			AND FLOWRATE > LAGPD
   			AND FLOWRATE < LEADPD ;
	
		IF V_LOOP3 > 0 
	   	THEN
--		    	MERGE INTO GTMP_PD_RESULT A  
--				USING GTMP_SMOOTH B           
--				ON (A.BUCKET_FROM = B.BUCKET_FROM AND A.PD_RULE_ID = B.PD_RULE_ID)
--				WHEN MATCHED THEN
--				    UPDATE SET A.PD_RESULT =
--				        CASE 
--				            WHEN A.FLOWRATE <> A.PD_RESULT
--				             AND A.FLOWRATE > B.LAGPD
--				             AND A.FLOWRATE < B.LEADPD
--				            THEN A.FLOWRATE  
--				            ELSE A.PD_RESULT  
--				        END;
			MERGE INTO GTMP_PD_RESULT A 
				USING ( SELECT B.BUCKET_FROM, B.PD_RULE_ID, B.LAGPD, B.LEADPD, 
				LEAD(A2.PD_RESULT, 1, 0) OVER ( PARTITION BY A2.PD_RULE_ID ORDER BY A2.BUCKET_FROM ) AS NEXT_PD_RESULT 
				FROM GTMP_SMOOTH B 
				INNER JOIN GTMP_PD_RESULT A2 ON A2.BUCKET_FROM = B.BUCKET_FROM 
					AND A2.PD_RULE_ID = B.PD_RULE_ID ) X ON ( A.BUCKET_FROM = X.BUCKET_FROM AND A.PD_RULE_ID = X.PD_RULE_ID ) 
					WHEN MATCHED THEN 
								UPDATE SET A.PD_RESULT = CASE WHEN A.FLOWRATE <> A.PD_RESULT 
															AND A.FLOWRATE > X.LAGPD 
															AND A.FLOWRATE < X.LEADPD 
															AND X.NEXT_PD_RESULT > A.FLOWRATE 
															THEN A.FLOWRATE 
															ELSE A.PD_RESULT END;
			COMMIT ; 
	   	ELSE
	    	NULL;
	   	END IF;
		
	
	END LOOP;
	
    ----------------------------------------------------------------
    -- Insert final result into target table IFRS_PD_MAA_FLOWRATE_SMOOTH
    ----------------------------------------------------------------
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' (EFF_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE, SMOOTHED_PD, LOGIT_ODR,
	  PREDICTED_LOGIT_ODR, PREDICTED_PD, FLOWRATE_SMOOTH_PD, CREATEDBY, CREATEDDATE, CREATEDHOST)
	SELECT EFF_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE, SMOOTHED_PD, LOGIT_ODR, PREDICTED_LOGIT_ODR, PREDICTED_PD, 
	  PD_RESULT, ''SP_IFRS_PD_MAA_FLOWRATE_SMOOTH'' CREATEDBY, SYSDATE CREATEDDATE, ''LOCALHOST'' CREATEDHOST
	 FROM GTMP_PD_RESULT
	 UNION
	  SELECT EFF_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE, SMOOTHED_PD, LOGIT_ODR, PREDICTED_LOGIT_ODR, PREDICTED_PD, 
	  FLOWRATE FLOWRATE_SMOOTH_PD, ''SP_IFRS_PD_MAA_FLOWRATE_SMOOTH'' CREATEDBY, SYSDATE CREATEDDATE, ''LOCALHOST'' CREATEDHOST
	 FROM GTMP_PD_BASE
	 WHERE BUCKET_FROM = BUCKET_TO';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
   
    V_STR_QUERY := 'MERGE INTO IFRS_PD_MAA_FLOWRATE_SUM A
    USING IFRS_PD_MAA_FLOWRATE_SMOOTH B
        ON (A.EFF_DATE = B.EFF_DATE
        AND A.PD_RULE_ID = B.PD_RULE_ID
        AND A.BUCKET_GROUP = B.BUCKET_GROUP
        AND A.BUCKET_FROM = B.BUCKET_FROM
        AND A.BUCKET_TO = B.BUCKET_TO)
    WHEN MATCHED THEN
    UPDATE SET A.FLOWRATE = B.FLOWRATE_SMOOTH_PD
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';
   
	EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    -----------------------------
    -- Log & insert final data
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT2;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (PD_RULE_ID IN (SELECT PKID FROM ' || V_TABLEPDCONFIG || ') )';

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

END