CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_PD_TM_SCENARIO_DATA
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS
    V_CURRDATE      DATE;
    V_DATADATE      VARCHAR2(20);
    V_TABLE_NAME    VARCHAR2(50);
	V_PREVDATE      DATE;
    V_COUNT         NUMBER;
	V_MODEL_ID      VARCHAR2(22);

-- DYNAMIC NAMES / QUERY
    V_STR_QUERY     CLOB;

    -- TABLE NAMES
    V_TAB_OWNER     CONSTANT 		VARCHAR2(30) := 'PSAK413';
    V_IFRS_SCENARIO_DATA  			VARCHAR2(100);
    V_TMP_SCENARIO_DATA  			VARCHAR2(100);
    V_IFRS_PD_SCENARIO_DATA 		VARCHAR2(100);
    V_TABLEPDCONFIG 				VARCHAR2(100);

    -- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME        VARCHAR2(100) := 'SP_IFRS_PD_TM_SCENARIO_DATA';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        CLOB;
    V_RETURNROWS2   NUMBER;
    
    V_STR_SQL        CLOB;
    V_STR_SQL_RULE   CLOB;
    V_RULE_ID        VARCHAR2(250);
    V_ID             NUMBER := 0;
    V_MAX_ID         NUMBER := 0;
    V_STR_SQLPD      CLOB;
    V_SEQUENCE       VARCHAR2(50);
    
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, -1));
    V_MODEL_ID := 0;

    -- CHOOSE TABLE NAMES BASED ON MODE
    IF P_PRC = 'S' THEN
        V_IFRS_SCENARIO_DATA  := 'IFRS_PD_RULE_DATA_' || P_RUNID;
        V_TMP_SCENARIO_DATA  := 'TMP_SCENARIO_DATA_' || P_RUNID;
        V_IFRS_PD_SCENARIO_DATA := 'IFRS_PD_SCENARIO_DATA_' || P_RUNID;
    	V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG_' || P_RUNID;
    ELSE
        V_IFRS_SCENARIO_DATA  := 'IFRS_PD_RULE_DATA';
        V_TMP_SCENARIO_DATA  := 'TMP_SCENARIO_DATA';
        V_IFRS_PD_SCENARIO_DATA := 'IFRS_PD_SCENARIO_DATA';
    	V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG';
    END IF;

    BEGIN
        SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSTIMESTAMP);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('WARNING: SP_IFRS_RUNNING_LOG FAILED: ' || SQLERRM);
    END;
    COMMIT;

    IF P_PRC = 'S' THEN
    	        
    	-- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_TMP_SCENARIO_DATA);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TMP_SCENARIO_DATA;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TMP_SCENARIO_DATA || ' AS SELECT * FROM TMP_SCENARIO_DATA WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        
    	-- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_IFRS_PD_SCENARIO_DATA);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA || ' AS SELECT * FROM IFRS_PD_SCENARIO_DATA WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
    
        -- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_TABLEPDCONFIG);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' AS SELECT * FROM IFRS_PD_RULES_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;

        COMMIT;
    ELSE
       	EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TMP_SCENARIO_DATA || '';
	    
	    COMMIT;
    
    END IF;
   
   EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TABLEPDCONFIG || '' ; 
	 
    V_STR_QUERY := 'INSERT INTO ' || V_TABLEPDCONFIG || ' (PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)' ||
               'SELECT PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE' || 
					 	' FROM IFRS_PD_RULES_CONFIG ' ||
               'WHERE PD_METHOD = ''MAA'' AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0'' 
               )';
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
    ---------------------------------------------------------------------

   ----------------------------------------------------------------
    -- TRUNCATE TMP_SCENARIO_DATA then populate it from IFRS_SCENARIO_DATA
    ----------------------------------------------------------------
    V_STR_QUERY := '
        INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_SCENARIO_DATA || ' (
            DOWNLOAD_DATE, MASTERID, PD_RULE_ID, RULE_ID, SEGMENT, SUB_SEGMENT, GROUP_SEGMENT, RULE_TYPE, RATING_CODE,
            DAY_PAST_DUE, DPD_CIF, BI_COLLECTABILITY, WRITEOFF_FLAG, KEY_TMP_IMA, ACCOUNT_NUMBER, ACCOUNT_STATUS,
            CUSTOMER_NUMBER, CUSTOMER_NAME, EXCHANGE_RATE, IMPAIRED_FLAG, OUTSTANDING, FAIR_VALUE_AMOUNT, EARLY_ALERT_FLAG, FACILITY_NUMBER, CUSTOMER_GRADE
        )
        SELECT A.DOWNLOAD_DATE, A.MASTERID, B.PKID AS PD_RULE_ID, A.RULE_ID, A.SEGMENT, A.SUB_SEGMENT, A.GROUP_SEGMENT, A.RULE_TYPE,
               A.RATING_CODE, A.DAY_PAST_DUE, A.DAY_PAST_DUE_CIF, A.BI_COLLECTABILITY, A.WRITEOFF_FLAG,
               CASE
                 WHEN B.CALC_METHOD IN (''CNOC'',''COS'',''CVS'') THEN A.CUSTOMER_NUMBER
                 WHEN B.CALC_METHOD IN (''ANOA'',''ACA'',''AVS'') THEN A.MASTERID
                 WHEN B.CALC_METHOD = ''FNOF'' THEN A.FACILITY_NUMBER
                 ELSE A.MASTERID
               END AS KEY_TMP_IMA, A.ACCOUNT_NUMBER, A.ACCOUNT_STATUS, A.CUSTOMER_NUMBER, A.CUSTOMER_NAME, A.EXCHANGE_RATE, A.IMPAIRED_FLAG, A.OUTSTANDING,
               A.FAIR_VALUE_AMOUNT, A.EARLY_ALERT_FLAG, A.FACILITY_NUMBER, A.CUSTOMER_GRADE
        FROM ' || V_TAB_OWNER || '.' || V_IFRS_SCENARIO_DATA || ' A
        INNER JOIN ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' B
            ON A.RULE_ID = B.SEGMENTATION_ID
           AND A.DOWNLOAD_DATE = :V_CURRDATE
        WHERE B.PD_METHOD = ''MAA''';

    EXECUTE IMMEDIATE V_STR_QUERY
        USING V_CURRDATE;

    -- UNION ALL part: historical dates (EOMONTH equivalent)
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_SCENARIO_DATA || ' (
        DOWNLOAD_DATE, MASTERID, PD_RULE_ID, RULE_ID, SEGMENT, SUB_SEGMENT, GROUP_SEGMENT, RULE_TYPE, RATING_CODE, DAY_PAST_DUE, DPD_CIF,
        BI_COLLECTABILITY, WRITEOFF_FLAG, KEY_TMP_IMA, ACCOUNT_NUMBER, ACCOUNT_STATUS, CUSTOMER_NUMBER, CUSTOMER_NAME, EXCHANGE_RATE,
        IMPAIRED_FLAG, OUTSTANDING, FAIR_VALUE_AMOUNT, EARLY_ALERT_FLAG, FACILITY_NUMBER, CUSTOMER_GRADE
    )
    SELECT A.DOWNLOAD_DATE, A.MASTERID, B.PKID AS PD_RULE_ID, A.RULE_ID, A.SEGMENT, A.SUB_SEGMENT, A.GROUP_SEGMENT, A.RULE_TYPE,
           A.RATING_CODE, A.DAY_PAST_DUE, A.DAY_PAST_DUE_CIF, A.BI_COLLECTABILITY, A.WRITEOFF_FLAG,
           CASE
             WHEN B.CALC_METHOD IN (''CNOC'',''COS'',''CVS'') THEN A.CUSTOMER_NUMBER
             WHEN B.CALC_METHOD IN (''ANOA'',''ACA'',''AVS'') THEN A.MASTERID
             WHEN B.CALC_METHOD = ''FNOF'' THEN A.FACILITY_NUMBER
             ELSE A.MASTERID
           END AS KEY_TMP_IMA, A.ACCOUNT_NUMBER, A.ACCOUNT_STATUS, A.CUSTOMER_NUMBER, A.CUSTOMER_NAME, A.EXCHANGE_RATE, A.IMPAIRED_FLAG, A.OUTSTANDING,
           A.FAIR_VALUE_AMOUNT, A.EARLY_ALERT_FLAG, A.FACILITY_NUMBER, A.CUSTOMER_GRADE
    FROM ' || V_TAB_OWNER || '.' || V_IFRS_SCENARIO_DATA || ' A
    INNER JOIN ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' B
        ON A.RULE_ID = B.SEGMENTATION_ID
       AND A.DOWNLOAD_DATE = LAST_DAY(ADD_MONTHS(:V_CURRDATE, - B.INCREMENT_PERIOD))
    WHERE (
           (B.INCLUDE_INDIVIDUAL_ACCOUNT = 0 AND A.IMPAIRED_FLAG = ''C'')
           OR (B.INCLUDE_INDIVIDUAL_ACCOUNT <> 0)
          )
      AND B.PD_METHOD = ''MAA''' ;
    
    EXECUTE IMMEDIATE V_STR_QUERY
        USING V_CURRDATE;

    ----------------------------------------------------------------
    -- TRUNCATE IFRS_PD_SCENARIO_DATA and populate from joins
    ----------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA || '';

     V_STR_QUERY := '
        INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA || ' (
            PERIOD, PD_RULE_ID, RULE_ID, BUCKET_GROUP, MASTERID, CUSTOMER_NUMBER, PD_UNIQUE_ID, PD_METHOD, CALC_METHOD, CALC_AMOUNT, BUCKET_ID,
            OUTSTANDING, FAIR_VALUE_AMOUNT, ACCOUNT_STATUS, IMPAIRED_FLAG, IS_IMPAIRED, WRITEOFF_FLAG
        )
        SELECT B.DOWNLOAD_DATE, A.PKID, A.SEGMENTATION_ID, A.BUCKET_GROUP, B.MASTERID, B.CUSTOMER_NUMBER, B.KEY_TMP_IMA AS PD_UNIQUE_ID, A.PD_METHOD, A.CALC_METHOD,
               CASE
                 WHEN A.CALC_METHOD IN (''MNOA'',''ANOA'') THEN 1
                 WHEN A.CALC_METHOD = ''CNOC'' THEN
                    CASE
                      WHEN B.MASTERID = MAX(B.MASTERID)
                           OVER (PARTITION BY A.PKID, B.DOWNLOAD_DATE, B.CUSTOMER_NUMBER)
                      THEN 1 ELSE 0
                    END
                 WHEN A.CALC_METHOD IN (''CVS'',''AVS'')
                      THEN B.FAIR_VALUE_AMOUNT * B.EXCHANGE_RATE
                 WHEN A.CALC_METHOD = ''FNOF'' THEN
                    CASE
                      WHEN B.MASTERID = MAX(B.MASTERID)
                           OVER (PARTITION BY A.PKID, B.DOWNLOAD_DATE, B.FACILITY_NUMBER)
                      THEN 1 ELSE 0
                    END
                 ELSE B.OUTSTANDING * B.EXCHANGE_RATE
               END AS CALC_AMOUNT, E.BUCKET_ID, B.OUTSTANDING * B.EXCHANGE_RATE AS OUTSTANDING, B.FAIR_VALUE_AMOUNT * B.EXCHANGE_RATE AS FAIR_VALUE_AMOUNT,
               B.ACCOUNT_STATUS, B.IMPAIRED_FLAG, 0 AS IS_IMPAIRED, B.WRITEOFF_FLAG
        FROM ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' A
        JOIN ' || V_TAB_OWNER || '.' || V_TMP_SCENARIO_DATA || ' B
          ON B.PD_RULE_ID = A.PKID
         AND B.DOWNLOAD_DATE >= A.START_HISTORICAL_DATE
        JOIN IFRS_BUCKET_HEADER C
          ON C.BUCKET_GROUP = A.BUCKET_GROUP
        JOIN IFRS_BUCKET_DETAIL E
          ON E.BUCKET_GROUP = A.BUCKET_GROUP
         AND (
              (
                (
                  CASE
                    WHEN C.OPTION_GROUPING = ''DPD_ACCT'' THEN B.DAY_PAST_DUE
                    WHEN C.OPTION_GROUPING = ''DPD_CIF''  THEN B.DPD_CIF
                    WHEN C.OPTION_GROUPING = ''BIC''      THEN B.BI_COLLECTABILITY
                  END
                ) BETWEEN E.RANGE_START AND E.RANGE_END
              )
              OR (C.OPTION_GROUPING = ''IR'' AND E.BUCKET_NAME = B.CUSTOMER_GRADE)
              OR (C.OPTION_GROUPING = ''ER'' AND E.BUCKET_NAME = B.RATING_CODE)
             )
        JOIN VW_IFRS_MAX_BUCKET D
          ON D.BUCKET_GROUP = C.BUCKET_GROUP
        WHERE B.DOWNLOAD_DATE >= A.START_HISTORICAL_DATE
          AND A.PD_METHOD = ''MAA'' ';

    EXECUTE IMMEDIATE V_STR_QUERY;

	-----------------------------
    -- Log & insert final data
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_SCENARIO_DATA ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (PD_RULE_ID IN (SELECT PKID FROM ' || V_TABLEPDCONFIG || ') OR ''' || V_MODEL_ID || ''' = ''0'')';

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- ROLLBACK TO SAFE STATE AND RE-RAISE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR IN SP_IFRS_PD_TM_SCENARIO_DATA: ' || SQLERRM);
        RAISE;
END