CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_IFRS_LGD_RULE_DATA
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'X'
) 
AUTHID CURRENT_USER
AS
	---- DATE   
    V_CURRDATE DATE; 
	V_EOMDATE DATE ;  

	---- PROCESS
	V_COUNT NUMBER;
	V_RULE_ID VARCHAR2(10);
	V_ID NUMBER DEFAULT 0; 
	V_MAX_ID NUMBER DEFAULT 0; 
	V_DATADATE VARCHAR(20); 
    ---- QUERY  
    V_STR_QUERY CLOB;
	V_STR_SQL_RULE CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);
 
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CASE 
        		WHEN CURRDATE = LAST_DAY(CURRDATE) THEN CURRDATE
        		ELSE LAST_DAY(ADD_MONTHS(CURRDATE, -1))
    		END, LAST_DAY(CURRDATE)
        INTO V_CURRDATE,V_EOMDATE 
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
 
 	IF V_CURRDATE = V_EOMDATE THEN   
 		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY' ;
 	ELSE 
 		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY';
 	END IF ;
 	 V_TABLELGDCONFIG := 'GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG';
 	
    IF P_PRC = 'S' THEN 

        V_TABLEINSERT1 := 'IFRS_LGD_RULE_DATA_' || P_RUNID || ''; 
    ELSE 

        V_TABLEINSERT1 := 'IFRS_LGD_RULE_DATA'; 
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, 'SP_IFRS_LGD_RULE_DATA', P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG' ; 
	 
    V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG
               SELECT * FROM IFRS_LGD_WORKOUT_RULES_CONFIG
               WHERE    IS_DELETED = 0 AND (  
                 UPPER(TRIM(SYSCODE_WORKOUT)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0''
               )';
  DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
        

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE CONFIG
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1); 
        
		IF V_COUNT > 0 THEN 
		 V_STR_QUERY := '';
         V_STR_QUERY := V_STR_QUERY || 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ';
        EXECUTE IMMEDIATE (V_STR_QUERY);
		END IF;

        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LGD_RULE_DATA WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
        
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_' || V_TABLEINSERT1 || ' ON ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '(DOWNLOAD_DATE, RULE_ID , MASTERID)';
    END IF;
	COMMIT;
        
    V_STR_QUERY := 'TRUNCATE TABLE ' || V_TABLEINSERT1;
   
    EXECUTE IMMEDIATE (V_STR_QUERY) ; 

	  
    
    V_STR_QUERY := 'SELECT MAX(PKID) 
	FROM IFRS_SEGMENTATION_MAPPING A 
	WHERE EXISTS (SELECT * FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE X.SEGMENTATION_ID = A.PKID) ';

    EXECUTE IMMEDIATE V_STR_QUERY INTO V_MAX_ID;
    
    V_ID := 0 ;

    WHILE V_ID < V_MAX_ID LOOP
	    V_STR_QUERY := '
        SELECT MIN(PKID) 
		FROM IFRS_SEGMENTATION_MAPPING A 
		WHERE EXISTS (SELECT * FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE X.SEGMENTATION_ID = A.PKID) 
        AND A.PKID > :V_ID';

    	EXECUTE IMMEDIATE V_STR_QUERY
        INTO V_ID
        USING V_ID;
		
    	V_STR_QUERY :=
        'SELECT PKID, MERGE_SQL_CONDITIONS, TO_CHAR(:dt, ''YYYY-MM-DD'')
         FROM IFRS_SEGMENTATION_MAPPING
         WHERE PKID = :x';

    	EXECUTE IMMEDIATE V_STR_QUERY
        INTO V_RULE_ID, V_STR_SQL_RULE, V_DATADATE
        USING V_CURRDATE,V_ID;
    	
    	COMMIT;
        -----------------------------------------------------------------
        -- BUILD FINAL DYNAMIC SQL
        -----------------------------------------------------------------
        V_STR_QUERY :=
            'INSERT INTO ' || V_TABLEINSERT1 ||' (' ||
            'DOWNLOAD_DATE, RULE_ID, MASTERID, CUSTOMER_NUMBER, FACILITY_NUMBER,' ||
			'ACCOUNT_STATUS,OUTSTANDING, ' ||
            'IMPAIRED_FLAG, LOAN_START_DATE, LOAN_DUE_DATE, CREATED_DATE, CREATED_BY) ' ||

            'SELECT DOWNLOAD_DATE, ' || V_RULE_ID || ', MASTERID, CUSTOMER_NUMBER, FACILITY_NUMBER,' ||
            'ACCOUNT_STATUS, OUTSTANDING, ' ||
            'IMPAIRED_FLAG, LOAN_START_DATE, LOAN_DUE_DATE, SYSDATE, ''SP_IFRS_LGD_RULE_DATA'' ' ||
            'FROM ' || V_TABLE_NAME ||   
            ' IFRS_MASTER_ACCOUNT WHERE ACCOUNT_STATUS IN (''A'',''W'') ' ||
            '  AND DOWNLOAD_DATE = DATE ''' || V_DATADATE || ''' ' ||
            '  AND (' || V_STR_SQL_RULE || ')';

     
       DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
         EXECUTE IMMEDIATE V_STR_QUERY;

    END LOOP;
    
    
     

    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_SPNAME := 'SP_IFRS_LGD_RULE_DATA';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_STR_QUERY := 'SELECT * FROM ' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_STR_QUERY, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END