CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.SP_MULTIJASA
BEGIN
	
	
		INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
		(
			 DOWNLOAD_DATE
			,MASTERID
			,MASTER_ACCOUNT_CODE
			,DATA_SOURCE
			,PRODUCT_TYPE 
			,PRODUCT_CODE 
			,BRANCH_CODE 
			,ACCOUNT_STATUS 
			,ACCOUNT_NUMBER 
			,CUSTOMER_NUMBER 
			,CUSTOMER_NAME 
			,CURRENCY 
			,EXCHANGE_RATE 
			,OUTSTANDING 
			,PLAFOND 
			,MARGIN_RATE 
			,EIR 
			,FAIR_VALUE_AMOUNT 
			,DAY_PAST_DUE 
			,DPD_CIF 
			,BI_COLLECTABILITY 
			,BI_COLLECT_CIF 
			,STAFF_LOAN_FLAG 
			,COLL_AMOUNT 
			,UNAMORT_FEE_AMT 
			,UNAMORT_COST_AMT 
			,MARGIN_TYPE 
			,DEFAULT_DATE 
			,LOAN_START_DATE 
			,LOAN_DUE_DATE 
			,DIVISION_CODE 
			,RESTRUCTURE_FLAG 
			,OUTSTANDING_PAST_DUE 
			,MARGIN_PAST_DUE 
		)
		
		
		SELECT 
			 TO_DATE(FICMISDATE, 'DD/MM/YYYY HH24:MI:SS')  AS DOWNLOAD_DATE
			,IMI.MASTERID
			,'MULTIJASA_'||NOMORREKENING AS MASTER_ACCOUNT_CODE
			,'MULTIJASA' AS DATA_SOURCE
			,'IJARAH' AS PRODUCT_TYPE 
			,LOANTYPECODE AS PRODUCT_CODE 
			,KODECABANG AS BRANCH_CODE 
			,'A' AS ACCOUNT_STATUS 
			,NOMORREKENING AS ACCOUNT_NUMBER 
			,NOMORNASABAH AS CUSTOMER_NUMBER 
			,NAMANASABAH AS CUSTOMER_NAME 
			,JENISVALUTA AS CURRENCY 
			,1 AS EXCHANGE_RATE 
			,NOMINAL AS OUTSTANDING 
			,NULL AS PLAFOND 
			,NULL AS MARGIN_RATE 
			,NULL AS EIR 
			,NOMINAL AS FAIR_VALUE_AMOUNT 
			,TUNGGAKAN_HARI AS DAY_PAST_DUE 
			,TUNGGAKAN_HARI AS DPD_CIF 
			,KUALITAS AS BI_COLLECTABILITY 
			,KUALITAS AS BI_COLLECT_CIF 
			,NULL AS STAFF_LOAN_FLAG 
			,NULL AS COLL_AMOUNT 
			,NULL AS UNAMORT_FEE_AMT 
			,NULL AS UNAMORT_COST_AMT 
			,NULL AS MARGIN_TYPE 
			,NULL AS DEFAULT_DATE 
			,TO_DATE(JANGKAWAKTU_MULAI , 'DD/MM/YYYY HH24:MI:SS') AS LOAN_START_DATE 
			,TO_DATE(JANGKAWAKTU_JATUHTEMPO , 'DD/MM/YYYY HH24:MI:SS') AS LOAN_DUE_DATE 
			,DIVISIPISAH AS DIVISION_CODE 
			,CASE WHEN SIFATPEMBIAYAAN IN ('1', '5') THEN 1 ELSE 0 END RESTRUCTURE_FLAG
			,TUNGGAKAN_POKOK AS OUTSTANDING_PAST_DUE
			,TUNGGAKAN_IMBALAN AS MARGIN_PAST_DUE
		FROM 
		IMPORT_MULTIJASA_DEC pmam 
		LEFT JOIN
		IFRS_MASTER_ID IMI
		ON
		'MULTIJASA'||TRIM(NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE;

END