CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.X_IFRS_POPULATE_IMAM_FROM_PMAM
   V_CURRDATE  DATE;
   V_PREVDATE  DATE; 
BEGIN

SELECT CURRDATE, PREVDATE INTO V_CURRDATE, V_PREVDATE
FROM IFRS_PRC_DATE;

DELETE FROM IFRS_MASTER_ACCOUNT_MONTHLY
WHERE DOWNLOAD_DATE = V_CURRDATE;

INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,GLOBAL_CUSTOMER_NUMBER
	,CUSTOMER_NUMBER
	,CUSTOMER_NAME
	,FACILITY_NUMBER
	,ACCOUNT_NUMBER
	,PREVIOUS_ACCOUNT_NUMBER
	,ACCOUNT_STATUS
	,MARGIN_RATE
	,MARKET_RATE
	,PRODUCT_GROUP
	,PRODUCT_TYPE
	,PRODUCT_CODE
	,PRODUCT_ENTITY
	,GL_CONSTNAME
	,BRANCH_CODE
	,BRANCH_CODE_OPEN
	,CURRENCY
	,EXCHANGE_RATE
	,OUTSTANDING
	,OUTSTANDING_PASTDUE
	,PLAFOND
	,MARGIN_ACCRUED
	,LOAN_START_DATE
	,LOAN_DUE_DATE
	,TENOR
	,PAYMENT_CODE
	,PAYMENT_TERM
	,MARGIN_CALCULATION_CODE
	,MARGIN_PAYMENT_Term
	,RESTRUCTURE_DATE
	,RESTRUCTURE_FLAG
	,ORIGINAL_COLLECTABILITY
	,BI_COLLECTABILITY
	,DAY_PAST_DUE
	,GROUP_SEGMENT
	,SEGMENT
	,SUB_SEGMENT
	,STAGE
	,UNAMORT_COST_AMT
	,UNAMORT_FEE_AMT
	,CREATEDDATE
	,CREATEDBY
	,STAFF_LOAN_FLAG
)
SELECT
	 A.DOWNLOAD_DATE
	,A.MASTER_ACCOUNT_ID AS MASTERID
	,A.MASTER_ACCOUNT_ID AS MASTER_ACCOUNT_CODE
	,A.DATA_SOURCE
	,NULL GLOBAL_CUSTOMER_NUMBER
	,A.CUSTOMER_NUMBER
	,A.CUSTOMER_NAME
	,NULL FACILITY_NUMBER
	,A.ACCOUNT_NUMBER
	,NULL PREVIOUS_ACCOUNT_NUMBER
	,A.ACCOUNT_STATUS
	,A.INTEREST_RATE AS MARGIN_RATE
	,NULL MARKET_RATE
	,A.PRODUCT_GROUP
	,A.PRODUCT_TYPE
	,A.PRODUCT_CODE
	,NULL AS PRODUCT_ENTITY
	,NULL AS GL_CONSTNAME
	,A.BRANCH_CODE
	,NULL AS BRANCH_CODE_OPEN
	,A.CURRENCY
	,A.EXCHANGE_RATE
	,A.OUTSTANDING
	,NULL AS OUTSTANDING_PASTDUE
	,A.PLAFOND
	,NULL AS MARGIN_ACCRUED
	,B.LOAN_START_DATE AS LOAN_START_DATE
	,B.LOAN_DUE_DATE AS LOAN_DUE_DATE
	,NULL AS TENOR
	,NULL AS PAYMENT_CODE
	,NULL AS PAYMENT_TERM
	,NULL AS MARGIN_CALCULATION_CODE
	,NULL AS MARGIN_PAYMENT_TERM
	,NULL AS RESTRUCTURE_DATE
	,NULL AS RESTRUCTURE_FLAG
	,A.BI_COLLECTABILITY AS ORIGINAL_COLLECTABILITY
	,A.BI_COLLECTABILITY
	,A.DAY_PAST_DUE
	,NULL AS GROUP_SEGMENT
	,A.SEGMENT
	,NULL AS SUB_SEGMENT
	,NULL AS STAGE
	,A.UNAMOR_TRANS_COST_AMT AS UNAMORT_COST_AMT
	,A.UNAMOR_ORIGINATION_FEE_AMT AS UNAMORT_FEE_AMT
	,SYSDATE AS CREATEDDATE
	,'DUMMY' AS CREATEDBY
	,CASE WHEN NVL(A.STAFF_LOAN_FLAG,'N') = 'N' THEN 0 ELSE 1 END
FROM PSAK_MASTER_ACCOUNT_MONTHLY A
LEFT JOIN
TABLENYA_ADAM B
ON
A.DOWNLOAD_DATE = 
TO_DATE
(
	TO_CHAR
	(
         TO_TIMESTAMP(B.DOWNLOAD_DATE, 'YYYY-MM-DD HH24:MI:SS.FF'),'YYYY-MM-DD'
    ), 'YYYY-MM-DD'
)
AND
A.MASTER_ACCOUNT_ID = B.MASTER_ACCOUNT_ID
WHERE 
A.DOWNLOAD_DATE = V_CURRDATE;



END