CREATE OR REPLACE EDITIONABLE PROCEDURE PSAK413.XSP_IFRS_EAD_RESULT2
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS 
    V_CURRDATE       DATE;
    V_DATADATE       VARCHAR2(20);
    V_TABLE_NAME     VARCHAR2(50);
    V_COUNT          NUMBER;
	V_MODEL_ID       NUMBER;

-- DYNAMIC NAMES / QUERY
    V_STR_QUERY      CLOB;

    -- TABLE NAMES
    V_TAB_OWNER     CONSTANT 		VARCHAR2(30) := 'PSAK413';
    V_IFRS_PAYM_SCHD_ALL 			VARCHAR2(100);
    V_IFRS_EIL_IMA					VARCHAR2(100);
    V_TABLEPDCONFIG					VARCHAR2(100);
    V_IFRS_EAD_RESULT				VARCHAR2(100);

    -- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_EAD_RESULT';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        VARCHAR2(8000);
    V_RETURNROWS2   NUMBER;
    
    V_STR_SQL        CLOB;
    V_STR_SQL_RULE   CLOB;
    V_RULE_ID        VARCHAR2(250);
    V_ID             NUMBER := 0;
    V_MAX_ID         NUMBER := 0;
    V_SEQUENCE       VARCHAR2(50);
    
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := 0;

    -- CHOOSE TABLE NAMES BASED ON MODE
    IF P_PRC = 'S' THEN 
        V_IFRS_EIL_IMA  		:= 'IFRS_EIL_IMA_' || P_RUNID;
        V_IFRS_EAD_RESULT		:= 'IFRS_EAD_RESULT_' || P_RUNID; 
    ELSE 
        V_IFRS_EIL_IMA  		:= 'IFRS_EIL_IMA'; 
    	V_IFRS_EAD_RESULT		:= 'IFRS_EAD_RESULT';
    END IF;

    BEGIN
        SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSTIMESTAMP);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('WARNING: SP_IFRS_RUNNING_LOG FAILED: ' || SQLERRM);
    END;
    COMMIT;

    IF P_PRC = 'S' THEN
        
        -- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_IFRS_PAYM_SCHD_ALL);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PAYM_SCHD_ALL;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PAYM_SCHD_ALL || ' AS SELECT * FROM IFRS_EAD_RESULT WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
    ELSE
    	    
	   	EXECUTE IMMEDIATE 'DELETE FROM ' || V_IFRS_EAD_RESULT || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''' ' ;
   
    END IF;
   
    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_PAYM_SCHD_EAD' ; 
    COMMIT;
   
    V_STR_QUERY := '
	INSERT INTO GTMP_IFRS_PAYM_SCHD_EAD (DOWNLOAD_DATE, MASTERID, PMTDATE, SEQ, PRINCIPAL, SUM_PRINCIPAL)
		WITH CTE_INIT AS ( ' ||
		'	SELECT MAX(DOWNLOAD_DATE) AS DOWNLOAD_DATE, MASTERID ' ||
		'	FROM IFRS_INITIAL_PAYM_SCHD ' ||
		'	WHERE DOWNLOAD_DATE <= ''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''' 
			GROUP BY MASTERID ' ||
		'), 
		CTE AS ( ' ||
		'SELECT A.DOWNLOAD_DATE , A.MASTERID ,A.PMTDATE ,MONTHS_BETWEEN(LAST_DAY(A.PMTDATE),A.DOWNLOAD_DATE) AS SEQ ,A.PRINCIPAL , ' ||
		'	SUM(A.PRINCIPAL) OVER (PARTITION BY A.MASTERID, A.DOWNLOAD_DATE ORDER BY A.PMTDATE) SUM_PRINCIPAL ' ||
		'	FROM IFRS_PAYM_SCHD_ALL A ' ||
		'	WHERE DOWNLOAD_DATE  <= ''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || '''
				AND PMTDATE > ''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || '''
				AND EXISTS(SELECT 1 FROM CTE_INIT X WHERE X.DOWNLOAD_DATE = A.DOWNLOAD_DATE AND X.MASTERID = A.MASTERID)
			GROUP BY A.DOWNLOAD_DATE , A.MASTERID ,A.PMTDATE ,MONTHS_BETWEEN(LAST_DAY(A.PMTDATE),A.DOWNLOAD_DATE) ,A.PRINCIPAL
		SELECT DOWNLOAD_DATE, MASTERID, PMTDATE,SEQ, PRINCIPAL, SUM_PRINCIPAL
		FROM CTE ';
				
	EXECUTE IMMEDIATE V_STR_QUERY;
	COMMIT;

	V_STR_QUERY := 'INSERT INTO IFRS_EAD_RESULT(DOWNLOAD_DATE, MASTERID, GROUP_SEGMENT, SEGMENT, SUB_SEGMENT, RATING_CODE, DAY_PAST_DUE, BI_COLLECTABILITY,
					 ACCOUNT_NUMBER, ACCOUNT_STATUS, CUSTOMER_NUMBER, CUSTOMER_NAME, EXCHANGE_RATE, IMPAIRED_FLAG, OUTSTANDING, BUCKET_ID, REVOLVING_FLAG, 
					 PRODUCT_CODE, PRODUCT_TYPE, PLAFOND, LOAN_START_DATE, DAY_PAST_DUE_CIF, RESTRUCTURE_FLAG, EIR, LOAN_DUE_DATE, MARGIN_PAST_DUE, SEGMENTATION_ID,
					 LT_RULE_ID, CUSTOMER_GRADE, PRODUCT_ENTITY, DATA_SOURCE, PRODUCT_GROUP, IS_IMPAIRED, IFRS9_CLASS, PD_SEGMENT, LGD_SEGMENT, EAD_SEGMENT, BUCKET_GROUP,
					 LIFETIME, STAGE, UNAMORT_COST_AMT, UNAMORT_FEE_AMT, MARGIN_ACCRUED, FAIR_VALUE_AMOUNT, EAD_BALANCE, EAD_MARGIN, EIL_MODEL_ID, EAD_RULE_ID, LGD_RULE_ID,
					 LGD_ME_MODEL_ID, PD_RULE_ID, PD_ME_MODEL_ID, CURRENCY, EIL_AMOUNT, FLAG_VAS, UNUSED_AMOUNT, EAD_TYPE, SEQ, EAD_PRINCIPAL, CREATEDBY, CREATEDDATE)
					WITH CTE_SEQ AS (
					SELECT 1 SEQ , 600 MAX_SEQ FROM DUAL 
					UNION ALL 
					SELECT SEQ+1, MAX_SEQ 
					FROM CTE 
					WHERE SEQ+1 < MAX_SEQ
					),
					
					SELECT B.DOWNLOAD_DATE, B.MASTERID, B.GROUP_SEGMENT, B.SEGMENT, B.SUB_SEGMENT, B.RATING_CODE, B.DAY_PAST_DUE, B.BI_COLLECTABILITY, B.ACCOUNT_NUMBER,
					 B.ACCOUNT_STATUS, B.CUSTOMER_NUMBER, B.CUSTOMER_NAME, B.EXCHANGE_RATE, B.IMPAIRED_FLAG, B.OUTSTANDING, B.BUCKET_ID, B.REVOLVING_FLAG, B.PRODUCT_CODE,
					 B.PRODUCT_TYPE, B.PLAFOND, B.LOAN_START_DATE, B.DAY_PAST_DUE_CIF, B.RESTRUCTURE_FLAG, B.EIR, B.LOAN_DUE_DATE, B.MARGIN_PAST_DUE, B.SEGMENTATION_ID,
					 B.LT_RULE_ID, B.CUSTOMER_GRADE, B.PRODUCT_ENTITY, B.DATA_SOURCE, B.PRODUCT_GROUP, B.IS_IMPAIRED, B.IFRS9_CLASS, B.PD_SEGMENT, B.LGD_SEGMENT,
					 B.EAD_SEGMENT, B.BUCKET_GROUP, B.LIFETIME, B.STAGE, B.UNAMORT_COST_AMT, B.UNAMORT_FEE_AMT, B.MARGIN_ACCRUED, B.FAIR_VALUE_AMOUNT, B.EAD_BALANCE,
					 B.EAD_MARGIN, B.EIL_MODEL_ID, B.EAD_RULE_ID, B.LGD_RULE_ID, B.LGD_ME_MODEL_ID, B.PD_RULE_ID, B.PD_ME_MODEL_ID, B.CURRENCY, B.EIL_AMOUNT,
					 B.FLAG_VAS, B.UNUSED_AMOUNT, B.EAD_TYPE,0 SEQ, B.EAD_PRINCIPAL, ''SP_IFRS_EAD_RESULT'' AS CREATEDBY, SYSDATE AS CREATEDDATE
					FROM IFRS_EIL_IMA B 
					UNION ALL 
					SELECT B.DOWNLOAD_DATE, B.MASTERID, B.GROUP_SEGMENT, B.SEGMENT, B.SUB_SEGMENT, B.RATING_CODE, B.DAY_PAST_DUE, B.BI_COLLECTABILITY, B.ACCOUNT_NUMBER,
					 B.ACCOUNT_STATUS, B.CUSTOMER_NUMBER, B.CUSTOMER_NAME, B.EXCHANGE_RATE, B.IMPAIRED_FLAG, B.OUTSTANDING, B.BUCKET_ID, B.REVOLVING_FLAG, B.PRODUCT_CODE,
					 B.PRODUCT_TYPE, B.PLAFOND, B.LOAN_START_DATE, B.DAY_PAST_DUE_CIF, B.RESTRUCTURE_FLAG, B.EIR, B.LOAN_DUE_DATE, B.MARGIN_PAST_DUE, B.SEGMENTATION_ID,
					 B.LT_RULE_ID, B.CUSTOMER_GRADE, B.PRODUCT_ENTITY, B.DATA_SOURCE, B.PRODUCT_GROUP, B.IS_IMPAIRED, B.IFRS9_CLASS, B.PD_SEGMENT, B.LGD_SEGMENT,
					 B.EAD_SEGMENT, B.BUCKET_GROUP, B.LIFETIME, B.STAGE, B.UNAMORT_COST_AMT, B.UNAMORT_FEE_AMT, B.MARGIN_ACCRUED, B.FAIR_VALUE_AMOUNT, B.EAD_BALANCE,
					 A.EAD_MARGIN, B.EIL_MODEL_ID, B.EAD_RULE_ID, B.LGD_RULE_ID, B.LGD_ME_MODEL_ID, B.PD_RULE_ID, B.PD_ME_MODEL_ID, B.CURRENCY, B.EIL_AMOUNT,
					 B.FLAG_VAS, B.UNUSED_AMOUNT, B.EAD_TYPE, A.SEQ, A.EAD_PRINCIPAL, ''SP_IFRS_EAD_RESULT'' AS CREATEDBY, SYSDATE AS CREATEDDATE
					FROM IFRS_EIL_IMA A 
					INNER JOIN CTE_SEQ C ON A.LIFETIME >= C.SEQ
					LEFT  JOIN GTMP_IFRS_PAYM_SCHD_EAD B ON A.MASTERID = B.MASTERID  AND B.SEQ = C.SEQ
					WHERE  ((C.SEQ <= 12 AND A.STAGE = 1 ) OR A.STAGE = 2 )';
					
		EXECUTE IMMEDIATE V_STR_QUERY;
		COMMIT;
        -----------------------------
	    -- Log & insert final data
	    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_EAD_RESULT;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_EAD_RESULT ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ;

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- ROLLBACK TO SAFE STATE AND RE-RAISE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR IN SP_IFRS_PD_RULE_DATA: ' || SQLERRM);
        RAISE;
END