	INSERT INTO PSAK413.IFRS_LGD_DATA_S_0000_111 (
	 LGD_SEGMENT_ID,DEFAULT_DATE , CUSTOMER_NUMBER, FACILITY_NUMBER, MASTERID,
	CURRENCY, ACCOUNT_STATUS, CURE_FLAG, --CURED_DATE, WO_DATE, CLOSED_DATE,
	OS_AT_DEFAULT, EQV_AT_DEFAULT, OS_WO, EQV_WO, EIR_AT_DEFAULT
	 ,CREATEDBY
	 ,CREATEDDATE
	 )
	SELECT B.SEGMENTATION_ID, A.DOWNLOAD_DATE
	 ,A.CUSTOMER_NUMBER
	 ,A.FACILITY_NUMBER, A.MASTERID
	 ,A.CCY_AT_DEFAULT , 'A', 0--, NULL, NULL, NULL
	 ,A.OS_AT_DEFAULT
	 ,A.EQV_AT_DEFAULT
	,0,0, A.EIR_AT_DEFAULT
	 ,'SP_IFRS_LGD_DATA' CREATEDBY 
	 ,SYSDATE CREATEDDATE 
	FROM PSAK413.IFRS_DEFAULT A 
	JOIN GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG  B ON A.RULE_ID = B.DEFAULT_RULE_ID 
	WHERE A.DOWNLOAD_DATE = TO_DATE('2025-12-31', 'YYYY-MM-DD')
	AND EXISTS (SELECT 1 FROM  PSAK413.IFRS_LGD_RULE_DATA_S_0000_111 C WHERE A.MASTERID = C.MASTERID 
	 AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE AND C.RULE_ID  =B.SEGMENTATION_ID) 