CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_INITIAL_PAYM_SCHD_DEV (
    P_RUNID		     IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE  IN DATE, 
    P_SYSCODE        IN VARCHAR2 DEFAULT '0', 
    P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AUTHID CURRENT_USER
AS

	---- DATE   
    V_CURRDATE DATE; 
	V_EOMDATE DATE ;  

	---- PROCESS
	V_COUNT NUMBER;
	V_RULE_ID VARCHAR2(10);
	V_ID NUMBER DEFAULT 0; 
	V_MAX_ID NUMBER DEFAULT 0; 
	V_DATADATE VARCHAR(20); 
    ---- QUERY  
    V_STR_QUERY CLOB;
	V_STR_SQL_RULE CLOB;
    V_SQL_CONDITIONS CLOB;
    V_SCRIPT1 CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SP_NAME VARCHAR2(100) := 'SP_IFRS_INITIAL_PAYM_SCHD_DEV';
    V_OPERATION VARCHAR2(100);

    V_SYSCODE VARCHAR(500);
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

	IF P_PRC = 'S' THEN 
        V_TABLE_NAME := 'IFRS_INITIAL_PAYM_SCHD_' || P_RUNID || ''; 
    ELSE 
        V_TABLE_NAME := 'IFRS_INITIAL_PAYM_SCHD'; 
    END IF;

    IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_INITIAL_PAYM_SCHD', V_TABLE_NAME);    
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, TO_NUMBER(SYS_CONTEXT('USERENV','SESSIONID')), SYSDATE);
	COMMIT;
    -------- RECORD RUN_ID --------
   
   	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTEMP_IMA_FILTER';

	V_STR_QUERY := 'INSERT INTO GTEMP_IMA_FILTER(MASTERID,SEGMENT)
	SELECT IMA.MASTERID, IMA.SEGMENT
	FROM IFRS_MASTER_ACCOUNT IMA
	LEFT JOIN TBLM_COMMONCODEDETAIL CD
	    ON CD.COMMONCODE = ''BUS-504''
	    AND CD.VALUE1 = IMA.SEGMENT
	WHERE IMA.DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''
	    AND IMA.ACCOUNT_STATUS = ''A''
	    AND CD.VALUE1 IS NULL';
    
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;
	COMMIT;

   	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_INITIAL_PAYM_SCHD'; 
   	
	V_STR_QUERY := 'INSERT INTO IFRS_INITIAL_PAYM_SCHD (DOWNLOAD_DATE, MASTERID, CREATED_DATE)
	SELECT 
	    MAX(P.DOWNLOAD_DATE) AS DOWNLOAD_DATE,
	    P.MASTERID,
	    SYSDATE
	FROM IFRS_PAYM_SCHD_ALL P
	INNER JOIN GTEMP_IMA_FILTER T ON T.MASTERID = P.MASTERID
	WHERE P.DOWNLOAD_DATE <= DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''
	GROUP BY P.MASTERID';
	
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;
	COMMIT;

    -------- ====== LOG ======
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLE_NAME;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_STR_QUERY := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLE_NAME || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_STR_QUERY, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;