CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_EIL_MODEL_DEV (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
)
IS
    V_CURRDATE    	DATE;
    V_EIL_MODEL_ID 	NUMBER := 0;
    V_SCRIPT      	CLOB;
    V_TMP1        	VARCHAR2(100);
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_COUNT         NUMBER;
   
   	-- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_EIL_MODEL_DEV';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        VARCHAR2(8000);
    V_RETURNROWS2   NUMBER;

	V_SYSCODE VARCHAR(500);
BEGIN
    ------------------------------------------------------------------
    -- SET TANGGAL
    ------------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    ------------------------------------------------------------------
    -- AMBIL EIL MODEL ID
    ------------------------------------------------------------------
    SELECT PKID
    INTO   V_EIL_MODEL_ID
    FROM   IFRS_EIL_MODEL_HEADER
    WHERE  IS_EOM = 1 AND IS_DELETE = 0 
    FETCH FIRST 1 ROW ONLY;


	----- TAMBAHAN JIKA P_SYSCODE NYA DI DAPAT NULL
    IF COALESCE(P_SYSCODE, NULL) IS NULL THEN
        V_SYSCODE := '0';
	ELSE
		V_SYSCODE := P_SYSCODE;
    END IF;
   
    
    ------------------------------------------------------------------
    -- Nama tabel target
    ------------------------------------------------------------------
   IF P_PRC = 'S' THEN 
        V_TMP1 := 'IFRS_EIL_MODEL_' || P_RUNID || ''; 
    ELSE 

        V_TMP1 := 'IFRS_EIL_MODEL'; 
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, 'SP_IFRS_EIL_MODEL', P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    ------------------------------------------------------------------
    -- Build dynamic SQL
    ------------------------------------------------------------------

	IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TMP1); 
        
		IF V_COUNT > 0 THEN 
		 V_SCRIPT := '';
         V_SCRIPT := V_SCRIPT || 'DROP TABLE ' || V_TMP1 || ' ';
        EXECUTE IMMEDIATE (V_SCRIPT);
		END IF;

        V_SCRIPT := '';
        V_SCRIPT := V_SCRIPT || 'CREATE TABLE ' || V_TMP1 || ' AS SELECT * FROM IFRS_EIL_MODEL WHERE 0=1';
        EXECUTE IMMEDIATE (V_SCRIPT);
        
    END IF;
	COMMIT;
	
	--V_SCRIPT := 'TRUNCATE TABLE PSAK413.' || V_TMP1 || '';

    V_SCRIPT := 'DELETE FROM ' || V_TMP1 || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') 
	AND EIL_MODEL_ID =  ' || V_EIL_MODEL_ID  ;
     
    EXECUTE IMMEDIATE V_SCRIPT;
	COMMIT;

    V_SCRIPT := 'INSERT INTO PSAK413.' || V_TMP1 || '
	(DOWNLOAD_DATE,
		EIL_MODEL_ID,
		EAD_RULE_ID,
		SUB_SEGMENT_EAD,
		SEGMENTATION_ID,
		LGD_RULE_ID,
		LGD_ME_MODEL_ID,
		SUB_SEGMENT_LGD,
		LGD_DATE,
		LGD_OVERRIDE_FLAG,
		PD_RULE_ID,
		PD_ME_MODEL_ID,
		SUB_SEGMENT_PD,
		PD_DATE,
		BUCKET_GROUP,
		EAD_BALANCE,
		EAD_BALANCE_INTEREST,
		LT_RULE_ID,
		LT_EFF_DATE,
		LT_OVERRIDE_FLAG,
		FLAG_VAS,
		MODEL_TYPE, 
		EAD_BALANCE_ADDITIONAL,
		EAD_BALANCE_INTEREST_ADDITIONAL,
		CREATEDBY, CREATEDDATE)
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS DOWNLOAD_DATE,
		A.PKID AS EIL_MODEL_ID,
		C.PKID AS EAD_RULE_ID,
		I.SEGMENT_NAME_LV3 AS SUB_SEGMENT_EAD,
		b.SEGMENTATION_ID AS SEGMENTATION_ID,
		D.LGD_RULE_ID AS LGD_RULE_ID,
		D.LGD_MODEL_ID AS LGD_ME_MODEL_ID,
		J.SEGMENT_NAME_LV3 AS SUB_SEGMENT_LGD,
		CASE WHEN D.EFF_DATE_OPTION = ''Current Month'' THEN TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Previous Month'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-1)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Last Year'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-12)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Selected Date'' THEN D.EFF_DATE END AS LGD_DATE,
		D.IS_OVERRIDE AS LGD_OVERRIDE_FLAG,
		E.PD_RULE_ID AS PD_RULE_ID,
		E.PD_MODEL_ID AS PD_ME_MODEL_ID,
		K.SEGMENT_NAME_LV3 AS SUB_SEGMENT_PD,
		CASE WHEN E.EFF_DATE_OPTION = ''Current Month'' THEN TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Previous Month'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-1)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Last Year'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-12)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Selected Date'' THEN E.EFF_DATE END AS PD_DATE ,
		H.BUCKET_GROUP AS BUCKET_GROUP,
		C.EAD_BALANCE AS EAD_BALANCE,
		CASE WHEN L.SEGMENT_NAME_LV2 LIKE ''%INVESTASI%'' THEN ''CASE WHEN BI_COLLECTABILITY IN (1,2) THEN MARGIN_PAST_DUE ELSE 0 END '' ELSE ''0'' END AS EAD_BALANCE_INTEREST,
		C.LIFETIME_RULE_ID AS LT_RULE_ID,
		B.LIFETIME_DATE AS LT_EFF_DATE,
		B.IS_OVERRIDE_LIFETIME AS LT_OVERRIDE_FLAG,
		CASE WHEN H.PD_METHOD = ''VAS'' THEN 1 ELSE 0 END AS FLAG_VAS,
		CASE WHEN D.LGD_RULE_ID = 0 AND E.PD_RULE_ID = 0 THEN 1 ELSE 0 END AS MODEL_TYPE,
		''0'' || CASE WHEN C.UNAMORTIZED_FEE_COST_FLAG = 1 THEN '' + NVL(UNAMORT_COST_AMT,0) + NVL(UNAMORT_FEE_AMT,0) + NVL(UNAMORT_OTHERS,0) '' ELSE '''' END || 
		CASE WHEN C.MARGIN_ACCRUED_FLAG = 1 THEN '' + CASE WHEN BI_COLLECTABILITY IN(1,2) THEN NVL(MARGIN_ACCRUED,0) ELSE 0 END '' ELSE '''' END AS EAD_BALANCE_ADDITIONAL,
		''0'' AS EAD_BALANCE_INTEREST_ADDITIONAL,
		''SP_IFRS_EIL_MODEL'' AS CREATEDBY,
		SYSDATE AS CREATEDDATE
	 FROM IFRS_EIL_MODEL_HEADER A
	  JOIN IFRS_EIL_MODEL_DETAIL_EAD B ON A.PKID = B.EIL_MODEL_ID
	   JOIN IFRS_EAD_RULES_CONFIG C ON B.EAD_RULE_ID = C.PKID
	  JOIN IFRS_EIL_MODEL_DETAIL_LGD D ON A.PKID = D.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = D.SEGMENTATION_ID
	  JOIN IFRS_EIL_MODEL_DETAIL_PD E ON A.PKID = E.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = E.SEGMENTATION_ID
	  JOIN IFRS_EIL_MODEL_DETAIL_PF F ON A.PKID = F.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = F.SEGMENTATION_ID
	    JOIN IFRS_LGD_RULES_CONFIG G ON D.LGD_RULE_ID = G.PKID
	    JOIN IFRS_PD_RULES_CONFIG H ON E.PD_RULE_ID  = H.PKID
	    JOIN IFRS_SEGMENTATION_MAPPING I ON C.SEGMENTATION_ID = I.PKID  
	    JOIN IFRS_SEGMENTATION_MAPPING J ON G.SEGMENTATION_ID = J.PKID
	    JOIN IFRS_SEGMENTATION_MAPPING K ON H.SEGMENTATION_ID = K.PKID 
		JOIN IFRS_SEGMENTATION_MAPPING L ON F.SEGMENTATION_ID = L.PKID 
	  WHERE A.PKID = ' || V_EIL_MODEL_ID || '' ;
	 
	--DBMS_OUTPUT.PUT_LINE(V_SCRIPT);
    EXECUTE IMMEDIATE V_SCRIPT;
	COMMIT;

	V_SCRIPT := 'UPDATE PSAK413.' || V_TMP1 || ' A 
		SET LGD = (SELECT LGD FROM IFRS_LGD_RESULT X WHERE A.LGD_DATE = X.EFF_DATE AND A.LGD_RULE_ID = X.LGD_RULE_ID)
		, LIFETIME = (SELECt LIFETIME fROM IFRS_LIFETIME_HEADER Y WHERE A.LT_EFF_DATE = Y.EFF_DATE AND A.LT_RULE_ID = Y.LIFETIME_RULE_ID ) 
		WHERE A.EIL_MODEL_ID = ' || V_EIL_MODEL_ID || '
		AND A.DOWNLOAD_DATE =  TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') '; 
	EXECUTE IMMEDIATE V_SCRIPT;
	COMMIT;
	

	-----------------------------
    -- Log & insert final data
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TMP1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    ----------------------------------------------------------------
    -- RESULT PREVIEW
    ----------------------------------------------------------------
	V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TMP1 || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;