CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_IMP_INITIAL_UPDATE_DEV (
	P_RUNID		 	 IN VARCHAR2 DEFAULT 'S_00000_0000',
	P_DOWNLOAD_DATE  IN DATE, 
	P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
	P_PRC			 IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    -- DATE
    V_CURRDATE   DATE;
    V_PREVDATE   DATE;
    V_MODEL_ID   VARCHAR2(22);
    V_COUNT      NUMBER;

    -- QUERY
    V_STR_QUERY  CLOB;

    -- TABLE LIST
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1   VARCHAR2(100);
    V_TABLEINSERT2   VARCHAR2(100);
    V_TABLESELECT1   VARCHAR2(100);
    V_TABLEPDCONFIG  VARCHAR2(100);

    -- CONDITION / LOG
    V_RETURNROWS  NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST   VARCHAR2(100);
    V_COLUMNDEST  VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_IMP_INITIAL_UPDATE_DEV';
    V_OPERATION   VARCHAR2(100);

    V_QUERYS      CLOB;

	V_SYSCODE VARCHAR(500);

BEGIN
    ------------------------------------------------------------------------
    -- SET CURRDATE
    ------------------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE_AMORT ipda ;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
	
    --V_PREVDATE := V_CURRDATE - 1;
    --V_MODEL_ID := NVL(P_SYSCODE, '0');

	----- TAMBAHAN JIKA P_SYSCODE NYA DI DAPAT NULL
    IF COALESCE(P_SYSCODE, NULL) IS NULL THEN
        V_SYSCODE := '0';
	ELSE
		V_SYSCODE := P_SYSCODE;
    END IF;
   
    ------------------------------------------------------------------------
    -- SET TABLE NAMES
    ------------------------------------------------------------------------
    IF P_PRC = 'S' THEN
        V_TABLEINSERT1  := 'IFRS_MASTER_ACCOUNT_' || P_RUNID;
    ELSE
        V_TABLEINSERT1  := 'IFRS_MASTER_ACCOUNT';
    END IF;
   
    ------------------------------------------------------------------------
    -- DEFAULT ACCOUNT_STATUS (LOAN_DUE_DATE NULL AND BI_COLL NULL)
    ------------------------------------------------------------------------  
    UPDATE IFRS_MASTER_ACCOUNT A
	SET A.ACCOUNT_STATUS = 'C'
	WHERE A.DAY_PAST_DUE IS NULL 
	AND A.BI_COLLECTABILITY IS NULL
	AND DOWNLOAD_DATE = V_CURRDATE ;
   
   --- STEP PATCHING SEGMENT ---
   
	PSAK413.SP_IFRS_SEGMENTATION_MAPPING();
	
	-- RESET MULTIJASA_FLAG --
	UPDATE IFRS_MASTER_ACCOUNT A
	SET A.MULTIJASA_FLAG = 0
	WHERE DOWNLOAD_DATE = V_CURRDATE;
	
	-- UPDATE SEGMENT MULTIJASA --
	UPDATE IFRS_MASTER_ACCOUNT A
	SET A.MULTIJASA_FLAG = 1
	WHERE ACCOUNT_STATUS = 'A'
	AND DOWNLOAD_DATE = V_CURRDATE
	AND EXISTS(SELECT 1 FROM IFRS_LOAN_MULTIJASA X WHERE X.NOMORREKENING = A.ACCOUNT_NUMBER AND X.PERIODEDATA = A.DOWNLOAD_DATE);

	PSAK413.SP_IFRS_EIL_UPDATE_PORTFOLIO(P_RUNID, V_CURRDATE, 'M');
	
	--- STEP UPDATE DARI BULAN SEBELUMNYA ---

	MERGE INTO IFRS_MASTER_ACCOUNT X
	USING (
			SELECT A.DOWNLOAD_DATE , A.MASTERID, B.GROUP_SEGMENT ,A.GROUP_SEGMENT AS GS_RULES, B.SEGMENT , A.SEGMENT  AS S_RULES, B.SUB_SEGMENT, A.SUB_SEGMENT AS SS_RULES,
			B.SEGMENTATION_ID
			FROM IFRS_MASTER_ACCOUNT A
			INNER JOIN IFRS_MASTER_ACCOUNT_MONTHLY B ON A.MASTERID = B.MASTERID 
			WHERE A.DOWNLOAD_DATE = V_CURRDATE AND B.DOWNLOAD_DATE = '31 MAR 2026'
			AND A.SEGMENTATION_ID <> B.SEGMENTATION_ID 
			AND A.ACCOUNT_STATUS = 'A'
			)Y
	ON (X.DOWNLOAD_DATE = V_CURRDATE
		AND X.MASTERID = Y.MASTERID)
	WHEN MATCHED THEN UPDATE SET X.GROUP_SEGMENT = Y.GROUP_SEGMENT,
				X.SEGMENT = Y.SEGMENT,
				X.SUB_SEGMENT = Y.SUB_SEGMENT,
				X.SEGMENTATION_ID = Y.SEGMENTATION_ID;
	
	--- STEP OVERRIDE SEGMENT ---
	UPDATE IFRS_MASTER_ACCOUNT A
	SET (A.GROUP_SEGMENT,
		 A.SEGMENT,
	     A.SUB_SEGMENT,
	     A.SEGMENTATION_ID) =
	    (
	        SELECT MAX(Y.GROUP_SEGMENT),
	        	   MAX(Y.SEGMENT),
	               MAX(Y.SUB_SEGMENT),
	               MAX(Y.SEGMENTATION_ID)
	        FROM IMPORT_SEGMENT_OVERRIDE_MAR26 Y
	        WHERE TO_NUMBER(REPLACE(Y.MASTERID,'.',''))  = A.MASTERID 
	    )
	WHERE A.ACCOUNT_STATUS = 'A' AND A.DOWNLOAD_DATE = V_CURRDATE 
		AND EXISTS (
		    SELECT 1
		    FROM IMPORT_SEGMENT_OVERRIDE_MAR26 Y
		    WHERE TO_NUMBER(REPLACE(Y.MASTERID,'.',''))  = A.MASTERID);		
			
    ------------------------------------------------------------------------
    -- UPDATE GLOBAL_CUSTOMER_NUMBER
    ------------------------------------------------------------------------
    V_STR_QUERY := 
    'UPDATE '|| V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
		SET A.GLOBAL_CUSTOMER_NUMBER =
		    (
		        SELECT MAX(X.SUPERCIF_NO)
		        FROM IFRS_SUPERCIF X
		        WHERE X.CIF_NO = A.CUSTOMER_NUMBER AND X.PERIODEDATA = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
		    )
		WHERE A.ACCOUNT_STATUS = ''A'' AND A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') 
		  AND EXISTS (
		        SELECT 1
		        FROM IFRS_SUPERCIF X
		        WHERE X.CIF_NO = A.CUSTOMER_NUMBER
		  )';

	EXECUTE IMMEDIATE V_STR_QUERY;
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    COMMIT;  			
				
    ------------------------------------------------------------------------
    -- UPDATE DIVISION_CODE
    ------------------------------------------------------------------------   
    V_STR_QUERY := 
    'UPDATE '|| V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
	SET (A.DAY_PAST_DUE ,
		 A.DIVISION_CODE ,
		 A.MARGIN_ACCRUED) =
		(SELECT MAX(TUNGGAKAN_HARI) AS DPD,
			MAX(DIVISIPISAH) AS DIVISION_CODE,
			MAX(IMBALANYANGAKANDITERIMA) AS MARGIN_ACCRUED 
		FROM IFRS_LOAN_DPD X WHERE X.NOMORREKENING = A.ACCOUNT_NUMBER AND X.FICMISDATE = A.DOWNLOAD_DATE )
	WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND A.ACCOUNT_STATUS = ''A''
		AND EXISTS(
		SELECT 1 FROM IFRS_LOAN_DPD D WHERE A.ACCOUNT_NUMBER = D.NOMORREKENING AND A.DOWNLOAD_DATE = D.FICMISDATE ) ';

	EXECUTE IMMEDIATE V_STR_QUERY;
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    COMMIT;      
    
	------------------------------------------------------------------------
    -- UPDATE DPD_ZERO_COUNTER
    ------------------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IMA_DPD';

	
	INSERT INTO GTMP_IMA_DPD
	SELECT DOWNLOAD_DATE, MASTERID, DAY_PAST_DUE, DAY_PAST_DUE_ORI , DPD_ZERO_COUNTER, OUTSTANDING, NVL(ACCOUNT_STATUS_ORI, CASE WHEN RESTRUCTURE_FLAG = 1 THEN 'R' ELSE 'X' END ) ACCOUNT_STATUS_ORI 
	FROM IFRS_MASTER_ACCOUNT A 
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND ACCOUNT_STATUS =  'A'
	AND restructure_flag = 1 
	UNION ALL 
	SELECT DOWNLOAD_DATE, MASTERID, DAY_PAST_DUE, DAY_PAST_DUE_ORI , DPD_ZERO_COUNTER, OUTSTANDING, NVL(ACCOUNT_STATUS_ORI, CASE WHEN RESTRUCTURE_FLAG = 1 THEN 'R' ELSE 'X' END ) ACCOUNT_STATUS_ORI 
	FROM IFRS_MASTER_ACCOUNT_MONTHLY A 
	WHERE DOWNLOAD_DATE = LAST_DAY(ADD_MONTHS(V_CURRDATE,-1))
	AND ACCOUNT_STATUS =  'A'
	AND EXISTS (SELECT 1 FROM IFRS_MASTER_ACCOUNT X WHERE A.MASTERID = X.MASTERID AND X.DOWNLOAD_DATE = V_CURRDATE);

	COMMIT ; 

	MERGE INTO IFRS_MASTER_ACCOUNT A
	USING ( 
		SELECT B.download_date, A.masterid, 
			GREATEST(nvl(B.DAY_PAST_DUE_ORI,0), nvl(A.DAY_PAST_DUE,0)) DPD,
			NVL(A.DPD_ZERO_COUNTER,0)DPD_ZERO_COUNTER, A.OUTSTANDING - B.OUTSTANDING  AS DELTA_OS ,
			a.ACCOUNT_STATUS_ORI  AS prev_status, b.ACCOUNT_STATUS_ORI  AS curr_Status
		FROM GTMP_IMA_DPD a
			JOIN GTMP_IMA_DPD B ON A.MASTERID = B.MASTERID 
		WHERE A.DOWNLOAD_DATE  =  LAST_DAY(ADD_MONTHS(V_CURRDATE,-1))
			AND B.DOWNLOAD_DATE   = V_CURRDATE
		) b 
		ON (A.download_date = B.download_date AND A.masterid = B.masterid) 
		
		WHEN MATCHED THEN 
		
		UPDATE 
		SET  A.DPD_ZERO_COUNTER = 
			CASE WHEN B.DPD_ZERO_COUNTER >= 3 AND b.prev_status = b.curr_status THEN 3
			WHEN b.prev_Status <> b.curr_Status THEN 0 
			WHEN B.DELTA_OS > 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND b.prev_status = b.curr_status THEN B.DPD_ZERO_COUNTER + 1 
			WHEN B.DELTA_OS = 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND b.prev_status = b.curr_status THEN B.DPD_ZERO_COUNTER
			ELSE 0 END,
			A.DAY_PAST_DUE = 
			CASE WHEN B.DELTA_OS > 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND B.DPD_ZERO_COUNTER + 1 >= 3 
				AND b.prev_status = b.curr_status THEN nvl(A.DAY_PAST_DUE_ORI,0)	 
				WHEN B.DPD_ZERO_COUNTER >= 3 AND b.prev_status = b.curr_status  THEN nvl(A.DAY_PAST_DUE_ORI,0)
			ELSE B.DPD 
			END ;
	   
	COMMIT ; 
	
    ------------------------------------------------------------------------
    -- UPDATE PATCH DPD_CIF
    ------------------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE XGTMP_IMADPDMAS';
 
	INSERT INTO XGTMP_IMADPDMAS 
	SELECT DOWNLOAD_DATE , NVL(GLOBAL_CUSTOMER_NUMBER,CUSTOMER_NUMBER), DAY_PAST_DUE , GROUP_SEGMENT 
	FROM PSAK413.IFRS_MASTER_ACCOUNT 
	WHERE DOWNLOAD_DATE  = V_CURRDATE
	AND ACCOUNT_STATUS  = 'A'
	AND  NVL(GROUP_SEGMENT,'X') NOT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS');
	
	COMMIT ;  
	 	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE X_PSAK_DPD_CIF';

	INSERT INTO X_PSAK_DPD_CIF
	(
		 DOWNLOAD_DATE
		,SCIF 
		,MAX_DPD 
	)
	SELECT 
		 DOWNLOAD_DATE 
		,SCIF 
		,MAX(DPD)
	FROM XGTMP_IMADPDMAS imam 
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND  NVL(GROUP_SEGMENT,'X') NOT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS')  
	GROUP BY 
	 DOWNLOAD_DATE 
	,SCIF  ;
	
	COMMIT ;
	
	
	UPDATE  IFRS_MASTER_ACCOUNT A  
	SET A.DPD_CIF  = (SELECT MAX_DPD FROM X_PSAK_DPD_CIF X WHERE A.DOWNLOAD_DATE  = X.DOWNLOAD_DATE  AND NVL(A.GLOBAL_CUSTOMER_NUMBER,A.CUSTOMER_NUMBER) = X.SCIF  )
	WHERE A.DOWNLOAD_DATE  = V_CURRDATE
	AND A.ACCOUNT_STATUS  = 'A'
	AND NVL(A.GROUP_SEGMENT,'X') NOT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS')
	AND EXISTS (SELECT 1 FROM X_PSAK_DPD_CIF x 
		WHERE A.DOWNLOAD_DATE  = X.DOWNLOAD_DATE AND   nvl(a.GLOBAL_CUSTOMER_NUMBER, a.customer_number) = x.scif  )	;
	
	COMMIT ;
	
	-----------------------------------------------------------------------	----------------------------------------------------------------
	EXECUTE IMMEDIATE 'TRUNCATE TABLE XGTMP_IMADPDMAS';
	
	INSERT INTO XGTMP_IMADPDMAS 
	SELECT DOWNLOAD_DATE , NVL(GLOBAL_CUSTOMER_NUMBER,CUSTOMER_NUMBER), DAY_PAST_DUE , GROUP_SEGMENT 
	FROM PSAK413.IFRS_MASTER_ACCOUNT
	WHERE DOWNLOAD_DATE  = V_CURRDATE
	AND ACCOUNT_STATUS  = 'A'
	AND  GROUP_SEGMENT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS')
	;
	 
	EXECUTE IMMEDIATE 'TRUNCATE TABLE X_PSAK_DPD_CIF_1';

	INSERT INTO X_PSAK_DPD_CIF_1
	(
		 DOWNLOAD_DATE
		,SCIF 
		,MAX_DPD 
		,GROUP_SEGMENT
	)
	SELECT 
		 DOWNLOAD_DATE 
		,SCIF
		,MAX(DPD)
		,GROUP_SEGMENT
	FROM XGTMP_IMADPDMAS imam 
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND  GROUP_SEGMENT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS')
	GROUP BY 
	 DOWNLOAD_DATE 
	,SCIF
	,GROUP_SEGMENT;
	
	COMMIT ;
	 
	UPDATE   IFRS_MASTER_ACCOUNT A  SET DPD_CIF  = (SELECT MAX_DPD FROM X_PSAK_DPD_CIF_1 Y WHERE a.GROUP_SEGMENT = Y.GROUP_SEGMENT AND nvl(a.GLOBAL_CUSTOMER_NUMBER, a.customer_number) = Y.scif   )
	 WHERE A.DOWNLOAD_DATE  = V_CURRDATE
	AND A.ACCOUNT_STATUS  = 'A'
	AND A.GROUP_SEGMENT IN ('BTB_MRB_EMAS','HASANAH_CARD','GADAI_EMAS')
	AND EXISTS (SELECT 1 FROM X_PSAK_DPD_CIF_1 x 
	WHERE A.DOWNLOAD_DATE  = X.DOWNLOAD_DATE AND  a.GROUP_SEGMENT = x.GROUP_SEGMENT AND nvl(a.GLOBAL_CUSTOMER_NUMBER, a.customer_number) = x.scif );
	
	COMMIT ;
	
   
    ------------------------------------------------------------------------
    -- UPDATE OUT_STANDING_PAST_DUE AND MARGIN_PAST_DUE NON MURABAHAH
    ------------------------------------------------------------------------ 
    UPDATE IFRS_MASTER_ACCOUNT A
	SET (A.OUTSTANDING_PAST_DUE ,
		 A.MARGIN_PAST_DUE ) =
		(SELECT MAX(X.TUNGGAKANPOKOKJUMLAH) ,
			MAX(X.TUNGGAKANBAGIHASILJUMLAH) 
		FROM IFRS_LOAN_PASTDUE X WHERE X.NOMORREKENING = A.ACCOUNT_NUMBER AND X.FICMISDATE = A.DOWNLOAD_DATE )
	WHERE A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_STATUS = 'A' 
		AND EXISTS(
		SELECT 1 FROM IFRS_LOAN_PASTDUE D WHERE A.ACCOUNT_NUMBER = D.NOMORREKENING AND A.DOWNLOAD_DATE = D.FICMISDATE );

    ------------------------------------------------------------------------
    -- UPDATE OUT_STANDING_PAST_DUE AND MARGIN_PAST_DUE IJARAH
    ------------------------------------------------------------------------ 
    UPDATE IFRS_MASTER_ACCOUNT A
	SET (A.OUTSTANDING_PAST_DUE ,
		 A.MARGIN_PAST_DUE ) =
		(SELECT MAX(X.TUNGGAKAN_POKOK) ,
			MAX(X.TUNGGAKAN_IMBALAN) 
		FROM IFRS_LOAN_PASTDUE_IJARAH X WHERE X.NOMORREKENING = A.ACCOUNT_NUMBER AND X.FICMISDATE = A.DOWNLOAD_DATE )
	WHERE A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_STATUS = 'A' 
		AND EXISTS(
		SELECT 1 FROM IFRS_LOAN_PASTDUE_IJARAH D WHERE A.ACCOUNT_NUMBER = D.NOMORREKENING AND A.DOWNLOAD_DATE = D.FICMISDATE );

    ------------------------------------------------------------------------
    -- UPDATE UNAMORT_OTHERS
    ------------------------------------------------------------------------
	UPDATE IFRS_MASTER_ACCOUNT A
	SET (A.UNAMORT_OTHERS ) =
		(SELECT MAX(X.EIR)
		FROM IFRS_UNAMORT_OTHERS X WHERE X.LOAN_NO = A.ACCOUNT_NUMBER AND X.PERIODE = A.DOWNLOAD_DATE )
	WHERE A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_STATUS = 'A' 
		AND EXISTS(
		SELECT 1 FROM IFRS_UNAMORT_OTHERS D WHERE A.ACCOUNT_NUMBER = D.LOAN_NO AND A.DOWNLOAD_DATE = D.PERIODE );
   
	------------------------------------------------------------------------
    -- UPDATE IMPAIR_FLAG
    ------------------------------------------------------------------------
	UPDATE IFRS_MASTER_ACCOUNT A
	SET A.IMPAIRED_FLAG = 'C'
	WHERE ACCOUNT_STATUS = 'A'
	AND DOWNLOAD_DATE = V_CURRDATE;
	------------------------------------------------------------------------
    -- UPDATE IS_IMPAIRED
    ------------------------------------------------------------------------
	UPDATE IFRS_MASTER_ACCOUNT A
	SET A.IS_IMPAIRED = 1
	WHERE ACCOUNT_STATUS = 'A'
	AND DOWNLOAD_DATE = V_CURRDATE;

	------------------------------------------------------------------------
    -- UPDATE IAS_CLASS
    ------------------------------------------------------------------------
	UPDATE IFRS_MASTER_ACCOUNT A
	SET IAS_CLASS  = 'A' 
	WHERE ACCOUNT_STATUS = 'A'
	AND DOWNLOAD_DATE = V_CURRDATE;

	------------------------------------------------------------------------
    -- UPDATE IFRS9_CLASS
    ------------------------------------------------------------------------
	
	-----------------------------
    -- Log & insert final data
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    ----------------------------------------------------------------
    -- RESULT PREVIEW
    ----------------------------------------------------------------
	V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;