CREATE OR REPLACE PROCEDURE XXXXXX.TEMPLATE_XXX (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AUTHID CURRENT_USER
AS
	---- DATE   
    V_CURRDATE DATE; 
	V_EOMDATE DATE ;  

	---- PROCESS
	V_COUNT NUMBER;
	V_RULE_ID VARCHAR2(10);
	V_ID NUMBER DEFAULT 0; 
	V_MAX_ID NUMBER DEFAULT 0; 
	V_DATADATE VARCHAR(20); 
    ---- QUERY  
    V_STR_QUERY CLOB;
	V_STR_SQL_RULE CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'TEMPLATE_XXX';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    V_SYSCODE VARCHAR(500);
 
BEGIN
    
    V_SPNAME := 'XXX';
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CASE 
        		WHEN CURRDATE = LAST_DAY(CURRDATE) THEN CURRDATE
        		ELSE LAST_DAY(ADD_MONTHS(CURRDATE, -1))
    		END, LAST_DAY(CURRDATE)
        INTO V_CURRDATE,V_EOMDATE 
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    ----- TAMBAHAN JIKA P_SYSCODE NYA DI DAPAT NULL
    IF COALESCE(P_SYSCODE, NULL) IS NULL THEN
        V_SYSCODE := '0';
	ELSE
		V_SYSCODE := P_SYSCODE;
    END IF;
 	
    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'XXX_' || P_RUNID || ''; 
    ELSE 

        V_TABLEINSERT1 := 'XXX'; 
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

	-------- BODY LOGIC --------
    -------- WRITE HERE --------
    ----------------------------
    
    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_STR_QUERY := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_STR_QUERY, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END;