DROP TABLE IF EXISTS IFRS_LOGS_PROCESS;

CREATE TABLE IF NOT EXISTS IFRS_LOGS_PROCESS (
  PKID SERIAL PRIMARY KEY,
  DOWNLOAD_DATE DATE,
  TABLE_DEST VARCHAR(50) NOT NULL,
  COLUMN_DEST TEXT NOT NULL,
  SP_NAME VARCHAR(50) NOT NULL,
  OPERATION VARCHAR(50) NOT NULL,
  RUN_ID VARCHAR(100) NOT NULL,
  PROCESS_ID BIGINT NOT NULL,
  AFFECTED_RECORD INT NOT NULL,
  PROCESS_DATE TIMESTAMP WITHOUT TIME ZONE
)