CREATE TABLE "PSAK413"."IFRS_PD_NFR_ENR" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_ID" NUMBER(5,0), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"CALC_METHOD" NVARCHAR2(50), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
