CREATE TABLE "PSAK413"."IFRS_LI_ACCT_SL_ECF_STOPPED" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"AMORTSTOPDATE" DATE, 
	"AMORTSTOPREASON" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
