CREATE TABLE "PSAK413"."IFRS_ME_MODEL_CORRELATION" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_ID" NUMBER(20,0), 
	"ME_CODE" NVARCHAR2(100), 
	"DERIVED_TYPE" NVARCHAR2(100), 
	"EXPECTED_TREND" NVARCHAR2(3), 
	"IN_SAMPLE_SET" NUMBER(5,0), 
	"CORRELATION_VALUE" BINARY_DOUBLE, 
	"ADJ_CORRELATION" BINARY_DOUBLE, 
	"IS_CHOSEN" NUMBER(10,0), 
	 CONSTRAINT "PK_IFRS_ME_MODEL_CORREL" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
