CREATE TABLE "PSAK413"."IFRS_AC_PRODUCT_CLASS" 
   (	"PRD_CODE" NVARCHAR2(20), 
	"ASSET_CLASS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
