CREATE TABLE "PSAK413"."IFRS_GS_DATE2" 
   (	"MASTERID" NVARCHAR2(100), 
	"PMT_DATE" DATE, 
	"PMT_OS" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
