CREATE TABLE "PSAK413"."IFRS_NOMINATIF_TRS" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"MASTER_ACCOUNT_CODE" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(100), 
	"CURRENCY" NCHAR(3), 
	"OUTSTANDING_IDR" NVARCHAR2(50), 
	"PIP_AMOUNT" NVARCHAR2(50), 
	"PIP_AMOUNT_ORI" NVARCHAR2(50), 
	"DATA_SOURCE" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
