CREATE TABLE "PSAK413"."IFRS_MASTER_EXTERNAL_RATING" 
   (	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"SANDI_BANK" NVARCHAR2(10), 
	"EXTERNAL_RATING_AGENCY" NVARCHAR2(100), 
	"INITIAL_RATING_CODE" NVARCHAR2(20), 
	"EXTERNAL_RATING_CODE" NVARCHAR2(20), 
	"SOURCE_SYSTEM" NVARCHAR2(20), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
