CREATE TABLE "PSAK413"."IFRS_MASTER_COLLATERAL_CORP" 
   (	"DOWNLOAD_DATE" DATE, 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"COLLATERAL_PROOF_OWNERSHIP" NVARCHAR2(200), 
	"CURRENCY" NVARCHAR2(3), 
	"COLL_TP" NVARCHAR2(5), 
	"COLL_NAT" NVARCHAR2(5), 
	"LOAN_START_DATE" DATE, 
	"LOAN_DUE_DATE" DATE, 
	"AMOUNT" NUMBER(32,6), 
	"SOURCE_TABLE" NVARCHAR2(50), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_GENERATE_IMA_COLLATERAL', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
