CREATE TABLE "PSAK413"."IFRS_MASTER_WO_MB" 
   (	"DOWNLOAD_DATE" DATE, 
	"ACCOUNT_NUMBER" NVARCHAR2(20), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CURRENCY" NVARCHAR2(3), 
	"MASTERID" NVARCHAR2(50), 
	"OUTSTANDING_WO" NUMBER(18,2), 
	"PRODUCT_CODE" NVARCHAR2(5), 
	"RECOVERY_AMOUNT" NUMBER(18,2), 
	"WRITEOFF_DATE" DATE, 
	"RECOVERY_DATE" DATE, 
	"SOURCE_TABLE" NVARCHAR2(50), 
	"CO_FLAG" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
