CREATE TABLE "PSAK413"."IFRS_PD_MMULT_FL_MPD" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"MODEL_ID" NUMBER(19,0), 
	"MODEL_SEQ" NUMBER(19,0), 
	"SCENARIO_NO" NUMBER(3,0), 
	"SEQ" NUMBER(5,0), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"MPD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
