CREATE TABLE "PSAK413"."IFRS_JUDGEMENT_RATING_TREASURY" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(50), 
	"EXTERNAL_RATING_AGENCY" NVARCHAR2(20), 
	"EXTERNAL_RATING_CODE" NVARCHAR2(10), 
	"EXTERNAL_RATING_INITIAL" NVARCHAR2(10), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_IFRS_SYNC_CORPORATE_DATA', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50) DEFAULT 'LOCALHOST'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
