CREATE TABLE "PSAK413"."IFRS_RECOVERY_RATE_TREASURY" 
   (	"DOWNLOAD_DATE" DATE, 
	"SEGMENT" NVARCHAR2(20), 
	"RECOVERY_RATE" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_IFRS_SYNC_CORPORATE_DATA', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50) DEFAULT 'LOCALHOST'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
