CREATE TABLE "PSAK413"."IFRS_PD_MIGRATION_DETAIL" 
   (	"PKID" NUMBER(36,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" VARCHAR2(30) NOT NULL ENABLE, 
	"PD_UNIQUE_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"CUSTOMER_NAME" VARCHAR2(150), 
	"BUCKET_FROM" NUMBER(19,0), 
	"BUCKET_TO" NUMBER(19,0), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"OUTSTANDING" NUMBER(32,6), 
	"CREATEDBY" VARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATEDHOST" VARCHAR2(36) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(30), 
	"CURR_DATE" DATE, 
	"PREV_DATE" DATE, 
	"CUSTOMER_NUMBER" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
