CREATE TABLE "PSAK413"."IFRS_EXCEPTION_DETAILS" 
   (	"DOWNLOAD_DATE" DATE, 
	"DATA_SOURCE" NVARCHAR2(20), 
	"PRD_CODE" NVARCHAR2(20), 
	"ACCOUNT_NUMBER" NVARCHAR2(70), 
	"MASTERID" NVARCHAR2(100), 
	"PROCESS_ID" NVARCHAR2(50), 
	"EXCEPTION_CODE" NVARCHAR2(50), 
	"REMARKS" NVARCHAR2(50), 
	"PRD_TYPE" NVARCHAR2(50), 
	"INSERTED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
