CREATE TABLE "PSAK413"."IFRS_LIFETIME_SCENARIO_DATA" 
   (	"PERIOD" DATE, 
	"LIFETIME_RULE_ID" NUMBER(20,0), 
	"RULE_ID" NUMBER(20,0), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"MASTERID" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(150), 
	"LIFETIME_UNIQUE_ID" NVARCHAR2(50), 
	"CALC_METHOD" NVARCHAR2(5), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"BUCKET_ID" NUMBER(5,0), 
	"OUTSTANDING" NUMBER(32,6), 
	"ACCOUNT_STATUS" NVARCHAR2(20), 
	"IMPAIRED_FLAG" NCHAR(1), 
	"IS_IMPAIRED" NUMBER(10,0), 
	"WRITEOFF_FLAG" NUMBER(10,0), 
	"DEFAULT_FLAG" NUMBER(10,0), 
	"LIFETIME" NUMBER(5,0), 
	"FAIR_VALUE_AMOUNT" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
