CREATE TABLE "PSAK413"."IFRS_DIM_SMBC_CLASS" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"SMBC_CLASS_NAME" NVARCHAR2(30) NOT NULL ENABLE, 
	"SMBC_CLASS_GROUP" NVARCHAR2(10) NOT NULL ENABLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
