CREATE TABLE "PSAK413"."IFRS_MIGRATION_FACILITY_NUMBER" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"NEW_FACILITY_NUMBER" NVARCHAR2(50), 
	"OLD_FACILITY_NUMBER" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
