CREATE TABLE "PSAK413"."IFRS_PAYM_SCHD_DWH_STG_NEW_DVC" 
   (	"PRINCIPAL" VARCHAR2(30), 
	"INTEREST" VARCHAR2(30), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"ACC_MSTR_ID" VARCHAR2(100), 
	"PMTDATE" VARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
