CREATE TABLE "PSAK413"."IFRS_STG_MASTER_ACCOUNT_TRSFX" 
   (	"DOWNLOAD_DATE" NVARCHAR2(20), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"DEAL_NO" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(50), 
	"PRD_TYPE" NVARCHAR2(50), 
	"AMOUNT_BUY" NVARCHAR2(50), 
	"AMOUNT_SELL" NVARCHAR2(50), 
	"CURR_BUY" NCHAR(3), 
	"CURR_SELL" NCHAR(3), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"TRX_DATE" NVARCHAR2(20), 
	"SETLE_DATE" NVARCHAR2(20), 
	"BROKER_CODE" NVARCHAR2(50), 
	"EXRATE_TO_LCY" NVARCHAR2(50), 
	"BANK_NON_BANK" NVARCHAR2(50), 
	"UNREALIZED_GAIN_LOSS_AMOUNT" NVARCHAR2(50), 
	"BRANCH_CODE" NVARCHAR2(50), 
	"RESIDENT_GROUP" NVARCHAR2(50), 
	"BI_CODE" NVARCHAR2(20), 
	"FILENAME" NVARCHAR2(100), 
	"AL_FLAG" NCHAR(1), 
	"SOURCE_PROCESS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
