CREATE TABLE "PSAK413"."IFRS_EIL_MODEL_DETAIL_PF_HIST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"EIL_MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SEGMENTATION_ID" NUMBER(20,0), 
	"LT_RULE_ID" NUMBER(20,0), 
	"SICR_RULE_ID" NUMBER(20,0), 
	"UPSIDE_VALUE" BINARY_DOUBLE, 
	"BASE_VALUE" BINARY_DOUBLE, 
	"DOWNSIDE_VALUE" BINARY_DOUBLE, 
	"UPSIDE_PROB_OUTCOME" BINARY_DOUBLE, 
	"BASE_PROB_OUTCOME" BINARY_DOUBLE, 
	"DOWNSIDE_PROB_OUTCOME" BINARY_DOUBLE, 
	"OVERLAY_AMOUNT" BINARY_DOUBLE, 
	"EIL_MODEL_ID_OLD" NUMBER(20,0), 
	"IS_NEW" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"DEFAULT_RULE_ID" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
