CREATE TABLE "PSAK413"."IFRS_FL_MODEL_DATA" 
   (	"MODEL_ID" NUMBER(19,0), 
	"MODEL_SEQ" NUMBER(19,0), 
	"COEFF_NAME" VARCHAR2(50), 
	"COEFF_VAL" NUMBER, 
	"PD_RULE_ID" NUMBER(19,0), 
	"ACTIVITY_CODE" VARCHAR2(100), 
	"AVG_PDRATE_MAPE" NUMBER, 
	"PD_RATE_MAPE" NUMBER, 
	"ADJ_R_SQ" NUMBER, 
	"IS_SELECTED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
