CREATE TABLE "PSAK413"."IFRS_PD_LINEST_SMOOTHING" 
   (	"PD_RULE_ID" NUMBER, 
	"SLOPE" NUMBER(32,6), 
	"INTERCEPT" NUMBER(32,6), 
	"RSQUARE" NUMBER(32,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
