CREATE TABLE "PSAK413"."IFRS_PD_MASTERSCALE_CORP" 
   (	"DOWNLOAD_DATE" DATE, 
	"OBLIGOR_GRADE" NVARCHAR2(5), 
	"PD" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(100) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
