CREATE TABLE "PSAK413"."IFRS_LBM_ACCT_EIR_CF_ECF1" 
   (	"MASTERID" NVARCHAR2(100), 
	"FEE_AMT" NUMBER(32,6), 
	"COST_AMT" NUMBER(32,6), 
	"TOTAL_AMT" NUMBER(32,6), 
	"FEE_AMT_ACRU" NUMBER(32,6), 
	"COST_AMT_ACRU" NUMBER(32,6), 
	"TOTAL_AMT_ACRU" NUMBER(32,6), 
	"PREV_EIR" NUMBER(18,10), 
	"PREV_ENDAMORTDATE" DATE, 
	"PKID" NUMBER(20,0), 
	"STAFFLOAN" NUMBER(10,0), 
	"BENEFIT" NUMBER(32,6), 
	"EIR" NUMBER(18,10), 
	"NPV_RATE" NUMBER(18,10), 
	"NEW_FEE_AMT" NUMBER(32,6), 
	"NEW_COST_AMT" NUMBER(32,6), 
	"NEW_TOTAL_AMT" NUMBER(32,6), 
	"GAIN_LOSS_AMT" NUMBER(32,6), 
	"GAIN_LOSS_FEE_AMT" NUMBER(32,6), 
	"GAIN_LOSS_COST_AMT" NUMBER(32,6), 
	"GAIN_LOSS_CALC" NCHAR(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
