CREATE TABLE "PSAK413"."IFRS_IMP_DEFAULT_RATE" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"PROJECTION_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"SEGMENT" NVARCHAR2(100), 
	"CALC_METHOD" NVARCHAR2(50), 
	"TOTAL_ACCOUNT" NUMBER(20,0), 
	"TOTAL_PERFORMING" NUMBER(20,0), 
	"TOTAL_12M_DEFAULT" NUMBER(20,0), 
	"TOTAL_OS" NUMBER(32,6), 
	"TOTAL_OS_PERFORMING" NUMBER(32,6), 
	"TOTAL_OS_12M_DEFAULT" NUMBER(32,6), 
	"ODR_RATE" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
