CREATE TABLE "PSAK413"."IFRS_PRODUCT_PARAM" 
   (	"DATA_SOURCE" NVARCHAR2(20), 
	"PRD_TYPE" NVARCHAR2(50), 
	"PRD_CODE" NVARCHAR2(20), 
	"PRD_GROUP" NVARCHAR2(20), 
	"MARKET_RATE" NUMBER(12,6), 
	"CCY" NVARCHAR2(5), 
	"AMORT_TYPE" NVARCHAR2(10), 
	"IS_STAF_LOAN" NVARCHAR2(3), 
	"IS_IMPAIRED" NVARCHAR2(3), 
	"PRODUCT_DESCRIPTION" NVARCHAR2(100), 
	"FEE_MAT_AMT" NUMBER(32,6), 
	"COST_MAT_AMT" NUMBER(32,6), 
	"EXPECTED_LIFE" NUMBER(10,0), 
	"FEE_MAT_TYPE" NVARCHAR2(20), 
	"COST_MAT_TYPE" NVARCHAR2(20), 
	"BISEGMENT" NVARCHAR2(10), 
	"FLAG_AL" NCHAR(1), 
	"REPAY_TYPE_VALUE" NVARCHAR2(10), 
	"WORKING_PERIOD" NUMBER(5,0), 
	"TENOR_TYPE" NCHAR(1), 
	"PRD_TYPE_1" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
