CREATE TABLE "PSAK413"."IFRS_LI_STG_PAYM_SCHD" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"MASTERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PMTDATE" DATE NOT NULL ENABLE, 
	"OSPRN" NUMBER(32,6) NOT NULL ENABLE, 
	"PRINCIPAL" NUMBER(32,6) NOT NULL ENABLE, 
	"MARGIN" NUMBER(32,6) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
