CREATE TABLE "PSAK413"."PSAK_MASTER_ACCOUNT_DPD_ORI" 
   (	"DOWNLOAD_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MASTER_ACCOUNT_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"DAY_PAST_DUE" NUMBER(31,0), 
	"BI_COLLECTABILITY" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
