CREATE TABLE "PSAK413"."TBLM_MACRO_ECONOMIC" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"ME_CODE" NVARCHAR2(100) NOT NULL ENABLE, 
	"ME_DESC" NVARCHAR2(100), 
	"ME_SOURCE" NVARCHAR2(100), 
	"ME_SOURCE_URL" NVARCHAR2(100), 
	"ME_SOURCE_TABLE" NVARCHAR2(100), 
	"ME_SOURCE_PERIOD_COLUMN" NVARCHAR2(30), 
	"ME_SOURCE_VALUE_COLUMN" NVARCHAR2(30), 
	"ME_SOURCE_FILTER" NUMBER(20,0), 
	"ME_TIME_SERIES" NVARCHAR2(100), 
	"ME_PERIOD_START" DATE, 
	"ME_PERIOD_END" DATE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"ME_SOURCE_FILTER_COLUMN" NVARCHAR2(50), 
	"ME_TYPE" NVARCHAR2(50), 
	 CONSTRAINT "PK__TBLM_MAC__5E028272BF5DBAA8" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
