CREATE TABLE "PSAK413"."TBLM_SEQUENCE" 
   (	"SEQUENCE_NAME" NVARCHAR2(30), 
	"PERIOD" NVARCHAR2(4), 
	"SEQUENCES" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
