CREATE TABLE "PSAK413"."TBLU_LGD_MASTER_RECOVERY" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50) NOT NULL ENABLE, 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"CUSTOMER_SEGMENT" NVARCHAR2(100), 
	"WO_DATE" NCHAR(6), 
	"DEFAULT_DATE" NCHAR(6), 
	"EAD_DEFAULT" NUMBER(32,6), 
	"CURRENCY" NCHAR(3) NOT NULL ENABLE, 
	"RECOVERY_AMOUNT" NUMBER(32,6), 
	"RECOVERY_DATE" NCHAR(6) NOT NULL ENABLE, 
	"DISCOUNT_RATE" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
