CREATE TABLE "PSAK413"."TBLU_PD_EXTERNAL_SNP" 
   (	"DOWNLOAD_DATE" NVARCHAR2(8), 
	"SEGMENT" NVARCHAR2(100), 
	"RATING_AGENCY_CODE" NVARCHAR2(50), 
	"RATING_CODE" NVARCHAR2(10), 
	"REMAINING_TENOR_YEAR" NVARCHAR2(5), 
	"CUMMULATIVE_PD" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
