CREATE TABLE "PSAK413"."TBLU_JUDGEMENT_RATING_TREASURY" 
   (	"DOWNLOAD_DATE" NVARCHAR2(8), 
	"DEAL_NO" NVARCHAR2(50), 
	"EXTERNAL_RATING_AGENCY" NVARCHAR2(20), 
	"EXTERNAL_RATING_INITIAL" NVARCHAR2(10), 
	"EXTERNAL_RATING_CODE" NVARCHAR2(10), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
