CREATE TABLE "PSAK413"."TBLU_MOODYS_CORPORATE" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"SUB_SEGMENT" NVARCHAR2(50) NOT NULL ENABLE, 
	"RECOVERY_RATE" BINARY_DOUBLE NOT NULL ENABLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
