CREATE TABLE "PSAK413"."TBLU_RECOVERY_MB" 
   (	"DOWNLOAD_DATE" NVARCHAR2(8), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"CURRENCY" NVARCHAR2(3), 
	"RECOVERY_DATE" NVARCHAR2(8), 
	"RECOVERY_AMOUNT" NVARCHAR2(20), 
	"CREATEDBY" NVARCHAR2(100), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
