CREATE TABLE "PSAK413"."TBLU_PD_SNP_SOVEREIGN" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"SUB_SEGMENT" NVARCHAR2(60) NOT NULL ENABLE, 
	"BUCKET_FROM" NVARCHAR2(5) NOT NULL ENABLE, 
	"BUCKET_TO" NVARCHAR2(5) NOT NULL ENABLE, 
	"TRANSITION_RATE" BINARY_DOUBLE, 
	"NUMBER_OF_ISSUER" NUMBER(10,0), 
	"DEFAULT_RATE" BINARY_DOUBLE, 
	"ANNUAL_PD_RATE" BINARY_DOUBLE, 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
