CREATE TABLE "PSAK413"."TMP_SCH_MAX" 
   (	"MASTERID" NVARCHAR2(100), 
	"MAX_PMTDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
