CREATE TABLE "PSAK413"."TMP_IFRS_PD_RUNNING_DATE" 
   (	"PKID" NUMBER(19,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" VARCHAR2(22), 
	"HISTORICAL_DATA" NUMBER(19,0), 
	"CURR_DATE" DATE, 
	"START_HISTORICAL_DATE" DATE, 
	"DEFAULT_RULE_ID" NUMBER(19,0), 
	"CALC_METHOD" VARCHAR2(100), 
	"PREV_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
