CREATE TABLE "PSAK413"."TMP_T10" 
   (	"MASTERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"FEE_AMT" NUMBER(32,6), 
	"COST_AMT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
