CREATE TABLE "PSAK413"."TMP_LI_GS2" 
   (	"MASTERID" NVARCHAR2(100), 
	"DTMIN" DATE, 
	"CNTMIN" NUMBER(10,0), 
	"NEXT_EIR" BINARY_DOUBLE, 
	"NEXT_EIR_NOCF" BINARY_DOUBLE, 
	"STAFFLOAN" NUMBER(10,0), 
	"BENEFIT" NUMBER(32,6), 
	"FEE_AMT" NUMBER(32,6), 
	"COST_AMT" NUMBER(32,6), 
	"PREV_EIR" BINARY_DOUBLE, 
	"NEXT_UNAMORT" NUMBER(32,6), 
	"GAIN_LOSS_FEE_AMT" NUMBER(32,6), 
	"GAIN_LOSS_COST_AMT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
