CREATE TABLE "PSAK413"."TMP_IFRS_DEPENDENT_VARIABLE" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
