CREATE TABLE "PSAK413"."TMP_IFRS_MULT_LINEAR_REGR_RSLT" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MODEL_SEQ" NUMBER(10,0), 
	"RESIDUAL_STD_ERR" BINARY_DOUBLE, 
	"DEG_OF_FREEDOM" NUMBER(10,0), 
	"MULT_R_SQUARED" BINARY_DOUBLE, 
	"ADJ_R_SQUARED" BINARY_DOUBLE, 
	"F_STATISTIC" BINARY_DOUBLE, 
	"P_VALUE" BINARY_DOUBLE, 
	"RESIDUAL_MIN" BINARY_DOUBLE, 
	"RESIDUAL_1Q" BINARY_DOUBLE, 
	"RESIDUAL_MEDIAN" BINARY_DOUBLE, 
	"RESIDUAL_3Q" BINARY_DOUBLE, 
	"RESIDUAL_MAX" BINARY_DOUBLE, 
	"DF_REGR" NUMBER(10,0), 
	"DF_RESD" NUMBER(10,0), 
	"DF_TOTAL" NUMBER(10,0), 
	"SUM_OF_SQR_REGR" BINARY_DOUBLE, 
	"SUM_OF_SQR_RESD" BINARY_DOUBLE, 
	"SUM_OF_SQR_TOTAL" BINARY_DOUBLE, 
	"MEAN_SUM_OF_SQR_REGR" BINARY_DOUBLE, 
	"MEAN_SUM_OF_SQR_RESD" BINARY_DOUBLE, 
	"SELECTED_FLAG" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
