CREATE TABLE "PSAK413"."TMP_IFRS_SCN_GENERATE_QUERY" 
   (	"ID" NUMBER, 
	"RULE_ID" NUMBER, 
	"SEQUENCE" NUMBER, 
	"SEGMENT_TYPE" VARCHAR2(50), 
	"TABLE_NAME" VARCHAR2(100), 
	"CONDITION" VARCHAR2(4000), 
	"DATA_DATE" DATE, 
	"SEGMENT" VARCHAR2(50), 
	"SUB_SEGMENT" VARCHAR2(50), 
	"GROUP_SEGMENT" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
