CREATE TABLE "PSAK413"."X_IMA_PD_DIFF" 
   (	"SEGMENT" VARCHAR2(100), 
	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" VARCHAR2(100), 
	"MASTERID" NUMBER, 
	"DPD" NUMBER, 
	"DPD_ORI" NUMBER, 
	"DPD_CIF" NUMBER, 
	"DPDX" NUMBER, 
	"PREV_BUCKET_ID" NUMBER, 
	"REAL_BUCKET_ID" NUMBER, 
	"PD_RULE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
