CREATE TABLE "PSAK413"."X_PSAK_MASTER_ACCOUNT_MONTHLY_DPD" 
   (	"DOWNLOAD_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"DAY_PAST_DUE_MONTHLY" NUMBER(31,0), 
	"DAY_PAST_DUE" NUMBER(31,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
