CREATE TABLE "PSAK413"."2019_COMMITMENT" 
   (	"BUSS_DATE" NVARCHAR2(50), 
	"COMMITMENT_REFERENCE" NVARCHAR2(50), 
	"BRANCH" NVARCHAR2(50), 
	"DEAL_TYPE" NVARCHAR2(50), 
	"DEAL_REF" NVARCHAR2(50), 
	"BRANCH_MNEMONIC" NVARCHAR2(50), 
	" ORIGINAL_COMMITMENT_AMOUNT " NVARCHAR2(50), 
	" UNUSED_COMMITMENT_AMOUNT " NVARCHAR2(50), 
	"AGREEMENT_DATE" NVARCHAR2(50), 
	"FIRST_DRAWDOWN_DATE" NVARCHAR2(50), 
	"FINAL_REPAYMENT_DATE" NVARCHAR2(50), 
	"COMMITMENT_TITLE" NVARCHAR2(50), 
	"COMMITMENT_DETAILS_LINE_1" NVARCHAR2(50), 
	"COMMITMENT_DETAILS_LINE_2" NVARCHAR2(50), 
	"COMMITMENT_DETAILS_LINE_3" NVARCHAR2(50), 
	"COMMITMENT_DETAILS_LINE_4" NVARCHAR2(50), 
	"COMMITMENT_AMOUNT" NVARCHAR2(50), 
	"EXPIRY_DATE" NVARCHAR2(50), 
	"CCY" NVARCHAR2(50), 
	"CIF" NVARCHAR2(50), 
	"REVOLVING_STATUS" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
