CREATE TABLE "PSAK413"."AC_MAX" 
   (	"FACILITY_NUMBER" NVARCHAR2(50), 
	"MAX_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
