CREATE TABLE "PSAK413"."BSI_FINAL_UPD_DPD" 
   (	"DOWNLOAD_DATE" VARCHAR2(50), 
	"DATA_SOURCE" VARCHAR2(50), 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"PRODUCT_TYPE" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"BI_COLLECTABILITY" VARCHAR2(5), 
	"DAY_PAST_DUE" NUMBER(31,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
