CREATE TABLE "PSAK413"."CKPN_LBUS" 
   (	"FICMISDATE" DATE, 
	"NOMORREKENING" VARCHAR2(25), 
	"JENISVALUTA" VARCHAR2(3), 
	"KUALITAS" VARCHAR2(1), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"SALDOHARGAPOKOK" NUMBER(22,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
