CREATE TABLE "PSAK413"."CURRENT_PD" 
   (	"OBLIGOR_GRADE" NVARCHAR2(5), 
	"PD" BINARY_DOUBLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
