CREATE TABLE "PSAK413"."DM_LIMIT" 
   (	"YMD" DATE, 
	"BR_CD" NVARCHAR2(100), 
	"LIMIT_ID" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
