CREATE TABLE "PSAK413"."GTMP_PD_ZSCORE_CONFIG" 
   (	"PD_RULE_ID" NUMBER, 
	"BUCKET_GROUP" VARCHAR2(30), 
	"INCREMENT_PERIOD" NUMBER(10,0), 
	"CURR_DATE" DATE, 
	"CUT_OFF_DATE" DATE, 
	"ME_CODE" VARCHAR2(100), 
	"CALC_METHOD" VARCHAR2(30), 
	"EXPECTED_LIFE" NUMBER(10,0), 
	"PERIOD_START" DATE, 
	"PERIOD_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
