CREATE TABLE "PSAK413"."IFRS_ARCHIVE_MASTER" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"TABLE_SRC" NVARCHAR2(60), 
	"CATALOG_SRC" NVARCHAR2(60), 
	"SCHEMA_SRC" NVARCHAR2(60), 
	"TABLE_DEST" NVARCHAR2(60), 
	"CATALOG_DEST" NVARCHAR2(60), 
	"SCHEMA_DEST" NVARCHAR2(60), 
	"COL_NAME_DATE" NVARCHAR2(50), 
	"RETENTION_DAYS" NUMBER(10,0), 
	"EOM" NUMBER(10,0) DEFAULT 0, 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50), 
	"UPDATEDBY" NVARCHAR2(50), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(50), 
	"LAG_1MONTH_FLAG" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
