CREATE TABLE "PSAK413"."IFRS_MASTER_LIMIT_CORP" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"COMMITMENT_ID" NVARCHAR2(50), 
	"BRANCH_CODE" NVARCHAR2(20), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CURRENCY" NCHAR(3), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"LIMIT_AMT" NUMBER(32,6), 
	"USED_AMT" NUMBER(32,6), 
	"UNUSED_AMT" NUMBER(32,6), 
	"START_DATE" DATE, 
	"DUE_DATE" DATE, 
	"REVOLVING_FLAG" NCHAR(1), 
	"COMMITMENT_FLAG" NCHAR(1), 
	"SOURCE_SYSTEM" NVARCHAR2(6), 
	"CUSTOMER_NAME" NVARCHAR2(150), 
	"CUSTOMER_TYPE" NVARCHAR2(10), 
	"ACCOUNT_TYPE" NVARCHAR2(10), 
	"SUN_ID" NVARCHAR2(30), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'ADMIN', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50) DEFAULT 'LOCALHOST', 
	"SANDI_BANK" NVARCHAR2(10), 
	"BI_COLLECTABILITY" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
