CREATE TABLE "PSAK413"."IFRS_EAD_CCF_DETAIL_FACILITY" 
   (	"DOWNLOAD_DATE" DATE, 
	"CCF_RULE_ID" NUMBER(10,0), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"EQV_PLAFOND_AT_DEFAULT" NUMBER(32,6), 
	"EQV_PLAFOND_12M_BEFORE_DEFAULT" NUMBER(32,6), 
	"EQV_OS_12M_BEFORE_DEFAULT" NUMBER(32,6), 
	"EQV_AT_DEFAULT" NUMBER(32,6), 
	"DRAWDOWN" BINARY_DOUBLE, 
	"HEADROOM" BINARY_DOUBLE, 
	"CCF" BINARY_DOUBLE, 
	"EXCLUDE" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50), 
	"UPDATEDBY" NVARCHAR2(50), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
