CREATE TABLE "PSAK413"."IFRS_EVENT_CHANGES" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"MASTERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"ACCOUNT_NUMBER" NVARCHAR2(70), 
	"EFFECTIVE_DATE" DATE, 
	"BEFORE_VALUE" NVARCHAR2(30) NOT NULL ENABLE, 
	"AFTER_VALUE" NVARCHAR2(30) NOT NULL ENABLE, 
	"EVENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REMARKS" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(50), 
	"CREATED_DATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
