CREATE TABLE "PSAK413"."IFRS_LGD_REC_UR_DETAIL" 
   (	"PKID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER, 
	"DEFAULT_DATE" DATE, 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"MASTERID" VARCHAR2(50), 
	"EIR_AT_DEFAULT" FLOAT(126), 
	"RECOVERY_DATE" FLOAT(126), 
	"EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"REC_OS" NUMBER(32,6), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
