CREATE TABLE "PSAK413"."IFRS_LI_FUNDING_SUMM" 
   (	"MASTERID" NVARCHAR2(100), 
	"SUMM_INT_AMT" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
