CREATE TABLE "PSAK413"."IFRS_PD_MAA_FLOWRATE_SUM_S_00000_0000" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"BASE_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" VARCHAR2(30), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"FLOWRATE" NUMBER, 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE NOT NULL ENABLE, 
	"CREATEDHOST" VARCHAR2(30), 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
