CREATE TABLE "PSAK413"."IFRS_RECOVERY_SCENARIO_DATA" 
   (	"DOWNLOAD_DATE" DATE, 
	"LGD_RULE_ID" NUMBER(20,0), 
	"LGD_RULE_NAME" NVARCHAR2(100), 
	"DEFAULT_RULE_ID" NUMBER(20,0), 
	"MASTERID" NVARCHAR2(100), 
	"SEGMENT" NVARCHAR2(50), 
	"SUB_SEGMENT" NVARCHAR2(50), 
	"GROUP_SEGMENT" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"LGD_METHOD" NVARCHAR2(50), 
	"CALC_METHOD" NVARCHAR2(10), 
	"RECOVERY_AMOUNT" NUMBER(32,6), 
	"BI_COLLECTABILITY" NUMBER(5,0), 
	"DAY_PAST_DUE" NUMBER(10,0), 
	"LGD_UNIQUE_ID" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
