CREATE TABLE "PSAK413"."IFRS_STAGE" 
   (	"PKID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MASTERID" NUMBER(19,0), 
	"CUSTOMER_NUMBER" VARCHAR2(100), 
	"CUSTOMER_NAME" VARCHAR2(150), 
	"ACCOUNT_NUMBER" VARCHAR2(100), 
	"STAGE" CHAR(1), 
	"STAGE_OVERRIDE" CHAR(1), 
	"OVERRIDE_LEVEL" VARCHAR2(25), 
	"OVERRIDE_DATE" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"CREATEDBY" VARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" DATE NOT NULL ENABLE, 
	"CREATEDHOST" VARCHAR2(36) NOT NULL ENABLE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(30), 
	 CONSTRAINT "PK_IFRS_STAGE" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
