CREATE TABLE "PSAK413"."IFRS_IMP_OVERRIDETRIGGERD" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"OVERRIDE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"TRIGGERID" NVARCHAR2(10), 
	"FLAG_TRIGGER" NCHAR(1), 
	"REMARK" NVARCHAR2(2000), 
	"DCFSTATUS" NVARCHAR2(1), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"UPDATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
