CREATE TABLE "PSAK413"."IFRS_IMP_PD_FL_TERM_YEARLY" 
   (	"DOWNLOAD_DATE" DATE, 
	"PD_EFFECTIVE_DATE" DATE, 
	"SCALAR_EFFECTIVE_DATE" DATE, 
	"EIL_MODEL_ID" NUMBER(20,0), 
	"SEGMENTATION_ID" NUMBER(10,0), 
	"PD_RULE_ID" NUMBER(20,0), 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"ME_MODEL_ID" NUMBER(10,0), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_ID" NUMBER(5,0), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"FL_SEQ" NUMBER(5,0), 
	"FL_YEAR" NUMBER(5,0), 
	"PD_RATE" BINARY_DOUBLE, 
	"SCALAR" BINARY_DOUBLE, 
	"PD_FINAL" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"PD_SCALAR" BINARY_DOUBLE, 
	"CUMULATIVE_PD_SCALAR" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
