CREATE TABLE "PSAK413"."IFRS_LI_GS_DATE1" 
   (	"MASTERID" NVARCHAR2(100), 
	"PMT_DATE" DATE, 
	"PERIOD" NUMBER(20,0), 
	"PMT_OS" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
