CREATE TABLE "PSAK413"."IFRS_PRC_DATE_AMORT" 
   (	"CURRDATE" DATE, 
	"PREVDATE" DATE, 
	"RUNNING_FLAG_FROM_DW" NCHAR(1), 
	"BATCH_STATUS" NVARCHAR2(50), 
	"REMARK" NVARCHAR2(250), 
	"LAST_PROCESS_DATE" DATE, 
	"SESSIONID" NVARCHAR2(50), 
	"PRC_NAME" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
