CREATE TABLE "PSAK413"."IFRS_LGD_UR_DETAIL_S_00000_0000" 
   (	"PKID" NUMBER NOT NULL ENABLE, 
	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER, 
	"DEFAULT_DATE" DATE, 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"MASTERID" VARCHAR2(50), 
	"EIR_AT_DEFAULT" FLOAT(126), 
	"EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"REC_OS" NUMBER(32,6), 
	"NPV_EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"NPV_EQV_REC_OS" NUMBER(32,6), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"UPDATEDBY" VARCHAR2(36), 
	"UPDATEDDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
