CREATE TABLE "PSAK413"."IFRS_LI_NOMINATIF_TRS" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NVARCHAR2(100), 
	"MASTER_ACCOUNT_CODE" NVARCHAR2(100), 
	"ACCOUNT_NUMBER" NVARCHAR2(100), 
	"OUTSTANDING" NVARCHAR2(50), 
	"CARRYING_AMOUNT" NVARCHAR2(50), 
	"ACCUMULATIVE_INTEREST" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
