CREATE TABLE "PSAK413"."IFRS_BUCKET_DETAIL_OLD" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"SUB_BUCKET_GROUP" NVARCHAR2(100), 
	"BUCKET_ID" NUMBER(5,0), 
	"BUCKET_NAME" NVARCHAR2(100), 
	"RANGE_START" NUMBER(5,0), 
	"RANGE_END" NUMBER(10,0) NOT NULL ENABLE, 
	"MINIMUM_PD" BINARY_DOUBLE, 
	"MAXIMUM_PD" BINARY_DOUBLE, 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACTIVE_FLAG" NUMBER(10,0) DEFAULT 0, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST' NOT NULL ENABLE, 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
