CREATE TABLE "PSAK413"."IFRS_EIL_MODEL_DETAIL_LGD_HIST" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"EIL_MODEL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SEGMENTATION_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"LGD_MODEL_ID" NUMBER(20,0), 
	"ME_MODEL_ID" NUMBER(20,0), 
	"EIL_MODEL_ID_OLD" NUMBER(20,0), 
	"EFF_DATE_OPTION" NVARCHAR2(50), 
	"EFF_DATE" DATE, 
	"IS_NEW" NUMBER(10,0), 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
