CREATE TABLE "PSAK413"."IFRS_IAP_LIST_SCENARIO" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50) NOT NULL ENABLE, 
	"SCENARIO_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"SCENARIO_NAME" NVARCHAR2(50), 
	"PROBABILITY_OUTCOME" BINARY_DOUBLE, 
	"IAP_PARAM_HEADERID" NUMBER(20,0) NOT NULL ENABLE, 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM' NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30), 
	"IIP_AMOUNT" NUMBER(32,6), 
	"DISC_CASH_FLOW" NUMBER(32,6), 
	"WORKOUT_PERIOD" NUMBER(10,0), 
	"MASTERID" NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
