CREATE TABLE "PSAK413"."IFRS_AC_BM_MASTER_QUEST_D" 
   (	"PKID" NUMBER(20,0) NOT NULL ENABLE, 
	"COMMONCODEID" NVARCHAR2(50), 
	"QUESTIONID" NUMBER(20,0), 
	"OPTION_ID" NUMBER(20,0), 
	"OPTION_DESC" NVARCHAR2(100), 
	"CREATEDBY" NVARCHAR2(36) DEFAULT 'SYSTEM', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(36) DEFAULT 'LOCALHOST', 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(36), 
	"IS_DELETE" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "PK__IFRS_AC___5E0282727E1183F1" PRIMARY KEY ("PKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
