CREATE TABLE "PSAK413"."IFRS_COLL_PRORATE" 
   (	"DOWNLOAD_DATE" DATE, 
	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_NAME" NVARCHAR2(100), 
	"FACILITY_NUMBER" NVARCHAR2(50), 
	"ACCOUNT_NUMBER" NVARCHAR2(100), 
	"MASTERID" NVARCHAR2(100), 
	"IAS_CLASS" NVARCHAR2(50), 
	"DATA_SOURCE" NVARCHAR2(20), 
	"PRODUCT_CODE" NVARCHAR2(20), 
	"OUTSTANDING_LCY" NUMBER(32,6), 
	"TOTAL_COLL_AMOUNT_LCY" NUMBER(32,6), 
	"PRORATE_COLLATERAL_LCY" NUMBER(32,6), 
	"UNUSED_AMOUNT_LCY" NUMBER(32,6), 
	"REMAINING_COLL_AMOUNT_LCY" NUMBER(32,6), 
	"CREATEDBY" NVARCHAR2(50) DEFAULT 'SP_IFRS_IMP_COLL_PRORATE', 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(50) DEFAULT 'SYSTEMS', 
	"CURRENCY_MASTER" NCHAR(3), 
	"EXCHANGE_RATE_MASTER" NUMBER(32,6), 
	"SUM_OS_LCY_PRIORITY" NUMBER(32,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
