CREATE TABLE "PSAK413"."IFRS_PD_MAA_ODR" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"TOT_DEFAULT" FLOAT(126), 
	"NON_DEFAULT" FLOAT(126), 
	"ODR" FLOAT(126), 
	"CREATEDBY" VARCHAR2(36), 
	"CREATEDDATE" DATE, 
	"BASE_DATE" DATE, 
	"ODR_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
