CREATE TABLE "PSAK413"."IFRS_PD_MAA_FLOWRATE_SMOOTH_S_00000_0000" 
   (	"EFF_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0), 
	"BUCKET_GROUP" VARCHAR2(30), 
	"BUCKET_FROM" NUMBER, 
	"BUCKET_TO" NUMBER, 
	"FLOWRATE" NUMBER, 
	"SMOOTHED_PD" NUMBER, 
	"LOGIT_ODR" NUMBER, 
	"PREDICTED_LOGIT_ODR" NUMBER, 
	"PREDICTED_PD" NUMBER, 
	"FLOWRATE_SMOOTH_PD" NUMBER, 
	"CREATEDBY" VARCHAR2(30), 
	"CRATEDDATE" DATE, 
	"CREATEDHOST" VARCHAR2(36), 
	"UPDATEDBY" VARCHAR2(30), 
	"UPDATEDDATE" DATE, 
	"UPDATEDHOST" VARCHAR2(36)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
