CREATE TABLE "PSAK413"."IMA_CUST_DPD" 
   (	"CUSTOMER_NUMBER" NVARCHAR2(50), 
	"DAY_PAST_DUE_CIF" NUMBER(10,0), 
	"BI_COLLECT_CIF" NUMBER(10,0), 
	"DPD_FINAL_CIF" NUMBER(10,0), 
	"RESTRUCTURE_COLLECT_FLAG_CIF" NUMBER(10,0), 
	"BUSINESS_UNIT" NCLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BUSINESS_UNIT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
