CREATE TABLE "PSAK413"."PSAK_MASTER_ACCOUNT" 
   (	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"MASTER_ACCOUNT_ID" VARCHAR2(100), 
	"DATA_SOURCE" VARCHAR2(20), 
	"PRODUCT_TYPE" VARCHAR2(20), 
	"PRODUCT_CODE" VARCHAR2(10), 
	"BRANCH_CODE" VARCHAR2(20), 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"ACCOUNT_NUMBER_PREVIOUS" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"ACCOUNT_STATUS" VARCHAR2(5), 
	"LOAN_START_DATE" TIMESTAMP (6), 
	"LOAN_DUE_DATE" TIMESTAMP (6), 
	"PAYMENT_CODE" VARCHAR2(20), 
	"PAYMENT_TERM" VARCHAR2(2), 
	"INTEREST_CALCULATION_CODE" VARCHAR2(20), 
	"INTEREST_RATE" NUMBER(31,6), 
	"AMORT_TYPE" VARCHAR2(10), 
	"EIR" NUMBER(31,6), 
	"EIR_AMOUNT" NUMBER(31,6), 
	"UNAMOR_TRANS_COST_AMT" NUMBER(31,6), 
	"UNAMOR_ORIGINATION_FEE_AMT" NUMBER(31,6), 
	"UNAMOR_AMT_TOTAL" NUMBER(31,6), 
	"OUTSTANDING_POKOK" NUMBER(31,6), 
	"OUTSTANDING_MARGIN" NUMBER(31,6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
