CREATE TABLE "PSAK413"."STG_TRX_PSAK71_REV" 
   (	"BUSS_DATE" DATE, 
	"BRANCH" NVARCHAR2(4), 
	"ACCOUNT_NO" NVARCHAR2(8), 
	"DESCRIPTION" NVARCHAR2(50), 
	"CCY" NVARCHAR2(3), 
	"ACCOUNT_TYPE" NVARCHAR2(2), 
	"VALUE_DATE" DATE, 
	"SIGN" NVARCHAR2(1), 
	"AMOUNT" NUMBER(32,6), 
	"NARRATIVE1" NVARCHAR2(35), 
	"GROUP_OR_USER_ID" NVARCHAR2(25) DEFAULT 'SYSTEM', 
	"TIME_STAMP" NVARCHAR2(26), 
	"PRODUCT_CODE" NVARCHAR2(6), 
	"CUSTOMER_TYPE" NVARCHAR2(4), 
	"TRANSACTION_RATE" NUMBER(32,6), 
	"AMOUNT_LEV" NUMBER(32,6), 
	"JURNAL_NUMBER" NVARCHAR2(60), 
	"SOURCE_DATA" NVARCHAR2(10) DEFAULT 'REGLA', 
	"EVENT_TYPE" NVARCHAR2(35), 
	"CLASS" NCHAR(1), 
	"TRANSACTION_TYPE" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
