CREATE TABLE "PSAK413"."TBLT_UNWINDING_WEIGHTED_PEND" 
   (	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"OVERRIDE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"ESTIMATED_REALIZATION_DATE" DATE, 
	"MARGINUNWINDING" NUMBER(32,6), 
	"BALANCE" NUMBER(32,6), 
	"DCFSTATUS" NVARCHAR2(1), 
	"CREATEDBY" NVARCHAR2(36) NOT NULL ENABLE, 
	"CREATEDDATE" TIMESTAMP (8) NOT NULL ENABLE, 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
