CREATE TABLE "PSAK413"."TBLU_SYNDICATION_UNAMORT_ACCOUNT" 
   (	"EFF_DATE" DATE NOT NULL ENABLE, 
	"LOAN_NUMBER" NVARCHAR2(50) NOT NULL ENABLE, 
	"CCY" NCHAR(3) NOT NULL ENABLE, 
	"UNAMORT_AMT" NUMBER(32,6), 
	"UPLOADID" NUMBER(20,0), 
	"UPLOADBY" NVARCHAR2(36), 
	"UPLOADDATE" TIMESTAMP (8), 
	"UPLOADHOST" NVARCHAR2(30), 
	"APPROVEDBY" NVARCHAR2(36), 
	"APPROVEDDATE" TIMESTAMP (8), 
	"APPROVEDHOST" NVARCHAR2(30), 
	 CONSTRAINT "PK_TBLU_SYNDICATION_UNAMORT_ACCOUNT" PRIMARY KEY ("EFF_DATE", "LOAN_NUMBER", "CCY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
