CREATE TABLE "PSAK413"."TEMP_TFC" 
   (	"MASTERID" NVARCHAR2(100), 
	"TFEE" NUMBER(30,10), 
	"TCOST" NUMBER(30,10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
