CREATE TABLE "PSAK413"."TMP_IFRS_PD_WO" 
   (	"PD_UNIQUE_ID" VARCHAR2(100), 
	"WO_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"PD_RULE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
