CREATE TABLE "PSAK413"."TMP_ENR_CURR" 
   (	"DOWNLOAD_DATE" DATE, 
	"BASE_DATE" DATE, 
	"TO_DATE" DATE, 
	"PD_RULE_ID" NUMBER(20,0), 
	"PD_RULE_NAME" NVARCHAR2(100), 
	"BUCKET_GROUP" NVARCHAR2(30), 
	"BUCKET_FROM" NUMBER(5,0), 
	"BUCKET_TO" NUMBER(5,0), 
	"CALC_AMOUNT" NUMBER(32,6), 
	"TOTAL_ACCOUNT" NUMBER(20,0), 
	"CALC_METHOD" NVARCHAR2(50), 
	"PERCENTAGE" BINARY_DOUBLE, 
	"CREATEDBY" NVARCHAR2(36), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDHOST" NVARCHAR2(30), 
	"UPDATEDBY" NVARCHAR2(36), 
	"UPDATEDDATE" TIMESTAMP (8), 
	"UPDATEDHOST" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
