CREATE TABLE "PSAK413"."TMP_GS1" 
   (	"MASTERID" NVARCHAR2(100), 
	"UNAMORT1" BINARY_DOUBLE, 
	"UNAMORT2" BINARY_DOUBLE, 
	"EIR1" BINARY_DOUBLE, 
	"EIR2" BINARY_DOUBLE, 
	"UNAMORT_NOCF1" BINARY_DOUBLE, 
	"UNAMORT_NOCF2" BINARY_DOUBLE, 
	"EIR_NOCF1" BINARY_DOUBLE, 
	"EIR_NOCF2" BINARY_DOUBLE, 
	"UNAMORT_GLOSS1" BINARY_DOUBLE, 
	"UNAMORT_GLOSS2" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
