CREATE TABLE "PSAK413"."TMP_LI_JRNL1" 
   (	"MASTERID" NVARCHAR2(100), 
	"FACNO" NVARCHAR2(50), 
	"CIFNO" NVARCHAR2(50), 
	"ACCTNO" NVARCHAR2(70), 
	"DATASOURCE" NVARCHAR2(20), 
	"PRDTYPE" NVARCHAR2(50), 
	"PRDCODE" NVARCHAR2(20), 
	"TRXCODE" NVARCHAR2(20), 
	"CCY" NVARCHAR2(5), 
	"JOURNALCODE" NVARCHAR2(20), 
	"JOURNALCODE2" NVARCHAR2(10), 
	"STATUS" NVARCHAR2(20), 
	"REVERSE" NVARCHAR2(3), 
	"FLAG_CF" NVARCHAR2(3), 
	"N_AMOUNT" NUMBER(32,6), 
	"SOURCEPROCESS" NVARCHAR2(20), 
	"CREATEDDATE" TIMESTAMP (8), 
	"CREATEDBY" NVARCHAR2(30), 
	"BRANCH" NVARCHAR2(20), 
	"IS_PNL" NVARCHAR2(3)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
