CREATE TABLE "PSAK413"."TMP_X2" 
   (	"DOWNLOAD_DATE" DATE, 
	"CCY" NVARCHAR2(5), 
	"MASTERID" NVARCHAR2(100), 
	"JOURNALCODE" NVARCHAR2(10), 
	"AMOUNT" NUMBER(32,6), 
	"ACCTNO" NVARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
