CREATE TABLE "PSAK413"."TMP_T7" 
   (	"MID" NVARCHAR2(100), 
	"STAFFLOAN" NUMBER(10,0), 
	"PKID" NUMBER(20,0), 
	"NPVRATE" NUMBER(18,10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
