CREATE INDEX "PSAK413"."IDX_IFRS_PD_TERM_STRUCTURE_NOFL" ON "PSAK413"."IFRS_PD_TERM_STRUCTURE_NOFL" ("PD_RULE_ID", "DOWNLOAD_DATE", "FL_YEAR", "FL_MONTH", "BUCKET_GROUP", "BUCKET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
