CREATE INDEX "PSAK413"."IDX_IFRS_IMP_PD_FL_JOIN" ON "PSAK413"."IFRS_IMP_PD_FL_TERM_STRUCTURE" ("EIL_MODEL_ID", "SEGMENTATION_ID", "PD_RULE_ID", "BUCKET_ID", "FL_SEQ", "DOWNLOAD_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
