CREATE INDEX "PSAK413"."IDX_IFRS_IMA_GCN_CNUM" ON "PSAK413"."IFRS_MASTER_ACCOUNT" ("DOWNLOAD_DATE", "GLOBAL_CUSTOMER_NUMBER", "CUSTOMER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
