CREATE INDEX "PSAK413"."IFRS_MASTER_ACCOUNT_1M_ECL_DOWNLOAD_DATE_MASTERID_MASTER_ACCOU_" ON "PSAK413"."IFRS_MASTER_ACCOUNT_OLD" ("DOWNLOAD_DATE", "MASTERID", "MASTER_ACCOUNT_CODE", "PRODUCT_CODE", "ACCOUNT_NUMBER", "DATA_SOURCE", "GROUP_SEGMENT", "SEGMENT", "SUB_SEGMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
