CREATE INDEX "PSAK413"."IX_GTMP_LGD_REC_DATA1" ON "PSAK413"."GTMP_IFRS_LGD_REC_DATA1" ("DOWNLOAD_DATE", "MASTERID") ;


-- PSAK413.GTMP_IFRS_LGD_REC_UR_DETAIL definition

CREATE GLOBAL TEMPORARY TABLE "PSAK413"."GTMP_IFRS_LGD_REC_UR_DETAIL" 
   (	"EFF_DATE" DATE, 
	"LGD_RULE_ID" NUMBER, 
	"DEFAULT_DATE" DATE, 
	"FACILITY_NUMBER" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(50), 
	"MASTERID" VARCHAR2(50), 
	"EIR_AT_DEFAULT" FLOAT(126), 
	"RECOVERY_DATE" FLOAT(126), 
	"EQV_OS_AT_DEFAULT" NUMBER(32,6), 
	"EQV_REC_OS" NUMBER(32,6), 
	"SUM_EQV_REC_OS" NUMBER(32,6), 
	"OS_AT_DEFAULT" NUMBER(32,6), 
	"REC_OS" NUMBER(32,6), 
	"SUM_REC_OS" NUMBER(32,6)
   ) ON COMMIT PRESERVE ROWS ;
