CREATE INDEX "PSAK413"."IX_GTMP_LGD_DATA1" ON "PSAK413"."GTMP_IFRS_LGD_DATA1" ("MASTERID") ;


-- PSAK413.GTMP_IFRS_LGD_REC_DATA1 definition

CREATE GLOBAL TEMPORARY TABLE "PSAK413"."GTMP_IFRS_LGD_REC_DATA1" 
   (	"DOWNLOAD_DATE" DATE, 
	"MASTERID" NUMBER(19,0), 
	"CCY" VARCHAR2(5), 
	"EXCHANGE_RATE" NUMBER(32,6), 
	"LGD_SEGMENT_ID" NUMBER(19,0), 
	"LGD_RULE_ID" NUMBER(19,0)
   ) ON COMMIT PRESERVE ROWS ;
