CREATE INDEX "PSAK413"."IXGTT_IMA" ON "PSAK413"."GTMP_IMA_DPD" ("DOWNLOAD_DATE", "MASTERID") ;


-- PSAK413.GTMP_LOGIT_ODR definition

CREATE GLOBAL TEMPORARY TABLE "PSAK413"."GTMP_LOGIT_ODR" 
   (	"PD_RULE_ID" NUMBER, 
	"BUCKET_ID" NUMBER, 
	"LOGIT_ODR" NUMBER
   ) ON COMMIT PRESERVE ROWS ;
