CREATE INDEX "PSAK413"."NCI_STG_N3L_UNDRAWN" ON "PSAK413"."TMP_STG_N3L_UNDRAWN" ("LIMIT_ID", "REPORT_LIMIT_ID", "YMD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
