CREATE INDEX "PSAK413"."NONCLUSTEREDINDEX-20200616-105921" ON "PSAK413"."TMP_IFRS_PD_SCENARIO_DATA_NOLAG" ("DOWNLOAD_DATE", "PD_RULE_ID", "DEFAULT_RULE_ID", "BUCKET_GROUP", "MASTERID", "SEGMENT", "SUB_SEGMENT", "GROUP_SEGMENT", "ACCOUNT_NUMBER", "CUSTOMER_NUMBER", "PD_METHOD", "CALC_METHOD", "BUCKET_ID", "IMPAIRED_FLAG", "DEFAULT_FLAG", "RATING_CODE", "PD_UNIQUE_ID", "BUCKET_ID_ORIG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
