CREATE UNIQUE INDEX "PSAK413"."PK__TBLU_PD_EXTERNAL_SOV" ON "PSAK413"."TBLU_PD_SNP_SOVEREIGN" ("EFF_DATE", "SUB_SEGMENT", "BUCKET_FROM", "BUCKET_TO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
