CREATE UNIQUE INDEX "PSAK413"."PK__TBLU_PD___E33E39A844DDF5E3" ON "PSAK413"."TBLU_PD_SNP_CORPORATE" ("EFF_DATE", "SUB_SEGMENT", "BUCKET_FROM", "BUCKET_TO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
