CREATE UNIQUE INDEX "PSAK413"."PK_IFRS_ME_DERIVED_VARIABLE_TEMP" ON "PSAK413"."IFRS_ME_DERIVED_VARIABLE_TEMP" ("PKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
