CREATE UNIQUE INDEX "PSAK413"."PK_IFRS_TRX_FACILITY" ON "PSAK413"."IFRS_TRX_FACILITY" ("PKID", "TRX_EFFDATE", "TRX_FACILITY_NO", "TRX_CODE", "TRX_DR_CR", "TRX_CCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
