CREATE UNIQUE INDEX "PSAK413"."PK_TBLU_LGD_EXTERNAL_RECOVERY" ON "PSAK413"."TBLU_LGD_EXTERNAL_RECOVERY" ("EFF_DATE", "LIEN_POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
