CREATE UNIQUE INDEX "PSAK413"."PK_TBLM_SCREENGROUPDETAIL" ON "PSAK413"."TBLM_SCREENGROUPDETAIL" ("SCREENGROUPID", "SCREENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
