CREATE UNIQUE INDEX "PSAK413"."PK_TBLU_TM_MOODYS" ON "PSAK413"."TBLU_TM_MOODYS" ("EFF_DATE", "RATING_FROM", "RATING_TO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
