CREATE UNIQUE INDEX "PSAK413"."PK_TBLU_SYNDICATION_UNAMORT_ACCOUNT" ON "PSAK413"."TBLU_SYNDICATION_UNAMORT_ACCOUNT" ("EFF_DATE", "LOAN_NUMBER", "CCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
