CREATE INDEX "PSAK413"."PK_TMP_IFRS_ECL_IMA_COVIDOPMZDGUKHX" ON "PSAK413"."TMP_IFRS_EIL_IMA_COVID" ("DOWNLOAD_DATE", "MASTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
