CREATE UNIQUE INDEX "PSAK413"."PK_TBLU_RETAIL_SEGMENT" ON "PSAK413"."TBLU_RETAIL_SEGMENT" ("EFF_DATE", "ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
