CREATE UNIQUE INDEX "PSAK413"."PK_TBLU_EAD_CCF" ON "PSAK413"."TBLU_EAD_CCF" ("EFF_DATE", "ASSET_TYPE_PRODUCT1", "ASSET_TYPE_PRODUCT2", "ORIGINAL_TENOR_LOW", "ORIGINAL_TENOR_HIGH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
