CREATE INDEX "PSAK413"."TMP_IFRS_PD_SCENARIO_DATA_PD_RULE_ID_IDX" ON "PSAK413"."TMP_IFRS_PD_SCENARIO_DATA" ("PD_RULE_ID", "PD_UNIQUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
