CREATE INDEX "PSAK413"."TMP_PD_CLOSE_PD_UNIQUE_ID_IDX" ON "PSAK413"."TMP_PD_CLOSE" ("PD_UNIQUE_ID", "CALC_METHOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
