CREATE OR REPLACE FUNCTION F_CHECK_SEQUENCE_PROCESS(
	P_PRC_NAME CHARACTER VARYING,
	P_RUN_ID CHARACTER VARYING)
    RETURNS INTEGER
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
V_CHECK_SEQ INTEGER;
BEGIN
    SELECT MAX(SEQ) AS SEQ INTO V_CHECK_SEQ FROM IFRS_LOG_SEQUENCE_PROCESS WHERE P_RUN_ID = '' || P_RUN_ID || '' AND PRC_NAME = '' || P_PRC_NAME || '';
    RETURN V_CHECK_SEQ;
END;
$BODY$;
