CREATE OR REPLACE PROCEDURE PSAK413.X_SP_IFRS_PATCH_SEGMENT
AS
	dtcurr DATE;
	dtprev DATE;
BEGIN

	 dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);

				--KORPORASI--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI_PIUTANG'
								WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI_PIUTANG'	
								WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
							END, 
					
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI_MURABAHAH'
									WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI_QARDH'	
									WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
								END,
								
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI'
										WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI'	
										WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
								END
				WHERE 
					PSAK55_SEGMENT = 'KORPORASI'
				AND DOWNLOAD_DATE = dtcurr;
				
				--COMMERCIAL--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL_PIUTANG'
								WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL_PIUTANG'	
								WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
							END, 
					
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL_MURABAHAH'
									WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL_QARDH'	
									WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
								END,
								
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL'
										WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL'	
										WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
								END
				WHERE 
					PSAK55_SEGMENT = 'COMMERCIAL'
				AND DOWNLOAD_DATE = dtcurr;
				
				--BISNIS BANKING/SMALL--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME_PIUTANG'
								WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME_PIUTANG'	
								WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
							END, 
					
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME_MURABAHAH'
									WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME_QARDH'	
									WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
								END,
								
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME'
										WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME'	
										WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
								END
				WHERE 
					PSAK55_SEGMENT = 'BISNIS BANKING/SMALL'
				AND DOWNLOAD_DATE = dtcurr;
				
				--PENSIUN & PRA PENSIUN--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN&PRAPENSIUN_PIUTANG'
								WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN&PRAPENSIUN_PIUTANG'	
								WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
								WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001') THEN 'PENSIUN&PRAPENSIUN_PIUTANG'
							END, 
					
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN&PRAPENSIUN_PIUTANG_MURABAHAH'
									WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN&PRAPENSIUN_PIUTANG_QARDH'	
									WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
									WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001') THEN 'PENSIUN&PRAPENSIUN_RAHN'
								END,
								
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN & PRA PENSIUN'
										WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN & PRA PENSIUN'	
										WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
										WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001')	THEN 'PENSIUN & PRA PENSIUN'
								END
				WHERE 
					PSAK55_SEGMENT = 'PENSIUN & PRA PENSIUN'
				AND DOWNLOAD_DATE = dtcurr;
				
				--BACK TO BACK & MURABAHAH EMAS--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'BTB_MRB_EMAS_PIUTANG'
								WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'BTB_MRB_EMAS_PIUTANG'	
								WHEN PRODUCT_TYPE = 'RAHN' 			THEN 'GADAI_EMAS_PIUTANG'
							END, 
					
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'BTB_MRB_EMAS_MURABAHAH'
									WHEN PRODUCT_TYPE = 'QARDH'	   	THEN 'BTB_MRB_EMAS_QARDH'	
									WHEN PRODUCT_TYPE = 'RAHN' 		THEN 'GADAI_EMAS_RAHN'
								END,
								
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'BTB_MRB_EMAS'
										WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'BTB_MRB_EMAS'	
										WHEN PRODUCT_TYPE = 'RAHN' 			THEN 'GADAI_EMAS'
								END
				WHERE 
					PSAK55_SEGMENT = 'BACK TO BACK & MURABAHAH EMAS'
				AND DOWNLOAD_DATE = dtcurr;
				
				--KUR--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KUR_PIUTANG' END, 
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'KUR_MURABAHAH' END,
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'KUR' END
				WHERE 
					PSAK55_SEGMENT = 'KUR'
				AND DOWNLOAD_DATE = dtcurr;
				
				--NON KUR--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'NON_KUR_PIUTANG' END, 
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'NON_KUR_MURABAHAH' END,
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'NON_KUR' END
				WHERE 
					PSAK55_SEGMENT = 'NON KUR'
				AND DOWNLOAD_DATE = dtcurr;
				
				--IMPLAN--
				UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
				SET 
					SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'MULTIGUNA_PIUTANG' END, 
					SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'MULTIGUNA_MURABAHAH' END,
					GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'MULTIGUNA' END
				WHERE 
					PSAK55_SEGMENT = 'IMPLAN'
				AND DOWNLOAD_DATE = dtcurr;
				
				dbms_output.put_line(dtcurr||'|'||dtprev);
				dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));

			COMMIT;
			
	END LOOP;

END;
/
