CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_SYNC_CONFIG_SEQUENCE 
AS
BEGIN
    -- 1
    PSAK413.SP_IFRS_BUCKET_DETAIL();

    -- 2
    PSAK413.SP_IFRS_BUCKET_HEADER();

    -- 3
    -- PSAK413.SP_TBLT_PAYMENTEXPECTED();

    -- 4
    PSAK413.SP_IFRS_DEFAULT_CRITERIA();

    -- 5
    PSAK413.SP_IFRS_STAGE_CONFIG();

    -- 5
    -- PSAK413.SP_SYNC_TBLM_COMMONCODE();

    -- 6
    -- PSAK413.SP_IFRS_MASTER_PRODUCT_PARAM();

    -- 7
    PSAK413.SP_IFRS_SYNC_PARAM();

    -- 8
    PSAK413.SP_IFRS_SEGMENTATION_MAPPING();

    -- 9
    PSAK413.SP_IFRS_LGD_WORKOUT_RULES_CONFIG();

    -- 10
    PSAK413.SP_IFRS_LIFETIME_RULES_CONFIG();

    -- 11
    PSAK413.SP_IFRS_PD_RULES_CONFIG();

    -- 12
    PSAK413.SP_IFRS_LGD_RULES_CONFIG();

    -- 13
    PSAK413.SP_IFRS_EAD_RULES_CONFIG();

    -- 14
    PSAK413.SP_IFRS_EIL_MODEL_HEADER();

    -- 15
    PSAK413.SP_IFRS_EIL_MODEL_DETAIL_EAD();

    -- 16
    PSAK413.SP_IFRS_EIL_MODEL_DETAIL_PF();

    -- 17
    PSAK413.SP_IFRS_EIL_MODEL_DETAIL_PD();

    -- 18
    PSAK413.SP_IFRS_EIL_MODEL_DETAIL_LGD();

    -- 19
    PSAK413.SP_IFRS_CLEAN_SIMULATION_TABLES();

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_IFRS_SYNC_CONFIG_SEQUENCE;