CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_DEFAULT_RULE_DEV (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AUTHID CURRENT_USER
AS
	---- DATE   
    V_CURRDATE DATE; 
	V_EOMDATE DATE ;  

	---- PROCESS
	V_COUNT NUMBER;
	V_RULE_ID VARCHAR2(10);
	V_ID NUMBER DEFAULT 0; 
	V_MAX_ID NUMBER DEFAULT 0; 
	V_DATADATE VARCHAR(20); 
    ---- QUERY  
    V_STR_QUERY CLOB;
	V_STR_SQL_RULE CLOB;
    V_SQL_CONDITIONS CLOB;
    V_SCRIPT1 CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    V_SYSCODE VARCHAR(500);
 
BEGIN
    
    V_SPNAME := 'SP_IFRS_DEFAULT_RULE_DEV';
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CASE 
        		WHEN CURRDATE = LAST_DAY(CURRDATE) THEN CURRDATE
        		ELSE LAST_DAY(ADD_MONTHS(CURRDATE, -1))
    		END, LAST_DAY(CURRDATE)
        INTO V_CURRDATE,V_EOMDATE 
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    ----- TAMBAHAN JIKA P_SYSCODE NYA DI DAPAT NULL
    IF COALESCE(P_SYSCODE, NULL) IS NULL THEN
        V_SYSCODE := '0';
	ELSE
		V_SYSCODE := P_SYSCODE;
    END IF;
 
 	IF V_CURRDATE = V_EOMDATE THEN   
 		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY';
 	ELSE 
 		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY';
 	END IF;
 	
    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'IFRS_DEFAULT_' || P_RUNID || ''; 
    ELSE 
        V_TABLEINSERT1 := 'IFRS_DEFAULT'; 
    END IF;

    IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_DEFAULT', V_TABLEINSERT1);    
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, 'SP_IFRS_LGD_RULE_DATA', P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------
    
	EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG';
	 
    V_STR_QUERY := 'INSERT INTO PSAK413.GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG
               SELECT * FROM PSAK413.IFRS_LGD_WORKOUT_RULES_CONFIG
               WHERE IS_DELETED = 0 AND (  
                 UPPER(TRIM(SYSCODE_WORKOUT)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(''' || V_SYSCODE || ''', ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(''' || V_SYSCODE || ''', ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR ''' || V_SYSCODE || ''' = ''0''
               )';

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.GTMP_IFRS_PD_RULES_CONFIG';

    V_STR_QUERY := 'INSERT INTO PSAK413.GTMP_IFRS_PD_RULES_CONFIG (PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)' ||
               'SELECT PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE' || 
					 	' FROM PSAK413.IFRS_PD_RULES_CONFIG ' ||
               'WHERE PD_METHOD = ''MAA'' AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(''' || V_SYSCODE || ''', ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(''' || V_SYSCODE || ''', ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR ''' || V_SYSCODE || ''' = ''0'' 
               )';
    
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE PSAK413.TMPRULE';

    V_STR_QUERY := 'INSERT INTO PSAK413.TMPRULE
    SELECT DISTINCT DEFAULT_RULE_ID
    FROM PSAK413.GTMP_IFRS_PD_RULES_CONFIG
    WHERE IS_ACTIVE = 1
    AND IS_DELETED = 0';

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    V_STR_QUERY := 'INSERT INTO PSAK413.TMPRULE
    SELECT DISTINCT DEFAULT_RULE_ID
    FROM PSAK413.GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG
    WHERE IS_DELETED = 0';

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '
    WHERE RULE_ID IN (SELECT DEFAULT_RULE_ID FROM PSAK413.TMPRULE)
    AND DOWNLOAD_DATE = LAST_DAY(DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''')';

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    ----------------------------------------------------------------
    ---- LOOP RULE
    ----------------------------------------------------------------
    FOR r_rule IN (
        SELECT
		    A.PKID,
		    A.SQL_CONDITIONS
		FROM PSAK413.IFRS_DEFAULT_CRITERIA A
		JOIN PSAK413.TMPRULE B
		  ON A.PKID = B.DEFAULT_RULE_ID
		ORDER BY A.PKID     
    )
    LOOP
        V_RULE_ID := r_rule.PKID;
    	V_SQL_CONDITIONS := r_rule.SQL_CONDITIONS;
       
        V_SCRIPT1 :=' ' || V_SQL_CONDITIONS || ' ';
        ------------------------------------------------------------------
        -- BUILD FINAL INSERT SQL
        ------------------------------------------------------------------
        V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' (
                DOWNLOAD_DATE,
                RULE_ID,
                MASTERID,
                FACILITY_NUMBER,
                CUSTOMER_NUMBER,
                OS_AT_DEFAULT,
                EQV_AT_DEFAULT,
                PLAFOND_AT_DEFAULT,
                EQV_PLAFOND_AT_DEFAULT,
                EIR_AT_DEFAULT,
                CCY_AT_DEFAULT,
                CREATED_DATE
            )
            SELECT
                LAST_DAY(ifrs_master_account.DOWNLOAD_DATE),
                ' || V_RULE_ID || ',
                ifrs_master_account.MASTERID,
                ifrs_master_account.FACILITY_NUMBER,
                ifrs_master_account.CUSTOMER_NUMBER,
                NVL(B.OUTSTANDING, ifrs_master_account.OUTSTANDING),
                NVL(B.OUTSTANDING, ifrs_master_account.OUTSTANDING) * ifrs_master_account.EXCHANGE_RATE,
                ifrs_master_account.PLAFOND,
                ifrs_master_account.PLAFOND * ifrs_master_account.EXCHANGE_RATE,
                NVL(ifrs_master_account.EIR, ifrs_master_account.MARGIN_RATE),
                ifrs_master_account.CURRENCY,
                SYSDATE
            FROM ' || V_TAB_OWNER || '.' || V_TABLE_NAME || ' ifrs_master_account
            LEFT JOIN PSAK413.IFRS_MASTER_ACCOUNT_WO B
                   ON ifrs_master_account.MASTERID = B.MASTERID
                  AND ifrs_master_account.DOWNLOAD_DATE >= B.DOWNLOAD_DATE
            WHERE ifrs_master_account.DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''
            AND ' || V_SCRIPT1 ||'';

        DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
        EXECUTE IMMEDIATE V_STR_QUERY;
    END LOOP;

    COMMIT;

    V_STR_QUERY := 'MERGE INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A
	USING (
	    SELECT
	        A.RULE_ID,
	        A.DOWNLOAD_DATE,
	        A.MASTERID,
	        B.OUTSTANDING AS OS_12M,
	        B.OUTSTANDING * B.EXCHANGE_RATE EQV_OS_12M,
	        ROW_NUMBER() OVER (
	            PARTITION BY A.RULE_ID, A.MASTERID
	            ORDER BY B.DOWNLOAD_DATE
	        ) RN
	    FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A
	    JOIN ' || V_TAB_OWNER || '.' || V_TABLE_NAME || ' B
	      ON A.MASTERID = B.MASTERID
	    JOIN PSAK413.TMPRULE C
	      ON A.RULE_ID = C.DEFAULT_RULE_ID
	    WHERE B.DOWNLOAD_DATE BETWEEN ADD_MONTHS(A.DOWNLOAD_DATE, -12)
	                              AND A.DOWNLOAD_DATE
	      AND A.DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''
	      AND B.OUTSTANDING > 0
	) B
	ON (
	    A.RULE_ID = B.RULE_ID
	    AND A.MASTERID = B.MASTERID
	    AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
	)
	WHEN MATCHED THEN
	UPDATE SET
	    A.OS_12M_BEFORE_DEFAULT      = B.OS_12M,
	    A.EQV_OS_12M_BEFORE_DEFAULT  = B.EQV_OS_12M
	WHERE B.RN = 1';

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;

    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_STR_QUERY := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = DATE ''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || '''';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_STR_QUERY, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END;