CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_CLOSED
AS
    V_CURRDATE DATE ;
    V_PREVDATE DATE;

BEGIN

    SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT ;

    INSERT INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'START' ,'SP_IFRS_ACCT_CLOSED' ,'') ;
    COMMIT;


    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_ACCT';
    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_ACCT( MASTERID)
    SELECT  A.MASTERID
    FROM    IFRS_IMA_AMORT_CURR A
    LEFT JOIN IFRS_IMA_AMORT_PREV B ON A.MASTERID = B.MASTERID
    WHERE   B.MASTERID IS NULL;
    COMMIT;


    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'DEBUG' ,'SP_IFRS_ACCT_CLOSED ACCTSTATUS' ,'');
    /*
    UPDATE  IFRS_MASTER_ACCOUNT
    SET     IFRS_ACCT_STATUS = 'OLD'
    WHERE   DOWNLOAD_DATE = @v_currdate

    UPDATE  IMA_AMORT_CURR
    SET     IFRS_ACCT_STATUS = 'OLD'
    WHERE   DOWNLOAD_DATE = @v_currdate

    UPDATE  IFRS_MASTER_ACCOUNT
    SET     IFRS_ACCT_STATUS = 'NEW'
    WHERE   DOWNLOAD_DATE = @v_currdate
            AND MASTER_ACCOUNT_ID IN ( SELECT masterid FROM TMP_ACCT )

    UPDATE  IMA_AMORT_CURR
    SET     IFRS_ACCT_STATUS = 'NEW'
    WHERE   DOWNLOAD_DATE = @v_currdate
            AND MASTERID IN ( SELECT masterid FROM TMP_ACCT)
    */
    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'DEBUG' ,'SP_IFRS_ACCT_CLOSED CLS' ,'');

    -- insert account closed
    DELETE /*+ PARALLEL(12) */ FROM IFRS_ACCT_CLOSED
    WHERE   DOWNLOAD_DATE = V_CURRDATE ;
    COMMIT;

    --adding 20170227 to get eir account
    EXECUTE IMMEDIATE 'truncate table TMP_T1';
    COMMIT;

    --get eir account
    INSERT /*+ PARALLEL(12) */ INTO TMP_T1 (MASTERID)
    (SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
    FROM IFRS_IMA_AMORT_CURR
    WHERE AMORT_TYPE = 'EIR'
    UNION
    SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
    FROM IFRS_IMA_AMORT_PREV
    WHERE AMORT_TYPE = 'EIR');
    /*end adding 20170227*/
    COMMIT;

    --amort type eir
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_CLOSED
    ( FACNO ,
      CIFNO ,
      DATASOURCE ,
      DOWNLOAD_DATE ,
      MASTERID ,
      ACCTNO
    )
    SELECT  /*+ PARALLEL(12) */ A.FACILITY_NUMBER ,
            A.CUSTOMER_NUMBER ,
            A.DATA_SOURCE ,
            V_CURRDATE ,
            A.MASTERID ,
            A.ACCOUNT_NUMBER
    FROM    IFRS_IMA_AMORT_CURR A
    INNER JOIN TMP_T1 C ON A.MASTERID = C.MASTERID
    WHERE ( A.WRITEOFF_FLAG = 'Y' OR A.ACCOUNT_STATUS = 'W')
			OR (A.ACCOUNT_STATUS IN ('C','E','CE','CT','CN'))
			OR (A.OUTSTANDING <= 0)
			OR (A.LOAN_DUE_DATE <= V_CURRDATE)
      OR (a.bi_collectability IN ('3','4','5','C'));
    COMMIT;


    --adding 20170227 to get sl account
    EXECUTE IMMEDIATE 'truncate table TMP_T1';
    COMMIT;

    --get sl account
    INSERT /*+ PARALLEL(12) */ INTO TMP_T1 (MASTERID)
    SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
    FROM IFRS_IMA_AMORT_CURR
    WHERE AMORT_TYPE = 'SL'
    UNION
    SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
    FROM IFRS_IMA_AMORT_PREV
    WHERE AMORT_TYPE = 'SL';
    /*end adding 20170227*/
    COMMIT;

    --amort type sl
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_CLOSED
    ( FACNO ,
      CIFNO ,
      DATASOURCE ,
      DOWNLOAD_DATE ,
      MASTERID ,
      ACCTNO
    )
    SELECT  /*+ PARALLEL(12) */ A.FACILITY_NUMBER ,
            A.CUSTOMER_NUMBER ,
            A.DATA_SOURCE ,
            V_CURRDATE ,
            A.MASTERID ,
            A.ACCOUNT_NUMBER
            FROM IFRS_IMA_AMORT_CURR A
    INNER JOIN TMP_T1 C ON A.MASTERID = C.MASTERID
    WHERE ( A.WRITEOFF_FLAG = 'Y' OR A.ACCOUNT_STATUS = 'W')
			OR (A.ACCOUNT_STATUS IN ('C','E','CE','CT','CN'))
			OR (A.LOAN_DUE_DATE <= V_CURRDATE)
      OR (a.bi_collectability IN ('3','4','5','C'));
    COMMIT;


	--account hilang
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_CLOSED
    ( FACNO ,
      CIFNO ,
      DATASOURCE ,
      DOWNLOAD_DATE ,
      MASTERID ,
      ACCTNO
    )
    SELECT  /*+ PARALLEL(12) */ A.FACILITY_NUMBER ,
            A.CUSTOMER_NUMBER ,
            A.DATA_SOURCE ,
            V_CURRDATE ,
            A.MASTERID ,
            A.ACCOUNT_NUMBER
            FROM    IFRS_IMA_AMORT_PREV A
    LEFT JOIN IFRS_IMA_AMORT_CURR B ON A.MASTERID = B.MASTERID
    WHERE B.MASTERID IS NULL;
    COMMIT;

    -- PNL SISA UNAMORT IF IFRS9 CLASS FVTPL
	INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_CLOSED
	(
		FACNO
		,CIFNO
		,DATASOURCE
		,DOWNLOAD_DATE
		,MASTERID
		,ACCTNO
	)
	SELECT /*+ PARALLEL(12) */ A.FACILITY_NUMBER
		,A.CUSTOMER_NUMBER
		,A.DATA_SOURCE
		,V_CURRDATE
		,A.MASTERID
		,A.ACCOUNT_NUMBER
	FROM IFRS_IMA_AMORT_CURR A
	WHERE A.IFRS9_CLASS = 'FVTPL'
	AND A.DOWNLOAD_DATE = V_CURRDATE;

    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_ACCT_CLOSED' ,'');
    COMMIT;

END;