CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_SWITCH
AS
	V_CURRDATE DATE;
	V_PREVDATE DATE;
	V_NUM NUMBER(10);
BEGIN
	SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT ;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LBM_ACCT_EIR_SWITCH','');
    COMMIT;

	--RESET
	UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_CF_PREV
	SET STATUS = 'ACT'
	WHERE STATUS = 'REV'
	AND CREATEDBY = 'EIR_SWITCH'
	AND DOWNLOAD_DATE = V_CURRDATE;

	COMMIT;

	UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_CF_PREV
	SET STATUS = 'ACT'
	WHERE STATUS = 'REV2'
	AND CREATEDBY = 'EIR_SWITCH'
	AND DOWNLOAD_DATE = V_PREVDATE;

	COMMIT;

	-- EXIST PROC IF NO NEED TO PROCESS EIR SWITCH
	SELECT COUNT(*) INTO V_NUM
	FROM IFRS_LBM_ACCT_SWITCH
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND PREV_EIR_ECF = 'Y';

	IF V_NUM<=0
	THEN
      INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
      VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_SWITCH','');
	  COMMIT;
      RETURN;
    END IF;

	-- COPY ECF FROM OLD TO NEW ACCTNO
	INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_ECF (
	DOWNLOAD_DATE
	,MASTERID
	,N_LOAN_AMT
	,N_INT_RATE
	,N_EFF_INT_RATE
	,STARTAMORTDATE
	,ENDAMORTDATE
	,GRACEDATE
	,PAYMENTCODE
	,INTCALCCODE
	,PAYMENTTERM
	,ISGRACE
	,PREV_PMT_DATE
	,PMT_DATE
	,I_DAYS
	,I_DAYS2
	,N_OSPRN_PREV
	,N_INSTALLMENT
	,N_PRN_PAYMENT
	,N_INT_PAYMENT
	,N_OSPRN
	,N_FAIRVALUE_PREV
	,N_EFF_INT_AMT
	,N_FAIRVALUE
	,N_UNAMORT_AMT_PREV
	,N_AMORT_AMT
	,N_UNAMORT_AMT
	,N_COST_UNAMORT_AMT_PREV
	,N_COST_AMORT_AMT
	,N_COST_UNAMORT_AMT
	,N_FEE_UNAMORT_AMT_PREV
	,N_FEE_AMORT_AMT
	,N_FEE_UNAMORT_AMT
	,AMORTSTOPDATE
	,AMORTSTOPMSG
	,N_DAILY_AMORT_COST
	,N_DAILY_AMORT_FEE
	,N_EFF_INT_AMT0
	,N_EFF_INT_RATE0
	,N_DAILY_INT_ADJ_AMT
	,N_INT_ADJ_AMT
	-- SWITCH ADJUST CARRY FORWARD
	,SW_ADJ_COST
	,SW_ADJ_FEE
	,NOCF_OSPRN
	,NOCF_OSPRN_PREV
	,NOCF_INT_RATE
	,NOCF_PRN_PAYMENT
	,NOCF_EFF_INT_AMT
	,NOCF_UNAMORT_AMT_PREV
	,NOCF_AMORT_AMT
	,NOCF_UNAMORT_AMT
	)
	SELECT /*+ PARALLEL(12) */ V_CURRDATE
	,A.MASTERID
	,B.N_LOAN_AMT
	,B.N_INT_RATE
	,B.N_EFF_INT_RATE
	,B.STARTAMORTDATE
	,B.ENDAMORTDATE
	,B.GRACEDATE
	,B.PAYMENTCODE
	,B.INTCALCCODE
	,B.PAYMENTTERM
	,B.ISGRACE
	,B.PREV_PMT_DATE
	,B.PMT_DATE
	,B.I_DAYS
	,B.I_DAYS2
	,B.N_OSPRN_PREV
	,B.N_INSTALLMENT
	,B.N_PRN_PAYMENT
	,B.N_INT_PAYMENT
	,B.N_OSPRN
	,B.N_FAIRVALUE_PREV
	,B.N_EFF_INT_AMT
	,B.N_FAIRVALUE
	,B.N_UNAMORT_AMT_PREV
	,B.N_AMORT_AMT
	,B.N_UNAMORT_AMT
	,B.N_COST_UNAMORT_AMT_PREV
	,B.N_COST_AMORT_AMT
	,B.N_COST_UNAMORT_AMT
	,B.N_FEE_UNAMORT_AMT_PREV
	,B.N_FEE_AMORT_AMT
	,B.N_FEE_UNAMORT_AMT
	,B.AMORTSTOPDATE
	,'EIR_SWITCH_2'
	,B.N_DAILY_AMORT_COST
	,B.N_DAILY_AMORT_FEE
	,B.N_EFF_INT_AMT0
	,B.N_EFF_INT_RATE0
	,B.N_DAILY_INT_ADJ_AMT
	,B.N_INT_ADJ_AMT
	-- SWITCH ADJUST CARRY FORWARD
	,B.SW_ADJ_COST
	,B.SW_ADJ_FEE
	,B.NOCF_OSPRN
	,B.NOCF_OSPRN_PREV
	,B.NOCF_INT_RATE
	,B.NOCF_PRN_PAYMENT
	,B.NOCF_EFF_INT_AMT
	,B.NOCF_UNAMORT_AMT_PREV
	,B.NOCF_AMORT_AMT
	,B.NOCF_UNAMORT_AMT
	FROM IFRS_LBM_ACCT_SWITCH A
	JOIN IFRS_LBM_ACCT_EIR_ECF B
	ON B.AMORTSTOPDATE IS NULL
		AND B.MASTERID = A.PREV_MASTERID
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
		AND A.PREV_EIR_ECF = 'Y';

	COMMIT;

	-- COPY OLD COST FEE ECF TO NEW ACCT
	INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_COST_FEE_ECF (
	DOWNLOAD_DATE
	,ECFDATE
	,MASTERID
	,BRCODE
	,CIFNO
	,FACNO
	,ACCTNO
	,DATASOURCE
	,CCY
	,PRDCODE
	,TRXCODE
	,FLAG_CF
	,FLAG_REVERSE
	,METHOD
	,STATUS
	,SRCPROCESS
	,AMOUNT
	,CREATEDDATE
	,CREATEDBY
	,SEQ
	,AMOUNT_ORG
	,ORG_CCY
	,ORG_CCY_EXRATE
	,PRDTYPE
	,CF_ID
	)
	SELECT /*+ PARALLEL(12) */ C.DOWNLOAD_DATE
	,V_CURRDATE
	,A.MASTERID
	,A.BRCODE
	,A.CIFNO
	,A.FACNO
	,A.ACCTNO
	,A.DATASOURCE
	,C.CCY
	,A.PRDCODE
	,C.TRXCODE
	,C.FLAG_CF
	,C.FLAG_REVERSE
	,C.METHOD
	,C.STATUS
	,C.SRCPROCESS
	,C.AMOUNT
	,SYSTIMESTAMP
	,'EIR_SWITCH'
	,C.SEQ
	,C.AMOUNT_ORG
	,C.ORG_CCY
	,C.ORG_CCY_EXRATE
	,A.PRDTYPE
	,C.CF_ID
	FROM IFRS_LBM_ACCT_SWITCH A
	JOIN IFRS_LBM_ACCT_EIR_ECF B
	ON B.AMORTSTOPDATE IS NULL
		AND B.MASTERID = A.PREV_MASTERID
		AND B.PREV_PMT_DATE = B.PMT_DATE
		AND B.DOWNLOAD_DATE < V_CURRDATE -- ADD FILTER FOR BRANCH CHANGE
	JOIN IFRS_LBM_ACCT_EIR_COST_FEE_ECF C
	ON C.ECFDATE = B.DOWNLOAD_DATE
		AND C.MASTERID = B.MASTERID
		AND C.STATUS = 'ACT'
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
		AND A.PREV_EIR_ECF = 'Y';

    COMMIT;

	--REV OLD COST FEE PREV
	MERGE INTO IFRS_ACCT_SL_COST_FEE_PREV A
    USING  (SELECT C.MASTERID,C.DOWNLOAD_DATE,C.SEQ
            FROM IFRS_LBM_ACCT_SWITCH A
            JOIN IFRS_PRC_DATE_AMORT P ON P.CURRDATE=A.DOWNLOAD_DATE
            JOIN VW_LBM_LAST_EIR_CF_PREV C ON C.MASTERID=A.PREV_MASTERID
            WHERE A.PREV_EIR_ECF='Y'
            ) C
    ON (A.DOWNLOAD_DATE=C.DOWNLOAD_DATE
        AND A.MASTERID=C.MASTERID
        AND A.SEQ=C.SEQ
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.STATUS=CASE WHEN A.DOWNLOAD_DATE=V_CURRDATE THEN 'REV' ELSE 'REV2' END
      , A.CREATEDBY='EIR_SWITCH';

	COMMIT;

	--COPY OLD COST FEE PREV TO NEW ACCT
	INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_CF_PREV (
	DOWNLOAD_DATE
	,ECFDATE
	,MASTERID
	,BRCODE
	,CIFNO
	,FACNO
	,ACCTNO
	,DATASOURCE
	,CCY
	,PRDCODE
	,TRXCODE
	,FLAG_CF
	,FLAG_REVERSE
	,METHOD
	,STATUS
	,SRCPROCESS
	,AMOUNT
	,CREATEDDATE
	,CREATEDBY
	,ISUSED
	,SEQ
	,AMOUNT_ORG
	,ORG_CCY
	,ORG_CCY_EXRATE
	,PRDTYPE
	,CF_ID
	)
	SELECT /*+ PARALLEL(12) */ V_CURRDATE
	,V_CURRDATE
	,A.MASTERID
	,A.BRCODE
	,A.CIFNO
	,A.FACNO
	,A.ACCTNO
	,A.DATASOURCE
	,D.CCY
	,A.PRDCODE
	,D.TRXCODE
	,D.FLAG_CF
	,D.FLAG_REVERSE
	,D.METHOD
	,'ACT' STATUS
	,D.SRCPROCESS
	,D.AMOUNT
	,SYSTIMESTAMP
	,'EIR_SWITCH'
	,D.ISUSED
	,'0' SEQ_NEW
	,D.AMOUNT_ORG
	,D.ORG_CCY
	,D.ORG_CCY_EXRATE
	,A.PRDTYPE
	,D.CF_ID
	FROM IFRS_LBM_ACCT_SWITCH A
	JOIN VW_LBM_LAST_EIR_CF_PREV C ON C.MASTERID = A.PREV_MASTERID
	JOIN IFRS_LBM_ACCT_EIR_CF_PREV D ON D.DOWNLOAD_DATE = C.DOWNLOAD_DATE
	AND D.MASTERID = C.MASTERID
	AND D.SEQ = C.SEQ
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
	AND A.PREV_EIR_ECF = 'Y';

	COMMIT;

	-- STOP OLD ECF
	UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_ECF
	SET AMORTSTOPDATE = V_CURRDATE
	,AMORTSTOPMSG = 'EIR_SWITCH'
	WHERE AMORTSTOPDATE IS NULL
	AND DOWNLOAD_DATE < V_CURRDATE -- ADD FILTER FOR BRANCH CHANGE
	AND MASTERID IN (
		SELECT PREV_MASTERID
		FROM IFRS_LBM_ACCT_SWITCH
		WHERE DOWNLOAD_DATE = V_CURRDATE
		AND PREV_EIR_ECF = 'Y'
	);

	COMMIT;

	-- HANDLE ACF THAT IS DOING ACCRU YESTERDAY
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T1';

	INSERT /*+ PARALLEL(12) */ INTO TMP_T1 (MASTERID)
	SELECT /*+ PARALLEL(12) */ PREV_MASTERID AS MASTERID
	FROM IFRS_LBM_ACCT_SWITCH
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND PREV_EIR_ECF = 'Y';

	COMMIT;

	-- NO ACCRU IF YESTERDAY IS DOING AMORT
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T2';

	INSERT /*+ PARALLEL(12) */ INTO TMP_T2 (MASTERID)
	SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
	FROM IFRS_LBM_ACCT_EIR_ACF
	WHERE DOWNLOAD_DATE = V_PREVDATE
	AND DO_AMORT = 'Y';

	COMMIT;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T3';

	INSERT /*+ PARALLEL(12) */ INTO TMP_T3 (MASTERID)
	SELECT /*+ PARALLEL(12) */ A.MASTERID
	FROM TMP_T1 A;

	COMMIT;

	--LEFT JOIN TMP_T2 B ON B.MASTERID=A.MASTERID
	--WHERE B.MASTERID IS NULL
	-- GET LAST ACF WITH DO_AMORT=N
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_P1';

	INSERT /*+ PARALLEL(12) */ INTO TMP_P1 (ID)
	SELECT /*+ PARALLEL(12) */ MAX(ID) AS ID
	FROM IFRS_LBM_ACCT_EIR_ACF
	WHERE MASTERID IN (
		SELECT MASTERID
		FROM TMP_T3
	)
	AND DO_AMORT = 'N'
	GROUP BY MASTERID;

	COMMIT;

	--UPDATE SW ADJ COST/FEE FOR LBM
	MERGE INTO IFRS_LBM_ACCT_SWITCH A
    USING (SELECT B.MASTERID,B.N_ACCRU_COST,B.N_ACCRU_FEE, V_CURRDATE CURRDATE
           FROM IFRS_LBM_ACCT_EIR_ACF B
           WHERE B.ID IN (SELECT ID FROM TMP_P1)
           ) B
    ON (A.DOWNLOAD_DATE = B.CURRDATE
        AND A.PREV_EIR_ECF = 'Y'
        AND A.PREV_MASTERID = B.MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.SW_ADJ_COST=B.N_ACCRU_COST
    ,A.SW_ADJ_FEE=B.N_ACCRU_FEE;

    COMMIT;

	-- GET FEE SUMMARY
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_TF';

	INSERT /*+ PARALLEL(12) */ INTO TMP_TF (
	SUM_AMT
	,DOWNLOAD_DATE
	,MASTERID
	)
	SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT
	,A.DOWNLOAD_DATE
	,A.MASTERID
	FROM (
		SELECT CASE
		WHEN A.FLAG_REVERSE = 'Y'
		 THEN - 1 * A.AMOUNT
		ELSE A.AMOUNT
		END AS N_AMOUNT
		,A.ECFDATE DOWNLOAD_DATE
		,A.MASTERID
		FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
		WHERE A.MASTERID IN (
			SELECT MASTERID
			FROM TMP_T3
		)
		AND A.STATUS = 'ACT'
		AND A.FLAG_CF = 'F'
		AND A.METHOD = 'EIR'
	) A
	GROUP BY A.DOWNLOAD_DATE
	,A.MASTERID;

	COMMIT;

	-- GET COST SUMMARY
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_TC';

	INSERT /*+ PARALLEL(12) */ INTO TMP_TC (
		SUM_AMT
		,DOWNLOAD_DATE
		,MASTERID
	)
	SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT
	,A.DOWNLOAD_DATE
	,A.MASTERID
	FROM (
		SELECT CASE
		WHEN A.FLAG_REVERSE = 'Y'
		 THEN - 1 * A.AMOUNT
		ELSE A.AMOUNT
		END AS N_AMOUNT
		,A.ECFDATE DOWNLOAD_DATE
		,A.MASTERID
		FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
		WHERE A.MASTERID IN (
			SELECT MASTERID
			FROM TMP_T3
		)
		AND A.STATUS = 'ACT'
		AND A.FLAG_CF = 'C'
		AND A.METHOD = 'EIR'
	) A
	GROUP BY A.DOWNLOAD_DATE
	,A.MASTERID;

	COMMIT;

	--INSERT FEE 1
	INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_ACCRU_PREV (
	FACNO
	,CIFNO
	,DOWNLOAD_DATE
	,ECFDATE
	,DATASOURCE
	,PRDCODE
	,TRXCODE
	,CCY
	,AMOUNT
	,STATUS
	,CREATEDDATE
	,ACCTNO
	,MASTERID
	,FLAG_CF
	,FLAG_REVERSE
	,AMORTDATE
	,SRCPROCESS
	,ORG_CCY
	,ORG_CCY_EXRATE
	,PRDTYPE
	,CF_ID
	)
	SELECT /*+ PARALLEL(12) */ A.FACNO
	,A.CIFNO
	,V_CURRDATE
	,A.ECFDATE
	,A.DATASOURCE
	,B.PRDCODE
	,B.TRXCODE
	,B.CCY
	,CAST(CAST(CASE
	 WHEN B.FLAG_REVERSE = 'Y'
	  THEN - 1 * B.AMOUNT
	 ELSE B.AMOUNT
	 END AS BINARY_DOUBLE) / CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32, 20)) * A.N_ACCRU_FEE AS N_AMOUNT
	,B.STATUS
	,SYSTIMESTAMP
	,A.ACCTNO
	,A.MASTERID
	,B.FLAG_CF
	,'N'
	,NULL AS AMORTDATE
	,'SW'
	,B.ORG_CCY
	,B.ORG_CCY_EXRATE
	,B.PRDTYPE
	,B.CF_ID
	FROM IFRS_LBM_ACCT_EIR_ACF A
	JOIN IFRS_LBM_ACCT_EIR_COST_FEE_ECF B ON B.ECFDATE = A.ECFDATE
	AND A.MASTERID = B.MASTERID
	AND B.FLAG_CF = 'F'
	AND B.STATUS = 'ACT' --ADD LBM 20180823
	JOIN TMP_TF C ON C.DOWNLOAD_DATE = A.ECFDATE
	AND C.MASTERID = A.MASTERID
	WHERE A.ID IN (
	SELECT ID
	FROM TMP_P1
	);

	COMMIT;

	--COST 1
	INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_ACCRU_PREV (
	FACNO
	,CIFNO
	,DOWNLOAD_DATE
	,ECFDATE
	,DATASOURCE
	,PRDCODE
	,TRXCODE
	,CCY
	,AMOUNT
	,STATUS
	,CREATEDDATE
	,ACCTNO
	,MASTERID
	,FLAG_CF
	,FLAG_REVERSE
	,AMORTDATE
	,SRCPROCESS
	,ORG_CCY
	,ORG_CCY_EXRATE
	,PRDTYPE
	,CF_ID
	)
	SELECT /*+ PARALLEL(12) */ A.FACNO
	,A.CIFNO
	,V_CURRDATE
	,A.ECFDATE
	,A.DATASOURCE
	,B.PRDCODE
	,B.TRXCODE
	,B.CCY
	,CAST(CAST(CASE
	 WHEN B.FLAG_REVERSE = 'Y'
	  THEN - 1 * B.AMOUNT
	 ELSE B.AMOUNT
	 END AS BINARY_DOUBLE) / CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32, 20)) * A.N_ACCRU_COST AS N_AMOUNT
	,B.STATUS
	,SYSTIMESTAMP
	,A.ACCTNO
	,A.MASTERID
	,B.FLAG_CF
	,'N'
	,NULL AS AMORTDATE
	,'SW'
	,B.ORG_CCY
	,B.ORG_CCY_EXRATE
	,B.PRDTYPE
	,B.CF_ID
	FROM IFRS_LBM_ACCT_EIR_ACF A
	JOIN IFRS_LBM_ACCT_EIR_COST_FEE_ECF B ON B.ECFDATE = A.ECFDATE
	AND A.MASTERID = B.MASTERID
	AND B.FLAG_CF = 'C'
	AND B.STATUS = 'ACT' --ADD LBM 20180823
	JOIN TMP_TC C ON C.DOWNLOAD_DATE = A.ECFDATE
	AND C.MASTERID = A.MASTERID
	WHERE A.ID IN (
	SELECT ID
	FROM TMP_P1
	);

	COMMIT;

	--STOP OLD ACCRU BEFORE CURRDATE
	UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_ACCRU_PREV
	SET STATUS = TO_CHAR(V_CURRDATE,'YYYYMMDD')
	WHERE STATUS = 'ACT'
	--AND DOWNLOAD_DATE<V_CURRDATE
	AND MASTERID IN (
		SELECT PREV_MASTERID
		FROM IFRS_LBM_ACCT_SWITCH
		WHERE DOWNLOAD_DATE = V_CURRDATE
		AND PREV_EIR_ECF = 'Y'
	);

	COMMIT;

	-- SW ADJ COST FEE TO NEW ECF
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_SW1';

	INSERT /*+ PARALLEL(12) */ INTO TMP_SW1 (
		MASTERID
		,PMTDATE
	)
	SELECT /*+ PARALLEL(12) */ A.MASTERID
	,MIN(A.PMT_DATE) AS PMTDATE
	FROM IFRS_LBM_ACCT_EIR_ECF A
	JOIN IFRS_LBM_ACCT_SWITCH B ON B.MASTERID = A.MASTERID
	AND B.DOWNLOAD_DATE = V_CURRDATE
	AND B.PREV_EIR_ECF = 'Y'
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
	AND A.AMORTSTOPDATE IS NULL
	AND A.PMT_DATE >= V_CURRDATE
	AND A.PMT_DATE <> A.PREV_PMT_DATE
	GROUP BY A.MASTERID;

	COMMIT;

	MERGE INTO IFRS_LBM_ACCT_EIR_ECF A
    USING (SELECT A.*,B.SW_ADJ_COST,B.SW_ADJ_FEE,V_CURRDATE CURRDATE
           FROM TMP_SW1 A
           JOIN IFRS_LBM_ACCT_SWITCH B
             ON B.MASTERID = A.MASTERID
             AND B.DOWNLOAD_DATE = V_CURRDATE
             AND B.PREV_EIR_ECF = 'Y'
           ) X
    ON (A.DOWNLOAD_DATE = X.CURRDATE
        AND A.MASTERID = X.MASTERID
        AND A.PMT_DATE = X.PMTDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET  A.SW_ADJ_COST=COALESCE(A.SW_ADJ_COST,0)+X.SW_ADJ_COST
    ,A.SW_ADJ_FEE=COALESCE(A.SW_ADJ_FEE,0)+X.SW_ADJ_FEE;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_SWITCH','');

	COMMIT;
END;