CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_ACF_ACRU
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_ROUND NUMBER(10);
  V_FUNCROUND NUMBER(10);

BEGIN

    SELECT MAX(CURRDATE)
        , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    BEGIN
      SELECT CAST(VALUE1 AS NUMBER(10))
        , CAST(VALUE2 AS NUMBER(10)) INTO V_ROUND, V_FUNCROUND
      FROM TBLM_COMMONCODEDETAIL
      WHERE COMMONCODE = 'SCM003';
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      V_ROUND:=6;
      V_FUNCROUND:=1;
    END;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','');

    COMMIT;

    -- CLEAN UP
    DELETE /*+ PARALLEL(12) */ FROM IFRS_LBM_ACCT_EIR_ACF
    WHERE DOWNLOAD_DATE = V_CURRDATE
        AND DO_AMORT = 'N';
    COMMIT;

    DELETE /*+ PARALLEL(12) */ FROM IFRS_LBM_ACCT_EIR_CF_PREV
    WHERE DOWNLOAD_DATE = V_CURRDATE
        AND CREATEDBY = 'EIRACF02';
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','CLEAN UP');

    COMMIT;

    -- PREPARE INDEX
    --EXECUTE IMMEDIATE 'DROP INDEX PSAK_EIR_ECF_IDX1';
    --EXECUTE IMMEDIATE 'DROP INDEX IFRS_IMA_AMORT_CURR_IDX1';
    --EXECUTE IMMEDIATE 'CREATE INDEX PSAK_EIR_ECF_IDX1 ON IFRS_LBM_ACCT_EIR_ECF(MASTERID,PREV_PMT_DATE,PMT_DATE,AMORTSTOPDATE)';
    --EXECUTE IMMEDIATE 'CREATE INDEX IFRS_IMA_AMORT_CURR_IDX1 ON IFRS_LBM_ACCT_EIR_ECF(MASTERID)';
    -- INSERT ACF
    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_ACF (
        DOWNLOAD_DATE
        ,FACNO
        ,CIFNO
        ,DATASOURCE
        ,N_UNAMORT_COST
        ,N_UNAMORT_FEE
        ,N_AMORT_COST
        ,N_AMORT_FEE
        ,N_ACCRU_COST
        ,N_ACCRU_FEE
        ,N_ACCRUFULL_COST
        ,N_ACCRUFULL_FEE
        ,ECFDATE
        ,CREATEDDATE
        ,CREATEDBY
        ,MASTERID
        ,ACCTNO
        ,DO_AMORT
        ,BRANCH
        ,ACF_CODE
        ,FLAG_AL -- AR : ADDITIONAL ASSET / LIAB FLAG
        ,N_ACCRU_NOCF -- FROM NO COST FEE ECF
        ,N_UNAMORT_NOCF
        ,N_UNAMORT_PREV_NOCF
        )
    SELECT /*+ PARALLEL(12) */ V_CURRDATE AS DOWNLOAD_DATE
        ,--M.DOWNLOAD_DATE,
        M.FACILITY_NUMBER
        ,M.CUSTOMER_NUMBER
        ,M.DATA_SOURCE
        ,CASE
            WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                THEN (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV)
            ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV), V_ROUND)
            END + A.N_COST_UNAMORT_AMT_PREV
        ,CASE
            WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                THEN (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV)
            ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV), V_ROUND)
            END + A.N_FEE_UNAMORT_AMT_PREV
        ,(C.N_COST_UNAMORT_AMT) - (
            CASE
                WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                    THEN (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV)
                ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV), V_ROUND)
                END
                 + A.N_COST_UNAMORT_AMT_PREV
            )
        ,(C.N_FEE_UNAMORT_AMT) - (
            CASE
                WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                    THEN (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV)
                ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV), V_ROUND)
                END + A.N_FEE_UNAMORT_AMT_PREV
            )
        ,CASE
            WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                THEN (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV)
            ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_COST_UNAMORT_AMT - A.N_COST_UNAMORT_AMT_PREV), V_ROUND)
            END - COALESCE(A.SW_ADJ_COST, 0)
        ,CASE
            WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                THEN (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV)
            ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * (A.N_FEE_UNAMORT_AMT - A.N_FEE_UNAMORT_AMT_PREV), V_ROUND)
            END - COALESCE(A.SW_ADJ_FEE, 0)
        ,A.N_COST_AMORT_AMT - COALESCE(A.SW_ADJ_COST, 0) AS ACCRUFULL_COST
        ,A.N_FEE_AMORT_AMT - COALESCE(A.SW_ADJ_FEE, 0) AS ACCRUFULL_FEE
        ,A.DOWNLOAD_DATE
        ,SYSTIMESTAMP
        ,'SP_ACCT_EIR_ACF_ACCRU 2'
        ,M.MASTERID
        ,M.ACCOUNT_NUMBER
        ,'N' DO_AMORT
        ,M.BRANCH_CODE
        ,'2' ACFCODE
        ,M.FLAG_AL -- ARI : USE FOR LOAN AND FUNDING
        ,CASE
            WHEN (V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 > 1
                THEN A.NOCF_AMORT_AMT
            ELSE ROUND((V_CURRDATE - A.PREV_PMT_DATE + 1) / A.I_DAYS2 * A.NOCF_AMORT_AMT, V_ROUND)
            END
        ,A.NOCF_UNAMORT_AMT
        ,A.NOCF_UNAMORT_AMT_PREV
    FROM IFRS_LBM_ACCT_EIR_ECF A
    JOIN (
        SELECT M.DATA_SOURCE
            ,M.BRANCH_CODE
            ,M.MASTERID
            ,M.ACCOUNT_NUMBER
            ,M.FACILITY_NUMBER
            ,M.CUSTOMER_NUMBER
            ,M.IAS_CLASS AS FLAG_AL
        FROM IFRS_IMA_AMORT_CURR M
        LEFT JOIN (SELECT DISTINCT DOWNLOAD_DATE,MASTERID
                    FROM IFRS_ACCT_CLOSED
                    WHERE DOWNLOAD_DATE = V_CURRDATE
                    ) D
        ON M.DOWNLOAD_DATE = D.DOWNLOAD_DATE
        AND M.MASTERID = D.MASTERID
        WHERE M.DOWNLOAD_DATE = V_CURRDATE
        AND D.MASTERID IS NULL
        ) M ON A.MASTERID = M.MASTERID
    JOIN IFRS_LBM_ACCT_EIR_ECF C ON C.AMORTSTOPDATE IS NULL
        AND C.MASTERID = A.MASTERID
        AND C.PMT_DATE = C.PREV_PMT_DATE
    WHERE A.PMT_DATE > V_CURRDATE
        AND A.PREV_PMT_DATE <= V_CURRDATE
        AND A.PMT_DATE <> A.PREV_PMT_DATE
        AND A.AMORTSTOPDATE IS NULL;
    COMMIT;

    /* REMARKS.. TUNNING SCRIPT 20160602
        FROM IFRS_IMA_AMORT_CURR M
             JOIN IFRS_LBM_ACCT_EIR_ECF A
                ON     A.AMORTSTOPDATE IS NULL
                   AND A.MASTERID = M.MASTERID
                   AND V_CURRDATE < A.PMT_DATE
                   AND V_CURRDATE >= A.PREV_PMT_DATE
                   AND A.PMT_DATE <> A.PREV_PMT_DATE
             JOIN IFRS_LBM_ACCT_EIR_ECF C
                ON     C.AMORTSTOPDATE IS NULL
                   AND C.MASTERID = A.MASTERID
                   AND C.PMT_DATE = C.PREV_PMT_DATE
       WHERE                                               --DONT DO IF CLOSED
            M.MASTERID NOT IN (SELECT MASTERID
                                 FROM IFRS_ACCT_CLOSED
                                WHERE DOWNLOAD_DATE = V_CURRDATE)
        END REMARKS.. TUNNING SCRIPT 20160602*/
    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','ACF INSERTED');

    COMMIT;

    -- GET SL_ACF MAX(ID) TO PROCESS
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_P1';

    INSERT /*+ PARALLEL(12) */ INTO TMP_P1 (ID)
    SELECT /*+ PARALLEL(12) */ MAX(ID) AS ID
    FROM IFRS_LBM_ACCT_EIR_ACF
    WHERE DOWNLOAD_DATE = V_CURRDATE
        AND DO_AMORT = 'N'
    GROUP BY MASTERID;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','P1');

    COMMIT;

    --FEE 1
    EXECUTE IMMEDIATE'TRUNCATE TABLE TMP_T1';

    INSERT /*+ PARALLEL(12) */ INTO TMP_T1 (
        SUM_AMT
        ,DOWNLOAD_DATE
        ,FACNO
        ,CIFNO
        ,DATASOURCE
        ,ACCTNO
        ,MASTERID
        )
    SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT
        ,A.DOWNLOAD_DATE
        ,A.FACNO
        ,A.CIFNO
        ,A.DATASOURCE
        ,A.ACCTNO
        ,A.MASTERID
    FROM (
        SELECT CASE
                WHEN A.FLAG_REVERSE = 'Y'
                    THEN - 1 * A.AMOUNT
                ELSE A.AMOUNT
                END AS N_AMOUNT
            ,A.ECFDATE DOWNLOAD_DATE
            ,A.FACNO
            ,A.CIFNO
            ,A.DATASOURCE
            ,A.ACCTNO
            ,A.MASTERID
        FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
        WHERE A.FLAG_CF = 'F' AND A.STATUS = 'ACT'
        ) A
    GROUP BY A.DOWNLOAD_DATE
        ,A.FACNO
        ,A.CIFNO
        ,A.DATASOURCE
        ,A.ACCTNO
        ,A.MASTERID;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','T1 FEE');
    COMMIT;

    --PREPARE INDEX
    --EXECUTE IMMEDIATE 'DROP INDEX PSAK_EIR_COST_FEE_ECF_IDX1';
    --EXECUTE IMMEDIATE 'DROP INDEX PSAK_EIR_ACF_IDX1';
    --EXECUTE IMMEDIATE 'DROP INDEX TMP_T1_IDX1';
    --EXECUTE IMMEDIATE 'CREATE INDEX PSAK_EIR_COST_FEE_ECF_IDX1 ON IFRS_LBM_ACCT_EIR_COST_FEE_ECF(MASTERID,ECFDATE,FLAG_CF)';
    --EXECUTE IMMEDIATE 'CREATE INDEX PSAK_EIR_ACF_IDX1 ON IFRS_LBM_ACCT_EIR_ACF(MASTERID,ECFDATE)';
    --EXECUTE IMMEDIATE 'CREATE INDEX TMP_T1_IDX1 ON TMP_T1(MASTERID,DOWNLOAD_DATE)';
    -- UPDATE SUM_AMT

    MERGE INTO IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
    USING TMP_T1 B
    ON ( B.MASTERID = A.MASTERID
        AND B.DOWNLOAD_DATE = A.ECFDATE
        AND A.FLAG_CF = 'F'
       )
    WHEN MATCHED THEN
    UPDATE
    SET SUM_AMT = B.SUM_AMT;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','INSERT FEE');

    COMMIT;

    -- FEE 1
    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_CF_PREV (
        FACNO
        ,CIFNO
        ,DOWNLOAD_DATE
        ,ECFDATE
        ,DATASOURCE
        ,PRDCODE
        ,TRXCODE
        ,CCY
        ,AMOUNT
        ,STATUS
        ,CREATEDDATE
        ,ACCTNO
        ,MASTERID
        ,FLAG_CF
        ,FLAG_REVERSE
        ,BRCODE
        ,SRCPROCESS
        ,METHOD
        ,CREATEDBY
        ,SEQ
        ,AMOUNT_ORG
        ,ORG_CCY
        ,ORG_CCY_EXRATE
        ,PRDTYPE
        ,CF_ID
        )
    SELECT /*+ PARALLEL(12) */ A.FACNO
        ,A.CIFNO
        ,A.DOWNLOAD_DATE
        ,A.ECFDATE
        ,A.DATASOURCE
        ,B.PRDCODE
        ,B.TRXCODE
        ,B.CCY
        ,ROUND(B.AMOUNT / B.SUM_AMT * A.N_UNAMORT_FEE, V_ROUND) AS N_AMOUNT
        ,B.STATUS
        ,SYSTIMESTAMP
        ,A.ACCTNO
        ,A.MASTERID
        ,B.FLAG_CF
        ,B.FLAG_REVERSE
        ,B.BRCODE
        ,B.SRCPROCESS
        ,'EIR'
        ,'EIRACF02'
        ,'2'
        ,B.AMOUNT_ORG
        ,B.ORG_CCY
        ,B.ORG_CCY_EXRATE
        ,B.PRDTYPE
        ,B.CF_ID
    FROM IFRS_LBM_ACCT_EIR_ACF A
    --TUNNING SCRIPT 20160723
    JOIN TMP_P1 C ON A.ID = C.ID
    --TUNNING SCRIPT 20160723
    JOIN IFRS_LBM_ACCT_EIR_COST_FEE_ECF B ON B.ECFDATE = A.ECFDATE
        AND A.MASTERID = B.MASTERID
        AND B.FLAG_CF = 'F' AND B.STATUS = 'ACT'
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
        AND (
            (A.N_UNAMORT_FEE < 0 AND A.FLAG_AL = 'A')
            OR (A.N_UNAMORT_FEE > 0 AND A.FLAG_AL = 'L')
            );
    COMMIT;

    --REMARKS 20160723
    --AND A.ID IN (SELECT ID FROM TMP_P1)
    --REMARKS 20160723
    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','FEE PREV');

    --COST 1
    EXECUTE IMMEDIATE'TRUNCATE TABLE TMP_T2';

    INSERT /*+ PARALLEL(12) */ INTO TMP_T2 (
        SUM_AMT
        ,DOWNLOAD_DATE
        ,FACNO
        ,CIFNO
        ,DATASOURCE
        ,ACCTNO
        ,MASTERID
        )
    SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT
        ,A.DOWNLOAD_DATE
        ,A.FACNO
        ,A.CIFNO
        ,A.DATASOURCE
        ,A.ACCTNO
        ,A.MASTERID
    FROM (
        SELECT CASE
                WHEN A.FLAG_REVERSE = 'Y'
                    THEN - 1 * A.AMOUNT
                ELSE A.AMOUNT
                END AS N_AMOUNT
            ,A.ECFDATE DOWNLOAD_DATE
            ,A.FACNO
            ,A.CIFNO
            ,A.DATASOURCE
            ,A.ACCTNO
            ,A.MASTERID
        FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
        WHERE A.FLAG_CF = 'C' AND A.STATUS = 'ACT'
        ) A
    GROUP BY A.DOWNLOAD_DATE
        ,A.FACNO
        ,A.CIFNO
        ,A.DATASOURCE
        ,A.ACCTNO
        ,A.MASTERID;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','T2 COST');

    COMMIT;

    --EXECUTE IMMEDIATE 'DROP INDEX TMP_T2_IDX1';
    --EXECUTE IMMEDIATE 'CREATE INDEX TMP_T2_IDX1 ON TMP_T2(MASTERID,DOWNLOAD_DATE)';
    -- UPDATE SUM_AMT
    MERGE INTO IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
    USING TMP_T2 B
    ON (B.MASTERID = A.MASTERID
        AND B.DOWNLOAD_DATE = A.ECFDATE
        AND A.FLAG_CF = 'C'
       )
    WHEN MATCHED THEN
    UPDATE
    SET SUM_AMT = B.SUM_AMT;

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_EIR_CF_PREV (
        FACNO
        ,CIFNO
        ,DOWNLOAD_DATE
        ,ECFDATE
        ,DATASOURCE
        ,PRDCODE
        ,TRXCODE
        ,CCY
        ,AMOUNT
        ,STATUS
        ,CREATEDDATE
        ,ACCTNO
        ,MASTERID
        ,FLAG_CF
        ,FLAG_REVERSE
        ,BRCODE
        ,SRCPROCESS
        ,METHOD
        ,CREATEDBY
        ,SEQ
        ,AMOUNT_ORG
        ,ORG_CCY
        ,ORG_CCY_EXRATE
        ,PRDTYPE
        ,CF_ID
        )
    SELECT /*+ PARALLEL(12) */ A.FACNO
        ,A.CIFNO
        ,A.DOWNLOAD_DATE
        ,A.ECFDATE
        ,A.DATASOURCE
        ,B.PRDCODE
        ,B.TRXCODE
        ,B.CCY
        ,ROUND(B.AMOUNT / B.SUM_AMT * A.N_UNAMORT_COST, V_ROUND) AS N_AMOUNT
        ,B.STATUS
        ,SYSTIMESTAMP
        ,A.ACCTNO
        ,A.MASTERID
        ,B.FLAG_CF
        ,B.FLAG_REVERSE
        ,B.BRCODE
        ,B.SRCPROCESS
        ,'EIR'
        ,'EIRACF02'
        ,'2'
        ,B.AMOUNT_ORG
        ,B.ORG_CCY
        ,B.ORG_CCY_EXRATE
        ,B.PRDTYPE
        ,B.CF_ID
    FROM IFRS_LBM_ACCT_EIR_ACF A
    --TUNNING SCRIPT 20160723
    JOIN TMP_P1 C ON A.ID = C.ID
    --TUNNING SCRIPT 20160723
    JOIN IFRS_LBM_ACCT_EIR_COST_FEE_ECF B ON B.ECFDATE = A.ECFDATE
        AND A.MASTERID = B.MASTERID
        AND B.FLAG_CF = 'C' AND B.STATUS = 'ACT'
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
        AND (
            (A.N_UNAMORT_COST > 0 AND A.FLAG_AL = 'A')
            OR (A.N_UNAMORT_COST < 0 AND A.FLAG_AL = 'L')
            );
    COMMIT;

    --REMARKS 20160723
    /*AND A.ID IN (SELECT ID FROM TMP_P1)*/
    --REMARKS 20160723
    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','COST PREV');
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_ACF_ACRU','');

    COMMIT;
END;