CREATE OR REPLACE PROCEDURE SP_IFRS_RESET_AMT_PRC
IS
    V_CURRDATE DATE ;
    V_PREVDATE DATE;
BEGIN

    SELECT  CURRDATE ,
            PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT ;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,
              SYSTIMESTAMP ,
              'Delete ECF' ,
              'SP_IFRS_RESET_AMT_PRC' ,
              ''
              );
	COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_SL_ECF
    WHERE   DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_EIR_ECF
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
	COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,
              SYSTIMESTAMP ,
              'Update ECF' ,
              'SP_IFRS_RESET_AMT_PRC' ,
              ''
            );
    COMMIT;

    UPDATE  /*+ PARALLEL(12) */ IFRS_ACCT_SL_ECF
    SET     AMORTSTOPDATE = NULL ,
            AMORTSTOPREASON = NULL
    WHERE   AMORTSTOPDATE = V_CURRDATE;
    COMMIT;

    UPDATE  /*+ PARALLEL(12) */ IFRS_ACCT_EIR_ECF
    SET     AMORTSTOPDATE = NULL ,
            AMORTSTOPMSG = NULL
    WHERE   AMORTSTOPDATE = V_CURRDATE;
	COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,
              SYSTIMESTAMP ,
              'Delete accru prev' ,
              'SP_IFRS_RESET_AMT_PRC' ,
              ''
            );
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_SL_ACCRU_PREV
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_EIR_ACCRU_PREV
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
	COMMIT;

    INSERT  INTO IFRS_AMORT_LOG
            ( DOWNLOAD_DATE ,
              DTM ,
              OPS ,
              PROCNAME ,
              REMARK
            )
    VALUES  ( V_CURRDATE ,
              SYSTIMESTAMP ,
              'Delete acf' ,
              'SP_IFRS_RESET_AMT_PRC' ,
              ''
            );
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_SL_ACF
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_EIR_ACF
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,
              SYSTIMESTAMP ,
              'Delete Cost Fee Ecf' ,
              'SP_IFRS_RESET_AMT_PRC' ,
              ''
            );
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_SL_COST_FEE_ECF
    WHERE   ECFDATE >= V_CURRDATE;
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_EIR_COST_FEE_ECF
    WHERE   ECFDATE >= V_CURRDATE;
    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'Delete Cost Fee Prev' ,'SP_IFRS_RESET_AMT_PRC' ,'');
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_SL_COST_FEE_PREV
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_EIR_COST_FEE_PREV
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'Update accru Prev' ,'SP_IFRS_RESET_AMT_PRC' ,'');
    COMMIT;

   --reset acru table sl
    UPDATE  /*+ PARALLEL(12) */ IFRS_ACCT_SL_ACCRU_PREV
    SET     STATUS = 'ACT'
    WHERE   STATUS = TO_CHAR (V_CURRDATE, 'DD-MM-YYYY')
            AND STATUS != 'ACT';
    COMMIT;

   --reset acru table eir
    UPDATE  /*+ PARALLEL(12) */ IFRS_ACCT_EIR_ACCRU_PREV
    SET     STATUS = 'ACT'
    WHERE   STATUS = TO_CHAR (V_CURRDATE, 'DD-MM-YYYY')
            AND STATUS != 'ACT';
    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'Delete acct cost fee' ,'SP_IFRS_RESET_AMT_PRC' ,'');
    COMMIT;

   -- reset cost fee from SL to EIR process
    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_COST_FEE
    WHERE   DOWNLOAD_DATE = V_CURRDATE
            AND SRCPROCESS = 'SL_TO_EIR';
    COMMIT;

   -- Delete IFRS_ACCT_JOURNAL_INTM
    DELETE  /*+ PARALLEL(12) */ FROM IFRS_ACCT_JOURNAL_INTM
    WHERE   DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_RESET_AMT_PRC' ,'') ;

    COMMIT;
END;