CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_UPD_UNMRT
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;


BEGIN
    SELECT MAX(CURRDATE)
      , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LBM_ACCT_EIR_UPD_UNMRT','');

    COMMIT;

    --GET ACTIVE ECF
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_B1';

    INSERT /*+ PARALLEL(12) */ INTO TMP_B1 (MASTERID)
    SELECT /*+ PARALLEL(12) */ DISTINCT MASTERID
    FROM IFRS_LBM_ACCT_EIR_ECF
    WHERE AMORTSTOPDATE IS NULL;

    COMMIT;

    -- CLEAN UP ALREADY DONE ON SP_PSAK_ACCT_SL_UPD_UNAMORT
    --GET LAST ACF ID
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_P1';

    INSERT /*+ PARALLEL(12) */ INTO TMP_P1 (ID)
    SELECT /*+ PARALLEL(12) */ MAX(ID) ID
    FROM IFRS_LBM_ACCT_EIR_ACF
    WHERE DOWNLOAD_DATE = V_CURRDATE
      AND MASTERID IN (SELECT MASTERID FROM TMP_B1)
    GROUP BY MASTERID;

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_U1';

    INSERT /*+ PARALLEL(12) */ INTO TMP_U1 (
      DOWNLOAD_DATE
      ,MASTERID
      ,N_UNAMORT_FEE
      ,N_UNAMORT_COST
      ,ECFDATE
      ,ACCTNO
      ,ENDAMORTDATE
      )
    SELECT /*+ PARALLEL(12) */ B.DOWNLOAD_DATE
      ,B.MASTERID
      ,B.N_UNAMORT_FEE
      ,B.N_UNAMORT_COST
      ,B.ECFDATE
      ,B.ACCTNO
      ,E.ENDAMORTDATE
    FROM IFRS_LBM_ACCT_EIR_ACF B
    JOIN TMP_P1 C ON C.ID = B.ID
    LEFT JOIN IFRS_LBM_ACCT_EIR_ECF E ON E.MASTERID = B.MASTERID
      AND E.PREV_PMT_DATE = E.PMT_DATE
      AND E.DOWNLOAD_DATE = B.ECFDATE;

    COMMIT;

    -- UPDATE TO MASTER ACCT --SELECT * FROM IFRS_ACCT_EIR_ACF
    MERGE INTO IFRS_IMA_AMORT_CURR A
    USING TMP_U1 X
    ON (X.MASTERID = A.MASTERID
      AND X.ACCTNO = A.ACCOUNT_NUMBER
       )
    WHEN MATCHED THEN
    UPDATE
    SET UNAMORT_BENEFIT = X.N_UNAMORT_FEE;

    COMMIT;



    MERGE INTO IFRS_MASTER_ACCOUNT A
    USING IFRS_IMA_AMORT_CURR B
    ON (A.MASTERID = B.MASTERID
      AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
      AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
      AND B.AMORT_TYPE = 'EIR'
       )
    WHEN MATCHED THEN
    UPDATE
    SET UNAMORT_BENEFIT = B.UNAMORT_BENEFIT;

    COMMIT;

    -- UPDATE EIR TO PMA 20151124 BY RIS
    MERGE INTO IFRS_MASTER_ACCOUNT A
    USING (SELECT MASTERID
            ,MAX(N_EFF_INT_RATE) N_EFF_INT_RATE
          FROM IFRS_LBM_ACCT_EIR_ECF
          WHERE AMORTSTOPDATE IS NULL
            AND PREV_PMT_DATE = PMT_DATE
          GROUP BY MASTERID
          ) B
    ON (A.MASTERID = B.MASTERID
      AND A.DOWNLOAD_DATE = V_CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET EIR = B.N_EFF_INT_RATE;commit;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_UPD_UNMRT','');

    COMMIT;
END;