CREATE OR REPLACE EDITIONABLE PROCEDURE "PSAK413"."SP_ADAM_CHECK"
AS
BEGIN
	NULL;
/*
 
INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_MULTIJASA
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2025'
,IMI.MASTERID 
,PAYM.SCHD_DT AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.ANGS_POKOK,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.ANGS_MARGIN,'.','')) AS INTR 
,rank() over (partition by PAYM.LOAN_NO order by TO_DATE(PAYM.SCHD_DT, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.ANGSURANSCHEDULE_NTT_REQ PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'MULTIJASA'||PAYM.LOAN_NO = IMI.MASTER_ACCOUNT_CODE 

INSERT INTO PSAK413.IFRS_PAYM_SCHD_ALL
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
,SOURCE_PROCESS
)
SELECT 
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
,'MULTIJASA' AS SOURCE_PROCESS 
FROM IFRS_PAYM_SCHD_ALL_MULTIJASA 
 
*/


/*

INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_JFAST
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2025'
,IMI.MASTERID 
,TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.REPAY_PRIN_AMT,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.REPAY_INTR_AMT,'.','')) AS INTR 
,rank() over (partition by PAYM.CONT_CONTRACT_NO order by TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.KARTU_ANGSURAN_ALL_2025 PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'JFAST'||PAYM.CONT_CONTRACT_NO = IMI.MASTER_ACCOUNT_CODE 


INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_JFAST
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2024'
,IMI.MASTERID 
,TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.REPAY_PRIN_AMT,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.REPAY_INTR_AMT,'.','')) AS INTR 
,rank() over (partition by PAYM.CONT_CONTRACT_NO order by TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.KARTU_ANGSURAN_ALL_2024 PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'JFAST'||PAYM.CONT_CONTRACT_NO = IMI.MASTER_ACCOUNT_CODE 


INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_JFAST
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2023'
,IMI.MASTERID 
,TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.REPAY_PRIN_AMT,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.REPAY_INTR_AMT,'.','')) AS INTR 
,rank() over (partition by PAYM.CONT_CONTRACT_NO order by TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.KARTU_ANGSURAN_ALL_2023 PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'JFAST'||PAYM.CONT_CONTRACT_NO = IMI.MASTER_ACCOUNT_CODE 



INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_JFAST
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2022'
,IMI.MASTERID 
,TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.REPAY_PRIN_AMT,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.REPAY_INTR_AMT,'.','')) AS INTR 
,rank() over (partition by PAYM.CONT_CONTRACT_NO order by TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.KARTU_ANGSURAN_ALL_2022 PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'JFAST'||PAYM.CONT_CONTRACT_NO = IMI.MASTER_ACCOUNT_CODE 


INSERT INTO PSAK.IFRS_PAYM_SCHD_ALL_JFAST
(
 DOWNLOAD_DATE
,MASTERID
,PMTDATE
,PRINCIPAL
,MARGIN
,COUNTER
)
SELECT 
 '31 Dec 2021'
,IMI.MASTERID 
,TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') AS PMT_DATE
,TO_NUMBER(REPLACE(PAYM.REPAY_PRIN_AMT,'.','')) AS PRIN
,TO_NUMBER(REPLACE(PAYM.REPAY_INTR_AMT,'.','')) AS INTR 
,rank() over (partition by PAYM.CONT_CONTRACT_NO order by TO_DATE(PAYM.DUE_DATE, 'DD-MM-YYYY') ) - 1 counter
FROM PSAK.KARTU_ANGSURAN_ALL_2021 PAYM
JOIN
PSAK413.IFRS_MASTER_ID IMI
ON
'JFAST'||PAYM.CONT_CONTRACT_NO = IMI.MASTER_ACCOUNT_CODE  
   
*/

/*
 SELECT * FROM psak.HCWO_LBUT hl 
WHERE "nomorRekening" = '40000000001121'
ORDER BY "periodeData" ASC 

SELECT DOWNLOAD_DATE, MASTERID, MASTER_ACCOUNT_CODE, CUSTOMER_NUMBER, OUTSTANDING  FROM psak413.IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE CUSTOMER_NUMBER = '40000000001121'
ORDER BY DOWNLOAD_DATE ASC 


SELECT * FROM psak413.IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE imam.ACCOUNT_NUMBER IN 
(
SELECT "nomorRekening" FROM psak.HCWO_LBUT hl 
)

SELECT download_Date
FROM "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC"

SELECT * FROM psak.HCWO_LBUT hl 

INSERT INTO "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC"
(
	download_date
	,masterid
	,account_number
	,master_account_code
	,currency
	,outstanding
	,product_code
	,customer_name
	,account_status
	,product_type
	,segment
	,sub_segment
	,group_segment
)
SELECT 
	 TO_DATE(hl."periodeData", 'YYYY-MM-DD')   AS download_date
	,imi.MASTERID 
	,hl."nomorRekening" AS account_number
	,'HC_'||hl."nomorRekening" AS master_Account_code
	,hl."jenisValuta" AS currency
	,hl."jumlah" AS outstanding
	,hl."LoanTypeCode" AS product_code
	,hl."NamaNasabah" AS customer_name
	,'W'AS ACCOUNT_STATUS
	,'QARDH' AS PRODUCT_TYPE
	,'HASANAH_CARD_PIUTANG' AS SEGMENT
	,'HASANAH_CARD_QARDH' AS SUB_SEGMENT
	,'HASANAH_CARD' AS GROUP_sEGMENT
FROM psak.HCWO_LBUT hl 
JOIN
psak413.IFRS_MASTER_ID imi 
ON
'HC_'||hl."nomorRekening" = imi.MASTER_ACCOUNT_CODE 



SELECT * FROM PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY  A
JOIN "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC" B
ON
A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
AND 
A.MASTERID = B.MASTERID
WHERE A.MASTERID NOT IN 
(
 2438348
,2450943
,4668046
,4543067
,4664233
,2959972
,3802278
)


SELECT COUNT(1) FROM PSAK.HCWO_LBUT hl 
SELECT COUNT(1) FROM PSAK.X_IFRS_MASTER_ACCOUNT_WO_HC


SELECT * FROM "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC"
WHERE ACCOUNT_NUMBER IN 
(
'41009404392889'
--,'43009796721124'
--,'41000088409465'
--,'41000051013986'
--,'41000060251441'
--,'41000087469798'
--,'51000088408595'
)
ORDER BY DOWNLOAD_DATE ASC

SELECT COUNT(1) FROM PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY
WHERE CREATEDBY = 'PSAK.X_IFRS_MASTER_ACCOUNT_WO_HC'

INSERT INTO PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY 
(
     download_date
	,masterid
	,DATA_SOURCE
	,account_number
	,master_account_code
	,currency
	,outstanding
	,product_code
	,customer_name
	,account_status
	,product_type
	,segment
	,sub_segment
	,group_segment
	,createdby
)
SELECT	
    download_date
	,masterid
	,'HC'
	,account_number
	,master_account_code
	,currency
	,outstanding
	,product_code
	,customer_name
	,account_status
	,product_type
	,segment
	,sub_segment
	,group_segment
	,'PSAK.X_IFRS_MASTER_ACCOUNT_WO_HC'
FROM "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC" 
WHERE MASTERID NOT IN 
(
 2438348
,2450943
,4668046
,4543067
,4664233
,2959972
,3802278
)


INSERT INTO PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY_EXT 
(
	DOWNLOAD_DATE
	,MASTERID 
)
SELECT	
    download_date
	,masterid
FROM "PSAK"."X_IFRS_MASTER_ACCOUNT_WO_HC" 
WHERE DOWNLOAD_DATE <> '31 DEC 2024


 
 * */
/*
MERGE INTO 	IFRS_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT  
		pmam.DOWNLOAD_DATE,
		pmam.MASTER_ACCOUNT_CODE 
	FROM IFRS_MASTER_ACCOUNT_MONTHLY pmam, 
		 IFRS_PATCH_LOAN_START_DUE_NULL lpda
	WHERE pmam.DOWNLOAD_DATE = lpda.DOWNLOAD_DATE
	AND pmam.MASTER_ACCOUNT_CODE = lpda.MASTER_ACCOUNT_CODE
	AND pmam.download_date = '31 JAN 2021'
) dat 
ON 
(
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE 
	AND 
	a.MASTER_ACCOUNT_CODE = dat.MASTER_ACCOUNT_CODE
)
WHEN MATCHED THEN UPDATE 
		SET 
			LOAN_DUE_DATE = dat.DOWNLOAD_DATE,
			LOAN_START_DATE = '31 JAN 2019',
		    UPDATEDBY = 'Patch_loan_start_due_date_null';
*/



/*
  DECLARE
  v_start_date DATE := DATE '2020-01-31';  
  v_end_date   DATE := DATE '2025-12-31';  
 
BEGIN 

  WHILE v_start_date <= v_end_date LOOP
	  
	
INSERT INTO PSAK413.IFRS_DEFAULT
(
     DOWNLOAD_DATE
    ,MASTERID
    ,RULE_ID
    ,ACCOUNT_NUMBER
    ,CUSTOMER_NUMBER
    ,OS_AT_DEFAULT
    ,EQV_AT_DEFAULT
    ,EIR_AT_DEFAULT
    ,CCY_AT_DEFAULT
    ,CREATED_DATE 
    ,PLAFOND_AT_DEFAULT
    ,EQV_PLAFOND_AT_DEFAULT
    ,FACILITY_NUMBER
) 
SELECT DOWNLOAD_DATE , MASTERID , 1,ACCOUNT_NUMBER , CUSTOMER_NUMBER , OUTSTANDING , OUTSTANDING  * NVL(EXCHANGE_RATE,1),
NVL(EIR, MARGIN_RATE), CURRENCY , SYSDATE, PLAFOND , PLAFOND * NVL(EXCHANGE_RATE,1), FACILITY_NUMBER 
FROM IFRS_MASTER_ACCOUNT_MONTHLY   
WHERE ( segment not in ('GADAI_EMAS_PIUTANG') and ( day_past_due > '90' OR  ACCOUNT_STATUS  = 'W'))
AND DOWNLOAD_DATE  = v_start_date
UNION 
SELECT DOWNLOAD_DATE , MASTERID , 2,ACCOUNT_NUMBER , CUSTOMER_NUMBER , OUTSTANDING , OUTSTANDING  * NVL(EXCHANGE_RATE,1),
NVL(EIR, MARGIN_RATE), CURRENCY , SYSDATE, PLAFOND , PLAFOND * NVL(EXCHANGE_RATE,1), FACILITY_NUMBER 
FROM IFRS_MASTER_ACCOUNT_MONTHLY   
WHERE ( segment in ('GADAI_EMAS_PIUTANG') AND ( day_past_due > '0' OR  ACCOUNT_STATUS  = 'W' OR restructure_flag = '1'))
AND DOWNLOAD_DATE  = v_start_date
 
;

COMMIT ; 

UPDATE X_IFRS_PRCDATE  SET CURRDATE  =  v_start_date ; COMMIT ; 
    -- tambah 1 bulan
DBMS_OUTPUT.PUT_LINE('Tanggal: ' || TO_CHAR(v_start_date, 'YYYY-MM-DD'));
    v_start_date := LAST_DAY(ADD_MONTHS(v_start_date, 1));
  END LOOP;
END;

*/

/* 
SELECT DOWNLOAD_DATE, SEGMENT, SUB_SEGMENT, GROUP_SEGMENT, DATA_SOURCE, PRODUCT_CODE, PRODUCT_TYPE, PRODUCT_GROUP  FROM PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY 
WHERE SEGMENT = 'JFAST_DVC_PIUTANG'

SELECT PREV_DATE ,CURR_DATE ,BUCKET_FROM ,BUCKET_TO ,CALC_AMOUNT  FROM IFRS_PD_MIGRATION_DETAIL ipmd 
WHERE PD_RULE_ID ='2'
ORDER BY PREV_DATE 

SELECT * FROM IFRS_PD_RULES_CONFIG iprc 

SELECT EFF_DATE ,TOT_DEFAULT ,NON_DEFAULT ,ODR  FROM IFRS_PD_MAA_ODR ipmo 
WHERE PD_RULE_ID ='2'
ORDER BY EFF_DATE 

SELECT DOWNLOAD_DATE ,CUSTOMER_NUMBER,GLOBAL_CUSTOMER_NUMBER ,ACCOUNT_NUMBER ,SEGMENT ,DPD_CIF ,DAY_PAST_DUE ,DAY_PAST_DUE_ORI ,OUTSTANDING ,EXCHANGE_RATE ,
BUCKET_ID
FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE SEGMENT ='KORPORASI_PIUTANG' AND ACCOUNT_STATUS ='A'
AND DOWNLOAD_DATE ='30 APR 2025'

SELECT DOWNLOAD_DATE ,CUSTOMER_NUMBER,GLOBAL_CUSTOMER_NUMBER ,ACCOUNT_NUMBER ,SEGMENT ,DPD_CIF ,DAY_PAST_DUE ,DAY_PAST_DUE_ORI ,OUTSTANDING ,EXCHANGE_RATE ,
BUCKET_ID , RESTRUCTURE_FLAG , ACCOUNT_STATUS_ORI 
FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE ACCOUNT_NUMBER ='LD2116343050'
ORDER BY DOWNLOAD_DATE 
AND DOWNLOAD_DATE ='30 APR 2024'

SELECT * FROM 
; 
SELECT * FROM NTT_PSAK413_IMPAIRMENT."Segmentation" ; A WHERE A.segment_type = 'LIFETIME';
SELECT * FROM NTT_PSAK413_IMPAIRMENT."LifetimeConfiguration";
SELECT * FROM NTT_PSAK413_IMPAIRMENT."Lgd

SELECT * FROM NTT_PSAK413_IMPAIRMENT."WorkoutPeriodConfiguration";

SELECT "lgd_name", "is_use_workout_period_config", "recovery_amount", "selected_workout_period_config"
FROM NTT_PSAK413_IMPAIRMENT."LgdConfiguration";

SELECT * FROM NTT_PSAK413_IMPAIRMENT."Segmentation"
WHERE "segment_type" IS NULL
order by "segment_name"

SELECT "pkid", "syscode_lgd_config", "lgd_name", "lgd_method", 
"calculation_method", "is_active", "created_by", "created_date", "updated_by",
 "updated_date", "created_host", "updated_host", "segment_code", "default_criteria_code", 
"is_deleted", "deleted_by", "deleted_date", "deleted_host", "designated_workout_period", "is_use_workout_period_config", "recovery_amount", "selected_workout_period_config", "start_historical_date", "historical_data", "workout_period" FROM NTT_PSAK413_IMPAIRMENT."LgdConfiguration";




--DY--

   SELECT * FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
   
   SELECT * FROM IFRS_SEGMENTATION_MAPPING ism ; 
  
 SELECT * FROM IFRS_PD_MIGRATION_DETAIL ipmd
 WHERE IPMD.PD_RULE_ID = 2;
 
 SELECT pkid,PREV_DATE, CURR_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT, OUTSTANDING
 FROM IFRS_PD_MIGRATION_DETAIL ipmd WHERE ipmd.PD_RULE_ID = 2;

  
  SELECT * FROM IFRS_BUCKET_HEADER ibh ;
 SELECT * FROM IFRS_PD_RULES_CONFIG iprc  WHERE iprc.pkid='8' ;

  SELECT * FROM  IFRS_PD_SCENARIO_DATA ipsd  ;

 
  SELECT pkid,BASE_DATE ,EFF_DATE ,PD_RULE_ID ,BUCKET_GROUP ,BUCKET_FROM ,BUCKET_TO ,CALC_AMOUNT  
  FROM  IFRS_PD_MAA_ENR ipme  WHERE ipme.PD_RULE_ID = 2 ORDER BY BASE_DATE ,BUCKET_FROM , BUCKET_TO ;
 
 SELECT PKID, EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE, CREATEDBY, CREATEDDATE, CREATEDHOST, 
UPDATEDBY, UPDATEDDATE, UPDATEDHOST FROM IFRS_PD_MAA_FLOWRATE;

  SELECT * FROM IFRS_PD_MAA_FLOWRATE_SUM ipmfs ;
 
 
 
  SELECT * FROM IFRS_PD_MIGRATION_DETAIL;\
   SELECT  * FROM IFRS_MASTER_ACCOUNT_MONTHLY imam ;
  
 SELECT DISTINCT GROUP_SEGMENT ,SEGMENT ,SUB_SEGMENT FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
 ORDER BY GROUP_SEGMENT ;
  
SELECT "pkid", "syscode_segmentation_lv1", "segment_name_lv1", "syscode_segmentation_lv2", "segment_name_lv2", "syscode_segmentation_lv3", "segment_name_lv3", "syscode_segmentation_lv4", "segment_name_lv4", "syscode_segmentation_lv5", "segment_name_lv5", "syscode_segmentation_lv6", "segment_name_lv6", "syscode_segmentation_lv7", "segment_name_lv7", "syscode_segmentation_lv8", "segment_name_lv8", "syscode_segmentation_lv9", "segment_name_lv9", "syscode_segmentation_lv10", "segment_name_lv10", "merge_sql_conditions", "created_by", "created_date", "created_host", "updated_by", "updated_date", "updated_host", "is_deleted", "deleted_by", "deleted_date", "deleted_host", "segment_type" FROM NTT_PSAK413_IMPAIRMENT."SegmentationMapping"
WHERE "segment_name_lv1"  LIKE '%PENSIUN%'
AND "segment_type" IS NULL 
 
 
 SELECT PREV_DATE , CURR_DATE ,PD_RULE_ID ,BUCKET_GROUP ,BUCKET_FROM ,BUCKET_TO, ROUND(  sum(CALC_AMOUNT),0),ROUND(SUM(OUTSTANDING),0)  
 FROM IFRS_PD_MIGRATION_DETAIL
WHERE PD_RULE_ID  = '8' AND PREV_DATE  BETWEEN '31 JAN 2020' AND '31 DEC 2026'
GROUP BY PREV_DATE , CURR_DATE ,PD_RULE_ID ,BUCKET_GROUP ,BUCKET_FROM ,BUCKET_TO;


SELECT PKID, BASE_DATE,EFF_DATE,  PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT 
FROM IFRS_PD_MAA_ENR
WHERE PD_RULE_ID  = '8' 
ORDER BY BASE_DATE ,BUCKET_FROM , BUCKET_TO ;

SELECT PKID, EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE
 FROM IFRS_PD_MAA_FLOWRATE WHERE PD_RULE_ID  = '8' 
ORDER BY BASE_DATE ,BUCKET_FROM , BUCKET_TO ;

SELECT EFF_DATE, PD_RULE_ID, TOT_DEFAULT, NON_DEFAULT, ODR FROM IFRS_PD_MAA_ODR
WHERE PD_RULE_ID  = '8' ORDER BY EFF_DATE ;

SELECT EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, FLOWRATE
 FROM IFRS_PD_MAA_FLOWRATE_SUM WHERE PD_RULE_ID  = '8' 
ORDER BY BASE_DATE ,BUCKET_FROM , BUCKET_TO ;

 SELECT * FROM IFRS_PD_MIGRATION_DETAIL;

 SELECT * FROM IFRS_PD_RULES_CONFIG iprc ;
  SELECT * FROM  PD_KUR_MIG_DTL_SUMM;

   SELECT * FROM  PD_MAA;
 
 
--COMMERECIAL 5
--GADAI_EMAS 8
 
 
 
 
 
--DY--   
  
*/

/*SELECT MIN(DOWNLOAD_DATE) MIN_DDATE, MASTERID, ACCOUNT_NUMBER, MASTER_ACCOUNT_CODE  FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE ACCOUNT_NUMBER IN 
(
SELECT old_account_number FROM psak.REKENING_PADANAN 
)
GROUP BY MASTERID, ACCOUNT_NUMBER, MASTER_ACCOUNT_CODE 
--NO DATA--

SELECT * FROM psak.REKENING_PADANAN 
WHERE OLD_ACCOUNT_NUMBER  = '1051153018'

SELECT * FROM IFRS_MASTER_ACCOUNT_MONTHLY
WHERE 
DOWNLOAD_DATE BETWEEN '31 JUL 2021' AND '30 SEP 2021'
AND
(
ACCOUNT_NUMBER = 'LD2116465677'
OR 
ACCOUNT_NUMBER = '1051153018'
)
ORDER BY DOWNLOAD_DATE */


/*
 * 
 * DECLARE
  v_start_date DATE := DATE '2020-02-29';  
  v_end_date   DATE := DATE '2020-02-29';  
 
BEGIN 

  WHILE v_start_date <= v_end_date LOOP
	  
	   EXECUTE IMMEDIATE 'TRUNCATE TABLE X_IMAHCDPD';
	   
	  INSERT INTO X_IMAHCDPD
	  SELECT DOWNLOAD_dATE, CUSTOMER_NUMBER, MAX(DAY_PAST_DUE) DPD_CIF
	  FROM IFRS_MASTER_ACCOUNT_MONTHLY A 
	  WHERE DOWNLOAD_DATE  = V_START_dATE
	  	AND ACCOUNT_STATUS  = 'A'
	  	AND DATA_SOURCE  = 'HC'
	  	GROUP BY DOWNLOAD_dATE, CUSTOMER_NUMBER ;
	   
	  UPDATE IFRS_MASTER_ACCOUNT_MONTHLY A SET 
	  A.DPD_CIF  = (SELECT DPD_CIF FROM X_IMAHCDPD X WHERE A.CUSTOMER_NUMBER  = X.CUSTOMER_NUMBER AND A.DOWNLOAD_DATE  = X.DOWNLOAD_DATE )
	  WHERE A.DOWNLOAD_DATE  = V_START_DATE
	  	AND A.ACCOUNT_STATUS  = 'A'
	  	AND A.DATA_SOURCE  = 'HC' ; 
	  	
	  
	   
COMMIT ; 
 

UPDATE X_IFRS_PRCDATE  SET CURRDATE  = v_start_date; 
COMMIT ; 
    -- tambah 1 bulan
DBMS_OUTPUT.PUT_LINE('Tanggal: ' || TO_CHAR(v_start_date, 'YYYY-MM-DD'));
    v_start_date := LAST_DAY(ADD_MONTHS(v_start_date, 1));
  END LOOP;
END;

--query check dpd_cif--
SELECT MASTERID, CUSTOMER_NUMBER, DAY_PAST_DUE_ORI, DAY_PAST_DUE, DPD_CIF  FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE DOWNLOAD_DATE = '31 AUG 2025'
AND DATA_SOURCE = 'HC'
AND ACCOUNT_STATUS = 'A'
AND EXISTS 
(
	SELECT 1 FROM IFRS_MASTER_ACCOUNT_MONTHLY x 
	WHERE 
		imam.DOWNLOAD_DATE = x.DOWNLOAD_DATE
	AND imam.DATA_SOURCE = x.DATA_SOURCE 
	AND imam.ACCOUNT_STATUS = x.ACCOUNT_STATUS 
	AND imam.CUSTOMER_NUMBER = x.customer_number
	AND x.DAY_PAST_DUE <> x.DPD_CIF 
)
ORDER BY imam.CUSTOMER_NUMBER 
--query check dpd_cif--

 * 
 */

/*
 * 
 CREATE TABLE X_IFRS_MASTER_ID_BACKUP
AS
SELECT * FROM IFRS_MASTER_ID


SELECT * FROM IFRS_MASTER_ID

WHERE MASTER_ACCOUNT_CODE 
IN
(
	SELECT MASTER_ACCOUNT_CODE FROM IFRS_MASTER_ACCOUNT_MONTHLY_HC_2020 WHERE MASTERID IS NULL 
)

SELECT * FROM FORM12_LSMK_BNIS_2006

/*
INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY_HC_2020
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,PRODUCT_TYPE 
	,PRODUCT_CODE 
	,BRANCH_CODE 
	,ACCOUNT_STATUS 
	,ACCOUNT_NUMBER 
	,CUSTOMER_NUMBER 
	,CUSTOMER_NAME 
	,CURRENCY 
	,EXCHANGE_RATE 
	,OUTSTANDING 
	,PLAFOND 
	,MARGIN_RATE 
	,EIR 
	,FAIR_VALUE_AMOUNT 
	,DAY_PAST_DUE 
	,DPD_CIF 
	,BI_COLLECTABILITY 
	,BI_COLLECT_CIF 
	,STAFF_LOAN_FLAG 
	,COLL_AMOUNT 
	,UNAMORT_FEE_AMT 
	,UNAMORT_COST_AMT 
	,MARGIN_TYPE 
	,DEFAULT_DATE 
	,LOAN_START_DATE 
	,LOAN_DUE_DATE 
	,DIVISION_CODE 
	,RESTRUCTURE_FLAG 
	,OUTSTANDING_PAST_DUE 
	,MARGIN_PAST_DUE 
)
SELECT 
	 TO_DATE("FicMisDate", 'YYYY-MM-DD')  AS DOWNLOAD_DATE
	,IMI.MASTERID
	,'HC_'||"NomorRekening"  AS MASTER_ACCOUNT_CODE
	,'HC' AS DATA_SOURCE
	,'QARDH' AS PRODUCT_TYPE 
	,"LoanTypeCode" AS PRODUCT_CODE 
	,"KodeCabang" AS BRANCH_CODE 
	,'A' AS ACCOUNT_STATUS 
	,"NomorRekening"  AS ACCOUNT_NUMBER 
	,"NomorNasabah"  AS CUSTOMER_NUMBER 
	,NULL AS CUSTOMER_NAME 
	,"JenisValuta" AS CURRENCY 
	,1 AS EXCHANGE_RATE 
	,"JumlahBulanLaporan"  AS OUTSTANDING 
	,NULL AS PLAFOND 
	,NULL AS MARGIN_RATE 
	,NULL AS EIR 
	,NULL AS FAIR_VALUE_AMOUNT 
	,"TunggakanHari"  AS DAY_PAST_DUE 
	,NULL AS DPD_CIF 
	,"Kualitas" AS BI_COLLECTABILITY 
	,"Kualitas"  AS BI_COLLECT_CIF 
	,NULL AS STAFF_LOAN_FLAG 
	,NULL AS COLL_AMOUNT 
	,NULL AS UNAMORT_FEE_AMT 
	,NULL AS UNAMORT_COST_AMT 
	,NULL AS MARGIN_TYPE 
	,NULL AS DEFAULT_DATE 
	,TO_DATE("JangkaWaktuMulai" , 'YYYY-MM-DD') AS LOAN_START_DATE 
	,TO_DATE("JangkaWaktuJatuhTempo" , 'YYYY-MM-DD') AS LOAN_DUE_DATE 
	,NULL AS DIVISION_CODE 
	,CASE WHEN "SifatPiutang"  IN ('1', '5') THEN 1 ELSE 0 END RESTRUCTURE_FLAG
	,"TunggakanPokok" AS OUTSTANDING_PAST_DUE
	,"TunggakanMargin" AS MARGIN_PAST_DUE
FROM 
FORM12_LSMK_BNIS_2006 pmam 
LEFT JOIN
IFRS_MASTER_ID IMI
ON
'HC_'||TRIM("NomorRekening") = IMI.MASTER_ACCOUNT_CODE;
*/

/*
CREATE TABLE PSAK413.PSAK_MASTER_ACCOUNT_DPD_ORI AS
SELECT DOWNLOAD_DATE, 
       MASTER_ACCOUNT_ID, 
       DAY_PAST_DUE, 
       BI_COLLECTABILITY
FROM PSAK.PSAK_MASTER_ACCOUNT_MONTHLY pmam;

Updated Rows	104093679
Query	CREATE TABLE PSAK413.PSAK_MASTER_ACCOUNT_DPD_ORI AS
	SELECT DOWNLOAD_DATE, 
	       MASTER_ACCOUNT_ID, 
	       DAY_PAST_DUE, 
	       BI_COLLECTABILITY
	FROM PSAK.PSAK_MASTER_ACCOUNT_MONTHLY pmam
Start time	Wed Jan 28 16:28:49 WIB 2026
Finish time	Wed Jan 28 17:38:30 WIB 2026


SELECT * FROM PSAK_MASTER_ACCOUNT_DPD_ORI
SELECT * FROM ifrs_master_id WHERE master_account_code = 'iBSMLD1934601191'

SELECT 
	TO_DATE(SUBSTR(IX.DOWNLOAD_DATE,1,10),'YYYY-MM-DD'), COUNT(1)
FROM CEK_DPD_MEI23_JUN23_REV_RESULT IX
GROUP BY IX.DOWNLOAD_DATE 


MERGE INTO 	IFRS_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		 TO_DATE(SUBSTR(DOWNLOAD_DATE,1,10),'YYYY-MM-DD') AS DDATE
		,MASTER_ACCOUNT_ID
		,DPD
	FROM CEK_DPD_MEI23_JUN23_REV_RESULT
	WHERE TO_DATE(SUBSTR(DOWNLOAD_DATE,1,10),'YYYY-MM-DD') = '30 JUN 2023'
	
) dat 
ON 
(
	a.DOWNLOAD_DATE = dat.DDATE 
	AND 
	a.MASTER_ACCOUNT_CODE = dat.MASTER_ACCOUNT_ID
)
WHEN MATCHED THEN UPDATE 
		SET 
			DAY_PAST_DUE_ORI = dat.DPD
*/			


/*
 * 
 * 
 * 
 * 
 * 
DECLARE
  v_start_date DATE := DATE '2020-01-31';  
  v_end_date   DATE := DATE '2025-12-31';  
 
BEGIN 

  WHILE v_start_date <= v_end_date LOOP
	  
	
UPDATE IFRS_MASTER_ACCOUNT_MONTHLY  a
SET (a.sub_segment, a.segment, a.group_segment) =
    (SELECT x.sub_segment, x.segment, x.group_segment
     FROM TMP_IMA_SEGMENT x
     WHERE a.masterid = x.masterid
     AND a.sub_segment <> x.sub_segment)
WHERE a.download_date = v_start_date;

COMMIT ; 
    -- tambah 1 bulan
DBMS_OUTPUT.PUT_LINE('Tanggal: ' || TO_CHAR(v_start_date, 'YYYY-MM-DD'));
    v_start_date := LAST_DAY(ADD_MONTHS(v_start_date, 1));
  END LOOP;
END;
 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
DECLARE
  v_start_date DATE := DATE '2020-01-31';  
  v_end_date   DATE := DATE '2025-12-31';  
 
BEGIN 

  WHILE v_start_date <= v_end_date LOOP
	  
	INSERT INTO IMATES   
	 
		SELECT download_Date,  MASTERID, ACCOUNT_STATUS_ORI, DAY_PAST_DUE   FROM IFRS_MASTER_ACCOUNT_MONTHLY A
		WHERE DOWNLOAD_DATE  = LAST_DAY(ADD_MONTHS(v_start_date, 1)) 
		AND ACCOUNT_STATUS_ORI <> 'E'
		AND EXISTS (SELECT 1 FROM IFRS_MASTER_ACCOUNT_MONTHLY X 
		WHERE X.DOWNLOAD_DATE = V_START_dATE AND A.MASTERID = X.MASTERID AND X.ACCOUNT_STATUS_ORI IS NULL
		FETCH FIRST 1 ROWS ONLY) ;
 

COMMIT ; 
    -- tambah 1 bulan
DBMS_OUTPUT.PUT_LINE('Tanggal: ' || TO_CHAR(v_start_date, 'YYYY-MM-DD'));
    v_start_date := LAST_DAY(ADD_MONTHS(v_start_date, 1));
  END LOOP;
END;

 * 
 * 
DECLARE
  v_start_date DATE := DATE '2020-02-29';  
  v_end_date   DATE := DATE '2025-12-31';  
 
BEGIN 

  WHILE v_start_date <= v_end_date LOOP
	  
	  
	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IMA_DPD';

INSERT INTO GTMP_IMA_DPD
SELECT DOWNLOAD_DATE, MASTERID, DAY_PAST_DUE, DAY_PAST_DUE_ORI , DPD_ZERO_COUNTER, OUTSTANDING, ACCOUNT_STATUS_ORI 
FROM IFRS_MASTER_ACCOUNT_MONTHLY A 
WHERE DOWNLOAD_DATE IN (V_START_dATE, LAST_DAY(ADD_MONTHS(V_START_dATE,-1)))
AND ACCOUNT_STATUS =  'A'
AND EXISTS (SELECT 1 FROM IMATES X WHERE A.MASTERID = X.MASTERID  AND LAST_DAY(ADD_MONTHS(X.DOWNLOAD_DATE,-1))  >= A.DOWNLOAD_DATE) 	  
	  
	MERGE INTO IFRS_MASTER_ACCOUNT_MONTHLY A
	USING ( 
		SELECT B.download_date, A.masterid, 
			GREATEST(nvl(B.DAY_PAST_DUE_ORI,0), nvl(A.DAY_PAST_DUE,0)) DPD,
			A.DPD_ZERO_COUNTER, A.OUTSTANDING - B.OUTSTANDING  AS DELTA_OS ,
			a.ACCOUNT_STATUS_ORI  AS prev_status, b.ACCOUNT_STATUS_ORI  AS curr_Status
		FROM GTMP_IMA_DPD a
			JOIN GTMP_IMA_DPD B ON A.MASTER = B.MASTERID 
		WHERE A.DOWNLOAD_DATE  = LAST_DAY(ADD_MONTHS(V_START_dATE,-1)) 
			AND B.DOWNLOAD_DATE   = V_START_DATE
			
		) b 
		ON (A.download_date = B.download_date AND A.masterid = B.masterid) 
		
		WHEN MATCHED THEN 
		
		UPDATE 
		SET  A.DPD_ZERO_COUNTER = 
			CASE WHEN B.DPD_ZERO_COUNTER = 4 AND b.prev_status = b.curr_status THEN 4
			WHEN b.prev_Status <> b.curr_Status THEN 0 
			WHEN B.DELTA_OS > 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND b.prev_status = b.curr_status THEN B.DPD_ZERO_COUNTER + 1 
			WHEN B.DELTA_OS = 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND b.prev_status = b.curr_status THEN B.DPD_ZERO_COUNTER
			ELSE 0 END,
			A.DAY_PAST_DUE = 
			CASE WHEN B.DELTA_OS > 0 AND NVL(A.DAY_PAST_DUE_ORI,0) = 0 AND B.DPD_ZERO_COUNTER + 1 >= 4 AND b.prev_status = b.curr_status THEN nvl(A.DAY_PAST_DUE_ORI,0)	 
			ELSE B.DPD 
			END
	  
	   
COMMIT ; 
    -- tambah 1 bulan
DBMS_OUTPUT.PUT_LINE('Tanggal: ' || TO_CHAR(v_start_date, 'YYYY-MM-DD'));
    v_start_date := LAST_DAY(ADD_MONTHS(v_start_date, 1));
  END LOOP;
END;


------------------------


 DECLARE 
dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-JAN-2020';
	 
	WHILE  dtcurr <=  '31-DEC-2025'
	LOOP 
		dtprev := LAST_DAY(ADD_MONTHS(dtcurr, -1));
	

MERGE INTO PSAK413.IFRS_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		imam.DOWNLOAD_DATE,
		imam.MASTER_ACCOUNT_ID, 
		imam.DAY_PAST_DUE
	FROM PSAK413.PSAK_MASTER_ACCOUNT_DPD_ORI imam
	WHERE imam.DOWNLOAD_DATE = dtcurr
) dat 
ON 
(
	a.MASTER_ACCOUNT_CODE = dat.MASTER_ACCOUNT_ID
	AND
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE
)
WHEN MATCHED THEN UPDATE 
		SET 
			DAY_PAST_DUE_ORI = dat.DAY_PAST_DUE;

dbms_output.put_line(dtcurr||'|'||dtprev);
dtcurr := last_day(ADD_MONTHS(dtcurr, 1));

COMMIT;

END LOOP;

END; 
 * */

/*

 
 DECLARE 
dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-JAN-2020';
	 
	WHILE  dtcurr <=  '30-SEP-2024'
	LOOP 
		dtprev := LAST_DAY(ADD_MONTHS(dtcurr, -1));


--KORPORASI--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI_PIUTANG'
				   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI_PIUTANG'	
				   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
			  END, 
	
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI_MURABAHAH'
				   	   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI_QARDH'	
				   	   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
			  	  END,
			  	  
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KORPORASI'
				   	   	 WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KORPORASI'	
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
			  	  END
WHERE 
	PSAK55_SEGMENT = 'KORPORASI'
AND DOWNLOAD_DATE = dtCURR;

--COMMERCIAL--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL_PIUTANG'
				   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL_PIUTANG'	
				   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
			  END, 
	
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL_MURABAHAH'
				   	   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL_QARDH'	
				   	   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
			  	  END,
			  	  
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KOMERSIAL'
				   	   	 WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'KOMERSIAL'	
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
			  	  END
WHERE 
	PSAK55_SEGMENT = 'COMMERCIAL'
AND DOWNLOAD_DATE = dtCURR;

--BISNIS BANKING/SMALL--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME_PIUTANG'
				   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME_PIUTANG'	
				   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
			  END, 
	
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME_MURABAHAH'
				   	   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME_QARDH'	
				   	   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
			  	  END,
			  	  
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'SME'
				   	   	 WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'SME'	
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
			  	  END
WHERE 
	PSAK55_SEGMENT = 'BISNIS BANKING/SMALL'
AND DOWNLOAD_DATE = dtCURR;

--PENSIUN & PRA PENSIUN--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN&PRAPENSIUN_PIUTANG'
				   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN&PRAPENSIUN_PIUTANG'	
				   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_PIUTANG'
				   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001') THEN 'PENSIUN&PRAPENSIUN_PIUTANG'
			  END, 
	
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN&PRAPENSIUN_PIUTANG_MURABAHAH'
				   	   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN&PRAPENSIUN_PIUTANG_QARDH'	
				   	   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS_RAHN'
				   	   WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001') THEN 'PENSIUN&PRAPENSIUN_RAHN'
			  	  END,
			  	  
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'PENSIUN_PRAPENSIUN'
				   	   	 WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'PENSIUN_PRAPENSIUN'	
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHN0001','RHN0002','RHN0004','RHN0005','RHN0007','RHN0008')	THEN 'GADAI_EMAS'
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' AND PRODUCT_CODE IN ('RHS0001')	THEN 'PENSIUN_PRAPENSIUN'
			  	  END
WHERE 
	PSAK55_SEGMENT = 'PENSIUN & PRA PENSIUN'
AND DOWNLOAD_DATE = dtCURR;

--BACK TO BACK & MURABAHAH EMAS--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'BTB_MRB_EMAS_PIUTANG'
				   WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'BTB_MRB_EMAS_PIUTANG'	
				   WHEN PRODUCT_TYPE = 'RAHN' 			THEN 'GADAI_EMAS_PIUTANG'
			  END, 
	
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'BTB_MRB_EMAS_MURABAHAH'
				   	   WHEN PRODUCT_TYPE = 'QARDH'	   	THEN 'BTB_MRB_EMAS_QARDH'	
				   	   WHEN PRODUCT_TYPE = 'RAHN' 		THEN 'GADAI_EMAS_RAHN'
			  	  END,
			  	  
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'BTB_MRB_EMAS'
				   	   	 WHEN PRODUCT_TYPE = 'QARDH'	   		THEN 'BTB_MRB_EMAS'	
				   	   	 WHEN PRODUCT_TYPE = 'RAHN' 			THEN 'GADAI_EMAS'
			  	  END
WHERE 
	PSAK55_SEGMENT = 'BACK TO BACK & MURABAHAH EMAS'
AND DOWNLOAD_DATE = dtCURR;

--KUR--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'KUR_PIUTANG' END, 
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'KUR_MURABAHAH' END,
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'KUR' END
WHERE 
	PSAK55_SEGMENT = 'KUR'
AND DOWNLOAD_DATE = dtCURR;


--NON KUR--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'NON_KUR_PIUTANG' END, 
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'NON_KUR_MURABAHAH' END,
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'NON_KUR' END
WHERE 
	PSAK55_SEGMENT = 'NON KUR'
AND DOWNLOAD_DATE = dtCURR;

--IMPLAN--
UPDATE VW_IFRS_MASTER_ACCOUNT_MONTHLY
SET 
	SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 		THEN 'MULTIGUNA_PIUTANG' END, 
	SUB_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' 	THEN 'MULTIGUNA_MURABAHAH' END,
	GROUP_SEGMENT = CASE WHEN PRODUCT_TYPE = 'MURABAHAH' THEN 'MULTIGUNA' END
WHERE 
	PSAK55_SEGMENT = 'IMPLAN'
AND DOWNLOAD_DATE = dtCURR;

dbms_output.put_line(dtcurr||'|'||dtprev);
dtcurr := last_day(ADD_MONTHS(dtcurr, 1));

COMMIT;

END LOOP;

END; 

 
  
*/



/*
SELECT DOWNLOAD_DATE, DATA_SOURCE, MASTERID, ACCOUNT_NUMBER FROM IFRS_MASTER_ACCOUNT_MONTHLY
WHERE 
PRODUCT_TYPE = 'QARDH'
AND       
ACCOUNT_STATUS = 'A'
AND 
DIVISION_CODE IS NULL

SELECT DOWNLOAD_DATE, DATA_SOURCE, MASTERID, ACCOUNT_NUMBER FROM VW_IFRS_MASTER_ACCOUNT_MONTHLY
WHERE 
PSAK55_SEGMENT = 'GRIYA & OTO'
AND       
ACCOUNT_STATUS = 'A'
AND 
DIVISION_CODE IS NULL    
*/





/*
 
 DECLARE dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);


MERGE INTO 	IFRS_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		imam.rowid rowids, 
		imam.DOWNLOAD_DATE,
		imam.DATA_SOURCE, 
		imam.ACCOUNT_NUMBER, 
		imam.CUSTOMER_NUMBER, 
		PMAM.GLOBAL_CUSTOMER_NUMBER 
	FROM IFRS_MASTER_ACCOUNT_MONTHLY imam, 
		 PSAK_MASTER_ACCOUNT_MONTHLY pmam 
	WHERE 
	    imam.account_number = PMAM.ACCOUNT_NUMBER  
	AND imam.DOWNLOAD_DATE = pmam.DOWNLOAD_DATE 
	AND imam.DATA_SOURCE = pmam.DATA_SOURCE  
	AND imam.GLOBAL_CUSTOMER_NUMBER IS NOT NULL
	AND imam.DOWNLOAD_DATE = dtcurr
	
) dat 
ON 
(
	a.rowid = dat.rowids 
	AND 
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE 
	AND 
	a.account_number = dat.account_number
	AND 
	a.DATA_SOURCE  = dat.data_source
)
WHEN MATCHED THEN UPDATE 
		SET 
			GLOBAL_CUSTOMER_NUMBER  = dat.GLOBAL_CUSTOMER_NUMBER;

dbms_output.put_line(dtcurr||'|'||dtprev);
dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));

COMMIT;

END LOOP;

END;

*/

/*


DECLARE dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);




		dbms_output.put_line(dtcurr||'|'||dtprev);
		dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));
--	COMMIT;
	END LOOP;
END;


  
*/

/*
DECLARE
	dtcurr DATE;

dtprev DATE;
BEGIN
	 dtcurr := '31-Jan-2020';

WHILE dtcurr <= '31-DEC-2025'
-- '31-DEC-2025'
LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);

MERGE
INTO
	PSAK_MASTER_ACCOUNT_MONTHLY pma
		USING (
	SELECT
		pmam.rowid rowids ,
		pmam.DOWNLOAD_DATE ,
		pmam.ACCOUNT_NUMBER ,
		pmam.CUSTOMER_NUMBER ,
		pmam.GLOBAL_CUSTOMER_NUMBER GLOBAL_CUSTOMER_NUMBER_MONTHLY,
		fin.GLOBAL_CUSTOMER_NUMBER
	FROM
		PSAK_MASTER_ACCOUNT_MONTHLY pmam,
		BSI_SUPER_CIF_FINAL fin
	WHERE
		fin.DOWNLOAD_DATE = '31-dec-2025'
		AND pmam.CUSTOMER_NUMBER = fin.CUSTOMER_NUMBER
		AND pmam.DOWNLOAD_DATE = dtcurr
		AND pmam.GLOBAL_CUSTOMER_NUMBER IS NULL
)dat ON
	(pma.rowid = dat.rowids
		AND pma.download_date = dat.download_date
		AND pma.account_number = dat.account_number
		AND pma.customer_number = dat.customer_number)
	WHEN MATCHED THEN
UPDATE
SET
	GLOBAL_CUSTOMER_NUMBER = dat.GLOBAL_CUSTOMER_NUMBER;

dbms_output.put_line(dtcurr || '|' || dtprev);

dtcurr := last_day(dtcurr + 1);

COMMIT;
END
LOOP;
END;
*/


/*
UPDATE TBLM_COMMONCODEh SET COMMONUSAGE = 10
WHERE COMMONCODE = 'MPI001'


DECLARE l_jobid number := null;
begin
	dbms_job.submit(job => l_jobid,
					what => 'BEGIN
								EXECUTE IMMEDIATE ''CREATE INDEX PSAK_MASTER_ACCOUNT_STG_IDX1 ON PSAK_MASTER_ACCOUNT_STG (DOWNLOAD_DATE)'';
							 END;',
					next_date => sysdate,
					interval => null
					);
commit;
end;
*/


/*
--QUERY CHECK TABLE CONSUME--
SELECT TABSCHEMA, TABNAME, CREATE_TIME, ALTER_TIME
FROM SYSCAT.TABLES
WHERE TABSCHEMA = 'PSAK'
ORDER BY ALTER_TIME DESC
 
SELECT SUBSTR(TABSCHEMA,1,18) AS TABSCHEMA
, SUBSTR(TABNAME,1,30) AS TABNAME
,(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) AS TOTAL_SIZE_IN_KB
,(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) / 1024  AS TOTAL_SIZE_IN_MB
,(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) / (1024*1024) AS TOTAL_SIZE_IN_GB
FROM SYSIBMADM.ADMINTABINFO
WHERE TABSCHEMA NOT LIKE 'SYS%'
ORDER BY TOTAL_SIZE_IN_GB DESC 
  
   
    
     
       
 --QUERY CHECK TABLE SPACE--
 select a.tablespace_name as "Tablespace Name",
       round(a.bytes_alloc / 1024 / 1024) "Allocated (MB)",
       round(nvl(b.bytes_free, 0) / 1024 / 1024) "Free (MB)",
       round((a.bytes_alloc - nvl(b.bytes_free, 0)) / 1024 / 1024) "Used (MB)",
       round((nvl(b.bytes_free, 0) / a.bytes_alloc) * 100) "% Free",
       100 - round((nvl(b.bytes_free, 0) / a.bytes_alloc) * 100) "% Used"
   --    round(maxbytes/1024 / 1024) "Max. Bytes (MB)"
from  ( select  f.tablespace_name,
               sum(f.bytes) bytes_alloc,
               sum(decode(f.autoextensible, 'YES',f.maxbytes,'NO', f.bytes)) maxbytes
        from dba_data_files f
        group by tablespace_name) a,
      ( select  f.tablespace_name,
               sum(f.bytes)  bytes_free
        from dba_free_space f
        group by tablespace_name) b
where a.tablespace_name = b.tablespace_name (+)
union all
select 
       h.tablespace_name as tablespace_name,
       round(sum(h.bytes_free + h.bytes_used) / 1048576) megs_alloc,
       round(sum((h.bytes_free + h.bytes_used) - nvl(p.bytes_used, 0)) / 1048576) megs_free,
       round(sum(nvl(p.bytes_used, 0))/ 1048576) megs_used,
       round((sum((h.bytes_free + h.bytes_used) - nvl(p.bytes_used, 0)) / sum(h.bytes_used + h.bytes_free)) * 100) Pct_Free,
       100 - round((sum((h.bytes_free + h.bytes_used) - nvl(p.bytes_used, 0)) / sum(h.bytes_used + h.bytes_free)) * 100) pct_used
     --  round(sum(f.maxbytes) / 1048576) max
from   sys.v_$TEMP_SPACE_HEADER h, sys.v_$Temp_extent_pool p, dba_temp_files f
where  p.file_id(+) = h.file_id
and    p.tablespace_name(+) = h.tablespace_name
and    f.file_id = h.file_id
and    f.tablespace_name = h.tablespace_name
group by h.tablespace_name
ORDER BY 2;

select * from CKPN_PMA
select * from CKPN_PAYM_SCHD_ALL
select * from CKPN_TRX
*/

/*
--INJECT PMA MONTHLY--
INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,PRODUCT_TYPE 
	,PRODUCT_CODE 
	,BRANCH_CODE 
	,ACCOUNT_STATUS 
	,ACCOUNT_STATUS_ORI
	,ACCOUNT_NUMBER 
	,CUSTOMER_NUMBER 
	,CUSTOMER_NAME 
	,CURRENCY 
	,EXCHANGE_RATE 
	,OUTSTANDING 
	,PLAFOND 
	,MARGIN_RATE 
	,EIR 
	,FAIR_VALUE_AMOUNT 
	,DAY_PAST_DUE 
	,DPD_CIF 
	,BI_COLLECTABILITY 
	,BI_COLLECT_CIF 
	,STAFF_LOAN_FLAG 
	,COLL_AMOUNT 
	,UNAMORT_FEE_AMT 
	,UNAMORT_COST_AMT 
	,MARGIN_TYPE 
	,DEFAULT_DATE 
	,LOAN_START_DATE 
	,LOAN_DUE_DATE  
	,DIVISION_CODE 
)
SELECT 
	 PMAM.DOWNLOAD_DATE
	,IMI.MASTERID
	,PMAM.MASTER_ACCOUNT_ID
	,PMAM.DATA_SOURCE
	,PMAM.PRODUCT_TYPE 
	,PMAM.PRODUCT_CODE 
	,PMAM.BRANCH_CODE 
	,CASE WHEN NVL(PMAM.ACCOUNT_STATUS,'A') = 'E' THEN 'W' ELSE 'A' END ACCOUNT_STATUS  
	,PMAM.ACCOUNT_STATUS AS ACCOUNT_STATUS_ORI
	,PMAM.ACCOUNT_NUMBER 
	,PMAM.CUSTOMER_NUMBER 
	,PMAM.CUSTOMER_NAME 
	,PMAM.CURRENCY 
	,PMAM.EXCHANGE_RATE 
	,PMAM.OUTSTANDING 
	,PMAM.PLAFOND 
	,PMAM.INTEREST_RATE 
	,PMAM.EIR 
	,PMAM.FAIR_VALUE_AMOUNT 
	,PMAM.DAY_PAST_DUE 
	,PMAM.DAY_PAST_DUE_CIF  
	,PMAM.BI_COLLECTABILITY 
	,PMAM.BI_COLLECTABILITY  
	,CASE WHEN NVL(PMAM.STAFF_LOAN_FLAG ,'N') = 'N' THEN 0 ELSE 1 END AS STAFF_LOAN_FLAG 
	,PMAM.COLLATERAL_VALUE_FOR_IMPAIR 
	,PMAM.UNAMOR_ORIGINATION_FEE_AMT 
	,PMAM.UNAMOR_TRANS_COST_AMT  
	,PMAM.AMORT_TYPE  
	,pmam.DEFAULT_DATE 
	,pmam.LOAN_START_DATE 
	,pmam.LOAN_END_DATE 
	,pmam.DIVISION_CODE 
FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam 
JOIN
IFRS_MASTER_ID IMI
ON
PMAM.MASTER_ACCOUNT_ID = IMI.MASTER_ACCOUNT_CODE; 


INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY_EXT 
(
	 DOWNLOAD_DATE 
	,MASTERID 
)
SELECT 
	 DOWNLOAD_DATE 
	,MASTERID 
FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam 
JOIN
IFRS_MASTER_ID IMI
ON
PMAM.MASTER_ACCOUNT_ID = IMI.MASTER_ACCOUNT_CODE;  
--INJECT PMA MONTHLY--

    

--INJECT VALUE CHAIN CODE--
INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,PRODUCT_TYPE 
	,PRODUCT_CODE 
	,BRANCH_CODE 
	,ACCOUNT_STATUS 
	,ACCOUNT_NUMBER 
	,CUSTOMER_NUMBER 
	,CUSTOMER_NAME 
	,CURRENCY 
	,EXCHANGE_RATE 
	,OUTSTANDING 
	,PLAFOND 
	,MARGIN_RATE 
	,EIR 
	,FAIR_VALUE_AMOUNT 
	,DAY_PAST_DUE 
	,DPD_CIF 
	,BI_COLLECTABILITY 
	,BI_COLLECT_CIF 
	,STAFF_LOAN_FLAG 
	,COLL_AMOUNT 
	,UNAMORT_FEE_AMT 
	,UNAMORT_COST_AMT 
	,MARGIN_TYPE 
	,DEFAULT_DATE 
	,LOAN_START_DATE 
	,LOAN_DUE_DATE 
	,DIVISION_CODE 
	,RESTRUCTURE_FLAG 
	,OUTSTANDING_PAST_DUE 
	,MARGIN_PAST_DUE 
)
SELECT
	 PMAM.FICMISDATE AS DOWNLOAD_DATE
	,IMI.MASTERID
	,'DVC_'|| TRIM(PMAM.NOMORREKENING) AS PMASTER_ACCOUNT_CODE
	,'DVC' AS DATA_SOURCE
	,NULL AS PRODUCT_TYPE 
	,PMAM.LOANTYPECODE AS PRODUCT_CODE 
	,PMAM.KODECABANG AS BRANCH_CODE 
	,'A' AS ACCOUNT_STATUS 
	,TRIM(PMAM.NOMORREKENING) AS ACCOUNT_NUMBER 
	,NULL AS CUSTOMER_NUMBER 
	,PMAM.NAMANASABAH AS CUSTOMER_NAME 
	,PMAM.JENISVALUTA AS CURRENCY 
	,1 AS EXCHANGE_RATE 
	,JUMLAHBULANLAPORAN AS OUTSTANDING 
	,TO_NUMBER(REPLACE(PLAFONAWAL, '.', ',')) AS PLAFOND 
	,TO_NUMBER(REPLACE(PERSENTASEIMBALANAWALKONTRAK, '.', ',')) AS MARGIN_RATE 
	,NULL AS EIR 
	,NULL AS FAIR_VALUE_AMOUNT 
	,TUNGGAKANHARI AS DAY_PAST_DUE 
	,NULL AS DPD_CIF 
	,KUALITAS AS BI_COLLECTABILITY 
	,KUALITAS AS BI_COLLECT_CIF 
	,NULL AS STAFF_LOAN_FLAG 
	,NULL AS COLL_AMOUNT 
	,NULL AS UNAMORT_FEE_AMT 
	,NULL AS UNAMORT_COST_AMT 
	,NULL AS MARGIN_TYPE 
	,NULL AS DEFAULT_DATE 
	,TO_DATE(PMAM.JANGKAWAKTUMULAI, 'YYYY-MM-DD') AS LOAN_START_DATE 
	,TO_DATE(PMAM.JANGKAWAKTUJATUHTEMPO, 'YYYY-MM-DD') AS  LOAN_DUE_DATE 
	,PMAM.DIVISIPISAH AS DIVISION_CODE 
	,NULL AS RESTRUCTURE_FLAG 
	,PMAM.TUNGGAKANPOKOK AS OUTSTANDING_PAST_DUE 
	,PMAM.TUNGGAKANMARGIN AS MARGIN_PAST_DUE
FROM FORM12_SANDIRINCIANPIUTANGQARDH_RPT_DVC PMAM
JOIN
IFRS_MASTER_ID IMI
ON
'DVC_'||TRIM(PMAM.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE; 


INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY_EXT 
(
	 DOWNLOAD_DATE 
	,MASTERID 
)
SELECT 
	 pmam.FICMISDATE AS DOWNLOAD_DATE 
	,IMI.MASTERID 
FROM FORM12_SANDIRINCIANPIUTANGQARDH_RPT_DVC pmam 
JOIN
IFRS_MASTER_ID IMI
ON
'DVC_'||TRIM(PMAM.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE; 
--INJECT VALUE CHAIN CODE--
  
 
--INJECT HASSANAH CARD--
INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,PRODUCT_TYPE 
	,PRODUCT_CODE 
	,BRANCH_CODE 
	,ACCOUNT_STATUS 
	,ACCOUNT_NUMBER 
	,CUSTOMER_NUMBER 
	,CUSTOMER_NAME 
	,CURRENCY 
	,EXCHANGE_RATE 
	,OUTSTANDING 
	,PLAFOND 
	,MARGIN_RATE 
	,EIR 
	,FAIR_VALUE_AMOUNT 
	,DAY_PAST_DUE 
	,DPD_CIF 
	,BI_COLLECTABILITY 
	,BI_COLLECT_CIF 
	,STAFF_LOAN_FLAG 
	,COLL_AMOUNT 
	,UNAMORT_FEE_AMT 
	,UNAMORT_COST_AMT 
	,MARGIN_TYPE 
	,DEFAULT_DATE 
	,LOAN_START_DATE 
	,LOAN_DUE_DATE 
	,DIVISION_CODE 
	,RESTRUCTURE_FLAG 
	,OUTSTANDING_PAST_DUE 
	,MARGIN_PAST_DUE 
)
SELECT 
	 pmam.FICMISDATE AS DOWNLOAD_DATE
	,IMI.MASTERID
	,'HC_'|| pmam.NOMORREKENING AS MASTER_ACCOUNT_CODE
	,'HC' AS DATA_SOURCE
	,'QARDH' AS PRODUCT_TYPE 
	,pmam.LOANTYPECODE AS PRODUCT_CODE 
	,pmam.KODECABANG AS BRANCH_CODE 
	,'A' AS ACCOUNT_STATUS 
	,pmam.NOMORREKENING  AS ACCOUNT_NUMBER 
	,pmam.NOMORNASABAH AS CUSTOMER_NUMBER 
	,pmam.NAMANASABAH  AS CUSTOMER_NAME 
	,pmam.JENISVALUTA AS CURRENCY 
	,1 AS EXCHANGE_RATE 
	,pmam.JUMLAHBULANLAPORAN  AS OUTSTANDING 
	,NULL AS PLAFOND 
	,NULL AS MARGIN_RATE 
	,NULL AS EIR 
	,NULL AS FAIR_VALUE_AMOUNT 
	,pmam.TUNGGAKANHARI AS DAY_PAST_DUE 
	,NULL AS DPD_CIF 
	,pmam.KUALITAS AS BI_COLLECTABILITY 
	,pmam.KUALITAS AS BI_COLLECT_CIF 
	,NULL AS STAFF_LOAN_FLAG 
	,NULL AS COLL_AMOUNT 
	,NULL AS UNAMORT_FEE_AMT 
	,NULL AS UNAMORT_COST_AMT 
	,NULL AS MARGIN_TYPE 
	,NULL AS DEFAULT_DATE 
	,pmam.JANGKAWAKTUMULAI AS LOAN_START_DATE 
	,pmam.JANGKAWAKTUJATUHTEMPO AS LOAN_DUE_DATE 
	,pmam.DIVISIPISAH AS DIVISION_CODE 
	,CASE WHEN pmam.SIFATPIUTANG IN ('1', '5') THEN 1 ELSE 0 END RESTRUCTURE_FLAG
	,pmam.TUNGGAKANPOKOK AS OUTSTANDING_PAST_DUE
	,pmam.TUNGGAKANMARGIN AS MARGIN_PAST_DUE
FROM 
FORM12_SANDIRINCIANPIUTANGQARDH_RPT_TMP pmam 
JOIN
IFRS_MASTER_ID IMI
ON
'HC_'||TRIM(pmam.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE;

INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY_EXT 
(
	 DOWNLOAD_DATE 
	,MASTERID 
)
SELECT 
	 pmam.FICMISDATE AS DOWNLOAD_DATE 
	,IMI.MASTERID 
FROM FORM12_SANDIRINCIANPIUTANGQARDH_RPT_TMP pmam 
JOIN
IFRS_MASTER_ID IMI
ON
'HC_'||TRIM(PMAM.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE; 

INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY
(
	 DOWNLOAD_DATE
	,MASTERID
	,MASTER_ACCOUNT_CODE
	,DATA_SOURCE
	,PRODUCT_TYPE 
	,PRODUCT_CODE 
	,BRANCH_CODE 
	,ACCOUNT_STATUS 
	,ACCOUNT_NUMBER 
	,CUSTOMER_NUMBER 
	,CUSTOMER_NAME 
	,CURRENCY 
	,EXCHANGE_RATE 
	,OUTSTANDING 
	,PLAFOND 
	,MARGIN_RATE 
	,EIR 
	,FAIR_VALUE_AMOUNT 
	,DAY_PAST_DUE 
	,DPD_CIF 
	,BI_COLLECTABILITY 
	,BI_COLLECT_CIF 
	,STAFF_LOAN_FLAG 
	,COLL_AMOUNT 
	,UNAMORT_FEE_AMT 
	,UNAMORT_COST_AMT 
	,MARGIN_TYPE 
	,DEFAULT_DATE 
	,LOAN_START_DATE 
	,LOAN_DUE_DATE 
	,DIVISION_CODE 
	,RESTRUCTURE_FLAG 
	,OUTSTANDING_PAST_DUE 
	,MARGIN_PAST_DUE 
)
SELECT 
	 PMAM.PERIODEDATA AS DOWNLOAD_DATE
	,IMI.MASTERID
	,'HC_'|| TRIM(PMAM.NOMORREKENING) AS MASTER_ACCOUNT_CODE
	,'HC' AS DATA_SOURCE
	,'QARDH' AS PRODUCT_TYPE 
	,'HC0001' AS PRODUCT_CODE 
	,NULL AS BRANCH_CODE 
	,'A' AS ACCOUNT_STATUS 
	,TRIM(PMAM.NOMORREKENING) AS ACCOUNT_NUMBER 
	,PMAM.IDDEBITUR AS CUSTOMER_NUMBER 
	,NULL AS CUSTOMER_NAME 
	,PMAM.JENISVALUTA AS CURRENCY 
	,1 AS EXCHANGE_RATE 
	,PMAM.BAKIDEBET AS OUTSTANDING 
	,PMAM.PLAFON AS PLAFOND 
	,21 AS MARGIN_RATE 
	,NULL AS EIR 
	,NULL AS FAIR_VALUE_AMOUNT 
	,PMAM.JUMLAHHARITUNGGAKAN DAY_PAST_DUE 
	,NULL DPD_CIF 
	,PMAM.KUALITAS AS BI_COLLECTABILITY 
	,PMAM.KUALITAS AS BI_COLLECT_CIF 
	,NULL AS STAFF_LOAN_FLAG 
	,NULL AS COLL_AMOUNT 
	,NULL AS UNAMORT_FEE_AMT 
	,NULL AS UNAMORT_COST_AMT 
	,NULL AS MARGIN_TYPE 
	,NULL AS DEFAULT_DATE 
	,TO_DATE(PMAM.TANGGALAKADAWAL, 'YYYY-MM-DD') AS LOAN_START_DATE 
	,TO_DATE(PMAM.TANGGALAKADAKHIR, 'YYYY-MM-DD') AS LOAN_DUE_DATE 
	,NULL AS DIVISION_CODE 
	,NULL AS RESTRUCTURE_FLAG 
	,PMAM.TUNGGAKANPOKOK AS OUTSTANDING_PAST_DUE 
	,PMAM.TUNGGAKANMARGINIMBALAN MARGIN_PAST_DUE 
FROM KREDITPEMBIAYAAN_HC PMAM
JOIN
IFRS_MASTER_ID IMI
ON
'HC_'||TRIM(PMAM.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE; 


INSERT INTO IFRS_MASTER_ACCOUNT_MONTHLY_EXT 
(
	 DOWNLOAD_DATE 
	,MASTERID 
)
SELECT 
	 pmam.PERIODEDATA AS DOWNLOAD_DATE 
	,IMI.MASTERID 
FROM KREDITPEMBIAYAAN_HC pmam 
JOIN
IFRS_MASTER_ID IMI
ON
'HC_'||TRIM(PMAM.NOMORREKENING) = IMI.MASTER_ACCOUNT_CODE;  
--INJECT HASSANAH CARD--  
*/

/*
--PATCH PRODUCT TYPE--
CREATE TABLE MAX_PMAM_PRODUCT_TYPE
AS
   SELECT 
		MAX(DOWNLOAD_DATE) AS MAX_DDATE
   	   ,MASTER_ACCOUNT_ID 	
   FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam
   WHERE MASTER_ACCOUNT_ID IN 
   (
   	   SELECT 
		MASTER_ACCOUNT_ID	
   	   FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam
   	   GROUP BY MASTER_ACCOUNT_ID 
   	   HAVING count(DISTINCT UPPER(PRODUCT_TYPE))> 1
   )
   GROUP BY MASTER_ACCOUNT_ID 
  
SELECT 
PMAM.DOWNLOAD_DATE, 
PMAM.MASTER_ACCOUNT_ID, 
PMAM.PRODUCT_TYPE 
FROM 
PSAK_MASTER_ACCOUNT_MONTHLY PMAM
JOIN
MAX_PMAM_PRODUCT_TYPE MPP
ON
PMAM.DOWNLOAD_DATE = MAX_DDATE
AND 
PMAM.MASTER_ACCOUNT_ID = MPP.MASTER_ACCOUNT_ID

) X
ON
PMAM.DOWNLOAD_DATE <= X.DOWNLOAD_DATE
AND 
PMAM.MASTER_ACCOUNT_ID = X.MASTER_ACCOUNT_ID
WHERE 
PMAM.MASTER_ACCOUNT_ID = 'iBSMLD2113658346'
 
SELECT DOWNLOAD_DATE, MASTER_ACCOUNT_ID, PRODUCT_CODE, PRODUCT_TYPE  FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam 
WHERE MASTER_ACCOUNT_ID  = 'iBSMLD2113658346'
ORDER BY DOWNLOAD_DATE 

MERGE INTO 	PSAK_MASTER_ACCOUNT_MONTHLY a USING
(
SELECT 
PMAM.DOWNLOAD_DATE, 
PMAM.MASTER_ACCOUNT_ID, 
PMAM.PRODUCT_TYPE 
FROM 
PSAK_MASTER_ACCOUNT_MONTHLY PMAM
JOIN
MAX_PMAM_PRODUCT_TYPE MPP
ON
PMAM.DOWNLOAD_DATE = MAX_DDATE
AND 
PMAM.MASTER_ACCOUNT_ID = MPP.MASTER_ACCOUNT_ID
) dat 
ON 
(
	a.DOWNLOAD_DATE <= dat.DOWNLOAD_DATE 
	AND 
	a.MASTER_ACCOUNT_ID = dat.MASTER_ACCOUNT_ID
)
WHEN MATCHED 
THEN UPDATE 
SET 
PRODUCT_TYPE = dat.PRODUCT_TYPE;
--PATCH PRODUCT TYPE--
  
--PATCH LOAN_START_DATE, LOAN_DUE_DATE--
DECLARE dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);


MERGE INTO 	PSAK_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		pmam.rowid rowids, 
		pmam.DOWNLOAD_DATE,
		pmam.MASTER_ACCOUNT_ID, 
		pmam.CUSTOMER_NUMBER, 
		pmal.LOAN_START_DATE,
		pmal.LOAN_DUE_DATE
	FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam, 
		PSAK_MASTER_ACCOUNT_LOAN_DATE pmal
	WHERE pmam.MASTER_ACCOUNT_ID = pmal.MASTER_ACCOUNT_ID 
    --AND trim(to_char(pmam.DOWNLOAD_DATE,'dd-mm-yyyy')) = trim(REPLACE(pmal.DOWNLOAD_DATE,'00.00.00,000000000',''))
	AND pmam.DOWNLOAD_DATE = pmal.DOWNLOAD_DATE 
	AND pmam.DOWNLOAD_DATE = dtcurr
) dat 
ON 
(
	a.rowid = dat.rowids 
	AND 
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE 
	AND 
	a.MASTER_ACCOUNT_ID = dat.MASTER_ACCOUNT_ID
)
WHEN MATCHED THEN UPDATE 
		SET 
			LOAN_START_DATE = dat.LOAN_START_DATE, 
			LOAN_END_DATE = dat.LOAN_DUE_DATE;

dbms_output.put_line(dtcurr||'|'||dtprev);
dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));

COMMIT;

END LOOP;

END;
--PATCH LOAN_START_DATE, LOAN_DUE_DATE--

--PATCH DIVISION CODE--
DECLARE dtcurr DATE;
dtprev DATE;

BEGIN
	 dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);


MERGE INTO 	PSAK_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		pmam.rowid rowids, 
		pmam.DOWNLOAD_DATE,
		pmam.account_number, 
		pmam.CUSTOMER_NUMBER, 
		lpda.noloan,
		lpda.divisi_pisah
	FROM PSAK_MASTER_ACCOUNT_MONTHLY pmam, 
		 LoanPerDivisi_All lpda
	WHERE pmam.account_number = lpda.noloan 
    --AND trim(to_char(pmam.DOWNLOAD_DATE,'dd-mm-yyyy')) = trim(REPLACE(pmal.DOWNLOAD_DATE,'00.00.00,000000000',''))
	AND pmam.DOWNLOAD_DATE = lpda.ficmisdate 
	AND pmam.DOWNLOAD_DATE = dtcurr
) dat 
ON 
(
	a.rowid = dat.rowids 
	AND 
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE 
	AND 
	a.account_number = dat.account_number
)
WHEN MATCHED THEN UPDATE 
		SET 
			DIVISION_CODE = dat.divisi_pisah;

dbms_output.put_line(dtcurr||'|'||dtprev);
dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));

COMMIT;

END LOOP;

END;
--PATCH DIVISION CODE--
 
 
 WITH cte  AS (
SELECT   PRODUCT_CODE ,MASTERID  , MIN(LOAN_DUE_DATE)LOAN_DUE_DATE, max(DOWNLOAD_DATE) DOWNLOAD_DATE
FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE extract(YEAR FROM download_date) = 2020
AND ACCOUNT_STATUS  = 'A'
AND OUTSTANDING  > 0
AND PRODUCT_CODE  NOT LIKE 'DUMMY%'
AND PRODUCT_TYPE  = 'MURABAHAH'
GROUP BY MASTERID , PRODUCT_CODE 
),
cte2 AS (
SELECT min(DOWNLOAD_DATE) DOWNLOAD_DATE, MASTERID  
FROM IFRS_MASTER_ACCOUNT_MONTHLY a 
WHERE DIVISION_CODE IS NOT NULL 
AND EXISTS (SELECT * FROM cte x WHERE a.masterid = x.MASTERID )
GROUP BY MASTERID 
)

SELECT  A.PRODUCT_CODE,count(*)
FROM cte a 
WHERE NOT  EXISTS (SELECT * FROM cte2 x WHERE a.masterid = x.masterid )  
GROUP BY a.PRODUCT_CODE

 
 --ini
 
SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2006 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-06-30	62,879

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2007 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-07-31	60,768

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2008 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-08-31	40,438

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2009 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-09-30	33,375

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2010 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-10-31	38,884

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2011 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-11-30	25,747

SELECT "FicMisDate", count(1) FROM FORM12_LSMK_BNIS_2012 GROUP BY "FicMisDate"
FicMisDate	COUNT(1)
2020-12-31	62,864
    
 * */



END;