CREATE OR REPLACE EDITIONABLE PROCEDURE "PSAK413"."SP_IFRS_LGD_WORKOUT_HEADER" (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0',
 P_PRC			 IN VARCHAR2 DEFAULT 'x'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(1000);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY VARCHAR2(32767);

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLESELECT2 VARCHAR2(100);
    V_TABLELGDCONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100) := 'SP_IFRS_LGD_WORKOUT_HEADER';
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');
	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));
	
    IF P_PRC = 'S' THEN  
        V_TABLEINSERT1 := 'IFRS_LGD_WORKOUT_HEADER_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_LGD_WORKOUT_DETAIL_' || P_RUNID || ''; 
    ELSE  
        V_TABLEINSERT1 := 'IFRS_LGD_WORKOUT_HEADER';
        V_TABLESELECT1 := 'IFRS_LGD_WORKOUT_DETAIL'; 
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
 

	----TABLE PROCESS
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1);
        
		IF V_COUNT =  0 THEN 
		 
        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LGD_WORKOUT_HEADER WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
       END IF ; 
    END IF;
	COMMIT;
    -------- ====== PRE SIMULATION TABLE ======

	 

   EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG' ; 
  
	 V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG
	               SELECT * FROM IFRS_LGD_WORKOUT_RULES_CONFIG
	               WHERE  IS_DELETED = 0  AND  (  
	                 UPPER(TRIM(SYSCODE_WORKOUT)) IN ( 
	                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
	                   FROM DUAL
	                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
	                 )
	                 OR :p2 = ''0'' 
	               )';
	 
	    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
 
  
	 

    IF V_MODEL_ID = '0' THEN 
    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    ELSE
	V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
    WHERE  EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE A.WORKOUT_RULE_ID = X.PKID)
    AND A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    END IF;
    EXECUTE IMMEDIATE (V_STR_QUERY);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	-- End Clear Session

   

   
	-- POPULATE RECOVERY FROM DEFAULT ACCOUNTS
	V_STR_QUERY := '';
	V_STR_QUERY := 
'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ( 
    EFF_DATE,
    WORKOUT_RULE_ID,
    EQV_OS_AT_DEFAULT,
    SEQ,
    EQV_REC_OS,
    CUM_REC_OS,
    MARGINAL_REC,
    CUM_REC,
    CREATEDBY,
    CREATEDDATE
) 
WITH cte AS (
SELECT EFF_DATE,WORKOUT_RULE_ID , MASTERID ,MAX(EQV_OS_AT_DEFAULT)EQV_OS_AT_DEFAULT  
FROM '   || V_TABLESELECT1 || ' A	
WHERE EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE A.WORKOUT_RULE_ID = X.PKID)
    AND A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
GROUP BY EFF_DATE,WORKOUT_RULE_ID ,MASTERID
),
cte2 AS (
SELECT EFF_DATE, WORKOUT_RULE_ID ,SUM(EQV_OS_AT_DEFAULT)EQV_OS_AT_DEFAULT  
FROM  CTE
GROUP BY EFF_DATE ,WORKOUT_RULE_ID 
),
 CTE_SEQ(EFF_DATE, WORKOUT_RULE_ID, SEQ,MAXSEQ) AS (
   SELECT EFF_DATE, WORKOUT_RULE_ID , 1 SEQ ,MAX(SEQ )MAXSEQ 
	FROM '   || V_TABLESELECT1 || ' A	 
	WHERE EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE A.WORKOUT_RULE_ID = X.PKID)
	    AND A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	GROUP BY EFF_DATE,WORKOUT_RULE_ID 
    UNION ALL 
   SELECT EFF_DATE, WORKOUT_RULE_ID , SEQ+1 ,MAXSEQ
   FROM CTE_SEQ
   WHERE SEQ < MAXSEQ
),
CTE3 AS (
SELECT B.EFF_DATE, B.WORKOUT_RULE_ID ,B.SEQ ,sum(NVL(A.EQV_REC_OS,0))EQV_REC_OS  
FROM '   || V_TABLESELECT1 || ' A	
	RIGHT JOIN CTE_SEQ B ON A.SEQ = B.SEQ AND A.EFF_DATE = B.EFF_DATE AND A.WORKOUT_RULE_ID = B.WORKOUT_RULE_ID
WHERE EXISTS (SELECT 1 FROM GTMP_IFRS_LGD_WORKOUT_RULES_CONFIG X WHERE B.WORKOUT_RULE_ID = X.PKID)
    AND B.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
GROUP BY B.EFF_DATE,B.WORKOUT_RULE_ID ,B.SEQ 
)
,CTE4 AS (
SELECT A.EFF_DATE, A.WORKOUT_RULE_ID, A.EQV_OS_AT_DEFAULT, B.SEQ, B.EQV_REC_OS,
	SUM(B.EQV_REC_OS) OVER (PARTITION BY A.EFF_DATE, A.WORKOUT_RULE_ID ORDER BY B.SEQ) AS MARGINAL_REC_OS
FROM CTE2 A 
	JOIN CTE3 B ON A.EFF_DATE = B.EFF_DATE AND A.WORKOUT_RULE_ID = B.WORKOUT_RULE_ID)

SELECT   A.EFF_DATE, A.WORKOUT_RULE_ID, A.EQV_OS_AT_DEFAULT, A.SEQ, A.EQV_REC_OS,
	A.MARGINAL_REC_OS,
	EQV_REC_OS / EQV_OS_AT_DEFAULT AS MARGINAL_REC, 
	MARGINAL_REC_OS/EQV_OS_AT_DEFAULT AS CUM_REC,
	''SP_IFRS_LGD_WORKOUT_HEADER'',
	SYSDATE
FROM CTE4 A 
ORDER BY  EFF_DATE,  WORKOUT_RULE_ID,  SEQ 
	';
	
	
	 
DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;


     
   
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT1; 
    V_COLUMNDEST := '-';
    
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') AND (WORKOUT_RULE_ID = ''' || V_MODEL_ID || ''' OR ''' || V_MODEL_ID || ''' = ''0'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END