CREATE OR REPLACE EDITIONABLE PROCEDURE "PSAK413"."SP_IFRS_LGD_REC_DATA2" (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0',
 P_PRC			 IN VARCHAR2 DEFAULT 'X'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(8000);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY VARCHAR2(8000);

	---- TABLE LIST A
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLECONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');
	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));
	
  --  IF V_CURRDATE = V_EOMDATE THEN   
 		V_TABLE_NAME := 'IFRS_MASTER_ACCOUNT_MONTHLY' ;
 --	ELSE 
 	--	V_TABLE_NAME := 'VW_IFRS_MASTER_ACCOUNT';
 --	END IF ;
 
    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'IFRS_LGD_REC_DATA_' || P_RUNID || '';  
		V_TABLESELECT1 := 'IFRS_DEFAULT_' || P_RUNID || '';
    ELSE 
        V_TABLEINSERT1 := 'IFRS_LGD_REC_DATA';  
		V_TABLESELECT1 := 'IFRS_DEFAULT';
    END IF;

    V_SPNAME := 'SP_IFRS_LGD_REC_DATA';
    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE PROCESS
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1);
        
		IF V_COUNT = 0 THEN
		V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LGD_REC_DATA WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
		END IF;

        
    END IF;
	COMMIT;
 

	 V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LGD_RULES_CONFIG
               SELECT * FROM IFRS_LGD_RULES_CONFIG
               WHERE LGD_METHOD = ''Expected Recovery'' AND IS_DELETED = 0 AND (  
                 UPPER(TRIM(SYSCODE_LGD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0''
               )';
  DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
 
	   
	    
   
    -------- ====== BODY ======
	-- Clear Session
    IF V_MODEL_ID = '0' THEN 
    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A
    WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    ELSE
	V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||' A 
    WHERE  A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')  
    AND EXISTS (SELECT * FROM GTMP_IFRS_LGD_RULES_CONFIG X WHERE A.RULE_ID = X.DEFAULT_RULE_ID)'; 
    END IF;
    EXECUTE IMMEDIATE (V_STR_QUERY);
    COMMIT;
 
   
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	-- End Clear Session
   
   EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_DEFAULT_LGD';
   EXECUTE IMMEDIATE 'TRUNCATE TABLE  GTMP_IFRS_IMA_CURR';  
   EXECUTE IMMEDIATE 'TRUNCATE TABLE  GTMP_IFRS_IMA_PREV'; 
   
  	V_STR_QUERY := 'INSERT INTO GTMP_IFRS_DEFAULT_LGD (DEFAULT_DATE , RULE_ID  , CUSTOMER_NUMBER,FACILITY_NUMBER, MASTERID,EIR,CCY, OUTSTANDING)
WITH CTE AS (
SELECT DOWNLOAD_DATE, MASTERID  , RULE_ID ,
CUSTOMER_NUMBER , FACILITY_NUMBER ,EIR_AT_DEFAULT , CCY_AT_DEFAULT , OS_AT_DEFAULT,
ROW_NUMBER() OVER (PARTITION BY RULE_ID,MASTERID  ORDER BY DOWNLOAD_DATE) RN
FROM ' || V_TABLESELECT1 || ' A 
WHERE DOWNLOAD_DATE <= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
AND EXISTS (SELECT 1 fROM  GTMP_IFRS_LGD_RULES_CONFIG X WHERE A.RULE_ID = X.DEFAULT_RULE_ID)
)
SELECT DOWNLOAD_DATE, RULE_ID ,CUSTOMER_NUMBER ,FACILITY_NUMBER ,MASTERID ,EIR_AT_DEFAULT , CCY_AT_DEFAULT , OS_AT_DEFAULT
FROM CTE 
WHERE RN = 1 
'; 
EXECUTE IMMEDIATE (V_STR_QUERY);
COMMIT;

 

V_STR_QUERY := 'INSERT INTO GTMP_IFRS_IMA_PREV (DOWNLOAD_DATE, MASTERID, CCY, OUTSTANDING, PRC_TYPE)
	SELECT DOWNLOAD_DATE, MASTERID, CURRENCY, OUTSTANDING, ''LGD''
	FROM IFRS_MASTER_ACCOUNT_MONTHLY A 
	WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_PREVDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	AND ACCOUNT_STATUS IN(''A'',''W'')
	AND EXISTS (SELECT 1 FROM GTMP_IFRS_DEFAULT_LGD X WHERE A.MASTERID = X.MASTERID FETCH FIRST 1 ROW ONLY)';
EXECUTE IMMEDIATE (V_STR_QUERY);
COMMIT;

V_STR_QUERY := 'INSERT INTO GTMP_IFRS_IMA_CURR (DOWNLOAD_DATE, MASTERID, CCY, OUTSTANDING, PRC_TYPE)
	SELECT DOWNLOAD_DATE, MASTERID, CURRENCY, OUTSTANDING, ''LGD''
	FROM IFRS_MASTER_ACCOUNT_MONTHLY A 
	WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	AND ACCOUNT_STATUS IN(''A'',''W'')
	AND EXISTS (SELECT 1 FROM GTMP_IFRS_DEFAULT_LGD X WHERE A.MASTERID = X.MASTERID FETCH FIRST 1 ROW ONLY)';
EXECUTE IMMEDIATE (V_STR_QUERY);
COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));


	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' (
	 DOWNLOAD_DATE
	 ,RULE_ID, CUSTOMER_NUMBER, FACILITY_NUMBER
	 ,MASTERID, CCY,REC_TYPE,SEQ
	 ,REC_OS
	 ,EQV_REC_OS
	 ,CREATEDBY
	 ,CREATEDDATE )
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
		,B.RULE_ID, B.CUSTOMER_NUMBER, B.FACILITY_NUMBER   
		,B.MASTERID , B.CCY, ''OS'' 
		,TRUNC(MONTHS_BETWEEN(TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD''),  B.DEFAULT_DATE))
		,C.OUTSTANDING - NVL(A.OUTSTANDING, 0) AS REC_OS    
		,(C.OUTSTANDING - NVL(A.OUTSTANDING, 0)) * E.RATE_AMOUNT AS EQV_REQ_OS     
		,''SP_IFRS_LGD_REC_DETAIL_1''   
		,SYSDATE
	FROM GTMP_IFRS_DEFAULT_LGD B    
		LEFT JOIN GTMP_IFRS_IMA_CURR A ON B.MASTERID = A.MASTERID     
		JOIN GTMP_IFRS_IMA_PREV C ON C.MASTERID = B.MASTERID      
		JOIN IFRS_MASTER_EXCHANGE_RATE E ON B.CCY = E.CURRENCY    
			AND E.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	WHERE B.DEFAULT_DATE <= TO_DATE(''' || TO_CHAR(V_PREVDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	    

	-- DELETE REC OS = 0 & REC_OS_INT = 0
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' 
	WHERE DOWNLOAD_DATE =  TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
	AND REC_OS <= 0 ';  
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    -------- ====== BODY ======

    -------- ====== LOG ======
    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END