CREATE OR REPLACE EDITIONABLE PROCEDURE "PSAK413"."SP_IFRS_LGD_DATAX" (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(22);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY VARCHAR2(8000);

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLESELECT2 VARCHAR2(100);
    V_TABLESELECT3 VARCHAR2(100);
    V_TABLESELECT4 VARCHAR2(100);
	V_TABLECONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');
	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));

	
		V_TABLECONFIG := 'IFRS_LGD_RULES_CONFIG';
	
    IF P_PRC = 'S' THEN 
        --V_TABLEINSERT1 := 'GTMP_LGD_RUNNING_CONFIG_' || P_RUNID || '';
        V_TABLEINSERT1 := 'IFRS_LGD_DATA_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_DEFAULT_' || P_RUNID || '';
        V_TABLESELECT2 := 'IFRS_LGD_RULE_DATA_' || P_RUNID || '';
        V_TABLESELECT3 := 'IFRS_MASTER_ACCOUNT_WO_' || P_RUNID || '';
        V_TABLESELECT4 := 'IFRS_MASTER_ACCOUNT_CLOSE_' || P_RUNID || ''; 
    ELSE 
       -- V_TABLEINSERT1 := 'GTMP_LGD_RUNNING_CONFIG';
        V_TABLEINSERT1 := 'IFRS_LGD_DATA';
        V_TABLESELECT1 := 'IFRS_DEFAULT';
        V_TABLESELECT2 := 'IFRS_LGD_RULE_DATA';
        V_TABLESELECT3 := 'IFRS_MASTER_ACCOUNT_WO';
        V_TABLESELECT4 := 'IFRS_MASTER_ACCOUNT_CLOSE';
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE CONFIG
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1);
        
		IF V_COUNT = 0 THEN 
		V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LGD_DATA ild  WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
		END IF;

        
    END IF;
	COMMIT;


	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LGD_RULES_CONFIG' ; 
		 
	    V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LGD_RULES_CONFIG
	               SELECT * FROM IFRS_LGD_RULES_CONFIG
	               WHERE LGD_METHOD = ''Expected Recovery'' AND (  
	                 UPPER(TRIM(SYSCODE_LGD)) IN ( 
	                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
	                   FROM DUAL
	                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
	                 )
	                 OR :p2 IS NULL 
	               )';
	 
	    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
 
    -------- ====== PRE SIMULATION TABLE ======
 
    IF V_MODEL_ID = '0' THEN 
	V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||' A
    WHERE A.DEFAULT_DATE >= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    ELSE
	V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||' A
    USING ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B 
    WHERE A.SYSCODE_LGD = B.SYSCODE_LGD AND A.LGD_RULE_ID = B.LGD_RULE_ID
    AND A.DEFAULT_DATE >= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    END IF;
	EXECUTE IMMEDIATE (V_STR_QUERY);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
	-- End Clear Session

	-- RESET STATUS WO
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	MERGE INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A 
	USING (
	 SELECT A.MASTERID, A.DEFAULT_DATE
	 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A
	 JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.SYSCODE_LGD = B.SYSCODE_LGD AND A.LGD_RULE_ID = B.LGD_RULE_ID
	 WHERE A.WO_DATE >= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	) B ON (A.MASTERID = B.MASTERID AND A.DEFAULT_DATE = B.DEFAULT_DATE) 
	WHEN MATCHED THEN 
	UPDATE SET A.ACCOUNT_STATUS = ''A'',
	A.WO_DATE = NULL,
	A.UPDATEDBY = ''SP_IFRS_LGD_DATA'',
	A.UPDATEDATE = SYSDATE()';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));

	-- RESET STATUS CLOSED
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	MERGE INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A 
	USING (
	 SELECT A.MASTERID, A.DEFAULT_DATE
	 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A
	 JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.SYSCODE_LGD = B.SYSCODE_LGD AND A.LGD_RULE_ID = B.LGD_RULE_ID
	 WHERE A.CLOSED_DATE >= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	) B ON (A.MASTERID = B.MASTERID AND A.DEFAULT_DATE = B.DEFAULT_DATE) 
	WHEN MATCHED THEN 
	UPDATE SET A.ACCOUNT_STATUS = ''A'',
	A.CLOSED_DATE = NULL,
	A.UPDATEDBY = ''SP_IFRS_LGD_DATA_1'',
	A.UPDATEDATE = SYSDATE()';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;

    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));

	--POPULATE LGD DATA
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' (
	 DEFAULT_DATE 
	 ,SYSCODE_LGD
	 ,LGD_RULE_ID
	 ,DEFAULT_RULE_ID 
	 ,MASTERID
	 ,FACILITY_NUMBER 
	 ,CUSTOMER_NUMBER 
	 ,EIR_AT_DEFAULT
	 ,CURRENCY
	 ,EQV_OS_AT_DEFAULT 
	 ,EQV_OS_INT_AT_DEFAULT 
	 ,OS_AT_DEFAULT  
	 ,OS_INT_AT_DEFAULT
	 ,WO_DATE
	 ,CLOSED_DATE
	 ,ACCOUNT_STATUS
	 ,CREATEDBY
	 ,CREATEDDATE
	 )
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	 ,B.SYSCODE_LGD
	 ,B.LGD_RULE_ID
	 ,A.RULE_ID 
	 ,A.MASTERID  
	 ,C.FACILITY_NUMBER 
	 ,C.CUSTOMER_NUMBER
	 ,A.EIR_AT_DEFAULT
	 ,C.CURRENCY
	 ,A.EQV_AT_DEFAULT 
	 ,A.EQV_OS_INT_AT_DEFAULT 
	 ,A.OS_AT_DEFAULT    
	 ,A.OS_INT_AT_DEFAULT 
	 ,D.DOWNLOAD_DATE AS WO_DATE 
	 ,NULL AS CLOSED_DATE 
	 ,C.ACCOUNT_STATUS  
	 ,''SP_IFRS_LGD_DATA'' CREATEDBY 
	 ,SYSDATE() CREATEDDATE 
	FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' A 
	INNER JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.RULE_ID = B.DEFAULT_RULE_ID 
	INNER JOIN ' || V_TAB_OWNER || '.' || V_TABLESELECT2 || ' C ON A.MASTERID = C.MASTERID 
	 AND B.SEGMENTATION_ID = C.RULE_ID 
	 AND C.RULE_TYPE = ''LGD_SEGMENT'' 
	LEFT JOIN IFRS_MASTER_ACCOUNT_WO D ON C.MASTERID = D.MASTERID 
	 AND D.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
            
	-- UPDATE STATUS WO
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	MERGE INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A 
	USING (
	 SELECT A.MASTERID, A.DEFAULT_DATE, C.DOWNLOAD_DATE AS WO_DATE
	 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A
	 JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.SYSCODE_LGD = B.SYSCODE_LGD AND A.LGD_RULE_ID = B.LGD_RULE_ID
	 JOIN ' || V_TAB_OWNER || '.' || V_TABLESELECT3 || ' C ON A.MASTERID = C.MASTERID
	 WHERE A.DEFAULT_DATE <= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
	  AND A.ACCOUNT_STATUS = ''A''
	  AND C.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
	) B ON (A.MASTERID = B.MASTERID AND A.DEFAULT_DATE = B.DEFAULT_DATE) 
	WHEN MATCHED THEN 
	UPDATE SET A.ACCOUNT_STATUS = ''W'',
	A.WO_DATE = B.WO_DATE,
	A.UPDATEDBY = ''SP_IFRS_LGD_DATA_4'',
	A.UPDATEDATE = SYSDATE()';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;

	-- UPDATE STATUS CLOSED
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	MERGE INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A 
	USING (
	 SELECT A.MASTERID, A.DEFAULT_DATE
	 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A
	 JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.SYSCODE_LGD = B.SYSCODE_LGD AND A.LGD_RULE_ID = B.LGD_RULE_ID
	 WHERE A.DEFAULT_DATE <= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
	  AND A.ACCOUNT_STATUS = ''A''
	  AND NOT EXISTS (
	   SELECT * 
	   FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT2 || ' C
	   WHERE C.RULE_TYPE = ''LGD_SEGMENT''
	    AND C.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')
	    AND C.MASTERID = A.MASTERID
	    AND C.RULE_ID = B.SEGMENTATION_ID
	   FETCH FIRST 1 ROW ONLY
	  )
	OR EXISTS (
	 SELECT * 
	 FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT4 || ' Z
	 WHERE Z.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
	  AND Z.MASTERID = A.MASTERID
	 FETCH FIRST 1 ROW ONLY
	)
	) B ON (A.MASTERID = B.MASTERID AND A.DEFAULT_DATE = B.DEFAULT_DATE) 
	WHEN MATCHED THEN 
	UPDATE SET A.ACCOUNT_STATUS = ''C'',
	A.CLOSED_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD''),
	A.UPDATEDBY = ''SP_IFRS_LGD_DATA_3'',
	A.UPDATEDATE = SYSDATE()';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;
    -------- ====== BODY ======

    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT2;
    V_COLUMNDEST := '-';
    V_SPNAME := 'SP_IFRS_LGD_DATA';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TABLEINSERT2 || ' WHERE DEFAULT_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END