CREATE OR REPLACE EDITIONABLE PROCEDURE "PSAK413"."SP_IFRS_INITIAL_PAYM_SCHD" (
P_DOWNLOAD_DATE IN DATE )
AS
V_CURRDATE       DATE;
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
   
   	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_INITIAL_PAYM_SCHD ' ; 
   	
	INSERT INTO IFRS_INITIAL_PAYM_SCHD(DOWNLOAD_DATE,MASTERID,CREATED_DATE)
	SELECT MAX(DOWNLOAD_DATE),MASTERID ,SYSDATE FROM IFRS_PAYM_SCHD_ALL 
	WHERE DOWNLOAD_DATE <= V_CURRDATE
	GROUP BY MASTERID;

END