CREATE TABLE IFRS9_BCA.GTMP_IFRS_EAD_RULES_CONFIG (
    PKID                  NUMBER(22),
    SYSCODE_EAD           VARCHAR2(22),
    EAD_RULE_NAME         NVARCHAR2(200),
    SEGMENTATION_ID       NUMBER(22),
    EAD_BALANCE           NVARCHAR2(500),
    CCF_FLAG              NUMBER(22),
    CCF_RULES_ID          NVARCHAR2(200),
    PREPAYMENT_FLAG       NUMBER(22),
    PREPAYMENT_RULES_ID   NVARCHAR2(200),
    ACTIVE_FLAG           NUMBER(22),
    IS_DELETE             NUMBER(22),
    CREATEDBY             NVARCHAR2(72) DEFAULT 'SYSTEM',
    CREATEDDATE           TIMESTAMP(8) DEFAULT SYSTIMESTAMP,
    CREATEDHOST           NVARCHAR2(60) DEFAULT 'LOCALHOST',
    UPDATEDBY             NVARCHAR2(72),
    UPDATEDDATE           TIMESTAMP(8),
    UPDATEDHOST           NVARCHAR2(60)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_EAD_RULES_CONFIG
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_EAD_RULES_CONFIG_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_EAD_RULES_CONFIG
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_EAD_RULES_CONFIG.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;