CREATE TABLE IFRS9_BCA.GTMP_IFRS_BUCKET_HEADER (
    PKID               NUMBER(22),
    SYSCODE_GROUP_BUCKET NVARCHAR2(22),
    BUCKET_GROUP       NVARCHAR2(60),
    BUCKET_DESCRIPTION NVARCHAR2(510),
    OPTION_GROUPING    NVARCHAR2(60),
    IS_DELETED         NUMBER(22) DEFAULT 0,
    CREATEDBY          VARCHAR2(36) DEFAULT 'SYSTEM',
    CREATEDDATE        DATE DEFAULT SYSDATE,
    CREATEDHOST        VARCHAR2(36) DEFAULT 'LOCALHOST',
    UPDATEDBY          VARCHAR2(36),
    UPDATEDDATE        DATE,
    UPDATEDHOST        VARCHAR2(30)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_BUCKET_HEADER
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_BUCKET_HEADER_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_BUCKET_HEADER
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_BUCKET_HEADER.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;