CREATE TABLE IFRS9_BCA.GTMP_IFRS_ECL_MODEL_DETAIL_PF (
    PKID             NUMBER(22),
    ECL_MODEL_ID     NUMBER(22),
    PF_SEGMENT_ID    NUMBER(22),
    LT_RULE_ID       NUMBER(22),
    SICR_RULE_ID     NUMBER(22),
    EFFECTIVE_DATE   DATE,
    CREATEDBY        NVARCHAR2(72) DEFAULT 'SYSTEM',
    CREATEDDATE      TIMESTAMP(8) DEFAULT SYSTIMESTAMP,
    CREATEDHOST      NVARCHAR2(60) DEFAULT 'LOCALHOST',
    UPDATEDBY        NVARCHAR2(72),
    UPDATEDDATE      TIMESTAMP(8),
    UPDATEDHOST      NVARCHAR2(60)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_ECL_MODEL_DETAIL_PF
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_ECL_MODEL_DETAIL_PF
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_ECL_MODEL_DETAIL_PF
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_ECL_MODEL_DETAIL_PF.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;