CREATE TABLE IFRS9_BCA.GTMP_IFRS_ECL_MODEL_DETAIL_PD (
    PKID             NUMBER(22),
    SYSCODE_PD       VARCHAR2(22),
    ECL_MODEL_ID     NUMBER(22),
    PD_MODEL_ID      NUMBER(22),
    PF_SEGMENT_ID    NUMBER(22),
    FL_MODEL_ID      NUMBER(22),
    PD_EFF_PERIOD    VARCHAR2(10),
    PD_DATE          DATE,
    CREATEDBY        NVARCHAR2(72) DEFAULT 'SYSTEM',
    CREATEDDATE      TIMESTAMP(8) DEFAULT SYSTIMESTAMP,
    CREATEDHOST      NVARCHAR2(60) DEFAULT 'LOCALHOST',
    UPDATEDBY        NVARCHAR2(72),
    UPDATEDDATE      TIMESTAMP(8),
    UPDATEDHOST      NVARCHAR2(60)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_ECL_MODEL_DETAIL_PD
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_ECL_MODEL_DETAIL_PD_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_ECL_MODEL_DETAIL_PD
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_ECL_MODEL_DETAIL_PD.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;