CREATE TABLE IFRS9_BCA.GTMP_IFRS_BUCKET_DETAIL (
    PKID               NUMBER(22),
    BUCKET_GROUP       VARCHAR2(30),
    BUCKET_ID          NUMBER(22),
    BUCKET_NAME        VARCHAR2(100),
    RANGE_START        NUMBER(22),
    RANGE_END          NUMBER(22),
    FLAG_DEFAULT       NUMBER(22),
    PD_DEFAULT         NUMBER(22),
    IMPAIRMENT_BUCKET  VARCHAR2(30),
    CREATEDBY          VARCHAR2(36) DEFAULT 'SYSTEM',
    CREATEDDATE        DATE DEFAULT SYSDATE,
    CREATEDHOST        VARCHAR2(36) DEFAULT 'LOCALHOST',
    UPDATEDBY          VARCHAR2(36),
    UPDATEDDATE        DATE,
    UPDATEDHOST        VARCHAR2(30)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_BUCKET_DETAIL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_BUCKET_DETAIL_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_BUCKET_DETAIL
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_BUCKET_DETAIL.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;