CREATE TABLE IFRS9_BCA.GTMP_IFRS_PD_RULES_CONFIG (
    PKID               NUMBER(22),
    SYSCODE_PD         VARCHAR2(22),
    PD_RULE_NAME       VARCHAR2(100),
    SEGMENTATION_ID    VARCHAR2(22),
    PD_METHOD          VARCHAR2(100),
    CALC_METHOD        VARCHAR2(100),
    HISTORICAL_DATA    NUMBER(22),
    EXPECTED_LIFE      NUMBER(22),
    BUCKET_GROUP       VARCHAR2(22),
    INCREMENT_PERIOD   NUMBER(22),
    ACTIVE_FLAG        NUMBER(22) DEFAULT 1,
    IS_NEW             NUMBER(22) DEFAULT 1,
    IS_DELETED         NUMBER(22) DEFAULT 0,
    CREATEDBY          VARCHAR2(36) DEFAULT 'SYSTEM',
    CREATEDDATE        DATE DEFAULT SYSDATE,
    CREATEDHOST        VARCHAR2(36) DEFAULT 'LOCALHOST',
    UPDATEDBY          VARCHAR2(36),
    UPDATEDDATE        DATE,
    UPDATEDHOST        VARCHAR2(30)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_PD_RULES_CONFIG
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_PD_RULES_CONFIG_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_PD_RULES_CONFIG
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_PD_RULES_CONFIG.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;