CREATE TABLE IFRS9_BCA.GTMP_IFRS_LGD_RULES_CONFIG (
    PKID               NUMBER(22),
    SYSCODE_LGD        NVARCHAR2(22),
    LGD_RULE_NAME      NVARCHAR2(100),
    SEGMENTATION_ID    NUMBER(22),
    WORKOUT_PERIOD     NUMBER(22),
    CUT_OFF_DATE       DATE,
    HISTORICAL_MONTH   NUMBER(22),
    CALC_METHOD        NVARCHAR2(40),
    METHOD             VARCHAR2(50),
    IS_NEW             NUMBER(22) DEFAULT 1,
    IS_DELETED         NUMBER(22) DEFAULT 0,
    CREATEDBY          NVARCHAR2(72) DEFAULT 'SYSTEM',
    CREATEDDATE        TIMESTAMP(8) DEFAULT SYSTIMESTAMP,
    CREATEDHOST        NVARCHAR2(60) DEFAULT 'LOCALHOST',
    UPDATEDBY          NVARCHAR2(72),
    UPDATEDDATE        TIMESTAMP(8),
    UPDATEDHOST        NVARCHAR2(60)
);


CREATE SEQUENCE IFRS9_BCA.SEQ_GTMP_IFRS_LGD_RULES_CONFIG
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER IFRS9_BCA.TRG_GTMP_IFRS_LGD_RULES_CONFIG_PKID
BEFORE INSERT ON IFRS9_BCA.GTMP_IFRS_LGD_RULES_CONFIG
FOR EACH ROW
WHEN (NEW.PKID IS NULL)
BEGIN
    SELECT IFRS9_BCA.SEQ_GTMP_IFRS_LGD_RULES_CONFIG.NEXTVAL
    INTO :NEW.PKID
    FROM DUAL;
END;