CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_EIL_MODEL (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'X'
)
AUTHID CURRENT_USER
IS
    V_CURRDATE    	DATE;
    V_EIL_MODEL_ID 	NUMBER := 0;
    V_STR_QUERY     CLOB;
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_COUNT         NUMBER;

	V_IFRS_EIL_MODEL VARCHAR2(100);
   
   -- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_EIL_MODEL';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        CLOB;
    V_RETURNROWS2   NUMBER;
BEGIN

    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
    
    ------------------------------------------------------------------
    -- Nama tabel target
    ------------------------------------------------------------------
   IF P_PRC = 'S' THEN 

        V_IFRS_EIL_MODEL := 'IFRS_EIL_MODEL_' || P_RUNID || ''; 
    ELSE 
        V_IFRS_EIL_MODEL := 'IFRS_EIL_MODEL'; 
    END IF;

	IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_EIL_MODEL', V_IFRS_EIL_MODEL);
    END IF;
	COMMIT;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;

	------------------------------------------------------------------
    -- AMBIL EIL MODEL ID
    ------------------------------------------------------------------
	EXECUTE IMMEDIATE 'SELECT PKID FROM IFRS_EIL_MODEL_HEADER WHERE IS_EOM = 1 AND IS_DELETE = 0 FETCH FIRST 1 ROW ONLY' INTO V_EIL_MODEL_ID;
	COMMIT;

	DBMS_OUTPUT.PUT_LINE('EIL_MODEL_ID: ' || V_EIL_MODEL_ID);
   
    ------------------------------------------------------------------
    -- BUILD DYNAMIC SQL
    -----------------------------------------------------------------
    V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') 
	AND EIL_MODEL_ID = :1';
     
    EXECUTE IMMEDIATE V_STR_QUERY USING V_EIL_MODEL_ID;
	COMMIT;

    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL || '
	(DOWNLOAD_DATE,
		EIL_MODEL_ID,
		EAD_RULE_ID,
		SUB_SEGMENT_EAD,
		SEGMENTATION_ID,
		LGD_RULE_ID,
		LGD_ME_MODEL_ID,
		SUB_SEGMENT_LGD,
		LGD_DATE,
		LGD_OVERRIDE_FLAG,
		PD_RULE_ID,
		PD_ME_MODEL_ID,
		SUB_SEGMENT_PD,
		PD_DATE,
		BUCKET_GROUP,
		EAD_BALANCE,
		EAD_BALANCE_INTEREST,
		LT_RULE_ID,
		LT_EFF_DATE,
		LT_OVERRIDE_FLAG,
		FLAG_VAS,
		MODEL_TYPE, 
		EAD_BALANCE_ADDITIONAL,
		EAD_BALANCE_INTEREST_ADDITIONAL,
		CREATEDBY, CREATEDDATE)
	SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS DOWNLOAD_DATE,
		A.PKID AS EIL_MODEL_ID,
		C.PKID AS EAD_RULE_ID,
		I.SEGMENT_NAME_LV3 AS SUB_SEGMENT_EAD,
		b.SEGMENTATION_ID AS SEGMENTATION_ID,
		D.LGD_RULE_ID AS LGD_RULE_ID,
		D.LGD_MODEL_ID AS LGD_ME_MODEL_ID,
		J.SEGMENT_NAME_LV3 AS SUB_SEGMENT_LGD,
		CASE WHEN D.EFF_DATE_OPTION = ''Current Month'' THEN TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Previous Month'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-1)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Last Year'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-12)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN D.EFF_DATE_OPTION = ''Selected Date'' THEN D.EFF_DATE END AS LGD_DATE,
		D.IS_OVERRIDE AS LGD_OVERRIDE_FLAG,
		E.PD_RULE_ID AS PD_RULE_ID,
		E.PD_MODEL_ID AS PD_ME_MODEL_ID,
		K.SEGMENT_NAME_LV3 AS SUB_SEGMENT_PD,
		CASE WHEN E.EFF_DATE_OPTION = ''Current Month'' THEN TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Previous Month'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-1)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Last Year'' THEN TO_DATE(''' || TO_CHAR(LAST_DAY(ADD_MONTHS(V_CURRDATE,-12)),'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			WHEN E.EFF_DATE_OPTION = ''Selected Date'' THEN E.EFF_DATE END AS PD_DATE ,
		H.BUCKET_GROUP AS BUCKET_GROUP,
		C.EAD_BALANCE AS EAD_BALANCE,
		CASE WHEN L.SEGMENT_NAME_LV2 LIKE ''%INVESTASI%'' THEN ''CASE WHEN BI_COLLECTABILITY IN (1,2) THEN MARGIN_PAST_DUE ELSE 0 END '' ELSE ''0'' END AS EAD_BALANCE_INTEREST,
		C.LIFETIME_RULE_ID AS LT_RULE_ID,
		B.LIFETIME_DATE AS LT_EFF_DATE,
		B.IS_OVERRIDE_LIFETIME AS LT_OVERRIDE_FLAG,
		CASE WHEN H.PD_METHOD = ''VAS'' THEN 1 ELSE 0 END AS FLAG_VAS,
		CASE WHEN D.LGD_RULE_ID = 0 AND E.PD_RULE_ID = 0 THEN 1 ELSE 0 END AS MODEL_TYPE,
		''0'' || CASE WHEN C.UNAMORTIZED_FEE_COST_FLAG = 1 THEN '' + NVL(UNAMORT_COST_AMT,0) + NVL(UNAMORT_FEE_AMT,0) + NVL(UNAMORT_OTHERS,0) '' ELSE '''' END || 
		CASE WHEN C.MARGIN_ACCRUED_FLAG = 1 THEN '' + CASE WHEN BI_COLLECTABILITY IN(1,2) THEN NVL(MARGIN_ACCRUED,0) ELSE 0 END '' ELSE '''' END AS EAD_BALANCE_ADDITIONAL,
		''0'' AS EAD_BALANCE_INTEREST_ADDITIONAL,
		''SP_IFRS_EIL_MODEL'' AS CREATEDBY,
		SYSDATE AS CREATEDDATE
	 FROM ' || V_TAB_OWNER || '.IFRS_EIL_MODEL_HEADER A
	  JOIN ' || V_TAB_OWNER || '.IFRS_EIL_MODEL_DETAIL_EAD B ON A.PKID = B.EIL_MODEL_ID
	   JOIN ' || V_TAB_OWNER || '.IFRS_EAD_RULES_CONFIG C ON B.EAD_RULE_ID = C.PKID
	  JOIN ' || V_TAB_OWNER || '.IFRS_EIL_MODEL_DETAIL_LGD D ON A.PKID = D.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = D.SEGMENTATION_ID
	  JOIN ' || V_TAB_OWNER || '.IFRS_EIL_MODEL_DETAIL_PD E ON A.PKID = E.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = E.SEGMENTATION_ID
	  JOIN ' || V_TAB_OWNER || '.IFRS_EIL_MODEL_DETAIL_PF F ON A.PKID = F.EIL_MODEL_ID
	   AND B.SEGMENTATION_ID = F.SEGMENTATION_ID
	    JOIN ' || V_TAB_OWNER || '.IFRS_LGD_RULES_CONFIG G ON D.LGD_RULE_ID = G.PKID
	    JOIN ' || V_TAB_OWNER || '.IFRS_PD_RULES_CONFIG H ON E.PD_RULE_ID  = H.PKID
	    JOIN ' || V_TAB_OWNER || '.IFRS_SEGMENTATION_MAPPING I ON C.SEGMENTATION_ID = I.PKID  
	    JOIN ' || V_TAB_OWNER || '.IFRS_SEGMENTATION_MAPPING J ON G.SEGMENTATION_ID = J.PKID
	    JOIN ' || V_TAB_OWNER || '.IFRS_SEGMENTATION_MAPPING K ON H.SEGMENTATION_ID = K.PKID 
		JOIN ' || V_TAB_OWNER || '.IFRS_SEGMENTATION_MAPPING L ON F.SEGMENTATION_ID = L.PKID 
	  WHERE A.PKID = :1';
	 
	DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING V_EIL_MODEL_ID;
	COMMIT;

	V_STR_QUERY := 'UPDATE ' || V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL || ' A 
		SET LGD = (SELECT LGD FROM ' || V_TAB_OWNER || '.IFRS_LGD_RESULT X WHERE A.LGD_DATE = X.EFF_DATE AND A.LGD_RULE_ID = X.LGD_RULE_ID)
		, LIFETIME = (SELECT LIFETIME FROM ' || V_TAB_OWNER || '.IFRS_LIFETIME_HEADER Y WHERE A.LT_EFF_DATE = Y.EFF_DATE AND A.LT_RULE_ID = Y.LIFETIME_RULE_ID ) 
		WHERE A.EIL_MODEL_ID = :1
		AND A.DOWNLOAD_DATE =  TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ';

	DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
	EXECUTE IMMEDIATE V_STR_QUERY USING V_EIL_MODEL_ID;
	COMMIT;
	

	-----------------------------
    -- LOG & INSERT FINAL DATA
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(v_currdate, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
	V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL;

    PSAK413.SP_IFRS_RESULT_PREV(v_currdate, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), p_RUNID);
    COMMIT;
END;