CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_INSERT_STG_PMA_DVC_HC
(
    P_RUNID         VARCHAR2,
    P_DOWNLOAD_DATE DATE,
    P_SYSCODE       VARCHAR2 DEFAULT '0',
    P_PRC           VARCHAR2 DEFAULT 'S'
)
AS
    -- DATE
    V_CURRDATE   DATE;
    V_PREVDATE   DATE;
    V_MODEL_ID   VARCHAR2(22);
    V_COUNT      NUMBER;

    -- QUERY
    V_STR_QUERY  CLOB;

    -- TABLE LIST
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1   VARCHAR2(100);
    V_TABLEINSERT2   VARCHAR2(100);
    V_TABLESELECT1   VARCHAR2(100);
    V_TABLEPDCONFIG  VARCHAR2(100);

    -- CONDITION / LOG
    V_RETURNROWS  NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST   VARCHAR2(100);
    V_COLUMNDEST  VARCHAR2(100);
    V_SPNAME      VARCHAR2(100);
    V_OPERATION   VARCHAR2(100);

    V_QUERYS      CLOB;

BEGIN

	-- set procedure name
    V_SPNAME := 'SP_IFRS_INSERT_STG_PMA_DVC_HC';
    
    ------------------------------------------------------------------------
    -- SET CURRDATE
    ------------------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE_AMORT ipda ;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
	
   
    V_PREVDATE := V_CURRDATE - 1;
    V_MODEL_ID := NVL(P_SYSCODE, '0');
   
    ------------------------------------------------------------------------
    -- SET TABLE NAMES
    ------------------------------------------------------------------------
    IF P_PRC = 'S' THEN
        V_TABLEINSERT1  := 'IFRS_STG_MASTER_ACCOUNT_' || P_RUNID;
    ELSE
        V_TABLEINSERT1  := 'IFRS_STG_MASTER_ACCOUNT';
    END IF;
   
    ------------------------------------------------------------------------
    -- LOG RUN_ID → Oracle tidak bisa CALL, cukup prosedur langsung
    ------------------------------------------------------------------------
    /*
    PSAK413.SP_IFRS_RUNNING_LOG
    (
        V_CURRDATE,
        V_SPNAME,
        P_RUNID,
        SYS_CONTEXT('USERENV','SID'),
        SYSDATE
    );
    COMMIT;
    */
   
    ------------------------------------------------------------------------
    -- DELETE EXISTING DATA--
    ------------------------------------------------------------------------
    V_STR_QUERY := '
            DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '
            WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
			AND SOURCE_PROCESS = ''CKPN_PMA_DVC_HC''
        ';

	EXECUTE IMMEDIATE V_STR_QUERY;
    --DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    COMMIT;   
      
    ------------------------------------------------------------------------
    -- INSERT DATA FROM CKPN_BSI--
    ------------------------------------------------------------------------
 	V_STR_QUERY := '
	INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '
	(
	 DOWNLOAD_DATE
	,DATA_SOURCE
	,BRANCH_CODE
	,MASTER_ACCOUNT_ID
	,ACCOUNT_NUMBER
	,CUSTOMER_NUMBER
	,CUSTOMER_NAME
	,FACILITY_NUMBER
	,PRODUCT_CODE
	,PRODUCT_TYPE
	,COMMITTED_FLAG
	,SEGMENT
	,COLLATERAL_VALUE_FOR_IMPAIR
	,KODE_JENIS_PENGGUNAAN
	,SEKTOR_INDUSTRI
	,KODE_SEKTOR_EKONOMI
	,CURRENCY
	,EXCHANGE_RATE
	,PLAFOND
	,MARGIN_RATE
	,OUTSTANDING
	,OUTSTANDING_MARGIN
	,ACCOUNT_STATUS
	,LOAN_START_DATE
	,LOAN_DUE_DATE
	,TENOR
	,MARGIN_CALCULATION_CODE
	,DAY_PAST_DUE
	,ORIGINAL_BI_COLLECTABILITY
	,BI_COLLECTABILITY
	,RESTRUCTURED_FLAG
	,RESTRUCTURE_DATE
	,DEFAULT_DATE
	,SOURCE_PROCESS
	,AYDA
	,DESC_JENIS_PENGGUNAAN
	,DIVISION_CODE
	,ACCRUED_MARGIN
	,MARGIN_PASTDUE
	,OUTSTANDING_PASTDUE
	,RATING_CODE
	,RATING_AGENCY
	)
	SELECT
	 FICMISDATE AS DOWNLOAD_DATE
	,DATA_SOURCE
	,KODECABANG AS BRANCH_CODE
	,DATA_SOURCE||''-''||NOMORREKENING AS MASTER_ACCOUNT_ID
	,NOMORREKENING AS ACCOUNT_NUMBER
	,NOMORNASABAH AS CUSTOMER_NUMBER
	,NAMANASABAH AS CUSTOMER_NAME
	,NULL AS FACILITY_NUMBER
	,LOANTYPECODE AS PRODUCT_CODE
	,NULL AS PRODUCT_TYPE
	,NULL AS COMMITTED_FLAG
	,NULL AS SEGMENT
	,NULL AS COLLATERAL_VALUE_FOR_IMPAIR
	,NULL AS KODE_JENIS_PENGGUNAAN
	,NULL AS SEKTOR_INDUSTRI
	,NULL AS KODE_SEKTOR_EKONOMI
	,JENISVALUTA AS CURRENCY
	,1 AS EXCHANGE_RATE
	,PLAFONAWAL AS PLAFOND
	,PERSENTASEIMBALANBULANLAPORAN AS MARGIN_RATE
	,JUMLAHBULANLAPORAN AS OUTSTANDING
	,NULL AS OUTSTANDING_MARGIN
	,''A'' AS ACCOUNT_STATUS
	,JANGKAWAKTUMULAI AS LOAN_START_DATE
	,JANGKAWAKTUJATUHTEMPO AS LOAN_DUE_DATE
	,NULL AS TENOR
	,NULL AS MARGIN_CALCULATION_CODE
	,TUNGGAKANHARI AS DAY_PAST_DUE
	,KUALITAS AS ORIGINAL_BI_COLLECTABILITY
	,KUALITAS AS BI_COLLECTABILITY
	,CASE WHEN SIFATPIUTANG in (1,5) then ''Y'' ELSE ''N'' END AS RESTRUCTURED_FLAG
	,NULL AS RESTRUCTURE_DATE
	,NULL AS DEFAULT_DATE
	,''CKPN_PMA_DVC_HC'' AS SOURCE_PROCESS
	,NULL AS AYDA
	,NULL AS DESC_JENIS_PENGGUNAAN
	,DIVISIPISAH AS DIVISION_CODE
	,NULL AS ACCRUED_MARGIN
	,TUNGGAKANMARGIN AS MARGIN_PASTDUE
	,TUNGGAKANPOKOK AS OUTSTANDING_PASTDUE
	,NULL AS RATING_CODE
	,NULL AS RATING_AGENCY
	FROM FORM12_SANDIRINCIANPIUTANGQARDH_RPT A
	WHERE FICMISDATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
	';	

 EXECUTE IMMEDIATE V_STR_QUERY;
 --DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
 COMMIT; 


END;
/
