CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_MASTER_ACCOUNT_PREV (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR2(22);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLESELECT2 VARCHAR2(100);
    V_TABLEPDCONFIG VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');
	V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, - 1));

    IF P_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'TMP_IFRS_MASTER_ACCOUNT_PREV_' || P_RUNID || '';
		V_TABLESELECT1 := 'IFRS_MASTER_ACCOUNT_MONTHLY_' || P_RUNID || '';
		V_TABLESELECT2 := 'IFRS_BUCKET_DETAIL_' || P_RUNID || '';
    ELSE 
        V_TABLEINSERT1 := 'TMP_IFRS_MASTER_ACCOUNT_PREV';
		V_TABLESELECT1 := 'IFRS_MASTER_ACCOUNT_MONTHLY';
		V_TABLESELECT2 := 'IFRS_BUCKET_DETAIL';
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE PROCESS
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1);
        
		IF V_COUNT > 0 THEN 
		 V_STR_QUERY := '';
         V_STR_QUERY := V_STR_QUERY || 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ';
        EXECUTE IMMEDIATE (V_STR_QUERY);
		END IF;

        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' AS SELECT * FROM ' || V_TAB_OWNER || '.TMP_IFRS_MASTER_ACCOUNT_PREV WHERE 0=1';
        EXECUTE IMMEDIATE (V_STR_QUERY);
    END IF;
	COMMIT;
    -------- ====== PRE SIMULATION TABLE ======

    -------- ====== BODY ======

    -- Delete logic
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || 'SELECT COUNT(*) FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '';
	EXECUTE IMMEDIATE V_STR_QUERY INTO V_COUNT;
	COMMIT;

	IF V_COUNT > 0 THEN 
	EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '';
	END IF;
    COMMIT;


    -- Insert IMA Prev
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
    INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' (
     DOWNLOAD_DATE  
	,MASTERID  
	,DATA_SOURCE  
	,PF_SEGMENT_ID 
	,GROUP_SEGMENT  
	,SEGMENT  
	,SUB_SEGMENT  
	,OUTSTANDING  
	,OUTSTANDING_EQV
	,OS_INTEREST  
	,ECL_AMOUNT  
	,ACCOUNT_STATUS  
	,CURRENCY  
	,IMPAIRED_FLAG  
	,IA_UNWINDING_AMOUNT  
	,IA_UNWINDING_SUM_AMOUNT  
	,BEGINNING_BALANCE  
	,ENDING_BALANCE  
	,LGD_RULE_ID  
	,LGD_SEGMENT  
	,FACILITY_NUMBER  
	,CUSTOMER_NUMBER  
	,ACCOUNT_NUMBER  
	,PRODUCT_TYPE  
	,PRODUCT_CODE  
	,EXCHANGE_RATE  
	,BRANCH_CODE  
	,GL_CONSTNAME  
	,APPLICATION_NO 
	,IAS_CLASS
	,RATING_CODE
	,RATING_AGENCY
	,RATING_ID
	,STAGE
	,ECL_MODEL_ID
    )
    SELECT 
     A.DOWNLOAD_DATE  
	,A.MASTERID  
	,A.DATA_SOURCE  
	,A.PF_SEGMENT_ID 
	,A.GROUP_SEGMENT  
	,A.SEGMENT  
	,A.SUB_SEGMENT  
	,A.OUTSTANDING  
	,A.OUTSTANDING * A.EXCHANGE_RATE  
	,A.OS_INTEREST
	,A.ECL_AMOUNT  
	,A.ACCOUNT_STATUS  
	,A.CURRENCY  
	,A.IMPAIRED_FLAG  
	,A.IA_UNWINDING_AMOUNT  
	,A.IA_UNWINDING_SUM_AMOUNT  
	,A.BEGINNING_BALANCE  
	,A.ENDING_BALANCE  
	,A.LGD_RULE_ID  
	,A.LGD_SEGMENT  
	,A.FACILITY_NUMBER  
	,A.CUSTOMER_NUMBER  
	,A.ACCOUNT_NUMBER  
	,A.PRODUCT_TYPE  
	,A.PRODUCT_CODE  
	,A.EXCHANGE_RATE  
	,A.BRANCH_CODE  
	,A.GL_CONSTNAME  
	,A.APPLICATION_NO
	,IAS_CLASS
	,RATING_CODE
	,RATING_AGENCY
	,B.BUCKET_ID
	,A.STAGE
	,A.ECL_MODEL_ID
    FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' A
    LEFT JOIN ' || V_TAB_OWNER || '.' || V_TABLESELECT2 || ' B ON ON A.BUCKET_GROUP = B.BUCKET_GROUP 
	WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_PREVDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')';
	EXECUTE IMMEDIATE (V_STR_QUERY);
	COMMIT;
    -------- ====== BODY ======

    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_SPNAME := 'SP_IFRS_MASTER_ACCOUNT_PREV';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS := 'SELECT * FROM ' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_PREVDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, V_RETURNROWS2, P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END;
/
