CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_LIFETIME_DATA (
 P_RUNID		 IN VARCHAR2 DEFAULT 'S_00000_0000',
 P_DOWNLOAD_DATE IN DATE, 
 P_SYSCODE		 IN VARCHAR2 DEFAULT '0', 
 P_PRC			 IN VARCHAR2 DEFAULT 'S'
) 
AUTHID CURRENT_USER
AS
	---- DATE   
    V_CURRDATE DATE; 
	V_EOMDATE DATE ;  

	---- PROCESS
	V_COUNT NUMBER;
	V_RULE_ID VARCHAR2(10);
	V_ID NUMBER DEFAULT 0; 
	V_MAX_ID NUMBER DEFAULT 0; 
	V_DATADATE VARCHAR(20); 
    ---- QUERY  
    V_STR_QUERY CLOB;
	V_STR_SQL_RULE CLOB;

	---- TABLE LIST 
	V_TAB_OWNER CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1 VARCHAR2(100);
    V_TABLEINSERT2 VARCHAR2(100);
    V_TABLESELECT1 VARCHAR2(100);
    V_TABLECONFIG VARCHAR2(100);
	V_TABLE_NAME VARCHAR2(100);

    ---- CONDITION
    V_RETURNROWS NUMBER;
    V_RETURNROWS2 NUMBER;
    V_TABLEDEST VARCHAR2(100);
    V_COLUMNDEST VARCHAR2(100);
    V_SPNAME VARCHAR2(100);
    V_OPERATION VARCHAR2(100);
 
BEGIN
   
	
    V_SPNAME := 'SP_IFRS_LIFETIME_DATA';
    V_DATADATE := TO_CHAR(V_CURRDATE, 'YYYY-MM-DD');
    
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CASE 
        		WHEN CURRDATE = LAST_DAY(CURRDATE) THEN CURRDATE
        		ELSE LAST_DAY(ADD_MONTHS(CURRDATE, -1))
    		END, LAST_DAY(CURRDATE)
        INTO V_CURRDATE,V_EOMDATE 
        FROM PSAK413.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
  
    IF P_PRC = 'S' THEN 
        V_TABLECONFIG := 'GTMP_IFRS_LIFETIME_RULES_CONFIG_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_LIFETIME_RULE_DATA_' || P_RUNID || ''; 
    	 	V_TABLEINSERT1 := 'IFRS_LIFETIME_DATA_' || P_RUNID || ''; 
    ELSE 
        V_TABLECONFIG := 'GTMP_IFRS_LIFETIME_RULES_CONFIG';
        V_TABLESELECT1 := 'IFRS_LIFETIME_RULE_DATA'; 
    	 	V_TABLEINSERT1 := 'IFRS_LIFETIME_DATA' ; 
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SPNAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== PRE SIMULATION TABLE ======
	----TABLE CONFIG
    IF P_PRC = 'S' THEN
		SELECT COUNT(*) INTO V_COUNT
		FROM ALL_TABLES
		WHERE OWNER = V_TAB_OWNER 
		 AND TABLE_NAME = UPPER(V_TABLEINSERT1); 
        
		IF V_COUNT > 0 THEN 
		 V_STR_QUERY := '';
         V_STR_QUERY := V_STR_QUERY || 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' ';
        EXECUTE IMMEDIATE (V_STR_QUERY);
		END IF;

        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '
		 AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LIFETIME_DATA  A 
		WHERE EXISTS (SELECT * FROM ' || V_TAB_OWNER || '.IFRS_LIFETIME_RULES_CONFIG X WHERE A.LIFETIME_RULE_ID = X.PKID)    ';
        EXECUTE IMMEDIATE (V_STR_QUERY);
        COMMIT ;
        
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_' || V_TABLEINSERT1 || ' ON ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || '(LIFETIME_RULE_ID , MASTERID)';
  
    END IF;
	COMMIT;
        
 EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_LIFETIME_RULES_CONFIG' ; 
	 
    V_STR_QUERY := 'INSERT INTO GTMP_IFRS_LIFETIME_RULES_CONFIG
               SELECT * FROM IFRS_LIFETIME_RULES_CONFIG
               WHERE  IS_DELETED = 0 AND START_HISTORICAL_DATE <= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') 
				AND (  
                 UPPER(TRIM(SYSCODE_LIFETIME)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = 0 
               )'; 
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;

   	V_STR_QUERY := 
	'DELETE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A  
	 WHERE    LAST_DAY(LIFETIME_START_DATE) = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')  
AND EXISTS (SELECT 1 FROM GTMP_IFRS_LIFETIME_RULES_CONFIG  X WHERE A.LIFETIME_RULE_ID = X.PKID) ' ; 
	
	
	
EXECUTE IMMEDIATE V_STR_QUERY;

COMMIT; 
	
   
	V_STR_QUERY := 
	'UPDATE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A  SET ACCOUNT_STATUS = ''A'' , CLOSE_DATE = NULL  ' || 
	' WHERE    CLOSE_DATE >= TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')  AND ACCOUNT_STATUS = ''C''  
AND EXISTS (SELECT 1 FROM GTMP_IFRS_LIFETIME_RULES_CONFIG  X WHERE A.LIFETIME_RULE_ID = X.PKID) ' ; 
	
	
	
EXECUTE IMMEDIATE V_STR_QUERY;

COMMIT; 
	 
	V_STR_QUERY :=
    'INSERT INTO  ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' (' ||
    '  LIFETIME_START_DATE, LIFETIME_RULE_ID, FACILITY_NUMBER, MASTERID, ' ||
    '  CUSTOMER_NUMBER, LOAN_START_DATE, LOAN_DUE_DATE, CLOSE_DATE, ' ||
    '  ACCOUNT_STATUS, CREATED_BY, CREATED_DATE' ||
    ') ' ||
    'SELECT ' ||
    '  A.LOAN_DUE_DATE, B.PKID , A.FACILITY_NUMBER, A.MASTERID, ' ||
    '  A.CUSTOMER_NUMBER, A.LOAN_START_DATE, A.LOAN_DUE_DATE, NULL, ' ||
    '  A.ACCOUNT_STATUS, ''' || V_SPNAME || ''', SYSDATE ' ||
    'FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' ' || ' A ' ||
    ' JOIN GTMP_IFRS_LIFETIME_RULES_CONFIG B ON A.RULE_ID = B.SEGMENTATION_ID ' || 
	' WHERE A.ACCOUNT_STATUS = ''A'' ' ||
    '  AND LAST_DAY(A.LOAN_DUE_DATE) = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ' ||
    '  AND NOT EXISTS (SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || 
    ' X WHERE  B.PKID = X.LIFETIME_RULE_ID AND A.MASTERID = X.MASTERID)  ' ; 
	

EXECUTE IMMEDIATE V_STR_QUERY;
COMMIT ;

	V_STR_QUERY := 
	'UPDATE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A SET A.ACCOUNT_STATUS = ''C'' , A.CLOSE_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'')   ' || 
	' WHERE NOT EXISTS (SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' X 
	JOIN GTMP_IFRS_LIFETIME_RULES_CONFIG Y ON X.RULE_ID = Y.SEGMENTATION_ID 
	WHERE A.MASTERID = X.MASTERID AND  Y.PKID = A.LIFETIME_RULE_ID)
	AND A.ACCOUNT_STATUS = ''A''
	AND A.LIFETIME_START_DATE <=  TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ' ;
	

	
 DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
EXECUTE IMMEDIATE V_STR_QUERY;
COMMIT; 

    -------- ====== LOG ======
    V_TABLEDEST := V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_STR_QUERY := 'SELECT * FROM ' || V_TABLEINSERT1 || ' WHERE LIFETIME_START_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_STR_QUERY, V_SPNAME, nvl(V_RETURNROWS2,0), P_RUNID);
	COMMIT;
    -------- ====== RESULT ======

END;
/
