CREATE OR REPLACE PROCEDURE PSAK413.SP_shu_check
AS 
BEGIN
	
/*
/*
 * 
 * 
CREATE TABLE IFRS_FL_MODEL_RESULT AS 
WITH CTE AS (
SELECT DISTINCT  "workflow_header_draft_pkid" MODEL_ID, "PdName" PD_NAME
FROM "NTT_RISK_MODELLING"."VW_MODEL_COEFFICIENT"@DBCONFIGLINK A)
SELECT A."workflow_header_draft_pkid" MODEL_ID, 
	A."model_seq" MODEL_SEQ,
	C.PKID AS PD_RULE_ID,
	A."avg_pdrate_mape" AVG_MAPE,
	A."pdrate_mape" MAPE,
	A."adj_r_squared" ADJ_R 
FROM "NTT_RISK_MODELLING"."VW_MODEL_RESULT"@DBCONFIGLINK A 
	JOIN CTE B ON B.MODEL_ID = A."workflow_header_draft_pkid"
	JOIN  IFRS_PD_RULES_CONFIG  C ON B.PD_NAME = C.PD_RULE_NAME 
WHERE  "model_name" LIKE '%1003%' OR "model_name" LIKE '%SMOOTH%'

INSERT INTO IFRS_FL_MODEL_DATA (MODEL_ID, MODEL_SEQ, COEFF_NAME, COEFF_VAL, PD_RULE_ID)
SELECT  A."workflow_header_draft_pkid" MODEL_ID, A."model_seq" MODEL_SEQ,
"coeff_name", "estimate_val", b.PKID 
FROM "NTT_RISK_MODELLING"."VW_MODEL_COEFFICIENT"@DBCONFIGLINK A
	JOIN  IFRS_PD_RULES_CONFIG  B ON A."PdName" = b.PD_RULE_NAME 
WHERE  "model_name" LIKE '%1003%' OR "model_name" LIKE '%SMOOTH%'
 
 SELECT *
 FROM IFRS_FL_MODEL_DATA  
 WHERE   IS_SELECTED = 1
-- PD_RULE_ID  IN (12, 10,8,7,13,5,71)
 --	AND MODEL_ID  = PD_RULE_ID 
 ORDER BY PD_RULE_ID  , MODEL_SEQ 
 
  
 
TRUNCATE TABLE IFRS_PD_NORMINV;
 
INSERT INTO IFRS_PD_NORMINV  (EFF_DATE, PD_RULE_ID, BUCKET_FROM, BUCKET_TO, NORMINV_MMULT)
 
WITH cte AS (
SELECT EFF_DATE , PD_RULE_ID ,BUCKET_FROM , BUCKET_TO , MMULT 
FROM IFRS_PD_MAA_MMULT  A 
	JOIN VW_IFRS_MAX_BUCKET B ON A.BUCKET_GROUP = B.BUCKET_GROUP
WHERE EFF_DATE  = '31 DEC 2025'
	AND FL_SEQ  = 0 
	AND BUCKET_FROM  <> B.MAX_BUCKET_ID AND BUCKET_TO  <> 1 
)  , cte2 AS (
SELECT A.EFF_DATE, A.PD_RULE_ID, A.BUCKET_FROM, A.BUCKET_TO,  
	 (SUM(B.MMULT)) MMULT
FROM CTE A 
	JOIN CTE B ON A.PD_RULE_ID = B.PD_RULE_ID AND A.BUCKET_FROM = B.BUCKET_FROM 
WHERE A.BUCKET_TO <= B.BUCKET_TO 
GROUP BY  A.EFF_DATE,A.PD_RULE_ID, A.BUCKET_FROM, A.BUCKET_TO 
) 
SELECT A.EFF_DATE, A.PD_RULE_ID, A.BUCKET_FROM, A.BUCKET_TO,  FN_NORMINV( MMULT  )
FROM cte2  a  
 

TRUNCATE TABLE IFRS_PD_NORMDIST;

 

INSERT INTO IFRS_PD_NORMDIST (EFF_DATE, PD_RULE_ID , MODEL_ID, MODEL_SEQ, scenario_no,seq, BUCKET_FROM, BUCKET_TO,NORMDIST_MMULT )

WITH 
cte2 as (

selecT a.pd_rule_id,a.model_id, a.model_seq,scenario_no , EXTRACT(YEAR FROM me_period) - 2026 seq, max(a.coeff_val )+ sum(b.coeff_val * c.me_val ) odr
from IFRS_FL_MODEL_DATA a 
	join IFRS_FL_MODEL_DATA b on a.model_id = b.model_id and a.model_seq = b.model_seq 
	join IFRS_MEV_FORECAST C ON B.COEFF_NAme = c.me_code 
where EXTRACT(MONTH FROM ME_PERIOD) = 12
	and a.coeff_name = 'const' and b.coeff_name <> 'const' 
	and nvl(a.is_selected,0) = 1 
 group by a.model_id, a.model_seq, EXTRACT(YEAR FROM me_period) - 2026, scenario_no, a.pd_rule_id
),
CTE AS (
SELECT a.EFF_DATE , a.PD_RULE_ID , b.MODEL_ID, b.MODEL_SEQ  ,b.scenario_no,b.seq,
	a.BUCKET_FROM , a.BUCKET_TO ,FN_NORMDIST(a.NORMINV_MMULT +  b.odr)  NORMDIST_MMULT
FROM IFRS_PD_NORMINV A 
	join cte2 b on a.pd_rule_id = b.pd_rule_id
), CTE3 AS (
SELECT A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,a.scenario_no, a.seq, A.BUCKET_FROM, A.BUCKET_TO ,  A.NORMDIST_MMULT, 
	LEAD( A.NORMDIST_MMULT,1,0) OVER (PARTITION BY A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,a.scenario_no, a.seq, A.BUCKET_FROM 
		ORDER BY A.BUCKET_TO) LEADNORM
FROM CTE  A) , 
CTE4 AS (
SELECT A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,a.scenario_no, a.seq, A.BUCKET_FROM, A.BUCKET_TO ,  
MAX(A.NORMDIST_MMULT) - SUM(NVL(B.NORMDIST_MMULT,0) - NVL(B.LEADNORM,0) )
FROM CTE3  A 
 LEFT JOIN CTE3 B ON A.EFF_DATE = B.EFF_DATE AND A.PD_RULE_ID = B.PD_RULE_ID
		AND A.MODEL_ID = B.MODEL_ID AND A.MODEL_SEQ = B.MODEL_SEQ 
		AND A.BUCKET_FROM = B.BUCKET_FROM 
		AND A.scenario_no = B.scenario_no
		AND A.SEQ = B.SEQ
		AND A.BUCKET_TO < B.BUCKET_TO 
GROUP BY A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, A.BUCKET_FROM, A.BUCKET_TO , a.scenario_no, a.seq
) 
SELECT * FROM CTE4 A 
 
-- PD NORMDIST BUCKET TO 1 

INSERT INTO IFRS_PD_NORMDIST
SELECT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,SCENARIO_NO,SEQ, A.BUCKET_FROM, 1  ,  1- SUM(A.NORMDIST_MMULT) 
FROM IFRS_PD_NORMDIST A 
GROUP BY A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, A.BUCKET_FROM, SCENARIO_NO,SEQ


-- PD NORMDIST BUCKET DEFAULT 


INSERT INTO IFRS_PD_NORMDIST
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ, 2, 1  ,0 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID IN (8,71)
UNION ALL 
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ,2, 2  ,1
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID IN (8,71)
UNION ALL 
SELECT DISTINCT   A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ,5, 1  ,0 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID NOT IN (8,71)
UNION ALL 
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ,5, 2  ,0 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID NOT IN (8,71)
UNION ALL 
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ,5, 3  ,0 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID NOT IN (8,71)
UNION ALL 
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,SCENARIO_NO,SEQ, 5, 4  ,0 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID NOT IN (8,71)
UNION ALL 
SELECT DISTINCT  A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, SCENARIO_NO,SEQ,5, 5  ,1 
FROM IFRS_PD_NORMDIST A 
WHERE PD_RULE_ID NOT IN (8,71)
  ORDER BY PD_RULE_ID
   

-- CPD   
  
TRUNCATE TABLE IFRS_PD_MMULT_FL ;

INSERT INTO IFRS_PD_MMULT_FL (EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SCENARIO_NO,SEQ, BUCKET_FROM, BUCKET_TO,MMULT)
	SELECT EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SCENARIO_NO,SEQ,BUCKET_FROM, BUCKET_TO,NORMDIST_MMULT 
	FROM IFRS_PD_NORMDIST 
	WHERE SEQ = 0 ; 


DECLARE V_SEQ NUMBER ; 
 
BEGIN  
	
	V_SEQ := 0 ;

	WHILE V_SEQ < 30 
	LOOP 
		INSERT INTO IFRS_PD_MMULT_FL (EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SCENARIO_NO,SEQ, BUCKET_FROM, BUCKET_TO,MMULT)
		SELECT A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ,A.SCENARIO_NO, V_SEQ + 1,  A.BUCKET_FROM , B.BUCKET_TO ,  SUM(A.MMULT * B.NORMDIST_MMULT ) 
		FROM IFRS_PD_MMULT_FL A 
			JOIN IFRS_PD_NORMDIST B ON A.EFF_DATE = B.EFF_DATE AND A.PD_RULE_ID = B.PD_RULE_ID 
				AND A.MODEL_ID = B.MODEL_ID 
				AND A.MODEL_SEQ = B.MODEL_SEQ 
				AND B.BUCKET_FROM = A.BUCKET_TO  
				AND A.SCENARIO_NO = B.SCENARIO_NO
		WHERE A.SEQ = V_SEQ
			AND B.SEQ =    V_SEQ +1 
		GROUP BY A.EFF_DATE, A.PD_RULE_ID, A.MODEL_ID, A.MODEL_SEQ, a.BUCKET_FROM, b.BUCKET_TO ,1 ,A.SCENARIO_NO ; 
		
	      V_SEQ := V_SEQ + 1;

		
	END LOOP;	
END ;  



-- MPD 

TRUNCATE TABLE IFRS_PD_MMULT_FL_MPD

INSERT INTO IFRS_PD_MMULT_FL_MPD (EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ,scenario_no,seq , BUCKET_FROM, BUCKET_TO, MPD)
SELECT EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ,scenario_no, seq ,BUCKET_FROM, BUCKET_TO, 
	MMULT - LAG(MMULT,1,0) OVER (PARTITION BY EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, BUCKET_FROM, scenario_no  ORDER BY SEQ ) MPD  
FROM IFRS_PD_MMULT_FL
WHERE BUCKET_TO = CASE WHEN PD_RULE_ID IN (8,71) THEN 2 ELSE 5 END 
ORDER BY PD_RULE_ID, BUCKET_FROM , SEQ 


 -- PD TERM STRUCTURE PER SKENARIO

 
 TRUNCATE TABLE IFRS_PD_TERM_FL
 
INSERT INTO IFRS_PD_TERM_FL (EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SCENARIO_NO, SEQ, BUCKET_FROM, BUCKET_TO,FL_YEAR,FL_MONTH, PD)
WITH CTE (MON) AS (
SELECT 1 AS MON FROM DUAL 
UNION ALL 
SELECT MON+1  
FROM CTE 
WHERE MON < 12 
) 
SELECT EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ,  SCENARIO_NO, 
	((SEQ * 12) + (MON  -1)) SEQ,
	BUCKET_FROM, BUCKET_TO,SEQ + 1 FL_YEAR,MON , 
	1- POWER(1 - MPD, (MON/ 12)) - CASE WHEN MON = 1 THEN 0 ELSE 1- POWER(1 - MPD, ((MON-1) / 12)) END
FROM IFRS_PD_MMULT_FL_MPD A 
	JOIN CTE B ON 1=1 
	  ;
	 
	 TRUNCATE TABLE IFRS_PD_TERM_FL_WEIGHT

INSERT INTO IFRS_PD_TERM_FL_WEIGHT  (EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SEQ, BUCKET_FROM, BUCKET_TO,FL_YEAR,FL_MONTH, PD)
SELECT EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ,   SEQ, 
	BUCKET_FROM, BUCKET_TO,FL_YEAR,FL_MONTH, SUM(CASE WHEN SCENARIO_NO = 2 THEN 0.5 ELSE 0.25 END * PD ) PD 
FROM IFRS_PD_TERM_FL A 
GROUP BY EFF_DATE, PD_RULE_ID, MODEL_ID, MODEL_SEQ, SEQ, BUCKET_FROM, BUCKET_TO,FL_YEAR,FL_MONTH
 


INSERT INTO PSAK413.IFRS_PD_TERM_STRUCTURE (
     EFF_DATE,
    BASE_DATE,
    SCENARIO_NO,
    PD_RULE_ID,
    PD_RULE_NAME,
    MODEL_ID,
    BUCKET_GROUP,
    BUCKET_ID,
    FL_SEQ,
    FL_YEAR,
    FL_MONTH,
    PD,
    PD_OVERRIDE,
    PD_METHOD,
    CREATEDBY,
    CREATEDDATE,
    CREATEDHOST,
    UPDATEDBY,
    UPDATEDDATE,
    UPDATEDHOST
)  
SELECT EFF_DATE , LAST_DAY(ADD_MONTHS(EFF_DATE , 12 * FL_YEAR)) BASE_DATE , 0 AS SCENARIO_NO , PD_RULE_ID , '' ,
MODEL_ID , 'DPD_5_2' , BUCKET_FROM , SEQ, FL_YEAR, FL_MONTH, PD, PD, 'MAA', 'MIGRASI', SYSDATE, 'LOCALHOST', NULL, NULL, NULL   
FROM IFRS_PD_TERM_FL_WEIGHT


 
	WITH CTE AS (
	SELECT PD_RULE_ID ,SUM(MMULT)  PD,
		MAX(CASE WHEN BUCKET_FROM = 1 THEN MMULT ELSE 0 END) B1,
		MAX(CASE WHEN BUCKET_FROM = 2 THEN MMULT ELSE 0 END) B2,
		MAX(CASE WHEN BUCKET_FROM = 3 THEN MMULT ELSE 0 END) B3,
		MAX(CASE WHEN BUCKET_FROM = 4 THEN MMULT ELSE 0 END) B4,
		MAX(CASE WHEN BUCKET_FROM = 5 THEN MMULT ELSE 0 END) B5
	FROM IFRS_PD_MAA_MMULT
	WHERE EFF_DATE  = '31 DEC 2025'
		AND BUCKET_TO  = CASE WHEN PD_RULE_ID  NOT IN (8,71) THEN 5 ELSE 2 END
		AND FL_SEQ  = 0 
		GROUP BY PD_RULE_ID 
	),CTE2 AS (
	 SELECt PD_RULE_ID , MODEL_ID , MODEL_SEQ  , BUCKET_FROM ,
	 	SUM(CASE WHEN SCENARIO_NO = 2 THEN 0.5 ELSE 0.25 END * MPD)   AFL
	 FROM IFRS_PD_MMULT_FL_MPD
	 WHERE SEQ = 0  
	 GROUP BY  PD_RULE_ID , MODEL_ID , MODEL_SEQ , BUCKET_FROM  ),
	 CTE3 AS (
	 SELECt PD_RULE_ID , MODEL_ID , MODEL_SEQ ,
	 	SUM(AFL)  AFL,
	 	MAX(CASE WHEN BUCKET_FROM = 1 THEN AFL ELSE 0 END) AFL1,
		MAX(CASE WHEN BUCKET_FROM = 2 THEN AFL ELSE 0 END) AFL2,
		MAX(CASE WHEN BUCKET_FROM = 3 THEN AFL ELSE 0 END) AFL3,
		MAX(CASE WHEN BUCKET_FROM = 4 THEN AFL ELSE 0 END) AFL4,
		MAX(CASE WHEN BUCKET_FROM = 5 THEN AFL ELSE 0 END) AFL5
	 FROM CTE2 
	 GROUP BY  PD_RULE_ID , MODEL_ID , MODEL_SEQ  
	 
	 ),
	 cte4 AS (
	  SELECT MODEL_ID, model_seq,
       LISTAGG(COEFF_NAME , '+') WITHIN GROUP (ORDER BY COEFF_NAME ) AS FORMULA
FROM IFRS_FL_MODEL_DATA
WHERE COEFF_NAME  <> 'const'
GROUP BY model_seq,MODEL_ID 
	 )
	 
	 SELECT B.PD_RULE_ID, d.PD_RULE_NAME  ,B.MODEL_SEQ,c.formula, B.AFL / A.PD AS FL_IMPACT , B1,AFL1, B2,AFL2, B3,AFL3,B4,AFL4,B5,AFL5 
	 FROM CTE A JOIN CTE3 B ON A.PD_RULE_ID = B.PD_RULE_ID 
	 	JOIN cte4 c ON b.model_id = c.model_id AND    b.model_seq = c.model_seq
	 	JOIN ifrs_pd_rules_config d ON a.pd_rule_id = d.PKID 
	 	 --WHERE b.pd_rule_id = 4 --  AND b.model_seq = 999
	 ORDER BY A.PD_RULE_ID, b.MODEL_ID, b.MODEL_SEQ 
	  


 
 
 
	 
*/	 
	INSERT INTO X_IMA_NONPAYM (masterid)
	SELECT 1 FROM dual  ; 
	
END;
/
