CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_EIL_GENERATE_IMA (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS 
    V_CURRDATE       DATE;
    V_DATADATE       VARCHAR2(20);
    V_TABLE_NAME     VARCHAR2(50);
	V_PREVDATE       DATE;
    V_COUNT          NUMBER;
	V_MODEL_ID       NUMBER;

    V_STR_QUERY     CLOB;

    -- TABLE NAMES
    V_TAB_OWNER     CONSTANT 		VARCHAR2(30) := 'PSAK413';
    V_TMP_QRY      				    VARCHAR2(100);
    V_TMP_PD  						VARCHAR2(100);
    V_IFRS_EIL_IMA					VARCHAR2(100);
    V_IFRS_EIL_MODEL                VARCHAR2(100);
    V_IFRS_MASTER_ACCOUNT_MONTHLY   VARCHAR2(100);
    V_EIL_MODEL_ID				 	NUMBER;
    V_MAXRN			 				NUMBER;
    V_IFRS_SEGMENTATION_MAPPING 	VARCHAR2(100);
    V_TABLEPDCONFIG					VARCHAR2(100);

    -- LOG / RESULT
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100) := 'SP_IFRS_EIL_GENERATE_IMA';
    V_OPERATION     VARCHAR2(100);
    V_QUERYS        VARCHAR2(8000);
    V_RETURNROWS2   NUMBER;
    
    V_STR_SQL        CLOB;
    V_STR_SQL_RULE   CLOB;
    V_RULE_ID        VARCHAR2(250);
    V_ID             NUMBER := 0;
    V_MAX_ID         NUMBER := 0;
    V_SEQUENCE       VARCHAR2(50);
    
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_PREVDATE := LAST_DAY(ADD_MONTHS(V_CURRDATE, -1));
    V_MODEL_ID := NVL(P_SYSCODE, '0');

    -- CHOOSE TABLE NAMES BASED ON MODE
    IF P_PRC = 'S' THEN 
        V_TMP_PD  						:= 'TMP_PD_' || P_RUNID;
        V_IFRS_EIL_IMA					:= 'IFRS_EIL_IMA_' || P_RUNID;
        V_TMP_QRY      					:= 'TMP_QRY_' || P_RUNID;
        V_IFRS_EIL_MODEL                := 'IFRS_EIL_MODEL_' || P_RUNID;
        V_IFRS_MASTER_ACCOUNT_MONTHLY   := 'IFRS_MASTER_ACCOUNT_MONTHLY_' || P_RUNID;
    ELSE
        V_TMP_PD  						:= 'TMP_PD';
        V_IFRS_EIL_IMA					:= 'IFRS_EIL_IMA';
        V_TMP_QRY      					:= 'TMP_QRY';
        V_IFRS_EIL_MODEL                := 'IFRS_EIL_MODEL';
        V_IFRS_MASTER_ACCOUNT_MONTHLY   := 'IFRS_MASTER_ACCOUNT_MONTHLY';
    END IF;

    IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_PD', V_TMP_PD);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_EIL_IMA', V_IFRS_EIL_IMA);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_QRY', V_TMP_QRY);
    END IF;

    -------- RECORD RUN_ID --------
    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, CURRENT_DATE); 
	COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA;
    COMMIT;

    -- AMBIL EIL_MODEL_ID YANG AKTIF ATAU PERSIS P_MODEL_ID
    EXECUTE IMMEDIATE 'SELECT PKID FROM IFRS_EIL_MODEL_HEADER WHERE PKID = :1 OR (IS_EOM = 1 AND IS_DELETE = 0) FETCH FIRST 1 ROW ONLY' INTO V_EIL_MODEL_ID USING V_MODEL_ID;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_TMP_QRY;

    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA || '
    (
        DOWNLOAD_DATE, MASTERID, GROUP_SEGMENT, SEGMENT, SUB_SEGMENT, SEGMENTATION_ID,
        ACCOUNT_NUMBER, CUSTOMER_NUMBER, LT_RULE_ID, DAY_PAST_DUE_CIF, DAY_PAST_DUE,
        RESTRUCTURE_FLAG, DATA_SOURCE, PRODUCT_CODE, PRODUCT_TYPE, PRODUCT_GROUP,
        IS_IMPAIRED, IFRS9_CLASS, PD_SEGMENT, LGD_SEGMENT, EAD_SEGMENT,
        BUCKET_GROUP, BUCKET_ID, STAGE, REVOLVING_FLAG, EIR,
        OUTSTANDING, UNAMORT_COST_AMT, UNAMORT_FEE_AMT, FAIR_VALUE_AMOUNT, PLAFOND,
        EIL_MODEL_ID, EAD_RULE_ID, EAD_TYPE, LGD_RULE_ID, LGD_ME_MODEL_ID,
        PD_RULE_ID, PD_ME_MODEL_ID, CURRENCY, CREATEDBY, IMPAIRED_FLAG,
        CUSTOMER_NAME, ACCOUNT_STATUS, EIL_AMOUNT, RATING_CODE, EXCHANGE_RATE,
        LOAN_START_DATE, LOAN_DUE_DATE, FLAG_VAS, BI_COLLECTABILITY,
        LIFETIME, EAD_BALANCE, EAD_MARGIN,
        EAD_BALANCE_ADDITIONAL, EAD_BALANCE_INTEREST_ADDITIONAL, MARGIN_ACCRUED
    )
    SELECT
        A.DOWNLOAD_DATE,
        A.MASTERID,
        A.GROUP_SEGMENT,
        A.SEGMENT,
        A.SUB_SEGMENT,
        A.SEGMENTATION_ID,
        A.ACCOUNT_NUMBER,
        NVL(A.CUSTOMER_NUMBER,''''),
        NVL(A.LT_RULE_ID,0),
        A.DPD_CIF,
        A.DAY_PAST_DUE,
        A.RESTRUCTURE_FLAG,
        A.DATA_SOURCE,
        A.PRODUCT_CODE,
        A.PRODUCT_TYPE,
        A.PRODUCT_GROUP,
        A.IS_IMPAIRED,
        A.IFRS9_CLASS,
        M.SUB_SEGMENT_PD,
        M.SUB_SEGMENT_LGD,
        M.SUB_SEGMENT_EAD,
        A.BUCKET_GROUP,

        CASE 
            WHEN D.BUCKET_ID > NVL(G.NO_BUCKET,0) THEN D.BUCKET_ID
            ELSE NVL(G.NO_BUCKET,0)
        END AS BUCKET_ID,

        A.STAGE,
        A.REVOLVING_FLAG,
        NVL(A.EIR, A.MARGIN_RATE),
        A.OUTSTANDING,
        NVL(A.UNAMORT_COST_AMT,0),
        NVL(A.UNAMORT_FEE_AMT,0),
        NVL(A.FAIR_VALUE_AMOUNT,0),
        NVL(A.PLAFOND,0),

        M.EIL_MODEL_ID,
        A.EAD_RULE_ID,
        M.EAD_TYPE,
        NVL(A.LGD_RULE_ID,0),
        NVL(M.LGD_ME_MODEL_ID,0),
        A.PD_RULE_ID,
        A.PD_ME_MODEL_ID,

        A.CURRENCY,
        A.CREATEDBY,
        A.IMPAIRED_FLAG,
        A.CUSTOMER_NAME,
        A.ACCOUNT_STATUS,
        NVL(A.EIL_AMOUNT,0),
        A.RATING_CODE,
        NVL(A.EXCHANGE_RATE,0),
        A.LOAN_START_DATE,
        A.LOAN_DUE_DATE,
        M.FLAG_VAS,
        A.BI_COLLECTABILITY,

        CASE 
            WHEN LAST_DAY(NVL(A.LOAN_DUE_DATE, DATE ''1990-01-31'')) 
                <= LAST_DAY(A.DOWNLOAD_DATE)
            THEN NVL(A.LIFETIME,0)
            ELSE MONTHS_BETWEEN(
                    LAST_DAY(NVL(A.LOAN_DUE_DATE, DATE ''1990-01-31'')),
                    LAST_DAY(A.DOWNLOAD_DATE)
                )
        END AS LIFETIME,

        NVL(A.EAD_AMOUNT,0),
        NVL(M.EAD_BALANCE_INTEREST,0) AS EAD_BALANCE_INTEREST,
        NVL(M.EAD_BALANCE_ADDITIONAL,0) AS EAD_BALANCE_ADDITIONAL,
        0 AS EAD_BALANCE_INTEREST_ADDITIONAL,
        A.MARGIN_ACCRUED
    FROM ' || V_TAB_OWNER || '.' || V_IFRS_MASTER_ACCOUNT_MONTHLY || ' A
    JOIN ' || V_TAB_OWNER || '.IFRS_SEGMENTATION_MAPPING B ON A.SEGMENTATION_ID = B.PKID
    JOIN ' || V_TAB_OWNER || '.' || V_IFRS_EIL_MODEL || ' M ON A.SEGMENTATION_ID = M.SEGMENTATION_ID
    AND M.DOWNLOAD_DATE = A.DOWNLOAD_DATE AND M.EIL_MODEL_ID = ' || V_EIL_MODEL_ID || '
    LEFT JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_HEADER C ON A.BUCKET_GROUP = C.BUCKET_GROUP
    LEFT JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_DETAIL D ON C.BUCKET_GROUP = D.BUCKET_GROUP
    AND (
            CASE
                WHEN C.OPTION_GROUPING = ''DPD_ACCT'' THEN A.DAY_PAST_DUE
                WHEN C.OPTION_GROUPING = ''DPD_CIF''  THEN A.DPD_CIF
                WHEN C.OPTION_GROUPING = ''BIC''      THEN A.BI_COLLECTABILITY
            END
        BETWEEN D.RANGE_START AND D.RANGE_END
    )
    LEFT JOIN ' || V_TAB_OWNER || '.VW_IFRS_MAX_BUCKET F ON C.BUCKET_GROUP = F.BUCKET_GROUP
    LEFT JOIN (
        SELECT DOWNLOAD_DATE, MASTERID, MAX(NO_BUCKET) NO_BUCKET
        FROM ' || V_TAB_OWNER || '.LIST_NASABAH_RESTRU_BENCANA
        GROUP BY DOWNLOAD_DATE, MASTERID
    ) G ON A.MASTERID = G.MASTERID
    AND A.DOWNLOAD_DATE = G.DOWNLOAD_DATE
    WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
    AND B.SEGMENT_TYPE = ''PORTFOLIO''
    AND A.ACCOUNT_STATUS = ''A''
    AND A.IAS_CLASS = ''A''
    AND NVL(A.IFRS9_CLASS,'' '') <> ''FVTPL''
    AND C.BUCKET_GROUP IS NOT NULL
    AND NVL(A.IMPAIRED_FLAG,''C'') = ''C'' ';

    DBMS_OUTPUT.PUT_LINE('GENERATE IMA - QUERY: ' || V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    -----------------------------
    -- LOG & INSERT FINAL DATA
    -----------------------------
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_EIL_IMA;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
	V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_EIL_IMA;

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;