CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_INITIAL_PAYM_SCHD (
P_DOWNLOAD_DATE IN DATE )
AS
V_CURRDATE       DATE;
BEGIN
	-- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
   
   	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTEMP_IMA_FILTER';

	INSERT INTO GTEMP_IMA_FILTER(MASTERID,SEGMENT)
	SELECT IMA.MASTERID, IMA.SEGMENT
	FROM IFRS_MASTER_ACCOUNT IMA
	LEFT JOIN TBLM_COMMONCODEDETAIL CD
	    ON CD.COMMONCODE = 'BUS-504'
	    AND CD.VALUE1 = IMA.SEGMENT
	WHERE 
	    IMA.DOWNLOAD_DATE = V_CURRDATE
	    AND IMA.ACCOUNT_STATUS = 'A'
	    AND CD.VALUE1 IS NULL;
   
	COMMIT;

   	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_INITIAL_PAYM_SCHD ' ; 
   	
	INSERT INTO IFRS_INITIAL_PAYM_SCHD (DOWNLOAD_DATE, MASTERID, CREATED_DATE)
	SELECT 
	    MAX(P.DOWNLOAD_DATE),
	    P.MASTERID,
	    SYSDATE
	FROM IFRS_PAYM_SCHD_ALL P
	INNER JOIN GTEMP_IMA_FILTER T
	    ON T.MASTERID = P.MASTERID
	WHERE 
	    P.DOWNLOAD_DATE <= V_CURRDATE
	GROUP BY 
	    P.MASTERID;
	
	COMMIT;

END;