CREATE OR REPLACE PROCEDURE PSAK413.SP_EIL_SEQ
AS
--declare
dtcurr DATE;
dtprev DATE;
BEGIN
	
	dtcurr := '30-APR-2026';

--	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_RESULT_DETAIL';
--  	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_RESULT_HEADER';
--  	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EAD_RESULT';
   	--EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_EIL_IMA';
  
--    COMMIT;
--	WHILE  dtcurr <= '31-DEC-2025' -- '31-DEC-2025'
--	LOOP 
		
--		SP_IFRS_EAD_RULES_CONFIG();
--
--	 	SP_IFRS_EIL_MODEL_HEADER();
--	 
--		SP_IFRS_EIL_MODEL_DETAIL_EAD();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_PF();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_PD();
--	
--		SP_IFRS_EIL_MODEL_DETAIL_LGD();
--	
--		SP_IFRS_EIL_MODEL('S_00000_0000',dtcurr,'0','M');
		
--		SP_IFRS_IMP_INITIAL_UPDATE('S_00000_0000',dtcurr,'0','M');
--
--		SP_IFRS_UPDATE_STAGE(dtcurr);

--		SP_IFRS_INITIAL_PAYM_SCHD(dtcurr);
	
		SP_IFRS_PREPARE_EAD_RESULT('S_00000_0000',dtcurr,'0','M');
		
		SP_IFRS_EIL_GENERATE_IMA('S_00000_0000',dtcurr,'0','M');
		
		SP_IFRS_EAD_RESULT('S_00000_0000',dtcurr,'0','M');
		
		SP_IFRS_EIL_RESULT_DETAIL('S_00000_0000',dtcurr,'0','M');
	
	 	SP_IFRS_EIL_RESULT_HEADER('S_00000_0000',dtcurr,'0','M');	
	 	
--	 	SP_IFRS_UPDATE_IMA_RESULT('S_00000_0000', dtcurr, 'M');
	 
--	 	SP_IFRS_MASTER_ACCOUNT_MONTHLY('S_00000_0000',dtcurr,'0','M');


--	dbms_output.put_line(dtcurr);
--	dtcurr := LAST_DAY(ADD_MONTHS(dtcurr, 1));
--	
--	END LOOP;

END;