CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MIG_TTC(V_EFF_DATE DATE)
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

    INSERT INTO TMP_IFRS_PD_RUNNING_DATE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        BUCKET_GROUP,
        MIG_LOSS_BUCKET,
        HISTORICAL_DATA,
        CUT_OFF_DATE
    )
    SELECT
        V_EFF_DATE AS EFF_DATE,
		LAST_DAY(ADD_MONTHS(V_EFF_DATE, A.INCREMENT_PERIOD * -1)) AS BASE_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.MIG_LOSS_BUCKET,
		A.HISTORICAL_DATA,
		NVL(A.CUT_OFF_DATE,'01 JAN 1900')
    FROM IFRS_PD_RULES_CONFIG A
    WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MIG'
	AND A.DERIVED_PD_MODEL IS NULL;

    COMMIT;

    DELETE IFRS_PD_MIG_TTC
    WHERE EFF_DATE = V_EFF_DATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE)
    AND MODEL_ID = 0;

    COMMIT;

    INSERT INTO IFRS_PD_MIG_TTC
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        TTC
    )
    SELECT
        A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        0 MODEL_ID,
        A.BUCKET_GROUP,
        A.BUCKET_ID,
        B.FLOW_TO_LOSS_AVG
    FROM IFRS_PD_MIG_FLOW_TO_LOSS A
    JOIN
        (
            SELECT V_EFF_DATE EFF_DATE,
                C.PD_RULE_ID,
                C.BUCKET_GROUP,
                C.BUCKET_ID,
                AVG(C.FLOW_TO_LOSS) AS FLOW_TO_LOSS_AVG
            FROM IFRS_PD_MIG_FLOW_TO_LOSS C
            JOIN TMP_IFRS_PD_RUNNING_DATE D
            ON C.PD_RULE_ID = D.PD_RULE_ID
                AND C.EFF_DATE BETWEEN ADD_MONTHS(V_EFF_DATE, -1 * D.HISTORICAL_DATA) AND V_EFF_DATE
                AND C.EFF_DATE >= D.CUT_OFF_DATE
            GROUP BY C.PD_RULE_ID,
                C.BUCKET_GROUP,
                C.BUCKET_ID
        ) B
    ON A.PD_RULE_ID = B.PD_RULE_ID
        AND A.BUCKET_ID = B.BUCKET_ID
        AND A.EFF_DATE = B.EFF_DATE
    ORDER BY A.PD_RULE_ID, A.BUCKET_ID;

    COMMIT;

    --Insert into IFRS_PD_TERM_STRUCTURE using TTC for PD without forward looking
    DELETE IFRS_PD_TERM_STRUCTURE
    WHERE EFF_DATE = V_EFF_DATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE)
    AND MODEL_ID = 0;

    COMMIT;

    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE
    )
    SELECT A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        B.PD_RULE_NAME,
        0 MODEL_ID,
        A.BUCKET_GROUP,
        A.BUCKET_ID,
        1 FL_SEQ,
        1 FL_YEAR,
        1 FL_MONTH,
        A.EFF_DATE FL_DATE,
        TTC PD,
        TTC PRODUCTION_PD,
        TTC OVERRIDE_PD,
        'M' PRC_FLAG,
        'YEAR' TM_TYPE
    FROM IFRS_PD_MIG_TTC A
    JOIN IFRS_PD_RULES_CONFIG B
    ON A.PD_RULE_ID = B.PKID
    AND A.MODEL_ID = 0
    JOIN TMP_IFRS_PD_RUNNING_DATE C
    ON A.PD_RULE_ID = C.PD_RULE_ID
    AND A.EFF_DATE = C.EFF_DATE;

    COMMIT;

END;