CREATE OR REPLACE PROCEDURE SP_IFRS_PD_VAS_PIT(V_EFF_DATE DATE)
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	-- GET PD_RULE_ID FOR VASICEK METHOD
	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        EFF_DATE,
        PD_RULE_ID,
        BUCKET_GROUP
	)
	SELECT
	    v_EFF_DATE AS EFF_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='VAS'
	AND DERIVED_PD_MODEL IS NULL;

	COMMIT;

	DELETE IFRS_PD_VAS_PIT
	WHERE EFF_DATE = v_EFF_DATE
	AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

	COMMIT;

	INSERT INTO IFRS_PD_VAS_PIT
	(
		EFF_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_ID,
		FL_YEAR,
		PIT
	)
	SELECT A.EFF_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.BUCKET_ID,
		C.FL_YEAR,
		CASE WHEN A.PD != 1 THEN
		   GREATEST(FN_R_NORMSDIST((FN_R_NORMSINV(PD)-SQRT(ASSET_CORRELATION)*Z_SCORE)/SQRT(1-ASSET_CORRELATION)),0.0005)
		ELSE
            1
        END
	FROM IFRS_PD_VAS A
	JOIN IFRS_PD_VAS_CORRELATION B
	ON A.EFF_DATE = B.EFF_DATE
	AND A.EFF_DATE = v_EFF_DATE
	AND A.PD_RULE_ID = B.PD_RULE_ID
	AND A.BUCKET_ID = B.BUCKET_ID
	JOIN IFRS_PD_VAS_ME_PROJECTION C
	ON A.EFF_DATE = C.EFF_DATE
	;

	COMMIT;
END;