CREATE OR REPLACE PROCEDURE SP_IFRS_PD_VAS_MARGINAL(V_EFF_DATE DATE)
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	-- GET PD_RULE_ID FOR VASICEK METHOD
	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        EFF_DATE,
        PD_RULE_ID,
        BUCKET_GROUP
	)
	SELECT
	    v_EFF_DATE AS EFF_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='VAS'
	AND DERIVED_PD_MODEL IS NULL;

	COMMIT;

    --Insert into IFRS_PD_TERM_STRUCTURE
    DELETE IFRS_PD_TERM_STRUCTURE
    WHERE EFF_DATE = v_EFF_DATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE)
    AND MODEL_ID = 0;

    COMMIT;

    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE
    )
    SELECT A.EFF_DATE,
        A.EFF_DATE BASE_DATE,
        A.PD_RULE_ID,
        B.PD_RULE_NAME,
        0 MODEL_ID,
        A.BUCKET_GROUP,
        A.BUCKET_ID,
        A.FL_YEAR FL_SEQ,
        A.FL_YEAR FL_YEAR,
        12 FL_MONTH,
        ADD_MONTHS(A.EFF_DATE, A.FL_YEAR * 12) FL_DATE,
        A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0) PD,
        A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0) PRODUCTION_PD,
        A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0) OVERRIDE_PD,
        'M' PRC_FLAG,
        'YEAR' TM_TYPE
    FROM IFRS_PD_VAS_CUMULATIVE A
    JOIN IFRS_PD_RULES_CONFIG B
    ON A.EFF_DATE = v_EFF_DATE
    AND A.PD_RULE_ID = B.PKID
    LEFT JOIN IFRS_PD_VAS_CUMULATIVE C
        ON A.EFF_DATE = C.EFF_DATE
        AND A.PD_RULE_ID = C.PD_RULE_ID
        AND A.BUCKET_ID = C.BUCKET_ID
        AND (A.FL_YEAR - 1) = C.FL_YEAR
    ORDER BY A.PD_RULE_ID, A.FL_YEAR, A.BUCKET_ID;

    COMMIT;

    /*
    --Add PD term structure for BR Group Bucket
    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE
    )
    SELECT A.EFF_DATE,
        A.EFF_DATE BASE_DATE,
        CASE WHEN A.PD_RULE_ID = 42 THEN
            23
        ELSE
            24
        END PD_RULE_ID,
        B.PD_RULE_NAME,
        0 MODEL_ID,
        F.BUCKET_GROUP,
        F.BUCKET_ID,
        A.FL_YEAR FL_SEQ,
        A.FL_YEAR FL_YEAR,
        12 FL_MONTH,
        ADD_MONTHS(A.EFF_DATE, A.FL_YEAR * 12) FL_DATE,
        AVG(A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0)) PD,
        AVG(A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0)) PRODUCTION_PD,
        AVG(A.CUMULATIVE_PD - NVL(C.CUMULATIVE_PD,0)) OVERRIDE_PD,
        'M' PRC_FLAG,
        'YEAR' TM_TYPE
    FROM IFRS_PD_VAS_CUMULATIVE A
    JOIN IFRS_PD_RULES_CONFIG B
    ON A.EFF_DATE = v_EFF_DATE
    AND A.PD_RULE_ID = B.PKID
    AND A.PD_RULE_ID IN (42, 43)
    JOIN IFRS_BUCKET_DETAIL D
    ON A.BUCKET_GROUP = D.BUCKET_GROUP
    AND A.BUCKET_ID = D.BUCKET_ID
    JOIN IFRS_MASTER_RATING_BANK E
    ON D.IMPAIRMENT_BUCKET = E.STANDARD_AND_POORS
    JOIN IFRS_BUCKET_DETAIL F
    ON E.CLASSIFICATION = CASE WHEN F.BUCKET_ID <= 7 THEN
                            'Investment Grade'
                        ELSE
                            'Non Investment Grade'
                        END
    AND F.BUCKET_GROUP  = 'BR9_1'
    LEFT JOIN IFRS_PD_VAS_CUMULATIVE C
        ON A.EFF_DATE = C.EFF_DATE
        AND A.PD_RULE_ID = C.PD_RULE_ID
        AND A.BUCKET_ID = C.BUCKET_ID
        AND (A.FL_YEAR - 1) = C.FL_YEAR
    GROUP BY A.EFF_DATE,
        A.PD_RULE_ID,
        B.PD_RULE_NAME,
        F.BUCKET_GROUP,
        F.BUCKET_ID,
        A.FL_YEAR
    ORDER BY A.PD_RULE_ID, A.FL_YEAR, F.BUCKET_ID;

    COMMIT;
    */
END;