CREATE OR REPLACE PROCEDURE SP_IFRS_PD_TM_SCENARIO_DATA(V_EFF_DATE DATE)
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_SCENARIO_DATA';
    -- ================================
	-- SELECT DATA INTO TABLE PROCESS
	-- ================================
	INSERT INTO TMP_SCENARIO_DATA
	(
        DOWNLOAD_DATE,
        RULE_ID,
        RULE_TYPE,
        MASTERID,
        GROUP_SEGMENT,
        SEGMENT,
        SUB_SEGMENT,
        RATING_CODE,
        DAY_PAST_DUE,
        BI_COLLECTABILITY,
        WRITEOFF_FLAG,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        EXCHANGE_RATE,
        IMPAIRED_FLAG,
        OUTSTANDING,
        KEY_TMP_IMA
	)
	SELECT A.DOWNLOAD_DATE,
		  B.PKID RULE_ID,
		  A.RULE_TYPE,
		  A.MASTERID,
		  A.GROUP_SEGMENT,
		  A.SEGMENT,
		  A.SUB_SEGMENT,
		  A.RATING_CODE,
		  A.DAY_PAST_DUE,
		  A.BI_COLLECTABILITY,
		  A.WRITEOFF_FLAG,
		  A.ACCOUNT_NUMBER,
		  A.ACCOUNT_STATUS,
		  A.CUSTOMER_NUMBER,
		  A.CUSTOMER_NAME,
		  A.EXCHANGE_RATE,
		  A.IMPAIRED_FLAG,
		  A.OUTSTANDING,
		  CASE WHEN B.CALC_METHOD IN ('CNOC', 'COS', 'CVS') THEN
                A.CUSTOMER_NUMBER
            WHEN B.CALC_METHOD IN ('ANOA', 'AOS', 'AVS') THEN
                A.ACCOUNT_NUMBER
            ELSE
                TO_CHAR(A.MASTERID)
          END KEY_TMP_IMA
	FROM GTMP_IFRS_SCENARIO_DATA A
	JOIN IFRS_PD_RULES_CONFIG B
	ON A.RULE_ID = B.SEGMENTATION_ID
	AND B.PD_METHOD = 'MIG'
	AND NVL(B.IS_DELETED,0) = 0
	AND NVL(B.ACTIVE_FLAG,1) = 1;
--	AND ACCOUNT_STATUS != 'C'; -- EXCLUDE CLOSE ACCOUNT FROM POPULATION DATA || Updated 14 Aug 2018 by SHELILA

	COMMIT;

	-- ================================================
	-- INSERT INTO PD_SCENARIO_DATA FROM SCENARIO_DATA
	-- ================================================
	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_PD_SCENARIO_DATA';

	INSERT INTO IFRS_PD_SCENARIO_DATA
	(
	  EFF_DATE
	  , PD_RULE_ID
	  , RULE_ID
	  , BUCKET_GROUP
	  , MASTERID
	  , ACCOUNT_NUMBER
	  , CUSTOMER_NUMBER
	  , CUSTOMER_NAME
	  , PD_UNIQUE_ID
	  , PD_METHOD
	  , CALC_METHOD
	  , CALC_AMOUNT
	  , BUCKET_ID
	  , OUTSTANDING
	  , ACCOUNT_STATUS
	  , IMPAIRED_FLAG
	  , IS_IMPAIRED
	  , WRITEOFF_FLAG
	 )
	 SELECT B.DOWNLOAD_DATE
	   , A.PKID
	   , A.SEGMENTATION_ID
	   , A.BUCKET_GROUP
	   , B.MASTERID
	   , B.ACCOUNT_NUMBER
	   , B.CUSTOMER_NUMBER
	   , B.CUSTOMER_NAME
	   , B.KEY_TMP_IMA AS PD_UNIQUE_ID
	   , A.PD_METHOD
	   , A.CALC_METHOD
	   , CASE WHEN A.CALC_METHOD = 'MNOA' THEN /*Add New Calc Method By YY 20180708*/
			1
		 WHEN A.CALC_METHOD = 'ANOA' THEN
			 CASE WHEN B.MASTERID = MAX(B.MASTERID) OVER (PARTITION BY A.PKID,B.DOWNLOAD_DATE,B.ACCOUNT_NUMBER) THEN
			 		   1
				  ELSE 0
			 END
		 WHEN A.CALC_METHOD = 'CNOC' THEN
			 CASE WHEN B.MASTERID = MAX(B.MASTERID) OVER (PARTITION BY A.PKID,B.DOWNLOAD_DATE,B.CUSTOMER_NUMBER) THEN
			 		   1
				  ELSE 0
			 END
		 --WHEN A.CALC_METHOD IN ('CVS', 'AVS') THEN
			--B.FAIR_VALUE_AMOUNT * B.EXCHANGE_RATE
		 ELSE
			B.OUTSTANDING * B.EXCHANGE_RATE
		 END CALC_AMOUNT
         /*
       , CASE WHEN B.ACCOUNT_STATUS='W' THEN D.MAX_BUCKET_ID
         ELSE
            C.BUCKET_ID
         END BUCKET_ID
       */
       , CASE WHEN C.BUCKET_ID > D.MAX_BUCKET_ID THEN
            D.MAX_BUCKET_ID
         ELSE
            C.BUCKET_ID
         END BUCKET_ID
	   , B.OUTSTANDING * B.EXCHANGE_RATE OUTSTANDING
	   , B.ACCOUNT_STATUS
	   , B.IMPAIRED_FLAG
	   , 0 AS IS_IMPAIRED
	   , B.WRITEOFF_FLAG
	 FROM IFRS_PD_RULES_CONFIG A
	 JOIN TMP_SCENARIO_DATA B
	 ON A.PKID = B.RULE_ID
	 LEFT JOIN VW_IFRS_BUCKET C
	 ON C.BUCKET_GROUP=A.BUCKET_GROUP
	  AND
	  (
	   (   -- DPD AND BI COLLECT FOR RETAIL
		CASE WHEN C.OPTION_GROUPING = 'DPD' THEN
		 B.DAY_PAST_DUE
		WHEN C.OPTION_GROUPING = 'BIC' THEN
		 TO_NUMBER(B.BI_COLLECTABILITY)
		WHEN C.OPTION_GROUPING = 'DLQ' THEN
         TO_NUMBER(B.RATING_CODE)
		END >= C.RANGE_START
		AND
		CASE WHEN C.OPTION_GROUPING = 'DPD' THEN
		 B.DAY_PAST_DUE
		WHEN C.OPTION_GROUPING = 'BIC' THEN
		 TO_NUMBER(B.BI_COLLECTABILITY)
		WHEN C.OPTION_GROUPING = 'DLQ' THEN
         TO_NUMBER(B.RATING_CODE)
		END <= C.RANGE_END
	   )
	   OR
	   (  -- INTERNAL RATING AND EXTERNAL RATING FOR CORPORATE
		C.OPTION_GROUPING IN ('IR','ER') AND C.BUCKET_NAME = B.RATING_CODE
	   )
	  )
	 JOIN VW_IFRS_MAX_BUCKET D
	 ON D.BUCKET_GROUP = C.BUCKET_GROUP
	 --LEFT JOIN TMP_IFRS_MASTER_DATA_PROFILING E
	 --on E.KEY_PROFILE = B.KEY_TMP_IMA
	 --and E.FIRST_DEFAULT_DATE = B.DOWNLOAD_DATE
	 ;

    COMMIT;
END;