CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MIG_FLOWRATE(V_EFF_DATE DATE)
AS
BEGIN
	-- =================
	-- Get PD Rule ID
	-- =================
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        PD_RULE_ID,
        BUCKET_GROUP,
        HISTORICAL_DATA,
        POPULATION_MONTH,
        EFF_DATE,
        BASE_DATE
	)
	SELECT A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.HISTORICAL_DATA,
		A.POPULATION_MONTH,
		V_EFF_DATE AS EFF_DATE,
        ADD_MONTHS(V_EFF_DATE, A.INCREMENT_PERIOD * -1) AS BASE_DATE
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MIG'
	AND A.DERIVED_PD_MODEL IS NULL;

	COMMIT;

	DELETE IFRS_PD_MIG_FLOWRATE
	WHERE EFF_DATE = V_EFF_DATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

    COMMIT;

	-- =========================
	-- Get Percentage from ENR
	-- =========================
	INSERT INTO IFRS_PD_MIG_FLOWRATE
	(
        EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_FROM,
		BUCKET_TO,
		FLOWRATE
	)
   SELECT DISTINCT
        A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        A.BUCKET_GROUP,
        A.BUCKET_FROM,
        A.BUCKET_TO,
        CASE WHEN B.TOTAL = 0 THEN
            0
        ELSE
            CAST(A.CALC_AMOUNT AS FLOAT) / CAST(B.TOTAL AS FLOAT)
        END FLOWRATE
    FROM IFRS_PD_MIG_ENR A
    JOIN
        (
            SELECT PD_RULE_ID,
                BUCKET_FROM,
                SUM(CALC_AMOUNT) AS TOTAL
            FROM IFRS_PD_MIG_ENR
            WHERE EFF_DATE = V_EFF_DATE
            GROUP BY PD_RULE_ID, BUCKET_FROM
        ) B
    ON A.PD_RULE_ID = B.PD_RULE_ID
        AND A.BUCKET_FROM = B.BUCKET_FROM
    JOIN TMP_IFRS_PD_RUNNING_DATE C
    ON A.PD_RULE_ID = C.PD_RULE_ID
        AND A.EFF_DATE = C.EFF_DATE
    WHERE A.BUCKET_TO > 0
    ORDER BY A.PD_RULE_ID, A.BUCKET_FROM, A.BUCKET_TO;

    COMMIT;

END;