CREATE OR REPLACE FUNCTION FN_INT_30_ACT (CALC_IDAYS NUMBER,OS NUMBER,INTS NUMBER ,STARTS IN DATE,ENDS IN DATE, INCREMENTS NUMBER)
RETURN NUMBER
AS
	IDAYSTOTAL NUMBER   ;
	INTEREST NUMBER;
	LD_YEAR_START DATE;
	LD_YEAR_END DATE;
	DAYS_IN_YEAR1 NUMBER;
	DAYS_IN_YEAR2 NUMBER;
	DATEDIF NUMBER;


BEGIN
	LD_YEAR_START:=TO_DATE('31-12-'|| EXTRACT (YEAR FROM STARTS),'DD-MM-YYYY');
	LD_YEAR_END:=TO_DATE('31-12-'|| EXTRACT (YEAR FROM ENDS),'DD-MM-YYYY');
	DAYS_IN_YEAR1:=LD_YEAR_START-TO_DATE('31-12-'|| (EXTRACT (YEAR FROM STARTS)-1),'DD-MM-YYYY');
	DAYS_IN_YEAR2:=LD_YEAR_END-TO_DATE('31-12-'|| (EXTRACT (YEAR FROM ENDS)-1),'DD-MM-YYYY');
	idaysTotal:= FN_CNT_DAYS_30_360(STARTS,ENDS);


	if CALC_IDAYS=0
	THEN
      IF EXTRACT (YEAR FROM STARTS)= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=INTS/100*OS*(INCREMENTS*30)/DAYS_IN_YEAR1;
      END IF;

      IF EXTRACT (YEAR FROM STARTS)!= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=(INTS/100*OS*(LD_YEAR_START-STARTS)/DAYS_IN_YEAR1)+
              (INTS/100*OS*((INCREMENTS*30)-(LD_YEAR_START-STARTS))/DAYS_IN_YEAR2);
      END IF;

	ELSE if CALC_IDAYS=1
	THEN
      IF EXTRACT (YEAR FROM STARTS)= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=INTS/100*OS*idaysTotal/DAYS_IN_YEAR1;
      END IF;
      IF EXTRACT (YEAR FROM STARTS)!= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=(INTS/100*OS*(LD_YEAR_START-STARTS)/DAYS_IN_YEAR1)+
              (INTS/100*OS*(idaysTotal-(LD_YEAR_START-STARTS))/DAYS_IN_YEAR2);
      END IF;

	ELSE
      IF EXTRACT (YEAR FROM STARTS)= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=INTS/100*OS*idaysTotal/DAYS_IN_YEAR1;
      END IF;
      IF EXTRACT (YEAR FROM STARTS)!= EXTRACT(YEAR FROM ENDS)
      THEN
        INTEREST:=(INTS/100*OS*(LD_YEAR_START-STARTS)/DAYS_IN_YEAR1)+
              (INTS/100*OS*(idaysTotal-(LD_YEAR_START-STARTS))/DAYS_IN_YEAR2);
      END IF;
	END IF;

  END IF;
RETURN INTEREST;
END;