CREATE OR REPLACE FUNCTION FN_ISNUMERIC (p_string IN VARCHAR2)
   RETURN NUMBER
IS
   v_new_num NUMBER;
BEGIN
   v_new_num := TO_NUMBER(p_string);
   RETURN 1;

EXCEPTION
WHEN VALUE_ERROR THEN
   RETURN 0;
END;