CREATE OR REPLACE FUNCTION FN_INT_ACT_ACT (OS NUMBER,INTS NUMBER ,STARTS IN DATE,ENDS IN DATE)
RETURN NUMBER
AS
    IDAYSTOTAL NUMBER  ;
		INTEREST NUMBER;
BEGIN
  INTEREST:=0;
  IDAYSTOTAL:= ENDS-STARTS;


  WITH CTE (OS,INT_RATE,ENDDATE,BOM,EOM,DAYSINT,SALDODAYS,YEARINDAYS) AS (
  SELECT OS AS OS,
         INTS AS INT_RATE,
         ENDS AS ENDDATE,
         STARTS AS BOM,
         CASE WHEN LAST_DAY(STARTS)<=ENDS THEN LAST_DAY(STARTS) ELSE ENDS END AS EOM,
         (CASE WHEN LAST_DAY(STARTS)<=ENDS THEN LAST_DAY(STARTS) ELSE ENDS END)-STARTS AS DAYSINT,
         IDAYSTOTAL - ((CASE WHEN LAST_DAY(STARTS)<=ENDS THEN LAST_DAY(STARTS) ELSE ENDS END)-STARTS) AS SALDODAYS,
         (ADD_MONTHS (LAST_DAY(STARTS),12-(EXTRACT (MONTH FROM STARTS))) ) - (ADD_MONTHS(LAST_DAY(STARTS),EXTRACT (MONTH FROM STARTS)*-1)) AS YEARINDAYS
  FROM DUAL
  UNION ALL
  SELECT AA.OS AS OS,
         AA.INT_RATE AS INT_RATE,
         AA.ENDDATE AS ENDDATE,
         (AA.EOM+1) AS BOM,
         LAST_DAY(ADD_MONTHS(AA.EOM,1)) AS EOM,
         CASE WHEN SALDODAYS - ((CASE WHEN LAST_DAY(ADD_MONTHS(AA.EOM,1)) <=ENDDATE THEN LAST_DAY(ADD_MONTHS(AA.EOM,1))
                                     ELSE AA.ENDDATE
                                END)-AA.EOM) <0 THEN SALDODAYS
              ELSE (CASE WHEN LAST_DAY(ADD_MONTHS(AA.EOM,1))<= AA.ENDDATE THEN LAST_DAY(ADD_MONTHS(AA.EOM,1))
                         ELSE AA.ENDDATE
                    END)-AA.EOM
          END AS DAYSINT,
          CASE WHEN AA.SALDODAYS - ((CASE WHEN LAST_DAY(ADD_MONTHS(AA.EOM,1)) <= AA.ENDDATE THEN LAST_DAY(ADD_MONTHS(AA.EOM,1)) ELSE AA.ENDDATE END) -AA.EOM)<0 THEN TO_NUMBER(0,'9')
               ELSE AA.SALDODAYS - ((CASE WHEN LAST_DAY(ADD_MONTHS(AA.EOM,1)) <= AA.ENDDATE THEN LAST_DAY(ADD_MONTHS(AA.EOM,1)) ELSE AA.ENDDATE END) -AA.EOM)
          END AS SALDODAYS,
          ADD_MONTHS(LAST_DAY(ADD_MONTHS(AA.BOM,1)),12-(EXTRACT (MONTH FROM ADD_MONTHS(AA.BOM,1)))) - ADD_MONTHS(LAST_DAY(ADD_MONTHS(AA.BOM,1)),(EXTRACT (MONTH FROM ADD_MONTHS(AA.BOM,1)))*-1) AS YEARINDAYS
  FROM CTE AA
  WHERE LAST_DAY(ADD_MONTHS(AA.EOM,1))<=LAST_DAY(AA.ENDDATE)
  )

  SELECT SUM(BB.OS*BB.INT_RATE*BB.DAYSINT/(BB.YEARINDAYS*100)) INTO INTEREST FROM CTE BB;

RETURN INTEREST;
END;