CREATE OR REPLACE PROCEDURE IFRS_LGD_RUN_ENGINE
AS

    BEGIN


    FOR LOOP_COUNTER IN 1..12
    LOOP

    --SP_IFRS_LGD_DATA_IMA;
    --SP_IFRS_LGD_SEQUENCE_DAILY;
    SP_IFRS_LGD_SEQUENCE;

    COMMIT;


    UPDATE IFRS_PRC_DATE_LGD
       --SET CURRDATE=CURRDATE+1;
       SET CURRDATE=ADD_MONTHS(CURRDATE,1);
    COMMIT;
    /*
    UPDATE IFRS_PRC_DATE_AMORT
        SET CURRDATE = CURRDATE+1,
            PREVDATE = PREVDATE+1;
            COMMIT;
      */
    END LOOP;
    END;