CREATE OR REPLACE PROCEDURE SP_IFRS_UPDATE_DATE
AS
BEGIN

   UPDATE IFRS_PRC_DATE
      SET CURRDATE = CURRDATE + 1,
          PREVDATE = PREVDATE + 1,
          BATCH_STATUS = ' ',
          REMARK = ' ';

   COMMIT;

   UPDATE IFRS_PRC_DATE_AMORT
      SET CURRDATE = CURRDATE + 1,
          PREVDATE = PREVDATE + 1,
          BATCH_STATUS = ' ',
          REMARK = ' ';

   COMMIT;
END;