CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MIG_TERM_STRUCTURE
AS
    v_CURRDATE DATE;
BEGIN

    SELECT CURRDATE
	INTO v_CURRDATE
	FROM IFRS_PRC_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

    INSERT INTO TMP_IFRS_PD_RUNNING_DATE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        BUCKET_GROUP,
        MIG_LOSS_BUCKET
    )
    SELECT
        v_CURRDATE AS EFF_DATE,
		LAST_DAY(ADD_MONTHS(v_CURRDATE, A.INCREMENT_PERIOD * -1)) AS BASE_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.MIG_LOSS_BUCKET
    FROM IFRS_PD_RULES_CONFIG A
    WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MIG'
	AND A.DERIVED_PD_MODEL IS NULL;

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_PD_TERM_STRUCTURE';

    INSERT INTO GTMP_IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD
    )
     SELECT
      A.EFF_DATE,
      A.BASE_DATE,
      A.PD_RULE_ID,
      B.PD_RULE_NAME,
      A.BUCKET_GROUP,
      A.BUCKET_ID,
      A.SEQUENCE FL_YEAR,
      D.MONTHS FL_MONTH,
      ADD_MONTHS (A.PROJECTION_DATE, D.MONTHS-1) FL_DATE,
      1 - POWER(1-A.MARGINAL_PD,D.MONTHS/12) PD,
      1 - POWER(1-A.MARGINAL_PD,D.MONTHS/12) PRODUCTION_PD,
      1 - POWER(1-A.MARGINAL_PD,D.MONTHS/12) OVERRIDE_PD--,
      --B.PD_MODEL_ID
     FROM IFRS_PD_MIG_MARGINAL A
     JOIN TMP_IFRS_PD_RUNNING_DATE B
      ON A.EFF_DATE = B.EFF_DATE
      AND A.PD_RULE_ID = B.PD_RULE_ID
     CROSS JOIN
     (
        SELECT 1 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 2 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 3 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 4 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 5 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 6 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 7 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 8 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 9 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 10 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 11 AS MONTHS FROM DUAL
        UNION ALL
        SELECT 12 AS MONTHS FROM DUAL
       )  D
     ORDER BY A.PD_RULE_ID,
      A.SEQUENCE,
      A.BUCKET_ID,
      D.MONTHS;

    COMMIT;

    DELETE IFRS_PD_TERM_STRUCTURE
    WHERE EFF_DATE = v_CURRDATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

    COMMIT;

    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD
    )
    SELECT
        A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        A.PD_RULE_NAME,
        A.BUCKET_GROUP,
        A.BUCKET_ID,
        A.FL_YEAR,
        A.FL_MONTH,
        A.FL_DATE,
        A.PD - NVL(B.PD,0) PD,
        A.PRODUCTION_PD - NVL(B.PRODUCTION_PD,0) PRODUCTION_PD,
        A.OVERRIDE_PD - NVL(B.OVERRIDE_PD,0) OVERRIDE_PD
     FROM GTMP_IFRS_PD_TERM_STRUCTURE A
     LEFT JOIN GTMP_IFRS_PD_TERM_STRUCTURE B
      ON A.PD_RULE_ID = B.PD_RULE_ID
        AND A.FL_YEAR = B.FL_YEAR
        AND (A.FL_MONTH - 1) = B.FL_MONTH;

    COMMIT;

--    INSERT INTO IFRS_PD_TERM_STRUCTURE
--    SELECT
--    0 PKID,
--    A.EFF_DATE,
--    A.BASE_DATE,
--    A.PD_RULE_ID,
--    A.PD_RULE_NAME,
--    A.MODEL_ID,
--    A.BUCKET_GROUP,
--    A.BUCKET_ID,
--    B.MONTHS + (A.FL_YEAR - 1) * 12 FL_SEQ,
--    A.FL_YEAR,
--    B.MONTHS FL_MONTH,
--    ADD_MONTHS(A.EFF_DATE, (B.MONTHS - 1) + (A.FL_YEAR - 1) * 12) FL_DATE,
--    A.PD / 12 PD,
--    A.PD / 12 PRODUCTION_PD,
--    A.PD / 12 OVERRIDE_PD,
--    'M' PRC_FLAG,
--    A.CREATEDBY,
--    A.CREATEDDATE,
--    A.CREATEDHOST,
--    A.UPDATEDBY,
--    A.UPDATEDDATE,
--    A.UPDATEDHOST
--    FROM IFRS_PD_TERM_STRUCTURE A
--    CROSS JOIN
--    (
--        SELECT 1 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 2 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 3 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 4 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 5 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 6 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 7 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 8 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 9 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 10 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 11 AS MONTHS FROM DUAL
--        UNION ALL
--        SELECT 12 AS MONTHS FROM DUAL
--    ) B;
--
--    COMMIT;
END;