CREATE OR REPLACE PROCEDURE SP_IFRS_FILL_IMA_PREV_CURR
AS
    V_CURRDATE DATE ;
    V_PREVDATE DATE;

BEGIN

        SELECT  MAX(CURRDATE) ,
                MAX(PREVDATE)
        INTO V_CURRDATE, V_PREVDATE
        FROM    IFRS_PRC_DATE_AMORT ;


        INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
        VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'START' ,'SP_IFRS_FILL_IMA_PREV_CURR' ,'');
        COMMIT;

   -- clean up
        EXECUTE IMMEDIATE ('TRUNCATE TABLE IFRS_IMA_AMORT_CURR');
        EXECUTE IMMEDIATE ('TRUNCATE TABLE IFRS_IMA_AMORT_PREV');
        COMMIT;

        INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
        VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'DEBUG' ,'SP_IFRS_FILL_IMA_PREV_CURR' ,'FILL IMA_AMORT_PREV');

        INSERT /*+ PARALLEL(12) */ INTO IFRS_IMA_AMORT_PREV
                ( DOWNLOAD_DATE ,
                        MASTERID ,
                        PRODUCT_ENTITY ,
                        JF_FLAG ,
                        DATA_SOURCE ,
                        PRODUCT_TYPE ,
                        PRODUCT_CODE ,
                        PRODUCT_GROUP ,
                        BRANCH_CODE ,
                        CURRENCY ,
                        ACCOUNT_NUMBER ,
                        PREVIOUS_ACCOUNT_NUMBER ,
                        CUSTOMER_NUMBER ,
                        CUSTOMER_NAME ,
                        --RESIDENCE_TYPE ,
                        GLOBAL_CUSTOMER_NUMBER ,
                        EXCHANGE_RATE ,
                        MARKET_RATE ,
                        INITIAL_OUTSTANDING ,
                        OUTSTANDING ,
                        OUTSTANDING_JF ,
                        OUTSTANDING_BANK ,
                        OUTSTANDING_PASTDUE ,
                        OUTSTANDING_IDC ,
                        PLAFOND ,
                        --PLAFOND_IDC ,
                        PLAFOND_CASH ,
                        UNUSED_AMOUNT ,
                        --UNUSED_IDC_AMOUNT ,
                        DOWN_PAYMENT_AMOUNT ,
                        --OTR_AMOUNT ,
                        INTEREST_RATE ,
                        ACCOUNT_STATUS ,
                        FACILITY_NUMBER ,
                        --PREVIOUS_FACILITY_NUMBER ,
                        --FACILITY_START_DATE ,
                        LOAN_START_DATE ,
                        LOAN_DUE_DATE ,
                        INSTALLMENT_GRACE_PERIOD ,
                        LOAN_START_AMORTIZATION ,
                        LOAN_END_AMORTIZATION ,
                        AMORT_TYPE ,
                        NEXT_PAYMENT_DATE ,
                        LAST_PAYMENT_DATE ,
                        FIRST_INSTALLMENT_DATE ,
                        TENOR ,
                        PAYMENT_CODE ,
                        PAYMENT_TERM ,
                        INTEREST_PAYMENT_TERM ,
                        EIR_STATUS ,
                        ECF_STATUS ,
                        INTEREST_CALCULATION_CODE ,
                        EIR ,
                        EIR_AMOUNT ,
                        FAIR_VALUE_AMOUNT ,
                        UNAMORT_COST_AMT ,
                        UNAMORT_FEE_AMT ,
                        DAILY_AMORT_AMT ,
                        DAY_PAST_DUE ,
                        --CUSTOMER_GRADE ,
                        ORIGINAL_COLLECTABILITY ,
                        BI_COLLECTABILITY ,
                        --IFRS_DAY_PAST_DUE ,
                        GL_CONSTNAME ,
                        SEGMENT ,
                        PD_SEGMENT ,
                        --PD_RATE ,
                        LGD_SEGMENT ,
                        --LGD_RATE ,
                        IMPAIRED_FLAG ,
                        IS_IMPAIRED ,
                        --PIP_AMOUNT ,
                        --PIP_AMOUNT_ORIGINAL ,
                        --IIP_AMOUNT ,
                        CA_UNWINDING_AMOUNT ,
                        IA_UNWINDING_AMOUNT ,
                        BEGINNING_BALANCE ,
                        ENDING_BALANCE ,
                        WRITEBACK ,
                        CHARGE ,
                        WRITEOFF_FLAG ,
                        WRITEOFF_DATE ,
                        OUTSTANDING_WO ,
                        --RECOVERY_DATE ,
                        --RECOVERY_AMOUNT ,
                        RESTRUCTURE_DATE ,
                        RESTRUCTURE_FLAG ,
                        STAFF_LOAN_FLAG ,
                        BELOW_MARKET_FLAG ,
                        COMMITTED_FLAG ,
                        INSTALLMENT_AMOUNT ,
                        --CUSTOMER_TYPE ,
                        --COLLATERAL_AMOUNT ,
                        --AYDA_AMOUNT ,
                        --COLLATERAL_VALUE_FOR_IMPAIR ,
                        --COLLATERAL_VALUE_FOR_NLP ,
                        --COLLATERAL_PROV_CALC_AMT ,
                        --COLLATERAL_TYPE ,
                        INITIAL_UNAMORT_TXN_COST ,
                        INITIAL_UNAMORT_ORG_FEE ,
                        IAS_CLASS ,
                        --AO_NAME ,
                        --AO_CODE ,
                        REVOLVING_FLAG ,
                        --PAID_DATE ,
                        BUCKET_ID ,
                        --INSERTED_DATE ,
                        --DEBTOR_CLASS ,
                        --DEBTOR_GROUP ,
                        --DEBTOR_CATEGORY ,
                        --POST_CODE ,
                        --REGION ,
                        --CITY ,
                        --INDUSTRY_SECTOR ,
                        --ECONOMIC_SECTOR ,
                        --ECONOMIC_SECTOR_OJK ,
                        PRODUCT_TYPE_GROUP ,
                        --FIRST_OVERDUE_DATE ,
                        NPL_DATE ,
                        NPL_FLAG ,
                        BRANCH_CODE_OPEN ,
                        --COMPOUND_FLAG ,
                        UNAMORT_AMT_TOTAL_JF ,
                        UNAMORT_FEE_AMT_JF ,
                        UNAMORT_COST_AMT_JF
                        ,IFRS9_CLASS
                )
                SELECT  /*+ PARALLEL(12) */ DOWNLOAD_DATE ,
                        MASTERID ,
                        PRODUCT_ENTITY ,
                        JF_FLAG ,
                        DATA_SOURCE ,
                        PRODUCT_TYPE ,
                        PRODUCT_CODE ,
                        PRODUCT_GROUP ,
                        BRANCH_CODE ,
                        CURRENCY ,
                        ACCOUNT_NUMBER ,
                        PREVIOUS_ACCOUNT_NUMBER ,
                        CUSTOMER_NUMBER ,
                        CUSTOMER_NAME ,
                        --RESIDENCE_TYPE ,
                        GLOBAL_CUSTOMER_NUMBER ,
                        EXCHANGE_RATE ,
                        MARKET_RATE ,
                        INITIAL_OUTSTANDING ,
                        OUTSTANDING ,
                        OUTSTANDING_JF ,
                        OUTSTANDING_BANK ,
                        OUTSTANDING_PASTDUE ,
                        OUTSTANDING_IDC ,
                        PLAFOND ,
                        --PLAFOND_IDC ,
						PLAFOND_CASH ,
                        UNUSED_AMOUNT ,
                        --UNUSED_IDC_AMOUNT ,
                        DOWN_PAYMENT_AMOUNT ,
                        --OTR_AMOUNT ,
                        INTEREST_RATE ,
                        ACCOUNT_STATUS ,
                        FACILITY_NUMBER ,
                        --PREVIOUS_FACILITY_NUMBER ,
                        --FACILITY_START_DATE ,
                        LOAN_START_DATE ,
                        LOAN_DUE_DATE ,
                        INSTALLMENT_GRACE_PERIOD ,
                        LOAN_START_AMORTIZATION ,
                        LOAN_END_AMORTIZATION ,
                        AMORT_TYPE ,
                        NEXT_PAYMENT_DATE ,
                        LAST_PAYMENT_DATE ,
                        FIRST_INSTALLMENT_DATE ,
                        TENOR ,
                        PAYMENT_CODE ,
                        PAYMENT_TERM ,
                        INTEREST_PAYMENT_TERM ,
                        EIR_STATUS ,
                        ECF_STATUS ,
                        INTEREST_CALCULATION_CODE ,
                        EIR ,
                        EIR_AMOUNT ,
                        FAIR_VALUE_AMOUNT ,
                        UNAMORT_COST_AMT ,
                        CASE WHEN STAFF_LOAN_FLAG = 1 THEN UNAMORT_BENEFIT ELSE UNAMORT_FEE_AMT END ,
                        DAILY_AMORT_AMT ,
                        DAY_PAST_DUE ,
                        --CUSTOMER_GRADE ,
                        ORIGINAL_COLLECTABILITY ,
                        BI_COLLECTABILITY ,
                        --IFRS_DAY_PAST_DUE ,
                        GL_CONSTNAME ,
                        SEGMENT ,
                        PD_SEGMENT ,
                        --PD_RATE ,
                        LGD_SEGMENT ,
                        --LGD_RATE ,
                        IMPAIRED_FLAG ,
                        IS_IMPAIRED ,
                        --PIP_AMOUNT ,
                        --PIP_AMOUNT_ORIGINAL ,
                        --IIP_AMOUNT ,
                        CA_UNWINDING_AMOUNT ,
                        IA_UNWINDING_AMOUNT ,
                        BEGINNING_BALANCE ,
                        ENDING_BALANCE ,
                        WRITEBACK_AMOUNT ,
                        CHARGE_AMOUNT ,
                        WRITEOFF_FLAG ,
                        WRITEOFF_DATE ,
                        OUTSTANDING_WO ,
                        --RECOVERY_DATE ,
                        --RECOVERY_AMOUNT ,
                        RESTRUCTURE_DATE ,
                        RESTRUCTURE_FLAG ,
                        CASE WHEN STAFF_LOAN_FLAG = 1 THEN 'Y' ELSE 'N' END ,
                        BELOW_MARKET_FLAG ,
                        COMMITTED_FLAG ,
                        INSTALLMENT_AMOUNT ,
                        --CUSTOMER_TYPE ,
                        --COLLATERAL_AMOUNT ,
                        --AYDA_AMOUNT ,
                        --COLLATERAL_VALUE_FOR_IMPAIR ,
                        --COLLATERAL_VALUE_FOR_NLP ,
                        --COLLATERAL_PROV_CALC_AMT ,
                        --COLLATERAL_TYPE ,
                        INITIAL_UNAMORT_TXN_COST ,
                        INITIAL_UNAMORT_ORG_FEE ,
                        IAS_CLASS ,
                        --AO_NAME ,
                        --AO_CODE ,
                        REVOLVING_FLAG ,
                       -- PAID_DATE ,
                        BUCKET_ID ,
                        --CREATED_DATE ,
                        --DEBTOR_CLASS ,
                        --DEBTOR_GROUP ,
                        --DEBTOR_CATEGORY ,
                        --POST_CODE ,
                        --REGION ,
                        --CITY ,
                        --INDUSTRY_SECTOR ,
                        --ECONOMIC_SECTOR ,
                        --ECONOMIC_SECTOR_OJK ,
                        NULL PRODUCT_TYPE_GROUP ,
                        --FIRST_OVERDUE_DATE ,
                        NPL_DATE ,
                        NPL_FLAG ,
                        BRANCH_CODE_OPEN ,
                        --COMPOUND_FLAG ,
                        UNAMORT_AMT_TOTAL_JF ,
                        UNAMORT_FEE_AMT_JF ,
                        UNAMORT_COST_AMT_JF ,
                        IFRS9_CLASS
                FROM    IFRS_MASTER_ACCOUNT
                WHERE   DOWNLOAD_DATE = V_PREVDATE
                AND DATA_SOURCE = 'ILS';
                COMMIT;

        INSERT  INTO IFRS_AMORT_LOG( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
        VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'DEBUG' ,'SP_IFRS_FILL_IMA_PREV_CURR' ,'FILL IMA_AMORT_CURR');

        INSERT /*+ PARALLEL(12) */ INTO IFRS_IMA_AMORT_CURR
                ( DOWNLOAD_DATE ,
                        MASTERID ,
                        PRODUCT_ENTITY ,
                        JF_FLAG ,
                        DATA_SOURCE ,
                        PRODUCT_TYPE ,
                        PRODUCT_CODE ,
                        PRODUCT_GROUP ,
                        BRANCH_CODE ,
                        CURRENCY ,
                        ACCOUNT_NUMBER ,
                        PREVIOUS_ACCOUNT_NUMBER ,
                        CUSTOMER_NUMBER ,
                        CUSTOMER_NAME ,
                        --RESIDENCE_TYPE ,
                        GLOBAL_CUSTOMER_NUMBER ,
                        EXCHANGE_RATE ,
                        MARKET_RATE ,
                        INITIAL_OUTSTANDING ,
                        OUTSTANDING ,
                        OUTSTANDING_JF ,
                        OUTSTANDING_BANK ,
                        OUTSTANDING_PASTDUE ,
                        OUTSTANDING_IDC ,
                        PLAFOND ,
                        --PLAFOND_IDC ,
                        PLAFOND_CASH ,
                        UNUSED_AMOUNT ,
                        --UNUSED_IDC_AMOUNT ,
                        DOWN_PAYMENT_AMOUNT ,
                        --OTR_AMOUNT ,
                        INTEREST_RATE ,
                        ACCOUNT_STATUS ,
                        FACILITY_NUMBER ,
                        --PREVIOUS_FACILITY_NUMBER ,
                        --FACILITY_START_DATE ,
                        LOAN_START_DATE ,
                        LOAN_DUE_DATE ,
                        INSTALLMENT_GRACE_PERIOD ,
                        LOAN_START_AMORTIZATION ,
                        LOAN_END_AMORTIZATION ,
                        AMORT_TYPE ,
                        NEXT_PAYMENT_DATE ,
                        LAST_PAYMENT_DATE ,
                        FIRST_INSTALLMENT_DATE ,
                        TENOR ,
                        PAYMENT_CODE ,
                        PAYMENT_TERM ,
                        INTEREST_PAYMENT_TERM ,
                        EIR_STATUS ,
                        ECF_STATUS ,
                        INTEREST_CALCULATION_CODE ,
                        EIR ,
                        EIR_AMOUNT ,
                        FAIR_VALUE_AMOUNT ,
                        UNAMORT_COST_AMT ,
                        UNAMORT_FEE_AMT ,
                        DAILY_AMORT_AMT ,
                        DAY_PAST_DUE ,
                        --CUSTOMER_GRADE ,
                        ORIGINAL_COLLECTABILITY ,
                        BI_COLLECTABILITY ,
                        --IFRS_DAY_PAST_DUE ,
                        GL_CONSTNAME ,
                        SEGMENT ,
                        PD_SEGMENT ,
						--PD_RATE ,
                        LGD_SEGMENT ,
                        --LGD_RATE ,
                        IMPAIRED_FLAG ,
                        IS_IMPAIRED ,
                        --PIP_AMOUNT ,
                        --PIP_AMOUNT_ORIGINAL ,
                        --IIP_AMOUNT ,
                        CA_UNWINDING_AMOUNT ,
                        IA_UNWINDING_AMOUNT ,
                        BEGINNING_BALANCE ,
                        ENDING_BALANCE ,
                        WRITEBACK ,
                        CHARGE ,
                        WRITEOFF_FLAG ,
                        WRITEOFF_DATE ,
                        OUTSTANDING_WO ,
                        --RECOVERY_DATE ,
                        --RECOVERY_AMOUNT ,
                        RESTRUCTURE_DATE ,
                        RESTRUCTURE_FLAG ,
                        STAFF_LOAN_FLAG ,
                        BELOW_MARKET_FLAG ,
                        COMMITTED_FLAG ,
                        INSTALLMENT_AMOUNT ,
                        --CUSTOMER_TYPE ,
                        --COLLATERAL_AMOUNT ,
                        --AYDA_AMOUNT ,
                        --COLLATERAL_VALUE_FOR_IMPAIR ,
                        --COLLATERAL_VALUE_FOR_NLP ,
                        --COLLATERAL_PROV_CALC_AMT ,
                        --COLLATERAL_TYPE ,
                        INITIAL_UNAMORT_TXN_COST ,
                        INITIAL_UNAMORT_ORG_FEE ,
                        IAS_CLASS ,
                        --AO_NAME ,
                        --AO_CODE ,
                        REVOLVING_FLAG ,
                        --PAID_DATE ,
                        BUCKET_ID ,
                        --INSERTED_DATE ,
                        --DEBTOR_CLASS ,
                        --DEBTOR_GROUP ,
                        --DEBTOR_CATEGORY ,
                        --POST_CODE ,
                        --REGION ,
                        --CITY ,
                        --INDUSTRY_SECTOR ,
                        --ECONOMIC_SECTOR ,
                        --ECONOMIC_SECTOR_OJK ,
                        PRODUCT_TYPE_GROUP ,
                        --FIRST_OVERDUE_DATE ,
                        NPL_DATE ,
                        NPL_FLAG ,
                        BRANCH_CODE_OPEN ,
                        --COMPOUND_FLAG ,
                        UNAMORT_AMT_TOTAL_JF ,
                        UNAMORT_FEE_AMT_JF ,
                        UNAMORT_COST_AMT_JF
                        ,IFRS9_CLASS
                )
                SELECT /*+ PARALLEL(12) */ DOWNLOAD_DATE ,
                        MASTERID ,
                        PRODUCT_ENTITY ,
                        JF_FLAG ,
                        DATA_SOURCE ,
                        PRODUCT_TYPE ,
                        PRODUCT_CODE ,
                        PRODUCT_GROUP ,
                        BRANCH_CODE ,
                        CURRENCY ,
                        ACCOUNT_NUMBER ,
                        PREVIOUS_ACCOUNT_NUMBER ,
                        CUSTOMER_NUMBER ,
                        CUSTOMER_NAME ,
                        --RESIDENCE_TYPE ,
                        GLOBAL_CUSTOMER_NUMBER ,
                        EXCHANGE_RATE ,
                        MARKET_RATE ,
                        INITIAL_OUTSTANDING ,
                        OUTSTANDING ,
                        OUTSTANDING_JF ,
                        OUTSTANDING_BANK ,
                        OUTSTANDING_PASTDUE ,
                        OUTSTANDING_IDC ,
                        PLAFOND ,
                        --PLAFOND_IDC ,
                        PLAFOND_CASH ,
                        UNUSED_AMOUNT ,
                        --UNUSED_IDC_AMOUNT ,
                        DOWN_PAYMENT_AMOUNT ,
                       -- OTR_AMOUNT ,
                        INTEREST_RATE ,
                        ACCOUNT_STATUS ,
                        FACILITY_NUMBER ,
                        --PREVIOUS_FACILITY_NUMBER ,
                        --FACILITY_START_DATE ,
                        LOAN_START_DATE ,
                        LOAN_DUE_DATE ,
                        INSTALLMENT_GRACE_PERIOD ,
                        LOAN_START_AMORTIZATION ,
                        LOAN_END_AMORTIZATION ,
                        AMORT_TYPE ,
                        NEXT_PAYMENT_DATE ,
                        LAST_PAYMENT_DATE ,
                        FIRST_INSTALLMENT_DATE ,
                        TENOR ,
                        PAYMENT_CODE ,
                        PAYMENT_TERM ,
                        INTEREST_PAYMENT_TERM ,
                        EIR_STATUS ,
                        ECF_STATUS ,
                        INTEREST_CALCULATION_CODE ,
                        EIR ,
                        EIR_AMOUNT ,
                        FAIR_VALUE_AMOUNT ,
                        UNAMORT_COST_AMT ,
                        CASE WHEN STAFF_LOAN_FLAG = 1 THEN UNAMORT_BENEFIT ELSE UNAMORT_FEE_AMT END ,
                        DAILY_AMORT_AMT ,
                        DAY_PAST_DUE ,
                        --CUSTOMER_GRADE ,
                        ORIGINAL_COLLECTABILITY ,
                        BI_COLLECTABILITY ,
                        --IFRS_DAY_PAST_DUE ,
                        GL_CONSTNAME ,
                        SEGMENT ,
                        PD_SEGMENT ,
                        --PD_RATE ,
                        LGD_SEGMENT ,
                        --LGD_RATE ,
                        IMPAIRED_FLAG ,
                        IS_IMPAIRED ,
                        --PIP_AMOUNT ,
                        --PIP_AMOUNT_ORIGINAL ,
                        --IIP_AMOUNT ,
                        CA_UNWINDING_AMOUNT ,
                        IA_UNWINDING_AMOUNT ,
                        BEGINNING_BALANCE ,
                        ENDING_BALANCE ,
                        WRITEBACK_AMOUNT,
                        CHARGE_AMOUNT ,
                        WRITEOFF_FLAG ,
                        WRITEOFF_DATE ,
                        OUTSTANDING_WO ,
                        --RECOVERY_DATE ,
                        --RECOVERY_AMOUNT ,
                        RESTRUCTURE_DATE ,
                        RESTRUCTURE_FLAG ,
                        CASE WHEN STAFF_LOAN_FLAG = 1 THEN 'Y' ELSE 'N' END ,
                        BELOW_MARKET_FLAG ,
                        COMMITTED_FLAG ,
                        INSTALLMENT_AMOUNT ,
                        --CUSTOMER_TYPE ,
                        --COLLATERAL_AMOUNT ,
                        --AYDA_AMOUNT ,
                        --COLLATERAL_VALUE_FOR_IMPAIR ,
                        --COLLATERAL_VALUE_FOR_NLP ,
                        --COLLATERAL_PROV_CALC_AMT ,
                        --COLLATERAL_TYPE ,
                        INITIAL_UNAMORT_TXN_COST ,
                        INITIAL_UNAMORT_ORG_FEE ,
                        IAS_CLASS ,
                        --AO_NAME ,
                        --AO_CODE ,
                        REVOLVING_FLAG ,
                        --PAID_DATE ,
                         BUCKET_ID ,
                        --CREATED_DATE ,
                        --DEBTOR_CLASS ,
                        --DEBTOR_GROUP ,
                        --DEBTOR_CATEGORY ,
                        --POST_CODE ,
                        --REGION ,
                        --CITY ,
                        --INDUSTRY_SECTOR ,
                        --ECONOMIC_SECTOR ,
                        --ECONOMIC_SECTOR_OJK ,
                        NULL PRODUCT_TYPE_GROUP ,
                        --FIRST_OVERDUE_DATE ,
                        NPL_DATE ,
                        NPL_FLAG ,
                        BRANCH_CODE_OPEN ,
                        ---COMPOUND_FLAG ,
                        UNAMORT_AMT_TOTAL_JF ,
                        UNAMORT_FEE_AMT_JF ,
                        UNAMORT_COST_AMT_JF
                        /*  BCA DISABLE BPI ,SPECIAL_FLAG */
                        ,IFRS9_CLASS
                        FROM    IFRS_MASTER_ACCOUNT
                WHERE   DOWNLOAD_DATE = V_CURRDATE
                AND DATA_SOURCE = 'ILS';
                COMMIT;

        INSERT  INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
        VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_FILL_IMA_PREV_CURR' ,'');
        COMMIT;
END;