CREATE OR REPLACE PROCEDURE SP_IFRS_RONA_STAT (v_DOWNLOADDATECUR  DATE DEFAULT ('1-JAN-1900'),
                                               v_DOWNLOADDATEPREV DATE DEFAULT ('1-JAN-1900'))
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_SPNAME   VARCHAR2(200);

BEGIN

IF v_DOWNLOADDATECUR = '1-JAN-1900'
  THEN
    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
  ELSE
    V_CURRDATE := v_DOWNLOADDATECUR;
  END IF;

  IF v_DOWNLOADDATEPREV = '1-JAN-1900'
  THEN
    SELECT PREVDATE INTO V_PREVDATE FROM IFRS_PRC_DATE;
  ELSE
    V_PREVDATE := v_DOWNLOADDATEPREV;
  END IF;


V_SPNAME := 'SP_IFRS_REPORT_RONA (' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ')';
SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'REPORT', 'Y');

END;