CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_UPDATE
AS
    V_CURRDATE DATE;
    V_PREVDATE DATE;

BEGIN

    SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_LGD ;  --HARUS DIRUBAH KE IFRS_PRC_DATE

    --TRUNCATE TMP_IFRS_MASTER_ACCOUNT
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_MASTER_ACCOUNT';
    COMMIT;

    --GET TMP IMA
    INSERT INTO TMP_IFRS_MASTER_ACCOUNT (DOWNLOAD_DATE,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        INTEREST_RATE,
        PRODUCT_CODE,
        CURRENCY,
        OUTSTANDING,
        OUTSTANDING2,
        LOAN_START_DATE,
        LOAN_DUE_DATE,
        BI_COLLECTABILITY,
        WRITEOFF_FLAG,
        WRITEOFF_DATE,
        OUTSTANDING_WO,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_21,
        RESERVED_AMOUNT_8,
        RESERVED_RATE_10,
        RESERVED_DATE_3,
        RESERVED_DATE_5)
    SELECT DOWNLOAD_DATE,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        INTEREST_RATE,
        PRODUCT_CODE,
        CURRENCY,
        OUTSTANDING,
        LAG(OUTSTANDING) OVER(PARTITION BY CUSTOMER_NUMBER,ACCOUNT_NUMBER ORDER BY DOWNLOAD_DATE) OUTSTANDING2,
        LOAN_START_DATE,
        LOAN_DUE_DATE,
        BI_COLLECTABILITY,
        WRITEOFF_FLAG,
        WRITEOFF_DATE,
        OUTSTANDING_WO,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_21,
        RESERVED_AMOUNT_8,
        RESERVED_RATE_10,
        RESERVED_DATE_3,
        RESERVED_DATE_5
    FROM (
        SELECT
            V_CURRDATE AS DOWNLOAD_DATE,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            ACCOUNT_NUMBER,
            ACCOUNT_STATUS,
            INTEREST_RATE,
            PRODUCT_CODE,
            CURRENCY,
            OUTSTANDING,
            LOAN_START_DATE,
            LOAN_DUE_DATE,
            BI_COLLECTABILITY,
            WRITEOFF_FLAG,
            WRITEOFF_DATE,
            OUTSTANDING_WO,
            RESERVED_VARCHAR_2,
            RESERVED_VARCHAR_9,
            RESERVED_VARCHAR_21,
            RESERVED_AMOUNT_8,
            RESERVED_RATE_10,
            RESERVED_DATE_3,
            RESERVED_DATE_5
        FROM IFRS_MASTER_ACCOUNT
        WHERE DATA_SOURCE       =   'ILS'
            AND BI_COLLECTABILITY IN ('C','3','4','5')
            AND DOWNLOAD_DATE   =   V_CURRDATE
        UNION
        SELECT
            DOWNLOAD_DATE,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            ACCOUNT_NUMBER,
            ACCOUNT_STATUS,
            INTEREST_RATE,
            PRODUCT_CODE,
            CURRENCY,
            OUTSTANDING,
            LOAN_START_DATE,
            LOAN_DUE_DATE,
            BI_COLLECTABILITY,
            WRITEOFF_FLAG,
            WRITEOFF_DATE,
            OUTSTANDING_WO,
            RESERVED_VARCHAR_2,
            RESERVED_VARCHAR_9,
            RESERVED_VARCHAR_21,
            RESERVED_AMOUNT_8,
            RESERVED_RATE_10,
            RESERVED_DATE_3,
            RESERVED_DATE_5
        FROM IFRS_MASTER_ACCOUNT
        WHERE DATA_SOURCE       =   'ILS'
            AND BI_COLLECTABILITY IN ('C','3','4','5')
            AND DOWNLOAD_DATE   =   V_PREVDATE
    )AA;
    COMMIT;

    --UPDATE KKB RODA 2 C1
    UPDATE TMP_IFRS_MASTER_ACCOUNT
        SET RESERVED_VARCHAR_21     =   CASE WHEN (ACCOUNT_STATUS!='C' OR OUTSTANDING!=0 ) AND MONTHS_BETWEEN(LAST_DAY(TO_DATE(DOWNLOAD_DATE,'YYYY-MM-DD')),LAST_DAY(TO_DATE(WRITEOFF_DATE,'YYYY-MM-DD')))>=12 THEN'C1' END,
            RESERVED_DATE_5         =   CASE WHEN (ACCOUNT_STATUS!='C' OR OUTSTANDING!=0 ) AND MONTHS_BETWEEN(LAST_DAY(TO_DATE(DOWNLOAD_DATE,'YYYY-MM-DD')),LAST_DAY(TO_DATE(WRITEOFF_DATE,'YYYY-MM-DD')))>=12 THEN V_CURRDATE END
    WHERE DOWNLOAD_DATE     =   V_CURRDATE;
    COMMIT;

    --UPDATE KKB RODA 2 C2,C3
    UPDATE  TMP_IFRS_MASTER_ACCOUNT
        SET RESERVED_VARCHAR_21 =   CASE WHEN RESERVED_VARCHAR_21='C1' AND OUTSTANDING!=0 AND OUTSTANDING>OUTSTANDING2 THEN 'C2' --LAG(OUTSTANDING) OVER(PARTITION BY CUSTOMER_NUMBER,ACCOUNT_NUMBER ORDER BY DOWNLOAD_DATE) THEN 'C2'
                                        WHEN (RESERVED_VARCHAR_21 IN('C1','C2')  AND ACCOUNT_STATUS='C') OR OUTSTANDING=0 THEN 'C3'
                                    ELSE RESERVED_VARCHAR_21
                                    END,
        RESERVED_DATE_5        =   CASE WHEN  RESERVED_VARCHAR_21='C1' AND OUTSTANDING!=0 AND OUTSTANDING>OUTSTANDING2 THEN LOAN_DUE_DATE --LAG (OUTSTANDING) OVER(PARTITION BY CUSTOMER_NUMBER,ACCOUNT_NUMBER ORDER BY DOWNLOAD_DATE) THEN LOAN_DUE_DATE
                                        WHEN  (RESERVED_VARCHAR_21 IN('C1','C2')  AND ACCOUNT_STATUS='C') OR OUTSTANDING=0 THEN DOWNLOAD_DATE
                                    END
    WHERE DOWNLOAD_DATE =   V_CURRDATE;
    COMMIT;

    --UPDATE RESERVED_VARCHAR_9 LIKE'%J%'
    UPDATE TMP_IFRS_MASTER_ACCOUNT SET
        RESERVED_VARCHAR_21 = CASE WHEN RESERVED_VARCHAR_9 LIKE '%J%' THEN 'J' END
    WHERE ACCOUNT_STATUS        =   'C'
        AND OUTSTANDING         =   0
        AND BI_COLLECTABILITY IN ('C','3','4','5')
        AND RESERVED_VARCHAR_9 LIKE '%J%'
        AND DOWNLOAD_DATE       =    V_CURRDATE;
    COMMIT;

    --PRODUCT_CODE NOT IN ('304','310','311','312','313','314','315','316','320')
    UPDATE TMP_IFRS_MASTER_ACCOUNT SET
        RESERVED_VARCHAR_21 = CASE WHEN PRODUCT_CODE NOT IN ('304','310','311','312','313','314','315','316','320') THEN 'L' END
    WHERE
        ACCOUNT_STATUS      =   'C'
        AND OUTSTANDING     =   0
        AND BI_COLLECTABILITY IN ('C','3','4','5')
        AND PRODUCT_CODE NOT IN ('304','310','311','312','313','314','315','316','320')
        AND DOWNLOAD_DATE   =   V_CURRDATE;
     COMMIT;


     --UPDATE CLOSED DATE
    UPDATE TMP_IFRS_MASTER_ACCOUNT SET
        RESERVED_DATE_5 = CASE WHEN RESERVED_AMOUNT_8 = 0 THEN LOAN_DUE_DATE
                                WHEN RESERVED_VARCHAR_21='J' THEN DOWNLOAD_DATE
                                WHEN RESERVED_VARCHAR_21='L' THEN DOWNLOAD_DATE
                          END
    WHERE
        ACCOUNT_STATUS='C'
        AND OUTSTANDING=0
        AND BI_COLLECTABILITY IN ('C','3','4','5')
        AND DOWNLOAD_DATE=V_CURRDATE;
    COMMIT;

    --UPDATE IMA
    MERGE INTO IFRS_MASTER_ACCOUNT D
    USING (SELECT * FROM TMP_IFRS_MASTER_ACCOUNT WHERE DOWNLOAD_DATE=V_CURRDATE) S ON (D.ACCOUNT_NUMBER=S.ACCOUNT_NUMBER
        AND D.CUSTOMER_NUMBER=S.CUSTOMER_NUMBER AND D.DOWNLOAD_DATE=V_CURRDATE)
    WHEN MATCHED THEN
    UPDATE SET
        RESERVED_VARCHAR_21     =   S.RESERVED_VARCHAR_21,
        RESERVED_DATE_5         =   S.RESERVED_DATE_5;
    COMMIT;

END;