CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_RESET_AMT_PRC
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;

  BEGIN
    SELECT CURRDATE, PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DELETE ECF','SP_IFRS_LBM_RESET_AMT_PRC','');

    DELETE /*+ PARALLEL(12) */
    FROM IFRS_LBM_ACCT_EIR_ECF
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'UPDATE ECF','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;

    UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_ECF
    SET AMORTSTOPDATE = NULL
        ,AMORTSTOPMSG = NULL
    WHERE AMORTSTOPDATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DELETE ACCRU PREV','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;

    DELETE /*+ PARALLEL(12) */
    FROM IFRS_LBM_ACCT_EIR_ACCRU_PREV
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DELETE ACF','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;

    DELETE /*+ PARALLEL(12) */
    FROM IFRS_LBM_ACCT_EIR_ACF
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DELETE COST FEE ECF','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;


    DELETE /*+ PARALLEL(12) */
    FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF
    WHERE ECFDATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DELETE COST FEE PREV','SP_IFRS_LBM_RESET_AMT_PRC','');
    COMMIT;


    DELETE /*+ PARALLEL(12) */
    FROM IFRS_LBM_ACCT_EIR_CF_PREV
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'UPDATE ACCRU PREV','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;

    --RESET ACRU TABLE EIR
    UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_EIR_ACCRU_PREV
    SET STATUS = 'ACT'
    WHERE STATUS >= TO_CHAR (V_CURRDATE, 'YYYYMMDD')
        AND STATUS != 'ACT';

        /*
    INSERT INTO IFRS_AMORT_LOG (
        DOWNLOAD_DATE
        ,DTM
        ,OPS
        ,PROCNAME
        ,REMARK
        )
    VALUES (
        @V_CURRDATE
        ,CURRENT_TIMESTAMP
        ,'DELETE ACCT COST FEE'
        ,'SP_IFRS_LBM_RESET_AMT_PRC'
        ,''
        )

    -- RESET COST FEE FROM SL TO EIR PROCESS
    DELETE
    FROM IFRS_ACCT_COST_FEE
    WHERE DOWNLOAD_DATE = @V_CURRDATE
        AND SRCPROCESS = 'SL_TO_EIR'

    -- DELETE IFRS_ACCT_JOURNAL_INTM
    DELETE
    FROM IFRS_ACCT_JOURNAL_INTM
    WHERE DOWNLOAD_DATE >= @V_CURRDATE

    */
    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_RESET_AMT_PRC','');

    COMMIT;
END;