CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_UNPROCESSED_IA_PR(v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
    V_CURRDATE  DATE;
    V_QUERY VARCHAR2(32000);
    V_STR_SQL_RULE VARCHAR2(32000);
BEGIN
    IF v_DOWNLOADDATE = '1-JAN-1900' THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATE;
    END IF;

    SP_IFRS_GENERATE_RULE('THRESHOLD');

    SELECT PD_RULES_QRY_RESULT
    INTO v_STR_SQL_RULE
    FROM GTMP_IFRS_SCENARIO_GEN_QUERY;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    v_QUERY := 'INSERT INTO GTMP_IFRS_MASTER_ACCOUNT
                (
                    PKID,
                    DOWNLOAD_DATE,
                    MASTERID,
                    MASTER_ACCOUNT_CODE,
                    CUSTOMER_NUMBER,
                    ACCOUNT_NUMBER,
                    FAIR_VALUE_AMOUNT
                )
                SELECT A.PKID,
                    A.DOWNLOAD_DATE,
                    A.MASTERID,
                    '' '' MASTER_ACCOUNT_CODE,
                    A.CUSTOMER_NUMBER,
                    A.ACCOUNT_NUMBER,
                    A.FAIR_VALUE_AMOUNT
                FROM TMP_IMA_PARTIAL A
                WHERE A.ACCOUNT_STATUS = ''A''
                AND A.CUSTOMER_NUMBER NOT IN (SELECT CUSTOMER_NUMBER FROM IFRS_IA_OVERRIDEH)
                AND A.OUTSTANDING > 0
                AND (' || v_STR_SQL_RULE || ')';

    EXECUTE IMMEDIATE v_QUERY;

    COMMIT;

    DELETE IFRS_ECL_RESULT_DETAIL_CALC_PR
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND ECL_MODEL_ID = v_ECLID
    AND MASTERID IN
    (SELECT MASTERID FROM GTMP_IFRS_MASTER_ACCOUNT)
    AND COUNTER_PAYSCHD > 1;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_CALC_PR A
    USING GTMP_IFRS_MASTER_ACCOUNT B
    ON (A.DOWNLOAD_DATE = V_CURRDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        A.PD_RATE = 1,
        A.LGD_RATE = 1,
        A.DISCOUNT_RATE = 1,
        A.ECL_AMOUNT = B.FAIR_VALUE_AMOUNT;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_PR A
    USING
    (   SELECT A2.MASTERID, B2.ECL_AMOUNT, A2.IMPAIRED_FLAG
        FROM GTMP_IFRS_MASTER_ACCOUNT A2
        JOIN IFRS_ECL_RESULT_DETAIL_CALC_PR B2
        ON B2.DOWNLOAD_DATE = V_CURRDATE
        AND B2.ECL_MODEL_ID = v_ECLID
        AND A2.MASTERID = B2.MASTERID
    ) B
    ON (A.DOWNLOAD_DATE = V_CURRDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        A.ECL_AMOUNT = B.ECL_AMOUNT,
        A.IMPAIRED_FLAG = 'I',
        A.SPECIAL_REASON = 'UNPROCESSED INDIVIDUAL';

    COMMIT;
END;