CREATE OR REPLACE PROCEDURE SP_IFRS_VALIDATE_WO_TREASURY(V_UPLOADID IN NUMBER)
  AS
    V_MESSAGE         VARCHAR2(100);
    V_COUNT           NUMBER(10);
    V_COLNAME         VARCHAR2(30);
    V_COLDESC         VARCHAR2(50);
    V_QUERY           VARCHAR2(4000);
    V_QUERYCOUNT      VARCHAR2(4000);
    V_DOWNLOADDATE    VARCHAR2(30);
    V_COLNAME_ACCOUNT VARCHAR2(100);
    V_COLNAME_AMOUNT  VARCHAR2(100);
  BEGIN

    --Validate Upload ke IFRS_NOMINATIVE
    V_COLDESC := 'DOWNLOAD_DATE';

    SELECT COLUMN_ALIAS
      INTO V_COLNAME
      FROM GTMP_SOURCE_HEADER
      WHERE COLUMN_SOURCE = V_COLDESC;

    V_QUERY := 'SELECT ' || V_COLNAME || '
    FROM GTMP_TBLU_DOC_TEMP_DETAIL
    WHERE ROWNUM = 1';

    EXECUTE IMMEDIATE V_QUERY
      INTO V_DOWNLOADDATE;


    SELECT COLUMN_ALIAS
      INTO V_COLNAME_ACCOUNT
      FROM GTMP_SOURCE_HEADER
      WHERE COLUMN_SOURCE = 'ACCOUNT_NUMBER';

    SELECT COLUMN_ALIAS
      INTO V_COLNAME_AMOUNT
      FROM GTMP_SOURCE_HEADER
      WHERE COLUMN_SOURCE = 'WO_AMOUNT';

    V_QUERYCOUNT := 'SELECT COUNT(*) from GTMP_TBLU_DOC_TEMP_DETAIL
    					WHERE ' || V_COLNAME_ACCOUNT || ' NOT IN (SELECT DISTINCT ACCOUNT_NUMBER FROM IFRS_NOMINATIVE WHERE REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1))';

    V_MESSAGE := 'ACCOUNT_NUMBER is not exist in IFRS_NOMINATIVE.';

    V_QUERY := 'SELECT UPLOADID,NO_URUT,''ACCOUNT_NUMBER'',' || V_COLNAME_ACCOUNT || ',''' || V_MESSAGE || ''' from GTMP_TBLU_DOC_TEMP_DETAIL
                      WHERE ' || V_COLNAME_ACCOUNT || ' NOT IN (SELECT DISTINCT ACCOUNT_NUMBER FROM IFRS_NOMINATIVE WHERE REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1))';

    EXECUTE IMMEDIATE V_QUERYCOUNT
      INTO V_COUNT;

    IF (V_COUNT > 0)
    THEN
      EXECUTE IMMEDIATE 'INSERT INTO GTMP_TBLU_DOC_TEMP_EXCEPTION (UPLOAD_ID, ROWNUMBER, COLUMN_NAME, COLUMN_VALUE, ERRORMESSAGE) ' || V_QUERY;
      COMMIT;
    END IF;

    V_QUERYCOUNT := 'SELECT COUNT(*) from GTMP_TBLU_DOC_TEMP_DETAIL
    					WHERE ' || V_COLNAME_ACCOUNT || ' NOT IN (SELECT DISTINCT ACCOUNT_NUMBER FROM IFRS_NOMINATIVE WHERE ACCOUNT_STATUS != ''A'' AND REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1))';

    V_MESSAGE := 'ACCOUNT_NUMBER is already closed or WO in IFRS_NOMINATIVE.';

    V_QUERY := 'SELECT UPLOADID,NO_URUT,''ACCOUNT_NUMBER'',' || V_COLNAME_ACCOUNT || ',''' || V_MESSAGE || ''' from GTMP_TBLU_DOC_TEMP_DETAIL
                      WHERE ' || V_COLNAME_ACCOUNT || ' NOT IN (SELECT DISTINCT ACCOUNT_NUMBER FROM IFRS_NOMINATIVE WHERE ACCOUNT_STATUS != ''A'' AND REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1))';

    EXECUTE IMMEDIATE V_QUERYCOUNT
      INTO V_COUNT;

    IF (V_COUNT > 0)
    THEN
      EXECUTE IMMEDIATE 'INSERT INTO GTMP_TBLU_DOC_TEMP_EXCEPTION (UPLOAD_ID, ROWNUMBER, COLUMN_NAME, COLUMN_VALUE, ERRORMESSAGE) ' || V_QUERY;
      COMMIT;
    END IF;


    V_QUERYCOUNT := 'SELECT  COUNT(*)
      FROM GTMP_TBLU_DOC_TEMP_DETAIL A
       INNER JOIN (SELECT B.ACCOUNT_NUMBER,
                           B.OUTSTANDING_ON_BS_CCY
            FROM IFRS_NOMINATIVE B
            WHERE B.REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1)) C ON C.ACCOUNT_NUMBER = A.' || V_COLNAME_ACCOUNT || '
      WHERE  A.' || V_COLNAME || ' =  ' || V_DOWNLOADDATE || ' AND C.OUTSTANDING_ON_BS_CCY < TO_NUMBER(A.' || V_COLNAME_AMOUNT || ')';

    V_MESSAGE := 'Amount WO is more bigger than last month OS.';

    V_QUERY := 'SELECT UPLOADID,NO_URUT,''WO_AMOUNT'',' || V_COLNAME_AMOUNT || ',''' || V_MESSAGE || ''' from GTMP_TBLU_DOC_TEMP_DETAIL
                        WHERE ' || V_COLNAME_ACCOUNT || ' IN (SELECT C.ACCOUNT_NUMBER
      FROM GTMP_TBLU_DOC_TEMP_DETAIL A
       INNER JOIN (SELECT B.ACCOUNT_NUMBER,
                           B.OUTSTANDING_ON_BS_CCY
            FROM IFRS_NOMINATIVE B
            WHERE B.REPORT_DATE = ADD_MONTHS(TO_DATE(' || V_DOWNLOADDATE || ', ''YYYYMMDD''), -1)) C ON C.ACCOUNT_NUMBER = A.' || V_COLNAME_ACCOUNT || '
      WHERE  A.' || V_COLNAME || ' =  ''' || V_DOWNLOADDATE || ''' AND C.OUTSTANDING_ON_BS_CCY < TO_NUMBER(A.' || V_COLNAME_AMOUNT || '))';

    EXECUTE IMMEDIATE V_QUERYCOUNT
      INTO V_COUNT;

    IF (V_COUNT > 0)
    THEN
      EXECUTE IMMEDIATE 'INSERT INTO GTMP_TBLU_DOC_TEMP_EXCEPTION (UPLOAD_ID, ROWNUMBER, COLUMN_NAME, COLUMN_VALUE, ERRORMESSAGE) ' || V_QUERY;
      COMMIT;
    END IF;



  END;