CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_EIR_GS_PROC3
AS
 V_CURRDATE DATE;
 V_PREVDATE DATE;
 V_VLOOP2 NUMBER;
 V_VCNT NUMBER;
 V_VCNT2 NUMBER;

BEGIN
    SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,CURRENT_TIMESTAMP,'START','SP_IFRS_ACCT_EIR_GS_PROCESS3','');

	COMMIT;

	UPDATE /*+ PARALLEL(8) */ IFRS_ACCT_EIR_PAYM_GS_DATE
	SET EIR = NULL
		,NEXT_EIR = NULL
		,FINAL_EIR = NULL
		,FINAL_UNAMORT = NULL
		,NEXT_UNAMORT = NULL
		,UNAMORT_GLOSS = NULL;

	COMMIT;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS2';

	COMMIT;

	INSERT /*+ PARALLEL(8) */ INTO TMP_GS2 (
		MASTERID
		,DTMIN
		,BENEFIT
		,STAFFLOAN
		,COST_AMT
		,FEE_AMT
		,PREV_EIR
		)
	SELECT /*+ PARALLEL(8) */ B.MASTERID
		,C.DTMIN
		,B.BENEFIT
		,B.STAFFLOAN
		,B.COST_AMT
		,B.FEE_AMT
		,CASE
			WHEN D.GAIN_LOSS_CALC = 'Y'
				THEN D.PREV_EIR
			ELSE D.NPV_RATE
			END --20180417 PREPAYMENT USE PREV EIR
	FROM IFRS_ACCT_EIR_CF_ECF1 B
	JOIN IFRS_ACCT_EIR_PAYM_GS_DATE C ON C.MASTERID = B.MASTERID
	JOIN IFRS_ACCT_EIR_CF_ECF D ON D.MASTERID = C.MASTERID -- GET NPVRATE AS PREV_EIR
	;

	COMMIT;

		MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
	USING TMP_GS2 B
	ON (A.MASTERID = B.MASTERID
		AND A.PMT_DATE = B.DTMIN)
	WHEN MATCHED THEN
	UPDATE SET PREV_UNAMORT1 = CASE
			WHEN B.STAFFLOAN = 1
				AND B.BENEFIT < 0
				THEN B.BENEFIT
			WHEN B.STAFFLOAN = 1
				AND B.BENEFIT >= 0
				THEN 0
			ELSE B.FEE_AMT
			END + CASE
			WHEN B.STAFFLOAN = 1
				AND B.BENEFIT <= 0
				THEN 0
			WHEN B.STAFFLOAN = 1
				AND B.BENEFIT > 0
				THEN B.BENEFIT
			ELSE B.COST_AMT
			END
		,PREV_UNAMORT2 = 1.001 * (
			CASE
				WHEN B.STAFFLOAN = 1
					AND B.BENEFIT < 0
					THEN B.BENEFIT
				WHEN B.STAFFLOAN = 1
					AND B.BENEFIT >= 0
					THEN 0
				ELSE B.FEE_AMT
				END + CASE
				WHEN B.STAFFLOAN = 1
					AND B.BENEFIT <= 0
					THEN 0
				WHEN B.STAFFLOAN = 1
					AND B.BENEFIT > 0
					THEN B.BENEFIT
				ELSE B.COST_AMT
				END
			)
		,EIR1 = B.PREV_EIR
		,EIR2 = B.PREV_EIR;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'1'
		);

	COMMIT;

	-- 20131106 DANIEL S : NOTE UNAMORT AMOUNT FOR EACH MASTERID
	MERGE INTO IFRS_ACCT_EIR_PAYM_GS_DATE A
	USING IFRS_ACCT_EIR_PAYM_GS B
	ON (B.MASTERID = A.MASTERID AND B.PMT_DATE = A.DTMIN)
	WHEN MATCHED THEN
	UPDATE SET A.UNAMORT = B.PREV_UNAMORT1;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'2'
		);
	COMMIT;


	MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
	USING IFRS_ACCT_EIR_PAYM_GS_DATE B
	ON (A.MASTERID = B.MASTERID
		AND A.PMT_DATE = B.DTMIN
		)
	WHEN MATCHED THEN
	UPDATE SET
		 PREV_CRYAMT1 = N_OSPRN_PREV + PREV_UNAMORT1
		,PREV_CRYAMT2 = N_OSPRN_PREV + PREV_UNAMORT2
		,EIRAMT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS DECIMAL(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                         END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
               END
		,EIRAMT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                    /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                              END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
               END
		,AMORT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                   --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                   /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                         END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                   ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
              END - N_INT_PAYMENT
		,AMORT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                   --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                   /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                              END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                   ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
              END - N_INT_PAYMENT
		,UNAMORT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                     /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                         END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT + PREV_UNAMORT1
		,UNAMORT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                     /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                              END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                END - N_INT_PAYMENT + PREV_UNAMORT2
		,CRYAMT1 = (N_OSPRN_PREV + PREV_UNAMORT1) - N_PRN_PAYMENT + (
               CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    WHEN INTCALCCODE IN ( '7', '9' )
                    THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                              THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                              ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                  +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                         END
                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                    ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
               END - N_INT_PAYMENT
			)
		,CRYAMT2 = (N_OSPRN_PREV + PREV_UNAMORT2) - N_PRN_PAYMENT + (
                CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                END - N_INT_PAYMENT
			);


	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'3'
		);

	COMMIT;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_GS_DATE1';


	INSERT /*+ PARALLEL(8) */ INTO IFRS_GS_DATE1 (
		MASTERID
		,PMT_DATE
		)
	SELECT /*+ PARALLEL(8) */ A.MASTERID
		,MIN(A.PMT_DATE) DT
	FROM IFRS_ACCT_EIR_PAYM_GS A
	JOIN IFRS_ACCT_EIR_PAYM_GS_DATE B ON A.PMT_DATE > B.DTMIN
		AND A.MASTERID = B.MASTERID
	GROUP BY A.MASTERID;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'4'
		);

	COMMIT;

	V_VLOOP2 := 0;

	-- OUTER LOOP
	WHILE 1 = 1
	LOOP --LOOP
		V_VLOOP2 := V_VLOOP2 + 1;

		IF V_VLOOP2 > 30 THEN
			EXIT;
		END IF; -- MAX COUNT FOR OUTER LOOP


		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'LOOP ' || CAST(V_VLOOP2 AS VARCHAR(5))
			);
		COMMIT;

		--INNER LOOP
		WHILE 1 = 1
		LOOP --LOOP
			SELECT COUNT(*) INTO V_VCNT
			FROM IFRS_GS_DATE1;

			IF V_VCNT <= 0 THEN
				EXIT;
			END IF;

			--UPDATE
			EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS3';

			INSERT /*+ PARALLEL(8) */ INTO TMP_GS3 (
				MASTERID
				,PMT_DATE
				,EIR1
				,CRYAMT1
				,EIR2
				,CRYAMT2
				,UNAMORT1
				,UNAMORT2
				)
			SELECT /*+ PARALLEL(8) */ B.MASTERID
				,B.PMT_DATE
				,C.EIR1
				,C.CRYAMT1
				,C.EIR2
				,C.CRYAMT2
				,C.UNAMORT1
				,C.UNAMORT2
			FROM IFRS_GS_DATE1 B
			JOIN IFRS_ACCT_EIR_PAYM_GS D ON D.MASTERID = B.MASTERID
				AND D.PMT_DATE = B.PMT_DATE
			JOIN IFRS_ACCT_EIR_PAYM_GS C ON C.MASTERID = B.MASTERID
				AND C.PMT_DATE = D.PREV_PMT_DATE;

			COMMIT;

			MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
			USING TMP_GS3 C
			ON (C.PMT_DATE = A.PMT_DATE
				AND A.MASTERID = C.MASTERID
				)
			WHEN MATCHED THEN
			UPDATE
			SET PREV_UNAMORT1 = C.UNAMORT1
				,PREV_UNAMORT2 = C.UNAMORT2
				,PREV_CRYAMT1 = C.CRYAMT1
				,PREV_CRYAMT2 = C.CRYAMT2
				,EIR1 = C.EIR1
				,EIR2 = C.EIR2
				,EIRAMT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                        WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * C.EIR1 / 100 * C.CRYAMT1
                        --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                        WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * C.EIR1 / 100 * C.CRYAMT1
                        /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        WHEN INTCALCCODE IN ( '7', '9' )
                        THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                  THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * C.EIR1 / 100 * C.CRYAMT1
                                  ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * C.EIR1 / 100 * C.CRYAMT1)
                                      +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE)* C.EIR1 / 100 * C.CRYAMT1)
                             END
                        /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/

                        ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * C.EIR1 * C.CRYAMT1)
                   END
				,EIRAMT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                        WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * C.EIR2 / 100 * C.CRYAMT2
                        --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                        WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * C.EIR2 / 100 * C.CRYAMT2
                        /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        WHEN INTCALCCODE IN ( '7', '9' )
                        THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                  THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE)* C.EIR2 / 100 * C.CRYAMT2
                                  ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * C.EIR2 / 100 * C.CRYAMT2)
                                      +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE)* C.EIR2 / 100 * C.CRYAMT2)
                             END
                        /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * C.EIR2 * C.CRYAMT2)
                   END;
			COMMIT;

			INSERT INTO IFRS_AMORT_LOG (
				DOWNLOAD_DATE
				,DTM
				,OPS
				,PROCNAME
				,REMARK
				)
			VALUES (
				V_CURRDATE
				,CURRENT_TIMESTAMP
				,'DEBUG'
				,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
				,'5'
				);

			COMMIT;

			MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
			USING IFRS_GS_DATE1 B
			ON (B.PMT_DATE = A.PMT_DATE
				AND A.MASTERID = B.MASTERID
				)
			WHEN MATCHED THEN
      UPDATE
			SET AMORT1 = EIRAMT1 - N_INT_PAYMENT
				,AMORT2 = EIRAMT2 - N_INT_PAYMENT
				,UNAMORT1 = (EIRAMT1 - N_INT_PAYMENT) + PREV_UNAMORT1
				,UNAMORT2 = (EIRAMT2 - N_INT_PAYMENT) + PREV_UNAMORT2
				,CRYAMT1 = PREV_CRYAMT1 + (EIRAMT1 - N_INT_PAYMENT) - N_PRN_PAYMENT
				,CRYAMT2 = PREV_CRYAMT2 + (EIRAMT2 - N_INT_PAYMENT) - N_PRN_PAYMENT;

			COMMIT;

			INSERT INTO IFRS_AMORT_LOG (
				DOWNLOAD_DATE
				,DTM
				,OPS
				,PROCNAME
				,REMARK
				)
			VALUES (
				V_CURRDATE
				,CURRENT_TIMESTAMP
				,'DEBUG'
				,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
				,'6'
				);

			COMMIT;

			--PREPARE NEXT
			EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_GS_DATE2';


			INSERT /*+ PARALLEL(8) */ INTO IFRS_GS_DATE2 (
				MASTERID
				,PMT_DATE
				)
			SELECT /*+ PARALLEL(8) */ A.MASTERID
				,MIN(A.PMT_DATE) DT
			FROM IFRS_ACCT_EIR_PAYM_GS A
			JOIN IFRS_GS_DATE1 B ON A.PMT_DATE > B.PMT_DATE
				AND B.MASTERID = A.MASTERID
			GROUP BY A.MASTERID;

			COMMIT;

			EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_GS_DATE1';

			INSERT /*+ PARALLEL(8) */ INTO IFRS_GS_DATE1 (
				MASTERID,PMT_DATE
        )
			SELECT /*+ PARALLEL(8) */ MASTERID,PMT_DATE
			FROM IFRS_GS_DATE2;

			COMMIT;

			INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
			VALUES (V_CURRDATE,CURRENT_TIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_PROCESS3','7');

			COMMIT;
		END LOOP; --LOOP;
				--INNER LOOP
				-- GET SUCCESS UNAMORT1

		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T14';

		INSERT /*+ PARALLEL(8) */ INTO TMP_T14 (
			MASTERID
			,U1
			,E1
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,U.PREV_UNAMORT1
			,U.EIR1
		FROM IFRS_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_ACCT_EIR_PAYM_GS U ON U.PMT_DATE = B.DTMIN
			AND B.MASTERID = U.MASTERID
		JOIN IFRS_ACCT_EIR_PAYM_GS C ON C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID
			AND ABS(C.UNAMORT1) < 0.01;

		COMMIT;

		MERGE INTO IFRS_ACCT_EIR_PAYM_GS_DATE A
		USING TMP_T14 C
		ON (A.MASTERID = C.MASTERID
			AND A.UNAMORT_GLOSS IS NULL
			)
		WHEN MATCHED THEN
		UPDATE
		SET FINAL_UNAMORT = C.U1
			,EIR = C.E1;

		COMMIT;

		UPDATE /*+ PARALLEL(8) */ IFRS_ACCT_EIR_PAYM_GS_DATE
		SET UNAMORT_GLOSS = FINAL_UNAMORT
		WHERE FINAL_UNAMORT IS NOT NULL;

		COMMIT;

		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'7B'
			);

		COMMIT;

		-- SET NEXT UNAMORT
		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS1';

		INSERT /*+ PARALLEL(8) */ INTO TMP_GS1 (
			MASTERID
			,UNAMORT1
			,UNAMORT2
			,UNAMORT_GLOSS1
			,UNAMORT_GLOSS2
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,C.UNAMORT1
			,C.UNAMORT2
			,U.PREV_UNAMORT1
			,U.PREV_UNAMORT2
		FROM IFRS_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_ACCT_EIR_PAYM_GS U ON U.PMT_DATE = B.DTMIN
			AND B.MASTERID = U.MASTERID
		JOIN IFRS_ACCT_EIR_PAYM_GS C ON C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID;

		COMMIT;

		MERGE INTO IFRS_ACCT_EIR_PAYM_GS_DATE A
		USING TMP_GS1 C
		ON (A.MASTERID = C.MASTERID
			AND A.UNAMORT_GLOSS IS NULL
			)
		WHEN MATCHED THEN
		UPDATE
		SET NEXT_UNAMORT = (((C.UNAMORT2 - C.UNAMORT1) / NULLIF((C.UNAMORT_GLOSS2 - C.UNAMORT_GLOSS1), 0)) * C.UNAMORT_GLOSS1 - C.UNAMORT1) / NULLIF(((C.UNAMORT2 - C.UNAMORT1) / NULLIF((C.UNAMORT_GLOSS2 - C.UNAMORT_GLOSS1), 0)), 0);

		COMMIT;


		-- IF NEXT_UNAMORT=UNAMORT_GLOSS1 THEN PROBABLY GS HAS REACH ITS LIMIT SO TERMINATE AS SOON AS POSSIBLE
		MERGE INTO IFRS_ACCT_EIR_PAYM_GS_DATE A
		USING TMP_GS1 C
		ON (A.MASTERID = C.MASTERID
			AND A.UNAMORT_GLOSS IS NULL
			AND C.UNAMORT_GLOSS1 = A.NEXT_UNAMORT
			AND ABS(C.UNAMORT1) < 1
			)
		WHEN MATCHED THEN
		UPDATE
		SET FINAL_UNAMORT = NEXT_UNAMORT;

		COMMIT;

		UPDATE /*+ PARALLEL(8) */ IFRS_ACCT_EIR_PAYM_GS_DATE
		SET UNAMORT_GLOSS = FINAL_UNAMORT
		WHERE FINAL_UNAMORT IS NOT NULL;

		COMMIT;

		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'8'
			);

		COMMIT;

		--INIT LOOP 1
		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS2';

		INSERT /*+ PARALLEL(8) */ INTO TMP_GS2 (
			MASTERID
			,DTMIN
			,NEXT_EIR
			,STAFFLOAN
			,BENEFIT
			,FEE_AMT
			,COST_AMT
			,PREV_EIR
			,NEXT_UNAMORT
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,C.DTMIN
			,C.NEXT_EIR
			,B.STAFFLOAN
			,B.BENEFIT
			,B.FEE_AMT
			,B.COST_AMT
			,B.PREV_EIR
			,C.NEXT_UNAMORT
		FROM IFRS_ACCT_EIR_CF_ECF1 B
		JOIN IFRS_ACCT_EIR_PAYM_GS_DATE C ON C.MASTERID = B.MASTERID
			AND C.UNAMORT_GLOSS IS NULL;

		COMMIT;

		SELECT COUNT(*) INTO V_VCNT2
		FROM TMP_GS2;

		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'NOA GS : ' || CAST(V_VCNT2 AS VARCHAR(10))
			);

		COMMIT;

		MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
		USING TMP_GS2 B
		ON (B.MASTERID = A.MASTERID
			AND A.PMT_DATE = B.DTMIN
			)
		WHEN MATCHED THEN
		UPDATE
		SET PREV_UNAMORT1 = B.NEXT_UNAMORT
			,PREV_UNAMORT2 = B.NEXT_UNAMORT + (0.001 * B.NEXT_UNAMORT);

		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'9'
			);

		COMMIT;

		MERGE INTO IFRS_ACCT_EIR_PAYM_GS A
		USING IFRS_ACCT_EIR_PAYM_GS_DATE C
		ON (C.MASTERID = A.MASTERID
			AND A.PMT_DATE = C.DTMIN
			AND C.UNAMORT_GLOSS IS NULL
			)
		WHEN MATCHED THEN
		UPDATE
		SET PREV_CRYAMT1 = N_OSPRN_PREV + PREV_UNAMORT1
			,PREV_CRYAMT2 = N_OSPRN_PREV + PREV_UNAMORT2
			,EIRAMT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                      --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                      /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                           END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                 END
			,EIRAMT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                  END
			,AMORT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('1','6')THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                     /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     WHEN INTCALCCODE IN ( '7', '9' )
                     THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                               THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                               ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                   +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                          END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT
			,AMORT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                     /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     WHEN INTCALCCODE IN ( '7', '9' )
                     THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                               THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                               ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                   +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                               END
                     /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                     ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                END - N_INT_PAYMENT
			,UNAMORT1 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                       WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                       --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                       WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                       /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                           END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                       ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                  END - N_INT_PAYMENT + PREV_UNAMORT1
			,UNAMORT2 = CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                       WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                       --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                       WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                       /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                       ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                  END - N_INT_PAYMENT + PREV_UNAMORT2
			,CRYAMT1 = (N_OSPRN_PREV + PREV_UNAMORT1) - N_PRN_PAYMENT + (
                 CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                      --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                      /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1))
                           END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                  END - N_INT_PAYMENT
				)
			,CRYAMT2 = (N_OSPRN_PREV + PREV_UNAMORT2) - N_PRN_PAYMENT + (
                 CASE --WHEN INTCALCCODE IN ('2', '6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('1','6') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(360 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                      WHEN INTCALCCODE IN ('2','3') THEN CAST(I_DAYS AS NUMBER(18, 10)) / CAST(365 AS NUMBER(18, 10)) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                      /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      WHEN INTCALCCODE IN ( '7', '9' )
                      THEN CASE WHEN EXTRACT(YEAR FROM PREV_PMT_DATE)= EXTRACT(YEAR FROM PMT_DATE)
                                THEN CAST(I_DAYS AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2)
                                ELSE (CAST((FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                    +(CAST((I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)) AS BINARY_DOUBLE)/ CAST (FN_IDAYS_CURR_YEAR(PMT_DATE) AS BINARY_DOUBLE) * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT2))
                                END
                      /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                      ELSE (CAST(M AS NUMBER(18, 10)) / CAST(1200 AS NUMBER(18, 10)) * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT2))
                 END - N_INT_PAYMENT
				);


		COMMIT;


		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'9B'
			);

		COMMIT;

		EXECUTE IMMEDIATE'TRUNCATE TABLE IFRS_GS_DATE1';

		INSERT /*+ PARALLEL(8) */ INTO IFRS_GS_DATE1 (
			MASTERID
			,PMT_DATE
			)
		SELECT /*+ PARALLEL(8) */ A.MASTERID
			,MIN(A.PMT_DATE) DT
		FROM IFRS_ACCT_EIR_PAYM_GS A
		JOIN IFRS_ACCT_EIR_PAYM_GS_DATE B ON A.PMT_DATE > B.DTMIN
			AND A.MASTERID = B.MASTERID
			AND B.UNAMORT_GLOSS IS NULL
		GROUP BY A.MASTERID;

		COMMIT;

		INSERT INTO IFRS_AMORT_LOG (
			DOWNLOAD_DATE
			,DTM
			,OPS
			,PROCNAME
			,REMARK
			)
		VALUES (
			V_CURRDATE
			,CURRENT_TIMESTAMP
			,'DEBUG'
			,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
			,'10'
			);

		COMMIT;
	END LOOP; --LOOP;
			--OUTER LOOP
			-- GET SUCCESS EIR1 LAST LOOP

	MERGE INTO IFRS_ACCT_EIR_PAYM_GS_DATE A
	USING (
		SELECT B.MASTERID
			,U.PREV_UNAMORT1
			,U.EIR1
		FROM IFRS_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_ACCT_EIR_PAYM_GS U ON U.PMT_DATE = B.DTMIN
			AND B.MASTERID = U.MASTERID
		JOIN IFRS_ACCT_EIR_PAYM_GS C ON C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID
			AND ABS(C.UNAMORT1) < 1
		) B
	ON (A.MASTERID = B.MASTERID
		AND A.UNAMORT_GLOSS IS NULL
		)
	WHEN MATCHED THEN
	UPDATE
	SET FINAL_UNAMORT = B.PREV_UNAMORT1
		,EIR = B.EIR1;

	COMMIT;

	UPDATE /*+ PARALLEL(8) */ IFRS_ACCT_EIR_PAYM_GS_DATE
	SET UNAMORT_GLOSS = FINAL_UNAMORT
	WHERE FINAL_UNAMORT IS NOT NULL;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'11'
		);

	COMMIT;

	-- FAILED GOAL SEEK
	INSERT /*+ PARALLEL(8) */ INTO IFRS_ACCT_EIR_FAILED_GS3 (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		)
	SELECT V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,CURRENT_TIMESTAMP
	FROM IFRS_ACCT_EIR_PAYM_GS_DATE
	WHERE UNAMORT_GLOSS IS NULL;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'DEBUG'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,'12'
		);

	COMMIT;

	-- SUCCESS GOAL SEEK
	INSERT /*+ PARALLEL(8) */ INTO IFRS_ACCT_EIR_GS_RESULT3 (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		,EIR
		,GLOSS
		,UNAMORT
		)
	SELECT /*+ PARALLEL(8) */ V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,CURRENT_TIMESTAMP
		,EIR
		,UNAMORT - UNAMORT_GLOSS
		,UNAMORT
	FROM IFRS_ACCT_EIR_PAYM_GS_DATE
	WHERE UNAMORT_GLOSS IS NOT NULL;

	COMMIT;

	INSERT INTO IFRS_AMORT_LOG (
		DOWNLOAD_DATE
		,DTM
		,OPS
		,PROCNAME
		,REMARK
		)
	VALUES (
		V_CURRDATE
		,CURRENT_TIMESTAMP
		,'END'
		,'SP_IFRS_ACCT_EIR_GS_PROCESS3'
		,''
		);
	COMMIT;
END;