CREATE OR REPLACE PROCEDURE SP_INITIAL_VARIABLE_SELECTION (V_MODEL_ID NUMBER)
AS
BEGIN
	--Clear all results before run the variable selection

    DELETE IFRS_ME_DERIVED_VARIABLE_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_MODEL_FILTER_DTL_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_MODEL_FILTER_CORTEST_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_MODEL_FILTER_DTL_FULL_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_ADF_TEST_DTL_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_VARCLUS_MASTER_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_VARCLUS_GRAND_SUMM_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_VARCLUS_CLUSTER_SUMM_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    DELETE R_VARCLUS_INTER_CLUST_CORR_PEN
    WHERE MODEL_ID = V_MODEL_ID;

	DELETE R_VARCLUS_CLUSTER_DTL_PEN
    WHERE MODEL_ID = V_MODEL_ID;

    COMMIT;
END;