CREATE OR REPLACE PROCEDURE SP_IFRS_INSERT_ADJ_COVID(v_uploadId number)
AS
BEGIN

    DELETE FROM TBLU_ADJUSTMENT_COVID
    WHERE DOWNLOAD_DATE = (SELECT DISTINCT TO_DATE(COLUMN_1,'YYYYMMDD') DOWNLOAD_DATE FROM TBLU_DOC_TEMP_DETAIL WHERE UPLOADID = v_uploadId);
    COMMIT;

    INSERT INTO TBLU_ADJUSTMENT_COVID
    (
        DOWNLOAD_DATE,
        NO_REKENING,
        ACCOUNT_NUMBER,
        PERSEN_PENCADANGAN,
        FLAG,
        UPLOADID,
        UPLOADBY,
        UPLOADDATE,
        UPLOADHOST
    )
    SELECT DISTINCT
        TO_DATE(A.COLUMN_1,'YYYYMMDD') DOWNLOAD_DATE,
        A.COLUMN_2 AS NO_REKENING,
        B.ACCOUNT_NUMBER,
        CASE WHEN TO_NUMBER(A.COLUMN_4) < 1 THEN TO_NUMBER(A.COLUMN_4) * 100 ELSE TO_NUMBER(A.COLUMN_4) END AS PERSEN_PENCADANGAN,
        A.COLUMN_5,
        A.UPLOADID,
        C.CREATEDBY UPLOADBY,
        C.CREATEDDATE UPLOADDATE,
        C.CREATEDHOST UPLOADHOST
    FROM TBLU_DOC_TEMP_DETAIL A
    JOIN IFRS_MASTER_ACCOUNT B
    ON B.DOWNLOAD_DATE = (SELECT CURRDATE FROM IFRS_PRC_DATE)
    AND A.COLUMN_2 = SUBSTR(B.ACCOUNT_NUMBER,2,10)
    JOIN TBLT_UPLOAD_POOL C
    ON A.UPLOADID = C.PKID
    WHERE A.UPLOADID = v_uploadId;

    COMMIT;
END;