CREATE OR REPLACE PROCEDURE SP_IFRS_LIFETIME  (v_DOWNLOADDATE  DATE DEFAULT ('1-JAN-1900'))
AS
V_CURRDATE DATE;
V_PREVDATE DATE;

BEGIN

  IF v_DOWNLOADDATE = '1-JAN-1900'
  THEN
    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
  ELSE
    V_CURRDATE := v_DOWNLOADDATE;
  END IF;


/*
    SELECT CURRDATE, PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_DATE_DAY1;
*/
    DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL WHERE DOWNLOAD_DATE = V_CURRDATE; COMMIT;
    DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_HEADER WHERE DOWNLOAD_DATE = V_CURRDATE; COMMIT;
    DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL_P WHERE DOWNLOAD_DATE = V_CURRDATE; COMMIT;
    DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL_UNP WHERE DOWNLOAD_DATE = V_CURRDATE; COMMIT;

    -- REVOLVING_FLAG 0
    -- ILS NON RETAIL

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL_P
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD        ,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER,
      PRODUCT_CODE,
      ACCOUNT_STATUS
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CEIL((MONTHS_BETWEEN(RESERVED_DATE_8, A.LOAN_START_DATE)))LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.DPD_START_DATE,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER,
    A.PRODUCT_CODE,
    A.ACCOUNT_STATUS
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE AND
          A.ACCOUNT_STATUS IN ('A','C')
          AND A.REVOLVING_FLAG = 0
          AND DATA_SOURCE = 'ILS'
          AND RESERVED_VARCHAR_2 <> 'X'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL_P);

    COMMIT;

    -- ILS RETAIL

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD        ,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CEIL((MONTHS_BETWEEN(RESERVED_DATE_8, A.LOAN_START_DATE)))LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.DPD_START_DATE,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE AND
          A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 0
          AND DATA_SOURCE = 'ILS'
          AND RESERVED_VARCHAR_2 = 'X'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);

    COMMIT;

    -- CARD
    /*
    INSERT INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD        ,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CEIL((MONTHS_BETWEEN(RESERVED_DATE_8, A.LOAN_START_DATE)))LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB ,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.DPD_START_DATE,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE AND
          A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 0
          AND DATA_SOURCE = 'CRD'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);

    COMMIT;
    */
    -- REVOLVING_FLAG 1
    -- ILS NON RETAIL

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL_P
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER,
      PRODUCT_CODE,
      ACCOUNT_STATUS
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CASE WHEN RESERVED_DATE_7 IS NOT NULL AND
              RESERVED_DATE_3 IS NOT NULL
              THEN ((12 + CEIL(MONTHS_BETWEEN (RESERVED_DATE_3, RESERVED_DATE_7))))
    ELSE 12 END LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB ,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.RESERVED_DATE_7,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER,
    A.PRODUCT_CODE,
    A.ACCOUNT_STATUS
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
          --AND A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 1
          AND (RESERVED_DATE_3 IS NOT NULL OR BI_COLLECTABILITY >= '3')
          AND DATA_SOURCE = 'ILS'
          AND RESERVED_VARCHAR_2 <> 'X'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL_P);
          COMMIT;


    -- ILS RETAIL

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CASE WHEN RESERVED_DATE_7 IS NOT NULL AND
              RESERVED_DATE_3 IS NOT NULL
              THEN ((12 + CEIL(MONTHS_BETWEEN (RESERVED_DATE_3, RESERVED_DATE_7))))
    ELSE 12 END LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB ,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.RESERVED_DATE_7,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
          --AND A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 1
          AND (RESERVED_DATE_3 IS NOT NULL OR BI_COLLECTABILITY >= '3')
          AND DATA_SOURCE = 'ILS'
          AND RESERVED_VARCHAR_2 = 'X'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);
          COMMIT;

    -- CARD

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CASE WHEN RESERVED_DATE_7 IS NOT NULL AND RESERVED_DATE_3 IS NOT NULL THEN ((12 + CEIL(MONTHS_BETWEEN (RESERVED_DATE_3, RESERVED_DATE_7))))
                                                 ELSE 12 END LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.RESERVED_DATE_7,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
          --AND A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 1
          AND (RESERVED_DATE_3 IS NOT NULL OR RESERVED_AMOUNT_4 >= '5')
          AND A.DATA_SOURCE = 'CRD'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);
          COMMIT;


----------------------------------------DELETE ACTIVE ACCOUNT ON ILS REV 0

                 INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL_UNP
                 SELECT * FROM IFRS_LIFETIME_DETAIL_P
                 WHERE (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE) IN(
                 SELECT ACCOUNT_NUMBER FROM(
                 SELECT (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER,ACCOUNT_STATUS FROM IFRS_LIFETIME_DETAIL_P
                 WHERE DOWNLOAD_DATE = V_CURRDATE
                 GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE),ACCOUNT_STATUS)
                 GROUP BY ACCOUNT_NUMBER HAVING COUNT(*)>1);
                 COMMIT;

                 DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL_UNP WHERE ACCOUNT_STATUS = 'A' AND REVOLVING_FLAG = 0 AND DOWNLOAD_DATE = V_CURRDATE;COMMIT;

                 DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL_P WHERE (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE) IN(
                 SELECT ACCOUNT_NUMBER FROM(
                 SELECT (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER,ACCOUNT_STATUS FROM IFRS_LIFETIME_DETAIL_P WHERE DOWNLOAD_DATE = V_CURRDATE
                 GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE),ACCOUNT_STATUS)
                 GROUP BY ACCOUNT_NUMBER HAVING COUNT(*)>1);COMMIT;

                 DELETE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL_P WHERE REVOLVING_FLAG = 0
                 AND ACCOUNT_STATUS = 'A'
                 AND DOWNLOAD_DATE = V_CURRDATE;
                 COMMIT;


------------------------------------------ INSERT FROM PROCESS TO DETAIL REV 0 ILS

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    FROM (SELECT D.*,CEIL((MONTHS_BETWEEN(D.END_DATE, D.LOAN_START_DATE)))LIFETIME_PERIOD FROM
            (SELECT   DOWNLOAD_DATE, (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.CUSTOMER_NAME, A.CUSTOMER_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
        MAX(A.END_DATE)END_DATE, A.GOL_DEB, A.SEGMENTATION_ID, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
        MIN(A.NPL_DATE)NPL_DATE FROM IFRS_LIFETIME_DETAIL_P A  WHERE DOWNLOAD_DATE = V_CURRDATE
        GROUP BY DOWNLOAD_DATE, (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.CUSTOMER_NAME, A.CUSTOMER_NUMBER, A.DATA_SOURCE,
                 A.GOL_DEB, A.SEGMENTATION_ID, A.REVOLVING_FLAG)D)C
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    WHERE C.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL)
    AND REVOLVING_FLAG = 0;COMMIT;

------------------------------------------ INSERT FROM PROCESS TO DETAIL REV 1 ILS

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    FROM (SELECT D.*,CASE WHEN DAY_PAST_DUE_DATE IS NOT NULL AND
              NPL_DATE IS NOT NULL
              THEN ((12 + CEIL(MONTHS_BETWEEN (NPL_DATE, DAY_PAST_DUE_DATE))))
    ELSE 12 END LIFETIME_PERIOD FROM
            (SELECT   DOWNLOAD_DATE, (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.CUSTOMER_NAME, A.CUSTOMER_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
        MAX(A.END_DATE)END_DATE, A.GOL_DEB, A.SEGMENTATION_ID, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
        MIN(A.NPL_DATE)NPL_DATE FROM IFRS_LIFETIME_DETAIL_P A  WHERE DOWNLOAD_DATE = V_CURRDATE
        GROUP BY DOWNLOAD_DATE, (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.CUSTOMER_NAME, A.CUSTOMER_NUMBER, A.DATA_SOURCE,
                 A.GOL_DEB, A.SEGMENTATION_ID, A.REVOLVING_FLAG)D)C
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    WHERE C.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL)
    AND REVOLVING_FLAG = 1;   COMMIT;


------------------------------------------ UPDATE LIFETIME PERIOD ILS REV 0

  -- LIFETIME KKB
          MERGE INTO IFRS_LIFETIME_DETAIL G
          USING (SELECT D.*,CEIL((MONTHS_BETWEEN(D.END_DATE, D.LOAN_START_DATE)))LIFETIME_PERIOD , E.GOL_DEB, E.CUSTOMER_NUMBER
                    FROM (SELECT (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
                        MAX(A.END_DATE)END_DATE, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
                        MIN(A.NPL_DATE)NPL_DATE, A.SEGMENTATION_ID FROM IFRS_LIFETIME_DETAIL_P A
        GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.DATA_SOURCE, A.REVOLVING_FLAG, A.SEGMENTATION_ID)D
        JOIN (SELECT DISTINCT SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE ACCOUNT_NUMBER, END_DATE,PRODUCT_CODE,SEGMENTATION_ID,GOL_DEB, CUSTOMER_NUMBER FROM IFRS_LIFETIME_DETAIL_P) E
        ON D.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER AND D.END_DATE = E.END_DATE AND D.SEGMENTATION_ID = E.SEGMENTATION_ID
                 )B
                 ON (G.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND G.SEGMENTATION_ID = B.SEGMENTATION_ID)
                 WHEN MATCHED THEN UPDATE
                 SET G.LOAN_DUE_DATE = B.LOAN_DUE_DATE,
                     G.LOAN_START_DATE = B.LOAN_START_DATE,
                     G.END_DATE = B.END_DATE,
                     G.NPL_DATE = B.NPL_DATE,
                     G.LIFETIME_PERIOD = B.LIFETIME_PERIOD,
                     G.DAY_PAST_DUE_DATE = B.DAY_PAST_DUE_DATE,
                     G.GOL_DEB = B.GOL_DEB,
                     G.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
                     WHERE G.REVOLVING_FLAG = 0 AND G.DATA_SOURCE = 'ILS'
 and SEGMENTATION_ID  in ( 159, 161, 172, 179, 535, 536, 537, 538, 539, 540, 541, 542 )
                     ;

                     COMMIT;

  --LIFETIME NON KKB
   MERGE INTO IFRS_LIFETIME_DETAIL A
          USING (SELECT D.*,CEIL((MONTHS_BETWEEN(D.END_DATE, D.LOAN_START_DATE)))LIFETIME_PERIOD , E.GOL_DEB, E.SEGMENTATION_ID, E.CUSTOMER_NUMBER
                    FROM (SELECT (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
                        MAX(A.END_DATE)END_DATE, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
                        MIN(A.NPL_DATE)NPL_DATE FROM IFRS_LIFETIME_DETAIL_P A
        GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.DATA_SOURCE, A.REVOLVING_FLAG)D
        JOIN (SELECT DISTINCT SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE ACCOUNT_NUMBER, END_DATE,PRODUCT_CODE,SEGMENTATION_ID,GOL_DEB, CUSTOMER_NUMBER FROM IFRS_LIFETIME_DETAIL_P) E
        ON D.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER AND D.END_DATE = E.END_DATE
                 )B
                 ON (A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
                 WHEN MATCHED THEN UPDATE
                 SET A.LOAN_DUE_DATE = B.LOAN_DUE_DATE,
                     A.LOAN_START_DATE = B.LOAN_START_DATE,
                     A.END_DATE = B.END_DATE,
                     A.NPL_DATE = B.NPL_DATE,
                     A.LIFETIME_PERIOD = B.LIFETIME_PERIOD,
                     A.DAY_PAST_DUE_DATE = B.DAY_PAST_DUE_DATE,
                     A.GOL_DEB = B.GOL_DEB,
                     A.SEGMENTATION_ID = B.SEGMENTATION_ID,
                     A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
                     WHERE A.REVOLVING_FLAG = 0 AND A.DATA_SOURCE = 'ILS'
 and SEGMENTATION_ID not in ( 159, 161, 172, 179, 535, 536, 537, 538, 539, 540, 541, 542 );

  commit;

          MERGE /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL G
          USING (SELECT D.*,CEIL((MONTHS_BETWEEN(D.END_DATE, D.LOAN_START_DATE)))LIFETIME_PERIOD , E.GOL_DEB,  E.CUSTOMER_NUMBER
                    FROM (SELECT (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
                        MAX(A.END_DATE)END_DATE, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
                        MIN(A.NPL_DATE)NPL_DATE FROM IFRS_LIFETIME_DETAIL_UNP A
        GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.DATA_SOURCE, A.REVOLVING_FLAG)D
        JOIN (SELECT DISTINCT SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE ACCOUNT_NUMBER, END_DATE,PRODUCT_CODE,SEGMENTATION_ID,GOL_DEB, CUSTOMER_NUMBER FROM IFRS_LIFETIME_DETAIL_UNP) E
        ON D.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER AND D.END_DATE = E.END_DATE
                 )B
                 ON (G.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
                 WHEN MATCHED THEN UPDATE
                 SET G.LOAN_START_DATE = CASE WHEN G.LOAN_START_DATE < B.LOAN_START_DATE THEN G.LOAN_START_DATE ELSE B.LOAN_START_DATE END,
                     G.LOAN_DUE_DATE = CASE WHEN G.LOAN_DUE_DATE > B.LOAN_DUE_DATE THEN G.LOAN_DUE_DATE ELSE B.LOAN_DUE_DATE END,
                     G.END_DATE = CASE WHEN G.END_DATE > B.END_DATE THEN G.END_DATE ELSE B.END_DATE END
                     WHERE G.REVOLVING_FLAG = 0 AND G.DATA_SOURCE = 'ILS'
                     ;

                     COMMIT;

        UPDATE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL D
        SET LIFETIME_PERIOD = CEIL((MONTHS_BETWEEN(D.END_DATE, D.LOAN_START_DATE)))
        WHERE DATA_SOURCE = 'ILS' AND REVOLVING_FLAG = 0;COMMIT;

------------------------------------------ UPDATE LIFETIME PERIOD ILS REV 1

          MERGE /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_DETAIL A
          USING (SELECT D.*,CASE WHEN DAY_PAST_DUE_DATE IS NOT NULL AND
                                NPL_DATE IS NOT NULL
                                THEN ((12 + CEIL(MONTHS_BETWEEN (NPL_DATE, DAY_PAST_DUE_DATE))))
                                ELSE 12 END LIFETIME_PERIOD
                    FROM (SELECT  (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE)ACCOUNT_NUMBER, A.CUSTOMER_NUMBER, A.DATA_SOURCE, MAX(A.LOAN_DUE_DATE)LOAN_DUE_DATE, MIN(A.LOAN_START_DATE)LOAN_START_DATE,
                        MAX(A.END_DATE)END_DATE, A.REVOLVING_FLAG, MIN(A.DAY_PAST_DUE_DATE)DAY_PAST_DUE_DATE,
                        MIN(A.NPL_DATE)NPL_DATE FROM IFRS_LIFETIME_DETAIL_P A
        GROUP BY (SUBSTR(ACCOUNT_NUMBER,1,11)||PRODUCT_CODE), A.CUSTOMER_NUMBER, A.DATA_SOURCE, A.REVOLVING_FLAG)D
                 )B
                 ON (A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
                 WHEN MATCHED THEN UPDATE
                 SET A.LOAN_DUE_DATE = B.LOAN_DUE_DATE,
                     A.LOAN_START_DATE = B.LOAN_START_DATE,
                     A.END_DATE = B.END_DATE,
                     A.NPL_DATE = B.NPL_DATE,
                     A.LIFETIME_PERIOD = B.LIFETIME_PERIOD,
                     A.DAY_PAST_DUE_DATE = B.DAY_PAST_DUE_DATE
                     WHERE A.REVOLVING_FLAG = 1 AND A.DATA_SOURCE = 'ILS';
                     COMMIT;


          UPDATE /*+ PARALLEL(12) */ IFRS_LIFETIME_DETAIL
            SET LIFETIME_PERIOD = CASE WHEN REVOLVING_FLAG = '1' THEN CASE WHEN LIFETIME_PERIOD <= 12 THEN 12 ELSE LIFETIME_PERIOD END
                                       WHEN REVOLVING_FLAG = '0' THEN CASE WHEN LIFETIME_PERIOD <= 0 THEN 0 ELSE LIFETIME_PERIOD END
                                       WHEN REVOLVING_FLAG = '0' THEN CASE WHEN LIFETIME_PERIOD <= 12 THEN 12 ELSE LIFETIME_PERIOD END
                                  END
                                       ;COMMIT;

        INSERT /*+ PARALLEL(IFRS_LIFETIME_DETAIL,4) */
            INTO IFRS.IFRS_LIFETIME_DETAIL (
              DOWNLOAD_DATE, ACCOUNT_NUMBER, CUSTOMER_NAME,
              CUSTOMER_NUMBER, DATA_SOURCE, LOAN_DUE_DATE,
              LOAN_START_DATE, END_DATE, LIFETIME_PERIOD,
              GOL_DEB, SEGMENTATION_ID, REVOLVING_FLAG,
              DAY_PAST_DUE_DATE, NPL_DATE,
              CREATEDBY, CREATEDDATE, CREATEDHOST,
              UPDATEDBY, UPDATEDDATE, UPDATEDHOST
            )
            SELECT
              a.DOWNLOAD_DATE,
              a.ACCOUNT_NUMBER,
              a.CUSTOMER_NAME,
              a.CUSTOMER_NUMBER,
              a.DATA_SOURCE,
              a.LOAN_DUE_DATE,
              a.LOAN_START_DATE,
              a.END_DATE,
              a.LIFETIME_PERIOD,
              a.GOL_DEB,
              '179'                                                                                         AS SEGMENTATION_ID,
              a.REVOLVING_FLAG,
              a.DAY_PAST_DUE_DATE,
              a.NPL_DATE,
              'SYSTEM'                                                                                            AS CREATEDBY,
              SYSDATE                                                                                           AS CREATEDDATE,
              'SYSTEM'                                                                                          AS CREATEDHOST,
              NULL AS UPDATEDBY,
              NULL AS UPDATEDDATE,
              NULL AS UPDATEDHOST
            FROM IFRS.IFRS_LIFETIME_DETAIL a
            WHERE a.SEGMENTATION_ID IN ('535','537')
              AND a.DOWNLOAD_DATE = V_CURRDATE
              AND a.ACCOUNT_NUMBER IN (
                SELECT ACCOUNT_NUMBER
                FROM IFRS.IFRS_LIFETIME_DETAIL b
                WHERE b.SEGMENTATION_ID IN ('535','537')
                  AND b.DOWNLOAD_DATE = V_CURRDATE
                GROUP BY ACCOUNT_NUMBER
                HAVING COUNT(*) = 1
              )
              AND NOT EXISTS (
                SELECT 1
                FROM IFRS.IFRS_LIFETIME_DETAIL b
                WHERE b.ACCOUNT_NUMBER  = a.ACCOUNT_NUMBER
                  AND b.DOWNLOAD_DATE   = a.DOWNLOAD_DATE
                  AND b.SEGMENTATION_ID = '179'
              );

            ------------------------------------------------------------------
            -- B: seg 539/541 - KKB RODA 2
            ------------------------------------------------------------------
            INSERT /*+ PARALLEL(IFRS_LIFETIME_DETAIL,4) */
            INTO IFRS.IFRS_LIFETIME_DETAIL (
              DOWNLOAD_DATE, ACCOUNT_NUMBER, CUSTOMER_NAME,
              CUSTOMER_NUMBER, DATA_SOURCE, LOAN_DUE_DATE,
              LOAN_START_DATE, END_DATE, LIFETIME_PERIOD,
              GOL_DEB, SEGMENTATION_ID, REVOLVING_FLAG,
              DAY_PAST_DUE_DATE, NPL_DATE,
              CREATEDBY, CREATEDDATE, CREATEDHOST,
              UPDATEDBY, UPDATEDDATE, UPDATEDHOST
            )
            SELECT
              a.DOWNLOAD_DATE,
              a.ACCOUNT_NUMBER,
              a.CUSTOMER_NAME,
              a.CUSTOMER_NUMBER,
              a.DATA_SOURCE,
              a.LOAN_DUE_DATE,
              a.LOAN_START_DATE,
              a.END_DATE,
              a.LIFETIME_PERIOD,
              a.GOL_DEB,
              '172'                                                                                         AS SEGMENTATION_ID,
              a.REVOLVING_FLAG,
              a.DAY_PAST_DUE_DATE,
              a.NPL_DATE,
              'SYSTEM'                                                                                            AS CREATEDBY,
              SYSDATE                                                                                           AS CREATEDDATE,
              'SYSTEM'                                                                                          AS CREATEDHOST,
              NULL AS UPDATEDBY,
              NULL AS UPDATEDDATE,
              NULL AS UPDATEDHOST
            FROM IFRS.IFRS_LIFETIME_DETAIL a
            WHERE a.SEGMENTATION_ID IN ('539','541')
              AND a.DOWNLOAD_DATE = V_CURRDATE
              AND a.ACCOUNT_NUMBER IN (
                SELECT ACCOUNT_NUMBER
                FROM IFRS.IFRS_LIFETIME_DETAIL b
                WHERE b.SEGMENTATION_ID IN ('539','541')
                  AND b.DOWNLOAD_DATE = V_CURRDATE
                GROUP BY ACCOUNT_NUMBER
                HAVING COUNT(*) = 1
              )
              AND NOT EXISTS (
                SELECT 1
                FROM IFRS.IFRS_LIFETIME_DETAIL b
                WHERE b.ACCOUNT_NUMBER  = a.ACCOUNT_NUMBER
                  AND b.DOWNLOAD_DATE   = a.DOWNLOAD_DATE
                  AND b.SEGMENTATION_ID = '172'
              );

        COMMIT;

        INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_HEADER (PKID,
                                          DOWNLOAD_DATE,
                                          LIFETIME_SEGMENT_ID,
                                          LIFETIME_CONFIG_ID,
                                          LIFETIME_SEGMENT,
                                          LIFETIME_PERIOD)
             SELECT 0,
                    V_CURRDATE,
                    B.SEGMENTATION_ID,
                    C.PKID,
                    C.LIFETIME_RULE_NAME,
                    --CASE WHEN NVL(LIFETIME_OVERRIDE,0) <> 0 THEN LIFETIME_OVERRIDE ELSE
                    CASE
                       WHEN C.LIFETIME_METHOD = 1 THEN LM1
                       WHEN C.LIFETIME_METHOD = 2 THEN LM2
                       WHEN C.LIFETIME_METHOD = 3 THEN LM3
                    END --END
                       LIFETIME_CALCULATION
               FROM  (  SELECT SEGMENTATION_ID,
                              (CEIL (AVG (LIFETIME_PERIOD))) LM1,
                              (ROUND (
                                  PERCENTILE_CONT (0.9) WITHIN GROUP (ORDER BY LIFETIME_PERIOD)))
                                 LM2,
                               (CEIL (AVG (LIFETIME_PERIOD))) LM3
                         FROM IFRS_LIFETIME_DETAIL
                     GROUP BY SEGMENTATION_ID)B
                          JOIN IFRS_LIFETIME_RULES_CONFIG C
                          ON B.SEGMENTATION_ID = C.SEGMENTATION_ID
           ORDER BY B.SEGMENTATION_ID, C.PKID;

        COMMIT;

 INSERT /*+ PARALLEL(12) */ INTO IFRS_LIFETIME_HEADER (PKID,
                                          DOWNLOAD_DATE,
                                          LIFETIME_SEGMENT_ID,
                                          LIFETIME_CONFIG_ID,
                                          LIFETIME_SEGMENT,
                                          LIFETIME_PERIOD)
             SELECT 0,
                    V_CURRDATE,
                    C.SEGMENTATION_ID,
                    C.PKID,
                    C.LIFETIME_RULE_NAME,
                    12
               FROM IFRS_LIFETIME_RULES_CONFIG C
               WHERE PKID NOT IN (SELECT LIFETIME_CONFIG_ID FROM IFRS_LIFETIME_HEADER WHERE DOWNLOAD_DATE = V_CURRDATE);COMMIT;

END;