CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_IA_INITIAL_RUN(v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
    V_CURRDATE  DATE;
BEGIN
    IF v_DOWNLOADDATE = '1-JAN-1900' THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATE;
    END IF;

    INSERT INTO TBLT_PAYMENTEXPECTED
    (
        PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        ESTIMATED_REALIZE_DATE,
        ESTIMATED_PRIN_AMOUNT,
        ESTIMATED_INT_AMOUNT,
        ESTIMATED_COLL_AMOUNT,
        ESTIMATED_AMOUNT,
        DISCOUNT_RATE,
        EIR,
        INTEREST_RATE,
        PV_MONTH,
        PV_AMOUNT,
        ECL_AMOUNT,
        BEGIN_BALANCE,
        INTEREST_UNWINDING,
        ENDING_BALANCE,
        UNWIND_BALANCE,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT
        0 PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        ESTIMATED_REALIZE_DATE,
        ESTIMATED_PRIN_AMOUNT,
        ESTIMATED_INT_AMOUNT,
        ESTIMATED_COLL_AMOUNT,
        ESTIMATED_AMOUNT,
        DISCOUNT_RATE,
        EIR,
        INTEREST_RATE,
        PV_MONTH,
        PV_AMOUNT,
        ECL_AMOUNT,
        BEGIN_BALANCE,
        INTEREST_UNWINDING,
        ENDING_BALANCE,
        UNWIND_BALANCE,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM TBLT_PAYMENTEXPECTED_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = 'C'
        AND RESERVED_DATE_2 = V_CURRDATE
    );

    COMMIT;

    INSERT INTO TBLT_PAYMENTEXPECTEDH
    (
        PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        CURRENCY,
        OUTSTANDING,
        EAD,
        COLLATERAL_AMOUNT,
        PV_AMOUNT,
        ECL_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT 0 PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        CURRENCY,
        OUTSTANDING,
        EAD,
        COLLATERAL_AMOUNT,
        PV_AMOUNT,
        ECL_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM TBLT_PAYMENTEXPECTEDH_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = 'C'
        AND RESERVED_DATE_2 = V_CURRDATE
    );

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDED
    SELECT * FROM IFRS_IA_OVERRIDED_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = 'C'
        AND RESERVED_DATE_2 = V_CURRDATE
    );

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDEH
    SELECT * FROM IFRS_IA_OVERRIDEH_HIST
    WHERE RESERVED_VARCHAR_1 = 'C'
    AND RESERVED_DATE_2 = V_CURRDATE;

    COMMIT;

    UPDATE IFRS_IA_OVERRIDEH_HIST
    SET RESERVED_VARCHAR_1 = NULL,
        RESERVED_DATE_1 = NULL,
        RESERVED_DATE_2 = NULL
    WHERE RESERVED_VARCHAR_1 = 'C'
    AND RESERVED_DATE_2 = V_CURRDATE;

    COMMIT;

END;