CREATE OR REPLACE PROCEDURE SP_IFRS_AMORT_SEQUENCE_K2
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_SPNAME VARCHAR2(100);
  V_VCNT NUMBER(19);
  V_SESSIONID VARCHAR2(100);
  V_ERRM VARCHAR2(255);
  V_ERRORMESSAGEDESCRIPTION NVARCHAR2(4000) ;
  V_DATEPROCESS VARCHAR2(100) ;

BEGIN

    V_SESSIONID := SYS_GUID();

    SELECT  CURRDATE ,  PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM    IFRS_PRC_DATE_AMORT ;
    /*
    V_SPNAME := 'SP_IFRS_LBM_PAYM_SCHD_SRC' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --V_SPNAME := 'SP_LBM_SYNC_PAYM_CORE' ;
    --SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ECF_MAIN' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_STAFF_BENEFIT_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ACF_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_UPD_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_LAST_ACF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');
    */

    V_SPNAME := 'SP_IFRS_ACCT_SL_ACF_ACCRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_UPD_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_LAST_ACF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');



    -- update unamortized pma SL then EIR
    V_SPNAME := 'SP_IFRS_ACCT_SL_UPD_UNAMRT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_JRNL_INTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_EIR_UPD_UNAMRT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    -- MARKET TO MARKET
    V_SPNAME := 'SP_IFRS_PAYM_SCHD_MTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    -- JOURNAL SUMMARY
    V_SPNAME := 'SP_IFRS_ACCT_JRNL_INTM_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_CFID_JRNL_INTM_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_JRNL_ACF_ABN_ADJ' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --JOURNAL DATA
    V_SPNAME := 'SP_IFRS_ACCT_JOURNAL_DATA' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --ADDED BY VIVI 15 FEB 2019
    V_SPNAME := 'SP_IFRS_ACCT_JOURNAL_DATA_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_JRNL_DATA_MTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --GL OUTBOUND
    V_SPNAME := 'SP_IFRS_GL_OUTBOUND' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --IFRS RECON REPORT  20180501
    V_SPNAME := 'SP_IFRS_REPORT_RECON' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --IFRS LBM RECON REPORT 20180915
    V_SPNAME := 'SP_IFRS_LBM_REPORT_RECON' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --[SP_IFRS_NOMINATIF]  20180501
    V_SPNAME := 'SP_IFRS_NOMINATIF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --CHECK AMORT
    V_SPNAME := 'SP_IFRS_CHECK_AMORT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --CHECK AMORT NO CF
    V_SPNAME := 'SP_IFRS_CHECK_AMORT_NOCF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --ADDED BY VIVI 15 FEB 2019
    V_SPNAME := 'SP_IFRS_RECON_MANUAL' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --DATA ARCHIVING.. SEMENTARA NEMPEL DI SEQUENCE
    --set @V_SPNAME = 'SP_PSAK_DATA_ARCHIVING';
    --exec SP_IFRS_EXEC_AND_LOG_PROCESS @V_SPNAME, 'AMT'

    INSERT  INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE , DTM , OPS , PROCNAME , REMARK )
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_AMORT_SEQUENCE' , ''  );

    COMMIT;

--    SELECT COUNT(*)
--    INTO V_VCNT
--    FROM IFRS_CHECK_AMORT
--    WHERE ABS(CONTROL_AMT) > 1;
--
--    IF V_VCNT > 0 THEN
--      RAISE_APPLICATION_ERROR(-20000, 'CHECK AMORT ERROR !');
--      RETURN;
--    END IF;

    INSERT  INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE , DTM , OPS , PROCNAME , REMARK )
    VALUES  (V_CURRDATE , SYSTIMESTAMP , 'END' , 'SP_IFRS_AMORT_SEQUENCE' , '' );

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN

    V_DATEPROCESS := TO_CHAR (SYSTIMESTAMP, 'MON DD, YYYY');


    UPDATE  IFRS_STATISTIC
    SET END_DATE = SYSTIMESTAMP ,
        ISCOMPLETE = 'N' ,
        REMARK = V_ERRM
    WHERE   DOWNLOAD_DATE = V_CURRDATE
    AND SP_NAME = V_SPNAME ;


    UPDATE  IFRS_PRC_DATE_AMORT
    SET     BATCH_STATUS = 'ERROR!!..' ,
    REMARK = V_ERRM ,
    LAST_PROCESS_DATE = SYSTIMESTAMP ;

    V_ERRORMESSAGEDESCRIPTION := V_SPNAME || ' ( ' || V_DATEPROCESS ;

    RAISE_APPLICATION_ERROR (-20002, 'ERROR MESSAGE ' || V_ERRORMESSAGEDESCRIPTION || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);


    END;