CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_EIR_GS_ECF_INSER4
AS
  V_CURRDATE    DATE;
  V_PREVDATE    DATE;
  V_VI NUMBER(19);
  V_ROUND NUMBER(10);
  V_FUNCROUND NUMBER(10);
  V_EXISTS NUMBER(1);
  V_SCHEMA  VARCHAR2(30);

BEGIN

    -- daniel s : zero unamort with no cost fee
    SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    SELECT USER INTO V_SCHEMA FROM DUAL;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','' );

    COMMIT;


    BEGIN
      SELECT CAST(VALUE1 AS NUMBER(10))
           , CAST(VALUE2 AS NUMBER(10))
      INTO V_ROUND, V_FUNCROUND
      FROM TBLM_COMMONCODEDETAIL
      WHERE COMMONCODE = 'SCM003';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_ROUND := 6;
        V_FUNCROUND:=1;
    END;

    -- insert initial row prevdate=pmtdate
    EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF1';
    EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF2';

    COMMIT;

    -- prepare index
    --execute immediate 'drop index psak_eir_paym_idx1';
    --execute immediate 'create index psak_eir_paym_idx1 on IFRS_ACCT_EIR_PAYM(masterid,pmt_date,prev_pmt_date)';
    --execute immediate 'drop index psak_eir_cf_ecf_idx1';
    --execute immediate 'create index psak_eir_cf_ecf_idx1 on IFRS_ACCT_EIR_CF_ECF(masterid)';
    --execute immediate 'drop index psak_goalseek_result_idx14';
    --execute immediate 'create index psak_goalseek_result_idx14 on IFRS_ACCT_EIR_GOALSEEK_RESULT4(masterid,download_date)';

    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF2
    (
        MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
        ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
        ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
        ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
        ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
        ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
        ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
        ,N_FEE_AMT
        ,N_COST_AMT
    )
    SELECT /*+ PARALLEL(12) */
        A.MASTERID,V_CURRDATE,A.N_LOAN_AMT,A.N_INT_RATE, C.EIR,A.STARTAMORTDATE,A.ENDAMORTDATE
        ,A.GRACEDATE,A.DISB_PERCENTAGE,A.DISB_AMOUNT,A.PLAFOND,A.PAYMENTCODE,A.INTCALCCODE,A.PAYMENTTERM
        ,A.ISGRACE,A.PREV_PMT_DATE,A.PMT_DATE,A.I_DAYS,A.I_DAYS
        ,A.N_OSPRN_PREV,A.N_INSTALLMENT,A.N_PRN_PAYMENT,A.N_INT_PAYMENT,A.N_OSPRN
        ,0 + A.N_OSPRN N_FAIRVALUE_PREV        --zero unamort
        ,0 N_EFF_INT_AMT
        ,0 + A.N_OSPRN N_FAIRVALUE            --zero unamort
        ,0  N_UNAMORT_AMT_PREV                --zero unamort
        ,0 N_AMORT_AMT
        ,0 N_UNAMORT_AMT
        ,0 N_COST_UNAMORT_AMT_PREV
        ,0 N_COST_AMORT_AMT
        ,0 N_COST_UNAMORT_AMT
        ,0 N_FEE_UNAMORT_AMT_PREV
        ,0 N_FEE_AMORT_AMT
        ,0 N_FEE_UNAMORT_AMT
        ,0 N_FEE_AMT
        ,0 N_COST_AMT_PREV
    FROM IFRS_ACCT_EIR_PAYM A
    JOIN IFRS_ACCT_EIR_CF_ECF B ON B.MASTERID=A.MASTERID
    JOIN IFRS_ACCT_EIR_GOALSEEK_RESULT4 C ON C.DOWNLOAD_DATE=V_CURRDATE AND C.MASTERID=A.MASTERID
    WHERE A.PMT_DATE=A.PREV_PMT_DATE;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','1');

    COMMIT;


    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_NOCF(
        MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
        ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
        ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
        ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
        ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
        ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
        ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
    )
    SELECT /*+ PARALLEL(12) */
        MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
        ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
        ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,PMT_DATE -PREV_PMT_DATE AS I_DAYS2
        ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
        ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
        ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
        ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
    FROM IFRS_ACCT_EIR_ECF2;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','2');

    COMMIT;

    -- prepare temp table for looping
    SELECT COUNT(*) INTO V_EXISTS
    FROM user_indexes
    WHERE index_name = 'IDX_IFRS_ACCT_EIR_PAYM';

    IF V_EXISTS = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_ACCT_EIR_PAYM';
    END IF;

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_ACCT_EIR_PAYM ON IFRS_ACCT_EIR_PAYM (PMT_DATE) TABLESPACE IFRS_IDX_TBS NOLOGGING';

    DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>V_SCHEMA, TABNAME=>'IFRS_ACCT_EIR_PAYM');
    DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>V_SCHEMA, TABNAME=>'IFRS_ACCT_EIR_PAYM',DEGREE=>2);

    EXECUTE IMMEDIATE 'truncate table TMP_T9';

    INSERT /*+ PARALLEL(12) */ INTO TMP_T9(MASTERID,PMTDATE)
    SELECT /*+ PARALLEL(12) */ MASTERID,PMT_DATE
    FROM IFRS_ACCT_EIR_PAYM WHERE PMT_DATE=PREV_PMT_DATE;

    SELECT COUNT(*) INTO V_EXISTS
    FROM user_indexes
    WHERE index_name = 'IDX_IFRS_ACCT_EIR_PAYM';

    IF V_EXISTS = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_ACCT_EIR_PAYM';
    END IF;

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_ACCT_EIR_PAYM ON IFRS_ACCT_EIR_PAYM (MASTERID, PMT_DATE) TABLESPACE IFRS_IDX_TBS NOLOGGING';

    DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>V_SCHEMA, TABNAME=>'IFRS_ACCT_EIR_PAYM');
    DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>V_SCHEMA, TABNAME=>'IFRS_ACCT_EIR_PAYM',DEGREE=>2);

    EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF_T2';

    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_T2(MASTERID,PMTDATE)
    SELECT /*+ PARALLEL(12) */ A.MASTERID,MIN(A.PMT_DATE) AS PMTDATE
    FROM IFRS_ACCT_EIR_PAYM A
    JOIN TMP_T9 B ON B.MASTERID=A.MASTERID AND A.PMT_DATE>B.PMTDATE
    GROUP BY A.MASTERID;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','3');

    COMMIT;

    SELECT COUNT(*)
    INTO V_VI
    FROM IFRS_ACCT_EIR_ECF_T2;

    WHILE V_VI>0
    LOOP --loop
        INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
        VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','4');

        EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF1';

        COMMIT;

        -- prepare index
        --execute immediate 'drop index PSAK_EIR_ECF_T2_IDX1';
        --execute immediate 'create index PSAK_EIR_ECF_T2_IDX1 on IFRS_ACCT_EIR_ECF_T2(masterid,pmtdate)';
        --execute immediate 'drop index psak_eir_ecf2_IDX1';
        --execute immediate 'create index psak_eir_ecf2_IDX1 on IFRS_ACCT_EIR_ECF2(masterid)';

        INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF1(
            MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
            ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
            ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
            ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
            ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
            ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
            ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
            ,N_FEE_AMT,N_COST_AMT
        )
        SELECT /*+ PARALLEL(12) */
            A.MASTERID,V_CURRDATE,A.N_LOAN_AMT,A.N_INT_RATE, C.N_EFF_INT_RATE ,A.STARTAMORTDATE,A.ENDAMORTDATE
            ,A.GRACEDATE,A.DISB_PERCENTAGE,A.DISB_AMOUNT,A.PLAFOND,A.PAYMENTCODE,A.INTCALCCODE,A.PAYMENTTERM
            ,A.ISGRACE,A.PREV_PMT_DATE,A.PMT_DATE,A.I_DAYS,A.I_DAYS
            ,A.N_OSPRN_PREV,A.N_INSTALLMENT,A.N_PRN_PAYMENT,A.N_INT_PAYMENT,A.N_OSPRN
            ,C.N_FAIRVALUE N_FAIRVALUE_PREV
            ,ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                        WHEN A.INTCALCCODE IN('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                        WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                        /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        WHEN A.INTCALCCODE IN ( '7', '9' )
                        THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                  THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100 * C.N_FAIRVALUE
                                  ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                       +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                             END
                        /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                        END,V_ROUND) AS N_EFF_INT_AMT
            ,C.N_FAIRVALUE - A.N_PRN_PAYMENT +
                ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                           WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                           /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                          WHEN A.INTCALCCODE IN ( '7', '9' )
                          THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                    THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                    ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                         +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                               END
                          /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                           WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                           ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                           END,V_ROUND) - A.N_INT_PAYMENT + A.DISB_AMOUNT AS N_FAIRVALUE
            ,C.N_UNAMORT_AMT N_UNAMORT_AMT_PREV
            ,ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                        WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                        /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        WHEN A.INTCALCCODE IN ( '7', '9' )
                        THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                  THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                  ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                       +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                             END
                        /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                        WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                        ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                        END,V_ROUND) - A.N_INT_PAYMENT AS N_AMORT_AMT
            , C.N_UNAMORT_AMT +
                ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                           WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                           /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                          WHEN A.INTCALCCODE IN ( '7', '9' )
                          THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                    THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                    ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                         +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                               END
                          /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                           WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                           ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                           END,V_ROUND) - A.N_INT_PAYMENT AS N_UNAMORT_AMT
            ,C.N_COST_UNAMORT_AMT N_COST_UNAMORT_AMT_PREV
            ,CASE WHEN C.N_FEE_AMT + C.N_COST_AMT = 0 THEN 0
                ELSE(ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                WHEN A.INTCALCCODE IN ( '7', '9' )
                                THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                          THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                          ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                               +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                     END
                                /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                                ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                                END,V_ROUND) - A.N_INT_PAYMENT) * C.N_COST_AMT / (C.N_FEE_AMT + C.N_COST_AMT)
                                END AS N_COST_AMORT_AMT
            , C.N_COST_UNAMORT_AMT +
                CASE WHEN C.N_FEE_AMT + C.N_COST_AMT = 0 THEN 0
                ELSE (ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                 WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                 /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                WHEN A.INTCALCCODE IN ( '7', '9' )
                                THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                          THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                          ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                               +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                     END
                                /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                 WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                                 ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                                 END,V_ROUND) - A.N_INT_PAYMENT) * C.N_COST_AMT / (C.N_FEE_AMT + C.N_COST_AMT)
                                 END AS N_COST_UNAMORT_AMT
            ,C.N_FEE_UNAMORT_AMT N_FEE_UNAMORT_AMT_PREV
            ,CASE WHEN C.N_FEE_AMT + C.N_COST_AMT = 0 THEN 0
                  ELSE (ROUND(CASE  WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                    WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                    /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                    WHEN A.INTCALCCODE IN ( '7', '9' )
                                    THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                              THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                              ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                                   +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                         END
                                    /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                    WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                                    ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                                    END,V_ROUND) - A.N_INT_PAYMENT) * C.N_FEE_AMT / (C.N_FEE_AMT + C.N_COST_AMT)
                                    END AS N_FEE_AMORT_AMT
            ,C.N_FEE_UNAMORT_AMT +
             CASE WHEN C.N_FEE_AMT + C.N_COST_AMT = 0 THEN 0
                  ELSE (ROUND(CASE WHEN A.INTCALCCODE IN('1','6') THEN A.I_DAYS / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                   WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE
                                   /******* 24 JAN 2019 - START ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                  WHEN A.INTCALCCODE IN ( '7', '9' )
                                  THEN CASE WHEN EXTRACT(YEAR FROM A.PREV_PMT_DATE)= EXTRACT(YEAR FROM A.PMT_DATE)
                                            THEN A.I_DAYS/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE
                                            ELSE ((FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(A.PREV_PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                                 +((A.I_DAYS - (FN_LASTDAY_OF_YEAR(A.PREV_PMT_DATE)-A.PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(A.PMT_DATE)* C.N_EFF_INT_RATE / 100* C.N_FAIRVALUE)
                                       END
                                  /******* 24 JAN 2019 - END ADDED BY VIVI, FOR ICC 7 AND 9 *******/
                                   WHEN A.INTCALCCODE='4' THEN C.N_EFF_INT_RATE/C.N_INT_RATE * A.N_INT_PAYMENT
                                   ELSE (30 * A.M / 360 * C.N_EFF_INT_RATE/100 * C.N_FAIRVALUE)
                                   END,V_ROUND) - A.N_INT_PAYMENT) * C.N_FEE_AMT / (C.N_FEE_AMT + C.N_COST_AMT)
                                   END AS N_FEE_UNAMORT_AMT
            ,C.N_FEE_AMT
            ,C.N_COST_AMT
        FROM IFRS_ACCT_EIR_PAYM A
        JOIN IFRS_ACCT_EIR_ECF_T2 B ON B.MASTERID=A.MASTERID AND B.PMTDATE=A.PMT_DATE
        JOIN IFRS_ACCT_EIR_ECF2 C ON C.MASTERID=B.MASTERID;

        COMMIT;


        INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
        VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','5');


        -- insert to ecf
        INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_NOCF(
            MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
            ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
            ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
            ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
            ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
            ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
            ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
        )
        SELECT /*+ PARALLEL(12) */
            MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
            ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
            ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,PMT_DATE -PREV_PMT_DATE AS I_DAYS2
            ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
            ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
            ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
            ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
        FROM IFRS_ACCT_EIR_ECF1;
        COMMIT;
        INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
        VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','6');


        -- insert to ecf2
        EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF2';

        INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF2(
            MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
            ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
            ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
            ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
            ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
            ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
            ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
            ,N_FEE_AMT,N_COST_AMT
        )
        SELECT /*+ PARALLEL(12) */
            MASTERID,DOWNLOAD_DATE,N_LOAN_AMT,N_INT_RATE,N_EFF_INT_RATE,STARTAMORTDATE,ENDAMORTDATE
            ,GRACEDATE,DISB_PERCENTAGE,DISB_AMOUNT,PLAFOND,PAYMENTCODE,INTCALCCODE,PAYMENTTERM
            ,ISGRACE,PREV_PMT_DATE,PMT_DATE,I_DAYS,I_DAYS2
            ,N_OSPRN_PREV,N_INSTALLMENT,N_PRN_PAYMENT,N_INT_PAYMENT,N_OSPRN,N_FAIRVALUE_PREV
            ,N_EFF_INT_AMT,N_FAIRVALUE,N_UNAMORT_AMT_PREV,N_AMORT_AMT,N_UNAMORT_AMT
            ,N_COST_UNAMORT_AMT_PREV,N_COST_AMORT_AMT,N_COST_UNAMORT_AMT
            ,N_FEE_UNAMORT_AMT_PREV,N_FEE_AMORT_AMT,N_FEE_UNAMORT_AMT
            ,N_FEE_AMT,N_COST_AMT
        FROM IFRS_ACCT_EIR_ECF1;

        COMMIT;

        INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
        VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','7');

        -- next cycle prepare #t2
        EXECUTE IMMEDIATE 'truncate table IFRS_ACCT_EIR_ECF_T2';

        COMMIT;

        INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_T2(MASTERID,PMTDATE)
        SELECT /*+ PARALLEL(12) */ A.MASTERID,MIN(A.PMT_DATE) AS PMTDATE
        FROM IFRS_ACCT_EIR_PAYM A
        JOIN IFRS_ACCT_EIR_ECF1 B ON B.MASTERID=A.MASTERID AND A.PMT_DATE>B.PMT_DATE
        GROUP BY A.MASTERID;

        COMMIT;
        -- assign var @i
        SELECT COUNT(*) INTO V_VI FROM IFRS_ACCT_EIR_ECF_T2;


        INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
        VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','8');

        COMMIT;
    END LOOP;
    --loop;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_ACCT_EIR_GS_ECF_INSER4','');

    COMMIT;

END;