CREATE OR REPLACE PROCEDURE SP_IFRS_AMORT_SEQUENCE
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_SPNAME VARCHAR2(100);
  V_VCNT NUMBER(19);
  V_SESSIONID VARCHAR2(100);
  V_ERRM VARCHAR2(255);
  V_ERRORMESSAGEDESCRIPTION NVARCHAR2(4000) ;
  V_DATEPROCESS VARCHAR2(100) ;

BEGIN

    EXECUTE IMMEDIATE 'alter session set temp_undo_enabled=true';
    EXECUTE IMMEDIATE 'alter session enable parallel dml';

    V_SESSIONID := SYS_GUID();

    SELECT  CURRDATE ,  PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM    IFRS_PRC_DATE_AMORT ;

    UPDATE IFRS_PRC_DATE_AMORT
    SET SESSIONID=V_SESSIONID
    WHERE CURRDATE=V_CURRDATE;

    COMMIT;

    DELETE  FROM IFRS_AMORT_LOG
    WHERE   DOWNLOAD_DATE = V_CURRDATE;

    COMMIT;

    DELETE  FROM IFRS_STATISTIC
    WHERE   DOWNLOAD_DATE = V_CURRDATE
    AND PRC_NAME = 'AMT';

    COMMIT;

    INSERT  INTO IFRS_AMORT_LOG  ( DOWNLOAD_DATE ,DTM , OPS , PROCNAME ,REMARK )
    VALUES  (V_CURRDATE ,SYSTIMESTAMP , 'START' , 'SP_IFRS_AMORT_SEQUENCE' , '' );

    COMMIT;


   V_SPNAME := 'SP_IFRS_RESET_AMT_PRC';
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   V_SPNAME := 'SP_IFRS_SYNC_PRODUCT_PARAM';
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   V_SPNAME := 'SP_IFRS_SYNC_TRANS_PARAM';
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   V_SPNAME := 'SP_IFRS_SYNC_JOURNAL_PARAM';
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   V_SPNAME := 'SP_IFRS_FILL_IMA_FROM_PREV' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','N');

   V_SPNAME := 'SP_IFRS_INITIAL_UPDATE';
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

--    V_SPNAME := 'SP_IFRS_TRX_PRORATE';
--    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_FILL_IMA_PREV_CURR' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_CLOSED';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_PROCESS_TRAN_DAILY' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_COST_FEE_STATUS' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_COST_FEE_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SWITCH' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_SWITCH' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SWITCH');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SWITCH',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ECF',DEGREE=>8);

    V_SPNAME := 'SP_IFRS_ACCT_EIR_SWITCH' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    -- EIR ENGINE
    V_SPNAME := 'SP_IFRS_ACCT_EIR_ACF_PMTDT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_ACCT_EIR_ECF_EVENT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


   -- Generate Payment Schedule
    V_SPNAME := 'SP_IFRS_PAYM_SCHD' ;
--    V_SPNAME := 'SP_IFRS_PAYM_SCHD_SRC' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');



DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_JOURNAL_INTM');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_JOURNAL_INTM',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_TODAYREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_TODAYREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_ACCT_EIR_COST_FEE_PREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_ACCT_EIR_COST_FEE_PREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T10');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T10',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_CURR');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_CURR',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_PREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_PREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ACF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_NOCF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_NOCF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ACF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T2');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T2',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T3');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T3',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_TC');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_TC',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_PREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_PREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_STOP_REV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_STOP_REV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF2');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF2',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_CLOSED');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_CLOSED',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF',DEGREE=>8);


    V_SPNAME := 'SP_IFRS_ACCT_EIR_ECF_MAIN' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_STAFF_BENEFIT_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');



    V_SPNAME := 'SP_IFRS_ACCT_EIR_ACF_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_EIR_UPD_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_EIR_LAST_ACF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_JOURNAL_INTM');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_JOURNAL_INTM',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_CURR');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_CURR',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_PREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_IMA_AMORT_PREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_ACF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_NOCF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_NOCF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ACF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_ECF',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_PREV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_COST_FEE_PREV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_STOP_REV');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_EIR_STOP_REV',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF2');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF2',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_CLOSED');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_CLOSED',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_IFRS_ACCT_EIR_ECF',DEGREE=>8);

    V_SPNAME := 'SP_IFRS_ACCT_EIR_JRNL_INTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');




    -- START ENGINE BELOW MARKET
    V_SPNAME := 'SP_IFRS_LBM_RESET_AMT_PRC' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --ADD LBM EIR SWITCH 20180823
    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_SWITCH' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');
    --END ADD 20180823

    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ACF_PMTDT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ECF_EVENT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_LBM_PAYM_SCHD_SRC' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --V_SPNAME := 'SP_LBM_SYNC_PAYM_CORE' ;
    --SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ECF_MAIN' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_STAFF_BENEFIT_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_ACF_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_UPD_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

---------------------------------------------------------------

    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_LAST_ACF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_JRNL_INTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    V_SPNAME := 'SP_IFRS_LBM_ACCT_EIR_UPD_UNMRT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

 --DONE

    -- END ENGINE BELOW MARKET




    --SL ENGINE

DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_PREV');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_ECF');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_PREV',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_ECF',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_ACF',DEGREE=>8);

    V_SPNAME := 'SP_IFRS_ACCT_SL_ACF_PMTDATE' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_ECF_EVENT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_ECF_MAIN' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_ACF_ACCRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_UPD_ACRU' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_SL_LAST_ACF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');



    -- update unamortized pma SL then EIR
    V_SPNAME := 'SP_IFRS_ACCT_SL_UPD_UNAMRT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_PREV');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_ECF');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_CFID_JOURNAL_INTM_SUMM');
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_PREV',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_P1',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_COST_FEE_ECF',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T1',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_CFID_JOURNAL_INTM_SUMM',DEGREE=>8);
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_COST_FEE',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T2');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_T2',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_AP');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'TMP_AP',DEGREE=>8);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_ACF');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_ACCT_SL_ACF',DEGREE=>8);

    V_SPNAME := 'SP_IFRS_ACCT_SL_JRNL_INTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_ACCT_EIR_UPD_UNAMRT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    -- MARKET TO MARKET
    V_SPNAME := 'SP_IFRS_PAYM_SCHD_MTM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    -- JOURNAL SUMMARY
    V_SPNAME := 'SP_IFRS_ACCT_JRNL_INTM_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    V_SPNAME := 'SP_IFRS_CFID_JRNL_INTM_SUMM' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


   V_SPNAME := 'SP_IFRS_JRNL_ACF_ABN_ADJ' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   --JOURNAL DATA
   V_SPNAME := 'SP_IFRS_ACCT_JOURNAL_DATA' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

   --ADDED BY VIVI 15 FEB 2019
   V_SPNAME := 'SP_IFRS_ACCT_JOURNAL_DATA_SUMM' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


   V_SPNAME := 'SP_IFRS_ACCT_JRNL_DATA_MTM' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


   V_SPNAME := 'SP_IFRS_ACCT_RECORE_JRNL_DATA' ;
   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --GL OUTBOUND
    V_SPNAME := 'SP_IFRS_GL_OUTBOUND' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');


    --IFRS RECON REPORT  20180501
    V_SPNAME := 'SP_IFRS_REPORT_RECON' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --IFRS LBM RECON REPORT 20180915
    V_SPNAME := 'SP_IFRS_LBM_REPORT_RECON' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --CHECK AMORT
    V_SPNAME := 'SP_IFRS_CHECK_AMORT' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --CHECK AMORT NO CF
    V_SPNAME := 'SP_IFRS_CHECK_AMORT_NOCF' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    --ADDED BY VIVI 15 FEB 2019
    V_SPNAME := 'SP_IFRS_RECON_MANUAL' ;
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');

    IF EXTRACT(DAY FROM SYSDATE) > 5 AND EXTRACT(MONTH FROM FN_NEXT_WORKING_DAY(V_CURRDATE)) = EXTRACT(MONTH FROM (V_CURRDATE)) THEN
        V_SPNAME := 'SP_IFRS_AMORT_ARCHIVE_TABLES' ;
        SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'AMT','Y');
    END IF;

    INSERT  INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE , DTM , OPS , PROCNAME , REMARK )
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_AMORT_SEQUENCE' , ''  );

    COMMIT;

--    SELECT COUNT(*)
--    INTO V_VCNT
--    FROM IFRS_CHECK_AMORT
--    WHERE ABS(CONTROL_AMT) > 1;
--
--    IF V_VCNT > 0 THEN
--      RAISE_APPLICATION_ERROR(-20000, 'CHECK AMORT ERROR !');
--      RETURN;
--    END IF;

    INSERT  INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE , DTM , OPS , PROCNAME , REMARK )
    VALUES  (V_CURRDATE , SYSTIMESTAMP , 'END' , 'SP_IFRS_AMORT_SEQUENCE' , '' );

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN

    V_DATEPROCESS := TO_CHAR (SYSTIMESTAMP, 'MON DD, YYYY');


    UPDATE  IFRS_STATISTIC
    SET END_DATE = SYSTIMESTAMP ,
        ISCOMPLETE = 'N' ,
        REMARK = V_ERRM
    WHERE   DOWNLOAD_DATE = V_CURRDATE
    AND SP_NAME = V_SPNAME ;


    UPDATE  IFRS_PRC_DATE_AMORT
    SET     BATCH_STATUS = 'ERROR!!..' ,
    REMARK = V_ERRM ,
    LAST_PROCESS_DATE = SYSTIMESTAMP ;

    V_ERRORMESSAGEDESCRIPTION := V_SPNAME || ' ( ' || V_DATEPROCESS ;

    RAISE_APPLICATION_ERROR (-20002, 'ERROR MESSAGE ' || V_ERRORMESSAGEDESCRIPTION || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);


    END;