CREATE OR REPLACE PROCEDURE SP_IFRS_MASTERID
    AS

    V_CURRDATE DATE;
    V_PREVDATE DATE;

    BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_DATE_DAY1;
    SELECT PREVDATE INTO V_PREVDATE FROM IFRS_DATE_DAY1;

    INSERT  INTO IFRS_UPDATE_LOG ( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'START' ,'SP_IFRS_MASTERID_PROD' ,''); COMMIT;

    INSERT INTO IFRS_MASTERID
                            (
                            PKID,
                            MASTER_ACCOUNT_CODE
                            )
    SELECT 0, ACCOUNT_NUMBER FROM IFRS_MASTER_ACCOUNT_MONTHLY
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND ACCOUNT_NUMBER NOT IN (SELECT MASTER_ACCOUNT_CODE FROM IFRS_MASTERID);
    COMMIT;

    UPDATE IFRS_MASTER_ACCOUNT_MONTHLY
    SET MASTERID = 0
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    MERGE INTO IFRS_MASTER_ACCOUNT_MONTHLY A
        USING (SELECT PKID,MASTER_ACCOUNT_CODE FROM IFRS_MASTERID) B
        ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.MASTER_ACCOUNT_CODE)
        WHEN MATCHED THEN
        UPDATE
        SET A.MASTERID = B.PKID;
    COMMIT;

    INSERT  INTO IFRS_UPDATE_LOG ( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_MASTERID_PROD' ,'');COMMIT;
    END;