CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_DATA_IMA
AS
    V_CURRDATE DATE;
BEGIN

    SELECT  CURRDATE
    INTO V_CURRDATE
    FROM IFRS_PRC_DATE_LGD ;
    /*
    --TRUNCATE IFRS_LGD_SEGMENT_LOSSDATE
    --EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LGD_SEGMENT_LOSSDATE';
    --COMMIT;

    --INSERT TABLE IFRS_LGD_SEGMENT_LOSSDATE
    INSERT INTO IFRS_LGD_SEGMENT_LOSSDATE(SEGMENTASI,ACCOUNT_NUMBER,CUSTOMER_NUMBER,LOSS_DATE,OUTSTANDING_FIRST_NPL,BI_COLLECTABILITY)
    SELECT
        C.RESERVED_VARCHAR_2 SEGMENTASI,
        XX.ACCOUNT_NUMBER,XX.CUSTOMER_NUMBER,XX.LOSS_DATE,
        XX.OUTSTANDING_FIRST_NPL,C.BI_COLLECTABILITY
    FROM (
        SELECT
            ACCOUNT_NUMBER,CUSTOMER_NUMBER,MIN(RESERVED_DATE_3) AS LOSS_DATE,MIN(DOWNLOAD_DATE) AS DOWNLOAD_DATE,
            RESERVED_AMOUNT_8 AS OUTSTANDING_FIRST_NPL
        FROM IFRS_MASTER_ACCOUNT
        WHERE ACCOUNT_STATUS='C' AND OUTSTANDING=0 AND BI_COLLECTABILITY IN ('C','3','4','5')
        AND DATA_SOURCE='ILS'
        GROUP BY ACCOUNT_NUMBER,CUSTOMER_NUMBER,RESERVED_AMOUNT_8
    )XX
    INNER JOIN IFRS_MASTER_ACCOUNT C ON XX.DOWNLOAD_DATE=C.DOWNLOAD_DATE AND XX.ACCOUNT_NUMBER=C.ACCOUNT_NUMBER
        AND XX.CUSTOMER_NUMBER=C.CUSTOMER_NUMBER
    WHERE LOSS_DATE IS NOT NULL;
    COMMIT;
    */
    /*
    --UPDATE/ INSERT LGD SEGMENT
    MERGE INTO IFRS_LGD_SEGMENT_LOSSDATE D
    USING (
        SELECT
            RESERVED_VARCHAR_2 SEGMENTASI,ACCOUNT_NUMBER,CUSTOMER_NUMBER,MIN(RESERVED_DATE_3) AS LOSS_DATE,MIN(DOWNLOAD_DATE) AS DOWNLOAD_DATE,
            RESERVED_AMOUNT_8 AS OUTSTANDING_FIRST_NPL,BI_COLLECTABILITY
        FROM IFRS_MASTER_ACCOUNT
        WHERE ACCOUNT_STATUS='C'
            AND OUTSTANDING=0
            AND BI_COLLECTABILITY IN ('C','3','4','5')
            AND DATA_SOURCE='ILS'
            AND DOWNLOAD_DATE=V_CURRDATE
        GROUP BY RESERVED_VARCHAR_2,ACCOUNT_NUMBER,CUSTOMER_NUMBER,RESERVED_AMOUNT_8,BI_COLLECTABILITY
      ) S ON (D.ACCOUNT_NUMBER=S.ACCOUNT_NUMBER AND D.CUSTOMER_NUMBER=S.CUSTOMER_NUMBER)
    WHEN NOT MATCHED THEN
    INSERT (SEGMENTASI,ACCOUNT_NUMBER,CUSTOMER_NUMBER,LOSS_DATE,OUTSTANDING_FIRST_NPL,BI_COLLECTABILITY)
    VALUES (S.SEGMENTASI,S.ACCOUNT_NUMBER,S.CUSTOMER_NUMBER,S.LOSS_DATE,S.OUTSTANDING_FIRST_NPL,S.BI_COLLECTABILITY);
    COMMIT;
    */



    --UPDATE/ INSERT TABLE IFRS_LGD_ER_NPL_ACCT
    MERGE INTO IFRS_LGD_ER_NPL_ACCT D
    USING (
            SELECT
                CASE WHEN B.LOSS_DATE=LAST_DAY(B.LOSS_DATE) THEN B.LOSS_DATE
                ELSE LAST_DAY(B.LOSS_DATE) END DOWNLOAD_DATE,
                A.MASTERID,
                A.ACCOUNT_NUMBER,
                A.CUSTOMER_NUMBER,
                A.CUSTOMER_NAME,
                B.LOSS_DATE NPL_DATE,
                A.RESERVED_DATE_5	CLOSED_DATE,
                B.BI_COLLECTABILITY_NPL,
                A.RESERVED_VARCHAR_2 BI_COLLECTABILITY_CLOSED,
                B.OUTSTANDING_FIRST_NPL OUTSTANDING_DEFAULT,
                A.SEGMENT LGD_CUSTOMER_TYPE,
                D.PKID SEGMENTATION_ID,
                D.SEGMENT SEGMENTATION_NAME,
                C.PKID LGD_RULE_ID,
                C.LGD_RULE_NAME,
                A.PLAFOND,
                A.PRODUCT_CODE,
                A.PRODUCT_TYPE,
                A.CURRENCY,
                A.CURRENCY ORIGINAL_CURRENCY,
                A.EXCHANGE_RATE,
                A.INTEREST_RATE,
                ''COLLATERAL_VALUE_FOR_IMPAIR,
                FN_LGD_DAYS_30_360 (NPL_DATE,RESERVED_DATE_5)/360 DAILY_BASIS,
                '' VALUATION_TYPE
            FROM IFRS_MASTER_ACCOUNT_MONTHLY A
                INNER JOIN IFRS_LGD_NPL_ACCOUNT B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                INNER JOIN IFRS_LGD_RULES_CONFIG C ON A.LGD_RULE_ID=C.PKID
                INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER D ON C.SEGMENTATION_ID=D.PKID
            WHERE A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                AND A.DATA_SOURCE = 'ILS'
                AND A.PRODUCT_CODE NOT IN ('101','CARDS')
                AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                AND RESERVED_DATE_5 IS NOT NULL
                AND A.LGD_RULE_ID!=0
            UNION ALL
            --KARTU KREDIT
            SELECT
                B.LOSS_DATE DOWNLOAD_DATE,
                A.MASTERID,
                CASE WHEN A.DATA_SOURCE='CRD' THEN A.CUSTOMER_NUMBER
                ELSE A.ACCOUNT_NUMBER END ACCOUNT_NUMBER,
                A.CUSTOMER_NUMBER,
                A.CUSTOMER_NAME,
                B.LOSS_DATE NPL_DATE,
                B.CLOSED_DATE,
                B.BI_COLLECTABILITY_NPL ,
                A.RESERVED_VARCHAR_2 BI_COLLECTABILITY_CLOSED,
                B.OUTSTANDING_FIRST_NPL OUTSTANDING_DEFAULT,
                A.SEGMENT LGD_CUSTOMER_TYPE,
                D.PKID SEGMENTATION_ID,
                D.SEGMENT SEGMENTATION_NAME,
                C.PKID LGD_RULE_ID,
                C.LGD_RULE_NAME,
                A.PLAFOND,
                A.PRODUCT_CODE,
                A.PRODUCT_TYPE,
                A.CURRENCY,
                A.CURRENCY ORIGINAL_CURRENCY,
                A.EXCHANGE_RATE,
                A.INTEREST_RATE,
                ''COLLATERAL_VALUE_FOR_IMPAIR,
                FN_LGD_DAYS_30_360 (NPL_DATE,RESERVED_DATE_5)/360 DAILY_BASIS,
                E.CHARGEOFF_STATUS VALUATION_TYPE
            FROM IFRS_MASTER_ACCOUNT_MONTHLY A
                INNER JOIN IFRS_LGD_NPL_ACCOUNT B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                INNER JOIN IFRS_LGD_RULES_CONFIG C ON A.LGD_RULE_ID=C.PKID
                INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER D ON C.SEGMENTATION_ID=D.PKID
                LEFT JOIN IFRS_STG_CRD_CHARGE E ON A.CUSTOMER_NUMBER=SUBSTR(E.CUSTOMER_NUMBER,6,11)
                   AND A.DOWNLOAD_DATE=E.DOWNLOAD_DATE
            WHERE
                --KARTU KREDIT INDIVIDUAL
                (A.DOWNLOAD_DATE=LAST_DAY(V_CURRDATE)
                 AND A.DATA_SOURCE='CRD'
                 AND A.RESERVED_VARCHAR_2 IN ('I','O')
                 AND A.ACCOUNT_STATUS IN ('C','W')
                 AND A.RESERVED_AMOUNT_4 >= 5
                 AND A.BI_COLLECTABILITY IN ('C','3','4','5'))
                OR
                --KARTU KREDIT LOKAL
                (A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                 AND A.DATA_SOURCE = 'ILS'
                 AND A.ACCOUNT_STATUS = 'C'
                 AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                 AND A.PRODUCT_CODE = '101'
                 AND A.LGD_RULE_ID!=0)
        )S ON (D.ACCOUNT_NUMBER     =   S.ACCOUNT_NUMBER
               AND D.CUSTOMER_NUMBER   =   S.CUSTOMER_NUMBER)
    WHEN MATCHED THEN
    UPDATE SET
        DOWNLOAD_DATE               =   S.DOWNLOAD_DATE,
        MASTER_ID                   =   S.MASTERID,
        SEGMENTATION_ID             =   S.SEGMENTATION_ID,
        SEGMENTATION_NAME           =   S.SEGMENTATION_NAME,
        LGD_RULE_ID                 =   S.LGD_RULE_ID,
        LGD_RULE_NAME               =   S.LGD_RULE_NAME,
        NPL_DATE                    =   S.NPL_DATE,
        CLOSED_DATE                 =   S.CLOSED_DATE,
        BI_COLLECTABILITY_NPL       =   S.BI_COLLECTABILITY_NPL,
        BI_COLLECTABILITY_CLOSED    =   S.BI_COLLECTABILITY_CLOSED,
        OUTSTANDING_DEFAULT         =   S.OUTSTANDING_DEFAULT,
        LGD_CUSTOMER_TYPE           =   S.LGD_CUSTOMER_TYPE,
        PRODUCT_CODE                =   S.PRODUCT_CODE,
        CURRENCY                    =   S.CURRENCY,
        ORIGINAL_CURRENCY           =   S.ORIGINAL_CURRENCY,
        INTEREST_RATE               =   S.INTEREST_RATE,
        UPDATEDDATE                 =   SYSDATE
    WHEN NOT MATCHED THEN
    INSERT (DOWNLOAD_DATE,
            MASTER_ID,
            ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            SEGMENTATION_ID,
            SEGMENTATION_NAME,
            LGD_RULE_ID,
            LGD_RULE_NAME,
            NPL_DATE,
            CLOSED_DATE,
            BI_COLLECTABILITY_NPL,
            BI_COLLECTABILITY_CLOSED,
            OUTSTANDING_DEFAULT,
            LGD_CUSTOMER_TYPE,
            PRODUCT_CODE,
            CURRENCY,
            ORIGINAL_CURRENCY,
            INTEREST_RATE
            )
    VALUES (S.DOWNLOAD_DATE,
            S.MASTERID,
            S.ACCOUNT_NUMBER,
            S.CUSTOMER_NUMBER,
            S.CUSTOMER_NAME,
            S.SEGMENTATION_ID,
            S.SEGMENTATION_NAME,
            S.LGD_RULE_ID,
            S.LGD_RULE_NAME,
            S.NPL_DATE,
            S.CLOSED_DATE,
            S.BI_COLLECTABILITY_NPL,
            S.BI_COLLECTABILITY_CLOSED,
            S.OUTSTANDING_DEFAULT,
            S.LGD_CUSTOMER_TYPE,
            S.PRODUCT_CODE,
            S.CURRENCY,
            S.ORIGINAL_CURRENCY,
            S.INTEREST_RATE
            );
    COMMIT;

    --UPDATE/ INSERT TABLE IFRS_LGD_DATA_DETAIL
    MERGE INTO IFRS_LGD_DATA_DETAIL D
    USING (
            SELECT
                DOWNLOAD_DATE,
                MASTERID,
                ACCOUNT_NUMBER,
                CUSTOMER_NUMBER,
                ACCOUNT_STATUS,
                SEGMENTATION_ID,
                CASE WHEN OUTSTANDING=0 THEN DOWNLOAD_DATE
                    WHEN OUTSTANDING2>OUTSTANDING  THEN DOWNLOAD_DATE
                END PAYMENT_DATE,
                CURRENCY,
                CASE WHEN (OUTSTANDING2 IS NULL OR OUTSTANDING2=0) AND OUTSTANDING!=0  THEN 0
                    WHEN OUTSTANDING2=OUTSTANDING THEN 0
                    WHEN OUTSTANDING2>OUTSTANDING  THEN OUTSTANDING
                    WHEN OUTSTANDING=0 THEN 0
                END RECOVERY_AMOUNT,
                '' RECOVERY_TYPE,
                IS_EFFECTIVE,
                DATA_SOURCE
            FROM (
                SELECT
                    DOWNLOAD_DATE,
                    MASTERID,
                    ACCOUNT_NUMBER,
                    CUSTOMER_NUMBER,
                    ACCOUNT_STATUS,
                    SEGMENTATION_ID,
                    CURRENCY,
                    OUTSTANDING,
                    LAG(OUTSTANDING) OVER (PARTITION BY ACCOUNT_NUMBER,CUSTOMER_NUMBER ORDER BY  DOWNLOAD_DATE) OUTSTANDING2,
                    IS_EFFECTIVE,
                    DATA_SOURCE
                FROM (
                    SELECT
                        A.DOWNLOAD_DATE,
                        A.MASTERID,
                        A.ACCOUNT_NUMBER,
                        D.PKID SEGMENTATION_ID,
                        A.CUSTOMER_NUMBER,
                        A.ACCOUNT_STATUS,
                        A.CURRENCY,
                        A.OUTSTANDING,
                        '1' IS_EFFECTIVE,
                        A.DATA_SOURCE
                    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
                        INNER JOIN IFRS_LGD_NPL_ACCOUNT B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                        INNER JOIN IFRS_LGD_RULES_CONFIG C ON A.LGD_RULE_ID=C.PKID
                        INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER D ON C.SEGMENTATION_ID=D.PKID
                    WHERE
                        (A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                         AND A.DATA_SOURCE = 'ILS'
                         AND A.PRODUCT_CODE NOT IN ('101','CARDS')
                         AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                         AND A.RESERVED_DATE_5 IS NOT NULL
                        )
                        OR
                        (A.DOWNLOAD_DATE = LAST_DAY(ADD_MONTHS(V_CURRDATE,-1))
                         AND A.DATA_SOURCE = 'ILS'
                         AND A.PRODUCT_CODE NOT IN ('101','CARDS')
                         AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                         AND A.RESERVED_DATE_5 IS NOT NULL
                        )
                   )AA
            )BB
            WHERE DOWNLOAD_DATE=LAST_DAY(V_CURRDATE)

            UNION

            --POPULASI KARTU KREDIT
            SELECT
                LAST_DAY(V_CURRDATE) DOWNLOAD_DATE,
                A.MASTERID,
                CASE WHEN A.DATA_SOURCE = 'CRD' THEN A.CUSTOMER_NUMBER
                ELSE A.ACCOUNT_NUMBER END ACCOUNT_NUMBER,
                A.CUSTOMER_NUMBER,
                A.ACCOUNT_STATUS,
                E.PKID SEGMENTATION_ID,
                CASE WHEN A.DATA_SOURCE = 'CRD' THEN C.CHARGEOFF_DATE ELSE  G.EFFECTIVE_DATE END PAYMENT_DATE,
                A.CURRENCY,
                CASE WHEN A.DATA_SOURCE = 'CRD' THEN C.CHARGEOFF_AMOUNT ELSE G.ORG_CCY_AMT*F.RATE_AMOUNT  END  RECOVERY_AMOUNT,
                '' RECOVERY_TYPE,
                '1' IS_EFFECTIVE,
                A.DATA_SOURCE
            FROM IFRS_MASTER_ACCOUNT_MONTHLY A
                INNER JOIN IFRS_LGD_NPL_ACCOUNT B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                LEFT JOIN IFRS_STG_CRD_CHARGE C ON A.CUSTOMER_NUMBER=SUBSTR(C.CUSTOMER_NUMBER,6,11)
                   AND A.DOWNLOAD_DATE=C.DOWNLOAD_DATE
                INNER JOIN IFRS_LGD_RULES_CONFIG D ON A.LGD_RULE_ID=D.PKID
                INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER E ON D.SEGMENTATION_ID=E.PKID
                INNER JOIN IFRS_MASTER_EXCHANGE_RATE F ON A.DOWNLOAD_DATE=F.DOWNLOAD_DATE AND A.CURRENCY=F.CURRENCY
                LEFT JOIN IFRS_PPR_TRANSACTION_DAILY G ON A.DOWNLOAD_DATE=G.EFFECTIVE_DATE
                    AND A.ACCOUNT_NUMBER=G.ACCOUNT_NUMBER
            WHERE
                --KARTU KREDIT INDIVIDUAL
                (A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                 AND A.DATA_SOURCE = 'CRD'
                 AND A.RESERVED_VARCHAR_2 IN ('I','O')
                 AND A.RESERVED_AMOUNT_4 >= 5
                 AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                 AND CHARGEOFF_AMOUNT IS NOT NULL)
                OR
                --KARTU KREDIT LOKAL
                (A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                 AND A.DATA_SOURCE = 'ILS'
                 AND A.BI_COLLECTABILITY IN ('C','3','4','5')
                 AND A.PRODUCT_CODE='101'
                 AND A.LGD_RULE_ID!=0
                 AND G.TRX_CODE='PP')
        )S ON (D.ACCOUNT_NUMBER=S.ACCOUNT_NUMBER
                AND D.CUSTOMER_NUMBER=S.CUSTOMER_NUMBER
                AND NVL(D.PAYMENT_DATE,'1-JAN-1900')=NVL(S.PAYMENT_DATE,'1-JAN-1900'))
    WHEN MATCHED THEN
    UPDATE SET
        MASTER_ID       =   S.MASTERID,
        ACCOUNT_STATUS  =   S.ACCOUNT_STATUS,
        SEGMENTATION_ID =   S.SEGMENTATION_ID,
        CURRENCY        =   S.CURRENCY,
        RECOVERY_AMOUNT =   S.RECOVERY_AMOUNT,
        RECOVERY_TYPE   =   S.RECOVERY_TYPE,
        IS_EFFECTIVE    =   S.IS_EFFECTIVE,
        DATA_SOURCE     =   S.DATA_SOURCE,
        UPDATEDDATE     =   SYSDATE
    WHEN NOT MATCHED THEN
    INSERT (MASTER_ID,
            ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            ACCOUNT_STATUS,
            SEGMENTATION_ID,
            PAYMENT_DATE,
            CURRENCY,
            RECOVERY_AMOUNT,
            IS_EFFECTIVE,
            DATA_SOURCE)
    VALUES (S.MASTERID,
            S.ACCOUNT_NUMBER,
            S.CUSTOMER_NUMBER,
            S.ACCOUNT_STATUS,
            S.SEGMENTATION_ID,
            S.PAYMENT_DATE,
            S.CURRENCY,
            S.RECOVERY_AMOUNT,
            S.IS_EFFECTIVE,
            S.DATA_SOURCE)
     ;
    COMMIT;
END;