CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_SEQUENCE_DAILY
AS
   -- V_SPNAME VARCHAR2(100);
BEGIN

/*
    V_SPNAME := 'SP_IFRS_LGD_DATA_IMA';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'LGD','N');
 */
 /*
    V_SPNAME := 'SP_IFRS_LGD_DATA_BCA';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'LGD','N');

    V_SPNAME := 'SP_IFRS_LGD';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'LGD','N');

    V_SPNAME := 'SP_IFRS_LGD_EXPECTED_RECOVERY';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'LGD','N');

 */
    --SP_IFRS_LGD_NPL_ACCOUNT;
    SP_IFRS_LGD_DATA_BCA;
    SP_IFRS_LGD_CARD_DATA_BCA;
    --SP_IFRS_LGD_DATA_IMA;

END;