CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_EIR_ECF_ALIGN4
AS
  V_CURRDATE    DATE;
  V_PREVDATE    DATE;
  V_ROUND NUMBER(10);
  V_FUNCROUND NUMBER(10);

BEGIN
    SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT ;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_ACCT_EIR_ECF_ALIGN4','');

    BEGIN
      SELECT CAST(VALUE1 AS NUMBER(10))
           , CAST(VALUE2 AS NUMBER(10))
      INTO V_ROUND, V_FUNCROUND
      FROM TBLM_COMMONCODEDETAIL
      WHERE COMMONCODE = 'SCM003';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_ROUND := 6;
        V_FUNCROUND:=1;
    END;


    EXECUTE IMMEDIATE 'truncate table TMP_T8';

    INSERT /*+ PARALLEL(12) */ INTO TMP_T8(MASTERID,DTMAX,CURRDATE)
    SELECT /*+ PARALLEL(12) */ MASTERID,MAX(PMT_DATE) DTMAX ,V_CURRDATE
    FROM IFRS_ACCT_EIR_ECF_NOCF
    WHERE DOWNLOAD_DATE=V_CURRDATE
    GROUP BY MASTERID;COMMIT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_ECF_ALIGN4','tmp t8 prepared');


    MERGE /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_NOCF A
    USING TMP_T8 B
    ON (A.MASTERID=B.MASTERID
        AND B.DTMAX=A.PMT_DATE
        AND A.DOWNLOAD_DATE=B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET   N_UNAMORT_AMT=0, N_COST_UNAMORT_AMT=0, N_FEE_UNAMORT_AMT=0
        , N_AMORT_AMT = -1 * N_UNAMORT_AMT_PREV
        , N_COST_AMORT_AMT = -1 * N_COST_UNAMORT_AMT_PREV
        , N_FEE_AMORT_AMT = -1 * N_FEE_UNAMORT_AMT_PREV
        , N_FAIRVALUE=0
    ;COMMIT;


    /*Pindahan dari atas 20160428 */
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_EIR_ECF_NOCF
    SET
    N_DAILY_AMORT_COST = ROUND(CASE WHEN I_DAYS2=0 THEN 0 ELSE N_COST_AMORT_AMT/CAST(I_DAYS2 AS NUMBER(32,6)) END,V_ROUND)
    , N_DAILY_AMORT_FEE = ROUND(CASE WHEN I_DAYS2=0 THEN 0 ELSE N_FEE_AMORT_AMT/CAST(I_DAYS2 AS NUMBER(32,6)) END,V_ROUND)
    WHERE DOWNLOAD_DATE=V_CURRDATE;COMMIT;


    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_ECF_ALIGN4','daily amort updated');
    /*Pindahan dari atas 20160428 */

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_ECF_ALIGN4','merge align done');

    -- update endamortdate to max pmtdate
    MERGE /*+ PARALLEL(12) */ INTO IFRS_ACCT_EIR_ECF_NOCF A
    USING TMP_T8 B
    ON (A.MASTERID=B.MASTERID
        AND A.DOWNLOAD_DATE=B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET ENDAMORTDATE=B.DTMAX;COMMIT;


    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_ACCT_EIR_ECF_ALIGN4','merge endamortdate done');

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_ACCT_EIR_ECF_ALIGN4','');


END;