CREATE OR REPLACE PROCEDURE SP_IFRS_DELETE_NOMINATIVE(v_DOWNLOADDATE DATE DEFAULT NULL, v_RUNNING_MODE NUMBER DEFAULT 0) AS
BEGIN

    IF v_RUNNING_MODE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE IFRS_NOMINATIVE TRUNCATE PARTITION REPORT_DATE_' || TO_CHAR(v_DOWNLOADDATE, 'YYYY_MM');
    ELSE
        DELETE /*+ PARALLEL(8) */ IFRS_NOMINATIVE
        WHERE REPORT_DATE = v_DOWNLOADDATE
        AND MASTERID IN
        (SELECT /*+ PARALLEL(8) */ MASTERID FROM TMP_IMA_PARTIAL);
        COMMIT;
    END IF;

END;