CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_JRNL_DATA_MTM
AS
	V_CURRDATE DATE;
	V_PREVDATE DATE;
	V_PREVMONTH DATE;
	V_CURRMONTH DATE;
BEGIN
	SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

	V_CURRMONTH := LAST_DAY(V_CURRDATE);
	V_PREVMONTH := LAST_DAY(ADD_MONTHS(V_CURRDATE,-1));


	IF V_CURRDATE = V_CURRMONTH
	THEN
		-------------------------	NO RECLASS	   ---------------------------------

		-------------------------      PLMTM	   ---------------------------------

		DELETE /*+ PARALLEL(12) */ IFRS_ACCT_JOURNAL_DATA
		WHERE JOURNALCODE = 'PLMTM'
		AND DOWNLOAD_DATE = V_CURRMONTH;

		COMMIT;

		INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_JOURNAL_DATA
		(
			DOWNLOAD_DATE
			,MASTERID
			,FACNO
			,CIFNO
			,ACCTNO
			,DATASOURCE
			,PRDTYPE
			,PRDCODE
			,TRXCODE
			,CCY
			,JOURNALCODE
			,STATUS
			,REVERSE
			,FLAG_CF
			,DRCR
			,GLNO
			,N_AMOUNT
			,N_AMOUNT_IDR
			,SOURCEPROCESS
			,INTMID
			,CREATEDDATE
			,CREATEDBY
			,BRANCH
			,JOURNALCODE2
			,JOURNAL_DESC
			,NOREF
			,VALCTR_CODE
			,GL_INTERNAL_CODE
--			,RESERVED_VARCHAR_1
--			,RESERVED_VARCHAR_2
			,METHOD
			,GL_COSTCENTER
		)
		SELECT /*+ PARALLEL(12) */ A.DOWNLOAD_DATE
			,A.MASTERID
			,NVL(IMC.FACILITY_NUMBER, IMP.FACILITY_NUMBER)
			,NVL(IMC.CUSTOMER_NUMBER, IMP.CUSTOMER_NUMBER)
			,A.ACCOUNT_NUMBER
			,NVL(IMC.DATA_SOURCE, IMP.DATA_SOURCE)
			,NVL(IMC.PRODUCT_TYPE, IMP.PRODUCT_TYPE)
			,NVL(IMC.PRODUCT_CODE, IMP.PRODUCT_CODE)
			,B.TRX_CODE
			,NVL(IMC.CURRENCY, IMP.CURRENCY)
			,B.JOURNALCODE
			,'ACT' STATUS
			,'N' REVERSE
			,B.FLAG_CF
			,CASE WHEN A.TOT_ADJUST >= 0 THEN
				B.DRCR
			 ELSE
				CASE WHEN B.DRCR = 'D' THEN 'C' ELSE 'D' END
			 END
			,B.GLNO
			,ABS(A.TOT_ADJUST)
			,ABS(A.TOT_ADJUST * COALESCE(IMC.EXCHANGE_RATE, 1))
			,'PLMTM' AS SOURCEPROCESS
			,NULL
			,SYSTIMESTAMP
			,'SP_JOURNAL_DATA2'
			,NVL(IMC.BRANCH_CODE, IMP.BRANCH_CODE)
			,B.JOURNALCODE AS JOURNALCODE2
			,B.JOURNAL_DESC
			,B.JOURNALCODE
			,B.COSTCENTER + '-' + COALESCE(IMC.APPLICATION_NO,IMP.APPLICATION_NO, '')
			,B.GL_INTERNAL_CODE
--			,NVL(IMC.RESERVED_VARCHAR_1, IMP.RESERVED_VARCHAR_1)
--			,NVL(IMC.RESERVED_VARCHAR_2, IMP.RESERVED_VARCHAR_2)
			,NULL METHOD
			,B.COSTCENTER
		FROM IFRS_EIR_ADJUSTMENT A
		LEFT JOIN IFRS_IMA_AMORT_CURR IMC ON A.MASTERID = IMC.MASTERID
		LEFT JOIN IFRS_IMA_AMORT_CURR IMP ON A.MASTERID = IMP.MASTERID
		JOIN IFRS_JOURNAL_PARAM B
			ON B.JOURNALCODE = 'PLMTM'
			AND B.GL_CONSTNAME = COALESCE(IMC.GL_CONSTNAME, '')
		WHERE A.DOWNLOAD_DATE = V_CURRMONTH AND IMC.IFRS9_CLASS = 'FVTPL';

		COMMIT;

		--REVERSE
		INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_JOURNAL_DATA
		(
			DOWNLOAD_DATE
			,MASTERID
			,FACNO
			,CIFNO
			,ACCTNO
			,DATASOURCE
			,PRDTYPE
			,PRDCODE
			,TRXCODE
			,CCY
			,JOURNALCODE
			,STATUS
			,REVERSE
			,FLAG_CF
			,DRCR
			,GLNO
			,N_AMOUNT
			,N_AMOUNT_IDR
			,SOURCEPROCESS
			,INTMID
			,CREATEDDATE
			,CREATEDBY
			,BRANCH
			,JOURNALCODE2
			,JOURNAL_DESC
			,NOREF
			,VALCTR_CODE
			,GL_INTERNAL_CODE
--			,RESERVED_VARCHAR_1
--			,RESERVED_VARCHAR_2
			,METHOD
			,GL_COSTCENTER
		)
		SELECT /*+ PARALLEL(12) */ V_CURRMONTH
			,A.MASTERID
			,A.FACNO
			,A.CIFNO
			,A.ACCTNO
			,A.DATASOURCE
			,A.PRDTYPE
			,A.PRDCODE
			,A.TRXCODE
			,A.CCY
			,A.JOURNALCODE
			,A.STATUS
			,'Y' REVERSE
			,A.FLAG_CF
			,CASE WHEN A.DRCR = 'D'
				THEN 'C'
				ELSE 'D'
			 END AS DRCR
			,A.GLNO
			,A.N_AMOUNT
			,A.N_AMOUNT_IDR
			,A.SOURCEPROCESS
			,A.INTMID
			,SYSTIMESTAMP
			,'SP_JOURNAL_DATA_REV'
			,A.BRANCH
			,A.JOURNALCODE2
			,A.JOURNAL_DESC
			,A.NOREF
			,A.VALCTR_CODE
			,A.GL_INTERNAL_CODE
--			,NVL(A.RESERVED_VARCHAR_1, A.RESERVED_VARCHAR_1)
--			,NVL(A.RESERVED_VARCHAR_1, A.RESERVED_VARCHAR_2)
			,A.METHOD
			,A.GL_COSTCENTER
		FROM IFRS_ACCT_JOURNAL_DATA A
--			LEFT JOIN IFRS_IMA_AMORT_CURR IMC ON A.MASTERID = IMC.MASTERID
--			LEFT JOIN IFRS_IMA_AMORT_PREV IMP ON A.MASTERID = IMP.MASTERID
		WHERE  A.DOWNLOAD_DATE = V_PREVMONTH AND A.REVERSE = 'N'
			AND A.JOURNALCODE = 'PLMTM';

		COMMIT;

		-------------------------      OCIMTM	   ---------------------------------

		DELETE /*+ PARALLEL(12) */ IFRS_ACCT_JOURNAL_DATA
		WHERE JOURNALCODE = 'OCIMTM'
		AND DOWNLOAD_DATE = V_CURRMONTH;

		COMMIT;

		INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_JOURNAL_DATA
		(
			DOWNLOAD_DATE
			,MASTERID
			,FACNO
			,CIFNO
			,ACCTNO
			,DATASOURCE
			,PRDTYPE
			,PRDCODE
			,TRXCODE
			,CCY
			,JOURNALCODE
			,STATUS
			,REVERSE
			,FLAG_CF
			,DRCR
			,GLNO
			,N_AMOUNT
			,N_AMOUNT_IDR
			,SOURCEPROCESS
			,INTMID
			,CREATEDDATE
			,CREATEDBY
			,BRANCH
			,JOURNALCODE2
			,JOURNAL_DESC
			,NOREF
			,VALCTR_CODE
			,GL_INTERNAL_CODE
--			,RESERVED_VARCHAR_1
--			,RESERVED_VARCHAR_2
			,METHOD
			,GL_COSTCENTER
		)
		SELECT /*+ PARALLEL(12) */ A.DOWNLOAD_DATE
			,A.MASTERID
			,NVL(IMC.FACILITY_NUMBER, IMP.FACILITY_NUMBER)
			,NVL(IMC.CUSTOMER_NUMBER, IMP.CUSTOMER_NUMBER)
			,A.ACCOUNT_NUMBER
			,NVL(IMC.DATA_SOURCE, IMP.DATA_SOURCE)
			,NVL(IMC.PRODUCT_TYPE, IMP.PRODUCT_TYPE)
			,NVL(IMC.PRODUCT_CODE, IMP.PRODUCT_CODE)
			,B.TRX_CODE
			,NVL(IMC.CURRENCY, IMP.CURRENCY)
			,B.JOURNALCODE
			,'ACT' STATUS
			,'N' REVERSE
			,B.FLAG_CF
			,CASE WHEN A.TOT_ADJUST >= 0 THEN
				B.DRCR
			 ELSE
				CASE WHEN B.DRCR = 'D' THEN 'C' ELSE 'D' END
			 END
			,B.GLNO
			,ABS(A.TOT_ADJUST)
			,ABS(A.TOT_ADJUST * COALESCE(IMC.EXCHANGE_RATE, 1))
			,'OCIMTM' AS SOURCEPROCESS
			,NULL
			,SYSTIMESTAMP
			,'SP_JOURNAL_DATA2'
			,NVL(IMC.BRANCH_CODE, IMP.BRANCH_CODE)
			,B.JOURNALCODE JOURNALCODE2
			,B.JOURNAL_DESC
			,B.JOURNALCODE
			,B.COSTCENTER + '-' + COALESCE(IMC.APPLICATION_NO, IMP.APPLICATION_NO, '')
			,B.GL_INTERNAL_CODE
--			,NVL(IMC.RESERVED_VARCHAR_1, IMP.RESERVED_VARCHAR_1)
--			,NVL(IMC.RESERVED_VARCHAR_2, IMP.RESERVED_VARCHAR_2)
			,NULL METHOD
			,B.COSTCENTER
		FROM IFRS_EIR_ADJUSTMENT A
			LEFT JOIN IFRS_IMA_AMORT_CURR IMC ON A.MASTERID = IMC.MASTERID
			LEFT JOIN IFRS_IMA_AMORT_PREV IMP ON A.MASTERID = IMP.MASTERID
		JOIN IFRS_JOURNAL_PARAM B
			ON B.JOURNALCODE = 'OCIMTM'
			AND B.GL_CONSTNAME = COALESCE(IMC.GL_CONSTNAME, '')
		WHERE A.DOWNLOAD_DATE = V_CURRMONTH AND IMC.IFRS9_CLASS = 'FVOCI';

		COMMIT;

		--REVERSE
		INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_JOURNAL_DATA
		(
			DOWNLOAD_DATE
			,MASTERID
			,FACNO
			,CIFNO
			,ACCTNO
			,DATASOURCE
			,PRDTYPE
			,PRDCODE
			,TRXCODE
			,CCY
			,JOURNALCODE
			,STATUS
			,REVERSE
			,FLAG_CF
			,DRCR
			,GLNO
			,N_AMOUNT
			,N_AMOUNT_IDR
			,SOURCEPROCESS
			,INTMID
			,CREATEDDATE
			,CREATEDBY
			,BRANCH
			,JOURNALCODE2
			,JOURNAL_DESC
			,NOREF
			,VALCTR_CODE
			,GL_INTERNAL_CODE
--			,RESERVED_VARCHAR_1
--			,RESERVED_VARCHAR_2
			,METHOD
			,GL_COSTCENTER
		)
		SELECT /*+ PARALLEL(12) */ IMC.DOWNLOAD_DATE
			,A.MASTERID
			,A.FACNO
			,A.CIFNO
			,A.ACCTNO
			,A.DATASOURCE
			,A.PRDTYPE
			,A.PRDCODE
			,A.TRXCODE
			,A.CCY
			,A.JOURNALCODE
			,A.STATUS
			,'Y' REVERSE
			,A.FLAG_CF
			,CASE WHEN A.DRCR = 'D'
				THEN 'C'
				ELSE 'D'
			 END AS DRCR
			,A.GLNO
			,A.N_AMOUNT
			,A.N_AMOUNT_IDR
			,A.SOURCEPROCESS
			,A.INTMID
			,SYSTIMESTAMP
			,'SP_JOURNAL_DATA_REV'
			,A.BRANCH
			,A.JOURNALCODE2
			,A.JOURNAL_DESC
			,A.NOREF
			,A.VALCTR_CODE
			,A.GL_INTERNAL_CODE
--			,A.RESERVED_VARCHAR_1
--			,A.RESERVED_VARCHAR_2
			,A.METHOD
			,A.GL_COSTCENTER
		FROM IFRS_ACCT_JOURNAL_DATA A
			LEFT JOIN IFRS_IMA_AMORT_CURR IMC ON A.MASTERID = IMC.MASTERID
			LEFT JOIN IFRS_IMA_AMORT_PREV IMP ON A.MASTERID = IMP.MASTERID
		WHERE A.DOWNLOAD_DATE = V_PREVMONTH AND A.REVERSE = 'N'
			AND A.JOURNALCODE = 'OCIMTM';

		COMMIT;
	END IF;

END;