CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_SBLC_CALC_PR(v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    INSERT INTO GTMP_IFRS_MASTER_ACCOUNT
    (
        PKID,
        DOWNLOAD_DATE,
        MASTERID,
        MASTER_ACCOUNT_CODE,
        CUSTOMER_NUMBER,
        ACCOUNT_NUMBER,
        ECL_AMOUNT
    )
    SELECT A.PKID,
        A.DOWNLOAD_DATE,
        A.MASTERID,
        ' ' MASTER_ACCOUNT_CODE,
        A.CUSTOMER_NUMBER,
        A.ACCOUNT_NUMBER,
        CASE WHEN B.RATING IN ('UNK', 'PRIME', 'GOV') THEN 0 ELSE ECL_AMOUNT END ECL_AMOUNT
    FROM IFRS_ECL_RESULT_DETAIL_PR A
    JOIN TBLU_SBLC_OVERRIDE B
    ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    AND A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER;

    COMMIT;

    DELETE IFRS_ECL_RESULT_DETAIL_CALC_PR
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
    AND ECL_MODEL_ID = v_ECLID
    AND MASTERID IN
    (SELECT MASTERID FROM GTMP_IFRS_MASTER_ACCOUNT WHERE ECL_AMOUNT = 0)
    AND COUNTER_PAYSCHD > 1;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_CALC_PR A
    USING GTMP_IFRS_MASTER_ACCOUNT B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID
    AND B.ECL_AMOUNT = 0)
    WHEN MATCHED THEN
    UPDATE SET
        A.PD_RATE = 0,
        A.LGD_RATE = 0,
        A.DISCOUNT_RATE = 0,
        A.ECL_AMOUNT = 0;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_PR A
    USING GTMP_IFRS_MASTER_ACCOUNT B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        A.ECL_AMOUNT = B.ECL_AMOUNT,
        A.SPECIAL_REASON = 'SBLC';

    COMMIT;

END;