CREATE OR REPLACE procedure      SP_IFRS_GENERATE_RULE_GL_CONSTNAME
as
begin

    IFRS.SP_IFRS_GENERATE_RULE('GL');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS.IFRS_RULES_GL_CONSTNAME';

    insert into IFRS.IFRS_RULES_GL_CONSTNAME
    select b.RULE_NAME,
           a.PD_RULES_QRY_RESULT RULES_RESULT
    from IFRS.GTMP_IFRS_SCENARIO_GEN_QUERY a
             join IFRS.IFRS_SCENARIO_RULES_HEADER b
                  on a.RULE_ID = b.PKID;

    commit;

end;