CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MAA_ENR
AS
	v_CURRDATE date;
	v_COUNT number;
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_MAA_AVG_MONTH';

	SELECT CURRDATE INTO v_CURRDATE
	FROM IFRS_PRC_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	-- GET PD_RULE_ID FOR MAA
	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        BUCKET_GROUP,
        HISTORICAL_DATA,
        POPULATION_MONTH,
        TRANSITION_START_DATE
	)
	SELECT
	    v_CURRDATE AS EFF_DATE,
		LAST_DAY(ADD_MONTHS(v_CURRDATE, A.INCREMENT_PERIOD * -1)) AS BASE_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.HISTORICAL_DATA,
		A.POPULATION_MONTH,
		LAST_DAY(ADD_MONTHS(v_CURRDATE, A.TRANSITION_DATA * -1)) AS TRANSITION_START_DATE
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MAA'
	AND DERIVED_PD_MODEL IS NULL;

	COMMIT;

	INSERT INTO TMP_IFRS_PD_MAA_AVG_MONTH
	SELECT PD_RULE_ID,
	REGEXP_SUBSTR (NVL(POPULATION_MONTH,'1,2,3,4,5,6,7,8,9,10,11,12'),
				 '[^,]+',
				 1,
				 LEVEL)
	 AS VALUE
    FROM TMP_IFRS_PD_RUNNING_DATE
    CONNECT BY REGEXP_SUBSTR (NVL(POPULATION_MONTH,'1,2,3,4,5,6,7,8,9,10,11,12'),
							 '[^,]+',
							 1,
							 LEVEL)
	    IS NOT NULL;

	COMMIT;

	DELETE IFRS_PD_MAA_ENR
	WHERE EFF_DATE = v_CURRDATE
	AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

	COMMIT;

	-- GET DATA FROM IFRS_PD_SCENARIO_DATA
	INSERT INTO TMP_IFRS_PD_SCENARIO_DATA
	SELECT
		A.EFF_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.PD_UNIQUE_ID,
		A.CALC_METHOD,
		MAX(CUSTOMER_NAME) AS CUSTOMER_NAME,
		SUM(CALC_AMOUNT) AS CALC_AMOUNT,
		MAX(BUCKET_ID) AS BUCKET_ID,
		SUM(OUTSTANDING) AS OUTSTANDING,
		TO_CHAR(A.PD_RULE_ID || A.PD_UNIQUE_ID) AS KEY_TMP
	FROM IFRS_PD_SCENARIO_DATA A
	JOIN TMP_IFRS_PD_MAA_AVG_MONTH B
	ON EXTRACT(MONTH FROM A.EFF_DATE) = B.POPULATION_MONTH
		AND A.PD_RULE_ID = B.PD_RULE_ID
	GROUP BY A.EFF_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.PD_UNIQUE_ID,
		A.CALC_METHOD;

	COMMIT;

	DELETE
	FROM
	(SELECT A.* FROM IFRS_PD_MIGRATION_DETAIL A
	 JOIN TMP_IFRS_PD_RUNNING_DATE B
	 ON A.EFF_DATE = B.EFF_DATE
		AND A.PD_RULE_ID = B.PD_RULE_ID
    );

    COMMIT;

    SELECT COUNT(*)
    INTO v_COUNT
    FROM USER_INDEXES WHERE INDEX_NAME='IDX_IFRS_PD_MIGRATION_DETAIL';

	IF v_COUNT > 0
	  THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_PD_MIGRATION_DETAIL ON IFRS_PD_MIGRATION_DETAIL';
	  END IF;

	/*Start inserting ENR population*/
	INSERT INTO IFRS_PD_MIGRATION_DETAIL
	(
		EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		PD_UNIQUE_ID,
		BUCKET_FROM,
		BUCKET_TO,
		CALC_AMOUNT,
		CUSTOMER_NAME,
		OUTSTANDING
	)
	SELECT A.EFF_DATE BASE_DATE,
		B.EFF_DATE EFF_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.PD_UNIQUE_ID,
		A.BUCKET_ID BUCKET_FROM,
		CASE WHEN A.BUCKET_ID = D.MAX_BUCKET_ID THEN
			D.MAX_BUCKET_ID
		ELSE
		   B.BUCKET_ID
		END BUCKET_TO,
		A.CALC_AMOUNT,
		B.CUSTOMER_NAME,
		A.OUTSTANDING
	FROM TMP_IFRS_PD_SCENARIO_DATA A
	JOIN TMP_IFRS_PD_SCENARIO_DATA B
	ON A.PD_RULE_ID = B.PD_RULE_ID
	AND A.PD_UNIQUE_ID = B.PD_UNIQUE_ID
	JOIN TMP_IFRS_PD_RUNNING_DATE C
	ON A.PD_RULE_ID = C.PD_RULE_ID
		AND B.PD_RULE_ID = C.PD_RULE_ID
		AND A.EFF_DATE = C.BASE_DATE
		AND B.EFF_DATE = C.EFF_DATE
	JOIN VW_IFRS_MAX_BUCKET D
	ON D.BUCKET_GROUP = A.BUCKET_GROUP
		AND D.BUCKET_GROUP=B.BUCKET_GROUP;

	COMMIT;

	INSERT INTO IFRS_PD_MIGRATION_DETAIL
	(
		EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		PD_UNIQUE_ID,
		BUCKET_FROM,
		BUCKET_TO,
		CALC_AMOUNT,
		CUSTOMER_NAME,
		OUTSTANDING
	)
	SELECT B.EFF_DATE,
		A.EFF_DATE BASE_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.PD_UNIQUE_ID,
		A.BUCKET_ID BUCKET_FROM,
		0 BUCKET_TO,
		A.CALC_AMOUNT,
		A.CUSTOMER_NAME,
		A.OUTSTANDING
	FROM TMP_IFRS_PD_SCENARIO_DATA A
	JOIN TMP_IFRS_PD_RUNNING_DATE B
	ON A.PD_RULE_ID = B.PD_RULE_ID
		AND A.EFF_DATE = B.BASE_DATE
	WHERE NOT EXISTS (
		SELECT 1
		FROM TMP_IFRS_PD_SCENARIO_DATA A2
		JOIN TMP_IFRS_PD_RUNNING_DATE B2
	    ON A2.PD_RULE_ID = B2.PD_RULE_ID
		AND A2.EFF_DATE = B2.EFF_DATE
		AND A.KEY_TMP = A2.KEY_TMP WHERE rownum <= 1);

	COMMIT;

	--WHERE ISNULL(A.KEY_TMP,'') NOT IN
	--(
	--	SELECT A2.KEY_TMP
	--	FROM #TMP_IFRS_PD_SCENARIO_DATA A2
	--	JOIN #TMP_IFRS_PD_RUNNING_DATE B2
	--    ON A2.PD_RULE_ID = B2.PD_RULE_ID
	--	AND A2.PERIOD = B2.CURR_DATE
	--)

	EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_PD_MIGRATION_DETAIL ON IFRS_PD_MIGRATION_DETAIL(CURR_DATE, PD_RULE_ID, PD_UNIQUE_ID)';
	/*End inserting ENR population*/

	-- COUNT FOR BUCKET MOVEMENT
	INSERT INTO IFRS_PD_MAA_ENR
	(
		EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_FROM,
		BUCKET_TO,
		CALC_AMOUNT
	)
	SELECT B.EFF_DATE,
		B.BASE_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.BUCKET_FROM,
		A.BUCKET_TO,
		SUM(A.CALC_AMOUNT)
	FROM IFRS_PD_MIGRATION_DETAIL A
	JOIN TMP_IFRS_PD_RUNNING_DATE B
	ON A.PD_RULE_ID = B.PD_RULE_ID
		AND A.EFF_DATE BETWEEN B.TRANSITION_START_DATE AND B.EFF_DATE
	GROUP BY
		B.EFF_DATE,
		B.BASE_DATE,
		A.PD_RULE_ID,
		A.BUCKET_GROUP,
		A.BUCKET_FROM,
		A.BUCKET_TO;

	COMMIT;

	INSERT INTO IFRS_PD_MAA_ENR
	(
		EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_FROM,
		BUCKET_TO,
		CALC_AMOUNT
	)
   SELECT DISTINCT
        A.EFF_DATE,
        A.BASE_DATE,
        PD_RULE_ID,
        A.BUCKET_GROUP,
        B.BUCKET_ID BUCKET_FROM,
        C.BUCKET_ID BUCKET_TO,
        0 AS CALC_AMOUNT
    FROM TMP_IFRS_PD_RUNNING_DATE A
    JOIN IFRS_BUCKET_DETAIL B
    ON A.BUCKET_GROUP = B.BUCKET_GROUP
    CROSS JOIN IFRS_BUCKET_DETAIL C
    WHERE C.BUCKET_GROUP = B.BUCKET_GROUP
        AND NOT EXISTS
        (
            SELECT 1 FROM IFRS_PD_MAA_ENR D
            WHERE D.PD_RULE_ID = A.PD_RULE_ID
                AND D.EFF_DATE = v_CURRDATE
                AND D.BUCKET_FROM = B.BUCKET_ID
                AND D.BUCKET_TO = C.BUCKET_ID
        );

    COMMIT;
END;