CREATE OR REPLACE PROCEDURE SP_IFRS_UPDATE_SECID
AS

V_CURRDATE DATE;

BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;

    INSERT INTO IFRS_MASTER_SECID
    (
        SEC_ID,
        SEC_NAME,
        ISIN,
        DATA_SOURCE
    )
    SELECT
        SEC_ID,
        SEC_NAME,
        ISIN,
        'KTP'
    FROM IFRS_STG_SECID
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND SEC_ID NOT IN (SELECT DISTINCT SEC_ID FROM IFRS_MASTER_SECID);
    COMMIT;

END;