CREATE OR REPLACE PROCEDURE SP_IFRS_EAD_PROCESS_MONTHLY(v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
    V_CURRDATE DATE;
    V_EOM DATE;
    V_SP_NAME VARCHAR2(50);
    V_EXISTS NUMBER(1) := 0;
BEGIN


    SELECT  v_DOWNLOADDATE,LAST_DAY(v_DOWNLOADDATE)
    INTO V_CURRDATE,V_EOM
    FROM DUAL ;

    V_SP_NAME:='SP_IFRS_EAD_PROCESS';

    IF V_CURRDATE=V_EOM
    THEN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_IMA_EAD';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD_IMP';

    DELETE FROM IFRS_EAD_RESULT
    WHERE DOWNLOAD_DATE=V_EOM AND ECL_MODEL_ID = V_ECLID;
    COMMIT;

    /*****************************************************
    01 GET RULES AND IMA
    ******************************************************/
    INSERT INTO TMP_IFRS_IMA_EAD
   (
    DOWNLOAD_DATE,
    MASTERID,
    CURRENCY,
    EXCHANGE_RATE,
    ECL_MODEL_ID,
    CR_STAGE,
    DATA_SOURCE,
    SEGMENT_RULE_ID,
    EAD_RULE_ID,
    EAD_SEGMENT,
    CCF_RULE_ID,
    PREPAYMENT_RULE_ID,
    LIFETIME_PERIOD,
    LOAN_START_DATE,
    LOAN_DUE_DATE,
    NEXT_PAYMENT_DATE,
    LAST_PAYMENT_DATE,
    UNUSED_AMOUNT,
    OUTSTANDING,
    REVOLVING_FLAG,
    EAD_BALANCE,
    UNAMORT_FEE_AMT,
    MARKET_AMOUNT,
    INTEREST_ACCRUED,
    COMMITMENT_FLAG
    )
    SELECT A.DOWNLOAD_DATE,
           A.MASTERID,
           A.CURRENCY,
           A.EXCHANGE_RATE,
           v_ECLID AS ECL_MODEL_ID,
           CR_STAGE,
           A.DATA_SOURCE,
           A.SEGMENT_RULE_ID,
           C.EAD_MODEL_ID AS EAD_RULE_ID,
           H.SUB_SEGMENT AS EAD_SEGMENT,
           C.CCF_RULES_ID,
           C.PREPAYMENT_RULES_ID,
           CEIL((MONTHS_BETWEEN(A.LOAN_DUE_DATE, v_DOWNLOADDATE))) AS LIFETIME,
           A.LOAN_START_DATE,
           A.LOAN_DUE_DATE,
           A.NEXT_PAYMENT_DATE,
           A.LAST_PAYMENT_DATE,
           CASE WHEN A.CR_STAGE = '3' AND NOT (A.DATA_SOURCE = 'BTRD' OR (A.DATA_SOURCE = 'ILS' AND A.PRODUCT_CODE LIKE 'B%')) THEN 0 --CCF ONLY APPLIED TO STAGE 1 AND 2
                WHEN A.DATA_SOURCE = 'ILS' AND A.PRODUCT_CODE LIKE 'B%' THEN A.OUTSTANDING
                WHEN D.SUM_OUTSTANDING = 0 AND D.UNUSED_AMOUNT > 0 THEN ((D.UNUSED_AMOUNT * NVL(A.EXCHANGE_RATE, 1)) / D.NOA)/ NVL(A.EXCHANGE_RATE, 1)
                WHEN D.SUM_OUTSTANDING > 0 AND D.UNUSED_AMOUNT > 0 THEN (NVL(A.OUTSTANDING,0) * NVL(A.EXCHANGE_RATE, 1)/ D.SUM_OUTSTANDING) * (D.UNUSED_AMOUNT * NVL(A.EXCHANGE_RATE, 1)) / NVL(A.EXCHANGE_RATE, 1)
                --WHEN COALESCE(D.SUM_OUTSTANDING, E.SUM_OUTSTANDING) = 0 AND COALESCE(D.UNUSED_AMOUNT, E.UNUSED_AMOUNT) > 0 THEN ((COALESCE(D.UNUSED_AMOUNT, E.UNUSED_AMOUNT) * NVL(A.EXCHANGE_RATE, 1)) / D.NOA)/ NVL(A.EXCHANGE_RATE, 1)
                --WHEN COALESCE(D.SUM_OUTSTANDING, E.SUM_OUTSTANDING) > 0 AND COALESCE(D.UNUSED_AMOUNT, E.UNUSED_AMOUNT) > 0 THEN (NVL(A.OUTSTANDING,0) * NVL(A.EXCHANGE_RATE, 1)/ COALESCE(D.SUM_OUTSTANDING, E.SUM_OUTSTANDING)) * (COALESCE(D.UNUSED_AMOUNT, E.UNUSED_AMOUNT) * NVL(A.EXCHANGE_RATE, 1)) / NVL(A.EXCHANGE_RATE, 1)
                WHEN NVL(A.RESERVED_AMOUNT_2,0) > 0 AND A.DATA_SOURCE = 'CRD' THEN NVL(A.RESERVED_AMOUNT_2,0)
                ELSE 0
           END AS UNUSED_AMOUNT,
           CASE WHEN A.DATA_SOURCE = 'ILS' AND A.PRODUCT_CODE LIKE 'B%' THEN 0 ELSE NVL(A.OUTSTANDING,0) END AS OUTSTANDING,
           NVL(A.REVOLVING_FLAG,0) REVOLVING_FLAG,
           B.EAD_BALANCE,
           A.UNAMORT_FEE_AMT,
           A.RESERVED_AMOUNT_13 AS MARKET_AMOUNT,
           CASE WHEN A.BI_COLLECTABILITY IN ('3','4','5','C') THEN 0
                ELSE
                    CASE WHEN A.DATA_SOURCE = 'KTP' AND NVL(A.RESERVED_AMOUNT_9,0) > 0 THEN NVL(A.RESERVED_AMOUNT_9,0) -- TREASURY - Effective interest Accrue
                         ELSE CASE WHEN A.CR_STAGE <> '3' THEN NVL(A.INTEREST_ACCRUED,0) ELSE 0 END
                    END
           END INTEREST_ACCRUED,
           CASE WHEN A.DATA_SOURCE IN ('CRD','BTRD') OR (A.DATA_SOURCE = 'ILS' AND A.PRODUCT_CODE LIKE 'B%') THEN 1 ELSE NVL(D.COMMITMENT_FLAG,0) END COMMITMENT_FLAG
    FROM IFRS_MASTER_ACCOUNT A
    JOIN IFRS_ECL_MODEL_CONFIG C ON C.PF_SEGMENT_ID = A.SEGMENT_RULE_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
    JOIN IFRS_EAD_RULES_CONFIG B ON C.EAD_MODEL_ID=B.PKID
    JOIN IFRS_MSTR_SEGMENT_RULES_HEADER H ON B.SEGMENTATION_ID=H.PKID
    LEFT JOIN (
          SELECT D1.DOWNLOAD_DATE, D1.ACCOUNT_NUMBER AS FACILITY_NUMBER, D1.RESERVED_AMOUNT_14 AS UNUSED_AMOUNT,
                SUM(NVL(D2.OUTSTANDING, 0) * NVL(D2.EXCHANGE_RATE,0)) AS SUM_OUTSTANDING,
                COUNT(1) AS NOA, MAX(D1.COMMITTED_FLAG) COMMITMENT_FLAG
            FROM IFRS_MASTER_ACCOUNT D1
            JOIN IFRS_MASTER_ACCOUNT D2
              ON D1.ACCOUNT_NUMBER = D2.FACILITY_NUMBER
             AND D1.DOWNLOAD_DATE = D2.DOWNLOAD_DATE
           WHERE D1.DOWNLOAD_DATE = v_DOWNLOADDATE AND D1.DATA_SOURCE = 'LIMIT'
           GROUP BY D1.DOWNLOAD_DATE, D1.ACCOUNT_NUMBER, D1.RESERVED_AMOUNT_14
    ) D
    ON A.FACILITY_NUMBER = D.FACILITY_NUMBER
    AND A.DOWNLOAD_DATE = D.DOWNLOAD_DATE
    /* REMARKED BY YTA 2019-01-03
    LEFT JOIN (
       SELECT E1.DOWNLOAD_DATE, SUBSTR(E1.ACCOUNT_NUMBER,1,7) AS ACCOUNT_NUMBER,
              SUM(CASE WHEN E2.OUTSTANDING < E2.LIMIT THEN  E2.LIMIT - E2.OUTSTANDING ELSE 0 END) UNUSED_AMOUNT,
              SUM(NVL(E1.OUTSTANDING,0) * NVL(E1.EXCHANGE_RATE,1)) AS SUM_OUTSTANDING,
              COUNT(1) AS NOA --OFF BALANCE SHEET LC
          FROM IFRS_MASTER_ACCOUNT E1
          JOIN (
                SELECT DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7) AS ACCOUNT_NUMBER,
                SUM(CASE WHEN RESERVED_FLAG_1 = 0 THEN NVL(OUTSTANDING,0) ELSE 0 END) AS LIMIT,
                SUM(CASE WHEN RESERVED_FLAG_1 = 1 THEN NVL(OUTSTANDING,0) ELSE 0 END) AS OUTSTANDING
                FROM IFRS_MASTER_ACCOUNT
                WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
                AND DATA_SOURCE = 'BTRD' AND RESERVED_FLAG_1 = 0
                AND ACCOUNT_STATUS = 'A'
                GROUP BY DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7)
          ) E2
            ON SUBSTR(E1.ACCOUNT_NUMBER,1,7) = E2.ACCOUNT_NUMBER
           AND E1.DOWNLOAD_DATE = E2.DOWNLOAD_DATE
       WHERE E1.DOWNLOAD_DATE = v_DOWNLOADDATE
       AND E1.DATA_SOURCE = 'BTRD' AND E1.RESERVED_FLAG_1 = 1
       AND E1.ACCOUNT_STATUS = 'A'
       GROUP BY E1.DOWNLOAD_DATE, SUBSTR(E1.ACCOUNT_NUMBER,1,7)
    ) E
    ON SUBSTR(A.ACCOUNT_NUMBER,1,7) = SUBSTR(E.ACCOUNT_NUMBER,1,7)
    AND A.DOWNLOAD_DATE = E.DOWNLOAD_DATE
    */
    WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE AND C.ECL_MODEL_ID = v_ECLID
    AND (A.ACCOUNT_STATUS = 'A' OR (A.DATA_SOURCE = 'CRD' AND A.ACCOUNT_STATUS = 'C' AND A.OUTSTANDING > 0))
    AND NOT ((A.DATA_SOURCE = 'BTRD' AND RESERVED_FLAG_1 = 0) OR (A.DATA_SOURCE = 'KTP' AND A.SEGMENT = 'PBMM' AND A.RESERVED_FLAG_1 = 0) OR A.DATA_SOURCE = 'LIMIT')
    AND NVL(A.IS_IMPAIRED,0) = 1

    UNION ALL

    /*****************************************************
    01b ACCOUNT LC OFF BS WITHOUT ON BALANCE SHEET
    ******************************************************/
    SELECT A.DOWNLOAD_DATE,
           A.MASTERID,
           A.CURRENCY,
           A.EXCHANGE_RATE,
           v_ECLID AS ECL_MODEL_ID,
           A.CR_STAGE,
           A.DATA_SOURCE,
           A.SEGMENT_RULE_ID,
           C.EAD_MODEL_ID AS EAD_RULE_ID,
           H.SUB_SEGMENT AS EAD_SEGMENT,
           C.CCF_RULES_ID,
           C.PREPAYMENT_RULES_ID,
           CASE WHEN NVL(A.LOAN_DUE_DATE,'1-JAN-1900') > v_DOWNLOADDATE THEN CEIL((MONTHS_BETWEEN(A.LOAN_DUE_DATE, v_DOWNLOADDATE))) ELSE 12 END AS LIFETIME,
           --12 AS LIFETIME,
           A.LOAN_START_DATE,
           A.LOAN_DUE_DATE,
           A.NEXT_PAYMENT_DATE,
           A.LAST_PAYMENT_DATE,
           CASE WHEN A.CR_STAGE = '3' AND NOT (A.DATA_SOURCE = 'BTRD' OR (A.DATA_SOURCE = 'ILS' AND A.PRODUCT_CODE LIKE '%B')) THEN 0 --CCF ONLY APPLIED TO STAGE 1 AND 2
                WHEN A.DATA_SOURCE = 'LIMIT' THEN NVL(A.RESERVED_AMOUNT_14,0)
                WHEN A.DATA_SOURCE = 'KTP' AND A.SEGMENT = 'PBMM' THEN NVL(A.RESERVED_AMOUNT_14,0)
                ELSE NVL(A.OUTSTANDING, 0)
           END AS UNUSED_AMOUNT,
           0 AS OUTSTANDING,
           NVL(A.REVOLVING_FLAG,0) REVOLVING_FLAG,
           B.EAD_BALANCE,
           A.UNAMORT_FEE_AMT,
           A.RESERVED_AMOUNT_13 AS MARKET_AMOUNT,
           0 AS INTEREST_ACCRUED,
           1 AS COMMITMENT_FLAG
    FROM IFRS_MASTER_ACCOUNT A
    JOIN IFRS_ECL_MODEL_CONFIG C ON C.PF_SEGMENT_ID = A.SEGMENT_RULE_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
    JOIN IFRS_EAD_RULES_CONFIG B ON C.EAD_MODEL_ID=B.PKID
    JOIN IFRS_MSTR_SEGMENT_RULES_HEADER H ON B.SEGMENTATION_ID=H.PKID
    WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE AND C.ECL_MODEL_ID = v_ECLID
    AND A.ACCOUNT_STATUS = 'A'
    AND ((A.DATA_SOURCE IN('BTRD','LIMIT') AND A.RESERVED_FLAG_1 = 0) OR (A.DATA_SOURCE = 'KTP' AND A.SEGMENT = 'PBMM' AND A.RESERVED_FLAG_1 = 0))
    /* REMARKED BY YTA 2019-01-03
    AND NOT EXISTS(
        SELECT 1 FROM IFRS_MASTER_ACCOUNT X
        WHERE X.DOWNLOAD_DATE = v_DOWNLOADDATE
        AND (X.DATA_SOURCE = 'BTRD' AND X.RESERVED_FLAG_1 = 1)
        AND SUBSTR(X.ACCOUNT_NUMBER,1,7) = SUBSTR(A.ACCOUNT_NUMBER,1,7)
    )
    */
    AND NVL(A.IS_IMPAIRED,0) = 1;

    COMMIT;

    DELETE TMP_IFRS_IMA_EAD
    WHERE OUTSTANDING = 0 AND UNUSED_AMOUNT = 0;

    COMMIT;

    /*****************************************************
    02 GET PAYMENT SCHEDULE
    ******************************************************/
    SELECT COUNT(*) INTO V_EXISTS
    FROM user_indexes
    WHERE index_name = 'IDX_IFRS_PAYM_SCHD_ALL_3';

    IF V_EXISTS = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_PAYM_SCHD_ALL_3';
    END IF;

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_PAYM_SCHD_ALL_3 ON IFRS_PAYM_SCHD_ALL
                       (DOWNLOAD_DATE, MASTERID, COUNTER)
                       NOLOGGING
                       TABLESPACE IFRS_IDX_TBS';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD_MAX';



    INSERT INTO TMP_IFRS_PAYM_SCHD_MAX(DOWNLOAD_DATE, MASTERID)
    SELECT MAX(A.DOWNLOAD_DATE) MAX_DOWNLOAD_DATE, A.MASTERID
            FROM IFRS_PAYM_SCHD_ALL A
            JOIN TMP_IFRS_IMA_EAD B
            ON A.DOWNLOAD_DATE <= V_EOM
            AND A.MASTERID = B.MASTERID
            AND B.CR_STAGE = '1'
            GROUP BY A.MASTERID;
    COMMIT;

    INSERT INTO TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT * FROM
    (
        SELECT  V_CURRDATE DOWNLOAD_DATE,
            A.MASTERID,
            LAST_DAY(A.PMTDATE) AS PMTDATE,
            A.OSPRN,
            A.PRINCIPAL,
            A.INTEREST,
            ROW_NUMBER() OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER) COUNTER
        FROM IFRS_PAYM_SCHD_ALL A
        JOIN TMP_IFRS_PAYM_SCHD_MAX B
        ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
        AND A.MASTERID = B.MASTERID
        AND LAST_DAY(A.PMTDATE) >= V_EOM
    ) A
    WHERE COUNTER <= 12
    ;
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD_MAX';

    INSERT INTO TMP_IFRS_PAYM_SCHD_MAX(DOWNLOAD_DATE, MASTERID, CR_STAGE)
    SELECT MAX(A.DOWNLOAD_DATE) MAX_DOWNLOAD_DATE, A.MASTERID, MAX(CR_STAGE)
            FROM IFRS_PAYM_SCHD_ALL A
            JOIN TMP_IFRS_IMA_EAD B
            ON A.DOWNLOAD_DATE <= V_EOM
            AND A.MASTERID = B.MASTERID
            AND B.CR_STAGE > '1'
            GROUP BY A.MASTERID;
    COMMIT;

    INSERT INTO TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    FROM
    (
        SELECT  V_CURRDATE DOWNLOAD_DATE,
            A.MASTERID,
            LAST_DAY(A.PMTDATE) AS PMTDATE,
            A.OSPRN,
            A.PRINCIPAL,
            A.INTEREST,
        ROW_NUMBER() OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER) COUNTER,
            B.CR_STAGE
        FROM IFRS_PAYM_SCHD_ALL A
        JOIN TMP_IFRS_PAYM_SCHD_MAX B
        ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
        AND A.MASTERID = B.MASTERID
        AND LAST_DAY(A.PMTDATE) >=V_EOM
    ) A
    WHERE COUNTER = CASE WHEN A.CR_STAGE = '3' THEN 1 ELSE COUNTER END
    ;
    COMMIT;

    EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_PAYM_SCHD_ALL_3';

    /*****************************************************
    02 UPDATE CARRYING AMOUNT IN PAYMENT SCHEDULE
    ******************************************************/
    MERGE INTO TMP_IFRS_PAYM_SCHD_IMP A
    USING
    (
        SELECT A.MASTERID,
            A.COUNTER,
            CASE WHEN B.OUTSTANDING - SUM(CASE WHEN A.COUNTER = 1 THEN 0 ELSE A.PRINCIPAL END) OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER ASC) < 0 THEN
                0
            ELSE
                B.OUTSTANDING - SUM(CASE WHEN A.COUNTER = 1 THEN 0 ELSE A.PRINCIPAL END) OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER ASC)
            END AS NEW_OS
        FROM TMP_IFRS_PAYM_SCHD_IMP A
        JOIN TMP_IFRS_IMA_EAD B
        ON A.MASTERID = B.MASTERID
    ) B
    ON (A.MASTERID = B.MASTERID AND A.COUNTER = B.COUNTER)
    WHEN MATCHED THEN
    UPDATE SET
        A.OSPRN = B.NEW_OS;

    COMMIT;

    /*****************************************************
    04 GENERATE PAYMENT SCHEDULE FOR BANK AND TREASURY
    ******************************************************/
    INSERT INTO TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT  V_CURRDATE,
            A.MASTERID,
            CASE WHEN A.NEXT_PAYMENT_DATE IS NOT NULL AND A.LAST_PAYMENT_DATE IS NOT NULL THEN ADD_MONTHS(A.NEXT_PAYMENT_DATE, FLOOR((MONTHS_BETWEEN(A.NEXT_PAYMENT_DATE, A.LAST_PAYMENT_DATE))) * (G.MONTHS - 1))
                 ELSE CASE WHEN G.MONTHS = 1 THEN v_DOWNLOADDATE ELSE ADD_MONTHS(v_DOWNLOADDATE, (G.MONTHS-1)) END
            END AS PMTDATE,
            A.OUTSTANDING AS OSPRN,
            0 AS  PRINCIPAL,
            0 AS INTEREST,
            ROW_NUMBER() OVER (PARTITION BY A.MASTERID ORDER BY G.MONTHS)
    FROM TMP_IFRS_IMA_EAD A
    INNER JOIN IFRS_ECL_MODEL_CONFIG F  ON A.DOWNLOAD_DATE = F.DOWNLOAD_DATE AND A.ECL_MODEL_ID = F.ECL_MODEL_ID AND A.SEGMENT_RULE_ID = F.PF_SEGMENT_ID AND A.EAD_RULE_ID = F.EAD_MODEL_ID
    LEFT JOIN IFRS_LIFETIME_HEADER L    ON F.LT_EFF_DATE =L.DOWNLOAD_DATE AND F.LT_RULE_ID=L.LIFETIME_CONFIG_ID
    LEFT JOIN (
        SELECT ROWNUM MONTHS FROM DUAL
        CONNECT BY ROWNUM <=
        (
            SELECT MAX(LIFETIME_PERIOD)
            FROM IFRS_LIFETIME_HEADER A
            JOIN IFRS_ECL_MODEL_CONFIG B
            ON A.LIFETIME_CONFIG_ID = B.LT_RULE_ID
            AND A.DOWNLOAD_DATE = B.LT_EFF_DATE
            AND B.ECL_MODEL_ID = v_ECLID
            AND B.DOWNLOAD_DATE = V_EOM
        )
    ) G ON ((NVL(A.REVOLVING_FLAG,0) = 1 AND A.CR_STAGE = '1' AND G.MONTHS <= 12) OR (A.CR_STAGE > '1' AND NVL(A.REVOLVING_FLAG,0) = 1 AND G.MONTHS <= NVL(L.LIFETIME_PERIOD, 12))
             OR (NVL(A.REVOLVING_FLAG,0) = 0 AND G.MONTHS <= LEAST(CASE WHEN L.LIFETIME_PERIOD < 12 THEN 12 ELSE L.LIFETIME_PERIOD END, FLOOR((MONTHS_BETWEEN(A.LOAN_DUE_DATE, v_DOWNLOADDATE))))))
    OR (A.DATA_SOURCE IN ('BTRD') AND G.MONTHS <= NVL(A.LIFETIME_PERIOD, 12) )
    OR (A.DATA_SOURCE IN ('KTP') AND A.NEXT_PAYMENT_DATE IS NOT NULL
        AND G.MONTHS <= (FLOOR((MONTHS_BETWEEN(A.LOAN_DUE_DATE, A.NEXT_PAYMENT_DATE)))/ FLOOR((MONTHS_BETWEEN(A.NEXT_PAYMENT_DATE, A.LAST_PAYMENT_DATE)))) + 1  )
    OR (A.DATA_SOURCE IN ('KTP') AND A.NEXT_PAYMENT_DATE IS NULL AND G.MONTHS <= (CASE WHEN F.SEGMENT = 'PBMM' THEN 12 ELSE LEAST(CASE WHEN L.LIFETIME_PERIOD = 0 THEN 12 ELSE L.LIFETIME_PERIOD END, FLOOR((MONTHS_BETWEEN(A.LOAN_DUE_DATE, v_DOWNLOADDATE)))) END))
    OR (A.DATA_SOURCE IN ('RKN') AND G.MONTHS <= NVL(A.LIFETIME_PERIOD, 1))
    WHERE F.ECL_MODEL_ID = v_ECLID
    AND NOT EXISTS (SELECT * FROM TMP_IFRS_PAYM_SCHD_IMP C WHERE A.MASTERID=C.MASTERID);

    COMMIT;

    SELECT COUNT(*) INTO V_EXISTS
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_IFRS_EAD_RESULT';

    IF V_EXISTS = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_EAD_RESULT';
    END IF;

    /*****************************************************
    05. EAD
    ******************************************************/
    INSERT INTO IFRS_EAD_RESULT
    (
    PKID,
    DOWNLOAD_DATE,
    MASTERID,
    CURRENCY,
    EXCHANGE_RATE,
    ECL_MODEL_ID,
    CR_STAGE,
    EAD_RULE_ID,
    EAD_SEGMENT,
    CCF_RULE_ID,
    PREPAYMENT_RULE_ID,
    UNUSED_AMOUNT,
    REVOLVING_FLAG,
    MARKET_AMOUNT,
    INTEREST_ACCRUED,
    CCF_RATE,
    CCF_AMOUNT,
    PREPAYMENT_RATE,
    PREPAYMENT_AMOUNT,
    OUTSTANDING,
    UNAMORT_FEE_COST,
    FAIRVALUE,
    PMTDATE,
    EAD_AMOUNT,
    COUNTER,
    MAX_COUNTER,
    CREATEDDATE,
    CREATEDBY
    )
    SELECT  /*+ PARALLEL(E,8) */
            0,
            A.DOWNLOAD_DATE,
            A.MASTERID,
            A.CURRENCY,
            A.EXCHANGE_RATE,
            v_ECLID as ECL_MODEL_ID,
            A.CR_STAGE,
            A.EAD_RULE_ID,
            A.EAD_SEGMENT,
            A.CCF_RULE_ID,
            A.PREPAYMENT_RULE_ID,
            NVL(A.UNUSED_AMOUNT,0) AS UNUSED_AMOUNT,
            A.REVOLVING_FLAG,
            A.MARKET_AMOUNT,
            CASE WHEN COALESCE(E.COUNTER,1)=1 AND A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN A.INTEREST_ACCRUED ELSE 0 END AS INTEREST_ACCRUED,
            B.CCF_RATE,
            CASE
                WHEN A.CCF_RULE_ID IS NOT NULL
                    AND ((F.CCF_REVOLVING_FLAG LIKE '%'|| A.REVOLVING_FLAG ||'%' )  AND
                        (F.CCF_COMMITED_FLAG LIKE '%'|| A.COMMITMENT_FLAG ||'%'))
                THEN (B.CCF_RATE*A.UNUSED_AMOUNT)
                ELSE 0
            END AS CCF_AMOUNT,
            C.AVERAGE_SMM PREPAYMENT_RATE,
            CASE WHEN (CASE  WHEN A.EAD_BALANCE LIKE 'CV%' OR ((A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE '%UNAMORT_FEE_COST%' AND A.EAD_BALANCE NOT LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN ('2', '3')  THEN 0 ELSE COALESCE(C.AVERAGE_SMM,0) END) < 0 THEN 0
            ELSE
            (CASE  WHEN A.EAD_BALANCE LIKE 'CV%' OR ((A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE '%UNAMORT_FEE_COST%' AND A.EAD_BALANCE NOT LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN ('2', '3')  THEN 0 ELSE COALESCE(C.AVERAGE_SMM,0) END) END AS PREPAYMENT_AMOUNT,
            CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END AS OUTSTANDING,
            CASE WHEN A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE 'CV%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%'
                 THEN COALESCE(A.UNAMORT_FEE_AMT,0)
                 ELSE 0 END AS UNAMORT_FEE_COST,
            CASE  WHEN A.EAD_BALANCE LIKE 'CV%'
                      OR ((A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
--                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE '%UNAMORT_FEE_COST%' AND A.EAD_BALANCE NOT LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END AS FAIRVALUE,
            E.PMTDATE AS PMTDATE,
            (CASE  WHEN A.EAD_BALANCE LIKE 'CV%' OR ((A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
--                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE '%UNAMORT_FEE_COST%' AND A.EAD_BALANCE NOT LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END)
            - (CASE  WHEN A.EAD_BALANCE LIKE 'CV%' OR ((A.EAD_BALANCE LIKE '%UNAMORT_FEE_COST%' OR A.EAD_BALANCE LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
--                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE '%UNAMORT_FEE_COST%' AND A.EAD_BALANCE NOT LIKE '%UNAMORT_DISC_PREM%') AND A.EAD_BALANCE LIKE 'OS%')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN ('2', '3') THEN 0 ELSE COALESCE(C.AVERAGE_SMM,0) END)
            +CASE WHEN A.EAD_BALANCE LIKE '%ACCRUED_INT%' AND COALESCE(E.COUNTER,1)=1 AND CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END > 0 THEN NVL(A.INTEREST_ACCRUED,0) ELSE 0 END
            +CASE WHEN A.EAD_BALANCE LIKE '%MARKET_VALUE%' THEN A.MARKET_AMOUNT ELSE 0 END
             +CASE
                WHEN A.CCF_RULE_ID IS NOT NULL
                    AND ((F.CCF_REVOLVING_FLAG LIKE '%'|| A.REVOLVING_FLAG ||'%' )  AND
                        (F.CCF_COMMITED_FLAG LIKE '%'|| A.COMMITMENT_FLAG ||'%'))
                THEN (B.CCF_RATE*A.UNUSED_AMOUNT)
                ELSE 0
             END AS EAD_AMOUNT,
            ROW_NUMBER() OVER (PARTITION BY A.DOWNLOAD_DATE,A.MASTERID ORDER BY E.COUNTER) AS RN,
            SUM(1) OVER (PARTITION BY A.DOWNLOAD_DATE,A.MASTERID) AS MAX_COUNTER,
            SYSTIMESTAMP,
            V_SP_NAME
    FROM TMP_IFRS_IMA_EAD A
    INNER JOIN IFRS_ECL_MODEL_CONFIG F  ON A.DOWNLOAD_DATE = F.DOWNLOAD_DATE AND A.ECL_MODEL_ID = F.ECL_MODEL_ID AND A.SEGMENT_RULE_ID = F.PF_SEGMENT_ID AND A.EAD_RULE_ID = F.EAD_MODEL_ID
    LEFT JOIN IFRS_CCF_HEADER B         ON B.DOWNLOAD_DATE=F.CCF_EFF_DATE AND A.CCF_RULE_ID=B.CCF_RULE_ID
    LEFT JOIN IFRS_PREPAYMENT_HEADER C  ON C.DOWNLOAD_DATE=F.PREPAYMENT_EFF_DATE AND A.PREPAYMENT_RULE_ID=C.PREPAYMENT_RULE_ID
    LEFT JOIN TMP_IFRS_PAYM_SCHD_IMP E  ON A.MASTERID=E.MASTERID
    WHERE F.ECL_MODEL_ID = v_ECLID
    ;

    COMMIT;

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_EAD_RESULT ON IFRS_EAD_RESULT
                       (DOWNLOAD_DATE, ECL_MODEL_ID, EAD_RULE_ID, MASTERID, COUNTER)
                       LOGGING
                       TABLESPACE IFRS_IDX_TBS';

    merge into ifrs_ead_result a
    using
    (
    Select masterid from ifrs_ead_result
    where download_date = V_EOM
    and pmtdate = V_EOM
--    and cr_stage > '1'
    group by masterid having count(*) > 1
    ) b
    on (a.masterid = b.masterid)
    when matched then
    update set a.max_counter = a.max_counter - 1;

    --ADDED BY WILLY - LIFETIME SET TO 12 WHEN UNDER 12

    UPDATE IFRS_EAD_RESULT
    SET MAX_COUNTER = 12
    WHERE REVOLVING_FLAG = 1
    AND PMTDATE = V_EOM
    AND EAD_SEGMENT NOT LIKE '%CREDIT CARD%'
    AND CR_STAGE <> 1;COMMIT;

    END IF;
END;