CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_JRNL_DATA_FAC
AS
	V_CURRDATE DATE;
	V_PREVDATE DATE;
	V_PREVMONTH DATE;
BEGIN

	SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    V_PREVMONTH := LAST_DAY(ADD_MONTHS(V_CURRDATE,-1))  ;

	/**********************
	  1. PNL
	***********************/
	INSERT /*+ PARALLEL(8) */ INTO IFRS_ACCT_JOURNAL_DATA (
	  DOWNLOAD_DATE
	  ,MASTERID
	  ,FACNO
	  ,CIFNO
	  ,ACCTNO
	  ,DATASOURCE
	  ,PRDTYPE
	  ,PRDCODE
	  ,TRXCODE
	  ,CCY
	  ,JOURNALCODE
	  ,STATUS
	  ,REVERSE
	  ,FLAG_CF
	  ,DRCR
	  ,GLNO
	  ,N_AMOUNT
	  ,N_AMOUNT_IDR
	  ,SOURCEPROCESS
	  ,INTMID
	  ,CREATEDDATE
	  ,CREATEDBY
	  ,BRANCH
	  ,JOURNALCODE2
	  ,JOURNAL_DESC
	  ,NOREF
	  ,VALCTR_CODE
	  ,GL_INTERNAL_CODE
	  ,METHOD
	  ,GL_COSTCENTER
	  )
	SELECT /*+ PARALLEL(8) */
		 A.MATURITY_DATE AS DOWNLOAD_DATE
		,A.FACILITY_NUMBER AS MASTERID
		,A.FACILITY_NUMBER AS FACNO
		,A.FACILITY_NUMBER AS CIFNO
		,A.FACILITY_NUMBER AS ACCTNO
		,A.DATA_SOURCE AS DATASOURCE
		,A.PRD_TYPE AS PRDTYPE
		,A.PRD_CODE AS PRDCODE
		,A.TRX_CODE AS TRXCODE
		,A.CCY AS CCY
		,C.JOURNALCODE
		,'ACT' AS STATUS
		,'N' AS REVERSE
		,A.FLAG_CF
		,C.DRCR
		,C.GLNO
		,A.UNALOC AS N_AMOUNT
		,(A.UNALOC * B.RATE_AMOUNT )AS N_AMOUNT_IDR
		,'PNL FACILITY' AS SOURCEPROCESS
		,NULL INTMID
		,SYSTIMESTAMP AS CREATEDDATE
		,'JOURNAL FACILITY' AS CREATEDBY
		,A.BRANCH_CODE
		,C.JOURNALCODE    AS JOURNALCODE2
		,C.JOURNAL_DESC
		,NULL AS NOREF
		,C.COSTCENTER
		,C.GL_INTERNAL_CODE
		,NULL METHOD
		,C.COSTCENTER
	FROM IFRS_TRX_FACILITY_HEADER A
	JOIN IFRS_MASTER_EXCHANGE_RATE B
		ON A.CCY = B.CURRENCY
		  AND A.MATURITY_DATE = B.DOWNLOAD_DATE
	JOIN IFRS_JOURNAL_PARAM C
		ON A.GL_CONSTNAME = C.GL_CONSTNAME
		  AND (  A.TRX_CODE = C.TRX_CODE OR C.TRX_CODE = 'ALL')
		  AND (A.CCY = C.CCY OR C.CCY = 'ALL')
		  AND C.JOURNALCODE = 'AMORTF'
		  AND A.FLAG_CF = C.FLAG_CF
	WHERE A.UNALOC > 0
	  AND A.MATURITY_DATE = V_CURRDATE
	  AND A.STATUS = 'PNL'
	  AND A.REVID IS NULL
	  AND A.PKID NOT IN ( SELECT DISTINCT REVID FROM IFRS_TRX_FACILITY_HEADER WHERE REVID IS NOT NULL);

	COMMIT;

	/*************************
	 2. JOURNAL ITRCG
	**************************/
	INSERT /*+ PARALLEL(8) */ INTO IFRS_ACCT_JOURNAL_DATA (
	  DOWNLOAD_DATE
	  ,MASTERID
	  ,FACNO
	  ,CIFNO
	  ,ACCTNO
	  ,DATASOURCE
	  ,PRDTYPE
	  ,PRDCODE
	  ,TRXCODE
	  ,CCY
	  ,JOURNALCODE
	  ,STATUS
	  ,REVERSE
	  ,FLAG_CF
	  ,DRCR
	  ,GLNO
	  ,N_AMOUNT
	  ,N_AMOUNT_IDR
	  ,SOURCEPROCESS
	  ,INTMID
	  ,CREATEDDATE
	  ,CREATEDBY
	  ,BRANCH
	  ,JOURNALCODE2
	  ,JOURNAL_DESC
	  ,NOREF
	  ,VALCTR_CODE
	  ,GL_INTERNAL_CODE
	  ,METHOD
	  ,GL_COSTCENTER
	  )
	SELECT  /*+ PARALLEL(8) */
		A.DOWNLOAD_DATE
		,A.FACILITY_NUMBER  AS MASTERID
		,A.FACILITY_NUMBER AS FACNO
		,A.FACILITY_NUMBER  AS CIFNO
		,A.FACILITY_NUMBER  AS ACCTNO
		,A.DATA_SOURCE    AS DATASOURCE
		,A.PRD_TYPE AS PRDTYPE
		,A.PRD_CODE  AS PRDCODE
		,A.TRX_CODE   AS TRXCODE
		,A.CCY     AS CCY
		,C.JOURNALCODE
		,'ACT' AS STATUS
		,'N' AS REVERSE
		,A.FLAG_CF
		,C.DRCR
		,C.GLNO
		,A.TRX_AMOUNT AS N_AMOUNT
		,(A.TRX_AMOUNT * B.RATE_AMOUNT )AS N_AMOUNT_IDR
		,'ACT FACILITY' AS SOURCEPROCESS
		,NULL INTMID
		,SYSTIMESTAMP AS CREATEDDATE
		,'JOURNAL FACILITY' AS CREATEDBY
		,A.BRANCH_CODE
		,C.JOURNALCODE    AS JOURNALCODE2
		,C.JOURNAL_DESC
		,NULL AS NOREF
		,C.COSTCENTER
		,C.GL_INTERNAL_CODE
		,NULL METHOD
		,C.COSTCENTER
	FROM IFRS_TRX_FACILITY_HEADER A
	JOIN IFRS_MASTER_EXCHANGE_RATE B
		ON A.CCY = B.CURRENCY
		  AND A.DOWNLOAD_DATE= B.DOWNLOAD_DATE
	JOIN IFRS_JOURNAL_PARAM C
		ON A.GL_CONSTNAME = C.GL_CONSTNAME
		  AND (A.TRX_CODE = C.TRX_CODE OR C.TRX_CODE = 'ALL')
		  AND (A.CCY = C.CCY OR C.CCY = 'ALL')
		  AND C.JOURNALCODE = 'ITRCGF'
		  AND A.FLAG_CF = C.FLAG_CF
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
	  AND A.REVID IS NULL;

	COMMIT;

	/*************************
	 3. JOURNAL IF STATUS 'REV'
	**************************/
	INSERT /*+ PARALLEL(8) */ INTO IFRS_ACCT_JOURNAL_DATA (
	  DOWNLOAD_DATE
	  ,MASTERID
	  ,FACNO
	  ,CIFNO
	  ,ACCTNO
	  ,DATASOURCE
	  ,PRDTYPE
	  ,PRDCODE
	  ,TRXCODE
	  ,CCY
	  ,JOURNALCODE
	  ,STATUS
	  ,REVERSE
	  ,FLAG_CF
	  ,DRCR
	  ,GLNO
	  ,N_AMOUNT
	  ,N_AMOUNT_IDR
	  ,SOURCEPROCESS
	  ,INTMID
	  ,CREATEDDATE
	  ,CREATEDBY
	  ,BRANCH
	  ,JOURNALCODE2
	  ,JOURNAL_DESC
	  ,NOREF
	  ,VALCTR_CODE
	  ,GL_INTERNAL_CODE
	  ,METHOD
	  ,GL_COSTCENTER
	  )
	SELECT  /*+ PARALLEL(8) */
		A.DOWNLOAD_DATE
		,A.FACILITY_NUMBER AS MASTERID
		,A.FACILITY_NUMBER AS FACNO
		,A.FACILITY_NUMBER AS CIFNO
		,A.FACILITY_NUMBER AS ACCTNO
		,A.DATA_SOURCE AS DATASOURCE
		,A.PRD_TYPE AS PRDTYPE
		,A.PRD_CODE AS PRDCODE
		,A.TRX_CODE AS TRXCODE
		,A.CCY AS CCY
		,C.JOURNALCODE
		,'ACT' AS STATUS
		,'Y' AS REVERSE
		,A.FLAG_CF
		, CASE WHEN C.DRCR = 'C'
			THEN 'D'
			ELSE 'C'
			END DRCR
		,C.GLNO
		,A.TRX_AMOUNT AS N_AMOUNT
		,(A.TRX_AMOUNT * NVL(B.RATE_AMOUNT,1) )AS N_AMOUNT_IDR
		,'REV FACILITY' AS SOURCEPROCESS
		,NULL INTMID
		,SYSTIMESTAMP AS CREATEDDATE
		,'JOURNAL FACILITY' AS CREATEDBY
		,A.BRANCH_CODE
		,C.JOURNALCODE    AS JOURNALCODE2
		,C.JOURNAL_DESC
		,NULL AS NOREF
		,C.COSTCENTER
		,C.GL_INTERNAL_CODE
		,NULL METHOD
		,C.COSTCENTER
	FROM IFRS_TRX_FACILITY_HEADER A
	LEFT JOIN IFRS_MASTER_EXCHANGE_RATE B
		ON A.CCY = B.CURRENCY
		  AND A.DOWNLOAD_DATE= B.DOWNLOAD_DATE
	JOIN IFRS_JOURNAL_PARAM C
		ON A.GL_CONSTNAME = C.GL_CONSTNAME
		  AND (A.TRX_CODE = C.TRX_CODE OR C.TRX_CODE = 'ALL')
		  AND (A.CCY = C.CCY OR C.CCY = 'ALL')
		  AND C.JOURNALCODE = 'ITRCGF'
		  AND A.FLAG_CF = C.FLAG_CF
	WHERE A.DOWNLOAD_DATE = V_CURRDATE
	  AND A.STATUS = 'REV'
	  AND A.REVID IS NOT NULL;

	COMMIT;
END;