CREATE OR REPLACE PROCEDURE SP_IFRS_PPR_OS_MONTHLY
AS
    V_CURRDATE DATE;
BEGIN
    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE_LGD;

    MERGE INTO IFRS_PPR_OUTSTANDING D
    USING (
        SELECT
            MIN(DOWNLOAD_DATE) DOWNLOAD_DATE,
            ACCOUNT_NUMBER,
            OUTSTANDING
        FROM IFRS_MASTER_ACCOUNT_MONTHLY
        WHERE ACCOUNT_STATUS='C'
            AND OUTSTANDING=0
            AND BI_COLLECTABILITY IN ('C','3','4','5')
            AND DATA_SOURCE='ILS'
            AND DOWNLOAD_DATE=V_CURRDATE
        GROUP BY ACCOUNT_NUMBER,
                 CUSTOMER_NUMBER,
                 OUTSTANDING
      ) S ON (D.DOWNLOAD_DATE = S.DOWNLOAD_DATE
            AND D.ACCOUNT_NUMBER = S.ACCOUNT_NUMBER )
    WHEN NOT MATCHED THEN
    INSERT (DOWNLOAD_DATE,
            ACCOUNT_NUMBER,
            OUTSTANDING)
    VALUES (S.DOWNLOAD_DATE,
            S.ACCOUNT_NUMBER,
            S.OUTSTANDING);
    COMMIT;

END;