CREATE OR REPLACE PROCEDURE SP_IFRS_VALIDATION_IMA
AS
   V_CURRDATE   DATE;
   V_PREVDATE   DATE;
   V_ECODE      VARCHAR2(10);
   V_ACTIVE     NUMBER;
   V_SESSIONID  VARCHAR2(50);
BEGIN
   BEGIN
      SELECT currdate, prevdate, sessionid
        INTO V_CURRDATE, V_PREVDATE, V_SESSIONID
        FROM IFRS_PRC_DATE;
   END;

  DELETE FROM IFRS_EXCEPTION_DETAILS
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND EXCEPTION_CODE LIKE 'IMA-%';
  COMMIT;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

  /*INSERT IMA INTO GTMP_TABLE*/
  INSERT INTO GTMP_IFRS_MASTER_ACCOUNT(
    PKID,
    DOWNLOAD_DATE,
    MASTERID,
    MASTER_ACCOUNT_CODE,
    DATA_SOURCE,
    GLOBAL_CUSTOMER_NUMBER,
    CUSTOMER_NUMBER,
    CUSTOMER_NAME,
    FACILITY_NUMBER,
    ACCOUNT_NUMBER,
    PREVIOUS_ACCOUNT_NUMBER,
    ACCOUNT_STATUS,
    INTEREST_RATE,
    MARKET_RATE,
    PRODUCT_GROUP,
    PRODUCT_TYPE,
    PRODUCT_CODE,
    PRODUCT_ENTITY,
    GL_CONSTNAME,
    BRANCH_CODE,
    BRANCH_CODE_OPEN,
    CURRENCY,
    EXCHANGE_RATE,
    INITIAL_OUTSTANDING,
    OUTSTANDING,
    OUTSTANDING_IDC,
    OUTSTANDING_JF,
    OUTSTANDING_BANK,
    OUTSTANDING_PASTDUE,
    PLAFOND,
    PLAFOND_CASH,
    INTEREST_ACCRUED,
    INSTALLMENT_AMOUNT,
    UNUSED_AMOUNT,
    DOWN_PAYMENT_AMOUNT,
    JF_FLAG,
    LOAN_START_DATE,
    LOAN_DUE_DATE,
    LOAN_START_AMORTIZATION,
    LOAN_END_AMORTIZATION,
    INSTALLMENT_GRACE_PERIOD,
    NEXT_PAYMENT_DATE,
    NEXT_INT_PAYMENT_DATE,
    LAST_PAYMENT_DATE,
    FIRST_INSTALLMENT_DATE,
    TENOR,
    REMAINING_TENOR,
    PAYMENT_CODE,
    PAYMENT_TERM,
    INTEREST_CALCULATION_CODE,
    INTEREST_PAYMENT_TERM,
    RESTRUCTURE_DATE,
    RESTRUCTURE_FLAG,
    POCI_FLAG,
    STAFF_LOAN_FLAG,
    BELOW_MARKET_FLAG,
    BTB_FLAG,
    COMMITTED_FLAG,
    REVOLVING_FLAG,
    IAS_CLASS,
    IFRS9_CLASS,
    BM_RESULT,
    SPPI_RESULT,
    AMORT_TYPE,
    EIR_STATUS,
    ECF_STATUS,
    EIR,
    EIR_AMOUNT,
    FAIR_VALUE_AMOUNT,
    INITIAL_UNAMORT_TXN_COST,
    INITIAL_UNAMORT_ORG_FEE,
    UNAMORT_COST_AMT,
    UNAMORT_FEE_AMT,
    UNAMORT_BENEFIT,
    DAILY_AMORT_AMT,
    UNAMORT_AMT_TOTAL_JF,
    UNAMORT_FEE_AMT_JF,
    UNAMORT_COST_AMT_JF,
    ORIGINAL_COLLECTABILITY,
    BI_COLLECTABILITY,
    DAY_PAST_DUE,
    DPD_START_DATE,
    DPD_ZERO_COUNTER,
    NPL_DATE,
    NPL_FLAG,
    DEFAULT_DATE,
    DEFAULT_FLAG,
    WRITEOFF_FLAG,
    WRITEOFF_DATE,
    OUTSTANDING_WO,
    IMPAIRED_FLAG,
    IS_IMPAIRED,
    GROUP_SEGMENT,
    SEGMENT,
    SUB_SEGMENT,
    CR_STAGE,
    LIFETIME,
    EAD_RULE_ID,
    EAD_SEGMENT,
    EAD_AMOUNT,
    LGD_RULE_ID,
    LGD_SEGMENT,
    PD_RULE_ID,
    PD_SEGMENT,
    BUCKET_GROUP,
    BUCKET_ID,
    RATING_CODE,
    ECL_12_AMOUNT,
    ECL_LIFETIME_AMOUNT,
    ECL_AMOUNT,
    CA_UNWINDING_AMOUNT,
    IA_UNWINDING_AMOUNT,
    IA_UNWINDING_SUM_AMOUNT,
    BEGINNING_BALANCE,
    ENDING_BALANCE,
    WRITEBACK_AMOUNT,
    CHARGE_AMOUNT,
    RESERVED_VARCHAR_1,
    RESERVED_VARCHAR_2,
    RESERVED_VARCHAR_3,
    RESERVED_VARCHAR_4,
    RESERVED_VARCHAR_5,
    RESERVED_VARCHAR_6,
    RESERVED_VARCHAR_7,
    RESERVED_VARCHAR_8,
    RESERVED_VARCHAR_9,
    RESERVED_VARCHAR_10,
    RESERVED_VARCHAR_11,
    RESERVED_VARCHAR_12,
    RESERVED_VARCHAR_13,
    RESERVED_VARCHAR_14,
    RESERVED_VARCHAR_15,
    RESERVED_VARCHAR_16,
    RESERVED_VARCHAR_17,
    RESERVED_VARCHAR_18,
    RESERVED_VARCHAR_19,
    RESERVED_VARCHAR_20,
    RESERVED_VARCHAR_21,
    RESERVED_VARCHAR_22,
    RESERVED_VARCHAR_23,
    RESERVED_VARCHAR_24,
    RESERVED_VARCHAR_25,
    RESERVED_VARCHAR_26,
    RESERVED_VARCHAR_27,
    RESERVED_VARCHAR_28,
    RESERVED_VARCHAR_29,
    RESERVED_VARCHAR_30,
    RESERVED_AMOUNT_1,
    RESERVED_AMOUNT_2,
    RESERVED_AMOUNT_3,
    RESERVED_AMOUNT_4,
    RESERVED_AMOUNT_5,
    RESERVED_AMOUNT_6,
    RESERVED_AMOUNT_7,
    RESERVED_AMOUNT_8,
    RESERVED_AMOUNT_9,
    RESERVED_AMOUNT_10,
    RESERVED_AMOUNT_11,
    RESERVED_AMOUNT_12,
    RESERVED_AMOUNT_13,
    RESERVED_AMOUNT_14,
    RESERVED_AMOUNT_15,
    RESERVED_AMOUNT_16,
    RESERVED_AMOUNT_17,
    RESERVED_AMOUNT_18,
    RESERVED_AMOUNT_19,
    RESERVED_AMOUNT_20,
    RESERVED_RATE_1,
    RESERVED_RATE_2,
    RESERVED_RATE_3,
    RESERVED_RATE_4,
    RESERVED_RATE_5,
    RESERVED_RATE_6,
    RESERVED_RATE_7,
    RESERVED_RATE_8,
    RESERVED_RATE_9,
    RESERVED_RATE_10,
    RESERVED_FLAG_1,
    RESERVED_FLAG_2,
    RESERVED_FLAG_3,
    RESERVED_FLAG_4,
    RESERVED_FLAG_5,
    RESERVED_FLAG_6,
    RESERVED_FLAG_7,
    RESERVED_FLAG_8,
    RESERVED_FLAG_9,
    RESERVED_FLAG_10,
    RESERVED_DATE_1,
    RESERVED_DATE_2,
    RESERVED_DATE_3,
    RESERVED_DATE_4,
    RESERVED_DATE_5,
    RESERVED_DATE_6,
    RESERVED_DATE_7,
    RESERVED_DATE_8,
    RESERVED_DATE_9,
    RESERVED_DATE_10
  )
  SELECT
        PKID,
        DOWNLOAD_DATE,
        MASTERID,
        MASTER_ACCOUNT_CODE,
        DATA_SOURCE,
        GLOBAL_CUSTOMER_NUMBER,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        PREVIOUS_ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        INTEREST_RATE,
        MARKET_RATE,
        PRODUCT_GROUP,
        PRODUCT_TYPE,
        PRODUCT_CODE,
        PRODUCT_ENTITY,
        GL_CONSTNAME,
        BRANCH_CODE,
        BRANCH_CODE_OPEN,
        CURRENCY,
        EXCHANGE_RATE,
        INITIAL_OUTSTANDING,
        OUTSTANDING,
        OUTSTANDING_IDC,
        OUTSTANDING_JF,
        OUTSTANDING_BANK,
        OUTSTANDING_PASTDUE,
        PLAFOND,
        PLAFOND_CASH,
        INTEREST_ACCRUED,
        INSTALLMENT_AMOUNT,
        UNUSED_AMOUNT,
        DOWN_PAYMENT_AMOUNT,
        JF_FLAG,
        LOAN_START_DATE,
        LOAN_DUE_DATE,
        LOAN_START_AMORTIZATION,
        LOAN_END_AMORTIZATION,
        INSTALLMENT_GRACE_PERIOD,
        NEXT_PAYMENT_DATE,
        NEXT_INT_PAYMENT_DATE,
        LAST_PAYMENT_DATE,
        FIRST_INSTALLMENT_DATE,
        TENOR,
        REMAINING_TENOR,
        PAYMENT_CODE,
        PAYMENT_TERM,
        INTEREST_CALCULATION_CODE,
        INTEREST_PAYMENT_TERM,
        RESTRUCTURE_DATE,
        RESTRUCTURE_FLAG,
        POCI_FLAG,
        STAFF_LOAN_FLAG,
        BELOW_MARKET_FLAG,
        BTB_FLAG,
        COMMITTED_FLAG,
        REVOLVING_FLAG,
        IAS_CLASS,
        IFRS9_CLASS,
        BM_RESULT,
        SPPI_RESULT,
        AMORT_TYPE,
        EIR_STATUS,
        ECF_STATUS,
        EIR,
        EIR_AMOUNT,
        FAIR_VALUE_AMOUNT,
        INITIAL_UNAMORT_TXN_COST,
        INITIAL_UNAMORT_ORG_FEE,
        UNAMORT_COST_AMT,
        UNAMORT_FEE_AMT,
        UNAMORT_BENEFIT,
        DAILY_AMORT_AMT,
        UNAMORT_AMT_TOTAL_JF,
        UNAMORT_FEE_AMT_JF,
        UNAMORT_COST_AMT_JF,
        ORIGINAL_COLLECTABILITY,
        BI_COLLECTABILITY,
        DAY_PAST_DUE,
        DPD_START_DATE,
        DPD_ZERO_COUNTER,
        NPL_DATE,
        NPL_FLAG,
        DEFAULT_DATE,
        DEFAULT_FLAG,
        WRITEOFF_FLAG,
        WRITEOFF_DATE,
        OUTSTANDING_WO,
        IMPAIRED_FLAG,
        IS_IMPAIRED,
        GROUP_SEGMENT,
        SEGMENT,
        SUB_SEGMENT,
        CR_STAGE,
        LIFETIME,
        EAD_RULE_ID,
        EAD_SEGMENT,
        EAD_AMOUNT,
        LGD_RULE_ID,
        LGD_SEGMENT,
        PD_RULE_ID,
        PD_SEGMENT,
        BUCKET_GROUP,
        BUCKET_ID,
        RATING_CODE,
        ECL_12_AMOUNT,
        ECL_LIFETIME_AMOUNT,
        ECL_AMOUNT,
        CA_UNWINDING_AMOUNT,
        IA_UNWINDING_AMOUNT,
        IA_UNWINDING_SUM_AMOUNT,
        BEGINNING_BALANCE,
        ENDING_BALANCE,
        WRITEBACK_AMOUNT,
        CHARGE_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_VARCHAR_6,
        RESERVED_VARCHAR_7,
        RESERVED_VARCHAR_8,
        RESERVED_VARCHAR_9,
        RESERVED_VARCHAR_10,
        RESERVED_VARCHAR_11,
        RESERVED_VARCHAR_12,
        RESERVED_VARCHAR_13,
        RESERVED_VARCHAR_14,
        RESERVED_VARCHAR_15,
        RESERVED_VARCHAR_16,
        RESERVED_VARCHAR_17,
        RESERVED_VARCHAR_18,
        RESERVED_VARCHAR_19,
        RESERVED_VARCHAR_20,
        RESERVED_VARCHAR_21,
        RESERVED_VARCHAR_22,
        RESERVED_VARCHAR_23,
        RESERVED_VARCHAR_24,
        RESERVED_VARCHAR_25,
        RESERVED_VARCHAR_26,
        RESERVED_VARCHAR_27,
        RESERVED_VARCHAR_28,
        RESERVED_VARCHAR_29,
        RESERVED_VARCHAR_30,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_AMOUNT_6,
        RESERVED_AMOUNT_7,
        RESERVED_AMOUNT_8,
        RESERVED_AMOUNT_9,
        RESERVED_AMOUNT_10,
        RESERVED_AMOUNT_11,
        RESERVED_AMOUNT_12,
        RESERVED_AMOUNT_13,
        RESERVED_AMOUNT_14,
        RESERVED_AMOUNT_15,
        RESERVED_AMOUNT_16,
        RESERVED_AMOUNT_17,
        RESERVED_AMOUNT_18,
        RESERVED_AMOUNT_19,
        RESERVED_AMOUNT_20,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_RATE_6,
        RESERVED_RATE_7,
        RESERVED_RATE_8,
        RESERVED_RATE_9,
        RESERVED_RATE_10,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_FLAG_6,
        RESERVED_FLAG_7,
        RESERVED_FLAG_8,
        RESERVED_FLAG_9,
        RESERVED_FLAG_10,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        RESERVED_DATE_6,
        RESERVED_DATE_7,
        RESERVED_DATE_8,
        RESERVED_DATE_9,
        RESERVED_DATE_10
   FROM IFRS_MASTER_ACCOUNT IMA WHERE DOWNLOAD_DATE = V_CURRDATE; --AND ROWNUM <= 1000;

  /*IMA-1001 - Account Number should not be blank*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1001';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                '' AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        WHERE A.ACCOUNT_NUMBER IS NULL;
  END IF;
  COMMIT;

  /*IMA-1002 - Account Number should not be duplicate*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1002';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.ACCOUNT_NUMBER AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        GROUP BY A.ACCOUNT_NUMBER
        HAVING COUNT(A.ACCOUNT_NUMBER) > 1;
  END IF;
  COMMIT;

  /*IMA-1003 - Account Number should not have multiple Customer Number*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1003';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.CUSTOMER_NUMBER AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        GROUP BY A.CUSTOMER_NUMBER, A.ACCOUNT_NUMBER
        HAVING COUNT(A.ACCOUNT_NUMBER) > 1;
  END IF;
  COMMIT;

  /*IMA-1004 - Customer Number should not be blank*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1004';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.CUSTOMER_NUMBER AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        WHERE A.CUSTOMER_NUMBER IS NULL;
   END IF;
   COMMIT;

  /*IMA-1005 - Customer Name should not be blank*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1005';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.CUSTOMER_NUMBER AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        WHERE A.CUSTOMER_NAME IS NULL;
   END IF;
   COMMIT;

  /*IMA-1006 - Account Status should not be blank*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1006';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                '' AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        WHERE A.ACCOUNT_STATUS IS NULL;
  END IF;
  COMMIT;

  /*IMA-1007 - Account Status is invalid*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1007';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.ACCOUNT_STATUS AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      LEFT JOIN TBLM_COMMONCODEDETAIL B
      ON A.ACCOUNT_STATUS = B.VALUE1
      AND B.COMMONCODE = 'B95'
        WHERE B.COMMONCODE IS NULL
        AND A.ACCOUNT_STATUS IS NOT NULL;
   END IF;
   COMMIT;

  /*IMA-1008 - Data Source should not be blank*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1008';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                '' AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
        WHERE A.DATA_SOURCE IS NULL;
  END IF;
  COMMIT;

  /*IMA-1009 - Data Source is not registered. Please register in Commoncode 300*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1009';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.DATA_SOURCE AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      LEFT JOIN TBLM_COMMONCODEDETAIL B
      ON A.DATA_SOURCE = B.VALUE1
      AND B.COMMONCODE = '300'
      WHERE B.VALUE1 IS NULL;
  END IF;
  COMMIT;


  /*IMA-1011 - Product Code is not registered. Please register in Product Parameter.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1011';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                'DATA_SOURCE-PRD_TYPE-PRD_CODE-CCY: ' || A.DATA_SOURCE || '-' || A.PRODUCT_TYPE || '-' || A.PRODUCT_CODE || '-' || A.CURRENCY AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE NOT EXISTS (
            SELECT 1 FROM IFRS_MASTER_PRODUCT_PARAM B
            WHERE (NVL(B.DATA_SOURCE,' ') = NVL(A.DATA_SOURCE, ' ') OR NVL(B.DATA_SOURCE,'ALL') = 'ALL')
            AND (NVL(B.PRD_TYPE, ' ') = NVL(A.PRODUCT_TYPE, ' ')  OR NVL(B.PRD_TYPE,'ALL') = 'ALL')
            AND (NVL(B.PRD_CODE, ' ') = NVL(A.PRODUCT_CODE, ' ')  OR NVL(B.PRD_CODE,'ALL') = 'ALL')
            AND (NVL(B.CCY, ' ') = NVL(A.CURRENCY, ' ') OR NVL(B.CCY,'ALL') = 'ALL')
      );
  END IF;
  COMMIT;


  /*IMA-1012 - Currency should not be blank.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1012';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                ''AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.CURRENCY IS NULL;
  END IF;
  COMMIT;

  /*IMA-1013 - Currency ISO is not recognised.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1013';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.CURRENCY AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      LEFT JOIN IFRS_MASTER_EXCHANGE_RATE B
        ON A.CURRENCY = B.CURRENCY
       AND B.DOWNLOAD_DATE = V_CURRDATE
      WHERE B.CURRENCY IS NULL;
  END IF;
  COMMIT;


  /*IMA-1014 - Exchange rate should not be blank. Insert '1' for Local Currency.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1014';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                '' AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.EXCHANGE_RATE IS NULL;
  END IF;
  COMMIT;


  /*IMA-1015 - Outstanding should be greater or equal to zero.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1015';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.OUTSTANDING AS VARCHAR2(50)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE NVL(A.OUTSTANDING, 0) < 0;
  END IF;
  COMMIT;

  /*IMA-1016 - Plafond should be greater or equal to zero.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1016';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.PLAFOND AS VARCHAR2(50)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE NVL(A.PLAFOND,0) < 0;
  END IF;
  COMMIT;

  /*IMA-1017 - BI Collectability should be between 1- 5.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1017';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.BI_COLLECTABILITY AS VARCHAR2(10)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE CAST(A.BI_COLLECTABILITY AS VARCHAR2(10)) NOT IN ('1', '2', '3', '4', '5');
  END IF;
  COMMIT;

  /*IMA-1018 - Interest Rate should be greater or equal to zero, and typically less than 100%.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1018';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.INTEREST_RATE AS VARCHAR2(50)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.INTEREST_RATE < 0 OR A.INTEREST_RATE > 100;
  END IF;
  COMMIT;


  /*IMA-1019 - Branch Code is not recognised.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1019';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.BRANCH_CODE AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.BRANCH_CODE NOT IN (
            SELECT BRANCH_NUM FROM IFRS_MASTER_BRANCH WHERE DOWNLOAD_DATE = V_CURRDATE
      );
 END IF;
 COMMIT;


  /*IMA-1020 - Due Date should not be earlier than Start Date.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1020';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.LOAN_DUE_DATE AS VARCHAR2(10)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.LOAN_DUE_DATE IS NOT NULL AND A.LOAN_START_DATE IS NOT NULL
      AND A.LOAN_DUE_DATE < A.LOAN_START_DATE;
  END IF;
  COMMIT;

  /*IMA-1021 - Interest Calculation code is not recognised.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1021';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                A.INTEREST_CALCULATION_CODE AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      LEFT JOIN TBLM_COMMONCODEDETAIL B
        ON A.INTEREST_CALCULATION_CODE = B.VALUE1
       AND B.COMMONCODE = 'AP_ICC'
      WHERE A.INTEREST_CALCULATION_CODE IS NOT NULL
      AND B.VALUE1 IS NULL;
  END IF;
  COMMIT;

  /*IMA-1022 - Day Past Due should be greater or equal to zero.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1022';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                CAST(A.DAY_PAST_DUE AS VARCHAR2(10)) AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE NVL(A.DAY_PAST_DUE,0) < 0;
  END IF;
  COMMIT;

  /*IMA-1023 - Asset Classification should be assigned.*/
  V_ACTIVE := 0;
  V_ECODE := 'IMA-1023';
  SELECT IS_ACTIVE INTO V_ACTIVE FROM IFRS_EXCEPTION_CODE WHERE EXCEPTION_CODE = V_ECODE;
  IF V_ACTIVE = 1 THEN
      INSERT INTO IFRS_EXCEPTION_DETAILS
        (SESSION_ID, DOWNLOAD_DATE, UNIQUE_ID, EXCEPTION_CODE, VALUE)
      SELECT    V_SESSIONID,
                V_CURRDATE,
                A.ACCOUNT_NUMBER,
                V_ECODE AS EXCEPTION_CODE,
                'DATA_SOURCE-PRD_TYPE-PRD_CODE-CCY: ' || A.DATA_SOURCE || '-' || A.PRODUCT_TYPE || '-' || A.PRODUCT_CODE || '-' || A.CURRENCY AS VALUE
      FROM GTMP_IFRS_MASTER_ACCOUNT A
      WHERE A.IFRS9_CLASS IS NULL;
  END IF;
  COMMIT;

END;