CREATE OR REPLACE PROCEDURE SP_IFRS_LI_ACCT_EIR_CF_ECF_GRP
AS
-- 20160412 GROUP BY CF_ID FOR MULTIPLE ROWS WITH SAME CF_ID
  V_CURRDATE DATE;
  V_PREVDATE DATE;


BEGIN
	SELECT MAX(CURRDATE)
		, MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
	FROM IFRS_LI_PRC_DATE_AMORT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LI_CF_ECF';

    INSERT INTO TMP_LI_CF_ECF
    (ID1
    ,CF_ID
    ,FLAG_REV_ORI
    ,AMT
    )
	SELECT MIN(A.ID) AS ID1
		,A.CF_ID
		,B.FLAG_REVERSE AS FLAG_REV_ORI
		,SUM(CASE WHEN A.FLAG_REVERSE = 'N' THEN A.AMOUNT ELSE - 1 * A.AMOUNT END) AMT
	FROM IFRS_LI_ACCT_EIR_COST_FEE_ECF A
	JOIN IFRS_LI_ACCT_COST_FEE B ON B.ID = A.CF_ID
		AND B.MASTERID = A.MASTERID
	WHERE A.ECFDATE = V_CURRDATE
        AND A.CREATEDBY <> 'EIR_SWITCH'
        AND A.STATUS ='ACT'
	GROUP BY A.CF_ID
		,B.FLAG_REVERSE
	HAVING COUNT(*) > 1;

    COMMIT;

    MERGE INTO IFRS_LI_ACCT_EIR_COST_FEE_ECF Z
    USING TMP_LI_CF_ECF A
    ON (Z.ECFDATE=V_CURRDATE
        AND Z.CF_ID=A.CF_ID
       )
    WHEN MATCHED THEN
    UPDATE
    SET Z.AMOUNT = CASE WHEN A.FLAG_REV_ORI='N' THEN CASE WHEN A.ID1=Z.ID THEN A.AMT ELSE 0 END
                      ELSE CASE WHEN A.ID1=Z.ID THEN -1 * A.AMT ELSE 0 END
                      END
       ,Z.AMOUNT_ORG =  CASE WHEN A.FLAG_REV_ORI='N' THEN CASE WHEN A.ID1=Z.ID THEN A.AMT ELSE 0 END
                           ELSE CASE WHEN A.ID1=Z.ID THEN -1 * A.AMT ELSE 0 END
                           END
     ,Z.FLAG_REVERSE=A.FLAG_REV_ORI  ;

    COMMIT;

    DELETE FROM IFRS_LI_ACCT_EIR_COST_FEE_ECF
	WHERE ECFDATE = V_CURRDATE
		AND AMOUNT = 0;

    COMMIT;
END;