CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_SEQUENCE_LEO(v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'), v_ECLID NUMBER DEFAULT(0))
AS
    V_SPNAME VARCHAR2(100);
    V_ECLMODELID  NUMBER(18);
    V_CURRDATE  DATE;
BEGIN

    IF v_ECLID = 0 THEN
        SELECT PKID INTO V_ECLMODELID FROM IFRS_ECL_MODEL_HEADER WHERE ACTIVE_FLAG = 1;
    ELSE
        v_ECLMODELID := v_ECLID;
    END IF;

    IF v_DOWNLOADDATE = '1-JAN-1900' THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATE;
    END IF;


-- 	V_SPNAME := 'SP_IFRS_ECL_MODEL_CONFIG('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
--
-- 	V_SPNAME := 'SP_IFRS_ECL_UPDATE_STAGE('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
--
--     V_SPNAME := 'SP_IFRS_ECL_UPDATE_MULTIPLIER('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
--     SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

-- 	V_SPNAME := 'SP_IFRS_EAD_PROCESS ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
--
-- --V_SPNAME := 'SP_IFRS_EAD_PROCESS_MONTHLY ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- --SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
--
-- 	V_SPNAME := 'SP_IFRS_ECL_UPDATE_BUCKET('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

-- 	V_SPNAME := 'SP_IFRS_ECL_RESULT_CALC ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

 --V_SPNAME := 'SP_IFRS_ECL_RESULT_CAL_MONTHLY ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
 --SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

-- 	V_SPNAME := 'SP_IFRS_ECL_GATHER_TBL_STATS';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
--
-- 	V_SPNAME := 'SP_IFRS_ECL_WORSTCASE_CALC ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
-- 	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_IA_CALC ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_ADJUSTMENT_COVID ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_DISASTER_LOAN_CALC ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_SBLC_CALC ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_SPECIAL_REASON ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_EXCLUDE ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_ECL_RESULT_HEADER ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	V_SPNAME := 'SP_IFRS_NOMINATIVE_TO_IMA ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

END;