CREATE OR REPLACE PROCEDURE SP_IFRS_MASTERID_PROD
    AS

    V_CURRDATE DATE;
    V_PREVDATE DATE;

    BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    SELECT PREVDATE INTO V_PREVDATE FROM IFRS_PRC_DATE;

    INSERT  INTO IFRS_UPDATE_LOG ( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'START' ,'SP_IFRS_MASTERID_PROD' ,''); COMMIT;

    INSERT /*+ PARALLEL(8) */ INTO IFRS_MASTERID
                            (
                            PKID,
                            MASTER_ACCOUNT_CODE
                            )
    SELECT /*+ PARALLEL(8) */ 0, ACCOUNT_NUMBER FROM IFRS_MASTER_ACCOUNT
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND ACCOUNT_NUMBER NOT IN (SELECT MASTER_ACCOUNT_CODE FROM IFRS_MASTERID);
    COMMIT;

    UPDATE /*+ PARALLEL(8) */ IFRS_MASTER_ACCOUNT
    SET MASTERID = 0
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    MERGE  INTO IFRS_MASTER_ACCOUNT A
        USING (SELECT PKID,MASTER_ACCOUNT_CODE FROM IFRS_MASTERID) B
        ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.MASTER_ACCOUNT_CODE)
        WHEN MATCHED THEN
        UPDATE
        SET A.MASTERID = B.PKID;
    COMMIT;

    UPDATE /*+ PARALLEL(8) */ IFRS_MASTER_PAYMENT_SETTING
    SET MASTERID = 0
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    MERGE  INTO IFRS_MASTER_PAYMENT_SETTING A
        USING (SELECT PKID,MASTER_ACCOUNT_CODE FROM IFRS_MASTERID) B
        ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.MASTER_ACCOUNT_CODE)
        WHEN MATCHED THEN
        UPDATE
        SET A.MASTERID = B.PKID;
    COMMIT;

    UPDATE /*+ PARALLEL(8) */ IFRS_TRANSACTION_DAILY
    SET MASTERID = 0
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    MERGE /*+ PARALLEL(8) */ INTO IFRS_TRANSACTION_DAILY A
        USING (SELECT PKID,MASTER_ACCOUNT_CODE FROM IFRS_MASTERID) B
        ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.MASTER_ACCOUNT_CODE)
        WHEN MATCHED THEN
        UPDATE
        SET A.MASTERID = B.PKID;
    COMMIT;

    INSERT  INTO IFRS_UPDATE_LOG ( DOWNLOAD_DATE ,DTM ,OPS ,PROCNAME ,REMARK)
    VALUES  ( V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_MASTERID_PROD' ,'');COMMIT;
    END;