CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_RECOVERY_RATE_IMA
AS
    V_CURRDATE DATE;
    V_PREVDATE DATE;
BEGIN

    SELECT  MAX(CURRDATE), MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_LGD ;

    ----GET TEST_SEGMENT_LOSSDATE
    INSERT INTO IFRS_LGD_SEGMENT_LOSSDATE(SEGMENTASI,ACCOUNT_NUMBER,CUSTOMER_NUMBER,LOSS_DATE,OUTSTANDING_FIRST_NPL,BI_COLLECTABILITY)
    SELECT
        C.RESERVED_VARCHAR_2 SEGMENTASI,
        XX.ACCOUNT_NUMBER,XX.CUSTOMER_NUMBER,XX.LOSS_DATE,
        XX.OUTSTANDING_FIRST_NPL,C.BI_COLLECTABILITY
  FROM (
        SELECT
            ACCOUNT_NUMBER,CUSTOMER_NUMBER,MIN(RESERVED_DATE_3) AS LOSS_DATE,MIN(DOWNLOAD_DATE) AS DOWNLOAD_DATE,
            RESERVED_AMOUNT_8 AS OUTSTANDING_FIRST_NPL
        FROM IFRS_MASTER_ACCOUNT
        WHERE ACCOUNT_STATUS='C' AND OUTSTANDING=0 AND BI_COLLECTABILITY IN ('C','3','4','5')
        AND DATA_SOURCE='ILS'
        GROUP BY ACCOUNT_NUMBER,CUSTOMER_NUMBER,RESERVED_AMOUNT_8
    )XX
    INNER JOIN IFRS_MASTER_ACCOUNT C ON XX.DOWNLOAD_DATE=C.DOWNLOAD_DATE AND XX.ACCOUNT_NUMBER=C.ACCOUNT_NUMBER
        AND XX.CUSTOMER_NUMBER=C.CUSTOMER_NUMBER
    WHERE LOSS_DATE IS NOT NULL;
    COMMIT;

    --GET IFRS_RECOV
    INSERT INTO IFRS_LGD_RECOVERY
        (DOWNLOAD_DATE,ACCOUNT_NUMBER,CUSTOMER_NUMBER,CUSTOMER_NAME,ACCOUNT_STATUS,DEAL_TYPE,SEGMENTASI,
         CURRENCY,LOSS_DATE,CLOSED_DATE,TOTAL_LOSS_AMT,OUTSTANDING,OUTSTANDING2,
        DISCOUNT_RATE,RECOVERY_DATE,DAILY_BASIS,RECOVERY_AMOUNT)
    SELECT
         DOWNLOAD_DATE,ACCOUNT_NUMBER,CUSTOMER_NUMBER,CUSTOMER_NAME,ACCOUNT_STATUS,DEAL_TYPE,SEGMENTASI,
         CURRENCY,LOSS_DATE,CLOSED_DATE,TOTAL_LOSS_AMT,OUTSTANDING,OUTSTANDING2,
         DISCOUNT_RATE,RECOV_DATE,
         FN_LGD_DAYS_30_360 (LOSS_DATE,RECOV_DATE)/360 AS DAILY_BASIS,
        (RECOVERY_AMT/POWER((1+DISCOUNT_RATE),FN_LGD_DAYS_30_360 (LOSS_DATE,RECOV_DATE)/360)) RECOVERY_AMT
    FROM (
        SELECT DOWNLOAD_DATE,ACCOUNT_NUMBER,CUSTOMER_NUMBER,CUSTOMER_NAME,ACCOUNT_STATUS,DEAL_TYPE,SEGMENTASI,
            CURRENCY,LOSS_DATE,CLOSED_DATE,TOTAL_LOSS_AMT,OUTSTANDING,OUTSTANDING2,
            DISCOUNT_RATE,
            CASE WHEN (OUTSTANDING2 IS NULL OR OUTSTANDING2=0) AND OUTSTANDING!=0  THEN 0
                WHEN OUTSTANDING2=OUTSTANDING THEN 0
                WHEN OUTSTANDING=0 THEN 0 END RECOVERY_AMT,
            CASE WHEN OUTSTANDING=0 THEN DOWNLOAD_DATE
                WHEN OUTSTANDING2>OUTSTANDING  THEN DOWNLOAD_DATE
            END RECOV_DATE
        FROM (
            SELECT DOWNLOAD_DATE,A.CUSTOMER_NUMBER ,CUSTOMER_NAME,A.ACCOUNT_NUMBER,ACCOUNT_STATUS,INTEREST_RATE AS DISCOUNT_RATE,PRODUCT_CODE AS DEAL_TYPE,
                CURRENCY,OUTSTANDING,OUTSTANDING2,--LAG(OUTSTANDING)OVER (PARTITION BY A.ACCOUNT_NUMBER,A.CUSTOMER_NUMBER ORDER BY  A.DOWNLOAD_DATE) OUTSTANDING2,
                LOAN_DUE_DATE AS CLOSED_DATE,RESERVED_VARCHAR_2 AS SEGMENTASI,LOSS_DATE,OUTSTANDING_FIRST_NPL AS TOTAL_LOSS_AMT
            FROM TMP_IFRS_MASTER_ACCOUNT A
            INNER JOIN IFRS_LGD_SEGMENT_LOSSDATE B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                AND A.CUSTOMER_NUMBER=B.CUSTOMER_NUMBER
                AND A.RESERVED_VARCHAR_2=B.SEGMENTASI
            WHERE
                A.BI_COLLECTABILITY IN ('C','3','4','5')
                AND DOWNLOAD_DATE=V_CURRDATE
            ORDER BY A.ACCOUNT_NUMBER,A.CUSTOMER_NUMBER,DOWNLOAD_DATE
        )AA
    )BB;
    COMMIT;

    ---GET LGD RECOV RATE
    INSERT INTO IFRS_LGD_RECOVERY_RATE
        ( "DATE",DEAL_TYPE,DEAL_ID,CUSTOMER_NR,CUSTOMER_NAME,SEGMENTASI,CURRENCY,LOSS_DATE,CLOSED_DATE,TOTAL_LOSS_AMT,LAST_RECOV_DATE,
        DISCOUNT_RATE,RECOVERY_AMT,RECOV_AMT_BF_NPV,RECOV_PERCENTAGE,LOSS_RATE)
    SELECT MIN(LOSS_DATE) AS "DATE",DEAL_TYPE,ACCOUNT_NUMBER AS DEAL_ID,CUSTOMER_NUMBER,CUSTOMER_NAME,SEGMENTASI,CURRENCY,MIN(LOSS_DATE) LOSS_DATE,
        MAX(RECOVERY_DATE) CLOSED_DATE, TOTAL_LOSS_AMT,
        MAX(RECOVERY_DATE) LAST_RECOV_DATE,DISCOUNT_RATE,
        SUM(RECOVERY_AMOUNT) AS RECOVERY_AMT,
        SUM(RECOVERY_AMOUNT) AS RECOV_AMT_BF_NPV,
        ROUND(SUM(RECOVERY_AMOUNT)/TOTAL_LOSS_AMT,4)*100 AS RECOV_PERCENTAGE,
        100-ROUND(SUM(RECOVERY_AMOUNT)/TOTAL_LOSS_AMT,4)*100 LOSS_RATE
    FROM IFRS_LGD_RECOVERY
    GROUP BY DEAL_TYPE,ACCOUNT_NUMBER,CUSTOMER_NUMBER,CUSTOMER_NAME,SEGMENTASI,CURRENCY,TOTAL_LOSS_AMT,DISCOUNT_RATE;
    COMMIT;

END;