CREATE OR REPLACE PROCEDURE      SP_IFRS_VALIDATION_PROCESS (V_DATE  DATE DEFAULT ('1-JAN-1900'))
AS
V_CURRDATE DATE;
    V_ADJ   NUMBER;
BEGIN

    EXECUTE IMMEDIATE 'alter session enable parallel dml';

    V_CURRDATE:=V_DATE;

    DELETE IFRS.IFRS_CHECK_AUTOMATE_EOM WHERE DOWNLOAD_DATE = V_CURRDATE;COMMIT;

--INISIALISASI VALIDASI BERDASARKAN PARAMTETER YANG TERDAFTAR
    INSERT INTO IFRS.IFRS_CHECK_AUTOMATE_EOM (DOWNLOAD_DATE, NAMA_FILE_VALIDASI, SEQ_OR_JRNLCODE)
    SELECT V_CURRDATE, SEGMENT, SEQUENCE
    FROM IFRS.IFRS_MSTR_SEGMENT_RULES_HEADER
    WHERE SEGMENT_TYPE = 'EOM'
    ORDER BY PKID;
    COMMIT;

-- NEED TO OPEN THIS SCRIPT FOR RERUN PROCESS
--    UPDATE IFRS_CHECK_AUTOMATE_EOM
--    SET AMOUNT_CHECK = NULL, REASON = NULL,SEQ_CHECK = NULL
--    WHERE DOWNLOAD_DATE = V_CURRDATE;
--    COMMIT;

--INISIALISASI PEMBENTUKAN RULES DAN POPULASI VALIDASI NON LBU
        IFRS.SP_IFRS_GENERATE_RULE_SEGMENT('EOM','M');
        IFRS.SP_IFRS_INSERT_VALIDASI();
        IFRS.SP_IFRS_UPDATE_VALIDASI();

        EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS.TMP_VALIDATION_CHECK_SEQ';

--INISIALISASI PEMBENTUKAN RULES PENGECEKAN SEQUENCE BERDASARKAN SEQUENCE DAN JOURNAL CODE
        INSERT INTO IFRS.TMP_VALIDATION_CHECK_SEQ
        SELECT 'VW_IFRS_NOMI_VS_GL_AMT',COUNT(DISTINCT SEQ) FROM IFRS.IFRS_NOMI_VS_GL_AMT WHERE SEQ IN ('301','303','305','307')

        UNION ALL
        SELECT 'VW_IFRS_NOMI_VS_GL_AMT_LBMR', COUNT(DISTINCT JOURNAL_CODE) FROM IFRS.IFRS_NOMI_VS_GL_AMT_LBMR WHERE JOURNAL_CODE IN ('EBCTE','EMPBE','ITEMB')

        UNION ALL
        SELECT 'VW_IFRS_NOMI_VS_GL_ECL', COUNT(DISTINCT SEQ) FROM IFRS.IFRS_NOMI_VS_GL_ECL WHERE SEQ IN ('001','002','003','004','005','006','007','008')

        UNION ALL
        SELECT 'VW_IFRS_NOMI_VS_GL_ECL_UWD', COUNT(DISTINCT JOURNAL_CODE) FROM IFRS.IFRS_NOMI_VS_GL_ECL_UWD WHERE JOURNAL_CODE IN ('BKIUW')

        UNION ALL
        SELECT 'VW_IFRS_NOMI_VS_GL_FS_AMT', COUNT(DISTINCT JOURNAL_CODE) FROM IFRS.IFRS_NOMI_VS_GL_FS_AMT_VLD WHERE JOURNAL_CODE IN ('ACCRU') AND DOWNLOAD_DATE = V_CURRDATE

        UNION ALL
        SELECT 'VW_IFRS_REV_VS_BTK_GL_AMT', COUNT(DISTINCT REV_BLN_INI_SEQ) FROM IFRS.IFRS_REV_VS_BTK_GL_AMT_VLD WHERE REV_BLN_INI_SEQ IN ('202','302','304','306') AND DOWNLOAD_DATE = V_CURRDATE

        UNION ALL
        SELECT 'VW_IFRS_REV_VS_BTK_GL_ECL', COUNT(DISTINCT REV_BLN_INI_SEQ) FROM IFRS.IFRS_REV_VS_BTK_GL_ECL_VLD WHERE REV_BLN_INI_SEQ IN ('102') AND DOWNLOAD_DATE = V_CURRDATE

        UNION ALL
        SELECT 'VW_IFRS_REV_VS_BTK_GL_FS_AMT', COUNT(DISTINCT REV_BLN_INI_SEQ) FROM IFRS.IFRS_REV_VS_BTK_GL_FS_AMT_VLD WHERE REV_BLN_INI_SEQ IN ('309') AND DOWNLOAD_DATE = V_CURRDATE

        UNION ALL
        SELECT 'VW_IFRS_VLD_VS_GL_AMT', COUNT(DISTINCT SEQ) FROM IFRS.IFRS_VLD_VS_GL_AMT_VLD WHERE SEQ IN ('201','301','303','305') AND DOWNLOAD_DATE = V_CURRDATE

        UNION ALL
        SELECT 'VW_IFRS_VLD_VS_GL_ECL', COUNT(DISTINCT SEQ) FROM IFRS.IFRS_VLD_VS_GL_ECL_VLD WHERE SEQ IN ('001','002','003','004','005','006','007','008','101') AND DOWNLOAD_DATE = V_CURRDATE;

    COMMIT;

--UPDATE SEQUENCE CONDITION BASED ON IFRS.TMP_VALIDATION_CHECK
    MERGE INTO IFRS.IFRS_CHECK_AUTOMATE_EOM A
    USING (SELECT *
           FROM IFRS.TMP_VALIDATION_CHECK_SEQ) B
    ON (A.NAMA_FILE_VALIDASI = B.NAMA_FILE_VALIDASI)
    WHEN MATCHED THEN
        UPDATE
        SET A.SEQ_OR_JRNLCODE_CHECK = CASE WHEN A.SEQ_OR_JRNLCODE = B.SEQ THEN 'OKAY' ELSE 'NOT OKAY' END,
            A.AMOUNT_CHECK          = CASE WHEN AMOUNT_CHECK IS NULL THEN 'OKAY' ELSE AMOUNT_CHECK END
        WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

-- SPECIAL CASE UPDATE FOR VW_IFRS_VLD_VS_GL_AMT (NEED TO UPDATE REASON FOR SELISIH UNDER 500JT)
    MERGE INTO IFRS.IFRS_CHECK_AUTOMATE_EOM A
        USING (
                SELECT DOWNLOAD_DATE,SEQ, 'SELISIH_AMT_VA UNTUK SEQUENCE 307 SEBESAR ' || SUM(SELISIH_AMT_VA) REASON1, SUM(SELISIH_AMT_VA) SELISIH FROM IFRS.IFRS_VLD_VS_GL_AMT_VLD a
                    WHERE SEQ = 307 AND DOWNLOAD_DATE = V_CURRDATE
                    GROUP BY DOWNLOAD_DATE,SEQ)B
                ON (A.DOWNLOAD_DATE = B.DOWNLOAD_DATE AND A.NAMA_FILE_VALIDASI = 'VW_IFRS_VLD_VS_GL_AMT')
                WHEN MATCHED THEN UPDATE
                SET A.AMOUNT_CHECK = CASE WHEN SELISIH > 500000000 THEN 'NOT OKAY' ELSE AMOUNT_CHECK END,
                    A.REASON = CASE WHEN SELISIH = 0 THEN NULL WHEN SELISIH < 500000000 THEN B.REASON1  ELSE REASON END;
    COMMIT;

    -- LEO - SPECIAL CASE : sequence reverse all dan bentuk all keduanya dibandingin saja

    select count(1) into V_ADJ
    from (select distinct effdt from IFRS.IFRS_GL_OUTBOUND_ALL_R where EFFDT=(SELECT CURRDATE - TO_DATE ('1900-01-01', 'YYYY-MM-DD') + 1
      FROM IFRS.IFRS_PRC_DATE)) a join (select distinct effdt from IFRS.IFRS_GL_OUTBOUND_ALL where EFFDT=(SELECT CURRDATE - TO_DATE ('1900-01-01', 'YYYY-MM-DD') + 1
      FROM IFRS.IFRS_PRC_DATE)) b
    on 1=1;

    IF V_ADJ = 1 then

        MERGE INTO IFRS.IFRS_CHECK_AUTOMATE_EOM A
        USING (select 'VW_IFRS_REV_VS_BTK_GL_ADJ',
                      DOWNLOAD_DATE,
                      COUNT_REV_SEQ                                                           SEQ_OR_JRNLCODE,
                      case when COUNT_REV_SEQ = COUNT_BTK_SEQ then 'OKAY' else 'NOT OKAY' end SEQ_OR_JRNLCODE_CHECK
               from (select DOWNLOAD_DATE,
                            count(distinct REV_BLN_INI_ADJ_SEQ) COUNT_REV_SEQ,
                            count(distinct BTK_BLN_INI_SEQ)     COUNT_BTK_SEQ
                     from IFRS.IFRS_REV_VS_BTK_GL_ADJ
                     where DOWNLOAD_DATE = V_CURRDATE
                     group by DOWNLOAD_DATE)) B
        ON (A.DOWNLOAD_DATE = B.DOWNLOAD_DATE AND A.NAMA_FILE_VALIDASI = 'VW_IFRS_REV_VS_BTK_GL_ADJ')
        WHEN MATCHED THEN
            UPDATE
            SET A.SEQ_OR_JRNLCODE=B.SEQ_OR_JRNLCODE,
                A.SEQ_OR_JRNLCODE_CHECK=B.SEQ_OR_JRNLCODE_CHECK,
                A.AMOUNT_CHECK = CASE WHEN AMOUNT_CHECK IS NULL THEN 'OKAY' ELSE AMOUNT_CHECK END;
        commit;
    else
        delete from IFRS.IFRS_CHECK_AUTOMATE_EOM
        where DOWNLOAD_DATE=(select currdate from IFRS.IFRS_PRC_DATE) and
              NAMA_FILE_VALIDASI='VW_IFRS_REV_VS_BTK_GL_ADJ';
        commit;
    end if;
    -- END LEO

/*-------------------------------------------------------------------------------------------------------------
                                            LBU
-----------------------------------------------------------------------------------------------------------*/
        EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS.IFRS_NOMI_VS_LBU_VLD';

        DELETE IFRS.IFRS_CHECK_AUTOMATE_EOM_LBU WHERE DOWNLOAD_DATE = V_CURRDATE;COMMIT;

        INSERT INTO IFRS.IFRS_NOMI_VS_LBU_VLD
        SELECT * FROM VW_IFRS_NOMI_VS_LBU;
        COMMIT;


-- VALIDASI LBU
        INSERT INTO IFRS.IFRS_CHECK_AUTOMATE_EOM_LBU
            (DOWNLOAD_DATE, TOTAL_UNAMORT_FEE_AMT_CCY, TOTAL_UNAMORT_FEE_AMT_LCL, TOTAL_UNWINDING_INTEREST_CCY,
             TOTAL_UNWINDING_INTEREST_LCL, TOTAL_AMORT_FEE_CCY, TOTAL_AMORT_FEE_LCL, TOTAL_ECL_ON_BS_FINAL_CCY,
             TOTAL_ECL_ON_BS_FINAL_LCL, TOTAL_ECL_OFF_BS_CCY, TOTAL_ECL_OFF_BS_LCL)
        SELECT
            V_CURRDATE,
            CASE WHEN a.TOTAL_UNAMORT_FEE_AMT_CCY - b.TOTAL_UNAMORT_FEE_AMT_CCY       BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_UNAMORT_FEE_AMT_CCY - b.TOTAL_UNAMORT_FEE_AMT_CCY,'99999999999999.99999')       END TOTAL_UNAMORT_FEE_AMT_CCY   ,
            CASE WHEN a.TOTAL_UNAMORT_FEE_AMT_LCL - b.TOTAL_UNAMORT_FEE_AMT_LCL       BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_UNAMORT_FEE_AMT_LCL - b.TOTAL_UNAMORT_FEE_AMT_LCL,'99999999999999.99999')       END TOTAL_UNAMORT_FEE_AMT_LCL   ,
            CASE WHEN a.TOTAL_UNWINDING_INTEREST_CCY - b.TOTAL_UNWINDING_INTEREST_CCY BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_UNWINDING_INTEREST_CCY - b.TOTAL_UNWINDING_INTEREST_CCY,'99999999999999.99999') END TOTAL_UNWINDING_INTEREST_CCY,
            CASE WHEN a.TOTAL_UNWINDING_INTEREST_LCL - b.TOTAL_UNWINDING_INTEREST_LCL BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_UNWINDING_INTEREST_LCL - b.TOTAL_UNWINDING_INTEREST_LCL,'99999999999999.99999') END TOTAL_UNWINDING_INTEREST_LCL,
            CASE WHEN a.TOTAL_AMORT_FEE_CCY - b.TOTAL_AMORT_FEE_CCY                   BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_AMORT_FEE_CCY - b.TOTAL_AMORT_FEE_CCY,'99999999999999.99999')                   END TOTAL_AMORT_FEE_CCY         ,
            CASE WHEN a.TOTAL_AMORT_FEE_LCL - b.TOTAL_AMORT_FEE_LCL                   BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_AMORT_FEE_LCL - b.TOTAL_AMORT_FEE_LCL,'99999999999999.99999')                   END TOTAL_AMORT_FEE_LCL         ,
            CASE WHEN a.TOTAL_ECL_ON_BS_FINAL_CCY - b.TOTAL_ECL_ON_BS_FINAL_CCY       BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_ECL_ON_BS_FINAL_CCY - b.TOTAL_ECL_ON_BS_FINAL_CCY,'99999999999999.99999')       END TOTAL_ECL_ON_BS_FINAL_CCY   ,
            CASE WHEN a.TOTAL_ECL_ON_BS_FINAL_LCL - b.TOTAL_ECL_ON_BS_FINAL_LCL       BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_ECL_ON_BS_FINAL_LCL - b.TOTAL_ECL_ON_BS_FINAL_LCL,'99999999999999.99999')       END TOTAL_ECL_ON_BS_FINAL_LCL   ,
            CASE WHEN a.TOTAL_ECL_OFF_BS_CCY - b.TOTAL_ECL_OFF_BS_CCY                 BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_ECL_OFF_BS_CCY - b.TOTAL_ECL_OFF_BS_CCY,'99999999999999.99999')                 END TOTAL_ECL_OFF_BS_CCY        ,
            CASE WHEN a.TOTAL_ECL_OFF_BS_LCL - b.TOTAL_ECL_OFF_BS_LCL                 BETWEEN -1000 AND 1000 THEN 'AMOUNT CORRECT' ELSE 'ERROR - AMOUNT = ' || TO_CHAR(a.TOTAL_ECL_OFF_BS_LCL - b.TOTAL_ECL_OFF_BS_LCL,'99999999999999.99999')                 END TOTAL_ECL_OFF_BS_LCL
        FROM IFRS.IFRS_NOMI_VS_LBU_VLD a JOIN IFRS.IFRS_NOMI_VS_LBU_VLD B
        ON A.SOURCE = 'Nominatif' and B.Source = 'Textfile LBU';

        COMMIT;

END;