CREATE OR REPLACE PROCEDURE SP_IFRS_CEF
    AS
        V_CURRDATE DATE;
        V_PREVDATE DATE;

    BEGIN
            FOR LOOP_COUNTER IN 1..96
        LOOP
            SELECT CURRDATE INTO V_CURRDATE FROM IFRS_DATE_DAY1;
            SELECT ADD_MONTHS(CURRDATE,-1) INTO V_PREVDATE FROM IFRS_DATE_DAY1;

    DELETE IFRS_CEF_PROCESS WHERE DOWNLOAD_DATE >= V_CURRDATE;
    DELETE IFRS_CEF_UNPROCESS WHERE DOWNLOAD_DATE >= V_CURRDATE;
    COMMIT;

    INSERT INTO GTMP_IFRS_MASTER_ACCOUNT SELECT * FROM IFRS_MASTER_ACCOUNT_MONTHLY WHERE DATA_SOURCE = 'BTRD' AND DOWNLOAD_DATE IN (V_CURRDATE,V_PREVDATE);COMMIT;

    INSERT INTO IFRS_CEF_PROCESS
    (
        DOWNLOAD_DATE,
        CURRENT_DATE,
        PREVIOUS_DATE,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        SEGMENTATION_ID,
        AMOUNT_OFF_BS_CURR,
        AMOUNT_OFF_BS_PREV,
        AMOUNT_ON_BS_CURR,
        AMOUNT_ON_BS_PREV,
        SELISIH_ON_BS,
        CEF_RATE,
        BS_FLAG,
        SEGMENT,
        DATA_SOURCE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST
    )
    SELECT DISTINCT
        LAST_DAY(DOWNLOAD_DATE),
        LAST_DAY(DOWNLOAD_DATE),
        ADD_MONTHS(LAST_DAY(DOWNLOAD_DATE),-1),
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        '0' SEGMENTATION_ID,
        OUTSTANDING,
        0 OUTSTANDINGOFFPREV,
        0 OUTSTANDINGONCURR,
        0 OUTSTANDINGONPREV,
        0 SELISIHONBS,
        0 CEFRATE,
        RESERVED_FLAG_1,
        SEGMENT,
        DATA_SOURCE,
        'ADMIN',
        SYSDATE,
        'HOST'
    FROM (SELECT DISTINCT DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7)ACCOUNT_NUMBER,CUSTOMER_NUMBER, MAX(CUSTOMER_NAME)CUSTOMER_NAME, ACCOUNT_STATUS, SUM(OUTSTANDING)OUTSTANDING, RESERVED_FLAG_1, SEGMENT, DATA_SOURCE
                FROM GTMP_IFRS_MASTER_ACCOUNT WHERE DOWNLOAD_DATE = V_CURRDATE AND RESERVED_FLAG_1 = 0 AND ACCOUNT_STATUS = 'A' AND DATA_SOURCE = 'BTRD'
                GROUP BY DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7), CUSTOMER_NUMBER, ACCOUNT_STATUS,RESERVED_FLAG_1,SEGMENT, DATA_SOURCE) A;
                COMMIT;

    INSERT INTO IFRS_CEF_PROCESS
    (
        DOWNLOAD_DATE,
        CURRENT_DATE,
        PREVIOUS_DATE,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        SEGMENTATION_ID,
        AMOUNT_OFF_BS_CURR,
        AMOUNT_OFF_BS_PREV,
        AMOUNT_ON_BS_CURR,
        AMOUNT_ON_BS_PREV,
        SELISIH_ON_BS,
        CEF_RATE,
        BS_FLAG,
        SEGMENT,
        DATA_SOURCE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST
    )
    SELECT DISTINCT
        LAST_DAY(DOWNLOAD_DATE),
        LAST_DAY(DOWNLOAD_DATE),
        ADD_MONTHS(LAST_DAY(DOWNLOAD_DATE),-1),
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        '0' SEGMENTATION_ID,
        0 OUTSTANDINGOFFCUR,
        0 OUTSTANDINGOFFPREV,
        OUTSTANDING,
        0 OUTSTANDINGONPREV,
        0 SELISIHONBS,
        0 CEFRATE,
        RESERVED_FLAG_1,
        SEGMENT,
        DATA_SOURCE,
        'ADMIN',
        SYSDATE,
        'HOST'
    FROM (SELECT DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7)ACCOUNT_NUMBER, CUSTOMER_NUMBER, MAX(CUSTOMER_NAME)CUSTOMER_NAME, ACCOUNT_STATUS, SUM(OUTSTANDING)OUTSTANDING, RESERVED_FLAG_1 ,SEGMENT, DATA_SOURCE
                FROM GTMP_IFRS_MASTER_ACCOUNT WHERE LAST_DAY(DOWNLOAD_DATE) = V_CURRDATE AND RESERVED_FLAG_1 = 1 AND ACCOUNT_STATUS = 'A' AND DATA_SOURCE = 'BTRD'
                GROUP BY DOWNLOAD_DATE, SUBSTR(ACCOUNT_NUMBER,1,7), CUSTOMER_NUMBER, ACCOUNT_STATUS,RESERVED_FLAG_1,SEGMENT, DATA_SOURCE) A;
                COMMIT;


    MERGE INTO IFRS_CEF_PROCESS A
    USING (SELECT DOWNLOAD_DATE, ACCOUNT_NUMBER, AMOUNT_OFF_BS_CURR, AMOUNT_OFF_BS_PREV, AMOUNT_ON_BS_CURR, AMOUNT_ON_BS_PREV FROM IFRS_CEF_PROCESS
            WHERE DOWNLOAD_DATE = V_CURRDATE AND BS_FLAG = '1') B
            ON (A.BS_FLAG = '0' AND A.DOWNLOAD_DATE = V_CURRDATE AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
       WHEN MATCHED THEN UPDATE
       SET A.AMOUNT_ON_BS_CURR = B.AMOUNT_ON_BS_CURR;
       COMMIT;


        MERGE INTO IFRS_CEF_PROCESS A
        USING (SELECT DOWNLOAD_DATE, ACCOUNT_NUMBER, AMOUNT_OFF_BS_CURR, AMOUNT_OFF_BS_PREV, AMOUNT_ON_BS_CURR, AMOUNT_ON_BS_PREV FROM IFRS_CEF_PROCESS
                    WHERE DOWNLOAD_DATE = V_PREVDATE) B
                    ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
               WHEN MATCHED THEN UPDATE
               SET A.AMOUNT_ON_BS_PREV = B.AMOUNT_ON_BS_CURR,
                   A.AMOUNT_OFF_BS_PREV = B.AMOUNT_OFF_BS_CURR;
                   COMMIT;

       /* MERGE INTO IFRS_CEF_PROCESS A
        USING (SELECT DOWNLOAD_DATE, ACCOUNT_NUMBER, AMOUNT_OFF_BS_CURR, AMOUNT_OFF_BS_PREV, AMOUNT_ON_BS_CURR, AMOUNT_ON_BS_PREV FROM IFRS_CEF_UNPROCESS
                    WHERE DOWNLOAD_DATE = V_PREVDATE) B
                    ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER)
               WHEN MATCHED THEN UPDATE
               SET A.AMOUNT_ON_BS_PREV = B.AMOUNT_ON_BS_CURR,
                   A.AMOUNT_OFF_BS_PREV = B.AMOUNT_OFF_BS_CURR;
                   COMMIT;*/

        UPDATE IFRS_CEF_PROCESS
            SET SELISIH_ON_BS = CASE WHEN AMOUNT_ON_BS_CURR - AMOUNT_ON_BS_PREV < 0 THEN 0 ELSE AMOUNT_ON_BS_CURR - AMOUNT_ON_BS_PREV END
            WHERE DOWNLOAD_DATE = V_CURRDATE;COMMIT;

    COMMIT;

       DELETE(select a.download_date, a.current_date,a.previous_date, a.customer_number, a.account_number, a.account_status,
                a.segmentation_id, a.AMOUNT_off_bs_curr, a.AMOUNT_off_bs_prev, a.AMOUNT_on_bs_curr, a.AMOUNT_on_bs_prev,
                a.selisih_on_bs, cef_rate, BS_FLAG from ifrs_cef_process a join (
       select download_date, account_number from IFRS_CEF_PROCESS
       where download_date = V_CURRDATE --and ACCOUNT_NUMBER = 'V009913' --and (AMOUNT_ON_BS_CURR = 0 OR AMOUNT_OFF_BS_CURR = 0) AND AMOUNT_ON_BS_PREV = 0
       group by download_date, account_number
       having count(account_number)>1
       )b
       on a.download_date = b.download_date and a.account_number = b.account_number
       where (AMOUNT_ON_BS_CURR = 0 OR AMOUNT_OFF_BS_CURR = 0)
       )
       ;COMMIT;

    INSERT INTO IFRS_CEF_UNPROCESS
        SELECT * FROM IFRS_CEF_PROCESS
        WHERE (AMOUNT_OFF_BS_CURR = 0 OR AMOUNT_ON_BS_CURR = 0)
        AND DOWNLOAD_dATE = V_CURRDATE;

    DELETE IFRS_CEF_PROCESS
        WHERE (AMOUNT_OFF_BS_CURR = 0 --OR AMOUNT_ON_BS_CURR = 0
        )
        AND DOWNLOAD_dATE = V_CURRDATE;
        COMMIT;

       /*DELETE IFRS_CEF_PROCESS
       WHERE AMOUNT_OFF_BS_CURR = 0
       AND DOWNLOAD_dATE = V_CURRDATE;
       COMMIT;*/

        UPDATE IFRS_CEF_PROCESS
            SET CEF_RATE = CASE WHEN SELISIH_ON_BS / AMOUNT_OFF_BS_PREV > 1 THEN 1 ELSE SELISIH_ON_BS / AMOUNT_OFF_BS_PREV END
            WHERE DOWNLOAD_DATE = V_CURRDATE AND AMOUNT_OFF_BS_PREV <> 0;COMMIT;


    UPDATE IFRS_DATE_DAY1
    SET PREVDATE = ADD_MONTHS(PREVDATE,1),
        CURRDATE = ADD_MONTHS(CURRDATE,1);
    COMMIT;

    END LOOP;
    END;