CREATE OR REPLACE PROCEDURE SP_IFRS_PPR_SEQUENCE
AS
BEGIN
    /*
    SP_IFRS_PPR_IMA_MONTHLY;

    SP_IFRS_PPR_PAYM_SCHD_ALL;

    SP_IFRS_PPR_BI_COLLECTABILITY;

    SP_IFRS_PPR_MSTR_EXCHANGE_RATE;

    SP_IFRS_PPR_TRANSACTION_DAILY;

    SP_IFRS_PPR_CONVERT_AMOUNT;

    SP_IFRS_PPR_OS_MONTHLY;
    */


    --SP_IFRS_PPR_DETAILS_BCA;
    --SP_IFRS_PPR_HEADER_BCA;
    /*
    SP_IFRS_PPR_PROCESS;
    SP_IFRS_PPR_DETAILS;
    SP_IFRS_PPR_HEADER;
    */
     SP_IFRS_PPR_PROCESS_3;
    SP_IFRS_PPR_DETAILS_3;
    SP_IFRS_PPR_HEADER_3;
END;