CREATE OR REPLACE PROCEDURE SP_IFRS_PPR_CONVERT_AMOUNT
AS
    V_CURRDATE DATE;
BEGIN
   SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE_LGD;

    /*
    6. CONVERT ALL AMOUNT FROM POIN 1  TO IDR, E.G: OS * EXCHANGE_RATE --> TO IDR
    */

    MERGE INTO IFRS_PPR_IMA_MONTHLY D
    USING (
            SELECT
                A.DOWNLOAD_DATE,
                A.ACCOUNT_NUMBER,
                A.OUTSTANDING,
                (A.OUTSTANDING*B.RATE_AMOUNT) IDR_OUTSTANDING
            FROM IFRS_PPR_IMA_MONTHLY A
                INNER JOIN IFRS_PPR_MASTER_EXCHANGE_RATE B ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
                    AND A.CURRENCY = B.CURRENCY
            WHERE A.DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
           ) S ON (D.DOWNLOAD_DATE = S.DOWNLOAD_DATE
                   AND D.ACCOUNT_NUMBER = S.ACCOUNT_NUMBER)
    WHEN MATCHED THEN
    UPDATE SET
        IDR_OUTSTANDING     = S.IDR_OUTSTANDING,
        UPDATEDDATE         = SYSDATE;
    COMMIT;

    MERGE INTO IFRS_PPR_PAYM_SCHD_ALL D
    USING (
            SELECT
                A.DOWNLOAD_DATE,
                A.MASTERID,
                A.PMT_DATE,
                A.OSPRN,
                A.PRINCIPAL,
                (A.OSPRN*C.RATE_AMOUNT) IDR_OSPRN,
                (A.PRINCIPAL*C.RATE_AMOUNT) IDR_PRINCIPAL,
                A.ICC
            FROM IFRS_PPR_PAYM_SCHD_ALL A
                INNER JOIN IFRS_PPR_IMA_MONTHLY B ON A.PMT_DATE = B.DOWNLOAD_DATE
                    AND A.MASTERID = B.MASTERID
                INNER JOIN IFRS_PPR_MASTER_EXCHANGE_RATE C ON B.DOWNLOAD_DATE = C.DOWNLOAD_DATE
                    AND B.CURRENCY = C.CURRENCY
            WHERE A.PMT_DATE=LAST_DAY(V_CURRDATE)
          ) S ON (D.DOWNLOAD_DATE   =   S.DOWNLOAD_DATE
                  AND D.PMT_DATE    =   S.PMT_DATE
                  AND D.MASTERID    =   S.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        IDR_OSPRN       =   S.IDR_OSPRN,
        IDR_PRINCIPAL   =   S.IDR_PRINCIPAL,
        UPDATEDDATE     =   SYSDATE;
    COMMIT;

    MERGE INTO IFRS_PPR_TRANSACTION_DAILY D
    USING (
            SELECT
                A.DOWNLOAD_DATE,
                A.EFFECTIVE_DATE,
                A.MASTERID,
                A.ACCOUNT_NUMBER,
                A.ORG_CCY_AMT*B.RATE_AMOUNT IDR_ORG_CCY_AMT,
                A.EQV_LCY_AMT*B.RATE_AMOUNT IDR_EQV_LCY_AMT
            FROM IFRS_PPR_TRANSACTION_DAILY A
            LEFT JOIN IFRS_PPR_MASTER_EXCHANGE_RATE B ON A.EFFECTIVE_DATE = B.DOWNLOAD_DATE
                AND A.CCY=B.CURRENCY
            WHERE A.EFFECTIVE_DATE	= LAST_DAY(V_CURRDATE)
           ) S ON (D.EFFECTIVE_DATE = S.EFFECTIVE_DATE AND D.DOWNLOAD_DATE=S.DOWNLOAD_DATE
                   AND D.MASTERID = S.MASTERID
                   AND D.ACCOUNT_NUMBER = S.ACCOUNT_NUMBER)
    WHEN MATCHED  THEN
    UPDATE SET
        IDR_ORG_CCY_AMT     =   S.IDR_ORG_CCY_AMT,
        IDR_EQV_LCY_AMT     =   S.IDR_EQV_LCY_AMT,
        UPDATEDDATE         =   SYSDATE;
    COMMIT;


END;