CREATE OR REPLACE PROCEDURE SP_IFRS_LI_ACCT_SL_ECF_MAIN
AS
  V_CURRDATE	DATE;
  V_PREVDATE	DATE;
  V_NUM NUMBER(10);
  V_PARAM_DISABLE_ACCRU_PREV NUMBER(10);
  V_PARAM_CALC_TO_LASTPAYMENT NUMBER(10);
  V_LOOPS INT;

BEGIN

    SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_LI_PRC_DATE_AMORT;


    --disable aCCru prev Create on new eCF and return aCCrual to unamort
    V_PARAM_DISABLE_ACCRU_PREV := 0;

    -- eCF First paYment date = last paYment date iF 1 else Currdate
    V_PARAM_CALC_TO_LASTPAYMENT := 0;

    INSERT INTO IFRS_LI_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LI_ACCT_SL_ECF_MAIN','');
    COMMIT;

    --reset aCCru Caused bY new eCF
    DELETE FROM IFRS_LI_ACCT_SL_ACCRU_PREV
    WHERE DOWNLOAD_DATE >= V_CURRDATE
    AND SRCPROCESS = 'ECF';
    COMMIT;

    --reset data beFore proCessing
    UPDATE IFRS_LI_ACCT_COST_FEE
    SET STATUS = 'ACT'
    WHERE STATUS = 'PNL'
    AND CREATEDBY = 'SLECF1'
    AND DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    UPDATE IFRS_LI_ACCT_SL_COST_FEE_PREV
    SET STATUS = 'ACT'
    WHERE STATUS = 'PNL'
    AND CREATEDBY = 'SLECF2'
    AND DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    UPDATE IFRS_LI_ACCT_SL_COST_FEE_PREV
    SET STATUS = 'ACT'
    WHERE STATUS = 'PNL2'
    AND CREATEDBY = 'SLECF2'
    AND DOWNLOAD_DATE = V_PREVDATE;
    COMMIT;

    EXECUTE IMMEDIATE 'trunCate table TMP_LI_T1';

    INSERT INTO TMP_LI_T1 (MASTERID)
    SELECT MASTERID
    FROM IFRS_LI_IMA_AMORT_CURR
    WHERE ECF_STATUS = 'Y';
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LI_ACCT_SL_CF_ECF';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_LI_ACCT_STOP_REV';
    COMMIT;

    --20160721 get data From eir stop rev
    INSERT INTO TMP_IFRS_LI_ACCT_STOP_REV(MASTERID)
    SELECT A.MASTERID
    FROM (SELECT MASTERID FROM IFRS_LI_ACCT_EIR_STOP_REV WHERE DOWNLOAD_DATE=V_CURRDATE
          UNION
          SELECT MASTERID FROM IFRS_LI_ACCT_SL_STOP_REV WHERE DOWNLOAD_DATE=V_CURRDATE
         ) A;
    COMMIT;
    --20180109 aCCt with reversal todaY
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LI_TODAYREV';
    COMMIT;
    INSERT INTO TMP_LI_TODAYREV(MASTERID)
    SELECT MASTERID
    FROM IFRS_LI_ACCT_COST_FEE
    WHERE DOWNLOAD_DATE=V_CURRDATE
    AND FLAG_REVERSE='Y'
    AND CF_ID_REV IS NOT NULL;

    COMMIT;
    -- todaY new Cost Fee
    INSERT INTO IFRS_LI_ACCT_SL_CF_ECF (
    MASTERID,
    FEE_AMT,
    COST_AMT,
    FEE_AMT_ACRU,
    COST_AMT_ACRU
    )
    SELECT A.MASTERID,
           SUM (COALESCE (CASE WHEN C.FLAG_CF = 'F' THEN CASE WHEN C.FLAG_REVERSE = 'Y' THEN -1 * C.AMOUNT ELSE C.AMOUNT END
                               ELSE 0
                          END,0)),
           SUM (COALESCE (CASE WHEN C.FLAG_CF = 'C' THEN CASE WHEN C.FLAG_REVERSE = 'Y' THEN -1 * C.AMOUNT ELSE C.AMOUNT END
                               ELSE 0
                          END,0)),
           0,
           0
    FROM    TMP_LI_T1 A
    LEFT JOIN IFRS_LI_ACCT_COST_FEE C
    ON     C.DOWNLOAD_DATE = V_CURRDATE
    AND C.MASTERID = A.MASTERID
    AND C.STATUS = 'ACT'
    AND C.METHOD = 'SL'
    --20180108 exClude CF reversal and its pair
    AND C.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        UNION ALL
                        SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        )
    GROUP BY A.MASTERID;

    COMMIT;

    -- sisa unamort
    MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
    USING ( SELECT B.MASTERID,
                          SUM (COALESCE (CASE WHEN B.FLAG_CF = 'F' THEN CASE WHEN B.FLAG_REVERSE = 'Y' THEN -1 * CASE WHEN CFREV.MASTERID IS NULL THEN B.AMOUNT ELSE B.AMOUNT_ORG END
                                                                             ELSE CASE WHEN CFREV.MASTERID IS NULL THEN B.AMOUNT ELSE B.AMOUNT_ORG END
                                                                        END
                                              ELSE 0
                                         END,0)) AS FEE_AMT,
                          SUM (COALESCE (CASE WHEN B.FLAG_CF = 'C' THEN CASE WHEN B.FLAG_REVERSE = 'Y' THEN -1 * CASE WHEN CFREV.MASTERID IS NULL THEN B.AMOUNT ELSE B.AMOUNT_ORG END
                                                                             ELSE CASE WHEN CFREV.MASTERID IS NULL THEN B.AMOUNT ELSE B.AMOUNT_ORG END
                                                                        END
                                              ELSE 0
                                         END,0))AS COST_AMT
                    FROM    IFRS_LI_ACCT_SL_COST_FEE_PREV B
                    JOIN VW_LI_LAST_SL_CF_PREV X
                      ON     X.MASTERID = B.MASTERID
                      AND X.DOWNLOAD_DATE = B.DOWNLOAD_DATE
                      AND B.SEQ = X.SEQ
                    LEFT JOIN TMP_IFRS_LI_ACCT_STOP_REV REV
                      ON B.MASTERID = REV.MASTERID
                    --20180109 resona req
                    LEFT JOIN TMP_LI_TODAYREV CFREV
                      ON CFREV.MASTERID=B.MASTERID
                    WHERE B.DOWNLOAD_DATE IN (V_CURRDATE, V_PREVDATE)
                    AND B.STATUS = 'ACT'
                    AND REV.MASTERID IS NULL
                    --20180108 exClude CF reversal and its pair
                    AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                                        UNION ALL
                                        SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                                        )
                    --20180426 exClude prevdate iF not From sp aCF aCCru
                    AND CASE WHEN B.DOWNLOAD_DATE=V_PREVDATE AND B.SEQ<>'2' THEN 0 ELSE 1 END  = 1
                    GROUP BY B.MASTERID) B
    ON (A.MASTERID=B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET A.FEE_AMT = A.FEE_AMT + B.FEE_AMT,
              A.COST_AMT = A.COST_AMT + B.COST_AMT;



    IF V_PARAM_DISABLE_ACCRU_PREV!=0
    THEN
      -- no aCCru iF todaY is doing amort
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_T1';

      INSERT INTO TMP_LI_T1(MASTERID)
      SELECT DISTINCT MASTERID
      FROM IFRS_LI_ACCT_SL_ACF WHERE DOWNLOAD_DATE=V_CURRDATE AND DO_AMORT='Y';


      EXECUTE IMMEDIATE 'trunCate table TMP_LI_T3';

      INSERT INTO TMP_LI_T3(MASTERID)
      SELECT MASTERID
      FROM IFRS_LI_ACCT_SL_CF_ECF
      WHERE MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_T1)
      --20180109 resona reCalC From start date : exClude aCCt todaY have reversal
      AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV);


      -- get last aCF with do_amort=N
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_P1';

      INSERT INTO TMP_LI_P1(ID)
      SELECT MAX(ID) AS ID
      FROM IFRS_LI_ACCT_SL_ACF
      WHERE MASTERID IN (SELECT MASTERID FROM TMP_LI_T3) AND DO_AMORT='N'
        AND DOWNLOAD_DATE<V_CURRDATE AND DOWNLOAD_DATE>=V_PREVDATE
      GROUP BY MASTERID;


      --kembalikan nilai aCCru prevdate ke unamort
      MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
      USING (SELECT * FROM IFRS_LI_ACCT_SL_ACF WHERE ID IN (SELECT ID FROM TMP_LI_P1)) B
      ON (B.MASTERID=A.MASTERID
          --20160407 SL stop rev
          AND A.MASTERID NOT IN (SELECT MASTERID FROM TMP_IFRS_LI_ACCT_STOP_REV)
          AND A.MASTERID NOT IN (SELECT DISTINCT MASTERID FROM IFRS_LI_ACCT_SWITCH WHERE DOWNLOAD_DATE = V_CURRDATE)
         )
      WHEN MATCHED THEN
      UPDATE
      SET A.FEE_AMT=A.FEE_AMT - B.N_ACCRU_FEE
        , A.COST_AMT=A.COST_AMT - B.N_ACCRU_COST;


      --20180108 Fee adj rev ambil dari unamort untuk pair dari CF rev
      MERGE INTO  IFRS_LI_ACCT_SL_CF_ECF A
      USING (SELECT * FROM IFRS_LI_ACCT_JOURNAL_INTM
             WHERE CF_ID IN (SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                              WHERE DOWNLOAD_DATE=V_CURRDATE
                              AND FLAG_REVERSE='Y'
                              AND CF_ID_REV IS NOT NULL
                            )
             AND DOWNLOAD_DATE=V_PREVDATE
             AND REVERSE='N'
             AND JOURNALCODE='ACCRU_SL'
             AND FLAG_CF='F'
             ) B
      ON (B.MASTERID=A.MASTERID
          --20160407 SL stop rev
          AND A.MASTERID NOT IN (SELECT MASTERID FROM TMP_IFRS_LI_ACCT_STOP_REV)
          --20180109 resona reCalC From start date : exClude aCCt todaY have reversal
          AND A.MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
         )
      WHEN MATCHED THEN
      UPDATE
      SET A.FEE_AMT=A.FEE_AMT+B.N_AMOUNT;


      --20180108 Cost adj rev ambil dari unamort untuk pair dari CF rev
      MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
      USING (SELECT * FROM IFRS_LI_ACCT_JOURNAL_INTM
                    WHERE CF_ID IN (SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                                    WHERE DOWNLOAD_DATE=V_CURRDATE
                                      AND FLAG_REVERSE='Y'
                                      AND CF_ID_REV IS NOT NULL
                                   )
                    AND DOWNLOAD_DATE=V_PREVDATE
                    AND REVERSE='N'
                    AND JOURNALCODE='ACCRU_SL'
                    AND FLAG_CF='C'
                    ) B
      ON (B.MASTERID=A.MASTERID
          --20160407 SL stop rev
          AND A.MASTERID NOT IN (SELECT MASTERID FROM TMP_IFRS_LI_ACCT_STOP_REV)
          --20180109 resona reCalC From start date : exClude aCCt todaY have reversal
          AND A.MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
         )
      WHEN MATCHED THEN
      UPDATE
      SET  A.COST_AMT=A.COST_AMT+B.N_AMOUNT;

    END IF;

    -- aCCru
    MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
      USING (SELECT B.MASTERID,
                         SUM (COALESCE (CASE WHEN B.FLAG_CF = 'F' THEN CASE WHEN B.FLAG_REVERSE = 'Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END
                                             ELSE 0 END,0))AS FEE_AMT,
                         SUM (COALESCE (CASE WHEN B.FLAG_CF = 'C' THEN CASE WHEN B.FLAG_REVERSE = 'Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END
                                             ELSE 0 END,0))AS COST_AMT
                  FROM IFRS_LI_ACCT_SL_ACCRU_PREV B
                  WHERE B.STATUS = 'ACT'
                  --20180108 exClude CF rev and its pair
                  AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                                      UNION ALL
                                      SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                                      )
                  --20180109 resona reCalC From start date : exClude aCCt todaY have reversal
                  AND B.MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
                  GROUP BY B.MASTERID
                  ) B
      ON ( B.MASTERID = A.MASTERID
         )
      WHEN MATCHED THEN
      UPDATE
      SET A.FEE_AMT_ACRU = B.FEE_AMT, A.COST_AMT_ACRU = B.COST_AMT;

    -- update total
    UPDATE IFRS_LI_ACCT_SL_CF_ECF
    SET TOTAL_AMT = ROUND (FEE_AMT + COST_AMT, 0),
    TOTAL_AMT_ACRU =ROUND (FEE_AMT + COST_AMT + FEE_AMT_ACRU + COST_AMT_ACRU, 0);


    --update due_date to expeCted liFe date iF available    20120717
    MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
      USING (SELECT A.DUE_DATE, A.MASTERID
                  ,P.EXPECTED_LIFE
                  ,B.LOAN_START_DATE
                  ,B.LOAN_DUE_DATE
            FROM IFRS_LI_ACCT_SL_CF_ECF A
            JOIN IFRS_LI_IMA_AMORT_CURR B
              ON A.MASTERID=B.MASTERID
	    JOIN IFRS_LI_ACCT_COST_FEE C
	      ON B.MASTERID = C.MASTERID
	      AND B.DOWNLOAD_DATE = C.DOWNLOAD_DATE
            LEFT JOIN IFRS_LI_PRODUCT_PARAM P
              ON P.PRD_CODE=B.PRODUCT_CODE
              AND P.PRD_TYPE = B.PRODUCT_TYPE
              AND P.DATA_SOURCE=B.DATA_SOURCE
              AND P.CCY=B.CURRENCY
	    LEFT JOIN IFRS_LI_TRANSACTION_PARAM D
	      ON P.PRD_CODE = D.PRD_CODE
	      AND C.TRX_CODE = D.TRX_CODE
	      --AND D.TENOR_TYPE = 'E'
          WHERE B.DOWNLOAD_DATE=V_CURRDATE
            ) B
      ON (A.MASTERID=B.MASTERID
         )
      WHEN MATCHED THEN
      UPDATE
      SET A.DUE_DATE=CASE WHEN NVL(B.EXPECTED_LIFE,0)>0 THEN
                          CASE WHEN FN_PMTDATE(B.LOAN_START_DATE,B.EXPECTED_LIFE)<B.LOAN_DUE_DATE THEN (FN_PMTDATE(B.LOAN_START_DATE,B.EXPECTED_LIFE))
                               ELSE B.LOAN_DUE_DATE END
                        ELSE B.LOAN_DUE_DATE
                   END;

     COMMIT;


    -- do Full amort iF sum Cost Fee zero and dont Create new eCF
    UPDATE IFRS_LI_ACCT_COST_FEE
    SET STATUS = 'PNL'
        , CREATEDBY = 'SLECF1'
    WHERE     DOWNLOAD_DATE = V_CURRDATE
    AND MASTERID IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_CF_ECF WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0)
    AND STATUS = 'ACT'
    --20180108 exClude CF rev and its pair, will be handled bY aCF_abn
    AND CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      UNION ALL
                      SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      );
    COMMIT;


    -- iF last Cost Fee prev is Currdate
    UPDATE IFRS_LI_ACCT_SL_COST_FEE_PREV
    SET STATUS = 'PNL', CREATEDBY = 'SLECF2'
    WHERE ID IN (SELECT A.ID
                 FROM IFRS_LI_ACCT_SL_COST_FEE_PREV A, VW_LI_LAST_SL_CF_PREV B
                 WHERE A.DOWNLOAD_DATE = V_CURRDATE
                 AND A.MASTERID IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_CF_ECF WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0)
                 AND A.STATUS = 'ACT'
                 AND A.MASTERID = B.MASTERID
                 AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
                 AND A.SEQ = B.SEQ)
    --20180108 exClude CF rev and its pair, will be handled bY sp aCF abn
    AND CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      UNION ALL
                      SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      )
		--20180109 resona reCalC From start date : exClude aCCt todaY have reversal
		AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV);
    COMMIT;


    -- iF last Cost Fee prev is prevdate
    UPDATE IFRS_LI_ACCT_SL_COST_FEE_PREV
    SET STATUS = 'PNL2', CREATEDBY = 'SLECF2'
    WHERE ID IN(SELECT A.ID
                FROM IFRS_LI_ACCT_SL_COST_FEE_PREV A, VW_LI_LAST_SL_CF_PREV B
                WHERE A.DOWNLOAD_DATE = V_PREVDATE
                AND A.MASTERID IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_CF_ECF WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0)
                AND A.STATUS = 'ACT'
                AND A.MASTERID = B.MASTERID
                AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
                --20180426 exClude prevdate iF not From sp aCF aCCru
                AND CASE WHEN A.DOWNLOAD_DATE=V_PREVDATE AND A.SEQ<>'2' THEN 0 ELSE 1 END  = 1
                AND A.SEQ = B.SEQ)
                --20180108 exClude CF rev and its pair, will be handled bY aCF_abn
    AND CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      UNION ALL
                      SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      )
		--20180109 resona reCalC From start date : exClude aCCt todaY have reversal
		AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV);

    COMMIT;

    IF V_PARAM_DISABLE_ACCRU_PREV!=0
    THEN
      -- insert aCCru prev onlY For pnl ed
      -- get last aCF with do_amort=N
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_P1';

      INSERT INTO TMP_LI_P1(ID)
      SELECT MAX(ID) AS ID
      FROM IFRS_LI_ACCT_SL_ACF
      WHERE MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
      AND DO_AMORT='N'
      AND DOWNLOAD_DATE<V_CURRDATE
      AND DOWNLOAD_DATE>=V_PREVDATE
      -- add Filter pnl ed aCCtno
      AND MASTERID IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_CF_ECF WHERE TOTAL_AMT=0 OR TOTAL_AMT_ACRU=0)
      --20180109 resona reCalC From start date : exClude aCCt todaY have reversal
      AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
      GROUP BY MASTERID;

      COMMIT;

      -- get Fee summarY
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_TF';

      INSERT INTO TMP_LI_TF(SUM_AMT,DOWNLOAD_DATE,MASTERID)
      SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
      FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                 ,A.ECFDATE DOWNLOAD_DATE
                 ,A.MASTERID
           FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
           WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
           AND A.STATUS='ACT'
           AND A.FLAG_CF='F'
           AND A.METHOD='SL'
          ) A
      GROUP BY A.DOWNLOAD_DATE,A.MASTERID;
      COMMIT;

      -- get Cost summarY
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_TC';

      INSERT INTO TMP_LI_TC(SUM_AMT,DOWNLOAD_DATE,MASTERID)
      SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
      FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                 ,A.ECFDATE DOWNLOAD_DATE
                 ,A.MASTERID
            FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
            WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
            AND A.STATUS='ACT'
            AND A.FLAG_CF='C'
            AND A.METHOD='SL'
            ) A
      GROUP BY A.DOWNLOAD_DATE,A.MASTERID;
	    COMMIT;

      --insert Fee 1
      INSERT INTO IFRS_LI_ACCT_SL_ACCRU_PREV
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY
      ,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO
      ,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,AMORTDATE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      ,METHOD
      )
      SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,A.ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_FEE AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,'N'
            ,NULL AS AMORTDATE
            ,'ECF'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE
            ,B.CF_ID
            ,B.METHOD
      FROM IFRS_LI_ACCT_SL_ACF A
      JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B
        ON B.ECFDATE=A.ECFDATE
        AND A.MASTERID=B.MASTERID
        AND B.FLAG_CF='F'
        AND B.STATUS = 'ACT'
        AND A.MASTERID NOT IN (SELECT DISTINCT MASTERID FROM IFRS_LI_ACCT_SWITCH WHERE DOWNLOAD_DATE = V_CURRDATE )
      JOIN TMP_LI_TF C
        ON C.DOWNLOAD_DATE=A.ECFDATE
        AND C.MASTERID=A.MASTERID
      WHERE A.ID IN (SELECT ID FROM TMP_LI_P1)
      --20180108 exClude CF rev and its pair
			AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        );
	    COMMIT;


      --Cost 1
      INSERT INTO IFRS_LI_ACCT_SL_ACCRU_PREV
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY
      ,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO
      ,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,AMORTDATE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      ,METHOD
      )
      SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,A.ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_COST AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,'N'
            , NULL AS AMORTDATE
            ,'ECF'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE
            ,B.CF_ID
            ,B.METHOD
      FROM IFRS_LI_ACCT_SL_ACF A
      JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B
        ON B.ECFDATE=A.ECFDATE
        AND A.MASTERID=B.MASTERID
        AND B.FLAG_CF='C'
        AND A.MASTERID NOT IN (SELECT DISTINCT MASTERID FROM IFRS_ACCT_SWITCH WHERE DOWNLOAD_DATE = V_CURRDATE)
        AND B.STATUS = 'ACT'
      JOIN TMP_LI_TC C
        ON C.DOWNLOAD_DATE=A.ECFDATE
        AND C.MASTERID=A.MASTERID
      WHERE A.ID IN (SELECT ID FROM TMP_LI_P1)
      --20180108 exClude CF rev and its pair
			AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        );
      COMMIT;
    END IF;


    -- mark For do amort aCru
    UPDATE IFRS_LI_ACCT_SL_ACCRU_PREV
    SET STATUS = TO_CHAR (V_CURRDATE, 'YYYYMMDD')
    WHERE STATUS = 'ACT'
    AND MASTERID IN (SELECT MASTERID
                     FROM IFRS_LI_ACCT_SL_CF_ECF
                     WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0);

    COMMIT;

    -- stop old eCF
    UPDATE IFRS_LI_ACCT_SL_ECF
    SET AMORTSTOPDATE = V_CURRDATE, AMORTSTOPREASON = 'SP_ACCT_SL_ECF'
    WHERE MASTERID IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_CF_ECF)
    AND AMORTSTOPDATE IS NULL;
    COMMIT;


    INSERT INTO IFRS_LI_ACCT_SL_ECF_STOPPED
    (DOWNLOAD_DATE
    ,MASTERID
    ,AMORTSTOPDATE
    ,AMORTSTOPREASON
    )
    SELECT DOWNLOAD_DATE,
           MASTERID,
           AMORTSTOPDATE,
           AMORTSTOPREASON
    FROM IFRS_LI_ACCT_SL_ECF
    WHERE     AMORTSTOPDATE = V_CURRDATE
    AND AMORTSTOPREASON = 'SP_ACCT_SL_ECF'
    AND PMTDATE = PREVDATE;
    COMMIT;


    -- 20160412 update start_amort_date
    UPDATE IFRS_LI_ACCT_SL_CF_ECF
    SET START_AMORT_DATE=V_CURRDATE;
    COMMIT;


    IF V_PARAM_CALC_TO_LASTPAYMENT=1
    THEN
      -- 20160412 set start amort date to last paYment date
      -- better get it From master aCCount iF available
      UPDATE IFRS_LI_ACCT_SL_CF_ECF
      SET START_AMORT_DATE=DUE_DATE;
      COMMIT;

      WHILE 1=1
      LOOP

        V_LOOPS:=0;

        UPDATE IFRS_LI_ACCT_SL_CF_ECF
        SET START_AMORT_DATE=FN_PMTDATE(START_AMORT_DATE,-1)
        WHERE START_AMORT_DATE>V_CURRDATE;


        SELECT 1
        INTO V_LOOPS
        FROM IFRS_LI_ACCT_SL_CF_ECF
        WHERE START_AMORT_DATE>V_CURRDATE ;

        EXIT WHEN V_LOOPS<>1 ;
      END LOOP;
    END IF;
    COMMIT;


    --20180327 resona reCalC From start date iF First Fee / dont have previous eCF
    --20180328 CtbC : remark iF migration date diFFerent with Currdate
    MERGE INTO IFRS_LI_ACCT_SL_CF_ECF A
    USING ( SELECT A.MASTERID, MAX(A.LOAN_START_DATE) AS MAX_DATE
            FROM IFRS_LI_MASTER_ACCOUNT A
            JOIN IFRS_LI_ACCT_COST_FEE B
            ON A.MASTERID=B.MASTERID
            AND A.DOWNLOAD_DATE=B.DOWNLOAD_DATE
            WHERE A.DOWNLOAD_DATE=V_CURRDATE
            AND B.STATUS='ACT'
            AND B.DOWNLOAD_DATE<>'01 JAN 2018'
            AND B.MASTERID NOT IN (SELECT MASTERID FROM IFRS_LI_ACCT_SL_ECF)
            GROUP BY  A.MASTERID
          )B
    ON (A.MASTERID=B.MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.START_AMORT_DATE=B.MAX_DATE;


    COMMIT;

    --new loop
    EXECUTE IMMEDIATE 'trunCate table IFRS_LI_ACCT_SL_ECF1';
    COMMIT;


    INSERT INTO IFRS_LI_ACCT_SL_ECF1
    (DOWNLOAD_DATE
    ,FACNO
    ,CIFNO
    ,DATASOURCE
    ,PREVDATE
    ,PMTDATE
    ,I_DAYSCNT
    ,N_UNAMORT_COST
    ,N_UNAMORT_FEE
    ,N_AMORT_COST
    ,N_AMORT_FEE
    ,CREATEDDATE
    ,CREATEDBY
    ,MASTERID
    ,ACCTNO
    ,N_DAILY_AMORT_COST
    ,N_DAILY_AMORT_FEE
    ,AMORTENDDATE
    ,PERIOD
    ,UNAMORT_COST_PREV
    ,UNAMORT_FEE_PREV
    ,START_AMORT_DATE
    )
    SELECT V_CURRDATE
          ,B.FACILITY_NUMBER
          ,B.CUSTOMER_NUMBER
          ,B.DATA_SOURCE
          ,CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1)
                ELSE A.START_AMORT_DATE
           END -- as prevdate
          /*,CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1)
                ELSE A.START_AMORT_DATE
           END -- as prevdate
           */
          ,a.due_date	-- as pmtdate
          ,((CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1)
                  ELSE A.START_AMORT_DATE
             END)-A.DUE_DATE)*-1 --daYsCount
          /*
          ,((CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1)
                  ELSE A.START_AMORT_DATE
             END)-A.DUE_DATE) --daYsCount
          */
          ,A.COST_AMT-(CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)*A.COST_AMT)--unamort Cost
          ,A.FEE_AMT-(CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)*A.FEE_AMT)--unamort Fee
          ,(CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE) * A.COST_AMT)*-1	--amort Cost
          ,(CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE) * A.FEE_AMT)*-1	--amort Fee
          ,SYSTIMESTAMP
          ,'SP_ACCT_SL_ECF'
          ,B.MASTERID
          ,B.ACCOUNT_NUMBER
          ,(A.COST_AMT/(A.DUE_DATE -A.START_AMORT_DATE))*-1
          ,(a.fee_amt/(a.due_date -a.start_amort_date))*-1
          ,a.due_date amortendate
          ,a.due_date -a.start_amort_date period
          ,A.COST_AMT-(CAST(CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1) ELSE A.START_AMORT_DATE END -A.START_AMORT_DATE AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)* CAST (A.COST_AMT AS BINARY_DOUBLE))--unamort Cost
          ,A.Fee_amt-(CAST(CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1) ELSE A.START_AMORT_DATE END -A.START_AMORT_DATE AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)* CAST (A.Fee_amt AS BINARY_DOUBLE))--unamort Fee
          /*
          ,A.COST_AMT-(CAST(CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1) ELSE A.START_AMORT_DATE END -A.START_AMORT_DATE AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)* CAST (A.COST_AMT AS BINARY_DOUBLE))--unamort Cost
          ,A.Fee_amt-(CAST(CASE WHEN (FN_PMTDATE(A.DUE_DATE,-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(A.DUE_DATE,-1) ELSE A.START_AMORT_DATE END -A.START_AMORT_DATE AS BINARY_DOUBLE)/CAST((A.DUE_DATE-A.START_AMORT_DATE) AS BINARY_DOUBLE)* CAST (A.Fee_amt AS BINARY_DOUBLE))--unamort Fee
          */
          ,A.START_AMORT_DATE
    FROM IFRS_LI_ACCT_SL_CF_ECF A
    JOIN IFRS_LI_IMA_AMORT_CURR B ON B.DOWNLOAD_DATE=V_CURRDATE AND A.MASTERID=B.MASTERID AND B.LOAN_DUE_DATE>V_CURRDATE
    WHERE A.TOTAL_AMT<>0 AND A.TOTAL_AMT_ACRU<>0 AND A.DUE_DATE>V_CURRDATE;
    COMMIT;


    WHILE 1=1
    LOOP

      V_LOOPS :=0;

      INSERT INTO IFRS_LI_ACCT_SL_ECF
      (DOWNLOAD_DATE,FACNO,CIFNO,DATASOURCE,PREVDATE,PMTDATE,I_DAYSCNT,N_UNAMORT_COST,N_UNAMORT_FEE,N_AMORT_COST,N_AMORT_FEE,CREATEDDATE,CREATEDBY,MASTERID,ACCTNO,N_DAILY_AMORT_COST,N_DAILY_AMORT_FEE,AMORTENDDATE,PERIOD,UNAMORT_COST_PREV,UNAMORT_FEE_PREV)
      SELECT
      DOWNLOAD_DATE,FACNO,CIFNO,DATASOURCE,PREVDATE,PMTDATE,I_DAYSCNT,N_UNAMORT_COST,N_UNAMORT_FEE,N_AMORT_COST,N_AMORT_FEE,CREATEDDATE,CREATEDBY,MASTERID,ACCTNO,N_DAILY_AMORT_COST,N_DAILY_AMORT_FEE,AMORTENDDATE,PERIOD,UNAMORT_COST_PREV,UNAMORT_FEE_PREV
      FROM IFRS_LI_ACCT_SL_ECF1;

      EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LI_ACCT_SL_ECF2';

      INSERT INTO IFRS_LI_ACCT_SL_ECF2
      (DOWNLOAD_DATE,FACNO,CIFNO,DATASOURCE,PREVDATE,PMTDATE,I_DAYSCNT,N_UNAMORT_COST,N_UNAMORT_FEE,N_AMORT_COST,N_AMORT_FEE,CREATEDDATE,CREATEDBY,MASTERID,ACCTNO,N_DAILY_AMORT_COST,N_DAILY_AMORT_FEE,AMORTENDDATE,PERIOD,UNAMORT_COST_PREV,UNAMORT_FEE_PREV,START_AMORT_DATE)
      SELECT
      DOWNLOAD_DATE,FACNO,CIFNO,DATASOURCE,PREVDATE,PMTDATE,I_DAYSCNT,N_UNAMORT_COST,N_UNAMORT_FEE,N_AMORT_COST,N_AMORT_FEE,CREATEDDATE,CREATEDBY,MASTERID,ACCTNO,N_DAILY_AMORT_COST,N_DAILY_AMORT_FEE,AMORTENDDATE,PERIOD,UNAMORT_COST_PREV,UNAMORT_FEE_PREV,START_AMORT_DATE
      FROM IFRS_LI_ACCT_SL_ECF1;

      EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LI_ACCT_SL_ECF1';

      INSERT INTO IFRS_LI_ACCT_SL_ECF1
      (DOWNLOAD_DATE,FACNO,CIFNO,DATASOURCE,PREVDATE,PMTDATE,I_DAYSCNT,N_UNAMORT_COST,N_UNAMORT_FEE,N_AMORT_COST,N_AMORT_FEE,CREATEDDATE,CREATEDBY,MASTERID,ACCTNO,N_DAILY_AMORT_COST,N_DAILY_AMORT_FEE,AMORTENDDATE,PERIOD,UNAMORT_COST_PREV,UNAMORT_FEE_PREV,START_AMORT_DATE)
      SELECT V_CURRDATE
             ,a.facno
             ,A.CIFNO
             ,a.datasource
             ,CASE WHEN (FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)
                   ELSE A.START_AMORT_DATE
              END --prevdate
             ,FN_PMTDATE(A.PMTDATE,-1)--pmtdate
             ,FN_PMTDATE(A.PMTDATE,-1)-CASE WHEN (FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)
                                               ELSE A.START_AMORT_DATE
                                          END 	--daYsCount

             ,B.COST_AMT-(CAST(FN_PMTDATE(A.PMTDATE,-1)-A.START_AMORT_DATE AS BINARY_DOUBLE)/ CAST (A.PERIOD AS BINARY_DOUBLE) * CAST(B.COST_AMT AS BINARY_DOUBLE))	--unamort Cost
             ,B.FEE_AMT-(CAST(FN_PMTDATE(A.PMTDATE,-1)-A.START_AMORT_DATE AS BINARY_DOUBLE)/ CAST (A.PERIOD AS BINARY_DOUBLE) * CAST(B.FEE_AMT AS BINARY_DOUBLE))	--unamort Fee
             ,((cast((FN_PMTDATE(a.pmtdate,-1)-a.start_amort_date) as BINARY_DOUBLE)/cast(a.period as BINARY_DOUBLE) * cast(b.COST_AMT as BINARY_DOUBLE)))*-1 AS AMORT_COST
             ,((cast((FN_PMTDATE(a.pmtdate,-1)-a.start_amort_date) as BINARY_DOUBLE)/cast(a.period as BINARY_DOUBLE) * cast(b.fee_amt as BINARY_DOUBLE)))*-1 AS AMORT_FEE
             /*
             ,CASE WHEN (FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)
                   ELSE A.START_AMORT_DATE
              END --prevdate
             ,FN_PMTDATE(A.PMTDATE,-1)	--pmtdate
             ,FN_PMTDATE(A.PMTDATE,-1)-CASE WHEN (FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1)
                                               ELSE A.START_AMORT_DATE
                                          END 	--daYsCount

             ,B.COST_AMT-(CAST(FN_PMTDATE(A.PMTDATE,-1)-A.START_AMORT_DATE AS BINARY_DOUBLE)/ CAST (A.PERIOD AS BINARY_DOUBLE) * CAST(B.COST_AMT AS BINARY_DOUBLE))	--unamort Cost
             ,B.FEE_AMT-(CAST(FN_PMTDATE(A.PMTDATE,-1)-A.START_AMORT_DATE AS BINARY_DOUBLE)/ CAST (A.PERIOD AS BINARY_DOUBLE) * CAST(B.FEE_AMT AS BINARY_DOUBLE))	--unamort Fee
             ,(CAST(FN_PMTDATE(A.PMTDATE,-1)-A.START_AMORT_DATE AS BINARY_DOUBLE) * CAST (B.COST_AMT AS BINARY_DOUBLE))*-1 --amort Cost
             ,(CAST((FN_PMTDATE(A.PMTDATE,-1))-A.START_AMORT_DATE AS BINARY_DOUBLE) * CAST (B.FEE_AMT AS BINARY_DOUBLE))*-1 --amort Fee
             */
             ,SYSTIMESTAMP
             ,'sp_aCCt_SL_eCF'
             ,A.MASTERID
             ,A.ACCTNO
             ,A.N_DAILY_AMORT_COST
             ,a.n_daily_amort_fee
             ,A.AMORTENDDATE
             ,a.period
              ,B.COST_AMT-(CAST((CASE WHEN ((FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1))-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1) ELSE A.START_AMORT_DATE END)-A.START_AMORT_DATE AS BINARY_DOUBLE) /CAST(A.PERIOD AS BINARY_DOUBLE) * CAST(B.COST_AMT AS BINARY_DOUBLE)) --unamort Cost
             ,B.FEE_AMT-(CAST((CASE WHEN ((FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1))-A.START_aMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1) ELSE A.START_AMORT_DATE END)-A.START_AMORT_DATE AS BINARY_DOUBLE) /CAST(A.PERIOD AS BINARY_DOUBLE) * CAST(B.FEE_AMT AS BINARY_DOUBLE)) --unamort FEE
             /*
             ,B.COST_AMT-(CAST((CASE WHEN ((FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1))-A.START_AMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1) ELSE A.START_AMORT_DATE END)-A.START_AMORT_DATE AS BINARY_DOUBLE) /CAST(A.PERIOD AS BINARY_DOUBLE) * CAST(B.COST_AMT AS BINARY_DOUBLE)) --unamort Cost
             ,B.FEE_AMT-(CAST((CASE WHEN ((FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1))-A.START_aMORT_DATE)>0 THEN FN_PMTDATE(FN_PMTDATE(A.PMTDATE,-1),-1) ELSE A.START_AMORT_DATE END)-A.START_AMORT_DATE AS BINARY_DOUBLE) /CAST(A.PERIOD AS BINARY_DOUBLE) * CAST(B.FEE_AMT AS BINARY_DOUBLE)) --unamort FEE
             */
             ,A.START_AMORT_DATE
      FROM IFRS_LI_ACCT_SL_ECF2 A
      JOIN IFRS_LI_ACCT_SL_CF_ECF B ON B.MASTERID=A.MASTERID;


      DELETE FROM IFRS_LI_ACCT_SL_ECF1
      WHERE PMTDATE<=START_AMORT_DATE;

      BEGIN
        SELECT 1
        INTO V_LOOPS
        FROM IFRS_LI_ACCT_SL_ECF1 WHERE ROWNUM <= 1;
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_LOOPS := 0;
      END;

      EXIT WHEN V_LOOPS<>1 ;

    END LOOP;


    COMMIT;
    -- Currdate row
    INSERT INTO IFRS_LI_ACCT_SL_ECF
    (DOWNLOAD_DATE
    ,FACNO
    ,CIFNO
    ,DATASOURCE
    ,PREVDATE
    ,PMTDATE
    ,I_DAYSCNT
    ,N_UNAMORT_COST
    ,N_UNAMORT_FEE
    ,N_AMORT_COST
    ,N_AMORT_FEE
    ,CREATEDDATE
    ,CREATEDBY
    ,MASTERID
    ,ACCTNO
    ,N_DAILY_AMORT_COST
    ,N_DAILY_AMORT_FEE
    ,AMORTENDDATE
    ,PERIOD
    ,UNAMORT_COST_PREV
    ,UNAMORT_FEE_PREV
    )
    SELECT  V_CURRDATE
           ,B.FACILITY_NUMBER
           ,B.CUSTOMER_NUMBER
           ,B.DATA_SOURCE
           ,A.START_AMORT_DATE
           ,A.START_AMORT_DATE
           ,0
           ,A.COST_AMT
           ,A.FEE_AMT
           ,0
           ,0
           ,SYSTIMESTAMP
           ,NULL
           ,B.MASTERID
           ,B.ACCOUNT_NUMBER
           ,(A.COST_AMT/(A.DUE_DATE -A.START_AMORT_DATE))*-1
           ,(A.FEE_AMT/(A.DUE_DATE -A.START_AMORT_DATE))*-1
           ,A.DUE_DATE AMORTENDATE
           ,A.DUE_DATE -A.START_AMORT_DATE PERIOD
           ,A.COST_AMT
           ,A.FEE_AMT
    FROM IFRS_LI_ACCT_SL_CF_ECF A
    JOIN IFRS_LI_IMA_AMORT_CURR B
      ON B.DOWNLOAD_DATE=V_CURRDATE
      AND A.MASTERID=B.MASTERID
      AND B.LOAN_DUE_DATE>V_CURRDATE
    WHERE A.TOTAL_AMT<>0
    AND A.TOTAL_AMT_ACRU<>0
    AND A.DUE_DATE>V_CURRDATE;
    COMMIT;

    -- insert IFRS_LI_ACCT_SL_COST_FEE_ECF
    --delete From IFRS_LI_ACCT_SL_COST_FEE_ECF where eCFdate=@v_CURRDATE

    INSERT INTO IFRS_LI_ACCT_SL_COST_FEE_ECF
    (DOWNLOAD_DATE,ECFDATE,MASTERID,BRCODE,CIFNO,FACNO,ACCTNO,DATASOURCE,CCY
    ,PRDCODE,TRXCODE,FLAG_CF,FLAG_REVERSE,METHOD
    ,STATUS,SRCPROCESS,AMOUNT,CREATEDDATE,CREATEDBY,SEQ
    ,AMOUNT_ORG,ORG_CCY,ORG_CCY_EXRATE,PRDTYPE,CF_ID
    )
    -- insert Currdate Cost/Fee
    SELECT C.DOWNLOAD_DATE
          ,V_CURRDATE ECFDATE
          ,C.MASTERID
          ,C.BRCODE
          ,C.CIFNO
          ,C.FACNO
          ,C.ACCTNO
          ,C.DATASOURCE
          ,C.CCY
          ,C.PRD_CODE
          ,C.TRX_CODE
          ,C.FLAG_CF
          ,C.FLAG_REVERSE
          ,C.METHOD
          ,C.STATUS
          ,C.SRCPROCESS
          ,C.AMOUNT
          ,SYSTIMESTAMP CREATEDDATE
          ,'SL_eCF_main' CREATEDBY
          ,'' SEQ
          ,C.AMOUNT
          ,C.ORG_CCY
          ,C.ORG_CCY_EXRATE
          ,C.PRD_TYPE
          ,C.CF_ID
    FROM IFRS_LI_ACCT_COST_FEE C
    JOIN IFRS_LI_ACCT_SL_CF_ECF B
      ON B.MASTERID=C.MASTERID
      AND B.TOTAL_AMT<>0
      AND B.TOTAL_AMT_ACRU<>0
    WHERE C.DOWNLOAD_DATE=V_CURRDATE
    AND C.MASTERID=B.MASTERID
    AND C.STATUS='ACT'
    AND C.METHOD='SL'
    --20180108 exClude CF rev and its pair
    AND C.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        UNION ALL
                        SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      )
    UNION ALL
    -- insert unamort
    SELECT C.DOWNLOAD_DATE
          ,V_CURRDATE ECFDATE
          ,C.MASTERID
          ,C.BRCODE
          ,C.CIFNO
          ,C.FACNO
          ,C.ACCTNO
          ,C.DATASOURCE
          ,C.CCY
          ,C.PRDCODE
          ,C.TRXCODE
          ,C.FLAG_CF
          ,C.FLAG_REVERSE
          ,C.METHOD
          ,C.STATUS
          ,C.SRCPROCESS
          ,CASE WHEN CFREV.MASTERID IS NULL THEN C.AMOUNT ELSE C.AMOUNT_ORG END
          ,SYSTIMESTAMP CREATEDDATE
          ,'SL_eCF_main' CREATEDBY
          ,'' SEQ
          ,C.AMOUNT_ORG
          ,C.ORG_CCY
          ,C.ORG_CCY_EXRATE
          ,C.PRDTYPE
          ,C.CF_ID
    FROM IFRS_LI_ACCT_SL_COST_FEE_PREV C
    JOIN VW_LI_LAST_SL_CF_PREV X
      ON X.MASTERID=C.MASTERID
      AND X.DOWNLOAD_DATE=C.DOWNLOAD_DATE
      AND C.SEQ=X.SEQ
    JOIN IFRS_LI_ACCT_SL_CF_ECF B
      ON B.MASTERID=C.MASTERID
      AND B.TOTAL_AMT<>0
      AND B.TOTAL_AMT_ACRU<>0
    --20160721
    LEFT JOIN TMP_IFRS_LI_ACCT_STOP_REV REV
      ON C.MASTERID = REV.MASTERID
    --20180109 resona reCalC From loan start date
    LEFT JOIN TMP_LI_TODAYREV CFREV
      ON CFREV.MASTERID=C.MASTERID
    WHERE C.DOWNLOAD_DATE IN (V_CURRDATE,V_PREVDATE)
    AND C.STATUS='ACT'
    -- 20160407 SL stop rev exCluded
    AND REV.MASTERID IS NULL
    --20180108 exClude CF rev and its pair
    AND C.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        UNION ALL
                        SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                        WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                      )
    --20180426 exClude prevdate iF not From sp aCF aCCru
    AND CASE WHEN C.DOWNLOAD_DATE=V_PREVDATE AND C.SEQ<>'2' THEN 0 ELSE 1 END  = 1;
    COMMIT;

    IF V_PARAM_DISABLE_ACCRU_PREV!=0
    THEN
      -- purpose : to insert YesterdaY aCCru to SL_Cost_Fee eCF
      -- no aCCru iF todaY is doing amort
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_T1';

      INSERT INTO TMP_LI_T1(MASTERID)
      SELECT DISTINCT MASTERID
      FROM IFRS_LI_ACCT_SL_ACF
      WHERE DOWNLOAD_DATE=V_CURRDATE
      AND DO_AMORT='Y';


      EXECUTE IMMEDIATE 'trunCate table TMP_LI_T3';

      INSERT INTO TMP_LI_T3(MASTERID)
      SELECT MASTERID
      FROM IFRS_LI_ACCT_SL_CF_ECF
      WHERE MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_T1);


      -- get last aCF with do_amort=N
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_P1';

      INSERT INTO TMP_LI_P1(ID)
      SELECT MAX(ID) AS ID
      FROM IFRS_LI_ACCT_SL_ACF
      WHERE MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
      AND DO_AMORT=''
      AND DOWNLOAD_DATE<V_CURRDATE
      AND DOWNLOAD_DATE>=V_PREVDATE
      --20180109 resona reCalC From start date
      AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
      GROUP BY MASTERID;


      -- get Fee summarY
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_TF';

      INSERT INTO TMP_LI_TF(SUM_AMT,DOWNLOAD_DATE,MASTERID)
      SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
      FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                 ,A.ECFDATE DOWNLOAD_DATE
                 ,A.MASTERID
           FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
           WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
           AND A.STATUS='ACT'
           AND A.FLAG_CF='F'
           AND A.METHOD='SL'
          ) A
      GROUP BY A.DOWNLOAD_DATE,A.MASTERID;
      COMMIT;


      -- get Cost summarY
      EXECUTE IMMEDIATE 'trunCate table TMP_LI_TC';

      INSERT INTO TMP_LI_TC(SUM_AMT,DOWNLOAD_DATE,MASTERID)
      SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
      FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                 ,A.ECFDATE DOWNLOAD_DATE
                 ,A.MASTERID
            FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
            WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_T3)
            AND A.STATUS='ACT'
            AND A.FLAG_CF='C'
            AND A.METHOD='SL'
          ) A
      GROUP BY A.DOWNLOAD_DATE,A.MASTERID;
      COMMIT;


      --insert Fee 1
      INSERT INTO IFRS_LI_ACCT_SL_COST_FEE_ECF
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY
      ,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO
      ,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      ,BRCODE
      ,METHOD
      )
      SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,V_CURRDATE ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_FEE * -1 AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,''
            ,'ECFACCRU'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE,
            B.CF_ID
            ,B.BRCODE
            ,B.METHOD
      FROM IFRS_LI_ACCT_SL_ACF A
      JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B
        ON B.ECFDATE=A.ECFDATE
        AND A.MASTERID=B.MASTERID
        AND B.FLAG_CF='F'
      JOIN TMP_LI_TF C
        ON C.DOWNLOAD_DATE=A.ECFDATE
        AND C.MASTERID=A.MASTERID
      --20160721
      LEFT JOIN TMP_IFRS_LI_ACCT_STOP_REV REV
        ON A.MASTERID = REV.MASTERID
      WHERE A.ID IN (SELECT ID FROM TMP_LI_P1)
      --20160407 SL stop rev
      --and a.masterid not in (seleCt masterid From IFRS_LI_ACCT_SL_STOP_REV where DOWNLOAD_DATE=@v_Currdate)
      AND REV.MASTERID IS NULL
      --20180108 exClude CF rev and its pair
      AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                        );

      COMMIT;

      --Cost 1
      INSERT INTO IFRS_LI_ACCT_SL_COST_FEE_ECF
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY
      ,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO
      ,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      ,BRCODE
      ,METHOD
      )
      SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,V_CURRDATE ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_COST * -1 AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,''
            ,'ECFACCRU'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE
            ,B.CF_ID
            ,B.BRCODE
            ,B.METHOD
      FROM IFRS_LI_ACCT_SL_ACF A
      JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B
        ON B.ECFDATE=A.ECFDATE
        AND A.MASTERID=B.MASTERID
        AND B.FLAG_CF='C'
      JOIN TMP_LI_TC C
        ON C.DOWNLOAD_DATE=A.ECFDATE
        AND C.MASTERID=A.MASTERID
      --20160721
      LEFT JOIN TMP_IFRS_LI_ACCT_STOP_REV REV
        ON A.MASTERID = REV.MASTERID
      WHERE A.ID IN (SELECT ID FROM TMP_LI_P1)
      --20160407 eir stop rev
      AND REV.MASTERID IS NULL
      --20180108 exClude CF rev and its pair
      AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                         );
      COMMIT;

    END IF;
    COMMIT;

    -- 20160412 group multiple rows bY CF_id
    SP_IFRS_EXEC_AND_LOG_PROCESS('SP_IFRS_LI_ACCT_SL_CF_ECF_GRP');
    /***************************************************************************************************************
    RESET
    ****************************************************************************************************************/
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_M0';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_MX';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_M';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_M2';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_ACRU';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_ACRU2';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_TF';
    EXECUTE IMMEDIATE  'TRUNCATE TABLE TMP_LI_TC';
    COMMIT;

    /***************************************************************************************************************
    GET ACCOUNT HAS NEW ECF CURRENT DATE
    ****************************************************************************************************************/
    INSERT INTO TMP_LI_M0(MASTERID)
    SELECT DISTINCT MASTERID
    FROM IFRS_LI_ACCT_SL_ECF
    WHERE DOWNLOAD_DATE=V_CURRDATE;
    COMMIT;

    /***************************************************************************************************************
    FILTER OUT NOT TODAY STOPPED ECF
    ****************************************************************************************************************/
    INSERT INTO TMP_LI_MX(MASTERID)
    SELECT DISTINCT A.MASTERID
    FROM TMP_LI_M0 A
    JOIN IFRS_LI_ACCT_SL_ECF B
      ON B.PREVDATE=B.PMTDATE
      AND B.AMORTSTOPDATE=V_CURRDATE
      AND B.MASTERID=A.MASTERID
    UNION        -- 20171013 also inClude aCCount with zero amount (Fix Chkamort on due_date Change when end_amort_dt - 1)
    SELECT MASTERID
    FROM IFRS_LI_ACCT_SL_CF_ECF
    WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0;

    COMMIT;


    INSERT INTO TMP_LI_M(MASTERID)
    SELECT DISTINCT A.MASTERID
    FROM TMP_LI_MX A
    LEFT JOIN TMP_IFRS_LI_ACCT_STOP_REV REV
      ON A.MASTERID = REV.MASTERID
    LEFT JOIN IFRS_LI_ACCT_SWITCH SW
      ON A.MASTERID = SW.MASTERID
      AND SW.DOWNLOAD_DATE=V_CURRDATE
    WHERE --switCh exCluded
    SW.MASTERID IS NULL
    -- 20160407 SL stop rev exCluded
    AND REV.MASTERID IS NULL;
    COMMIT;

    /***************************************************************************************************************
    INSERT ACCRU VALUES FOR NEWLY GENERATED ECF
    NO ACCRU IF TODAY IS DOING AMORT
    ****************************************************************************************************************/
    INSERT INTO TMP_LI_M2(MASTERID)
    SELECT DISTINCT MASTERID
    FROM IFRS_LI_ACCT_SL_ACF
    WHERE DOWNLOAD_DATE=V_CURRDATE
    AND DO_AMORT='Y';

    /***************************************************************************************************************
    TAKE OUT ACCOUNT IF TODAY IS DOING AMORT
    ****************************************************************************************************************/
    INSERT INTO TMP_LI_ACRU(MASTERID)
    SELECT MASTERID
    FROM TMP_LI_M
    WHERE MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_M2);

    IF V_PARAM_DISABLE_ACCRU_PREV=0
    THEN
      /***************************************************************************************************************
      GET LAST ACF WITH DO AMORT=N
      ****************************************************************************************************************/
      INSERT INTO TMP_LI_ACRU2(ID)
      SELECT MAX(ID) AS ID
      FROM IFRS_LI_ACCT_SL_ACF
      WHERE MASTERID IN (SELECT MASTERID FROM TMP_LI_ACRU)
      AND DO_AMORT='N'
      AND DOWNLOAD_DATE<V_CURRDATE
      --20180109 resona reCalC From start date
      AND MASTERID NOT IN (SELECT MASTERID FROM TMP_LI_TODAYREV)
      GROUP BY MASTERID;


      -- get Fee summarY
      INSERT INTO TMP_LI_TF(SUM_AMT,DOWNLOAD_DATE,MASTERID)
	    SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
	    FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                  ,A.ECFDATE DOWNLOAD_DATE
                  ,A.MASTERID
           FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
           WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_ACRU)
           AND A.STATUS='ACT'
           AND A.FLAG_CF='F'
           AND A.METHOD='SL'
          ) A
	    GROUP BY A.DOWNLOAD_DATE,A.MASTERID;

	    -- get Cost summarY
      INSERT INTO TMP_LI_TC(SUM_AMT,DOWNLOAD_DATE,MASTERID)
	    SELECT SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
	    FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                 ,A.ECFDATE DOWNLOAD_DATE
                 ,A.MASTERID
           FROM IFRS_LI_ACCT_SL_COST_FEE_ECF A
           WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_LI_ACRU)
           AND A.STATUS='ACT' AND A.FLAG_CF='C' AND A.METHOD='SL'
          ) A
	    GROUP BY A.DOWNLOAD_DATE,A.MASTERID;
      COMMIT;

	    --insert Fee 1
	    INSERT INTO IFRS_LI_ACCT_SL_ACCRU_PREV
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO
      ,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,AMORTDATE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      )
	    SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,A.ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_FEE AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,''
            ,NULL AS AMORTDATE
            ,'eCF'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE
            ,B.CF_ID
	    FROM IFRS_LI_ACCT_SL_ACF A
	    JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B ON B.ECFDATE=A.ECFDATE
	    AND A.MASTERID=B.MASTERID
	    AND B.FLAG_CF='F'
	    JOIN TMP_LI_TF C ON C.DOWNLOAD_DATE=A.ECFDATE AND C.MASTERID=A.MASTERID
	    WHERE A.ID IN (SELECT ID FROM TMP_LI_ACRU2)
	    --20180108 exClude CF rev and its pair
	    AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          );
      COMMIT;


      --Cost 1
      INSERT INTO IFRS_LI_ACCT_SL_ACCRU_PREV
      (FACNO
      ,CIFNO
      ,DOWNLOAD_DATE
      ,ECFDATE
      ,DATASOURCE
      ,PRDCODE
      ,TRXCODE
      ,CCY
      ,AMOUNT
      ,STATUS
      ,CREATEDDATE
      ,ACCTNO,MASTERID
      ,FLAG_CF
      ,FLAG_REVERSE
      ,AMORTDATE
      ,SRCPROCESS
      ,ORG_CCY
      ,ORG_CCY_EXRATE
      ,PRDTYPE
      ,CF_ID
      )
      SELECT A.FACNO
            ,A.CIFNO
            ,V_CURRDATE
            ,A.ECFDATE
            ,A.DATASOURCE
            ,B.PRDCODE
            ,B.TRXCODE
            ,B.CCY
            ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_COST AS N_AMOUNT
            ,B.STATUS
            ,SYSTIMESTAMP
            ,A.ACCTNO
            ,A.MASTERID
            ,B.FLAG_CF
            ,'', NULL AS AMORTDATE
            ,'eCF'
            ,B.ORG_CCY
            ,B.ORG_CCY_EXRATE
            ,B.PRDTYPE
            ,B.CF_ID
      FROM IFRS_LI_ACCT_SL_ACF A
      JOIN IFRS_LI_ACCT_SL_COST_FEE_ECF B
        ON B.ECFDATE=A.ECFDATE
        AND A.MASTERID=B.MASTERID
        AND B.FLAG_CF='C'
      JOIN TMP_LI_TC C ON C.DOWNLOAD_DATE=A.ECFDATE AND C.MASTERID=A.MASTERID
      WHERE A.ID IN (SELECT ID FROM TMP_LI_ACRU2)
      --20180108 exClude CF rev and its pair
      AND B.CF_ID NOT IN (SELECT CF_ID FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          UNION ALL
                          SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE
                          WHERE DOWNLOAD_DATE=V_CURRDATE AND FLAG_REVERSE='Y' AND CF_ID_REV IS NOT NULL
                          );
      COMMIT;

    END IF; --iF;
    COMMIT;

    -- 20171013 mark For do amort aCru (Fix Chkamort on due_date Change when end_amort_dt - 1)
    UPDATE IFRS_LI_ACCT_SL_ACCRU_PREV
    SET STATUS = TO_CHAR (V_CURRDATE, 'YYYYMMDD')
    WHERE STATUS = 'ACT'
    AND (MASTERID IN (SELECT MASTERID
                     FROM IFRS_LI_ACCT_SL_CF_ECF
                     WHERE TOTAL_AMT = 0 OR TOTAL_AMT_ACRU = 0
                     )
        --20180807 UPDATE BY VIVI, IF FEE REV BEFORE PMTDATE
        OR
        CF_ID IN (SELECT CF_ID_REV FROM IFRS_LI_ACCT_COST_FEE WHERE FLAG_REVERSE='Y' AND DOWNLOAD_DATE=V_CURRDATE)
        );
    COMMIT;

    INSERT INTO IFRS_LI_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'end','sp_iFrs_aCCt_SL_eCF_main','');
    COMMIT;
END;