CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_ADJUSTMENT_COVID(v_ECLID NUMBER DEFAULT (0), v_DOWNLOADDATE DATE DEFAULT ('1-JAN-1900'))
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    INSERT INTO GTMP_IFRS_MASTER_ACCOUNT
    (PKID,
     DOWNLOAD_DATE,
     MASTERID,
     MASTER_ACCOUNT_CODE,
     CUSTOMER_NUMBER,
     ACCOUNT_NUMBER,
     OUTSTANDING,
     RESERVED_RATE_1)
    SELECT A.PKID,
           A.DOWNLOAD_DATE,
           A.MASTERID,
           ' ' MASTER_ACCOUNT_CODE,
           A.CUSTOMER_NUMBER,
           A.ACCOUNT_NUMBER,
           A.OUTSTANDING,
           CASE WHEN B.PERSEN_PENCADANGAN > 1 THEN B.PERSEN_PENCADANGAN / 100 ELSE B.PERSEN_PENCADANGAN END
    FROM IFRS_ECL_RESULT_DETAIL A
             JOIN TBLU_ADJUSTMENT_COVID B
                  ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
                      AND A.DOWNLOAD_DATE = v_DOWNLOADDATE
                      AND A.ECL_MODEL_ID = v_ECLID
                      AND A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
    where NOT (PRODUCT_CODE = '306' and OUTSTANDING = 0);

    COMMIT;

    DELETE IFRS_ECL_RESULT_DETAIL_CALC
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
      AND ECL_MODEL_ID = v_ECLID
      AND MASTERID IN
          (SELECT MASTERID FROM GTMP_IFRS_MASTER_ACCOUNT)
      AND COUNTER_PAYSCHD > 1;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_CALC A
    USING GTMP_IFRS_MASTER_ACCOUNT B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
        AND A.ECL_MODEL_ID = v_ECLID
        AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
        UPDATE
        SET A.PD_RATE       = 1,
            A.LGD_RATE      = 1,
            A.DISCOUNT_RATE = 1,
            A.ECL_AMOUNT    = NVL(A.EAD_AMOUNT, 0) * B.RESERVED_RATE_1;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL A
    USING
        (SELECT A2.MASTERID, B2.ECL_AMOUNT, A2.IMPAIRED_FLAG
         FROM GTMP_IFRS_MASTER_ACCOUNT A2
                  JOIN IFRS_ECL_RESULT_DETAIL_CALC B2
                       ON B2.DOWNLOAD_DATE = v_DOWNLOADDATE
                           AND B2.ECL_MODEL_ID = v_ECLID
                           AND A2.MASTERID = B2.MASTERID) B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
        AND A.ECL_MODEL_ID = v_ECLID
        AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
        UPDATE
        SET A.ECL_AMOUNT     = B.ECL_AMOUNT,
            A.SPECIAL_REASON = 'ADJUSTMENT COVID';
    COMMIT;

    UPDATE IFRS_ECL_RESULT_DETAIL
    SET SPECIAL_REASON='ADJUSTMENT EXPOSURE'
    WHERE ACCOUNT_NUMBER IN (select ACCOUNT_NUMBER
                             from TBLU_ADJUSTMENT_COVID
                             where DOWNLOAD_DATE = v_DOWNLOADDATE
                               and FLAG = 'E');

    COMMIT;

END;