CREATE OR REPLACE PROCEDURE SP_IFRS_CFID_JRNL_INTM_SUMM
AS
  V_CURRDATE    DATE;
  V_PREVDATE    DATE;

BEGIN
    /******************************************************************************
    01. DECLARE VARIABLE
    *******************************************************************************/
    SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;


    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_CFID_JOURNAL_INTM_SUMM','');

    COMMIT;
    /******************************************************************************
    02. DELETE
    *******************************************************************************/
    EXECUTE IMMEDIATE 'truncate table TMP_CFID1';
    EXECUTE IMMEDIATE 'truncate table TMP_CFID2';

    COMMIT;

    /******************************************************************************
    03. INSERT INTO CF ID SUMM
    *******************************************************************************/
    DELETE /*+ PARALLEL(12) */ FROM IFRS_CFID_JOURNAL_INTM_SUMM WHERE DOWNLOAD_DATE=V_CURRDATE;COMMIT;


    INSERT /*+ PARALLEL(12) */ INTO TMP_CFID1(MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT)
    SELECT /*+ PARALLEL(12) */ MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT
    FROM IFRS_CFID_JOURNAL_INTM_SUMM
    WHERE DOWNLOAD_DATE=V_PREVDATE;COMMIT;

    COMMIT;


    INSERT /*+ PARALLEL(12) */ INTO TMP_CFID1(MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT)
    SELECT /*+ PARALLEL(12) */ MASTERID,CF_ID
    ,SUM(CASE WHEN JOURNALCODE2 IN('ITRCG','ITRCG_SL') THEN CASE WHEN REVERSE='N' THEN N_AMOUNT ELSE -1 * N_AMOUNT END ELSE 0 END)
    ,SUM(CASE WHEN JOURNALCODE2 IN ('ACCRU','ACCRU_SL') THEN CASE WHEN REVERSE='N' THEN N_AMOUNT ELSE -1 * N_AMOUNT END ELSE 0 END)
    FROM IFRS_ACCT_JOURNAL_INTM
    WHERE DOWNLOAD_DATE=V_CURRDATE
    GROUP BY MASTERID,CF_ID;

    COMMIT;


    INSERT /*+ PARALLEL(12) */ INTO TMP_CFID2(MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT)
    SELECT /*+ PARALLEL(12) */ MASTERID,CF_ID,SUM(ITRCG_AMT),SUM(AMORT_AMT)
    FROM TMP_CFID1
    GROUP BY MASTERID,CF_ID;

    COMMIT;


    INSERT /*+ PARALLEL(12) */ INTO IFRS_CFID_JOURNAL_INTM_SUMM(DOWNLOAD_DATE,MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT,UNAMORT_AMT,CREATEDDATE)
    SELECT /*+ PARALLEL(12) */ V_CURRDATE,MASTERID,CF_ID,ITRCG_AMT,AMORT_AMT,(ITRCG_AMT+AMORT_AMT),SYSTIMESTAMP
    FROM TMP_CFID2;

    COMMIT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_CFID_JOURNAL_INTM_SUMM','');

    COMMIT;

END;