CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_CFECF_GRP
AS
-- 20160412 GROUP BY CF_ID FOR MULTIPLE ROWS WITH SAME CF_ID
  V_CURRDATE DATE;
  V_PREVDATE DATE;


BEGIN
    SELECT MAX(CURRDATE)
        , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;


    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_CF_ECF';

    INSERT /*+ PARALLEL(8) */ INTO TMP_CF_ECF
    (ID1
    ,CF_ID
    ,FLAG_REV_ORI
    ,AMT
    )
    SELECT /*+ PARALLEL(8) */ MIN(A.ID) AS ID1
        ,A.CF_ID
        ,B.FLAG_REVERSE AS FLAG_REV_ORI
        ,SUM(CASE WHEN A.FLAG_REVERSE = 'N' THEN A.AMOUNT ELSE - 1 * A.AMOUNT END) AMT
    FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF A
    JOIN IFRS_ACCT_COST_FEE B ON B.ID = A.CF_ID
        AND B.MASTERID = A.MASTERID
    WHERE A.ECFDATE = V_CURRDATE
        AND A.STATUS = 'ACT'
        AND A.CREATEDBY <> 'EIR_SWITCH'
    GROUP BY A.CF_ID
        ,B.FLAG_REVERSE
    HAVING COUNT(*) > 1;

    COMMIT;

    MERGE /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_COST_FEE_ECF B
    USING TMP_CF_ECF A
    ON (B.ECFDATE = V_CURRDATE
        AND B.CF_ID = A.CF_ID
	AND B.STATUS = 'ACT'
       )
    WHEN MATCHED THEN
    UPDATE
    SET AMOUNT = CASE WHEN A.FLAG_REV_ORI = 'N' THEN CASE WHEN A.ID1 = B.ID THEN A.AMT ELSE 0 END
            ELSE CASE WHEN A.ID1 = B.ID THEN - 1 * A.AMT ELSE 0 END
            END
        ,AMOUNT_ORG = CASE WHEN A.FLAG_REV_ORI = 'N' THEN CASE WHEN A.ID1 = B.ID THEN A.AMT ELSE 0 END
            ELSE CASE  WHEN A.ID1 = B.ID THEN - 1 * A.AMT ELSE 0 END
            END
        ,FLAG_REVERSE = A.FLAG_REV_ORI;

    COMMIT;

    DELETE /*+ PARALLEL(8) */
    FROM IFRS_LBM_ACCT_EIR_COST_FEE_ECF
    WHERE ECFDATE = V_CURRDATE
        AND AMOUNT = 0;

    COMMIT;

END;