CREATE OR REPLACE PROCEDURE SP_IFRS_CCF_K_ORI
AS
    V_CURRDATE DATE;
    V_PREVDATE DATE;
BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_DATE_DAY1;
    SELECT ADD_MONTHS(CURRDATE,-12) INTO V_PREVDATE FROM IFRS_DATE_DAY1;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    SP_IFRS_INSERT_GTMP_FROM_IMA_M(V_CURRDATE, 'ILS,CRD');
    SP_IFRS_INSERT_GTMP_IMA_M_PREV(V_PREVDATE, 'ILS,CRD');

    COMMIT;

    DELETE IFRS_CCF_HEADER WHERE DOWNLOAD_DATE >= V_CURRDATE;               COMMIT;
    DELETE IFRS_CCF_DETAIL WHERE DOWNLOAD_DATE >= V_CURRDATE;               COMMIT;
    DELETE IFRS_CCF_DETAIL_PROCESS WHERE DOWNLOAD_DATE >= V_CURRDATE;       COMMIT;
    DELETE IFRS_CCF_DETAIL_UNPROCESS WHERE DOWNLOAD_DATE >= V_CURRDATE;     COMMIT;

    INSERT INTO IFRS_CCF_DETAIL
    (
        DOWNLOAD_DATE,
        CURRENT_DATE,
        ACCOUNT_NUMBER,
        CUSTOMER_NAME,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_STATUS,
        FIRST_NPL_DATE,
        OS_CUR,
        OS_PREV,
        LIMIT_CUR,
        LIMIT_PREV,
        REVOLVING_FLAG_L,
        PRODUCT_CODE_L,
        OS_SELISIH,
        LIMIT_SELISIH,
        CCF_RULE_ID,
        SEGMENTATION_ID
    )
    SELECT
        A.DOWNLOAD_DATE,
        A.DOWNLOAD_DATE,
        A.ACCOUNT_NUMBER,
        A.CUSTOMER_NAME,
        A.CUSTOMER_NUMBER,
        A.FACILITY_NUMBER,
        A.ACCOUNT_STATUS,
        A.RESERVED_DATE_3,
        A.OUTSTANDING,
        B.OUTSTANDING,
        A.PLAFOND,
        B.PLAFOND,
        A.REVOLVING_FLAG,
        A.PRODUCT_CODE,
        (NVL(A.OUTSTANDING,0) - NVL(B.OUTSTANDING,0))   AS OS_SELISIH,
        (NVL(A.PLAFOND,0) - NVL(B.OUTSTANDING,0))       AS LIMIT_SELISIH,
        C.PKID              AS CCF_RULE_ID,
        A.SEGMENT_RULE_ID   AS SEGMENTATION_ID
    FROM (SELECT DOWNLOAD_DATE, MASTERID, ACCOUNT_NUMBER, FACILITY_NUMBER, ACCOUNT_STATUS, RESERVED_DATE_3, OUTSTANDING, PLAFOND, REVOLVING_FLAG,
                             PRODUCT_CODE, CUSTOMER_NAME, CUSTOMER_NUMBER, CCF_RULE_ID, SEGMENT_RULE_ID FROM GTMP_IFRS_MASTER_ACCOUNT
        WHERE RESERVED_DATE_3 IS NOT NULL AND ACCOUNT_STATUS = 'A') A
    JOIN (SELECT DOWNLOAD_DATE, MASTERID, ACCOUNT_NUMBER, FACILITY_NUMBER, ACCOUNT_STATUS, RESERVED_DATE_3, OUTSTANDING, PLAFOND, REVOLVING_FLAG,
                             PRODUCT_CODE, CUSTOMER_NAME, CUSTOMER_NUMBER, CCF_RULE_ID, SEGMENT_RULE_ID FROM GTMP_IFRS_MASTER_ACCOUNT_PREV
        WHERE RESERVED_DATE_3 IS NULL AND ACCOUNT_STATUS = 'A') B
    ON A.MASTERID = B.MASTERID
    JOIN IFRS_CCF_RULES_CONFIG C
    ON B.CCF_RULE_ID = C.PKID;

    COMMIT;

    INSERT INTO IFRS_CCF_DETAIL_PROCESS
    (
         PKID,
         DOWNLOAD_DATE,
         CURRENT_DATE,
         PREVIOUS_DATE,
         FACILITY_NUMBER,
         ACCOUNT_STATUS,
         SEGMENTATION_ID,
         FIRST_NPL_DATE,
         OS_CUR,
         OS_PREV,
         LIMIT_CUR,
         LIMIT_PREV,
         USED_AMOUNT_CUR,
         USED_AMOUNT_PREV,
         AVAILABLE_AMT_CUR,
         AVAILABLE_AMT_PREV,
         REVOLVING_FLAG_L,
         REVOLVING_FLAG_I,
         PRODUCT_CODE_L,
         PRODUCT_CODE_I,
         CCF_RULE_ID
    )
    SELECT
        0,
        DOWNLOAD_DATE,
        CURRENT_DATE,
        PREVIOUS_DATE,
        FACILITY_NUMBER,
        ACCOUNT_STATUS,
        SEGMENTATION_ID,
        FIRST_NPL_DATE,
        SUM (OS_CUR),
        SUM (OS_PREV),
        LIMIT_CUR,
        LIMIT_PREV,
        USED_AMOUNT_CUR,
        USED_AMOUNT_PREV,
        AVAILABLE_AMT_CUR,
        AVAILABLE_AMT_PREV,
        REVOLVING_FLAG_L,
        REVOLVING_FLAG_I,
        PRODUCT_CODE_L,
        PRODUCT_CODE_I,
        CCF_RULE_ID
    FROM IFRS_CCF_DETAIL
    WHERE DOWNLOAD_DATE = V_CURRDATE AND FACILITY_NUMBER NOT IN (SELECT NVL(FACILITY_NUMBER,0) FROM IFRS_CCF_DETAIL_PROCESS)
          AND PRODUCT_CODE_L <> 'CARDS' AND FIRST_NPL_DATE = DOWNLOAD_DATE
    GROUP BY
        DOWNLOAD_DATE,
        "CURRENT_DATE",
        PREVIOUS_DATE,
        FACILITY_NUMBER,
        ACCOUNT_STATUS,
        SEGMENTATION_ID,
        FIRST_NPL_DATE,
        LIMIT_CUR,
        LIMIT_PREV,
        USED_AMOUNT_CUR,
        USED_AMOUNT_PREV,
        AVAILABLE_AMT_CUR,
        AVAILABLE_AMT_PREV,
        REVOLVING_FLAG_L,
        REVOLVING_FLAG_I,
        PRODUCT_CODE_L,
        PRODUCT_CODE_I,
        CCF_RULE_ID;
    COMMIT;

    INSERT INTO IFRS_CCF_DETAIL_PROCESS
        (
             PKID,
             DOWNLOAD_DATE,
             CURRENT_DATE,
             PREVIOUS_DATE,
             FACILITY_NUMBER,
             ACCOUNT_STATUS,
             SEGMENTATION_ID,
             CCF_RULE_ID,
             FIRST_NPL_DATE,
             OS_CUR,
             OS_PREV,
             LIMIT_CUR,
             LIMIT_PREV,
             USED_AMOUNT_CUR,
             USED_AMOUNT_PREV,
             AVAILABLE_AMT_CUR,
             AVAILABLE_AMT_PREV,
             REVOLVING_FLAG_L,
             REVOLVING_FLAG_I,
             PRODUCT_CODE_L,
             PRODUCT_CODE_I
        )
        SELECT
            0,
            DOWNLOAD_DATE,
            CURRENT_DATE,
            PREVIOUS_DATE,
            ACCOUNT_NUMBER,
            ACCOUNT_STATUS,
            SEGMENTATION_ID,
            CCF_RULE_ID,
            FIRST_NPL_DATE,
            SUM (OS_CUR),
            SUM (OS_PREV),
            LIMIT_CUR,
            LIMIT_PREV,
            USED_AMOUNT_CUR,
            USED_AMOUNT_PREV,
            AVAILABLE_AMT_CUR,
            AVAILABLE_AMT_PREV,
            REVOLVING_FLAG_L,
            REVOLVING_FLAG_I,
            PRODUCT_CODE_L,
            PRODUCT_CODE_I
        FROM IFRS_CCF_DETAIL
        WHERE DOWNLOAD_DATE = V_CURRDATE AND ACCOUNT_NUMBER NOT IN (SELECT NVL(FACILITY_NUMBER,0) FROM IFRS_CCF_DETAIL_PROCESS)
              AND PRODUCT_CODE_L = 'CARDS' AND FIRST_NPL_DATE = DOWNLOAD_DATE
        GROUP BY
            DOWNLOAD_DATE,
            "CURRENT_DATE",
            PREVIOUS_DATE,
            ACCOUNT_NUMBER,
            ACCOUNT_STATUS,
            SEGMENTATION_ID,
            CCF_RULE_ID,
            FIRST_NPL_DATE,
            LIMIT_CUR,
            LIMIT_PREV,
            USED_AMOUNT_CUR,
            USED_AMOUNT_PREV,
            AVAILABLE_AMT_CUR,
            AVAILABLE_AMT_PREV,
            REVOLVING_FLAG_L,
            REVOLVING_FLAG_I,
            PRODUCT_CODE_L,
            PRODUCT_CODE_I,
            CCF_RULE_ID;
        COMMIT;



    UPDATE IFRS_CCF_DETAIL_PROCESS
    SET OS_SELISIH = CASE WHEN (OS_CUR - OS_PREV) < 0 THEN 0 ELSE OS_CUR - OS_PREV END,
        LIMIT_SELISIH = LIMIT_CUR - OS_PREV
        WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    INSERT INTO IFRS_CCF_DETAIL_UNPROCESS
    SELECT *
      FROM IFRS_CCF_DETAIL_PROCESS
      WHERE DOWNLOAD_DATE = V_CURRDATE
            AND
            (
              (LIMIT_CUR - OS_PREV) <= 0
              --OR OS_CUR > LIMIT_CUR
              OR OS_PREV > LIMIT_CUR
            );
    COMMIT;

    DELETE IFRS_CCF_DETAIL_PROCESS
    WHERE DOWNLOAD_DATE = V_CURRDATE
         AND (
               (LIMIT_CUR - OS_PREV) <= 0
               --OR OS_CUR > LIMIT_CUR
               OR OS_PREV > LIMIT_CUR
            );
    COMMIT;

    INSERT INTO IFRS_CCF_DETAIL_UNPROCESS
        SELECT * FROM IFRS_CCF_DETAIL_PROCESS
        WHERE DOWNLOAD_DATE = V_CURRDATE
          AND (LIMIT_SELISIH < 0);
    COMMIT;

    DELETE IFRS_CCF_DETAIL_PROCESS
        WHERE DOWNLOAD_DATE = V_CURRDATE
        AND (LIMIT_SELISIH < 0);
    COMMIT;

    UPDATE IFRS_CCF_DETAIL_PROCESS
      SET CCF_RESULT =
                CASE WHEN (OS_CUR - OS_PREV)/(NVL(LIMIT_CUR,0) - OS_PREV) > 1 THEN 1
                     WHEN (OS_CUR - OS_PREV)/(NVL(LIMIT_CUR,0) - OS_PREV) < 0 THEN 0
                     ELSE (OS_CUR - OS_PREV)/(NVL(LIMIT_CUR,0) - OS_PREV) END
      WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    UPDATE IFRS_CCF_DETAIL_PROCESS
           SET CCF_RESULT =
                    CASE WHEN (OS_CUR - OS_PREV) <= 0 THEN 0
                         ELSE CCF_RESULT END
          WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;


    INSERT INTO IFRS_CCF_HEADER
    (
         PKID,
         DOWNLOAD_DATE,
         --SEGMENTATION,
         SEGMENTATION_ID,
         CCF_RULE_ID,
         CCF_RATE,
         AVERAGE_METHOD
    )
    SELECT
          0,
          V_CURRDATE,
          A.SEGMENTATION_ID,
          A.CCF_RULE_ID,
          CASE WHEN B.AVERAGE_METHOD = 'Simple'
                THEN C1 ELSE C2
          END,
          B.AVERAGE_METHOD
    FROM (
              SELECT
                    SEGMENTATION_ID,
                    CCF_RULE_ID,
                    C1,C2
                    FROM
                    (
                            SELECT
                              SEGMENTATION_ID,
                              CCF_RULE_ID,
                              AVG(CCF_RESULT) C1,
                              (SUM(OS_CUR-OS_PREV))/(SUM(LIMIT_CUR-OS_PREV)) C2
                            FROM IFRS_CCF_DETAIL_PROCESS
                            GROUP BY SEGMENTATION_ID, CCF_RULE_ID
                    )
                    GROUP BY SEGMENTATION_ID, CCF_RULE_ID,C1,C2
           ) A
           JOIN IFRS_CCF_RULES_CONFIG B
                ON A.CCF_RULE_ID = B.PKID
                AND V_CURRDATE >= B.CUT_OFF_DATE;
    COMMIT;
END;