CREATE OR REPLACE PROCEDURE SP_IFRS_MOVEMENT_EOM AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_SPNAME   VARCHAR2(150);
BEGIN

--  IF v_DOWNLOADDATECUR = '1-JAN-1900'
--  THEN
--    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
--  ELSE
--    V_CURRDATE := v_DOWNLOADDATECUR;
--  END IF;
--
--  IF v_DOWNLOADDATEPREV = '1-JAN-1900'
--  THEN
--    SELECT LAST_DAY(ADD_MONTHS(MAX(PREVDATE), -1)) INTO V_PREVDATE FROM IFRS_PRC_DATE;
--  ELSE
--    V_PREVDATE := v_DOWNLOADDATEPREV;
--  END IF;

  SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;

  SELECT LAST_DAY(ADD_MONTHS(MAX(PREVDATE), -1)) INTO V_PREVDATE FROM IFRS_PRC_DATE;

  V_SPNAME := 'SP_IFRS_REPORT_ECL_MOVEMENT(''' || TO_CHAR(V_CURRDATE, 'DD-MON-RRRR') || '''' || ',' || '''' || TO_CHAR(V_CURRDATE, 'DD-MON-RRRR') || '''' || ')';
  SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'JRNL', 'Y');

  V_SPNAME := 'SP_IFRS_REPORT_ECL_MOVE_VALAS(''' || TO_CHAR(V_CURRDATE, 'DD-MON-RRRR') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'DD-MON-RRRR') || '''' || ')';
  SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'JRNL', 'Y');

--   V_SPNAME := 'IFRS9_REPORT.SP_IFRS_PRC_REPORT';
--   SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'JRNL', 'Y');

END;