CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MAA_FLOWRATE
AS
    v_CURRDATE date;
BEGIN
	SELECT CURRDATE
	INTO v_CURRDATE
	FROM IFRS_PRC_DATE;

	-- =================
	-- Get PD Rule ID
	-- =================
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        PD_RULE_ID,
        BUCKET_GROUP,
        HISTORICAL_DATA,
        POPULATION_MONTH,
        EFF_DATE,
        BASE_DATE
	)
	SELECT A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.HISTORICAL_DATA,
		A.POPULATION_MONTH,
		v_CURRDATE AS EFF_DATE,
		LAST_DAY(ADD_MONTHS(v_CURRDATE, A.INCREMENT_PERIOD * -1)) AS BASE_DATE
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MAA'
	AND A.DERIVED_PD_MODEL IS NULL;

	COMMIT;

	DELETE IFRS_PD_MAA_FLOWRATE
	WHERE EFF_DATE = v_CURRDATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

    COMMIT;

	-- =========================
	-- Get Percentage from ENR
	-- =========================
	INSERT INTO IFRS_PD_MAA_FLOWRATE
	(
        EFF_DATE,
		BASE_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_FROM,
		BUCKET_TO,
		FLOWRATE
	)
   SELECT DISTINCT
        A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        A.BUCKET_GROUP,
        A.BUCKET_FROM,
        A.BUCKET_TO,
        CASE WHEN B.TOTAL = 0 THEN
            0
--        WHEN A.BUCKET_FROM = D.MAX_BUCKET_ID AND A.BUCKET_TO = D.MAX_BUCKET_ID THEN
--            1
        ELSE
            CAST(A.CALC_AMOUNT AS FLOAT) / CAST(B.TOTAL AS FLOAT)
        END FLOWRATE
    FROM IFRS_PD_MAA_ENR A
    JOIN
        (
            SELECT PD_RULE_ID,
                BUCKET_FROM,
                SUM(CALC_AMOUNT) AS TOTAL
            FROM IFRS_PD_MAA_ENR
            WHERE EFF_DATE = v_CURRDATE
            GROUP BY PD_RULE_ID, BUCKET_FROM
        ) B
    ON A.PD_RULE_ID = B.PD_RULE_ID
        AND A.BUCKET_FROM = B.BUCKET_FROM
    JOIN TMP_IFRS_PD_RUNNING_DATE C
    ON A.PD_RULE_ID = C.PD_RULE_ID
        AND A.EFF_DATE = C.EFF_DATE
--    JOIN VW_IFRS_MAX_BUCKET D
--    ON A.BUCKET_GROUP = D.BUCKET_GROUP
    WHERE A.BUCKET_TO > 0
    ORDER BY A.PD_RULE_ID, A.BUCKET_FROM, A.BUCKET_TO;

    COMMIT;

END;