CREATE OR REPLACE PROCEDURE SP_IFRS_PD_VAS_CORRELATION(V_EFF_DATE DATE)
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

	-- GET PD_RULE_ID FOR VASICEK METHOD
	INSERT INTO TMP_IFRS_PD_RUNNING_DATE
	(
        EFF_DATE,
        PD_RULE_ID,
        BUCKET_GROUP
	)
	SELECT
	    v_EFF_DATE AS EFF_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP
	FROM IFRS_PD_RULES_CONFIG A
	WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='VAS'
	AND DERIVED_PD_MODEL IS NULL;

	COMMIT;

	DELETE IFRS_PD_VAS_CORRELATION
	WHERE EFF_DATE = v_EFF_DATE
	AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

	COMMIT;

	INSERT INTO IFRS_PD_VAS_CORRELATION
	(
		EFF_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_ID,
		ASSET_CORRELATION
	)
	SELECT EFF_DATE,
		PD_RULE_ID,
		BUCKET_GROUP,
		BUCKET_ID,
		0.12*(1-EXP(-50*PD))/(1-EXP(-50))+0.24*(1-(1-EXP(-50*PD))/(1-EXP(-50))) ASSET_CORRELATION
	FROM IFRS_PD_VAS
	WHERE EFF_DATE = v_EFF_DATE;

	COMMIT;
END;