CREATE OR REPLACE PROCEDURE     SP_IFRS_LI_ACCT_CLOSED
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;

BEGIN
    SELECT MAX(CURRDATE)
        , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_LI_PRC_DATE_AMORT;

    INSERT INTO IFRS_LI_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LI_ACCT_CLOSED','');

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LI_ACCT';

    INSERT INTO TMP_LI_ACCT (MASTERID)
    SELECT A.MASTERID
    FROM IFRS_LI_IMA_AMORT_CURR A
    LEFT JOIN IFRS_LI_IMA_AMORT_PREV B ON A.MASTERID = B.MASTERID
    WHERE B.MASTERID IS NULL;

    COMMIT;

    INSERT INTO IFRS_LI_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LI_ACCT_CLOSED ACCTSTATUS','');

    INSERT INTO IFRS_LI_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LI_ACCT_CLOSED CLS','');

    COMMIT;

    -- INSERT ACCOUNT CLOSED
    DELETE FROM IFRS_LI_ACCT_CLOSED
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    --ADDING 20170227 TO GET EIR ACCOUNT
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LI_T1';

    COMMIT;

    --GET EIR ACCOUNT
    INSERT INTO TMP_LI_T1 (MASTERID)
    SELECT DISTINCT MASTERID FROM IFRS_LI_IMA_AMORT_CURR WHERE AMORT_TYPE = 'EIR'
    UNION
    SELECT DISTINCT MASTERID FROM IFRS_LI_IMA_AMORT_PREV WHERE AMORT_TYPE = 'EIR'
    ;

    /*END ADDING 20170227*/
    --AMORT TYPE EIR
    INSERT INTO IFRS_LI_ACCT_CLOSED (
        FACNO
        ,CIFNO
        ,DATASOURCE
        ,DOWNLOAD_DATE
        ,MASTERID
        ,ACCTNO
        )
    SELECT A.FACILITY_NUMBER
        ,A.CUSTOMER_NUMBER
        ,A.DATA_SOURCE
        ,V_CURRDATE
        ,A.MASTERID
        ,A.ACCOUNT_NUMBER
    FROM IFRS_LI_IMA_AMORT_CURR A
    INNER JOIN TMP_LI_T1 C ON A.MASTERID = C.MASTERID
    WHERE (A.WRITEOFF_FLAG = 'Y' OR A.ACCOUNT_STATUS = 'W')
        OR (A.ACCOUNT_STATUS IN ('C','E','CE','CT','CN'))
        OR (A.OUTSTANDING <= 0)
        OR (A.LOAN_DUE_DATE <= V_CURRDATE);

    COMMIT;

    --ADDING 20170227 TO GET SL ACCOUNT
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LI_T1';

    --GET SL ACCOUNT
    INSERT INTO TMP_LI_T1 (MASTERID)
    SELECT DISTINCT MASTERID FROM IFRS_LI_IMA_AMORT_CURR WHERE AMORT_TYPE = 'SL'
    UNION
    SELECT DISTINCT MASTERID FROM IFRS_LI_IMA_AMORT_PREV WHERE AMORT_TYPE = 'SL'
    ;

    /*END ADDING 20170227*/
    --AMORT TYPE SL
    INSERT INTO IFRS_LI_ACCT_CLOSED (
        FACNO
        ,CIFNO
        ,DATASOURCE
        ,DOWNLOAD_DATE
        ,MASTERID
        ,ACCTNO
        )
    SELECT A.FACILITY_NUMBER
        ,A.CUSTOMER_NUMBER
        ,A.DATA_SOURCE
        ,V_CURRDATE
        ,A.MASTERID
        ,A.ACCOUNT_NUMBER
    FROM IFRS_LI_IMA_AMORT_CURR A
    INNER JOIN TMP_LI_T1 C ON A.MASTERID = C.MASTERID
    WHERE (A.WRITEOFF_FLAG = 'Y' OR A.ACCOUNT_STATUS = 'W')
        OR (A.ACCOUNT_STATUS IN ('C','E','CE','CT','CN'))
        OR (A.LOAN_DUE_DATE <= V_CURRDATE);

    COMMIT;

    --ACCOUNT HILANG
    INSERT INTO IFRS_LI_ACCT_CLOSED (
        FACNO
        ,CIFNO
        ,DATASOURCE
        ,DOWNLOAD_DATE
        ,MASTERID
        ,ACCTNO
        )
    SELECT A.FACILITY_NUMBER
        ,A.CUSTOMER_NUMBER
        ,A.DATA_SOURCE
        ,V_CURRDATE
        ,A.MASTERID
        ,A.ACCOUNT_NUMBER
    FROM IFRS_LI_IMA_AMORT_PREV A
    LEFT JOIN IFRS_LI_IMA_AMORT_CURR B ON A.MASTERID = B.MASTERID
    WHERE B.MASTERID IS NULL;

    --CLOSE PROGRAM FUNDING
	INSERT INTO IFRS_LI_ACCT_CLOSED
	(
		FACNO
		,CIFNO
		,DATASOURCE
		,DOWNLOAD_DATE
		,MASTERID
		,ACCTNO
	)
	SELECT
		 A.FACNO
		,A.CIFNO
		,A.DATASOURCE
		,V_CURRDATE
		,A.MASTERID
		,A.ACCTNO
	FROM IFRS_LI_ACCT_COST_FEE A
	JOIN IFRS_LI_STG_TRANSACTION_DAILY B
	ON A.TRX_REFF_NUMBER = B.TRANSACTION_REFERENCE_NUMBER
	AND B.DOWNLOAD_DATE = V_CURRDATE
	AND B.TERMINATE_FLAG = 'Y'
	AND A.STATUS = 'ACT';

	COMMIT;

    -- PNL SISA UNAMORT IF IFRS9 CLASS FVTPL
	INSERT INTO IFRS_LI_ACCT_CLOSED (
		FACNO
		,CIFNO
		,DATASOURCE
		,DOWNLOAD_DATE
		,MASTERID
		,ACCTNO
		)
	SELECT A.FACILITY_NUMBER
		,A.CUSTOMER_NUMBER
		,A.DATA_SOURCE
		,V_CURRDATE
		,A.MASTERID
		,A.ACCOUNT_NUMBER
	FROM IFRS_LI_IMA_AMORT_CURR A
	WHERE A.IFRS9_CLASS = 'FVTPL'
	AND A.DOWNLOAD_DATE = V_CURRDATE;

    INSERT INTO IFRS_LI_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LI_ACCT_CLOSED','');

    COMMIT;

END;