CREATE OR REPLACE PROCEDURE SP_IFRS_IA_SEQUENCE (v_UploadId IN number, v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
BEGIN
    SP_IFRS_INITIAL_IA_OVERRIDE(v_uploadId);
    SP_IFRS_INSERT_IA_OVERRIDE(v_uploadId, v_DOWNLOADDATE);
    SP_IFRS_INSERT_DCF(v_uploadId);
    SP_IFRS_DCF_CALCULATION(v_uploadId);
END;