CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_WOPERIOD
AS

BEGIN

    ---TRUNCATE TABLE IFRS_LGD_WO_PERIOD
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_LGD_WOPERIOD';
    COMMIT;

    ---INSERT CLOSED DATE WO PERIOD
    INSERT INTO TMP_LGD_WOPERIOD (ACCOUNT_NUMBER,NPL_DATE,CLOSED_DATE)
    SELECT
        ACCOUNT_NUMBER,
        NPL_DATE,
        MAX(CASE WHEN ACCOUNT_STATUS='C' THEN CLOSED_DATE ELSE RECOVERY_DATE END) CLOSED_DATE
    FROM IFRS_LGD_PROCESS A
        LEFT JOIN IFRS_LGD_RULES_CONFIG B ON A.SEGMENTATION_ID=B.SEGMENTATION_ID
            AND A.LGD_RULE_ID=B.PKID
    WHERE
             TO_CHAR(RECOVERY_DATE,'MM-YYYY') BETWEEN  TO_CHAR(NPL_DATE,'MM-YYYY')
             AND TO_CHAR(ADD_MONTHS(NPL_DATE,CASE WHEN B.WORKOUT_PERIOD	!=0 THEN 12 * WORKOUT_PERIOD ELSE 0 END ),'MM-YYYY')
    GROUP BY ACCOUNT_NUMBER,NPL_DATE,CLOSED_DATE;
    COMMIT;

    ---TRUNCATE TABLE IFRS_LGD_WO_PERIOD
    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LGD_WOPERIOD';
    COMMIT;

    ---INSERT LGD_WO_PERIOD
    INSERT INTO IFRS_LGD_WOPERIOD(DOWNLOAD_DATE,
            PRODUCT_CODE,
            PRODUCT_NAME,
            MASTER_ID,
            ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            LGD_CUSTOMER_TYPE,
            SEGMENTATION_ID,
            SEGMENTATION_NAME,
            CURRENCY,
            ORIGINAL_CURRENCY,
            NPL_DATE,
            CLOSED_DATE,
            BI_COLLECTABILITY_NPL,
            BI_COLLECTABILITY_CLOSED,
            RECOV_AMT_BF_NPV,
            LAST_RECOV_DATE,
            RECOV_PERCENTAGE,
            TOTAL_LOSS_AMT,
            DISCOUNT_RATE,
            RECOVERY_AMOUNT,
            LOSS_RATE,
            DATA_SOURCE	 )
    SELECT  DOWNLOAD_DATE,
            PRODUCT_CODE,
            PRODUCT_NAME,
            MASTER_ID,
            A.ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            LGD_CUSTOMER_TYPE,
            A.SEGMENTATION_ID,
            A.SEGMENTATION_NAME,
            CURRENCY,
            ORIGINAL_CURRENCY,
            MIN(A.NPL_DATE) NPL_DATE,
            B.CLOSED_DATE,
            BI_COLLECTABILITY_NPL,
            BI_COLLECTABILITY_CLOSED,
            SUM(REC_AMOUNT) RECOV_AMT_BF_NPV,
            MAX(RECOVERY_DATE) LAST_RECOV_DATE,
            ROUND(SUM(REC_AMOUNT)/TOTAL_LOSS_AMT,4)*100 AS RECOV_PERCENTAGE,
            TOTAL_LOSS_AMT,
            DISCOUNT_RATE,
            SUM(REC_AMOUNT) AS RECOVERY_AMOUNT,
            100-ROUND(SUM(REC_AMOUNT)/TOTAL_LOSS_AMT,4)*100 LOSS_RATE,
            DATA_SOURCE
    FROM IFRS_LGD_PROCESS A
        INNER JOIN TMP_LGD_WOPERIOD B ON A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
        LEFT JOIN IFRS_LGD_RULES_CONFIG C ON A.SEGMENTATION_ID=C.SEGMENTATION_ID
            AND A.LGD_RULE_ID=C.PKID
    WHERE
          TO_CHAR(RECOVERY_DATE,'MM-YYYY') BETWEEN  TO_CHAR(A.NPL_DATE,'MM-YYYY')
          AND TO_CHAR(ADD_MONTHS(A.NPL_DATE,CASE WHEN C.WORKOUT_PERIOD!=0 THEN 12 * C.WORKOUT_PERIOD ELSE 0 END ),'MM-YYYY')
    GROUP BY DOWNLOAD_DATE,
            PRODUCT_CODE,
            PRODUCT_NAME,
            MASTER_ID,
            A.ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            ACCOUNT_STATUS,
            CUSTOMER_NAME,
            LGD_CUSTOMER_TYPE,
            A.SEGMENTATION_ID,
            A.SEGMENTATION_NAME,
            CURRENCY,
            ORIGINAL_CURRENCY,
            B.CLOSED_DATE,
            BI_COLLECTABILITY_NPL,
            BI_COLLECTABILITY_CLOSED,
            TOTAL_LOSS_AMT,
            DISCOUNT_RATE,
            DATA_SOURCE;
    COMMIT;
END;