CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_RECOVERY_RATE
AS
BEGIN
    INSERT INTO IFRS_LGD_RECOVERY_RATE
        ("DATE",DEAL_TYPE,DEAL_ID,CUSTOMER_NR,CUSTOMER_NAME,SEGMENTASI,CURRENCY,LOSS_DATE,CLOSED_DATE,TOTAL_LOSS_AMT,LAST_RECOV_DATE,
        DISCOUNT_RATE,RECOVERY_AMT,RECOV_AMT_BF_NPV,RECOV_PERCENTAGE,LOSS_RATE)
    SELECT MIN(LOSS_DATE) AS "DATE",DEAL_TYPE,DEAL_ID,CUSTOMER_NR,CUSTOMER_NAME,SEGMENTASI,CURRENCY,MIN(LOSS_DATE) LOSS_DATE,
            MAX(RECOVERY_DATE) CLOSED_DATE, TOTAL_LOSS_AMT,
            MAX(RECOVERY_DATE) LAST_RECOV_DATE,DISCOUNT_RATE,
            SUM(REC_AMOUNT) AS RECOVERY_AMT,
            SUM(REC_AMOUNT) RECOV_AMT_BF_NPV,
            ROUND(SUM(REC_AMOUNT)/TOTAL_LOSS_AMT,4)*100 AS RECOV_PERCENTAGE,
            100-ROUND(SUM(REC_AMOUNT)/TOTAL_LOSS_AMT,4)*100 LOSS_RATE
    FROM (
        SELECT
            A."DATE",
            A.DEAL_TYPE,
            A.DEAL_NAME,
            A.DEAL_ID,
            A.CUSTOMER_NR,
            A.CUSTOMER_NAME,
            A.CUSTOMER_TYPE SEGMENTASI,
            A.POOL_ID,
            A.POOL_DESC,
            A.CURRENCY,
            A.ORIGINAL_CURRENCY,
            A.LOSS_DATE,
            A.CLOSED_DATE,
            A.DS_AT_LOSS_DATE,
            A.DS_AT_CLOSED_DATE,
            A.TOTAL_LOSS_AMT,
            B.RECOVERY_AMOUNT,  ---
            B.RECOVERY_DATE,
            A.DISCOUNT_RATE DISCOUNT_RATE,
            FN_LGD_DAYS_30_360 (A.LOSS_DATE,B.RECOVERY_DATE)/360 DAILY_BASIS,
            (RECOVERY_AMOUNT/POWER((1+DISCOUNT_RATE),
                FN_LGD_DAYS_30_360 (A.LOSS_DATE,B.RECOVERY_DATE)/360)
            )
            REC_AMOUNT
        FROM TEST_LGD_RESULT A
        LEFT JOIN TEST_LGD_RECOV B
        ON A.DEAL_ID=B.RECOV_EXT_REF
        ORDER BY "DATE",DEAL_TYPE,DEAL_ID
    )AA
    GROUP BY DEAL_TYPE,DEAL_ID,CUSTOMER_NR,CUSTOMER_NAME,SEGMENTASI,CURRENCY,TOTAL_LOSS_AMT,DISCOUNT_RATE;
    COMMIT;
END;