CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_ROUND NUMBER(10);
  V_FUNCROUND NUMBER(10);

BEGIN

    SELECT MAX(CURRDATE)
        , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','');
    COMMIT;


    SELECT CAST(VALUE1 AS NUMBER(10))
        , CAST(VALUE2 AS NUMBER(10)) INTO V_ROUND, V_FUNCROUND
    FROM TBLM_COMMONCODEDETAIL
    WHERE COMMONCODE = 'SCM003';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T8';

    INSERT /*+ PARALLEL(8) */ INTO TMP_T8 (
        MASTERID
        ,DTMAX
        ,CURRDATE
        )
    SELECT /*+ PARALLEL(8) */ MASTERID
        ,MAX(PMT_DATE) DTMAX
        ,V_CURRDATE
    FROM IFRS_LBM_ACCT_EIR_ECF
    WHERE DOWNLOAD_DATE = V_CURRDATE
        /*NAMBAHIN KONDISI UNTUK CASE ACCT SWITCH 20180115*/
        AND AMORTSTOPDATE IS NULL
    GROUP BY MASTERID;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','TMP T8 PREPARED');
    COMMIT;


    MERGE /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_ECF A
    USING TMP_T8 B
    ON (  A.MASTERID = B.MASTERID
        AND B.DTMAX = A.PMT_DATE
        AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET N_UNAMORT_AMT = 0
        ,N_COST_UNAMORT_AMT = 0
        ,N_FEE_UNAMORT_AMT = 0
        ,N_AMORT_AMT = - 1 * N_UNAMORT_AMT_PREV
        ,N_COST_AMORT_AMT = - 1 * N_COST_UNAMORT_AMT_PREV
        ,N_FEE_AMORT_AMT = - 1 * N_FEE_UNAMORT_AMT_PREV
        ,N_FAIRVALUE = 0;
    COMMIT;

    /*PINDAHAN DARI ATAS 20160428*/
    UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_ECF
    SET N_DAILY_AMORT_COST = ROUND(CASE
                WHEN I_DAYS2 = 0 THEN 0
                ELSE N_COST_AMORT_AMT / CAST(I_DAYS2 AS NUMBER(32, 6))
                END, V_ROUND)
        ,N_DAILY_AMORT_FEE = ROUND(CASE
                WHEN I_DAYS2 = 0 THEN 0
                ELSE N_FEE_AMORT_AMT / CAST(I_DAYS2 AS NUMBER(32, 6))
                END, V_ROUND)
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','DAILY AMORT UPDATED');
    COMMIT;

    /*PINDAHAN DARI ATAS 20160428*/
    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','MERGE ALIGN DONE');
    COMMIT;

    -- UPDATE ENDAMORTDATE TO MAX PMTDATE
    MERGE /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_ECF A
    USING TMP_T8 B
    ON (A.MASTERID = B.MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET ENDAMORTDATE = B.DTMAX;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','MERGE ENDAMORTDATE DONE');
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_ECF_ALIGN','');
    COMMIT;

END;