CREATE OR REPLACE PROCEDURE SP_IFRS_LI_AMORT_SEQUENCE
AS

	V_CURRDATE DATE;
	V_PREVDATE DATE;
	V_SPNAME VARCHAR2(100);
	V_SESSIONID VARCHAR2(100);
	V_ERRM VARCHAR2(255);

    BEGIN

	V_SESSIONID := SYS_GUID();

	SELECT  CURRDATE ,
			PREVDATE INTO V_CURRDATE, V_PREVDATE
	FROM IFRS_LI_PRC_DATE_AMORT;

	DELETE FROM IFRS_LI_AMORT_LOG
	WHERE DOWNLOAD_DATE = V_CURRDATE;

	COMMIT;

	DELETE FROM IFRS_STATISTIC
	WHERE DOWNLOAD_DATE = V_CURRDATE
	AND PRC_NAME = 'AMT';

    COMMIT;

	INSERT  INTO IFRS_LI_AMORT_LOG  ( DOWNLOAD_DATE ,DTM , OPS , PROCNAME ,REMARK )
    VALUES  (V_CURRDATE ,SYSTIMESTAMP , 'START' , 'SP_IFRS_LI_AMORT_SEQUENCE' , '' );

	COMMIT;

	V_SPNAME := 'SP_IFRS_LI_RESET_AMT_PRC';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_SYNC_PRODUCT_PARAM';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_SYNC_TRANS_PARAM';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_SYNC_JOURNAL_PARAM';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_FILL_IMA_FROM_PREV' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','N');

	--sementara jalanin dari sequence dulu
	V_SPNAME := 'SP_IFRS_LI_SYNC_MASTER_ID' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--sementara jalanin dari sequence dulu
	V_SPNAME := 'SP_IFRS_LI_SYNC_MASTER_ACCOUNT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--sementara jalanin dari sequence dulu
	V_SPNAME := 'SP_IFRS_LI_SYNC_TRANSACTION_DAILY' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--sementara jalanin dari sequence dulu
	V_SPNAME := 'SP_IFRS_LI_COPY_ACCOUNT_DUMMY' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--sementara jalanin dari sequence dulu
	V_SPNAME := 'SP_IFRS_LI_SYNC_UPLOAD_TRAN_DAILY' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_INITIAL_UPDATE';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_FILL_IMA_PREV_CURR' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_ACCT_CLOSED';
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_PROCESS_TRAN_DAILY' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_COST_FEE_STATUS' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_COST_FEE_SUMM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SWITCH' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_SWITCH' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_SWITCH' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	-- EIR ENGINE
	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_ACF_PMTDT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_ECF_EVENT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	-- Generate Payment Schedule
	 V_SPNAME := 'SP_IFRS_LI_PAYM_SCHD' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','N');

	 V_SPNAME := 'SP_IFRS_LI_PAYM_SCHD_FUNDING' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	-- ADD CTBC
	-- MARKET TO MARKET
	V_SPNAME := 'SP_IFRS_LI_PAYM_SCHD_MTM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','N');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_ECF_MAIN' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

/*
-- staffloan tidak ada diliab by adam
	SET @V_SPNAME = 'SP_IFRS_LI_STAFF_BENEFIT_SUMM' ;
	EXEC SP_IFRS_LI_EXEC_AND_LOG @V_SPNAME, 'AMT'
*/

	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_ACF_ACRU' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_UPD_ACRU' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_LAST_ACF' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_JRNL_INTM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	--SL ENGINE
	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_ACF_PMTDATE' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_ECF_EVENT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_ECF_MAIN' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_ACF_ACCRU' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_UPD_ACRU' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_LAST_ACF' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	-- update unamortized pma SL then EIR
	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_UPD_UNAMRT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_SL_JRNL_INTM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_ACCT_EIR_UPD_UNAMRT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	-- JOURNAL SUMMARY
	V_SPNAME := 'SP_IFRS_LI_ACCT_JRNL_INTM_SUMM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_CFID_JRNL_INTM_SUMM' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	V_SPNAME := 'SP_IFRS_LI_JRNL_ACF_ABN_ADJ' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--JOURNAL DATA
	V_SPNAME := 'SP_IFRS_LI_ACCT_JOURNAL_DATA' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	--GL OUTBOUND
	V_SPNAME := 'SP_IFRS_LI_GL_OUTBOUND' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	--IFRS RECON REPORT  20180501
	V_SPNAME := 'SP_IFRS_LI_REPORT_RECON' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--[SP_IFRS_LI_NOMINATIF]  20180501
	V_SPNAME := 'SP_IFRS_LI_NOMINATIF' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--CHECK AMORT
	V_SPNAME := 'SP_IFRS_LI_CHECK_AMORT' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');

	--CHECK AMORT NO CF
	V_SPNAME := 'SP_IFRS_LI_CHECK_AMORT_NOCF' ;
	SP_IFRS_LI_EXEC_AND_LOG(V_SPNAME, 'AMT','Y');


	INSERT INTO IFRS_LI_AMORT_LOG ( DOWNLOAD_DATE , DTM , OPS , PROCNAME , REMARK )
    VALUES (V_CURRDATE ,SYSTIMESTAMP ,'END' ,'SP_IFRS_LI_AMORT_SEQUENCE' , ''  );

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN

    V_DATEPROCESS := TO_CHAR (SYSTIMESTAMP, 'MON DD, YYYY');


    UPDATE  IFRS_STATISTIC
    SET END_DATE = SYSTIMESTAMP ,
        ISCOMPLETE = 'N' ,
        REMARK = V_ERRM
    WHERE   DOWNLOAD_DATE = V_CURRDATE
    AND SP_NAME = V_SPNAME ;


    UPDATE  IFRS_LI_PRC_DATE_AMORT
    SET     BATCH_STATUS = 'ERROR!!..' ,
    REMARK = V_ERRM ,
    LAST_PROCESS_DATE = SYSTIMESTAMP ;

    V_ERRORMESSAGEDESCRIPTION := V_SPNAME || ' ( ' || V_DATEPROCESS ;

    RAISE_APPLICATION_ERROR (-20002, 'ERROR MESSAGE ' || V_ERRORMESSAGEDESCRIPTION || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);


    END;