CREATE OR REPLACE PROCEDURE SP_IFRS_PPR_BI_COLLECTABILITY
AS
    V_CURRDATE DATE;
BEGIN
   SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE_LGD;

    /*
    3. SELECT DOWNLOAD_DATE, MASTERID, ACCOUNT_NUMBER, BI_COLLECTABILITY FROM IFRS_MASTER_ACCOUNT_MONTHLY WHERE 3,4,5,WO,C -->
    INSERT KE TABLE IFRS_PPR_BI_COLLECTABILITY
    */

    MERGE INTO IFRS_PPR_BI_COLLECTABILITY D
    USING (
           SELECT
                DOWNLOAD_DATE,
                MASTERID,
                ACCOUNT_NUMBER,
                BI_COLLECTABILITY
           FROM IFRS_MASTER_ACCOUNT_MONTHLY
           WHERE DOWNLOAD_DATE = LAST_DAY(V_CURRDATE)
                AND ACCOUNT_STATUS  !=  'C'
                AND BI_COLLECTABILITY IN ('3','4','5','C')
          ) S ON (D.DOWNLOAD_DATE   =   S.DOWNLOAD_DATE
                  AND D.ACCOUNT_NUMBER  =   S.ACCOUNT_NUMBER)
    WHEN NOT MATCHED THEN
    INSERT (DOWNLOAD_DATE,
            MASTERID,
            ACCOUNT_NUMBER,
            BI_COLLECTABILITY)
    VALUES (S.DOWNLOAD_DATE,
            S.MASTERID,
            S.ACCOUNT_NUMBER,
            S.BI_COLLECTABILITY);
    COMMIT;

END;