CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_SL_SWITCH
AS
  V_CURRDATE    DATE;
    V_PREVDATE    DATE;
    V_NUM NUMBER(10);
BEGIN

    SELECT MAX(CURRDATE),MAX(PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT ;
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_ACCT_SL_SWITH','');
    COMMIT;

    --reset
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SL_COST_FEE_PREV
    SET STATUS='ACT'
    WHERE STATUS='REV'
    AND CREATEDBY='SL_SWITCH'
    AND DOWNLOAD_DATE=V_CURRDATE;

    COMMIT;

    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SL_COST_FEE_PREV
    SET STATUS='ACT'
    WHERE STATUS='REV2'
    AND CREATEDBY='SL_SWITCH'
    AND DOWNLOAD_DATE=V_PREVDATE;

    COMMIT;

    -- exist proc if no need to process SL switch
    SELECT /*+ PARALLEL(12) */ COUNT(*)
    INTO V_NUM
    FROM IFRS_ACCT_SWITCH
    WHERE DOWNLOAD_DATE=V_CURRDATE
    AND PREV_SL_ECF='Y';

    COMMIT;

    IF V_NUM<=0
    THEN
      INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
      VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_ACCT_SL_SWITH','');

      COMMIT;

      RETURN;
    END IF;

    -- copy ecf from old to new acctno
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SL_ECF (
    DOWNLOAD_DATE,
    MASTERID,
    FACNO,
    CIFNO,
    ACCTNO,
    DATASOURCE,
    PREVDATE,
    PMTDATE,
    I_DAYSCNT,
    N_UNAMORT_COST,
    N_UNAMORT_FEE,
    N_AMORT_COST,
    N_AMORT_FEE,
    CREATEDDATE,
    CREATEDBY,
    STATUS,
    AMORTSTOPDATE,
    AMORTSTOPREASON,
    N_DAILY_AMORT_COST,
    N_DAILY_AMORT_FEE,
    AMORTENDDATE,
    PERIOD,
    UNAMORT_COST_PREV,
    UNAMORT_FEE_PREV
    -- switch adjust carry forward
    ,SW_ADJ_COST
    ,SW_ADJ_FEE
    )
    SELECT  /*+ PARALLEL(12) */ V_CURRDATE,
            A.MASTERID,
            A.FACNO,
            A.CIFNO,
            A.ACCTNO,
            A.DATASOURCE,
            B.PREVDATE,
            B.PMTDATE,
            B.I_DAYSCNT,
            B.N_UNAMORT_COST,
            B.N_UNAMORT_FEE,
            B.N_AMORT_COST,
            B.N_AMORT_FEE,
            SYSTIMESTAMP,
            'SL_SWITCH',
            B.STATUS,
            B.AMORTSTOPDATE,
            B.AMORTSTOPREASON,
            B.N_DAILY_AMORT_COST,
            B.N_DAILY_AMORT_FEE,
            B.AMORTENDDATE,
            B.PERIOD,
            B.UNAMORT_COST_PREV,
            B.UNAMORT_FEE_PREV
            -- switch adjust carry forward
            ,B.SW_ADJ_COST
            ,B.SW_ADJ_FEE
    FROM IFRS_ACCT_SWITCH A
    JOIN IFRS_ACCT_SL_ECF B
      ON B.AMORTSTOPDATE IS NULL
      AND B.MASTERID=A.PREV_MASTERID
    WHERE A.DOWNLOAD_DATE=V_CURRDATE
    AND A.PREV_SL_ECF='Y';

    COMMIT;

    -- copy old cost fee ecf to new acct
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SL_COST_FEE_ECF
    ( DOWNLOAD_DATE ,
      ECFDATE ,
      MASTERID ,
        BRCODE ,
        CIFNO ,
        FACNO ,
        ACCTNO ,
        DATASOURCE ,
        CCY,
        PRDCODE,
        TRXCODE,
        FLAG_CF,
        FLAG_REVERSE,
        METHOD,
        STATUS,
        SRCPROCESS,
        AMOUNT,
        CREATEDDATE,
        CREATEDBY,
        SEQ,
        AMOUNT_ORG,
        ORG_CCY,
        ORG_CCY_EXRATE,
        PRDTYPE,CF_ID
    )
    SELECT  /*+ PARALLEL(12) */ C.DOWNLOAD_DATE ,
            V_CURRDATE ,
              A.MASTERID ,
              A.BRCODE ,
              A.CIFNO ,
              A.FACNO ,
              A.ACCTNO ,
              A.DATASOURCE ,
              C.CCY,
              A.PRDCODE,
              C.TRXCODE,
              C.FLAG_CF,
              C.FLAG_REVERSE,
              C.METHOD,
              C.STATUS,
              C.SRCPROCESS,
              C.AMOUNT,
              SYSTIMESTAMP,
              'SL_SWITCH',
              C.SEQ,
              C.AMOUNT_ORG,
              C.ORG_CCY,
              C.ORG_CCY_EXRATE,
              A.PRDTYPE
              ,C.CF_ID
    FROM IFRS_ACCT_SWITCH A
    JOIN IFRS_ACCT_SL_ECF B
      ON B.AMORTSTOPDATE IS NULL
      AND B.MASTERID=A.PREV_MASTERID
      AND B.PREVDATE=B.PMTDATE
      AND B.DOWNLOAD_DATE<V_CURRDATE -- add filter for branch change
    JOIN IFRS_ACCT_SL_COST_FEE_ECF C
      ON C.ECFDATE=B.DOWNLOAD_DATE
      AND C.MASTERID=B.MASTERID
    WHERE A.DOWNLOAD_DATE=V_CURRDATE
    AND A.PREV_SL_ECF='Y';

    COMMIT;

    --rev old cost fee prev
    MERGE INTO IFRS_ACCT_SL_COST_FEE_PREV A
    USING  (SELECT C.MASTERID,C.DOWNLOAD_DATE,C.SEQ
            FROM IFRS_ACCT_SWITCH A
            JOIN IFRS_PRC_DATE_AMORT P ON P.CURRDATE=A.DOWNLOAD_DATE
            JOIN VW_LAST_SL_COST_FEE_PREV C ON C.MASTERID=A.PREV_MASTERID
            WHERE A.PREV_SL_ECF='Y'
            ) C
    ON (A.DOWNLOAD_DATE=C.DOWNLOAD_DATE
        AND A.MASTERID=C.MASTERID
        AND A.SEQ=C.SEQ
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.STATUS=CASE WHEN A.DOWNLOAD_DATE=V_CURRDATE THEN 'REV' ELSE 'REV2' END
      , A.CREATEDBY='SL_SWITCH';

    COMMIT;

    --copy old cost fee prev to new acct
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SL_COST_FEE_PREV
    ( DOWNLOAD_DATE ,
      ECFDATE ,
        MASTERID ,
        BRCODE ,
        CIFNO ,
        FACNO ,
        ACCTNO ,
        DATASOURCE ,
        CCY ,
        PRDCODE ,
        TRXCODE ,
        FLAG_CF ,
        FLAG_REVERSE ,
        METHOD ,
        STATUS ,
        SRCPROCESS ,
        AMOUNT ,
        CREATEDDATE ,
        CREATEDBY ,
        ISUSED ,
        SEQ ,
        AMOUNT_ORG ,
        ORG_CCY ,
        ORG_CCY_EXRATE ,
        PRDTYPE
        ,CF_ID
    )
    SELECT  /*+ PARALLEL(12) */ V_CURRDATE ,
            V_CURRDATE ,
              A.MASTERID ,
              A.BRCODE ,
              A.CIFNO ,
              A.FACNO ,
              A.ACCTNO ,
              A.DATASOURCE ,
              D.CCY ,
              A.PRDCODE ,
              D.TRXCODE ,
              D.FLAG_CF ,
              D.FLAG_REVERSE ,
              D.METHOD ,
              'ACT' STATUS ,
              D.SRCPROCESS ,
              D.AMOUNT ,
              SYSTIMESTAMP ,
              'SL_SWITCH' ,
              D.ISUSED ,
            '0' SEQ_NEW ,
              D.AMOUNT_ORG ,
              D.ORG_CCY ,
              D.ORG_CCY_EXRATE ,
              A.PRDTYPE
              ,D.CF_ID
    FROM IFRS_ACCT_SWITCH A
    JOIN VW_LAST_SL_COST_FEE_PREV C
      ON C.MASTERID=A.PREV_MASTERID
    JOIN IFRS_ACCT_SL_COST_FEE_PREV D
      ON D.DOWNLOAD_DATE=C.DOWNLOAD_DATE
      AND D.MASTERID=C.MASTERID
      AND D.SEQ=C.SEQ
    WHERE A.DOWNLOAD_DATE=V_CURRDATE AND A.PREV_SL_ECF='Y';

    COMMIT;

    -- stop old ecf
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SL_ECF
    SET AMORTSTOPDATE=V_CURRDATE
    ,AMORTSTOPREASON='SL_SWITCH'
    WHERE AMORTSTOPDATE IS NULL
    AND DOWNLOAD_DATE<V_CURRDATE -- add filter for branch change
    AND MASTERID IN (SELECT PREV_MASTERID FROM IFRS_ACCT_SWITCH WHERE DOWNLOAD_DATE=V_CURRDATE AND PREV_SL_ECF='Y');

    COMMIT;

    -- handle acf that is doing accru yesterday
    DELETE /*+ PARALLEL(12) */ FROM TMP_T1;
    COMMIT;
    INSERT INTO TMP_T1(MASTERID)
    SELECT PREV_MASTERID AS MASTERID
    FROM IFRS_ACCT_SWITCH WHERE DOWNLOAD_DATE=V_CURRDATE AND PREV_SL_ECF='Y';
    COMMIT;

    -- no accru if yesterday is doing amort
    DELETE /*+ PARALLEL(12) */ FROM TMP_T2;
    COMMIT;
    INSERT INTO TMP_T2(MASTERID)
    SELECT DISTINCT MASTERID FROM IFRS_ACCT_SL_ACF WHERE DOWNLOAD_DATE=V_PREVDATE AND DO_AMORT='Y';
    COMMIT;

    DELETE /*+ PARALLEL(12) */ FROM TMP_T3;
    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_T3(MASTERID)
    SELECT A.MASTERID
    FROM TMP_T1 A;
    COMMIT;
    --left join TMP_T2 b on b.masterid=a.masterid
    --where b.masterid is null


    -- get last acf with do_amort=N
    DELETE /*+ PARALLEL(12) */ FROM TMP_P1;

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_P1(ID)
    SELECT MAX(ID) AS ID FROM IFRS_ACCT_SL_ACF
    WHERE MASTERID IN (SELECT MASTERID FROM TMP_T3) AND DO_AMORT='N'
    GROUP BY MASTERID;

    COMMIT;

    -- update sw adj cost/fee
    MERGE INTO IFRS_ACCT_SWITCH A
    USING (SELECT B.MASTERID,B.N_ACCRU_COST,B.N_ACCRU_FEE, V_CURRDATE CURRDATE
           FROM IFRS_ACCT_SL_ACF B
           WHERE B.ID IN (SELECT ID FROM TMP_P1)
           ) B
    ON (A.DOWNLOAD_DATE=B.CURRDATE
        AND A.PREV_SL_ECF='Y'
        AND A.PREV_MASTERID=B.MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.SW_ADJ_COST=B.N_ACCRU_COST
    ,A.SW_ADJ_FEE=B.N_ACCRU_FEE;

    COMMIT;

    -- get fee summary
    EXECUTE IMMEDIATE 'truncate table TMP_TF';

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_TF(SUM_AMT,DOWNLOAD_DATE,MASTERID)
    SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
    FROM( SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                ,A.ECFDATE DOWNLOAD_DATE
                ,A.MASTERID
          FROM IFRS_ACCT_SL_COST_FEE_ECF A
          WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_T3)
          AND A.STATUS='ACT' AND A.FLAG_CF='F' AND A.METHOD='SL'
    ) A
    GROUP BY A.DOWNLOAD_DATE,A.MASTERID;

    COMMIT;


    -- get cost summary
    DELETE /*+ PARALLEL(12) */ FROM TMP_TC;

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_TC(SUM_AMT,DOWNLOAD_DATE,MASTERID)
    SELECT /*+ PARALLEL(12) */ SUM(A.N_AMOUNT) AS SUM_AMT, A.DOWNLOAD_DATE,A.MASTERID
    FROM(SELECT CASE WHEN A.FLAG_REVERSE='Y' THEN -1 * A.AMOUNT ELSE A.AMOUNT END AS N_AMOUNT
                ,A.ECFDATE DOWNLOAD_DATE,A.MASTERID
         FROM IFRS_ACCT_SL_COST_FEE_ECF A
         WHERE A.MASTERID IN (SELECT MASTERID FROM TMP_T3)
         AND A.STATUS='ACT' AND A.FLAG_CF='C' AND A.METHOD='SL'
        ) A
    GROUP BY A.DOWNLOAD_DATE,A.MASTERID;

    COMMIT;


    --insert fee 1
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SL_ACCRU_PREV
    (FACNO
    ,CIFNO
    ,DOWNLOAD_DATE
    ,ECFDATE
    ,DATASOURCE
    ,PRDCODE
    ,TRXCODE
    ,CCY,AMOUNT
    ,STATUS
    ,CREATEDDATE
    ,ACCTNO
    ,MASTERID
    ,FLAG_CF
    ,FLAG_REVERSE
    ,AMORTDATE
    ,SRCPROCESS
    ,ORG_CCY
    ,ORG_CCY_EXRATE
    ,PRDTYPE
    ,CF_ID
    )
    SELECT /*+ PARALLEL(12) */ A.FACNO
          ,A.CIFNO
          ,V_CURRDATE
          ,A.ECFDATE
          ,A.DATASOURCE
          ,B.PRDCODE
          ,B.TRXCODE
          ,B.CCY
          ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_FEE AS N_AMOUNT
          ,B.STATUS
          ,SYSTIMESTAMP
          ,A.ACCTNO
          ,A.MASTERID
          ,B.FLAG_CF
          ,'N',NULL AS AMORTDATE
          ,'SW'
          ,B.ORG_CCY
          ,B.ORG_CCY_EXRATE
          ,B.PRDTYPE
          ,B.CF_ID
    FROM IFRS_ACCT_SL_ACF A
    JOIN IFRS_ACCT_SL_COST_FEE_ECF B ON B.ECFDATE=A.ECFDATE
      AND A.MASTERID=B.MASTERID
      AND B.FLAG_CF='F'
    JOIN TMP_TF C ON C.DOWNLOAD_DATE=A.ECFDATE AND C.MASTERID=A.MASTERID
    WHERE A.ID IN (SELECT ID FROM TMP_P1);

    COMMIT;
    --cost 1
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SL_ACCRU_PREV
    (FACNO
    ,CIFNO
    ,DOWNLOAD_DATE
    ,ECFDATE
    ,DATASOURCE
    ,PRDCODE
    ,TRXCODE,CCY
    ,AMOUNT
    ,STATUS
    ,CREATEDDATE
    ,ACCTNO
    ,MASTERID
    ,FLAG_CF
    ,FLAG_REVERSE
    ,AMORTDATE
    ,SRCPROCESS
    ,ORG_CCY
    ,ORG_CCY_EXRATE
    ,PRDTYPE
    ,CF_ID
    )
    SELECT /*+ PARALLEL(12) */ A.FACNO
          ,A.CIFNO
          ,V_CURRDATE
          ,A.ECFDATE
          ,A.DATASOURCE
          ,B.PRDCODE
          ,B.TRXCODE
          ,B.CCY
          ,CAST(CAST(CASE WHEN B.FLAG_REVERSE='Y' THEN -1 * B.AMOUNT ELSE B.AMOUNT END AS BINARY_DOUBLE)/CAST(C.SUM_AMT AS BINARY_DOUBLE) AS NUMBER(32,20)) * A.N_ACCRU_COST AS N_AMOUNT
          ,B.STATUS
          ,SYSTIMESTAMP
          ,A.ACCTNO
          ,A.MASTERID
          ,B.FLAG_CF
          ,'N'
          , NULL AS AMORTDATE
          ,'SW'
          ,B.ORG_CCY
          ,B.ORG_CCY_EXRATE
          ,B.PRDTYPE
          ,B.CF_ID
    FROM IFRS_ACCT_SL_ACF A
    JOIN IFRS_ACCT_SL_COST_FEE_ECF B ON B.ECFDATE=A.ECFDATE
      AND A.MASTERID=B.MASTERID
      AND B.FLAG_CF='C'
    JOIN TMP_TC C ON C.DOWNLOAD_DATE=A.ECFDATE AND C.MASTERID=A.MASTERID
    WHERE A.ID IN (SELECT ID FROM TMP_P1);

    COMMIT;

    --stop old accru before currdate
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SL_ACCRU_PREV
    SET STATUS=TO_CHAR(V_CURRDATE,'YYYYMMDD')
    WHERE STATUS='ACT'
    --and effdate<v_currdate
    AND MASTERID IN (SELECT PREV_MASTERID FROM IFRS_ACCT_SWITCH WHERE DOWNLOAD_DATE=V_CURRDATE AND PREV_SL_ECF='Y');

    COMMIT;

    -- sw adj cost fee to new ecf
    DELETE /*+ PARALLEL(12) */ FROM TMP_SW1;

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO TMP_SW1(MASTERID,PMTDATE)
    SELECT /*+ PARALLEL(12) */ A.MASTERID,MIN(A.PMTDATE) AS PMTDATE
    FROM IFRS_ACCT_SL_ECF A
    JOIN IFRS_ACCT_SWITCH B ON B.MASTERID=A.MASTERID
      AND B.DOWNLOAD_DATE=V_CURRDATE AND B.PREV_SL_ECF='Y'
    WHERE A.DOWNLOAD_DATE=V_CURRDATE
    AND A.AMORTSTOPDATE IS NULL
    AND A.PMTDATE>=V_CURRDATE
    AND A.PMTDATE<>A.PREVDATE
    GROUP BY A.MASTERID;

    COMMIT;



    MERGE INTO IFRS_ACCT_SL_ECF A
    USING (SELECT A.*,B.SW_ADJ_COST,B.SW_ADJ_FEE, V_CURRDATE CURRDATE
           FROM TMP_SW1 A
           JOIN IFRS_ACCT_SWITCH B
             ON B.MASTERID=A.MASTERID
             AND B.DOWNLOAD_DATE=V_CURRDATE
             AND B.PREV_SL_ECF='Y'
           ) X
    ON (A.DOWNLOAD_DATE=X.CURRDATE
        AND A.MASTERID=X.MASTERID
        AND A.PMTDATE=X.PMTDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET  A.SW_ADJ_COST=COALESCE(A.SW_ADJ_COST,0)+X.SW_ADJ_COST
    ,A.SW_ADJ_FEE=COALESCE(A.SW_ADJ_FEE,0)+X.SW_ADJ_FEE;

    COMMIT;


    -- update cost fee summ
    MERGE INTO IFRS_ACCT_COST_FEE_SUMM A
    USING (SELECT B.DOWNLOAD_DATE,B.MASTERID
           FROM IFRS_ACCT_SWITCH B
           WHERE B.DOWNLOAD_DATE=V_CURRDATE
           AND B.MASTERID IN (SELECT MASTERID FROM IFRS_ACCT_SWITCH WHERE DOWNLOAD_DATE=V_CURRDATE AND PREV_SL_ECF='Y')
           ) B
    ON (A.DOWNLOAD_DATE=B.DOWNLOAD_DATE
        AND A.MASTERID=B.MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.AMOUNT_FEE = COALESCE(A.AMOUNT_FEE,0) + COALESCE(A.AMORT_FEE,0)
    ,A.AMOUNT_COST = COALESCE(A.AMOUNT_COST,0) + COALESCE(A.AMORT_COST,0)
    ,A.CREATEDBY='SL_SWITCH' ;

    COMMIT;


    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_ACCT_SL_SWITH','');

    COMMIT;

END;