CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_SEQUENCE_PR(v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'), v_ECLID NUMBER DEFAULT(0))
AS
    V_SPNAME VARCHAR2(100);
    V_ECLMODELID  NUMBER(18);
    V_CURRDATE  DATE;
    V_EXISTS NUMBER(10) := 0;
    V_HEADERID NUMBER(18);
BEGIN

    IF v_ECLID = 0 THEN
        SELECT PKID INTO V_ECLMODELID FROM IFRS_ECL_MODEL_HEADER WHERE ACTIVE_FLAG = 1;
    ELSE
        v_ECLMODELID := v_ECLID;
    END IF;

    IF v_DOWNLOADDATE = '1-JAN-1900' THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATE;
    END IF;

    V_SPNAME := 'SP_IFRS_ECL_PARTIAL_RUN_LIST('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
	SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

	 SELECT COUNT(*)
	 INTO V_EXISTS
	 FROM IFRS_PARTIAL_RUN_HEADER
	 WHERE DOWNLOAD_DATE = V_CURRDATE
	 AND RUN_STATUS = 1;

	 IF V_EXISTS > 0 THEN
         SELECT COUNT(*)
         INTO V_EXISTS
         FROM IFRS_PARTIAL_RUN_HEADER
         WHERE DOWNLOAD_DATE = V_CURRDATE
         AND RUN_STATUS = 1
         AND REASON LIKE '%Bank Multiplier%';

         IF V_EXISTS > 0 THEN
              V_SPNAME := 'SP_IFRS_ECL_UPDATE_MULT_PR('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
              SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
         END IF;


         SELECT COUNT(*)
         INTO V_EXISTS
         FROM IFRS_PARTIAL_RUN_HEADER
         WHERE DOWNLOAD_DATE = V_CURRDATE
         AND RUN_STATUS = 1
         AND REASON LIKE '%Stage Override%';

         IF V_EXISTS > 0 THEN
             V_SPNAME := 'SP_IFRS_ECL_UPDATE_STAGE('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
             SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

             V_SPNAME := 'SP_IFRS_EAD_PROCESS ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
             SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
         END IF;

         V_SPNAME := 'SP_IFRS_ECL_INSERT_TMP_IMA_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_RESULT_CALC_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_WORSTCASE_CALC_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_IA_CALC_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_ADJSTMNT_COVID_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_DISASTER_LN_CLC_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_SBLC_CALC_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_SPECIAL_REASON_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_EXCLUDE_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_ECL_RESULT_HEADER_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

         V_SPNAME := 'SP_IFRS_NOMINATIVE_TO_IMA_PR ('|| V_ECLMODELID ||', '''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
         SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

        SELECT PKID
        INTO V_HEADERID
        FROM IFRS_PARTIAL_RUN_HEADER
        WHERE DOWNLOAD_DATE = V_CURRDATE
        AND RUN_STATUS = 1;

        DELETE IFRS_PARTIAL_RUN_DETAIL
        WHERE HEADERID = V_HEADERID
        AND ACCOUNT_NUMBER != '-'
        AND ACCOUNT_NUMBER NOT IN
        (
            SELECT ACCOUNT_NUMBER FROM IFRS_ECL_RESULT_DETAIL
            WHERE DOWNLOAD_DATE = V_CURRDATE
        );
        COMMIT;

        DELETE IFRS_PARTIAL_RUN_DETAIL
        WHERE HEADERID = V_HEADERID
        AND CUSTOMER_NUMBER != '-'
        AND CUSTOMER_NUMBER NOT IN
        (
            SELECT CUSTOMER_NUMBER FROM IFRS_ECL_RESULT_DETAIL
            WHERE DOWNLOAD_DATE = V_CURRDATE
        );
        COMMIT;

        UPDATE IFRS_PARTIAL_RUN_HEADER
        SET RUN_STATUS = 2, UPDATEDDATE = SYSDATE, UPDATEDHOST = CREATEDHOST, UPDATEDBY = CREATEDBY
        WHERE PKID = V_HEADERID;
        COMMIT;
    END IF;
END;