CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_ACCT_EIR_GS_ALL
AS
  V_CURRDATE   DATE;
  V_PREVDATE   DATE;
  V_VLOOP2     NUMBER(19);
  V_VCNT       NUMBER(19);
  V_VCNT2      NUMBER(19);
  V_COUNTER    NUMBER(19);
  V_MAXCOUNTER NUMBER(19);


BEGIN

  SELECT MAX (CURRDATE),MAX (PREVDATE)
  INTO V_CURRDATE, V_PREVDATE
  FROM IFRS_PRC_DATE_AMORT  ;

  INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
  VALUES(V_CURRDATE, SYSTIMESTAMP, 'START', 'SP_IFRS_LBM_ACCT_EIR_GS_PROCESS', '');

  COMMIT;


	UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	SET EIR = NULL
		,NEXT_EIR = NULL
		,FINAL_EIR = NULL
		,EIR_NOCF = NULL
		,NEXT_EIR_NOCF = NULL
		,FINAL_EIR_NOCF = NULL;

  COMMIT;

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS2';

  COMMIT;

	INSERT /*+ PARALLEL(8) */ INTO TMP_GS2 (
		MASTERID
		,DTMIN
		,CNTMIN
		,--ADDING FOR MIN COUNTER
		BENEFIT
		,STAFFLOAN
		,COST_AMT
		,FEE_AMT
		,GAIN_LOSS_FEE_AMT
		,GAIN_LOSS_COST_AMT
		)
	SELECT /*+ PARALLEL(8) */ B.MASTERID
		,C.DTMIN
		,C.CNTMIN
		,--ADDING FOR MIN COUNTER
		B.BENEFIT
		,B.STAFFLOAN
		,B.COST_AMT
		,B.FEE_AMT
		,COALESCE(B.GAIN_LOSS_FEE_AMT, 0) --20180226 GAIN LOSS ADJ
		,COALESCE(B.GAIN_LOSS_COST_AMT, 0)
	FROM IFRS_LBM_ACCT_EIR_CF_ECF1 B
	JOIN IFRS_LBM_ACCT_EIR_PAYM_GS_DATE C ON C.MASTERID = B.MASTERID;

  COMMIT;

  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
  USING TMP_GS2 B
  ON (A.MASTERID=B.MASTERID
      AND A.COUNTER=B.CNTMIN)
  WHEN MATCHED THEN
  UPDATE
  SET A.PREV_UNAMORT1 = CASE WHEN B.STAFFLOAN = 1 AND B.BENEFIT < 0  THEN B.BENEFIT
                             WHEN B.STAFFLOAN = 1 AND B.BENEFIT >= 0 THEN 0
                             ELSE B.FEE_AMT - B.GAIN_LOSS_FEE_AMT --20180417
                           END + CASE WHEN B.STAFFLOAN = 1 AND B.BENEFIT <= 0 THEN 0
                                      WHEN B.STAFFLOAN = 1 AND B.BENEFIT > 0  THEN B.BENEFIT
                                      ELSE B.COST_AMT - B.GAIN_LOSS_COST_AMT --20180417
                                      END
		, A.PREV_UNAMORT_NOCF1 = 0
		,--FOR NO CF CALCULATION
		  A.EIR1 = CASE WHEN B.STAFFLOAN = 1 THEN 10.5
                  WHEN N_INT_RATE > 1  THEN N_INT_RATE
                  ELSE 1
                  END
		, A.EIR2 = CASE WHEN B.STAFFLOAN = 1 THEN 11
                    WHEN N_INT_RATE > 1 THEN N_INT_RATE
                    ELSE 1
                    END + (0.01 * CASE WHEN N_INT_RATE > 1 THEN N_INT_RATE ELSE 1 END)
		, A.EIR_NOCF1 = CASE WHEN B.STAFFLOAN = 1 THEN 10.5
                        WHEN N_INT_RATE > 1 THEN N_INT_RATE
                        ELSE 1
                        END
		, A.EIR_NOCF2 = CASE WHEN B.STAFFLOAN = 1 THEN 11
                         WHEN N_INT_RATE > 1 THEN N_INT_RATE
                         ELSE 1
                         END + (0.01 * CASE WHEN N_INT_RATE > 1 THEN N_INT_RATE ELSE 1 END);

  COMMIT;

  INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','1');


	-- 20131106 DANIEL S : NOTE UNAMORT AMOUNT FOR EACH MASTERID
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
  USING IFRS_LBM_ACCT_EIR_PAYM_GS B
  ON (A.MASTERID=B.MASTERID
      AND A.DTMIN=B.PMT_DATE)
  WHEN MATCHED THEN
  UPDATE
  SET A.UNAMORT=B.PREV_UNAMORT1
    , A.UNAMORT_NOCF=B.PREV_UNAMORT_NOCF1;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','2');

	--SELECT * FROM IFRS_LBM_ACCT_EIR_PAYM_GS ORDER BY PMT_DATE
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
  USING IFRS_LBM_ACCT_EIR_PAYM_GS_DATE C
  ON (A.MASTERID=C.MASTERID
      AND A.COUNTER=C.CNTMIN)
  WHEN MATCHED THEN
  UPDATE
  SET --WITHOUT CF PART
   A.PREV_UNAMORT_NOCF2 = A.PREV_UNAMORT_NOCF1
  ,A.PREV_CRYAMT_NOCF1 = A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1
  ,A.PREV_CRYAMT_NOCF2 = A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1
	,A.EIRAMT_NOCF1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                    WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS/ 360 * A.EIR_NOCF1 / 100 * ( A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1 )
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                    WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS/ 365 * A.EIR_NOCF1 / 100 * ( A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1 )
                    ELSE ( A.M/ 1200 * EIR_NOCF1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1) )
                    END
	,A.EIRAMT_NOCF2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    ELSE (A.M / 1200 * A.EIR_NOCF2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                    END
	,A.AMORT_NOCF1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                   --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                   ELSE (A.M / 1200 * A.EIR_NOCF1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                   END - N_INT_PAYMENT
	,A.AMORT_NOCF2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                   WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                   --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                   WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                   ELSE (A.M / 1200 * A.EIR_NOCF2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                   END - A.N_INT_PAYMENT
	,A.UNAMORT_NOCF1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                     WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                     ELSE (A.M / 1200 * A.EIR_NOCF1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                     END - A.N_INT_PAYMENT + A.PREV_UNAMORT_NOCF1
	,A.UNAMORT_NOCF2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                     WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                     --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                     WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                     ELSE (A.M / 1200 * A.EIR_NOCF2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                     END - A.N_INT_PAYMENT + A.PREV_UNAMORT_NOCF1
	,A.CRYAMT_NOCF1 = (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1) - A.N_PRN_PAYMENT + (
                    CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                    WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    ELSE (A.M / 1200 * EIR_NOCF1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                    END - A.N_INT_PAYMENT
                    ) + A.DISB_AMOUNT
	,A.CRYAMT_NOCF2 = (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1) - A.N_PRN_PAYMENT + (
                    CASE
                    --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                    WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
                    WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR_NOCF2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1)
                    ELSE (A.M / 1200 * A.EIR_NOCF2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT_NOCF1))
                    END - A.N_INT_PAYMENT
                    ) + A.DISB_AMOUNT
	,
	--WITH CF PART
	 A.PREV_UNAMORT2 = A.PREV_UNAMORT1
	,A.PREV_CRYAMT1 = A.N_OSPRN_PREV + A.PREV_UNAMORT1
	,A.PREV_CRYAMT2 = A.N_OSPRN_PREV + A.PREV_UNAMORT1
	,A.EIRAMT1 =/*  BCA DISABLE BPI
              CASE WHEN (IFRS_LBM_ACCT_EIR_PAYM_GS.COUNTER = 1 AND IFRS_LBM_ACCT_EIR_PAYM_GS.SPECIAL_FLAG = 1)
              THEN  EIR1 /100*(DATEDIFF(DAY,IFRS_LBM_ACCT_EIR_PAYM_GS.PREV_PMT_DATE,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))*
              (N_OSPRN_PREV + PREV_UNAMORT1)/12/(DATEDIFF(DAY,
              CASE WHEN IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE = EOMONTH(IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE)
              THEN EOMONTH(DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE)) ELSE DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) END,
              IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
              ELSE
              */
              CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              ELSE (A.M / 1200 * A.EIR1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
              /*  BCA DISABLE BPI END */
              END
	,A.EIRAMT2 =
              /*  BCA DISABLE BPI
                 CASE WHEN (IFRS_LBM_ACCT_EIR_PAYM_GS.COUNTER = 1 AND IFRS_LBM_ACCT_EIR_PAYM_GS.SPECIAL_FLAG = 1)
                 THEN
                  EIR2 /100*(DATEDIFF(DAY,IFRS_LBM_ACCT_EIR_PAYM_GS.PREV_PMT_DATE,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))*
                  (N_OSPRN_PREV + PREV_UNAMORT1)/12/(DATEDIFF(DAY,
                  CASE WHEN IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE = EOMONTH(IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE)
                  THEN EOMONTH(DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE)) ELSE DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) END,
                 IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
                 ELSE
                */
              CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              ELSE (A.M / 1200 * A.EIR2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
              /*  BCA DISABLE BPI END  */
			END
	,A.AMORT1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              ELSE (A.M / 1200 * A.EIR1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
              END - A.N_INT_PAYMENT
	,A.AMORT2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
              WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
              ELSE (A.M / 1200 * A.EIR2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
              END - A.N_INT_PAYMENT
	,A.UNAMORT1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
                --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
                ELSE (A.M / 1200 * A.EIR1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
                END - A.N_INT_PAYMENT + A.PREV_UNAMORT1
	,A.UNAMORT2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
                --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
                ELSE (A.M / 1200 * EIR2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
                END - A.N_INT_PAYMENT + A.PREV_UNAMORT1
	,A.CRYAMT1 = (A.N_OSPRN_PREV + A.PREV_UNAMORT1) - A.N_PRN_PAYMENT + (
               CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
               WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
               --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
               WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR1 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
               ELSE (A.M  / 1200 * A.EIR1 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
               END - A.N_INT_PAYMENT
               ) + A.DISB_AMOUNT
	,A.CRYAMT2 = (A.N_OSPRN_PREV + A.PREV_UNAMORT1) - A.N_PRN_PAYMENT + (
               CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
               WHEN A.INTCALCCODE IN ('1','6')THEN A.I_DAYS / 360 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
               --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
               WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * A.EIR2 / 100 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1)
               ELSE (A.M / 1200 * A.EIR2 * (A.N_OSPRN_PREV + A.PREV_UNAMORT1))
               END - A.N_INT_PAYMENT
               ) + A.DISB_AMOUNT;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','3');

	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LBM_GS_DATE1';
  COMMIT;

	INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_GS_DATE1 (
		MASTERID
		,PMT_DATE
		,PERIOD
		)
	SELECT /*+ PARALLEL(8) */ MASTERID
		,DTMIN
		,PERIOD
	FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE;

  COMMIT;

	/* REMARKS REMARKS 20160525
        SELECT A.MASTERID, MIN (A.PMT_DATE) DT
          FROM    IFRS_LBM_ACCT_EIR_PAYM_GS A
               JOIN
                  IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
               ON A.PMT_DATE > B.DTMIN AND A.MASTERID = B.MASTERID
      GROUP BY A.MASTERID
   END REMARKS 20160525*/
	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','4');
  COMMIT;

	V_VLOOP2 := 0;

	-- OUTER LOOP
	WHILE 1 = 1
	LOOP --LOOP

    V_VLOOP2 := V_VLOOP2 + 1;
        EXIT WHEN V_VLOOP2 > 50; -- max count for outer loop

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','LOOP ' || TO_CHAR (V_VLOOP2));


    V_COUNTER := 1;

    SELECT NVL(MAX(PERIOD),0) INTO V_MAXCOUNTER FROM IFRS_LBM_GS_DATE1;

        EXIT WHEN V_MAXCOUNTER <= 0 ;

		--INNER LOOP
		--WHILE 1 = 1
		WHILE V_COUNTER <= V_MAXCOUNTER
		LOOP
			/* REMARKS 20160525
   SELECT @VCNT=COUNT (*) FROM IFRS_LBM_GS_DATE1
         IF @VCNT <= 0 BREAK


         --UPDATE
         TRUNCATE TABLE PSAK_TMP_GS3

         INSERT INTO PSAK_TMP_GS3 (MASTERID,
                                   PMT_DATE,
                                   EIR1,
                                   CRYAMT1,
                                   EIR2,
                                   CRYAMT2,
                                   UNAMORT1,
                                   UNAMORT2)
            SELECT B.MASTERID,
                   B.PMT_DATE,
                   C.EIR1,
                   C.CRYAMT1,
                   C.EIR2,
                   C.CRYAMT2,
                   C.UNAMORT1,
                   C.UNAMORT2
              FROM IFRS_LBM_GS_DATE1 B
                   JOIN IFRS_LBM_ACCT_EIR_PAYM_GS D
              ON D.MASTERID = B.MASTERID AND D.PMT_DATE = B.PMT_DATE
                   JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C
                      ON C.MASTERID = B.MASTERID
                         AND C.PMT_DATE = D.PREV_PMT_DATE

   END REMARKS 20160525*/


      MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
      USING (SELECT Z.* FROM IFRS_LBM_GS_DATE1 B
             JOIN IFRS_LBM_ACCT_EIR_PAYM_GS Z ON B.MASTERID=Z.MASTERID AND Z.COUNTER=V_COUNTER-1
             )C
      ON (A.MASTERID=C.MASTERID
          AND A.COUNTER=V_COUNTER)
      WHEN MATCHED THEN
      UPDATE
      SET --WITHOUT CF PART
       A.PREV_UNAMORT_NOCF1 = C.UNAMORT_NOCF1
      ,A.PREV_UNAMORT_NOCF2 = C.UNAMORT_NOCF2
      ,A.PREV_CRYAMT_NOCF1 = C.CRYAMT_NOCF1
      ,A.PREV_CRYAMT_NOCF2 = C.CRYAMT_NOCF2
      ,A.EIR_NOCF1 = C.EIR_NOCF1
      ,A.EIR_NOCF2 = C.EIR_NOCF2
      ,A.EIRAMT_NOCF1 = CASE
                        WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * C.EIR_NOCF1 / 100 * C.CRYAMT_NOCF1
                        WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.EIR_NOCF1 / 100 * C.CRYAMT_NOCF1
                        ELSE (A.M / 1200 * C.EIR_NOCF1 * C.CRYAMT_NOCF1)
                        END
      ,A.EIRAMT_NOCF2 = CASE
                        WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                        WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                        ELSE (A.M / 1200 * C.EIR_NOCF2 * C.CRYAMT_NOCF2)
                        END
				,/*20170912, REMARK KATA YACOP
      A.AMORT_NOCF1 = ( CASE WHEN A.INTCALCCODE IN ( '1', '6' ) THEN A.I_DAYS / 360 * C.EIR_NOCF1 / 100* C.CRYAMT_NOCF1
                             WHEN A.INTCALCCODE IN ( '2', '3' ) THEN A.I_DAYS / 365 * C.EIR_NOCF1 / 100* C.CRYAMT_NOCF1
                             ELSE ( A.M/ 1200 * C.EIR_NOCF1 * C.CRYAMT_NOCF1 )
                             END ) - A.N_INT_PAYMENT ,
      A.AMORT_NOCF2 = ( CASE WHEN A.INTCALCCODE IN ( '1', '6' ) THEN A.I_DAYS / 360 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                             WHEN A.INTCALCCODE IN ( '2', '3' ) THEN A.I_DAYS / 365 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                             ELSE ( A.M / 1200* C.EIR_NOCF2 * C.CRYAMT_NOCF2 ) END ) - A.N_INT_PAYMENT ,
      A.UNAMORT_NOCF1 = ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' ) THEN A.I_DAYS/ 360 * C.EIR_NOCF1 / 100 * C.CRYAMT_NOCF1
                                 WHEN A.INTCALCCODE IN ( '2', '3' ) THEN A.I_DAYS / 365 * C.EIR_NOCF1 / 100 * C.CRYAMT_NOCF1
                                 ELSE ( A.M / 1200 * C.EIR_NOCF1 * C.CRYAMT_NOCF1 )
                                 END ) - A.N_INT_PAYMENT ) + C.UNAMORT_NOCF1 ,
      A.UNAMORT_NOCF2 = ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' ) THEN A.I_DAYS/ 360* C.EIR_NOCF2/ 100* C.CRYAMT_NOCF2
                                 WHEN A.INTCALCCODE IN ( '2', '3' ) THEN A.I_DAYS/ 365* C.EIR_NOCF2/ 100* C.CRYAMT_NOCF2
                                 ELSE ( A.M/ 1200* C.EIR_NOCF2* C.CRYAMT_NOCF2 )
                                 END ) - A.N_INT_PAYMENT )+ C.UNAMORT_NOCF2 ,
      A.CRYAMT_NOCF1 = C.CRYAMT_NOCF1 + ( (
                       CASE WHEN A.INTCALCCODE IN ( '1', '6' )THEN A.I_DAYS / 360* C.EIR_NOCF1 / 100 * C.CRYAMT_NOCF1
                            WHEN A.INTCALCCODE IN ( '2', '3' )THEN A.I_DAYS / 365* C.EIR_NOCF1 / 100* C.CRYAMT_NOCF1
                            ELSE ( A.M/ 1200 * C.EIR_NOCF1* C.CRYAMT_NOCF1 )
                            END ) - A.N_INT_PAYMENT ) - A.N_PRN_PAYMENT + A.DISB_AMOUNT,
      A.CRYAMT_NOCF2 = C.CRYAMT_NOCF2 + ( (
                       CASE WHEN A.INTCALCCODE IN ( '1', '6' )THEN A.I_DAYS / 360 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                            WHEN A.INTCALCCODE IN ( '2', '3' )THEN A.I_DAYS / 365 * C.EIR_NOCF2 / 100 * C.CRYAMT_NOCF2
                            ELSE ( A.M / 1200* C.EIR_NOCF2 * C.CRYAMT_NOCF2 )
                            END ) - A.N_INT_PAYMENT ) - A.N_PRN_PAYMENT + A.DISB_AMOUNT,
*/
				--WITH CF PART
       A.PREV_UNAMORT1 = C.UNAMORT1
      ,A.PREV_UNAMORT2 = C.UNAMORT2
      ,A.PREV_CRYAMT1 = C.CRYAMT1
      ,A.PREV_CRYAMT2 = C.CRYAMT2
      ,A.EIR1 = C.EIR1
      ,A.EIR2 = C.EIR2
      ,A.EIRAMT1 =
				/*  BCA DISABLE BPI
					CASE WHEN (A.COUNTER = 1 AND A.SPECIAL_FLAG = 1) THEN C.EIR1 /100*(DATEDIFF(DAY,A.PREV_PMT_DATE,A.PMT_DATE))* C.CRYAMT1/12/(DATEDIFF(DAY,
						CASE WHEN A.PMT_DATE = EOMONTH(A.PMT_DATE ) THEN EOMONTH(DATEADD(MONTH,-1,A.PMT_DATE )) ELSE DATEADD(MONTH,-1,A.PMT_DATE) END, A.PMT_DATE ))
					ELSE
					*/
				CASE WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * C.EIR1 / 100 * C.CRYAMT1
             WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.EIR1 / 100 * C.CRYAMT1
            ELSE (A.M / 1200 * C.EIR1 * C.CRYAMT1)
						/*  BCA DISABLE BPI END */
             END
				,EIRAMT2 =
				/*  BCA DISABLE BPI
    CASE WHEN (A.COUNTER = 1 AND A.SPECIAL_FLAG = 1) THEN C.EIR2 /100*(DATEDIFF(DAY,A.PREV_PMT_DATE,A.PMT_DATE))* C.CRYAMT2/12/(DATEDIFF(DAY,
        CASE WHEN A.PMT_DATE = EOMONTH(A.PMT_DATE ) THEN EOMONTH(DATEADD(MONTH,-1,A.PMT_DATE )) ELSE DATEADD(MONTH,-1,A.PMT_DATE) END, A.PMT_DATE ))
    ELSE
      */
				CASE WHEN A.INTCALCCODE IN ('1','6') THEN A.I_DAYS / 360 * C.EIR2 / 100 * C.CRYAMT2
             WHEN A.INTCALCCODE IN ('2','3') THEN A.I_DAYS / 365 * C.EIR2 / 100 * C.CRYAMT2
             ELSE (A.M / 1200 * C.EIR2 * C.CRYAMT2)
             END
			/*  BCA DISABLE BPI END */
			--,
			/*20170912, REMARK KATA YACOP
                A.AMORT1 = ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                                  THEN A.I_DAYS
                                       / 360 * C.EIR1 / 100
                                       * C.CRYAMT1
                                  WHEN A.INTCALCCODE IN ( '2', '3' )
                                  THEN A.I_DAYS
                                       / 365 * C.EIR1 / 100
                                       * C.CRYAMT1
                                  ELSE ( A.M
                                         / 1200 * C.EIR1
                                         * C.CRYAMT1 )
                             END ) - A.N_INT_PAYMENT ,
                A.AMORT2 = ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                                  THEN A.I_DAYS
                                       / 360 * C.EIR2 / 100
                                       * C.CRYAMT2
                                  WHEN A.INTCALCCODE IN ( '2', '3' )
                                  THEN A.I_DAYS
                                       / 365 * C.EIR2 / 100
                                       * C.CRYAMT2
                                  ELSE ( A.M
                                         / 1200 * C.EIR2
                                         * C.CRYAMT2 )
                             END ) - A.N_INT_PAYMENT ,
                A.UNAMORT1 = ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                                      THEN A.I_DAYS
                                           / 360 * C.EIR1
                                           / 100 * C.CRYAMT1
                                      WHEN A.INTCALCCODE IN ( '2', '3' )
                                      THEN A.I_DAYS
                                           / 365 * C.EIR1
                                           / 100 * C.CRYAMT1
                                      ELSE ( A.M
                                             / 1200 * C.EIR1
                                             * C.CRYAMT1 )
                                 END ) - A.N_INT_PAYMENT ) + C.UNAMORT1 ,
                A.UNAMORT2 = ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                                      THEN A.I_DAYS
                                           / 360 * C.EIR2
                                           / 100 * C.CRYAMT2
                                      WHEN A.INTCALCCODE IN ( '2', '3' )
                                      THEN A.I_DAYS
                                           / 365 * C.EIR2
                                           / 100 * C.CRYAMT2
                                      ELSE ( A.M
                                             / 1200 * C.EIR2
                                             * C.CRYAMT2 )
                                 END ) - A.N_INT_PAYMENT ) + C.UNAMORT2 ,
                A.CRYAMT1 = C.CRYAMT1
                + ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                           THEN A.I_DAYS / 360
                                * C.EIR1 / 100 * C.CRYAMT1                             WHEN A.INTCALCCODE IN ( '2', '3' )
                           THEN A.I_DAYS / 365
                                * C.EIR1 / 100 * C.CRYAMT1
                           ELSE ( A.M / 1200
                                  * C.EIR1 * C.CRYAMT1 )
                      END ) - A.N_INT_PAYMENT ) - A.N_PRN_PAYMENT + A.DISB_AMOUNT,
                A.CRYAMT2 = C.CRYAMT2
                + ( ( CASE WHEN A.INTCALCCODE IN ( '1', '6' )
                           THEN A.I_DAYS / 360
                                * C.EIR2 / 100 * C.CRYAMT2
                           WHEN A.INTCALCCODE IN ( '2', '3' )
                           THEN A.I_DAYS / 365
                                * C.EIR2 / 100 * C.CRYAMT2
                           ELSE ( A.M / 1200
                                  * C.EIR2 * C.CRYAMT2 )
                      END ) - A.N_INT_PAYMENT ) - A.N_PRN_PAYMENT + A.DISB_AMOUNT
*/
			/*REPLACE CODE 20160525*/
      ;
      COMMIT;

			/*REPLACE CODE 20160525*/
			/* REMARKS 20160525
         FROM PSAK_TMP_GS3 C
         WHERE C.PMT_DATE = DBO.IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE
    AND DBO.IFRS_LBM_ACCT_EIR_PAYM_GS.MASTERID = C.MASTERID
  */
			INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
			VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','5');


      MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
      USING IFRS_LBM_GS_DATE1 B
      ON (A.MASTERID=B.MASTERID AND A.COUNTER=V_COUNTER)
      WHEN MATCHED THEN
      UPDATE
      SET --WITHOUT CF PART
				A.AMORT_NOCF1 = EIRAMT_NOCF1 - N_INT_PAYMENT
				,A.AMORT_NOCF2 = EIRAMT_NOCF2 - N_INT_PAYMENT
				,A.UNAMORT_NOCF1 = (EIRAMT_NOCF1 - N_INT_PAYMENT) + PREV_UNAMORT_NOCF1
				,A.UNAMORT_NOCF2 = (EIRAMT_NOCF2 - N_INT_PAYMENT) + PREV_UNAMORT_NOCF2
				,A.CRYAMT_NOCF1 = PREV_CRYAMT_NOCF1 + (EIRAMT_NOCF1 - N_INT_PAYMENT) - N_PRN_PAYMENT
				,A.CRYAMT_NOCF2 = PREV_CRYAMT_NOCF2 + (EIRAMT_NOCF2 - N_INT_PAYMENT) - N_PRN_PAYMENT
				,
				--WITH CF PART
				A.AMORT1 = EIRAMT1 - N_INT_PAYMENT
				,A.AMORT2 = EIRAMT2 - N_INT_PAYMENT
				,A.UNAMORT1 = (EIRAMT1 - N_INT_PAYMENT) + PREV_UNAMORT1
				,A.UNAMORT2 = (EIRAMT2 - N_INT_PAYMENT) + PREV_UNAMORT2
				,A.CRYAMT1 = PREV_CRYAMT1 + (EIRAMT1 - N_INT_PAYMENT) - N_PRN_PAYMENT
				,A.CRYAMT2 = PREV_CRYAMT2 + (EIRAMT2 - N_INT_PAYMENT) - N_PRN_PAYMENT;
        /*REMARKS.. UPDATE SEKALIAN DIATAS 20160525
         END REMARKS 20160525*/

			INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
			VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','6');

      COMMIT;

			--PREPARE NEXT
			V_COUNTER := V_COUNTER + 1;
				/*REMARKS 200160525
         TRUNCATE TABLE PSAK_GS_DATE2
         INSERT INTO PSAK_GS_DATE2 (MASTERID, PMT_DATE)
              SELECT A.MASTERID, MIN (A.PMT_DATE) DT
                FROM    IFRS_LBM_ACCT_EIR_PAYM_GS A
                     JOIN
                        IFRS_LBM_GS_DATE1 B
                     ON A.PMT_DATE > B.PMT_DATE AND B.MASTERID = A.MASTERID
            GROUP BY A.MASTERID

  TRUNCATE TABLE IFRS_LBM_GS_DATE1
         INSERT INTO IFRS_LBM_GS_DATE1 (MASTERID, PMT_DATE)
            SELECT MASTERID, PMT_DATE FROM PSAK_GS_DATE2

         INSERT INTO IFRS_AMORT_LOG (
                                     DOWNLOAD_DATE,
                                     DTM,
                                     OPS,
                                     PROCNAME,
                                     REMARK)
              VALUES (
                      V_CURRDATE,
                      SYSTIMESTAMP,
                      'DEBUG',
                      'SP_IFRS_LBM_ACCT_EIR_GS_PROCESS',
                      '7')

    REMARKS 200160525*/
		END LOOP;--LOOP;

		--INNER LOOP
		-- GET SUCCESS EIR1
		--WITH CF PART
    COMMIT;

		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_T14';

		INSERT /*+ PARALLEL(8) */ INTO TMP_T14 (
			MASTERID
			,E1
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,C.EIR1
		FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_LBM_GS_DATE1 D ON B.MASTERID = D.MASTERID --ADDING JOIN 20160525
		JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID
			AND ABS(C.UNAMORT1) < 0.01;

    COMMIT;

    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
    USING TMP_T14 C
    ON (A.MASTERID=C.MASTERID
        AND A.EIR IS NULL
      )
    WHEN MATCHED THEN
    UPDATE
    SET A.FINAL_EIR=C.E1;

    COMMIT;

		UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
		SET EIR = FINAL_EIR
		WHERE FINAL_EIR IS NOT NULL
			AND EIR IS NULL;

    COMMIT;

		--WITHOUT CF PART
		EXECUTE IMMEDIATE'TRUNCATE TABLE TMP_T14';

		INSERT /*+ PARALLEL(8) */ INTO TMP_T14 (
			MASTERID
			,E1
			)
		SELECT B.MASTERID
			,C.EIR_NOCF1
		FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_LBM_GS_DATE1 D ON B.MASTERID = D.MASTERID --ADDING JOIN 20160525
		JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID
			AND ABS(C.UNAMORT_NOCF1) < 0.01;

    COMMIT;

    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
    USING TMP_T14 C
    ON (A.MASTERID=C.MASTERID
        AND A.EIR_NOCF IS NULL)
    WHEN MATCHED THEN
    UPDATE
    SET A.FINAL_EIR_NOCF = C.E1;

    COMMIT;



		UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
		SET EIR_NOCF = FINAL_EIR_NOCF
		WHERE FINAL_EIR_NOCF IS NOT NULL
			AND EIR_NOCF IS NULL;

    COMMIT;

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','7B');

		-- SET NEXT EIR
		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS1';

		INSERT /*+ PARALLEL(8) */ INTO TMP_GS1 (
			MASTERID
			,UNAMORT_NOCF1
			,UNAMORT_NOCF2
			,EIR_NOCF1
			,EIR_NOCF2
			,UNAMORT1
			,UNAMORT2
			,EIR1
			,EIR2
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,C.UNAMORT_NOCF1
			,C.UNAMORT_NOCF2
			,C.EIR_NOCF1
			,C.EIR_NOCF2
			,C.UNAMORT1
			,C.UNAMORT2
			,C.EIR1
			,C.EIR2
		FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
		JOIN IFRS_LBM_GS_DATE1 D ON B.MASTERID = D.MASTERID --ADDING JOIN 20160525
		JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
			AND B.MASTERID = C.MASTERID
			AND (
				B.EIR IS NULL
				OR B.EIR_NOCF IS NULL
				);

    COMMIT;


    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
    USING TMP_GS1 C
    ON (A.MASTERID=C.MASTERID
        AND A.EIR IS NULL
        AND A.EIR_NOCF IS NULL)
    WHEN MATCHED THEN
    UPDATE
    SET
    --WITHOUT CF PART
			A.NEXT_EIR_NOCF = NVL(EIR_NOCF, CASE
					WHEN ABS((((C.UNAMORT_NOCF2 - C.UNAMORT_NOCF1) / (C.EIR_NOCF2 - C.EIR_NOCF1)) * C.EIR_NOCF1 - C.UNAMORT_NOCF1) / ((C.UNAMORT_NOCF2 - C.UNAMORT_NOCF1) / (C.EIR_NOCF2 - C.EIR_NOCF1))) > 2000
						THEN 15
					ELSE (((C.UNAMORT_NOCF2 - C.UNAMORT_NOCF1) / (C.EIR_NOCF2 - C.EIR_NOCF1)) * C.EIR_NOCF1 - C.UNAMORT_NOCF1) / ((C.UNAMORT_NOCF2 - C.UNAMORT_NOCF1) / (C.EIR_NOCF2 - C.EIR_NOCF1))
					END)
			,
			--WITH CF PART
			A.NEXT_EIR = NVL(EIR, CASE
					WHEN ABS((((C.UNAMORT2 - C.UNAMORT1) / (C.EIR2 - C.EIR1)) * C.EIR1 - C.UNAMORT1) / ((C.UNAMORT2 - C.UNAMORT1) / (C.EIR2 - C.EIR1))) > 2000
						THEN 15
					ELSE (((C.UNAMORT2 - C.UNAMORT1) / (C.EIR2 - C.EIR1)) * C.EIR1 - C.UNAMORT1) / ((C.UNAMORT2 - C.UNAMORT1) / (C.EIR2 - C.EIR1))
					END);

    COMMIT;



		-- IF NEXT_EIR=EIR1 THEN PROBABLY GS HAS REACH ITS LIMIT SO TERMINATE AS SOON AS POSSIBLE
		--WITH CF PART
    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
    USING TMP_GS1 C
    ON (A.MASTERID=C.MASTERID
        AND A.EIR IS NULL
        AND A.NEXT_EIR=C.EIR1
        AND ABS(C.UNAMORT1)<1
        )
    WHEN MATCHED THEN
    UPDATE
    SET A.FINAL_EIR = NEXT_EIR;

    COMMIT;

		UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
		SET EIR = FINAL_EIR
		WHERE FINAL_EIR IS NOT NULL
			AND EIR IS NULL;

    COMMIT;

		--WITHOUT CF PART
    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
    USING TMP_GS1 C
    ON (A.MASTERID=C.MASTERID
        AND A.EIR_NOCF IS NULL
        AND A.NEXT_EIR_NOCF=C.EIR_NOCF1
        AND ABS(C.UNAMORT_NOCF1)<1
        )
    WHEN MATCHED THEN
    UPDATE
    SET A.FINAL_EIR_NOCF = NEXT_EIR_NOCF;

    COMMIT;


		UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
		SET EIR_NOCF = FINAL_EIR_NOCF
		WHERE FINAL_EIR_NOCF IS NOT NULL
			AND EIR_NOCF IS NULL;

    COMMIT;

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','8');

		--INIT LOOP 1 --SELECT * FROM TMP_GS2
		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_GS2';

    COMMIT;

		INSERT /*+ PARALLEL(8) */ INTO TMP_GS2 (
			MASTERID
			,DTMIN
			,CNTMIN
			,NEXT_EIR
			,NEXT_EIR_NOCF
			,STAFFLOAN
			,BENEFIT
			,FEE_AMT
			,COST_AMT
			,GAIN_LOSS_FEE_AMT --20180417
			,GAIN_LOSS_COST_AMT --20180417
			)
		SELECT /*+ PARALLEL(8) */ B.MASTERID
			,C.DTMIN
			,C.CNTMIN
			,C.NEXT_EIR
			,C.NEXT_EIR_NOCF
			,B.STAFFLOAN
			,B.BENEFIT
			,B.FEE_AMT
			,B.COST_AMT
			,COALESCE(B.GAIN_LOSS_FEE_AMT, 0) --20180417 GAIN LOSS ADJ
			,COALESCE(B.GAIN_LOSS_COST_AMT, 0)
		FROM IFRS_LBM_ACCT_EIR_CF_ECF1 B
		JOIN IFRS_LBM_ACCT_EIR_PAYM_GS_DATE C ON C.MASTERID = B.MASTERID
			AND (
				C.EIR IS NULL
				OR C.EIR_NOCF IS NULL
				);

    COMMIT;

		SELECT COUNT(*) INTO V_VCNT2 FROM TMP_GS2;

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','NOA GS : '||  TO_CHAR (V_VCNT2));


    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
    USING TMP_GS2 B
    ON (A.MASTERID=B.MASTERID
        AND A.COUNTER=B.CNTMIN)
    WHEN MATCHED THEN
    UPDATE
    SET
    --WITHOUT CF PART
		 A.PREV_UNAMORT_NOCF1 = 0
    ,--ZERO UNAMORT
     A.EIR_NOCF1 = B.NEXT_EIR_NOCF
    ,A.EIR_NOCF2 = B.NEXT_EIR_NOCF + (0.001 * B.NEXT_EIR_NOCF)
    ,--WITH CF PART
     A.PREV_UNAMORT1 = CASE WHEN B.STAFFLOAN = 1 AND B.BENEFIT < 0 THEN B.BENEFIT
                            WHEN B.STAFFLOAN = 1 AND B.BENEFIT >= 0THEN 0
                            ELSE B.FEE_AMT - B.GAIN_LOSS_FEE_AMT --201801417
                            END + CASE WHEN B.STAFFLOAN = 1 AND B.BENEFIT <= 0 THEN 0
                                       WHEN B.STAFFLOAN = 1 AND B.BENEFIT > 0 THEN B.BENEFIT
                                       ELSE B.COST_AMT - B.GAIN_LOSS_COST_AMT --201801417
                                       END
			,A.EIR1 = B.NEXT_EIR
			,A.EIR2 = B.NEXT_EIR + (0.001 * B.NEXT_EIR);

      COMMIT;

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','9');


    MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS A
    USING IFRS_LBM_ACCT_EIR_PAYM_GS_DATE C
    ON (A.MASTERID=C.MASTERID
        AND A.COUNTER=C.CNTMIN
        AND (C.EIR IS NULL OR C.EIR_NOCF IS NULL))
    WHEN MATCHED THEN
    UPDATE
    SET
    -- WITHOUT CF PART
			PREV_UNAMORT_NOCF2 = PREV_UNAMORT_NOCF1
			,PREV_CRYAMT_NOCF1 = N_OSPRN_PREV + PREV_UNAMORT_NOCF1
			,PREV_CRYAMT_NOCF2 = N_OSPRN_PREV + PREV_UNAMORT_NOCF1
			,EIRAMT_NOCF1 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
				ELSE (M / 1200 * EIR_NOCF1 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END
			,EIRAMT_NOCF2 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
				ELSE (M / 1200 * EIR_NOCF2 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END
			,AMORT_NOCF1 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
				ELSE (M / 1200 * EIR_NOCF1 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END - N_INT_PAYMENT
			,AMORT_NOCF2 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
				ELSE (M / 1200 * EIR_NOCF2 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END - N_INT_PAYMENT
			,UNAMORT_NOCF1 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
				ELSE (M / 1200 * EIR_NOCF1 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END - N_INT_PAYMENT + PREV_UNAMORT_NOCF1
			,UNAMORT_NOCF2 = CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
				ELSE (M / 1200 * EIR_NOCF2 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
				END - N_INT_PAYMENT + PREV_UNAMORT_NOCF1
			,CRYAMT_NOCF1 = (N_OSPRN_PREV + PREV_UNAMORT_NOCF1) - N_PRN_PAYMENT + (
				CASE
					--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
					WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
							--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
					WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
					ELSE (M / 1200 * EIR_NOCF1 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
					END - N_INT_PAYMENT
				) + DISB_AMOUNT
			,CRYAMT_NOCF2 = (N_OSPRN_PREV + PREV_UNAMORT_NOCF1) - N_PRN_PAYMENT + (
				CASE
					--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
					WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
							--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE
					WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR_NOCF2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1)
					ELSE (M / 1200 * EIR_NOCF2 * (N_OSPRN_PREV + PREV_UNAMORT_NOCF1))
					END - N_INT_PAYMENT
				) + DISB_AMOUNT
			,
			-- WITH CF PART
			PREV_UNAMORT2 = PREV_UNAMORT1
			,PREV_CRYAMT1 = N_OSPRN_PREV + PREV_UNAMORT1
			,PREV_CRYAMT2 = N_OSPRN_PREV + PREV_UNAMORT1
			,EIRAMT1 =
			/*  BCA DISABLE BPI
		   CASE WHEN (IFRS_LBM_ACCT_EIR_PAYM_GS.COUNTER = 1 AND IFRS_LBM_ACCT_EIR_PAYM_GS.SPECIAL_FLAG = 1)
		   THEN EIR1/100*(DATEDIFF(DAY,IFRS_LBM_ACCT_EIR_PAYM_GS.PREV_PMT_DATE,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))* (N_OSPRN_PREV + PREV_UNAMORT1)/12/(DATEDIFF(DAY,
				CASE WHEN IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE = EOMONTH(IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) THEN EOMONTH(DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
        ELSE DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) END, IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
		   ELSE
		   */
			CASE
				--WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6') THEN I_DAYS / 360 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('2','3') THEN I_DAYS / 365 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
				ELSE (M / 1200 * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
					/*  BCA DISABLE BPI END */
				END
			,EIRAMT2 =
			/*  BCA DISABLE BPI
   CASE WHEN (IFRS_LBM_ACCT_EIR_PAYM_GS.COUNTER = 1 AND IFRS_LBM_ACCT_EIR_PAYM_GS.SPECIAL_FLAG = 1)
   THEN EIR2/100*(DATEDIFF(DAY,IFRS_LBM_ACCT_EIR_PAYM_GS.PREV_PMT_DATE,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))* (N_OSPRN_PREV + PREV_UNAMORT2)/12/(DATEDIFF(DAY,
        CASE WHEN IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE = EOMONTH(IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) THEN EOMONTH(DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
        ELSE DATEADD(MONTH,-1,IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE) END, IFRS_LBM_ACCT_EIR_PAYM_GS.PMT_DATE))
   ELSE
        */
        CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
						--WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
				WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
				ELSE (M / 1200 * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT1))
					/*  BCA DISABLE BPI END */
				END
			,AMORT1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                ELSE (M / 1200 * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT
			,AMORT2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                    --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                ELSE (M / 1200 * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT
			,UNAMORT1 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                  WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                  --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                  WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                  ELSE (M / 1200 * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                  END - N_INT_PAYMENT + PREV_UNAMORT1
			,UNAMORT2 = CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                  WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                  --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                  WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                  ELSE (M / 1200 * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT1))
                  END - N_INT_PAYMENT + PREV_UNAMORT1
			,CRYAMT1 =(N_OSPRN_PREV + PREV_UNAMORT1) - N_PRN_PAYMENT + (
                CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR1 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                ELSE (M / 1200 * EIR1 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT
                ) + DISB_AMOUNT
			,CRYAMT2 =(N_OSPRN_PREV + PREV_UNAMORT1) - N_PRN_PAYMENT + (
                CASE --WHEN INTCALCCODE IN ('2','6') REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('1','6')THEN I_DAYS / 360 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                --WHEN INTCALCCODE = '3' REMARKS FOR ALIGN WITH ICC PAYMENT SCHEDULE 20160428
                WHEN INTCALCCODE IN ('2','3')THEN I_DAYS / 365 * EIR2 / 100 * (N_OSPRN_PREV + PREV_UNAMORT1)
                ELSE (M / 1200 * EIR2 * (N_OSPRN_PREV + PREV_UNAMORT1))
                END - N_INT_PAYMENT
                ) + DISB_AMOUNT;

    COMMIT;

		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','9B');

		EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LBM_GS_DATE1';

    COMMIT;

		INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_GS_DATE1 (
			MASTERID
			,PMT_DATE
			,PERIOD
			)
		SELECT /*+ PARALLEL(8) */ MASTERID
			,DTMIN
			,PERIOD
		FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
		WHERE (
				EIR IS NULL
				OR EIR_NOCF IS NULL
				);

    COMMIT;

		/*REMARKS 20160525
           SELECT A.MASTERID, MIN (A.PMT_DATE) DT
             FROM    IFRS_LBM_ACCT_EIR_PAYM_GS A
                  JOIN
                     IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
                  ON     A.PMT_DATE > B.DTMIN
                     AND A.MASTERID = B.MASTERID
                     AND B.EIR IS NULL
         GROUP BY A.MASTERID
   END REMARKS 20160525*/
		INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
		VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','10');

    COMMIT;
	END LOOP;

  COMMIT;

	--OUTER LOOP
	-- GET SUCCESS EIR1 LAST LOOP
	--WITH CF PART
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
  USING (SELECT B.MASTERID,C.EIR1
          FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
          JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
            AND B.MASTERID = C.MASTERID
            AND ABS(C.UNAMORT1) < 1
		) B
  ON (A.MASTERID=B.MASTERID
      AND A.EIR IS NULL)
  WHEN MATCHED THEN
  UPDATE
  SET A.FINAL_EIR = B.EIR1;

  COMMIT;


	UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	SET EIR = FINAL_EIR
	WHERE FINAL_EIR IS NOT NULL
		AND EIR IS NULL;

  COMMIT;


	--WITHOUT CF PART
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
  USING  (SELECT B.MASTERID,C.EIR_NOCF1
          FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
          JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
            AND B.MASTERID = C.MASTERID
            AND ABS(C.UNAMORT_NOCF1) < 1
		) B
  ON (A.MASTERID=B.MASTERID
      AND A.EIR_NOCF IS NULL)
  WHEN MATCHED THEN
  UPDATE
  SET A.FINAL_EIR_NOCF = B.EIR_NOCF1;

  COMMIT;



	UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	SET EIR_NOCF = FINAL_EIR_NOCF
	WHERE FINAL_EIR_NOCF IS NOT NULL
		AND EIR_NOCF IS NULL;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','11');

	-- 20131106 DANIEL S : GET SUCCESS EIR1 LAST LOOP WITH BIG INITIAL UNAMORT
	-- WITH CF PART
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
  USING (SELECT B.MASTERID,C.EIR1,C.EIR_NOCF1
          FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
          JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
            AND B.MASTERID = C.MASTERID
            AND ABS(C.UNAMORT1) < 10
		) B
  ON (A.MASTERID=B.MASTERID
      AND A.EIR IS NULL
      AND A.UNAMORT>1000000000)
  WHEN MATCHED THEN
  UPDATE
  SET A.FINAL_EIR = B.EIR1;

  COMMIT;


	UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	SET EIR = FINAL_EIR
	WHERE FINAL_EIR IS NOT NULL
		AND EIR IS NULL;

  COMMIT;


	-- WITHOUT CF PART
  MERGE INTO IFRS_LBM_ACCT_EIR_PAYM_GS_DATE A
  USING (SELECT B.MASTERID,C.EIR_NOCF1
          FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE B
          JOIN IFRS_LBM_ACCT_EIR_PAYM_GS C ON C.COUNTER = B.CNTMAX --C.PMT_DATE = B.DTMAX
            AND B.MASTERID = C.MASTERID
            AND ABS(C.UNAMORT_NOCF1) < 10
		) B
  ON (A.MASTERID=B.MASTERID
      AND A.EIR_NOCF IS NULL
      AND A.UNAMORT_NOCF > 1000000000)
  WHEN MATCHED THEN
  UPDATE
  SET A.FINAL_EIR_NOCF = B.EIR_NOCF1;

  COMMIT;


	UPDATE /*+ PARALLEL(8) */ IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	SET EIR_NOCF = FINAL_EIR_NOCF
	WHERE FINAL_EIR_NOCF IS NOT NULL
		AND EIR_NOCF IS NULL;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','12');

	-- FAILED GOAL SEEK WITH CF PART
	INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_FAILED_GS (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		)
	SELECT V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,SYSTIMESTAMP
	FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	WHERE EIR IS NULL;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','13');

	-- SUCCESS GOAL SEEK WITH CF PART
	INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_GS_RESULT (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		,EIR
		)
	SELECT V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,SYSTIMESTAMP
		,EIR
	FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	WHERE EIR IS NOT NULL;

  COMMIT;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','14');

	-- FAILED GOAL SEEK WITHOUT CF PART
	INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_FAILED_GS4 (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		)
	SELECT V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,SYSTIMESTAMP
	FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	WHERE EIR_NOCF IS NULL;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','15');

    COMMIT;

	-- SUCCESS GOAL SEEK WITHOUT CF PART
	INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_GS_RESULT4 (
		DOWNLOAD_DATE
		,MASTERID
		,CREATEDBY
		,CREATEDDATE
		,EIR
		)
	SELECT V_CURRDATE
		,MASTERID
		,'EIR_GS'
		,SYSTIMESTAMP
		,EIR_NOCF
	FROM IFRS_LBM_ACCT_EIR_PAYM_GS_DATE
	WHERE EIR_NOCF IS NOT NULL;

	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
	VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_ACCT_EIR_GS_PROCESS','');

    COMMIT;
END;