CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_EXCLUDE_PR(v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    INSERT INTO GTMP_IFRS_MASTER_ACCOUNT
    (
        PKID,
        DOWNLOAD_DATE,
        MASTERID,
        MASTER_ACCOUNT_CODE,
        CUSTOMER_NUMBER,
        ACCOUNT_NUMBER
    )
    SELECT A.PKID,
        A.DOWNLOAD_DATE,
        A.MASTERID,
        ' ' MASTER_ACCOUNT_CODE,
        A.CUSTOMER_NUMBER,
        A.ACCOUNT_NUMBER
    FROM TMP_IMA_PARTIAL A
    WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND BI_COLLECTABILITY = 'C';

    COMMIT;

    DELETE IFRS_ECL_RESULT_DETAIL_CALC_PR
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
    AND ECL_MODEL_ID = v_ECLID
    AND MASTERID IN
    (SELECT MASTERID FROM GTMP_IFRS_MASTER_ACCOUNT)
    AND COUNTER_PAYSCHD > 1;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_CALC_PR A
    USING GTMP_IFRS_MASTER_ACCOUNT B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        A.PD_RATE = 0,
        A.LGD_RATE = 0,
        A.DISCOUNT_RATE = 0,
        A.EAD_AMOUNT = 0,
        A.PREPAYMENT_RATE = 0,
        A.PREPAYMENT_AMOUNT = 0,
        A.CCF_RATE = 0,
        A.CCF_AMOUNT = 0,
        A.ECL_AMOUNT = 0;

    COMMIT;

    MERGE INTO IFRS_ECL_RESULT_DETAIL_PR A
    USING
    (   SELECT A2.MASTERID, B2.ECL_AMOUNT
        FROM GTMP_IFRS_MASTER_ACCOUNT A2
        JOIN IFRS_ECL_RESULT_DETAIL_CALC_PR B2
        ON B2.DOWNLOAD_DATE = v_DOWNLOADDATE
        AND B2.ECL_MODEL_ID = v_ECLID
        AND A2.MASTERID = B2.MASTERID
    ) B
    ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
    AND A.ECL_MODEL_ID = v_ECLID
    AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
    UPDATE SET
        A.CCF_AMOUNT = 0,
        A.PREPAYMENT_AMOUNT = 0,
        A.ECL_AMOUNT = 0,
        A.SPECIAL_REASON = 'EXCLUDE BI COLLECTABILITY C';

    COMMIT;

END;