CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_UPDATE_MULT_PR(v_ECLID NUMBER DEFAULT (0), v_DOWNLOADDATE DATE DEFAULT NULL)
AS

BEGIN
    UPDATE IFRS_MASTER_ACCOUNT IMA
    SET IMA.RESERVED_RATE_8 = 1
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
    AND DATA_SOURCE IN ('KTP','BTRD');

    COMMIT;

    MERGE INTO IFRS_MASTER_ACCOUNT A
	USING (
		SELECT DISTINCT SUBSTR(SWIFT_CODE,1,8) SWIFT_CODE,  NVL(MULTIPLIER,1) MULTIPLIER
		FROM TBLU_RATING_BANK
		WHERE DOWNLOAD_DATE = (SELECT MAX(DOWNLOAD_DATE) FROM TBLU_RATING_BANK WHERE DOWNLOAD_DATE <= v_DOWNLOADDATE)
	)B
	ON (B.SWIFT_CODE = SUBSTR(A.RESERVED_VARCHAR_1,1,8) AND A.DOWNLOAD_DATE = v_DOWNLOADDATE)
	WHEN MATCHED THEN
		UPDATE SET A.RESERVED_RATE_8 = B.MULTIPLIER
	WHERE  ((A.DATA_SOURCE = 'KTP' AND PRODUCT_CODE LIKE 'PLACEMENT%') OR (A.DATA_SOURCE = 'RKN'));
    COMMIT;

	MERGE INTO IFRS_MASTER_ACCOUNT A
	USING (
		SELECT DISTINCT SUBSTR(SWIFT_CODE,1,8) SWIFT_CODE,  NVL(MULTIPLIER,1) MULTIPLIER
		FROM TBLU_RATING_BANK
		WHERE DOWNLOAD_DATE = (SELECT MAX(DOWNLOAD_DATE) FROM TBLU_RATING_BANK WHERE DOWNLOAD_DATE <= v_DOWNLOADDATE)
	)B
	ON (B.SWIFT_CODE = SUBSTR(A.RESERVED_VARCHAR_15,1,8) AND A.DOWNLOAD_DATE = v_DOWNLOADDATE)
	WHEN MATCHED THEN
		UPDATE SET A.RESERVED_RATE_8 = B.MULTIPLIER
	WHERE  (DATA_SOURCE ='BTRD' AND RESERVED_VARCHAR_23 IN ('2','3')) OR (DATA_SOURCE = 'BTRD' AND RESERVED_VARCHAR_23 IN ('4','5') AND RESERVED_FLAG_10 = 1) OR DATA_SOURCE IN ('ILS','LIMIT');
	COMMIT;

END;