CREATE OR REPLACE PROCEDURE SP_IFRS_PPR_OUTSTANDING
AS
BEGIN

    MERGE INTO IFRS_PPR_OUTSTANDING D
    USING (
            SELECT
                MIN(DOWNLOAD_DATE) DOWNLOAD_DATE,
                XX.ACCOUNT_NUMBER,
                XX.OUTSTANDING
            FROM (
                SELECT
                    ACCOUNT_NUMBER,
                    OUTSTANDING
                FROM IFRS_MASTER_ACCOUNT_MONTHLY
                WHERE ACCOUNT_STATUS = 'C'
                    AND DATA_SOURCE = 'ILS'
                    AND OUTSTANDING = 0
            )XX
            INNER JOIN IFRS_MASTER_ACCOUNT_MONTHLY B ON XX.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                AND XX.OUTSTANDING=B.OUTSTANDING
            GROUP BY XX.ACCOUNT_NUMBER,XX.OUTSTANDING
           ) S ON (D.DOWNLOAD_DATE=S.DOWNLOAD_DATE
                AND D.ACCOUNT_NUMBER=S.ACCOUNT_NUMBER)
    WHEN NOT MATCHED THEN
    INSERT (DOWNLOAD_DATE,
            ACCOUNT_NUMBER,
            OUTSTANDING)
    VALUES (S.DOWNLOAD_DATE,
            S.ACCOUNT_NUMBER,
            S.OUTSTANDING);
    COMMIT;
END;