CREATE OR REPLACE PROCEDURE  SP_IFRS_LI_SYNC_PRODUCT_PARAM
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;

BEGIN
    SELECT MAX(CURRDATE)
          , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_LI_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LI_SYNC_PRODUCT_PARAM','');

    --  PRE-PROCESS EXTRACT CURRENCY ALL AND SYNC SEGMENT
    --    EXEC SP_EXTRACT_ALL_CCY_PARAM
    --  EXEC SP_SYNC_MASTER_SEGMENT BCAF NO NEED
    --  END PRE-PROCESS EXTRACT CURRENCY ALL AND SYNC SEGMENT
    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LI_PRODUCT_PARAM';

    INSERT INTO IFRS_LI_PRODUCT_PARAM (
        DATA_SOURCE
        ,PRD_TYPE
        ,PRD_CODE
        ,PRD_GROUP
        ,MARKET_RATE
        ,CCY
        ,AMORT_TYPE
        ,IS_STAF_LOAN
        ,IS_IMPAIRED
        ,PRODUCT_DESCRIPTION
        ,FEE_MAT_AMT
        ,COST_MAT_AMT
        ,EXPECTED_LIFE
        ,FEE_MAT_TYPE
        ,COST_MAT_TYPE
        ,FLAG_AL
	,LIABILITES_CLASSIFICATION
        )
    SELECT DATA_SOURCE
		,PRD_TYPE
		,PRD_CODE
		,PRD_GROUP
		,MKT_INT_RATE AS MARKET_RATE
		,CCY
		,AMORT_TYPE
		,CASE WHEN STAFF_LOAN_IND = 1 THEN 'Y' ELSE 'N' END
		,IS_IMPAIRED  ----ADD CTBC
		,PRD_DESC
		,ORG_FEE_MAT_AMT
		,TXN_COST_MAT_AMT
		,EXP_LIFE
		,ORG_FEE_MAT_TYPE
		,TXN_COST_MAT_TYPE
		,INST_CLS_VALUE
		,LIABILITES_CLASSIFICATION
    FROM IFRS_MASTER_PRODUCT_PARAM
    WHERE INST_CLS_VALUE = 'L';



    -- SET IAS CLASS
    MERGE INTO IFRS_LI_MASTER_ACCOUNT IMA
    USING IFRS_LI_PRODUCT_PARAM IMPP
    ON (IMPP.DATA_SOURCE = IMA.DATA_SOURCE
        AND IMPP.PRD_TYPE = IMA.PRODUCT_TYPE
        AND IMPP.PRD_CODE = IMA.PRODUCT_CODE
        AND (IMPP.CCY = IMA.CURRENCY OR IMPP.CCY = 'ALL')
        AND IMA.DOWNLOAD_DATE = V_CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET IMA.IAS_CLASS = IMPP.FLAG_AL;

    -- SET STAFF LOAN FLAG
    MERGE INTO IFRS_LI_MASTER_ACCOUNT A
    USING (
        SELECT DISTINCT DATA_SOURCE
            ,PRD_TYPE
            ,PRD_CODE
        FROM IFRS_LI_PRODUCT_PARAM
        WHERE IS_STAF_LOAN = 'Y'
        ) B
    ON (A.DATA_SOURCE = B.DATA_SOURCE
        AND A.PRODUCT_TYPE = B.PRD_TYPE
        AND A.PRODUCT_CODE = B.PRD_CODE
        AND A.DOWNLOAD_DATE = V_CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET STAFF_LOAN_FLAG = 1;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LI_SYNC_PRODUCT_PARAM','');

    COMMIT;
END;