CREATE OR REPLACE PROCEDURE SP_IFRS_REPORT_ECL_MOVE_VALAS (
   V_CURRDATE    DATE DEFAULT '1-JAN-2019',
   V_PREVDATE    DATE DEFAULT '1-JAN-2019')
AS
BEGIN
    SP_IFRS_INS_GTMP_NOMI_CUR_PRE (V_CURRDATE);

    COMMIT;

    DELETE FROM IFRS_REPORT_ECL_MOVE_VALAS_DTL WHERE REPORT_DATE = V_CURRDATE;
    COMMIT;

---- UPDATE NILAI UNTUK WO CRD 2022-08-18
/*
      MERGE INTO GTMP_NOMINATIVE_CURR_PREV UPD
      USING (select CURR.MASTERID,
                    CURR.REPORT_DATE,
                    NVL(PREV.OUTSTANDING_ON_BS_CCY,0) OUTSTANDING_ON_BS_CCY,
                    NVL(PREV.ECL_TOTAL_CCY,0) ECL_TOTAL_CCY,
                    NVL(PREV.ECL_OFF_BS_LCL,0) ECL_OFF_BS_LCL,
                    NVL(PREV.ECL_OFF_BS_CCY,0) ECL_OFF_BS_CCY,
                    NVL(PREV.RESERVED_AMOUNT_2,0) RESERVED_AMOUNT_2,
                    NVL(PREV.RESERVED_AMOUNT_3,0) RESERVED_AMOUNT_3,
                    NVL(PREV.RESERVED_AMOUNT_4,0) RESERVED_AMOUNT_4,
                    NVL(PREV.RESERVED_AMOUNT_5,0) RESERVED_AMOUNT_5,
                    NVL(PREV.RESERVED_AMOUNT_6,0) RESERVED_AMOUNT_6,
                    NVL(PREV.RESERVED_AMOUNT_6_CCY,0) RESERVED_AMOUNT_6_CCY,
                    NVL(PREV.UNUSED_AMT_CCY,0) UNUSED_AMT_CCY,
                    NVL(PREV.UNUSED_AMT_LCL,0) UNUSED_AMT_LCL,
                    NVL(PREV.OUTSTANDING_ON_BS_LCL,0) OUTSTANDING_ON_BS_LCL,
                    NVL(PREV.OUTSTANDING_OFF_BS_LCL,0) OUTSTANDING_OFF_BS_LCL,
                    NVL(PREV.OUTSTANDING_OFF_BS_CCY,0) OUTSTANDING_OFF_BS_CCY,
                    NVL(PREV.UNAMORT_FEE_AMT_CCY,0) UNAMORT_FEE_AMT_CCY,
                    NVL(PREV.UNAMORT_FEE_AMT_LCL,0) UNAMORT_FEE_AMT_LCL,
                    NVL(PREV.UNAMORT_FEE_AMT_ILS_CCY,0) UNAMORT_FEE_AMT_ILS_CCY,
                    NVL(PREV.UNAMORT_FEE_AMT_ILS_LCL,0) UNAMORT_FEE_AMT_ILS_LCL,
                    NVL(PREV.IA_UNWINDING_INTEREST_CCY,0) IA_UNWINDING_INTEREST_CCY,
                    NVL(PREV.IA_UNWINDING_INTEREST_LCL,0) IA_UNWINDING_INTEREST_LCL
               from GTMP_NOMINATIVE_CURR_PREV CURR,
                    GTMP_NOMINATIVE_CURR_PREV PREV
              where CURR.MASTERID = PREV.MASTERID
                AND PREV.REPORT_DATE = V_PREVDATE
                AND CURR.report_date = V_CURRDATE
                and (CURR.DATA_SOURCE = 'CRD' AND
                    (CURR.WRITEOFF_FLAG = 'Y' OR CURR.ACCOUNT_STATUS = 'W') AND
                    (NVL(CURR.outstanding_on_bs_ccy, 0) = 0))
                AND NOT EXISTS
              (SELECT 1
                       FROM IFRS_MASTER_WO_CRD_CHARGE STG
                      WHERE STG.DOWNLOAD_DATE = V_CURRDATE
                        AND CURR.CUSTOMER_NUMBER =
                            SUBSTR(STG.CUSTOMER_NUMBER, 6, 11))) DAT
      ON (UPD.MASTERID = DAT.MASTERID AND UPD.REPORT_DATE = DAT.REPORT_DATE)
      WHEN MATCHED THEN
        UPDATE
           SET OUTSTANDING_ON_BS_CCY = DAT.OUTSTANDING_ON_BS_CCY,
               --ECL_TOTAL_CCY = DAT.ECL_TOTAL_CCY,
               --ECL_OFF_BS_LCL = DAT.ECL_OFF_BS_LCL,
               --ECL_OFF_BS_CCY = DAT.ECL_OFF_BS_CCY,
               --RESERVED_AMOUNT_2 = DAT.RESERVED_AMOUNT_2,
               --RESERVED_AMOUNT_3 = DAT.RESERVED_AMOUNT_3,
               --RESERVED_AMOUNT_4 = DAT.RESERVED_AMOUNT_4,
               --RESERVED_AMOUNT_5 = DAT.RESERVED_AMOUNT_5,
               --RESERVED_AMOUNT_6 = DAT.RESERVED_AMOUNT_6,
               RESERVED_AMOUNT_6_CCY = DAT.RESERVED_AMOUNT_6_CCY;
               --UNUSED_AMT_CCY = DAT.UNUSED_AMT_CCY,
               --UNUSED_AMT_LCL = DAT.UNUSED_AMT_LCL,
               --OUTSTANDING_ON_BS_LCL = DAT.OUTSTANDING_ON_BS_LCL,
               --OUTSTANDING_OFF_BS_LCL = DAT.OUTSTANDING_OFF_BS_LCL,
               --OUTSTANDING_OFF_BS_CCY = DAT.OUTSTANDING_OFF_BS_CCY,
               --UNAMORT_FEE_AMT_CCY = DAT.UNAMORT_FEE_AMT_CCY,
               --UNAMORT_FEE_AMT_LCL = DAT.UNAMORT_FEE_AMT_LCL,
               --UNAMORT_FEE_AMT_ILS_CCY = DAT.UNAMORT_FEE_AMT_ILS_CCY,
               --UNAMORT_FEE_AMT_ILS_LCL = DAT.UNAMORT_FEE_AMT_ILS_LCL,
               --IA_UNWINDING_INTEREST_CCY = DAT.IA_UNWINDING_INTEREST_CCY,
               --IA_UNWINDING_INTEREST_LCL = DAT.IA_UNWINDING_INTEREST_LCL;

commit;


      MERGE INTO GTMP_NOMINATIVE_CURR_PREV UPD
      USING (SELECT STG.DOWNLOAD_DATE REPORT_DATE,
             PREV.MASTERID,
             NVL(STG.WRITEOFF_AMOUNT, 0) WRITEOFF_AMOUNT
               FROM IFRS_MASTER_WO_CRD_CHARGE STG, GTMP_NOMINATIVE_CURR_PREV PREV
              WHERE STG.DOWNLOAD_DATE = V_CURRDATE
                AND PREV.REPORT_DATE = V_PREVDATE
                AND PREV.CUSTOMER_NUMBER = SUBSTR(STG.customer_number, 6, 11)
                AND (PREV.DATA_SOURCE = 'CRD' AND
                    (PREV.WRITEOFF_FLAG = 'Y' OR PREV.ACCOUNT_STATUS = 'W') AND
                    (NVL(PREV.outstanding_on_bs_ccy, 0) = 0))) DAT
      ON (UPD.MASTERID = DAT.MASTERID AND UPD.REPORT_DATE = DAT.REPORT_DATE)
      WHEN MATCHED THEN
        UPDATE
           SET OUTSTANDING_ON_BS_CCY = DAT.WRITEOFF_AMOUNT,
               --ECL_TOTAL_CCY = DAT.WRITEOFF_AMOUNT,
               --ECL_OFF_BS_LCL = DAT.WRITEOFF_AMOUNT,
               --ECL_OFF_BS_CCY = DAT.WRITEOFF_AMOUNT,
               --RESERVED_AMOUNT_2 = DAT.WRITEOFF_AMOUNT,
               --RESERVED_AMOUNT_3 = DAT.WRITEOFF_AMOUNT,
               --RESERVED_AMOUNT_4 = DAT.WRITEOFF_AMOUNT,
               --RESERVED_AMOUNT_5 = DAT.WRITEOFF_AMOUNT,
               --RESERVED_AMOUNT_6 = DAT.WRITEOFF_AMOUNT,
               RESERVED_AMOUNT_6_CCY = DAT.WRITEOFF_AMOUNT;
               --UNUSED_AMT_CCY = DAT.WRITEOFF_AMOUNT,
               --UNUSED_AMT_LCL = DAT.WRITEOFF_AMOUNT,
               --OUTSTANDING_ON_BS_LCL = DAT.WRITEOFF_AMOUNT,
               --OUTSTANDING_OFF_BS_LCL = DAT.WRITEOFF_AMOUNT,
               --OUTSTANDING_OFF_BS_CCY = DAT.WRITEOFF_AMOUNT,
               --UNAMORT_FEE_AMT_CCY = DAT.WRITEOFF_AMOUNT,
               --UNAMORT_FEE_AMT_LCL = DAT.WRITEOFF_AMOUNT,
               --UNAMORT_FEE_AMT_ILS_CCY = DAT.WRITEOFF_AMOUNT,
               --UNAMORT_FEE_AMT_ILS_LCL = DAT.WRITEOFF_AMOUNT,
               --IA_UNWINDING_INTEREST_CCY = DAT.WRITEOFF_AMOUNT,
               --IA_UNWINDING_INTEREST_LCL = DAT.WRITEOFF_AMOUNT;

commit;
*/

---- END UPDATE NILAI UNTUK WO CRD
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_REPORT_ECL_MOVE_VALAS_DTL';

  INSERT INTO TEMP_REPORT_ECL_MOVE_VALAS_DTL
    (CURR_REPORT_DATE,
     CURR_MASTERID,
     CURR_CUSTOMER_NUMBER,
     CURR_CUSTOMER_NAME,
     CURR_ACCOUNT_NUMBER,
     CURR_FACILITY_NUMBER,
     CURR_ACCOUNT_STATUS,
     CURR_DATA_SOURCE,
     CURR_SUB_SEGMENT,
     CURR_POCI_FLAG,
     CURR_STAGE,
     CURR_CURRENCY,
     CURR_EXCHANGE_RATE,
     CURR_WRITEOFF_FLAG,
     CURR_IMPAIRED_FLAG,
     CURR_SPECIAL_REASON,
     CURR_OUTSTANDING_ON_BS_CCY,
     CURR_ECL_TOTAL_CCY,
     CURR_ECL_OFF_BS_CCY,
     CURR_RESERVED_AMOUNT_2,
     CURR_RESERVED_AMOUNT_4,
     CURR_RESERVED_AMOUNT_6,
     CURR_UNUSED_AMT,
     CURR_PRODUCT_CODE,
     CURR_RESERVED_VARCHAR_2,
     CURR_RESERVED_VARCHAR_5,
     CURR_RESERVED_FLAG_1,
     CURR_RESERVED_FLAG_2,
     CURR_OUTSTANDING_OFF_BS_CCY,
     CURR_UNAMORT_FEE_AMT_CCY,
     CURR_IA_UNWINDING_INTEREST_CCY,
     PREV_REPORT_DATE,
     PREV_MASTERID,
     PREV_CUSTOMER_NUMBER,
     PREV_CUSTOMER_NAME,
     PREV_ACCOUNT_NUMBER,
     PREV_FACILITY_NUMBER,
     PREV_ACCOUNT_STATUS,
     PREV_DATA_SOURCE,
     PREV_SUB_SEGMENT,
     PREV_POCI_FLAG,
     PREV_STAGE,
     PREV_CURRENCY,
     PREV_EXCHANGE_RATE,
     PREV_WRITEOFF_FLAG,
     PREV_IMPAIRED_FLAG,
     PREV_SPECIAL_REASON,
     PREV_OUTSTANDING_ON_BS_CCY,
     PREV_ECL_TOTAL_CCY,
     PREV_ECL_OFF_BS_CCY,
     PREV_RESERVED_AMOUNT_2,
     PREV_RESERVED_AMOUNT_4,
     PREV_RESERVED_AMOUNT_6,
     PREV_UNUSED_AMT,
     PREV_PRODUCT_CODE,
     PREV_RESERVED_VARCHAR_2,
     PREV_RESERVED_VARCHAR_5,
     PREV_RESERVED_FLAG_1,
     PREV_RESERVED_FLAG_2,
     PREV_OUTSTANDING_OFF_BS_CCY,
     PREV_UNAMORT_FEE_AMT_CCY,
     PREV_IA_UNWINDING_INTEREST_CCY)
    SELECT DISTINCT CURR_REPORT_DATE,
            CURR_MASTERID,
            CURR_CUSTOMER_NUMBER,
            CURR_CUSTOMER_NAME,
            CURR_ACCOUNT_NUMBER,
            CURR_FACILITY_NUMBER,
            CURR_ACCOUNT_STATUS,
            CURR_DATA_SOURCE,
            CURR_SUB_SEGMENT,
            CURR_POCI_FLAG,
            CURR_STAGE,
            CURR_CURRENCY,
            CURR_EXCHANGE_RATE,
            CURR_WRITEOFF_FLAG,
            CURR_IMPAIRED_FLAG,
            CURR_SPECIAL_REASON,
            CURR_OUTSTANDING_ON_BS_CCY,
            CURR_ECL_TOTAL_CCY,
            CURR_ECL_OFF_BS_CCY,
            CURR_RESERVED_AMOUNT_2,
            CURR_RESERVED_AMOUNT_4,
            CURR_RESERVED_AMOUNT_6,
            CURR_UNUSED_AMT,
            CURR_PRODUCT_CODE,
            CURR_RESERVED_VARCHAR_2,
            CURR_RESERVED_VARCHAR_5,
            CURR_RESERVED_FLAG_1,
            CURR_RESERVED_FLAG_2,
            CURR_OUTSTANDING_OFF_BS_CCY,
            CURR_UNAMORT_FEE_AMT_CCY,
            CURR_IA_UNWINDING_INTEREST_CCY,
            PREV_REPORT_DATE,
            PREV_MASTERID,
            PREV_CUSTOMER_NUMBER,
            PREV_CUSTOMER_NAME,
            PREV_ACCOUNT_NUMBER,
            PREV_FACILITY_NUMBER,
            PREV_ACCOUNT_STATUS,
            PREV_DATA_SOURCE,
            PREV_SUB_SEGMENT,
            PREV_POCI_FLAG,
            PREV_STAGE,
            PREV_CURRENCY,
            PREV_EXCHANGE_RATE,
            PREV_WRITEOFF_FLAG,
            PREV_IMPAIRED_FLAG,
            PREV_SPECIAL_REASON,
            PREV_OUTSTANDING_ON_BS_CCY,
            PREV_ECL_TOTAL_CCY,
            PREV_ECL_OFF_BS_CCY,
            PREV_RESERVED_AMOUNT_2,
            PREV_RESERVED_AMOUNT_4,
            PREV_RESERVED_AMOUNT_6,
            PREV_UNUSED_AMT,
            PREV_PRODUCT_CODE,
            PREV_RESERVED_VARCHAR_2,
            PREV_RESERVED_VARCHAR_5,
            PREV_RESERVED_FLAG_1,
            PREV_RESERVED_FLAG_2,
            PREV_OUTSTANDING_OFF_BS_CCY,
            PREV_UNAMORT_FEE_AMT_CCY,
            PREV_IA_UNWINDING_INTEREST_CCY
    FROM (SELECT REPORT_DATE           CURR_REPORT_DATE,
           MASTERID              CURR_MASTERID,
           CUSTOMER_NUMBER       CURR_CUSTOMER_NUMBER,
           CUSTOMER_NAME         CURR_CUSTOMER_NAME,
           ACCOUNT_NUMBER        CURR_ACCOUNT_NUMBER,
           FACILITY_NUMBER       CURR_FACILITY_NUMBER,
           ACCOUNT_STATUS        CURR_ACCOUNT_STATUS,
           DATA_SOURCE           CURR_DATA_SOURCE,
           SUB_SEGMENT           CURR_SUB_SEGMENT,
           POCI_FLAG             CURR_POCI_FLAG,
           STAGE                 CURR_STAGE,
           CURRENCY              CURR_CURRENCY,
           EXCHANGE_RATE         CURR_EXCHANGE_RATE,
           WRITEOFF_FLAG         CURR_WRITEOFF_FLAG,
           IMPAIRED_FLAG         CURR_IMPAIRED_FLAG,
           SPECIAL_REASON        CURR_SPECIAL_REASON,
           --OUTSTANDING_ON_BS_CCY CURR_OUTSTANDING_ON_BS_CCY,
           CASE WHEN CUR.DATA_SOURCE = 'CRD'
                THEN NVL(CUR.OUTSTANDING_ON_BS_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE <> 0
              THEN NVL(CUR.OUTSTANDING_ON_BS_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE = 0
              THEN 0
                WHEN CUR.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND
                 CUR.ACCOUNT_STATUS = 'A'
              THEN NVL(CUR.OUTSTANDING_ON_BS_CCY, 0)
                WHEN CUR.ACCOUNT_STATUS = 'W'
              THEN NVL(CUR.OUTSTANDING_ON_BS_CCY, 0)
                ELSE 0
           END AS CURR_OUTSTANDING_ON_BS_CCY,

           ECL_TOTAL_CCY         CURR_ECL_TOTAL_CCY,
           ECL_OFF_BS_CCY        CURR_ECL_OFF_BS_CCY,
           RESERVED_AMOUNT_2     CURR_RESERVED_AMOUNT_2,
           RESERVED_AMOUNT_4     CURR_RESERVED_AMOUNT_4,
           --RESERVED_AMOUNT_6     CURR_RESERVED_AMOUNT_6,
           CASE WHEN CUR.DATA_SOURCE = 'CRD'
                THEN NVL(CUR.RESERVED_AMOUNT_6_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE <> 0
              THEN NVL(CUR.RESERVED_AMOUNT_6_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE = 0
              THEN 0
                WHEN CUR.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND
                 CUR.ACCOUNT_STATUS = 'A'
              THEN NVL(CUR.RESERVED_AMOUNT_6_CCY, 0)
                WHEN CUR.ACCOUNT_STATUS = 'W'
              THEN NVL(CUR.RESERVED_AMOUNT_6_CCY, 0)
                ELSE 0
           END AS CURR_RESERVED_AMOUNT_6,
           CASE WHEN CUR.DATA_SOURCE = 'CRD'
                THEN NVL(CUR.UNUSED_AMT_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE <> 0
                THEN NVL(CUR.UNUSED_AMT_CCY, 0)
                WHEN CUR.DATA_SOURCE = 'BTRD' AND CUR.ACCOUNT_STATUS = 'A' AND
                 CUR.BI_CODE = 0
              THEN 0
                WHEN CUR.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND
                 CUR.ACCOUNT_STATUS = 'A'
              THEN NVL(CUR.UNUSED_AMT_CCY, 0)
                WHEN CUR.ACCOUNT_STATUS = 'W'
              THEN NVL(CUR.UNUSED_AMT_CCY, 0)
                ELSE 0
           END AS CURR_UNUSED_AMT,
           PRODUCT_CODE CURR_PRODUCT_CODE,
           RESERVED_VARCHAR_2 CURR_RESERVED_VARCHAR_2,
           RESERVED_VARCHAR_5 CURR_RESERVED_VARCHAR_5,
           RESERVED_FLAG_1 CURR_RESERVED_FLAG_1,
           RESERVED_FLAG_2 CURR_RESERVED_FLAG_2,
           OUTSTANDING_OFF_BS_CCY CURR_OUTSTANDING_OFF_BS_CCY,
           UNAMORT_FEE_AMT_CCY CURR_UNAMORT_FEE_AMT_CCY,
           IA_UNWINDING_INTEREST_CCY CURR_IA_UNWINDING_INTEREST_CCY
        FROM GTMP_NOMINATIVE_CURR_PREV CUR
         WHERE CUR.REPORT_DATE = V_CURRDATE
         AND NVL(CUR.EXCHANGE_RATE, 1) <> 1) CURR
    FULL JOIN (SELECT REPORT_DATE           PREV_REPORT_DATE,
              MASTERID              PREV_MASTERID,
              CUSTOMER_NUMBER       PREV_CUSTOMER_NUMBER,
              CUSTOMER_NAME         PREV_CUSTOMER_NAME,
              ACCOUNT_NUMBER        PREV_ACCOUNT_NUMBER,
              FACILITY_NUMBER       PREV_FACILITY_NUMBER,
              ACCOUNT_STATUS        PREV_ACCOUNT_STATUS,
              DATA_SOURCE           PREV_DATA_SOURCE,
              SUB_SEGMENT           PREV_SUB_SEGMENT,
              POCI_FLAG             PREV_POCI_FLAG,
              STAGE                 PREV_STAGE,
              CURRENCY              PREV_CURRENCY,
              EXCHANGE_RATE         PREV_EXCHANGE_RATE,
              WRITEOFF_FLAG         PREV_WRITEOFF_FLAG,
              IMPAIRED_FLAG         PREV_IMPAIRED_FLAG,
              SPECIAL_REASON        PREV_SPECIAL_REASON,
              --OUTSTANDING_ON_BS_CCY PREV_OUTSTANDING_ON_BS_CCY,
              CASE WHEN PRE.DATA_SOURCE = 'CRD'
                THEN NVL(PRE.OUTSTANDING_ON_BS_CCY, 0)
                WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                 PRE.BI_CODE <> 0
              THEN NVL(PRE.OUTSTANDING_ON_BS_CCY, 0)
                WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                 PRE.BI_CODE = 0
              THEN 0
                WHEN PRE.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND
                 PRE.ACCOUNT_STATUS = 'A'
              THEN NVL(PRE.OUTSTANDING_ON_BS_CCY, 0)
                WHEN PRE.ACCOUNT_STATUS = 'W'
              THEN NVL(PRE.OUTSTANDING_ON_BS_CCY, 0)
                ELSE 0
              END AS PREV_OUTSTANDING_ON_BS_CCY,
              ECL_TOTAL_CCY         PREV_ECL_TOTAL_CCY,
              ECL_OFF_BS_CCY        PREV_ECL_OFF_BS_CCY,
              RESERVED_AMOUNT_2     PREV_RESERVED_AMOUNT_2,
              RESERVED_AMOUNT_4     PREV_RESERVED_AMOUNT_4,
              --RESERVED_AMOUNT_6     PREV_RESERVED_AMOUNT_6,
              CASE WHEN PRE.DATA_SOURCE = 'CRD'
                   THEN NVL(PRE.RESERVED_AMOUNT_6_CCY, 0)
                 WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                      PRE.BI_CODE <> 0
                 THEN NVL(PRE.RESERVED_AMOUNT_6_CCY, 0)
                 WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                      PRE.BI_CODE = 0
                 THEN 0
                 WHEN PRE.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND PRE.ACCOUNT_STATUS = 'A'
                 THEN NVL(PRE.RESERVED_AMOUNT_6_CCY, 0)
                WHEN PRE.ACCOUNT_STATUS = 'W'
              THEN NVL(PRE.RESERVED_AMOUNT_6_CCY, 0)
                 ELSE 0
              END AS PREV_RESERVED_AMOUNT_6,
              CASE WHEN PRE.DATA_SOURCE = 'CRD'
                   THEN NVL(PRE.UNUSED_AMT_CCY, 0)
                 WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                      PRE.BI_CODE <> 0
                 THEN NVL(PRE.UNUSED_AMT_CCY, 0)
                 WHEN PRE.DATA_SOURCE = 'BTRD' AND PRE.ACCOUNT_STATUS = 'A' AND
                      PRE.BI_CODE = 0
                 THEN 0
                 WHEN PRE.DATA_SOURCE NOT IN ('CRD', 'BTRD') AND PRE.ACCOUNT_STATUS = 'A'
                 THEN NVL(PRE.UNUSED_AMT_CCY, 0)
                WHEN PRE.ACCOUNT_STATUS = 'W'
              THEN NVL(PRE.UNUSED_AMT_CCY, 0)
                 ELSE 0
              END AS PREV_UNUSED_AMT,
              PRODUCT_CODE       PREV_PRODUCT_CODE,
              RESERVED_VARCHAR_2 PREV_RESERVED_VARCHAR_2,
              RESERVED_VARCHAR_5 PREV_RESERVED_VARCHAR_5,
              RESERVED_FLAG_1    PREV_RESERVED_FLAG_1,
              RESERVED_FLAG_2    PREV_RESERVED_FLAG_2,
                OUTSTANDING_OFF_BS_CCY PREV_OUTSTANDING_OFF_BS_CCY,
                UNAMORT_FEE_AMT_CCY PREV_UNAMORT_FEE_AMT_CCY,
                IA_UNWINDING_INTEREST_CCY PREV_IA_UNWINDING_INTEREST_CCY
           FROM GTMP_NOMINATIVE_CURR_PREV PRE
          WHERE PRE.REPORT_DATE = V_PREVDATE
            AND NVL(PRE.EXCHANGE_RATE, 1) <> 1
            AND PRE.ACCOUNT_STATUS = 'A') PREV
      ON CURR_MASTERID = PREV_MASTERID;
  COMMIT;


/*
DELETE TEMP_REPORT_ECL_MOVE_VALAS_DTL
WHERE PREV_ACCOUNT_STATUS = 'C'
AND CURR_REPORT_DATE IS NULL;
*/

  DELETE TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE CURR_REPORT_DATE = V_CURRDATE
     AND CURR_ACCOUNT_STATUS IN ('C', 'W')
     AND PREV_REPORT_DATE IS NULL;

  COMMIT;

/*
DELETE TEMP_REPORT_ECL_MOVE_VALAS_DTL
WHERE PREV_ACCOUNT_STATUS IN ('C','W')
AND CURR_ACCOUNT_STATUS IN ('C','W')
AND PREV_ACCOUNT_STATUS = CURR_ACCOUNT_STATUS
AND PREV_REPORT_DATE = V_PREVDATE
AND CURR_REPORT_DATE = V_CURRDATE;
*/

--- ECL BULAN INI = ECL BULAN LALU
  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(CURR_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(CURR_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(CURR_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(CURR_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(CURR_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (nvl(CURR_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) - NVL(CURR_UNAMORT_FEE_AMT_CCY, 0) + NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND PREV_ACCOUNT_STATUS = 'A'
     AND CURR_REPORT_DATE = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'A'
     AND CURR_ACCOUNT_STATUS = PREV_ACCOUNT_STATUS
     AND CURR_ECL_TOTAL_CCY = PREV_ECL_TOTAL_CCY
     AND CURR_STAGE = PREV_STAGE
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND PREV_ACCOUNT_STATUS = 'A'
     AND CURR_REPORT_DATE = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'A'
     AND CURR_ACCOUNT_STATUS = PREV_ACCOUNT_STATUS
     AND CURR_ECL_TOTAL_CCY = PREV_ECL_TOTAL_CCY
     AND CURR_STAGE = PREV_STAGE;

  COMMIT;


  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE PREV_REPORT_DATE = V_PREVDATE
     AND PREV_ACCOUNT_STATUS = 'A'
     AND CURR_REPORT_DATE = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'A'
     AND CURR_ACCOUNT_STATUS = PREV_ACCOUNT_STATUS
     AND CURR_ECL_TOTAL_CCY = PREV_ECL_TOTAL_CCY
     AND CURR_STAGE = PREV_STAGE;
  COMMIT;

---New financial assets originated or purchased
  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       2 AS SEQ_NO,
       'NEW FINANCIAL ASSETS ORIGINATED OR PURCHASED' AS IMP_CHANGE_REASON,
       NVL(CURR_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE AS ECL_ON_BS,
       NVL(CURR_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE AS ECL_OFF_BS,
       NVL(CURR_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE AS ECL_TOTAL,
       NVL(CURR_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE AS CARRY_AMOUNT,
       NVL(CURR_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (nvl(CURR_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) - NVL(CURR_UNAMORT_FEE_AMT_CCY, 0) + NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL C
     WHERE PREV_REPORT_DATE IS NULL
     AND CURR_REPORT_DATE = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'A'
     AND (CURR_RESERVED_FLAG_1 <> 1 AND CURR_RESERVED_FLAG_2 <> 1);
     /*
     AND NOT EXISTS
     (SELECT 1
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL P
         WHERE P.PREV_REPORT_DATE = V_PREVDATE
         AND C.CURR_FACILITY_NUMBER = P.PREV_ACCOUNT_NUMBER);
      */
  COMMIT;

  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL C
   WHERE C.PREV_REPORT_DATE IS NULL
     AND C.CURR_REPORT_DATE = V_CURRDATE
     AND C.CURR_ACCOUNT_STATUS = 'A'
     AND (CURR_RESERVED_FLAG_1 <> 1 AND CURR_RESERVED_FLAG_2 <> 1);
     /*
     AND NOT EXISTS
   (SELECT 1
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL P
       WHERE P.PREV_REPORT_DATE = V_PREVDATE
         AND C.CURR_FACILITY_NUMBER = P.PREV_ACCOUNT_NUMBER);
      */
  COMMIT;


--- STATUS CURRENT CLOSE DAN WO
  EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT_VALAS';

  INSERT INTO GTMP_IFRS_MASTER_ACCOUNT_VALAS
    (PKID,
     DOWNLOAD_DATE,
     MASTERID,
     MASTER_ACCOUNT_CODE,
     DATA_SOURCE,
     GLOBAL_CUSTOMER_NUMBER,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     FACILITY_NUMBER,
     ACCOUNT_NUMBER,
     WRITEOFF_DATE,
     PREVIOUS_ACCOUNT_NUMBER,
     ACCOUNT_STATUS,
     CURRENCY,
     EXCHANGE_RATE)
    SELECT PKID,
       DOWNLOAD_DATE,
       MASTERID,
       MASTER_ACCOUNT_CODE,
       DATA_SOURCE,
       GLOBAL_CUSTOMER_NUMBER,
       CUSTOMER_NUMBER,
       CUSTOMER_NAME,
       FACILITY_NUMBER,
       ACCOUNT_NUMBER,
       WRITEOFF_DATE,
       PREVIOUS_ACCOUNT_NUMBER,
       ACCOUNT_STATUS,
       CURRENCY,
       EXCHANGE_RATE
    FROM IFRS_MASTER_ACCOUNT IMA
     WHERE DOWNLOAD_DATE >= V_PREVDATE
     AND DOWNLOAD_DATE <= V_CURRDATE
     AND EXISTS
     (SELECT 1
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL TMP
         WHERE PREV_REPORT_DATE = V_PREVDATE
         AND NVL(CURR_REPORT_DATE,
             V_CURRDATE) = V_CURRDATE
         AND NVL(CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
         AND PREV_ACCOUNT_STATUS = 'A'
         AND IMA.MASTERID = NVL(TMP.CURR_MASTERID, TMP.PREV_MASTERID))
    UNION
    SELECT PKID,
       DOWNLOAD_DATE,
       MASTERID,
       MASTER_ACCOUNT_CODE,
       DATA_SOURCE,
       GLOBAL_CUSTOMER_NUMBER,
       CUSTOMER_NUMBER,
       CUSTOMER_NAME,
       FACILITY_NUMBER,
       ACCOUNT_NUMBER,
       WRITEOFF_DATE,
       PREVIOUS_ACCOUNT_NUMBER,
       ACCOUNT_STATUS,
       CURRENCY,
       EXCHANGE_RATE
    FROM IFRS_MASTER_ACCOUNT_MONTHLY IMA
     WHERE DOWNLOAD_DATE >= V_PREVDATE
     AND DOWNLOAD_DATE <= V_CURRDATE
     AND EXISTS
     (SELECT 1
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL TMP
         WHERE PREV_REPORT_DATE = V_PREVDATE
         AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
         AND NVL(CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
         AND PREV_ACCOUNT_STATUS = 'A'
         AND IMA.MASTERID = NVL(TMP.CURR_MASTERID, TMP.PREV_MASTERID));

  COMMIT;

  MERGE INTO TEMP_REPORT_ECL_MOVE_VALAS_DTL DTL
  USING (SELECT CLOS.ROWIDS,
          CLOS.CURR_MASTERID,
          CLOS.MASTERID,
          CLOS.CURRENCY,
          CLOS.CLOSE_DATE,
          CLOS.TGL_VALAS,
          RATE.RATE_AMOUNT EXCHANGE_RATE
       FROM (SELECT CLO.ROWIDS,
              CLO.CURR_MASTERID,
              CLO.MASTERID,
              CLO.CURRENCY,
              CLO.CLOSE_DATE,
              MAX(RA.DOWNLOAD_DATE) TGL_VALAS
           FROM (SELECT ROWID ROWIDS,
                  CURR_MASTERID,
                  NVL(CURR_MASTERID, PREV_MASTERID) MASTERID,
                  NVL(CURR_CURRENCY, PREV_CURRENCY) CURRENCY,
                  NVL(CURR_REPORT_DATE, V_CURRDATE) CLOSE_DATE
               FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL VLS
              WHERE PREV_REPORT_DATE = V_PREVDATE
                AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
                AND CURR_ACCOUNT_STATUS IS NULL
                AND PREV_ACCOUNT_STATUS = 'A') CLO,
              IFRS_MASTER_EXCHANGE_RATE RA
          WHERE CLO.CLOSE_DATE >= RA.DOWNLOAD_DATE
            AND CLO.CURRENCY = RA.CURRENCY
          GROUP BY CLO.ROWIDS,
               CLO.CURR_MASTERID,
               CLO.MASTERID,
               CLO.CURRENCY,
               CLO.CLOSE_DATE) CLOS,
          IFRS_MASTER_EXCHANGE_RATE RATE
      WHERE RATE.DOWNLOAD_DATE = CLOS.TGL_VALAS
        AND RATE.CURRENCY = CLOS.CURRENCY) DAT
  ON (DTL.ROWID = DAT.ROWIDS)
  WHEN MATCHED THEN
    UPDATE SET CURR_EXCHANGE_RATE = DAT.EXCHANGE_RATE;

  COMMIT;

  MERGE INTO TEMP_REPORT_ECL_MOVE_VALAS_DTL DTL
  USING (SELECT CLOS.ROWIDS,
          CLOS.CURR_MASTERID,
          CLOS.MASTERID,
          CLOS.CURRENCY,
          CLOS.WRITEOFF_DATE,
          CLOS.TGL_VALAS,
          RATE.RATE_AMOUNT EXCHANGE_RATE
       FROM (SELECT CLO.ROWIDS,
              CLO.CURR_MASTERID,
              CLO.MASTERID,
              CLO.CURRENCY,
              CLO.WRITEOFF_DATE,
              MAX(RA.DOWNLOAD_DATE) TGL_VALAS
           FROM (SELECT VLS.ROWID ROWIDS,
                  CURR_MASTERID,
                  NVL(CURR_MASTERID, PREV_MASTERID) MASTERID,
                  NVL(CURR_CURRENCY, PREV_CURRENCY) CURRENCY,
                  NVL(IMA.WRITEOFF_DATE, NVL(MAX(VA.VALUATION_DATE), V_CURRDATE)) WRITEOFF_DATE
               FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL VLS,
                  GTMP_IFRS_MASTER_ACCOUNT_VALAS IMA LEFT JOIN ifrs_master_valuation VA ON VA.DOWNLOAD_DATE > V_PREVDATE
                                                     AND VA.DOWNLOAD_DATE <= V_CURRDATE
                                                     AND VA.TRX_CODE = 'CHARGEOFF'
                                                     AND VA.ACCOUNT_NUMBER = IMA.ACCOUNT_NUMBER
              WHERE PREV_REPORT_DATE = V_PREVDATE
                AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
                AND CURR_ACCOUNT_STATUS = 'W'
                AND PREV_ACCOUNT_STATUS = 'A'
                AND IMA.MASTERID = NVL(CURR_MASTERID, PREV_MASTERID)
                AND IMA.DOWNLOAD_DATE = V_CURRDATE
                AND IMA.DOWNLOAD_DATE = VLS.CURR_REPORT_DATE
                GROUP BY VLS.ROWID,
                     CURR_MASTERID,
                     CURR_ACCOUNT_NUMBER,
                     CURR_MASTERID,
                     PREV_MASTERID,
                     CURR_CURRENCY,
                     PREV_CURRENCY,
                     IMA.WRITEOFF_DATE ) CLO,
              IFRS_MASTER_EXCHANGE_RATE RA
          WHERE CLO.WRITEOFF_DATE >= RA.DOWNLOAD_DATE
            AND CLO.CURRENCY = RA.CURRENCY
          GROUP BY CLO.ROWIDS,
               CLO.CURR_MASTERID,
               CLO.MASTERID,
               CLO.CURRENCY,
               CLO.WRITEOFF_DATE) CLOS,
          IFRS_MASTER_EXCHANGE_RATE RATE
      WHERE RATE.DOWNLOAD_DATE = CLOS.TGL_VALAS
        AND RATE.CURRENCY = CLOS.CURRENCY) DAT
  ON (DTL.ROWID = DAT.ROWIDS)
  WHEN MATCHED THEN
    UPDATE SET /*WO_EXCHANGE_RATE*/ CURR_EXCHANGE_RATE = DAT.EXCHANGE_RATE;
  COMMIT;

/*
   MERGE INTO TEMP_REPORT_ECL_MOVE_VALAS_DTL DTL
        USING (SELECT VLS.ROWID ROWIDS,
                      IMA.MASTERID,
                      IMA.DOWNLOAD_DATE,
                      VLS.CURR_EXCHANGE_RATE,
                      IMA.EXCHANGE_RATE
                 FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL VLS,
                      GTMP_IFRS_MASTER_ACCOUNT_VALAS IMA,
                      (  SELECT MASTERID, MIN (DOWNLOAD_DATE) DOWNLOAD_DATE
                           FROM GTMP_IFRS_MASTER_ACCOUNT_VALAS
                          WHERE ACCOUNT_STATUS IN ('C', 'W')
                       GROUP BY MASTERID) TGL
                WHERE     IMA.MASTERID = TGL.MASTERID
                      AND IMA.DOWNLOAD_DATE = TGL.DOWNLOAD_DATE
                      AND IMA.MASTERID = NVL (CURR_MASTERID, PREV_MASTERID)
                      AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
                      AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W')
                      AND VLS.CURR_EXCHANGE_RATE <> IMA.EXCHANGE_RATE) DAT
           ON (DTL.ROWID = DAT.ROWIDS)
   WHEN MATCHED
   THEN
      UPDATE SET CURR_EXCHANGE_RATE = DAT.EXCHANGE_RATE;
COMMIT;




MERGE INTO TEMP_REPORT_ECL_MOVE_VALAS_DTL DTL
     USING (SELECT VL.ROWID ROWIDS, K.*, A.RATE_AMOUNT EXCHANGE_RATE
              FROM (  SELECT D.MASTERID,
                             D.CURRENCY,
                             MIN (R.DOWNLOAD_DATE) DOWNLOAD_DATE
                        FROM IFRS_MASTER_EXCHANGE_RATE R,
                             (SELECT MASTERID,
                                     MAX(DOWNLOAD_DATE) + 1 DOWNLOAD_DATE,
                                     CURRENCY
                                FROM GTMP_IFRS_MASTER_ACCOUNT_VALAS VLS
                               WHERE     ACCOUNT_STATUS = 'A'
                                     AND EXISTS
                                            (SELECT 1
                                               FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL TMP
                                              WHERE     PREV_REPORT_DATE = V_PREVDATE
                                                    AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
                                                    AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
                                                    AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W')
                                                    AND CURR_EXCHANGE_RATE IS NULL
                                                    AND VLS.MASTERID = NVL (TMP.CURR_MASTERID, TMP.PREV_MASTERID))
                          GROUP BY MASTERID, CURRENCY )D
                       WHERE     D.CURRENCY = R.CURRENCY
                             AND R.DOWNLOAD_DATE >= D.DOWNLOAD_DATE
                             AND R.DOWNLOAD_DATE <= V_CURRDATE
                    GROUP BY D.MASTERID, D.CURRENCY) K,
                   IFRS_MASTER_EXCHANGE_RATE      A,
                   TEMP_REPORT_ECL_MOVE_VALAS_DTL VL
             WHERE     K.CURRENCY = A.CURRENCY
                   AND K.DOWNLOAD_DATE = A.DOWNLOAD_DATE
                   AND CURR_EXCHANGE_RATE IS NULL
                   AND K.MASTERID = NVL (CURR_MASTERID, PREV_MASTERID)
                   AND PREV_REPORT_DATE = V_PREVDATE
                   AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
                   AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
                   AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W')) DAT
        ON (DTL.ROWID = DAT.ROWIDS)
WHEN MATCHED
THEN
   UPDATE SET CURR_EXCHANGE_RATE = DAT.EXCHANGE_RATE;

COMMIT;
*/

  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       5 AS SEQ_NO,
       'FINANCIAL ASSETS DERECOGNISED DURING THE PERIOD' AS IMP_CHANGE_REASON,
       /*(NVL (PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_2, 0) - NVL(PREV_RESERVED_AMOUNT_2, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       /*(NVL (PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_ECL_OFF_BS_CCY, 0) - NVL(PREV_ECL_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       /*(NVL (PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_4, 0) - NVL(PREV_RESERVED_AMOUNT_4, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       /*(NVL (PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_6, 0) - NVL(PREV_RESERVED_AMOUNT_6, 0)) *
       CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       ((NVL(CURR_UNUSED_AMT, 0) - NVL(PREV_UNUSED_AMT, 0)) *
       CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       --PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN
       NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       ((nvl(CURR_OUTSTANDING_ON_BS_CCY,0) - nvl(PREV_OUTSTANDING_ON_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       ((nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) - nvl(PREV_OUTSTANDING_OFF_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       (((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)-NVL(PREV_OUTSTANDING_ON_BS_CCY, 0)) -
         (NVL(CURR_UNAMORT_FEE_AMT_CCY, 0)- NVL(PREV_UNAMORT_FEE_AMT_CCY, 0)) +
         (NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0)- NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))) *
         CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(CURR_ACCOUNT_STATUS, 'C') = 'C'
     AND PREV_ACCOUNT_STATUS = 'A'
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(CURR_ACCOUNT_STATUS, 'C') = 'C'
     AND PREV_ACCOUNT_STATUS = 'A'
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       NVL(CURR_MASTERID, PREV_MASTERID) AS MASTERID,
       NVL(CURR_CUSTOMER_NUMBER, PREV_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
       NVL(CURR_CUSTOMER_NAME, PREV_CUSTOMER_NAME) AS CUSTOMER_NAME,
       NVL(CURR_ACCOUNT_NUMBER, PREV_ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
       NVL(CURR_DATA_SOURCE, PREV_DATA_SOURCE) AS DATA_SOURCE,
       NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       NVL(CURR_CURRENCY, PREV_CURRENCY) AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN NVL(CURR_POCI_FLAG, PREV_POCI_FLAG) = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       NVL(CURR_WRITEOFF_FLAG, PREV_WRITEOFF_FLAG) AS WRITEOFF_FLAG,
       NVL(CURR_SPECIAL_REASON, PREV_SPECIAL_REASON) AS SPECIAL_REASON,
       NVL(CURR_PRODUCT_CODE, PREV_PRODUCT_CODE) AS PRODUCT_CODE,
       NVL(CURR_RESERVED_VARCHAR_2, PREV_RESERVED_VARCHAR_2) AS TRA,
       NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(CURR_ACCOUNT_STATUS, 'C') = 'C'
     AND PREV_ACCOUNT_STATUS = 'A';
  COMMIT;

  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(CURR_ACCOUNT_STATUS, 'C') = 'C'
     AND PREV_ACCOUNT_STATUS = 'A';

  COMMIT;

  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
/*
    SELECT V_CURRDATE           AS REPORT_DATE,
       PREV_MASTERID        AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME   AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER  AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE     AS DATA_SOURCE,
       --NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       6 AS SEQ_NO,
       'WRITE OFFS' AS IMP_CHANGE_REASON,
       ((NVL(CURR_RESERVED_AMOUNT_2, 0) - NVL(PREV_RESERVED_AMOUNT_2, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       ((NVL(CURR_ECL_OFF_BS_CCY, 0) - NVL(PREV_ECL_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       ((NVL(CURR_RESERVED_AMOUNT_4, 0) - NVL(PREV_RESERVED_AMOUNT_4, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       ((NVL(CURR_RESERVED_AMOUNT_6, 0) - NVL(PREV_RESERVED_AMOUNT_6, 0)) *
       CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       ((NVL(CURR_UNUSED_AMT, 0) - NVL(PREV_UNUSED_AMT, 0)) *
       CURR_EXCHANGE_RATE) AS UNUSED_AMT,

       --(NVL(PREV_RESERVED_AMOUNT_2, 0) * (NVL(WO_EXCHANGE_RATE, 0) - PREV_EXCHANGE_RATE - CURR_EXCHANGE_RATE)) AS ECL_ON_BS,
       --(NVL(PREV_ECL_OFF_BS_CCY, 0) * (NVL(WO_EXCHANGE_RATE, 0) - PREV_EXCHANGE_RATE - CURR_EXCHANGE_RATE)) AS ECL_OFF_BS,
       --(NVL(PREV_RESERVED_AMOUNT_4, 0) * (NVL(WO_EXCHANGE_RATE, 0) - PREV_EXCHANGE_RATE - CURR_EXCHANGE_RATE)) AS ECL_TOTAL,
       --(NVL(PREV_RESERVED_AMOUNT_6, 0) * (NVL(WO_EXCHANGE_RATE, 0) - PREV_EXCHANGE_RATE - CURR_EXCHANGE_RATE)) AS CARRY_AMOUNT,

       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       ((nvl(CURR_OUTSTANDING_ON_BS_CCY,0) - nvl(PREV_OUTSTANDING_ON_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       ((nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) - nvl(PREV_OUTSTANDING_OFF_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       (((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)-NVL(PREV_OUTSTANDING_ON_BS_CCY, 0)) -
         (NVL(CURR_UNAMORT_FEE_AMT_CCY, 0)- NVL(PREV_UNAMORT_FEE_AMT_CCY, 0)) +
         (NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0)- NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))) *
         CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A'
*/
  SELECT V_CURRDATE AS REPORT_DATE,
         CURR_MASTERID AS MASTERID,
         CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
         CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
         CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
         CURR_DATA_SOURCE AS DATA_SOURCE,
         PREV_SUB_SEGMENT AS SUB_SEGMENT,
         6 AS SEQ_NO,
         'WRITE OFFS' AS IMP_CHANGE_REASON,
         case when PREV_RESERVED_AMOUNT_2 = 0
              then 0
              else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_ON_BS,
         case when PREV_ECL_OFF_BS_CCY = 0
              then 0
              else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_OFF_BS,
         case when PREV_RESERVED_AMOUNT_4 = 0
              then 0
              else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_TOTAL,
         case when PREV_RESERVED_AMOUNT_6 = 0
              then 0
              else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS CARRY_AMOUNT,
         case when PREV_UNUSED_AMT = 0
              then 0
              else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,

       case when PREV_OUTSTANDING_ON_BS_CCY = 0
            then 0
            else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_ON_BS,
       case when PREV_OUTSTANDING_OFF_BS_CCY = 0
            then 0
            else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_OFF_BS_LCL,
       case when (NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0)) = 0
            then 0
            else -1 * (NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS NILAI_TERCATAT_ON_BS
 FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
 WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A'

    UNION
      SELECT V_CURRDATE AS REPORT_DATE,
         CURR_MASTERID AS MASTERID,
         CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
         CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
         CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
         CURR_DATA_SOURCE AS DATA_SOURCE,
         PREV_SUB_SEGMENT AS SUB_SEGMENT,
         5 AS SEQ_NO,
         'FINANCIAL ASSETS DERECOGNISED DURING THE PERIOD' AS IMP_CHANGE_REASON,
         case when PREV_RESERVED_AMOUNT_2 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_2,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_ON_BS,
         case when PREV_ECL_OFF_BS_CCY = 0
              then 0
              else -1 * ((NVL(PREV_ECL_OFF_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_OFF_BS,
         case when PREV_RESERVED_AMOUNT_4 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_4,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_TOTAL,
         case when PREV_RESERVED_AMOUNT_6 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_6,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS CARRY_AMOUNT,
         case when PREV_UNUSED_AMT = 0
              then 0
              else -1 * ((NVL(PREV_UNUSED_AMT,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,

       case when PREV_OUTSTANDING_ON_BS_CCY = 0
            then 0
            else -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_ON_BS,
       case when PREV_OUTSTANDING_OFF_BS_CCY = 0
            then 0
            else -1 * ((NVL(PREV_OUTSTANDING_OFF_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_OFF_BS_LCL,
       case when (NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0)) = 0
            then 0
            else -1 * (((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) -
                        NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) +
                        NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0)) -
                        NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) *
                        NVL(CURR_EXCHANGE_RATE, 1))
       end AS NILAI_TERCATAT_ON_BS
 FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
 WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A'
     AND PREV_ECL_TOTAL_CCY >= CURR_OUTSTANDING_ON_BS_CCY
    UNION
      SELECT V_CURRDATE AS REPORT_DATE,
         CURR_MASTERID AS MASTERID,
         CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
         CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
         CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
         CURR_DATA_SOURCE AS DATA_SOURCE,
         PREV_SUB_SEGMENT AS SUB_SEGMENT,
         3 AS SEQ_NO,
         'CHANGES IN MODEL/ RISK PARAMETERS' AS IMP_CHANGE_REASON,
         case when PREV_RESERVED_AMOUNT_2 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_2,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_ON_BS,
         case when PREV_ECL_OFF_BS_CCY = 0
              then 0
              else -1 * ((NVL(PREV_ECL_OFF_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_OFF_BS,
         case when PREV_RESERVED_AMOUNT_4 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_4,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS ECL_TOTAL,
         case when PREV_RESERVED_AMOUNT_6 = 0
              then 0
              else -1 * ((NVL(PREV_RESERVED_AMOUNT_6,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS CARRY_AMOUNT,
         case when PREV_UNUSED_AMT = 0
              then 0
              else -1 * ((NVL(PREV_UNUSED_AMT,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
         end AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,

       case when PREV_OUTSTANDING_ON_BS_CCY = 0
            then 0
            else -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_ON_BS,
       case when PREV_OUTSTANDING_OFF_BS_CCY = 0
            then 0
            else -1 * ((NVL(PREV_OUTSTANDING_OFF_BS_CCY,0)- NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) * NVL(CURR_EXCHANGE_RATE, 1))
       end AS OUTSTANDING_OFF_BS_LCL,
       case when (NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0)) = 0
            then 0
            else -1 * (((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) -
                        NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) +
                        NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0)) -
                        NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)) *
                        NVL(CURR_EXCHANGE_RATE, 1))
       end AS NILAI_TERCATAT_ON_BS
 FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
 WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A'
     AND PREV_ECL_TOTAL_CCY < CURR_OUTSTANDING_ON_BS_CCY
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       /*
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * NVL(WO_EXCHANGE_RATE, 0)) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * NVL(WO_EXCHANGE_RATE, 0)) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * NVL(WO_EXCHANGE_RATE, 0)) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * NVL(WO_EXCHANGE_RATE, 0)) AS CARRY_AMOUNT,
       */
       PREV_CURRENCY AS CURRENCY,
       NVL(WO_EXCHANGE_RATE, 0) AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A'
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       NVL(CURR_MASTERID, PREV_MASTERID) AS MASTERID,
       NVL(CURR_CUSTOMER_NUMBER, PREV_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
       NVL(CURR_CUSTOMER_NAME, PREV_CUSTOMER_NAME) AS CUSTOMER_NAME,
       NVL(CURR_ACCOUNT_NUMBER, PREV_ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
       NVL(CURR_DATA_SOURCE, PREV_DATA_SOURCE) AS DATA_SOURCE,
       NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       NVL(CURR_CURRENCY, PREV_CURRENCY) AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE
         WHEN NVL(CURR_POCI_FLAG, PREV_POCI_FLAG) = 'Y' THEN
        'POCI'
         ELSE
        NVL(PREV_STAGE, '1')
       END AS STAGE,
       NVL(CURR_WRITEOFF_FLAG, PREV_WRITEOFF_FLAG) AS WRITEOFF_FLAG,
       NVL(CURR_SPECIAL_REASON, PREV_SPECIAL_REASON) AS SPECIAL_REASON,
       NVL(CURR_PRODUCT_CODE, PREV_PRODUCT_CODE) AS PRODUCT_CODE,
       NVL(CURR_RESERVED_VARCHAR_2, PREV_RESERVED_VARCHAR_2) AS TRA,
       NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A';
  COMMIT;

  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND CURR_ACCOUNT_STATUS = 'W'
     AND PREV_ACCOUNT_STATUS = 'A';

  COMMIT;


/*
      SELECT V_CURRDATE           AS REPORT_DATE,
             PREV_MASTERID        AS MASTERID,
             PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
             PREV_CUSTOMER_NAME   AS CUSTOMER_NAME,
             PREV_ACCOUNT_NUMBER  AS ACCOUNT_NUMBER,
             PREV_DATA_SOURCE     AS DATA_SOURCE,
             NVL(CURR_SUB_SEGMENT,PREV_SUB_SEGMENT)     AS SUB_SEGMENT,
             CASE WHEN NVL (CURR_ACCOUNT_STATUS, 'C') = 'C' THEN 5 ELSE 6 END AS SEQ_NO,
             CASE WHEN NVL (CURR_ACCOUNT_STATUS, 'C') = 'C' THEN
                   'FINANCIAL ASSETS DERECOGNISED DURING THE PERIOD'
                ELSE
                   'WRITE OFFS'
             END AS IMP_CHANGE_REASON,
             (NVL (CURR_RESERVED_AMOUNT_2, 0) - NVL (PREV_RESERVED_AMOUNT_2, 0)) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
             ((NVL (CURR_ECL_OFF_BS_CCY, 0) - NVL (PREV_ECL_OFF_BS_CCY, 0)) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
             ((NVL (CURR_RESERVED_AMOUNT_4, 0) - NVL (PREV_RESERVED_AMOUNT_4, 0)) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
             ((NVL (CURR_RESERVED_AMOUNT_6, 0) - NVL (PREV_RESERVED_AMOUNT_6, 0)) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
             PREV_CURRENCY        AS CURRENCY,
             PREV_EXCHANGE_RATE   AS EXCHANGE_RATE,
             CASE
                WHEN PREV_POCI_FLAG = 'Y' THEN 'POCI'
                ELSE NVL(PREV_STAGE, '1')
             END AS STAGE,
             PREV_WRITEOFF_FLAG   AS WRITEOFF_FLAG,
             PREV_SPECIAL_REASON  AS SPECIAL_REASON,
             PREV_PRODUCT_CODE    AS PRODUCT_CODE,
             PREV_RESERVED_VARCHAR_2 AS TRA,
             PREV_RESERVED_VARCHAR_2 AS ASET_KEUANGAN
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
       WHERE PREV_REPORT_DATE = V_PREVDATE
             AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
             AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
             AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W')
      UNION
      SELECT V_CURRDATE           AS REPORT_DATE,
             PREV_MASTERID        AS MASTERID,
             PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
             PREV_CUSTOMER_NAME   AS CUSTOMER_NAME,
             PREV_ACCOUNT_NUMBER  AS ACCOUNT_NUMBER,
             PREV_DATA_SOURCE     AS DATA_SOURCE,
             PREV_SUB_SEGMENT     AS SUB_SEGMENT,
             7  AS SEQ_NO,
             'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
             -1 * (NVL (PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
             -1 * (NVL (PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
             -1 * (NVL (PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
             -1 * (NVL (PREV_RESERVED_AMOUNT_6, 0) *  PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
             PREV_CURRENCY        AS CURRENCY,
             PREV_EXCHANGE_RATE   AS EXCHANGE_RATE,
             CASE
                WHEN PREV_POCI_FLAG = 'Y' THEN 'POCI'
                ELSE NVL (PREV_STAGE, '1')
             END AS STAGE,
             PREV_WRITEOFF_FLAG   AS WRITEOFF_FLAG,
             PREV_SPECIAL_REASON  AS SPECIAL_REASON,
             PREV_PRODUCT_CODE    AS PRODUCT_CODE,
             PREV_RESERVED_VARCHAR_2 AS TRA,
             PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
       WHERE PREV_REPORT_DATE = V_PREVDATE
             AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
             AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
             AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W')
      UNION
      SELECT V_CURRDATE           AS REPORT_DATE,
             NVL(CURR_MASTERID, PREV_MASTERID)        AS MASTERID,
             NVL(CURR_CUSTOMER_NUMBER,PREV_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
             NVL(CURR_CUSTOMER_NAME,PREV_CUSTOMER_NAME)   AS CUSTOMER_NAME,
             NVL(CURR_ACCOUNT_NUMBER,PREV_ACCOUNT_NUMBER)  AS ACCOUNT_NUMBER,
             NVL(CURR_DATA_SOURCE,PREV_DATA_SOURCE)     AS DATA_SOURCE,
             NVL(CURR_SUB_SEGMENT,PREV_SUB_SEGMENT)     AS SUB_SEGMENT,
             7  AS SEQ_NO,
             'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
             (NVL (PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE ) AS ECL_ON_BS,
             (NVL (PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE ) AS ECL_OFF_BS,
             (NVL (PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE ) AS ECL_TOTAL,
             (NVL (PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE ) AS CARRY_AMOUNT,
             NVL(CURR_CURRENCY,PREV_CURRENCY)        AS CURRENCY,
             CURR_EXCHANGE_RATE   AS EXCHANGE_RATE,
             CASE
                WHEN NVL(CURR_POCI_FLAG,PREV_POCI_FLAG) = 'Y' THEN 'POCI'
                ELSE NVL (PREV_STAGE, '1')
             END AS STAGE,
             NVL(CURR_WRITEOFF_FLAG,PREV_WRITEOFF_FLAG)   AS WRITEOFF_FLAG,
             NVL(CURR_SPECIAL_REASON,PREV_SPECIAL_REASON)  AS SPECIAL_REASON,
             NVL(CURR_PRODUCT_CODE, PREV_PRODUCT_CODE)  AS PRODUCT_CODE,
             NVL(CURR_RESERVED_VARCHAR_2, PREV_RESERVED_VARCHAR_2) AS TRA,
             NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN
        FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
       WHERE PREV_REPORT_DATE = V_PREVDATE
             AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
             AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
             AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W');

COMMIT;

   DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
         WHERE PREV_REPORT_DATE = V_PREVDATE
               AND NVL (CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
               AND NVL (CURR_ACCOUNT_STATUS, 'C') IN ('C', 'W')
               AND PREV_ACCOUNT_STATUS NOT IN ('C', 'W');

COMMIT;
*/

---- PINDAH STAGE DENGAN ECL BULAN LALU LEBIH KECIL DARI ECL BULAN INI
  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       1 AS SEQ_NO,
       'TRANSFER FROM STAGE ' || NVL(PREV_STAGE, '1') || ' TO STAGE ' ||
       CURR_STAGE AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) <> NVL(PREV_STAGE, 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       1 AS SEQ_NO,
       'TRANSFER FROM STAGE ' || NVL(PREV_STAGE, '1') || ' TO STAGE ' ||
       CURR_STAGE AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_RESERVED_AMOUNT_2, 0) - NVL(PREV_RESERVED_AMOUNT_2, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_ECL_OFF_BS_CCY, 0) - NVL(PREV_ECL_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_RESERVED_AMOUNT_4, 0) - NVL(PREV_RESERVED_AMOUNT_4, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_RESERVED_AMOUNT_6, 0) - NVL(PREV_RESERVED_AMOUNT_6, 0)) *
       CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_UNUSED_AMT, 0) - NVL(PREV_UNUSED_AMT, 0)) *
       CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_OUTSTANDING_ON_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (NVL(PREV_OUTSTANDING_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) +
       ((NVL(CURR_OUTSTANDING_OFF_BS_CCY, 0) - NVL(PREV_OUTSTANDING_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY,0) - NVL(PREV_UNAMORT_FEE_AMT_CCY,0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY,0)) * PREV_EXCHANGE_RATE) +
       (((NVL(CURR_OUTSTANDING_ON_BS_CCY,0) - NVL(CURR_UNAMORT_FEE_AMT_CCY,0) + NVL(CURR_IA_UNWINDING_INTEREST_CCY,0)) - (NVL(PREV_OUTSTANDING_ON_BS_CCY,0) - NVL(PREV_UNAMORT_FEE_AMT_CCY,0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY,0))) *
       CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) <> NVL(PREV_STAGE, 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) <> NVL(PREV_STAGE, 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) <> NVL(PREV_STAGE, 1);
  /*
      SELECT V_CURRDATE           AS REPORT_DATE,
         CURR_MASTERID        AS MASTERID,
         CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
         CURR_CUSTOMER_NAME   AS CUSTOMER_NAME,
         CURR_ACCOUNT_NUMBER  AS ACCOUNT_NUMBER,
         CURR_DATA_SOURCE     AS DATA_SOURCE,
         CURR_SUB_SEGMENT     AS SUB_SEGMENT,
         7                    AS SEQ_NO,
         'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
         (NVL (PREV_RESERVED_AMOUNT_2, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_ON_BS,
         (NVL (PREV_ECL_OFF_BS_CCY, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_OFF_BS,
         (NVL (PREV_RESERVED_AMOUNT_4, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_TOTAL,
         (NVL (PREV_RESERVED_AMOUNT_6, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS CARRY_AMOUNT,
         CURR_CURRENCY        AS CURRENCY,
         CURR_EXCHANGE_RATE   AS EXCHANGE_RATE,
         CASE
          WHEN CURR_POCI_FLAG = 'Y' THEN 'POCI'
          ELSE NVL (CURR_STAGE, '1')
         END                  AS STAGE,
         CURR_WRITEOFF_FLAG   AS WRITEOFF_FLAG,
         CURR_SPECIAL_REASON  AS SPECIAL_REASON
      FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
       WHERE CURR_REPORT_DATE = V_CURRDATE
         AND PREV_REPORT_DATE = V_PREVDATE
         AND NVL (CURR_STAGE, 1) <> NVL (PREV_STAGE, 1);
  */

  COMMIT;

  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) <> NVL(PREV_STAGE, 1);
  COMMIT;


---- STAGE SAMA DENGAN IMPAIRED FLAG INDIVIDUAL
  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
  /*14 maret 2022 CR ECL MOVEMENT*/
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       4 AS SEQ_NO,
       'MODIFICATION OF CONTRACTUAL CASH FLOWS WITH NO DERECOGNITION' AS IMP_CHANGE_REASON,
       (NVL(CURR_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(CURR_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(CURR_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(CURR_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(CURR_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (nvl(CURR_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0) - NVL(CURR_UNAMORT_FEE_AMT_CCY, 0) + NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL C
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND (CURR_RESERVED_FLAG_1 = 1 OR CURR_RESERVED_FLAG_2 = 1)
     AND CURR_ACCOUNT_NUMBER IS NOT NULL
     AND PREV_ACCOUNT_NUMBER IS NULL
    /*AND NOT EXISTS
    (SELECT 1
         FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL P
        WHERE P.PREV_REPORT_DATE = V_PREVDATE
        AND P.PREV_ACCOUNT_NUMBER IS NULL)*/
    UNION
    /*end 14 maret 2022 CR ECL MOVEMENT*/
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       4 AS SEQ_NO,
       'MODIFICATION OF CONTRACTUAL CASH FLOWS WITH NO DERECOGNITION' AS IMP_CHANGE_REASON,
       /*(NVL (PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_2, 0) - NVL(PREV_RESERVED_AMOUNT_2, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       /*(NVL (PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_ECL_OFF_BS_CCY, 0) - NVL(PREV_ECL_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       /*(NVL (PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_4, 0) - NVL(PREV_RESERVED_AMOUNT_4, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       /*(NVL (PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_6, 0) - NVL(PREV_RESERVED_AMOUNT_6, 0)) *
       CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       ((NVL(CURR_UNUSED_AMT, 0) - NVL(PREV_UNUSED_AMT, 0)) *
       CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       ((nvl(CURR_OUTSTANDING_ON_BS_CCY,0) - nvl(PREV_OUTSTANDING_ON_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       ((nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) - nvl(PREV_OUTSTANDING_OFF_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       (((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)-NVL(PREV_OUTSTANDING_ON_BS_CCY, 0)) -
         (NVL(CURR_UNAMORT_FEE_AMT_CCY, 0)- NVL(PREV_UNAMORT_FEE_AMT_CCY, 0)) +
         (NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0)- NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))) *
         CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 = 1 OR CURR_RESERVED_FLAG_2 = 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       CURR_MASTERID AS MASTERID,
       CURR_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       CURR_CUSTOMER_NAME AS CUSTOMER_NAME,
       CURR_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       CURR_DATA_SOURCE AS DATA_SOURCE,
       CURR_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       CURR_CURRENCY AS CURRENCY,
       CURR_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN CURR_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       CURR_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       CURR_SPECIAL_REASON AS SPECIAL_REASON,
       CURR_PRODUCT_CODE AS PRODUCT_CODE,
       CURR_RESERVED_VARCHAR_2 AS TRA,
       CURR_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 = 1 OR CURR_RESERVED_FLAG_2 = 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       PREV_MASTERID AS MASTERID,
       PREV_CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
       PREV_CUSTOMER_NAME AS CUSTOMER_NAME,
       PREV_ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
       PREV_DATA_SOURCE AS DATA_SOURCE,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * PREV_EXCHANGE_RATE) AS UNUSED_AMT,
       PREV_CURRENCY AS CURRENCY,
       PREV_EXCHANGE_RATE AS EXCHANGE_RATE,
       CASE WHEN PREV_POCI_FLAG = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       PREV_WRITEOFF_FLAG AS WRITEOFF_FLAG,
       PREV_SPECIAL_REASON AS SPECIAL_REASON,
       PREV_PRODUCT_CODE AS PRODUCT_CODE,
       PREV_RESERVED_VARCHAR_2 AS TRA,
       PREV_RESERVED_VARCHAR_5 AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 = 1 OR CURR_RESERVED_FLAG_2 = 1);

  COMMIT;

  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE CURR_REPORT_DATE = V_CURRDATE
     AND PREV_REPORT_DATE = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND CURR_RESERVED_FLAG_1 = 1
    OR CURR_RESERVED_FLAG_2 = 1;
  COMMIT;



---- STAGE SAMA DENGAN IMPAIRED FLAG NON INDIVIDUAL DENGAN ECL BULAN LALU LEBIH KECIL DARI ECL BULAN INI
  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT V_CURRDATE AS REPORT_DATE,
       NVL(CURR_MASTERID, PREV_MASTERID) AS MASTERID,
       NVL(CURR_CUSTOMER_NUMBER, PREV_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
       NVL(CURR_CUSTOMER_NAME, PREV_CUSTOMER_NAME) AS CUSTOMER_NAME,
       NVL(CURR_ACCOUNT_NUMBER, PREV_ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
       NVL(CURR_DATA_SOURCE, PREV_DATA_SOURCE) AS DATA_SOURCE,
       NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       3 AS SEQ_NO,
       'CHANGES IN MODEL/ RISK PARAMETERS' AS IMP_CHANGE_REASON,
       /*(NVL (PREV_RESERVED_AMOUNT_2, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_2, 0) - NVL(PREV_RESERVED_AMOUNT_2, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       /*(NVL (PREV_ECL_OFF_BS_CCY, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_ECL_OFF_BS_CCY, 0) - NVL(PREV_ECL_OFF_BS_CCY, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       /*(NVL (PREV_RESERVED_AMOUNT_4, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_4, 0) - NVL(PREV_RESERVED_AMOUNT_4, 0)) *
       CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       /*(NVL (PREV_RESERVED_AMOUNT_6, 0) * PREV_EXCHANGE_RATE) +*/
       ((NVL(CURR_RESERVED_AMOUNT_6, 0) - NVL(PREV_RESERVED_AMOUNT_6, 0)) *
       CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       ((NVL(CURR_UNUSED_AMT, 0) - NVL(PREV_UNUSED_AMT, 0)) *
       CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       NVL(CURR_CURRENCY, PREV_CURRENCY) AS CURRENCY,
       NVL(CURR_EXCHANGE_RATE, PREV_EXCHANGE_RATE) AS EXCHANGE_RATE,
       CASE WHEN NVL(CURR_POCI_FLAG, PREV_POCI_FLAG) = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       NVL(CURR_WRITEOFF_FLAG, PREV_WRITEOFF_FLAG) AS WRITEOFF_FLAG,
       NVL(CURR_SPECIAL_REASON, PREV_SPECIAL_REASON) AS SPECIAL_REASON,
       NVL(CURR_PRODUCT_CODE, PREV_PRODUCT_CODE) AS PRODUCT_CODE,
       NVL(CURR_RESERVED_VARCHAR_2, PREV_RESERVED_VARCHAR_2) AS TRA,
       NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       ((nvl(CURR_OUTSTANDING_ON_BS_CCY,0) - nvl(PREV_OUTSTANDING_ON_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       ((nvl(CURR_OUTSTANDING_OFF_BS_CCY,0) - nvl(PREV_OUTSTANDING_OFF_BS_CCY,0)) *
       CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       (((NVL(CURR_OUTSTANDING_ON_BS_CCY, 0)-NVL(PREV_OUTSTANDING_ON_BS_CCY, 0)) -
         (NVL(CURR_UNAMORT_FEE_AMT_CCY, 0)- NVL(PREV_UNAMORT_FEE_AMT_CCY, 0)) +
         (NVL(CURR_IA_UNWINDING_INTEREST_CCY, 0)- NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))) *
         CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(PREV_REPORT_DATE, V_PREVDATE) = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 <> 1 OR CURR_RESERVED_FLAG_2 <> 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       NVL(PREV_MASTERID, CURR_MASTERID) AS MASTERID,
       NVL(PREV_CUSTOMER_NUMBER, CURR_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
       NVL(PREV_CUSTOMER_NAME, CURR_CUSTOMER_NAME) AS CUSTOMER_NAME,
       NVL(PREV_ACCOUNT_NUMBER, CURR_ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
       NVL(PREV_DATA_SOURCE, CURR_DATA_SOURCE) AS DATA_SOURCE,
       --         NVL(PREV_SUB_SEGMENT, CURR_SUB_SEGMENT) AS SUB_SEGMENT,
       PREV_SUB_SEGMENT AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       -1 * (NVL(PREV_RESERVED_AMOUNT_2, 0) * NVL(PREV_EXCHANGE_RATE, 0)) AS ECL_ON_BS,
       -1 * (NVL(PREV_ECL_OFF_BS_CCY, 0) * NVL(PREV_EXCHANGE_RATE, 0)) AS ECL_OFF_BS,
       -1 * (NVL(PREV_RESERVED_AMOUNT_4, 0) * NVL(PREV_EXCHANGE_RATE, 0)) AS ECL_TOTAL,
       -1 * (NVL(PREV_RESERVED_AMOUNT_6, 0) * NVL(PREV_EXCHANGE_RATE, 0)) AS CARRY_AMOUNT,
       -1 * (NVL(PREV_UNUSED_AMT, 0) * NVL(PREV_EXCHANGE_RATE, 0)) AS UNUSED_AMT,
       NVL(PREV_CURRENCY, CURR_CURRENCY) AS CURRENCY,
       NVL(PREV_EXCHANGE_RATE, 0) AS EXCHANGE_RATE,
       CASE WHEN NVL(PREV_POCI_FLAG, CURR_POCI_FLAG) = 'Y'
            THEN 'POCI'
            ELSE NVL(PREV_STAGE, '1')
       END AS STAGE,
       NVL(PREV_WRITEOFF_FLAG, CURR_WRITEOFF_FLAG) AS WRITEOFF_FLAG,
       NVL(PREV_SPECIAL_REASON, CURR_SPECIAL_REASON) AS SPECIAL_REASON,
       NVL(PREV_PRODUCT_CODE, CURR_PRODUCT_CODE) AS PRODUCT_CODE,
       NVL(PREV_RESERVED_VARCHAR_2, CURR_RESERVED_VARCHAR_2) AS TRA,
       NVL(PREV_RESERVED_VARCHAR_5, CURR_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       -1 * (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       -1 * (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * PREV_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       -1 * ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* PREV_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(PREV_REPORT_DATE, V_PREVDATE) = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 <> 1 OR CURR_RESERVED_FLAG_2 <> 1)
    UNION
    SELECT V_CURRDATE AS REPORT_DATE,
       NVL(CURR_MASTERID, PREV_MASTERID) AS MASTERID,
       NVL(CURR_CUSTOMER_NUMBER, PREV_CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
       NVL(CURR_CUSTOMER_NAME, PREV_CUSTOMER_NAME) AS CUSTOMER_NAME,
       NVL(CURR_ACCOUNT_NUMBER, PREV_ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
       NVL(CURR_DATA_SOURCE, PREV_DATA_SOURCE) AS DATA_SOURCE,
       NVL(CURR_SUB_SEGMENT, PREV_SUB_SEGMENT) AS SUB_SEGMENT,
       7 AS SEQ_NO,
       'FOREIGN CURRENCIES EFFECTS AND OTHER MOVEMENTS' AS IMP_CHANGE_REASON,
       (NVL(PREV_RESERVED_AMOUNT_2, 0) * CURR_EXCHANGE_RATE) AS ECL_ON_BS,
       (NVL(PREV_ECL_OFF_BS_CCY, 0) * CURR_EXCHANGE_RATE) AS ECL_OFF_BS,
       (NVL(PREV_RESERVED_AMOUNT_4, 0) * CURR_EXCHANGE_RATE) AS ECL_TOTAL,
       (NVL(PREV_RESERVED_AMOUNT_6, 0) * CURR_EXCHANGE_RATE) AS CARRY_AMOUNT,
       (NVL(PREV_UNUSED_AMT, 0) * CURR_EXCHANGE_RATE) AS UNUSED_AMT,
       /*
       (NVL (PREV_RESERVED_AMOUNT_2, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_ON_BS,
       (NVL (PREV_ECL_OFF_BS_CCY, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_OFF_BS,
       (NVL (PREV_RESERVED_AMOUNT_4, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS ECL_TOTAL,
       (NVL (PREV_RESERVED_AMOUNT_6, 0) * (CURR_EXCHANGE_RATE - PREV_EXCHANGE_RATE)) AS CARRY_AMOUNT,
       */
       NVL(CURR_CURRENCY, PREV_CURRENCY) AS CURRENCY,
       NVL(CURR_EXCHANGE_RATE, PREV_EXCHANGE_RATE) AS EXCHANGE_RATE,
       CASE WHEN NVL(CURR_POCI_FLAG, PREV_POCI_FLAG) = 'Y'
            THEN 'POCI'
            ELSE NVL(CURR_STAGE, '1')
       END AS STAGE,
       NVL(CURR_WRITEOFF_FLAG, PREV_WRITEOFF_FLAG) AS WRITEOFF_FLAG,
       NVL(CURR_SPECIAL_REASON, PREV_SPECIAL_REASON) AS SPECIAL_REASON,
       NVL(CURR_PRODUCT_CODE, PREV_PRODUCT_CODE) AS PRODUCT_CODE,
       NVL(CURR_RESERVED_VARCHAR_2, PREV_RESERVED_VARCHAR_2) AS TRA,
       NVL(CURR_RESERVED_VARCHAR_5, PREV_RESERVED_VARCHAR_5) AS ASET_KEUANGAN,
       (nvl(PREV_OUTSTANDING_ON_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_ON_BS,
       (nvl(PREV_OUTSTANDING_OFF_BS_CCY,0) * CURR_EXCHANGE_RATE) AS OUTSTANDING_OFF_BS_LCL,
       ((NVL(PREV_OUTSTANDING_ON_BS_CCY, 0) - NVL(PREV_UNAMORT_FEE_AMT_CCY, 0) + NVL(PREV_IA_UNWINDING_INTEREST_CCY, 0))* CURR_EXCHANGE_RATE) AS NILAI_TERCATAT_ON_BS
    FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
     WHERE NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(PREV_REPORT_DATE, V_PREVDATE) = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 <> 1 OR CURR_RESERVED_FLAG_2 <> 1);

  COMMIT;
  DELETE FROM TEMP_REPORT_ECL_MOVE_VALAS_DTL
   WHERE NVL(CURR_REPORT_DATE, V_CURRDATE) = V_CURRDATE
     AND NVL(PREV_REPORT_DATE, V_PREVDATE) = V_PREVDATE
     AND NVL(CURR_STAGE, 1) = NVL(PREV_STAGE, 1)
     AND (CURR_RESERVED_FLAG_1 <> 1 OR CURR_RESERVED_FLAG_2 <> 1);
  COMMIT;


  INSERT INTO IFRS_REPORT_ECL_MOVE_VALAS_DTL
    (REPORT_DATE,
     MASTERID,
     CUSTOMER_NUMBER,
     CUSTOMER_NAME,
     ACCOUNT_NUMBER,
     DATA_SOURCE,
     SUB_SEGMENT,
     SEQ_NO,
     IMP_CHANGE_REASON,
     ECL_ON_BS,
     ECL_OFF_BS,
     ECL_TOTAL,
     CARRY_AMOUNT,
     UNUSED_AMT,
     CURRENCY,
     EXCHANGE_RATE,
     STAGE,
     WRITEOFF_FLAG,
     SPECIAL_REASON,
     PRODUCT_CODE,
     TRA,
     ASET_KEUANGAN,
     OUTSTANDING_ON_BS,
     OUTSTANDING_OFF_BS,
     NILAI_TERCATAT_ON_BS)
    SELECT IDR.REPORT_DATE,
       IDR.MASTERID,
       IDR.CUSTOMER_NUMBER,
       IDR.CUSTOMER_NAME,
       IDR.ACCOUNT_NUMBER,
       IDR.DATA_SOURCE,
       IDR.SUB_SEGMENT,
       IDR.SEQ_NO,
       IDR.IMP_CHANGE_REASON,
       IDR.ECL_ON_BS,
       IDR.ECL_OFF_BS,
       IDR.ECL_TOTAL,
       IDR.CARRY_AMOUNT,
       IDR.UNUSED_AMT,
       IDR.CURRENCY,
       IDR.EXCHANGE_RATE,
       IDR.STAGE,
       IDR.WRITEOFF_FLAG,
       IDR.SPECIAL_REASON,
       IDR.PRODUCT_CODE,
       IDR.TRA,
       IDR.ASET_KEUANGAN,
       IDR.OUTSTANDING_ON_BS,
       IDR.OUTSTANDING_OFF_BS,
       IDR.NILAI_TERCATAT_ON_BS
    FROM IFRS_REPORT_ECL_MOVEMENT_DTL IDR
    LEFT JOIN (select NVL(CURR.REPORT_DATE, V_CURRDATE) REPORT_DATE,
              NVL(CURR.MASTERID, PREV.MASTERID) MASTERID,
              --NVL(CURR.PRODUCT_CODE, PREV.PRODUCT_CODE) PRODUCT_CODE,
              --NVL(CURR.TRA, PREV.TRA) TRA,
              --NVL(CURR.ASET_KEUANGAN, PREV.ASET_KEUANGAN) ASET_KEUANGAN
              CASE WHEN (NVL(CURR.MASTERID, 0) = 0 OR
                     CURR.ACCOUNT_STATUS <> 'A')
                 THEN PREV.PRODUCT_CODE
              ELSE CURR.PRODUCT_CODE
              END PRODUCT_CODE,
              CASE WHEN (NVL(CURR.MASTERID, 0) = 0 OR
                     CURR.ACCOUNT_STATUS <> 'A')
                 THEN PREV.TRA
              ELSE CURR.TRA
              END TRA,
              CASE WHEN (NVL(CURR.MASTERID, 0) = 0 OR
                     CURR.ACCOUNT_STATUS <> 'A')
                 THEN PREV.ASET_KEUANGAN
                 ELSE CURR.ASET_KEUANGAN
              END ASET_KEUANGAN
           from (select report_date,
                  masterid,
                  ACCOUNT_STATUS,
                  PRODUCT_CODE,
                  RESERVED_VARCHAR_2 TRA,
                  RESERVED_VARCHAR_5 ASET_KEUANGAN
               from GTMP_NOMINATIVE_CURR_PREV
              where report_date = V_CURRDATE
                and exchange_rate = 1) CURR
           FULL JOIN (select report_date,
                    masterid,
                    ACCOUNT_STATUS,
                    PRODUCT_CODE,
                    RESERVED_VARCHAR_2 TRA,
                    RESERVED_VARCHAR_5 ASET_KEUANGAN
                 from GTMP_NOMINATIVE_CURR_PREV
                where report_date = V_PREVDATE
                  and exchange_rate = 1) PREV
             ON CURR.MASTERID = PREV.MASTERID) NOMI
      ON IDR.MASTERID = NOMI.MASTERID
     AND IDR.REPORT_DATE = NOMI.REPORT_DATE
     AND NOMI.REPORT_DATE = V_CURRDATE
     WHERE IDR.REPORT_DATE = V_CURRDATE
     AND IDR.EXCHANGE_RATE = 1;
  COMMIT;

SP_IFRS_INS_MOVE_MAP_SEG_ASET (V_CURRDATE);

/*
      SELECT IDR.REPORT_DATE,
             IDR.MASTERID,
             IDR.CUSTOMER_NUMBER,
             IDR.CUSTOMER_NAME,
             IDR.ACCOUNT_NUMBER,
             IDR.DATA_SOURCE,
             IDR.SUB_SEGMENT,
             IDR.SEQ_NO,
             IDR.IMP_CHANGE_REASON,
             IDR.ECL_ON_BS,
             IDR.ECL_OFF_BS,
             IDR.ECL_TOTAL,
             IDR.CARRY_AMOUNT,
             IDR.CURRENCY,
             IDR.EXCHANGE_RATE,
             IDR.STAGE,
             IDR.WRITEOFF_FLAG,
             IDR.SPECIAL_REASON,
             NOMI.PRODUCT_CODE,
             NOMI.RESERVED_VARCHAR_2,
             NOMI.RESERVED_VARCHAR_5
        FROM IFRS_REPORT_ECL_MOVEMENT_DTL IDR LEFT JOIN GTMP_NOMINATIVE_CURR_PREV  NOMI ON  IDR.MASTERID = NOMI.MASTERID
AND IDR.REPORT_DATE = NOMI.REPORT_DATE
AND NOMI.REPORT_DATE = V_CURRDATE
WHERE IDR.REPORT_DATE = V_CURRDATE AND IDR.EXCHANGE_RATE = 1;
*/
END;