CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_SEQUENCE (V_EFF_DATE DATE)
AS
    V_SPNAME VARCHAR2(100);
BEGIN
    V_SPNAME := 'SP_IFRS_LGD_IMA_DATA('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

    V_SPNAME := 'SP_IFRS_LGD_DATA_BCA('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

    V_SPNAME := 'SP_IFRS_LGD('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

    V_SPNAME := 'SP_IFRS_LGD_IMA_DATA_CARD('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

    V_SPNAME := 'SP_IFRS_LGD_CARD('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');

    V_SPNAME := 'SP_IFRS_LGD_EXPECTED_RECOVERY('''|| TO_CHAR(V_EFF_DATE, 'dd-mon-yyyy') ||''')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'IMP','Y');
END;