CREATE OR REPLACE PROCEDURE SP_IFRS_MASTER_PAYSET_UPLOAD
    AS

    V_CURRDATE DATE;
    V_PREVDATE DATE;

    BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    SELECT PREVDATE INTO V_PREVDATE FROM IFRS_PRC_DATE;


DELETE IFRS_MASTER_PAYSET_UPLOAD
WHERE DOWNLOAD_DATE >= V_CURRDATE;COMMIT;

INSERT INTO IFRS_MASTER_PAYSET_UPLOAD
SELECT * FROM TBLU_MASTER_PAYMENT_SETTING WHERE DOWNLOAD_DATE = V_CURRDATE;COMMIT;

DELETE IFRS_MASTER_PAYMENT_SETTING
 WHERE     DOWNLOAD_DATE = V_CURRDATE
       AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER
                                FROM IFRS_MASTER_PAYSET_UPLOAD WHERE DOWNLOAD_DATE = V_CURRDATE);

COMMIT;


INSERT INTO IFRS_MASTER_PAYMENT_SETTING (
                                    DOWNLOAD_DATE  ,
                                    MASTERID       ,
                                    ACCOUNT_NUMBER ,
                                    COMPONENT_TYPE ,
                                    FREQUENCY      ,
                                    INCREMENTS     ,
                                    AMOUNT         ,
                                    TIMES_ORG
                                        )
   SELECT V_CURRDATE,
          0,
          ACCOUNT_NUMBER,
          COMPONENT_TYPE,
          FREQUENCY,
          INCREMENTS,
          AMOUNT,
          TIMES_ORG
     FROM IFRS_MASTER_PAYSET_UPLOAD
     WHERE DOWNLOAD_DATE = V_CURRDATE;

COMMIT;*
INSERT INTO IFRS_MASTER_PAYMENT_SETTING
(
DOWNLOAD_DATE   ,
MASTERID        ,
ACCOUNT_NUMBER  ,
COMPONENT_TYPE  ,
COMPONENT_STATUS,
FREQUENCY       ,
INCREMENTS      ,
AMOUNT          ,
TIMES_ORG       ,
TIMES_USED      ,
DATE_START      ,
DATE_END        ,
PMT_DATE        ,
IS_INSERTED
)
SELECT
V_CURRDATE,
0        ,
ACCOUNT_NUMBER  ,
COMPONENT_TYPE  ,
COMPONENT_STATUS,
FREQUENCY       ,
INCREMENTS      ,
AMOUNT          ,
TIMES_ORG       ,
TIMES_USED      ,
DATE_START      ,
DATE_END        ,
PMT_DATE        ,
IS_INSERTED
FROM IFRS_MASTER_PAYMENT_SETTING
WHERE DOWNLOAD_DATE = V_PREVDATE;
COMMIT;
*/
END;