CREATE OR REPLACE PROCEDURE  SP_IFRS_LI_SYNC_TRANS_PARAM
AS


 V_CURRDATE   DATE;
 V_PREVDATE   DATE;

 BEGIN


    SELECT CURRDATE, PREVDATE INTO V_CURRDATE, V_PREVDATE FROM IFRS_LI_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG(DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(  V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_SYNC_TRANSACTION_PARAM','');

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LI_TRANSACTION_PARAM';

    INSERT INTO IFRS_LI_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_SYNC_TRANSACTION_PARAM','INSERT TRANS PARAM');

    COMMIT;


    INSERT  INTO IFRS_LI_TRANSACTION_PARAM
      ( DATA_SOURCE ,
      PRD_TYPE ,
      PRD_CODE ,
      TRX_CODE ,
      CCY ,
      IFRS_TXN_CLASS ,
      AMORTIZATION_FLAG ,
      AMORT_TYPE ,
      GL_CODE ,
      TENOR_AMORTIZATION ,
      TRANSACTION_TYPE ,
      GL_CODE_UAM ,
      FEE_MAT_TYPE ,
      FEE_MAT_AMT ,
      COST_MAT_TYPE ,
      COST_MAT_AMT ,
      SL_EXP_LIFE
      )
      SELECT  DATA_SOURCE ,
        PRD_TYPE ,
        PRD_CODE ,
        TRX_CODE ,
        CCY ,
        IFRS_TXN_CLASS ,
        AMORTIZATION_FLAG ,
        AMORT_TYPE ,
        GL_CODE ,
        TENOR_AMORTIZATION ,
        TRANSACTION_TYPE ,
        GL_CODE_UAM ,
	ORG_FEE_MAT_TYPE ,
	ORG_FEE_MAT_AMT ,
	TXN_COST_MAT_TYPE ,
	TXN_COST_MAT_AMT ,
	SL_EXP_LIFE
    FROM IFRS_MASTER_TRANS_PARAM
    WHERE INST_CLS_VALUE = 'L';

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES(V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_SYNC_TRANSACTION_PARAM',''  );

    COMMIT;
    END;