CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_EXPECT_RECOV_CARD
 AS
    V_CURRDATE DATE;
BEGIN
    SELECT  CURRDATE
    INTO V_CURRDATE
    FROM IFRS_PRC_DATE_LGD ;

    --UPDATE/ INSERT IFRS_LGD_EXPECTED_RECOVERY
    MERGE INTO IFRS_LGD_EXPECTED_RECOVERY D
    USING (
            SELECT DOWNLOAD_DATE,SEGMENTATION_ID,SEGMENTATION_NAME,LGD_RULE_ID,LGD_RULE_NAME,CALC_METHOD,
                SUM(OUTSTANDING_NPL) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID) OUTSTANDING_NPL,
                SUM(RECOVERY_AMOUNT)  OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID) RECOVERY_AMOUNT,
                SUM(PV_RECOVERY_AMOUNT) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID)PV_RECOVERY_AMOUNT,
                ROUND(SUM(PV_RECOVERY_AMOUNT) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID)/
                      SUM(OUTSTANDING_NPL) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID),4) RECOVERY_RATE,
                1-ROUND(SUM(PV_RECOVERY_AMOUNT) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID)/
                        SUM(OUTSTANDING_NPL) OVER(PARTITION BY SEGMENTATION_ID,LGD_RULE_ID,CALC_METHOD ORDER BY DOWNLOAD_DATE,SEGMENTATION_ID,LGD_RULE_ID),4) LGD_EXPECTED_RECOVERY
            FROM (
                SELECT A.DOWNLOAD_DATE,
                      A.SEGMENTATION_ID,
                      A.SEGMENTATION_NAME,
                      B.PKID LGD_RULE_ID,
                      B.LGD_RULE_NAME,
                      B.CALC_METHOD,
                      SUM(A.TOTAL_LOSS_AMT) OUTSTANDING_NPL,
                      SUM(A.RECOV_AMT_BF_NPV) RECOVERY_AMOUNT,
                      SUM(A.RECOV_AMT_BF_NPV) PV_RECOVERY_AMOUNT,
                      ROUND(SUM(A.RECOV_AMT_BF_NPV)/SUM(A.TOTAL_LOSS_AMT),4) RECOVERY_RATE,
                      1-ROUND(SUM(A.RECOV_AMT_BF_NPV)/SUM(A.TOTAL_LOSS_AMT),4) LGD_EXPECTED_RECOVERY
                FROM IFRS_LGD A
                    LEFT JOIN IFRS_LGD_RULES_CONFIG B ON A.LGD_RULE_ID = B.PKID
                WHERE
                     DOWNLOAD_DATE BETWEEN B.CUT_OFF_DATE AND LAST_DAY(V_CURRDATE)
                GROUP BY A.DOWNLOAD_DATE,
                      A.SEGMENTATION_ID,
                      A.SEGMENTATION_NAME,
                      B.PKID,
                      B.LGD_RULE_NAME,
                      B.CALC_METHOD
                ORDER BY DOWNLOAD_DATE
            )XX
            /*
            SELECT LAST_DAY(V_CURRDATE) DOWNLOAD_DATE,
                  A.SEGMENTATION_ID,
                  A.SEGMENTATION_NAME,
                  B.PKID LGD_RULE_ID,
                  B.LGD_RULE_NAME,
                  B.CALC_METHOD,
                  SUM(A.TOTAL_LOSS_AMT) OUTSTANDING_NPL,
                  SUM(A.RECOV_AMT_BF_NPV) RECOVERY_AMOUNT,
                  SUM(A.RECOV_AMT_BF_NPV) PV_RECOVERY_AMOUNT,
                  ROUND(SUM(A.RECOV_AMT_BF_NPV)/SUM(A.TOTAL_LOSS_AMT),4) RECOVERY_RATE,
                  1-ROUND(SUM(A.RECOV_AMT_BF_NPV)/SUM(A.TOTAL_LOSS_AMT),4) LGD_EXPECTED_RECOVERY
            FROM IFRS_LGD A
                LEFT JOIN IFRS_LGD_RULES_CONFIG B ON A.LGD_RULE_ID = B.PKID
            WHERE
                A.ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM IFRS_LGD_PROCESS
                                       WHERE --RECOVERY_DATE = LAST_DAY(V_CURRDATE) --LAST_DAY(V_CURRDATE)
                                       DOWNLOAD_DATE	= LAST_DAY(V_CURRDATE)
                                       )
                 DOWNLOAD_DATE BETWEEN B.CUT_OFF_DATE AND LAST_DAY(V_CURRDATE)
            GROUP BY A.DOWNLOAD_DATE,
                  A.SEGMENTATION_ID,
                  A.SEGMENTATION_NAME,
                  B.PKID,
                  B.LGD_RULE_NAME,
                  B.CALC_METHOD */
            ) S ON (D.DOWNLOAD_DATE = S.DOWNLOAD_DATE
                AND D.LGD_RULE_ID = S.LGD_RULE_ID)
    WHEN MATCHED THEN
    UPDATE SET
            LGD_RULE_NAME           =   S.LGD_RULE_NAME,
            SEGMENTATION_ID         =   S.SEGMENTATION_ID,
            CALC_METHOD             =   S.CALC_METHOD,
            OUTSTANDING_NPL         =   S.OUTSTANDING_NPL,
            RECOVERY_AMOUNT         =   S.RECOVERY_AMOUNT,
            PV_RECOVERY_AMOUNT      =   S.PV_RECOVERY_AMOUNT,
            RECOVERY_RATE           =   S.RECOVERY_RATE,
            LGD_EXPECTED_RECOVERY   =   S.LGD_EXPECTED_RECOVERY,
            UPDATEDDATE             =   SYSDATE
    WHEN NOT MATCHED THEN
    INSERT (DOWNLOAD_DATE,
            LGD_RULE_ID,
            LGD_RULE_NAME,
            SEGMENTATION_ID,
            CALC_METHOD,
            OUTSTANDING_NPL,
            RECOVERY_AMOUNT,
            PV_RECOVERY_AMOUNT,
            RECOVERY_RATE,
            LGD_EXPECTED_RECOVERY,
            CREATEDDATE)
    VALUES(S.DOWNLOAD_DATE,
           S.LGD_RULE_ID,
           S.LGD_RULE_NAME,
           S.SEGMENTATION_ID,
           S.CALC_METHOD,
           S.OUTSTANDING_NPL,
           S.RECOVERY_AMOUNT,
           S.PV_RECOVERY_AMOUNT,
           S.RECOVERY_RATE,
           S.LGD_EXPECTED_RECOVERY,
           SYSDATE);
    COMMIT;
END;