CREATE OR REPLACE procedure SP_IFRS_FRATE_POPULATE as
    V_CURRDATE DATE;
BEGIN

    update  IFRS_PRC_DATE_FR set BATCH_STATUS = 'N', REMARK='Running SP_IFRS_FRATE_POPULATE.....';

    commit;

    select CURRDATE INTO V_CURRDATE from IFRS_PRC_DATE_FR;

    delete IFRS_MASTER_FRATE_ACCOUNT where DOWNLOAD_DATE = V_CURRDATE;

    COMMIT;

    insert into IFRS_MASTER_FRATE_ACCOUNT (DOWNLOAD_DATE, ACCOUNT_NUMBER, MARKET_RATE, GOL_DEB, SOURCE)
    select a.DOWNLOAD_DATE, ACCOUNT_NUMBER, SUKU_BUNGA MARKET_RATE, a.GOLDEB, 'MIS' SOURCE
    from IFRS_STG_FR_MIS a
             left join TBLU_BUNGA_FIXED_RATE b
                  on a.DOWNLOAD_DATE = b.DOWNLOAD_DATE and a.PRODUCT_CODE = b.PRODUCT_CODE and a.GOLDEB = b.GOLDEB
    union
    select a.DOWNLOAD_DATE, b.*, a.RESERVED_VARCHAR_2 GOLDEB, 'CORPORATE' SOURCE
    from IFRS_MASTER_ACCOUNT_MONTHLY a
             join (select 0 || NOMOR_REKENING || NOMOR_PINJAMAN ACCOUNT_NUMBER, SUKU_BUNGA MARKET_RATE
                   from TBLU_FR_CORPORATE) b on a.ACCOUNT_NUMBER like b.ACCOUNT_NUMBER || '%'
    where DOWNLOAD_DATE = V_CURRDATE;

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE FRATE_ACCOUNT';

    insert into FRATE_ACCOUNT
    select ACCOUNT_NUMBER,MARKET_RATE,GOL_DEB from IFRS_MASTER_FRATE_ACCOUNT where DOWNLOAD_DATE=V_CURRDATE;

    COMMIT;

END;