CREATE OR REPLACE PROCEDURE SP_IFRS_PD_MAA_ODR
AS
    v_CURRDATE DATE;
BEGIN

    SELECT CURRDATE
	INTO v_CURRDATE
	FROM IFRS_PRC_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_RUNNING_DATE';

    INSERT INTO TMP_IFRS_PD_RUNNING_DATE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        BUCKET_GROUP,
        MIG_LOSS_BUCKET
    )
    SELECT
        v_CURRDATE AS EFF_DATE,
		LAST_DAY(ADD_MONTHS(v_CURRDATE, A.INCREMENT_PERIOD * -1)) AS BASE_DATE,
	    A.PKID AS PD_RULE_ID,
		A.BUCKET_GROUP,
		A.MIG_LOSS_BUCKET
    FROM IFRS_PD_RULES_CONFIG A
    WHERE NVL(A.ACTIVE_FLAG,0) = 1
	AND IS_DELETED = 0
	AND PD_METHOD ='MAA'
	AND A.DERIVED_PD_MODEL IS NULL;

    COMMIT;

    DELETE IFRS_PD_MAA_ODR
    WHERE EFF_DATE = v_CURRDATE
    AND PD_RULE_ID IN (SELECT PD_RULE_ID FROM TMP_IFRS_PD_RUNNING_DATE);

    COMMIT;

    INSERT INTO IFRS_PD_MAA_ODR
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        ODR
    )
    SELECT
        A.EFF_DATE,
        A.BASE_DATE,
        A.PD_RULE_ID,
        CASE WHEN B.SUM_CALC_AMOUNT = 0 THEN
            0
        ELSE
            A.SUM_CALC_AMOUNT / B.SUM_CALC_AMOUNT
        END
    FROM
    (
        SELECT A2.EFF_DATE,
            A2.BASE_DATE,
            A2.PD_RULE_ID,
            SUM(A2.CALC_AMOUNT) AS SUM_CALC_AMOUNT
        FROM IFRS_PD_MAA_ENR A2
        JOIN TMP_IFRS_PD_RUNNING_DATE B2
        ON A2.PD_RULE_ID = B2.PD_RULE_ID
            AND A2.EFF_DATE = v_CURRDATE
        JOIN VW_IFRS_MAX_BUCKET C2
        ON A2.BUCKET_GROUP = C2.BUCKET_GROUP
        AND A2.BUCKET_TO = C2.MAX_BUCKET_ID
        GROUP BY A2.EFF_DATE,
            A2.BASE_DATE,
            A2.PD_RULE_ID
    ) A
    JOIN
    (
        SELECT A2.EFF_DATE,
            A2.BASE_DATE,
            A2.PD_RULE_ID,
            SUM(A2.CALC_AMOUNT) AS SUM_CALC_AMOUNT
        FROM IFRS_PD_MAA_ENR A2
        JOIN TMP_IFRS_PD_RUNNING_DATE B2
        ON A2.PD_RULE_ID = B2.PD_RULE_ID
            AND A2.EFF_DATE = v_CURRDATE
        GROUP BY A2.EFF_DATE,
            A2.BASE_DATE,
            A2.PD_RULE_ID
    ) B
    ON A.EFF_DATE = B.EFF_DATE
        AND A.PD_RULE_ID = B.PD_RULE_ID
    ORDER BY A.PD_RULE_ID;

    COMMIT;

    INSERT INTO IFRS_PD_MAA_ODR
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        ODR
    )
    SELECT DISTINCT
        A.EFF_DATE,
        A.BASE_DATE,
        PD_RULE_ID,
        0 AS ODR
    FROM TMP_IFRS_PD_RUNNING_DATE A
    WHERE PD_RULE_ID NOT IN
    (
        SELECT PD_RULE_ID
        FROM IFRS_PD_MAA_ODR
        WHERE EFF_DATE = v_CURRDATE
    );

    COMMIT;

END;