CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_PAYM_SCHD_SRC
AS
    V_CALC_IDAYS NUMBER(10) := 1;
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_PARAM_CALC_TO_LASTPAYMENT NUMBER(10);
    V_EXISTS NUMBER(1) := 0;
BEGIN
    ---- INTEREST CALCULATION CODE = 6 ===> 30 /360
    ---- O  =  30
    ---- 1  =  WITH FUCTION FN_CNT_DAYS_30_360 (COUNTER 1 ALWAYS ACTUAL)

    SELECT CURRDATE
    , PREVDATE INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    SELECT COMMONUSAGE
    INTO V_CALC_IDAYS
    FROM TBLM_COMMONCODEHEADER
    WHERE COMMONCODE = 'SCM002';

    SELECT CASE WHEN COMMONUSAGE = 'Y' THEN
        1
    ELSE
        0
    END INTO V_PARAM_CALC_TO_LASTPAYMENT
    FROM TBLM_COMMONCODEHEADER
    WHERE COMMONCODE = 'SCM005';


    /*******   RESET HISTORY  *******/
    SELECT COUNT(*) INTO V_EXISTS
    FROM user_indexes
    WHERE index_name = 'IDX_IFRS_PAYM_SCHD_ALL_2';

    IF V_EXISTS = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_IFRS_PAYM_SCHD_ALL_2';
    END IF;


    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IFRS_PAYM_SCHD_ALL_2 ON IFRS_PAYM_SCHD_ALL
                       (PMTDATE, STATUS)
                       NOLOGGING
                       TABLESPACE IFRS_IDX_TBS';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD_ALL';

    INSERT /*+ PARALLEL(12) */ INTO TMP_IFRS_PAYM_SCHD_ALL
    (
       DOWNLOAD_DATE
      ,MASTERID
      ,PMTDATE
      ,INTEREST_RATE
      ,OSPRN
      ,PRINCIPAL
      ,INTEREST
      ,DISB_PERCENTAGE
      ,DISB_AMOUNT
      ,PLAFOND
      ,I_DAYS
      ,COUNTER
      ,ICC
      ,OUTSTANDING
      ,SOURCE_PROCESS
      ,SCH_FLAG
      ,GRACE_DATE
    )
    SELECT /*+ PARALLEL(12) */
       A.DOWNLOAD_DATE
      ,A.MASTERID
      ,A.PMTDATE
      ,A.INTEREST_RATE
      ,A.OSPRN
      ,A.PRINCIPAL
      ,A.INTEREST
      ,A.DISB_PERCENTAGE
      ,A.DISB_AMOUNT
      ,A.PLAFOND
      ,A.I_DAYS
      ,A.COUNTER
      ,A.ICC
      ,A.OUTSTANDING
      ,A.SOURCE_PROCESS
      ,A.SCH_FLAG
      ,A.GRACE_DATE
    FROM IFRS_PAYM_SCHD_ALL A
    WHERE A.PMTDATE >= V_CURRDATE
    AND A.STATUS = 'A';

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LBM_PAYM_SCHD';
    /*******  INSERT TO AMORTISASI  *******/
    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_PAYM_SCHD
    (DOWNLOAD_DATE
      ,MASTERID
      ,PMTDATE
      ,INTEREST_RATE
      ,OSPRN
      ,PRINCIPAL
      ,INTEREST
      ,DISB_PERCENTAGE
      ,DISB_AMOUNT
      ,PLAFOND
      ,I_DAYS
      ,COUNTER
      ,ICC
      ,OUTSTANDING
      ,SOURCE_PROCESS
      ,SCH_FLAG
      ,GRACE_DATE
    )
    SELECT /*+ PARALLEL(12) */
       V_CURRDATE
      ,A.MASTERID
      ,A.PMTDATE
      ,A.INTEREST_RATE
      ,A.OSPRN
      ,A.PRINCIPAL
      ,A.INTEREST
      ,A.DISB_PERCENTAGE
      ,A.DISB_AMOUNT
      ,A.PLAFOND
      ,A.I_DAYS
      ,A.COUNTER
      ,A.ICC
      ,A.OUTSTANDING
      ,A.SOURCE_PROCESS
      ,A.SCH_FLAG
      ,A.GRACE_DATE
    FROM TMP_IFRS_PAYM_SCHD_ALL A
    INNER JOIN IFRS_IMA_AMORT_CURR B
    ON A.MASTERID = B.MASTERID
    WHERE B.ECF_STATUS = 'Y'
    AND (B.STAFF_LOAN_FLAG='Y' OR B.BELOW_MARKET_FLAG='Y');

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_MAX_IFRS_PAYM_SCHD_ALL';

    INSERT /*+ PARALLEL(12) */ INTO TMP_MAX_IFRS_PAYM_SCHD_ALL
    (
        MASTERID,
        LAST_PAYMENT_DATE_PYM
    )
    SELECT /*+ PARALLEL(12) */ MASTERID,MAX(PMTDATE) LAST_PAYMENT_DATE_PYM
        FROM IFRS_PAYM_SCHD_ALL
        WHERE STATUS = 'A' AND PMTDATE <= V_CURRDATE
        GROUP BY MASTERID;
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP3';

    INSERT /*+ PARALLEL(12) */ INTO TMP3
    SELECT /*+ PARALLEL(12) */ PMA.DOWNLOAD_DATE,PMA.MASTERID,
    CASE
       WHEN V_PARAM_CALC_TO_LASTPAYMENT = 0
        THEN V_CURRDATE
       ELSE
       CASE
         WHEN PYM.MASTERID IS NOT NULL  THEN PYM.LAST_PAYMENT_DATE_PYM
         ELSE CASE
           WHEN NVL(PMA.LAST_PAYMENT_DATE, PMA.LOAN_START_DATE) <=  PMA.LOAN_START_DATE
            THEN  PMA.LOAN_START_DATE
           WHEN PMV.MASTERID IS NULL
            THEN PMA.LOAN_START_DATE
           ELSE CASE
             WHEN PMA.LAST_PAYMENT_DATE >= NVL(PMA.LOAN_END_AMORTIZATION, PMA.LOAN_DUE_DATE)
              THEN - 1 * INTERVAL '1' MONTH + NVL(PMA.LOAN_END_AMORTIZATION, PMA.LOAN_DUE_DATE)
             ELSE PMA.LAST_PAYMENT_DATE
             END
           END
         END
       END START_AMORTIZATION_DATE
       FROM IFRS_MASTER_ACCOUNT PMA
      INNER JOIN IFRS_IMA_AMORT_CURR PMC
        ON PMA.DOWNLOAD_DATE = PMC.DOWNLOAD_DATE AND PMA.MASTERID = PMC.MASTERID
      LEFT JOIN IFRS_IMA_AMORT_PREV PMV
        ON PMV.DOWNLOAD_DATE = V_PREVDATE AND PMC.MASTERID = PMV.MASTERID
      LEFT JOIN TMP_MAX_IFRS_PAYM_SCHD_ALL PYM
--    (
--        SELECT MASTERID,MAX(PMTDATE) LAST_PAYMENT_DATE_PYM
--        FROM IFRS_PAYM_SCHD_ALL
--        WHERE STATUS = 'A' AND PMTDATE <= V_CURRDATE
--        GROUP BY MASTERID
--    ) PYM
    ON PYM.MASTERID = PMA.MASTERID
    WHERE PMA.DOWNLOAD_DATE = V_CURRDATE
      AND PMC.ECF_STATUS = 'Y'
      AND PMA.ACCOUNT_STATUS = 'A'
      AND PMA.IAS_CLASS = 'A'
      AND PMA.LOAN_DUE_DATE > V_CURRDATE
      AND PMA.AMORT_TYPE = 'EIR'
      AND PMA.ECF_STATUS='Y';

    COMMIT;

    --DELETE TOP
--    DELETE IFRS_PAYM_SCHD
--    WHERE PMTDATE <= V_CURRDATE;

    COMMIT;

    --DELETE BOTTOM
    DELETE /*+ PARALLEL(12) */
    (SELECT A.*
      FROM IFRS_LBM_PAYM_SCHD A
      INNER JOIN
        (SELECT MASTERID, MIN(PMTDATE) AS MAX_PMTDATE FROM IFRS_PAYM_SCHD WHERE OSPRN = 0 GROUP BY MASTERID) B
        ON A.MASTERID = B.MASTERID
        AND A.PMTDATE > B.MAX_PMTDATE
    );

    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD_COUNTER';

    INSERT /*+ PARALLEL(12) */ INTO TMP_IFRS_PAYM_SCHD_COUNTER
    (MASTERID, COUNTER)
    SELECT /*+ PARALLEL(12) */ A.MASTERID, MIN(A.COUNTER) COUNTER
    FROM IFRS_LBM_PAYM_SCHD A
    GROUP BY A.MASTERID;

    COMMIT;

--    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PAYM_SCHD';
--
--    INSERT INTO TMP_IFRS_PAYM_SCHD
--    (
--       DOWNLOAD_DATE
--      ,MASTERID
--      ,PMTDATE
--      ,INTEREST_RATE
--      ,OSPRN
--      ,PRINCIPAL
--      ,INTEREST
--      ,DISB_PERCENTAGE
--      ,DISB_AMOUNT
--      ,PLAFOND
--      ,I_DAYS
--      ,COUNTER
--      ,ICC
--      ,OUTSTANDING
--      ,SOURCE_PROCESS
--      ,SCH_FLAG
--      ,GRACE_DATE
--    )
--    SELECT A.DOWNLOAD_DATE
--      ,A.MASTERID
--      ,B.START_AMORTIZATION_DATE PMTDATE
--      ,A.INTEREST_RATE
--      ,A.OSPRN
--      ,A.PRINCIPAL
--      ,A.INTEREST
--      ,A.DISB_PERCENTAGE
--      ,A.DISB_AMOUNT
--      ,A.PLAFOND
--      ,A.I_DAYS
--      ,A.COUNTER
--      ,A.ICC
--      ,A.OUTSTANDING
--      ,A.SOURCE_PROCESS
--      ,A.SCH_FLAG
--      ,A.GRACE_DATE
--    FROM IFRS_PAYM_SCHD A
--    INNER JOIN TMP3 B
--    ON A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
--    AND A.MASTERID = B.MASTERID;
--
--    COMMIT;
--
--    INSERT INTO IFRS_PAYM_SCHD
--    (DOWNLOAD_DATE
--      ,MASTERID
--      ,PMTDATE
--      ,INTEREST_RATE
--      ,OSPRN
--      ,PRINCIPAL
--      ,INTEREST
--      ,DISB_PERCENTAGE
--      ,DISB_AMOUNT
--      ,PLAFOND
--      ,I_DAYS
--      ,COUNTER
--      ,ICC
--      ,OUTSTANDING
--      ,SOURCE_PROCESS
--      ,SCH_FLAG
--      ,GRACE_DATE
--    )
--    SELECT
--       A.DOWNLOAD_DATE
--      ,A.MASTERID
--      ,A.PMTDATE
--      ,A.INTEREST_RATE
--      ,(A.OSPRN  +  A.PRINCIPAL ) AS OSPRN
--      ,0.000000 AS PRINCIPAL
--      ,0.000000 AS INTEREST
--      ,0.000000 AS DISB_PERCENTAGE
--      ,(A.OSPRN  +  A.PRINCIPAL ) AS DISB_AMOUNT
--      ,A.PLAFOND
--      ,0 AS I_DAYS
--      ,0 AS COUNTER
--      ,A.ICC
--      ,A.OUTSTANDING
--      ,A.SOURCE_PROCESS
--      ,A.SCH_FLAG
--      ,A.GRACE_DATE
--    FROM TMP_IFRS_PAYM_SCHD A
--    INNER JOIN IFRS_IMA_AMORT_CURR B ON A.MASTERID = B.MASTERID  AND B.ECF_STATUS = 'Y'
--    INNER JOIN TMP_IFRS_PAYM_SCHD_COUNTER D
--     ON A.MASTERID = D.MASTERID AND A.COUNTER = D.COUNTER;
--
--    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP4';

    INSERT /*+ PARALLEL(12) */ INTO TMP4
    SELECT /*+ PARALLEL(12) */ A.DOWNLOAD_DATE,
        A.MASTERID,
        CASE WHEN TENOR_TYPE = 'E' THEN B.EXPECTED_LIFE * INTERVAL '1' MONTH +A.LOAN_START_DATE ELSE A.LOAN_DUE_DATE END AS EXPECTED_DATE
    FROM IFRS_IMA_AMORT_CURR A
    LEFT JOIN IFRS_PRODUCT_PARAM B
    ON (A.PRODUCT_CODE = B.PRD_CODE OR B.PRD_CODE = 'ALL')
    AND A.DATA_SOURCE = B.DATA_SOURCE
    AND A.PRODUCT_TYPE = B.PRD_TYPE
    AND (A.CURRENCY = B.CCY OR B.CCY = 'ALL')
    WHERE A.ECF_STATUS = 'Y'
    AND (A.STAFF_LOAN_FLAG='Y' OR A.BELOW_MARKET_FLAG='Y');


    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LBM_PAYM_CORE_SRC';

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_PAYM_CORE_SRC (
       MASTERID
      ,PREV_PMT_DATE
      ,PMT_DATE
      ,INTEREST_RATE
      ,I_DAYS
      ,PRN_AMT
      ,INT_AMT
      ,DISB_PERCENTAGE
      ,DISB_AMOUNT
      ,PLAFOND
      ,OS_PRN_PREV
      ,OS_PRN
      ,COUNTER
      ,ICC
      ,GRACE_DATE
    )
    SELECT /*+ PARALLEL(12) */
       SCH.MASTERID
      ,NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE)
      ,SCH.PMTDATE
      ,SCH.INTEREST_RATE
      ,CASE WHEN SCH.ICC IN(6,9)
          THEN CASE WHEN V_CALC_IDAYS = 0
                    THEN CASE WHEN (ROW_NUMBER() OVER (PARTITION BY SCH.MASTERID ORDER BY PMTDATE) - 1) = 1
                              THEN CASE WHEN MONTHS_BETWEEN(LAST_DAY(SCH.PMTDATE), LAST_DAY(NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE))) = 0
                                        THEN 30
                                        ELSE MONTHS_BETWEEN(LAST_DAY(SCH.PMTDATE), LAST_DAY(NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE))) * 30
                                   END
                              ELSE MONTHS_BETWEEN(LAST_DAY(SCH.PMTDATE), LAST_DAY(NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE))) * 30
                         END
                    WHEN V_CALC_IDAYS = 1
                    THEN FN_CNT_DAYS_30_360(NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE), SCH.PMTDATE)
                    ELSE FN_CNT_DAYS_30_360(NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE), SCH.PMTDATE)
                END
        ELSE NVL(SCH.PMTDATE - NVL(LAG(SCH.PMTDATE) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.PMTDATE),0)
        END I_DAYS
      ,CASE
        WHEN SCH.COUNTER = MAX(SCH.COUNTER) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID)
        THEN  LAG(SCH.OSPRN) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID ORDER BY SCH.PMTDATE)
        ELSE SCH.PRINCIPAL  END NEW_PRINCIPAL
      , SCH.INTEREST  AS INTEREST
      ,SCH.DISB_PERCENTAGE
      ,SCH.DISB_AMOUNT AS DISB_AMOUNT
      ,SCH.PLAFOND
      ,NVL(LAG(SCH.OSPRN) OVER (PARTITION BY SCH.MASTERID ORDER BY SCH.PMTDATE), SCH.OSPRN)
      ,CASE
        WHEN SCH.COUNTER = MAX(SCH.COUNTER) OVER (PARTITION BY SCH.DOWNLOAD_DATE,SCH.MASTERID)
        THEN  0  ELSE  SCH.OSPRN  END OSPRN
      ,  (ROW_NUMBER () OVER (PARTITION BY SCH.MASTERID ORDER BY SCH.PMTDATE) -1)   COUNTER
      ,SCH.ICC
      ,SCH.GRACE_DATE
    FROM IFRS_LBM_PAYM_SCHD SCH
    INNER JOIN TMP4 B
    ON  SCH.MASTERID = B.MASTERID
    WHERE SCH.MASTERID NOT IN (
        SELECT MASTERID FROM IFRS_IMA_AMORT_CURR WHERE ACCOUNT_NUMBER IN (
                SELECT DISTINCT UNIQUE_ID
              FROM IFRS_EXCEPTION_DETAILS
              WHERE EXCEPTION_CODE LIKE 'PAY-%'
               AND DOWNLOAD_DATE = V_CURRDATE
         )
    )
    AND  SCH.PMTDATE <= B.EXPECTED_DATE;

  COMMIT;

  /***************************************************************
  17 JAN 2019 BY VIVI - ADJUST INTEREST AMOUNT
  ****************************************************************/
    UPDATE /*+ PARALLEL(12) */ IFRS_PAYM_CORE_SRC
    SET INT_AMT=
     CASE WHEN ICC = '1' THEN INTEREST_RATE/ 100 * OS_PRN_PREV* I_DAYS/ 360--ACTUAL/360
         WHEN ICC = '2' THEN INTEREST_RATE/ 100 * OS_PRN_PREV* I_DAYS/ 365--ACTUAL/365
         WHEN ICC = '6' THEN INTEREST_RATE/ 100 * OS_PRN_PREV* I_DAYS/ 360--ACTUAL/360
         WHEN ICC IN ('7','9')  THEN CASE WHEN EXTRACT (YEAR FROM PREV_PMT_DATE)=EXTRACT (YEAR FROM PMT_DATE)
                                          THEN INTEREST_RATE/ 100 * OS_PRN_PREV* I_DAYS/ FN_IDAYS_CURR_YEAR(PREV_PMT_DATE)
                                          ELSE INTEREST_RATE/ 100 * OS_PRN_PREV* (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE)/ FN_IDAYS_CURR_YEAR(PREV_PMT_DATE) +
                                               INTEREST_RATE/ 100 * OS_PRN_PREV* (I_DAYS - (FN_LASTDAY_OF_YEAR(PREV_PMT_DATE)-PREV_PMT_DATE))/ FN_IDAYS_CURR_YEAR(PMT_DATE)
                                      END
         END
    WHERE COUNTER=1;

    COMMIT;
END;