CREATE OR REPLACE PROCEDURE SP_IFRS_GENERATE_RULE (v_CONSTNAME VARCHAR2 DEFAULT ' ')
AS
  v_RULE_ID varchar2(250);
  v_DETAIL_TYPE varchar2(25);
  v_TABLE_NAME varchar2(30);
  v_OWNER    VARCHAR2(20);

  CURSOR seg1 IS
  SELECT DISTINCT
    b.detail_type,
    b.rule_id,
    table_name
  FROM IFRS_SCENARIO_RULES_HEADER a
  INNER JOIN IFRS_SCENARIO_RULES_DETAIL b
  ON A.PKID = B.RULE_ID
  AND (A.RULE_TYPE = v_CONSTNAME OR NVL(v_CONSTNAME, ' ') = ' ');
  --AND a.CREATEDBY = 'D0E645CD-CCD7-4EA7-8968-7236EA952C40'; -- FILTER UNTUK TESTING DATA BCA


BEGIN
  SELECT USERNAME INTO v_OWNER FROM USER_USERS;

  DBMS_STATS.unlock_table_stats(v_OWNER, 'GTMP_IFRS_SCENARIO_GEN_QUERY');
  DBMS_STATS.DELETE_table_stats(v_OWNER, 'GTMP_IFRS_SCENARIO_GEN_QUERY');
  EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_SCENARIO_GEN_QUERY';

  OPEN seg1;
  FETCH seg1 INTO v_DETAIL_TYPE, v_RULE_ID, v_TABLE_NAME;
  WHILE seg1%FOUND
  LOOP

    INSERT INTO GTMP_IFRS_SCENARIO_GEN_QUERY (RULE_TYPE, RULE_ID, TABLE_NAME, PD_RULES_QRY_RESULT)
      VALUES (v_DETAIL_TYPE, v_RULE_ID, v_TABLE_NAME, FN_GENERATE_RULE(v_RULE_ID, v_DETAIL_TYPE));

    COMMIT;

    FETCH seg1 INTO v_DETAIL_TYPE, v_RULE_ID,v_TABLE_NAME;

  END LOOP;
  CLOSE seg1;
END;