CREATE OR REPLACE PROCEDURE SP_IFRS_LGD_NPL_ACCOUNT
AS
    V_CURRDATE DATE;
BEGIN

    SELECT  CURRDATE
    INTO V_CURRDATE
    FROM IFRS_PRC_DATE_LGD ;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_LGD_NPL_ACCOUNT';
    COMMIT;

    INSERT INTO TMP_IFRS_LGD_NPL_ACCOUNT (ACCOUNT_NUMBER,
                                          CUSTOMER_NUMBER,
                                          BI_COLLECTABILITY_NPL,
                                          OUTSTANDING_FIRST_NPL,
                                          LOSS_DATE,
                                          CLOSED_DATE,
                                          DATA_SOURCE)
    --POPULASI NPL KARTU KREDIT INDIVIDUAL
    /*
    SELECT ACCOUNT_NUMBER,
        BI_COLLECTABILITY BI_COLLECTABILITY_NPL,
        OUTSTANDING OUTSTANDING_FIRST_NPL,
        RESERVED_DATE_3 LOSS_DATE,
        DOWNLOAD_DATE CLOSED_DATE,
        DATA_SOURCE
    FROM IFRS_MASTER_ACCOUNT
    WHERE
        ACCOUNT_STATUS IN ('C','W')
        AND BI_COLLECTABILITY IN ('3','4','5','C')
        AND OUTSTANDING = 0
        AND RESERVED_DATE_3 IS NOT NULL
        AND DATA_SOURCE = 'CRD'
        AND PRODUCT_CODE = 'CARDS'
        AND DOWNLOAD_DATE = V_CURRDATE */
    SELECT DISTINCT
        C.CUSTOMER_NUMBER ACCOUNT_NUMBER,
        C.CUSTOMER_NUMBER,
        C.BI_COLLECTABILITY BI_COLLECTABILITY_NPL,
        C.OUTSTANDING OUTSTANDING_FIRST_NPL,
        XX.LOSS_DATE,
        C.DOWNLOAD_DATE CLOSED_DATE,
        C.DATA_SOURCE
    FROM (
        SELECT CUSTOMER_NUMBER,MIN(RESERVED_DATE_3) LOSS_DATE
        FROM IFRS_MASTER_ACCOUNT
        WHERE
            ACCOUNT_STATUS IN ('C','W')
            AND BI_COLLECTABILITY IN ('3','4','5','C')
            AND OUTSTANDING = 0
            AND RESERVED_DATE_3 IS NOT NULL
            AND DATA_SOURCE = 'CRD'
            AND PRODUCT_CODE = 'CARDS'
            AND DOWNLOAD_DATE = V_CURRDATE
        GROUP BY CUSTOMER_NUMBER
    )XX
    INNER JOIN IFRS_MASTER_ACCOUNT C ON XX.CUSTOMER_NUMBER=C.CUSTOMER_NUMBER
        AND XX.LOSS_DATE=C.RESERVED_DATE_3
    UNION
    --POPULASI NPL KARTU KREDIT LOKAL
    SELECT
        ACCOUNT_NUMBER,
        CUSTOMER_NUMBER,
        BI_COLLECTABILITY BI_COLLECTABILITY_NPL,
        RESERVED_AMOUNT_8 OUTSTANDING_FIRST_NPL,
        RESERVED_DATE_3 LOSS_DATE,
        DOWNLOAD_DATE CLOSED_DATE,
        DATA_SOURCE
    FROM IFRS_MASTER_ACCOUNT
    WHERE
        (ACCOUNT_STATUS = 'C'
         AND BI_COLLECTABILITY IN ('3','4','5','C')
         AND OUTSTANDING > 0
         AND RESERVED_DATE_3 IS NOT NULL
         AND DATA_SOURCE = 'ILS'
         AND PRODUCT_CODE = '101'
         AND DOWNLOAD_DATE = V_CURRDATE)
        OR
        -- NON KARTU KREDIT
        (ACCOUNT_STATUS = 'C'
         AND BI_COLLECTABILITY IN ('3','4','5','C')
         AND OUTSTANDING = 0
         AND RESERVED_DATE_3 IS NOT NULL
         AND DATA_SOURCE = 'ILS'
         AND PRODUCT_CODE != '101'
         AND DOWNLOAD_DATE = V_CURRDATE)
     ;
    /*
    UNION
    SELECT ACCOUNT_NUMBER,
        BI_COLLECTABILITY BI_COLLECTABILITY_NPL,
        RESERVED_AMOUNT_8 OUTSTANDING_FIRST_NPL,
        RESERVED_DATE_3 LOSS_DATE,
        DOWNLOAD_DATE CLOSED_DATE,
        DATA_SOURCE
    FROM IFRS_MASTER_ACCOUNT_MONTHLY
    WHERE
        ACCOUNT_STATUS ='C'
        AND BI_COLLECTABILITY IN ('3','4','5','C')
        AND OUTSTANDING=0
        AND RESERVED_DATE_3 IS NOT NULL
        AND DATA_SOURCE = 'ILS'
        AND PRODUCT_CODE != '101'
        AND DOWNLOAD_DATE=LAST_DAY(V_CURRDATE);
        */
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_CEK_IFRS_LGD_NPL_ACCOUNT';
    COMMIT;

    INSERT INTO TMP_CEK_IFRS_LGD_NPL_ACCOUNT (ACCOUNT_NUMBER,
                                              CUSTOMER_NUMBER,
                                              BI_COLLECTABILITY_NPL,
                                              OUTSTANDING_FIRST_NPL,
                                              LOSS_DATE,
                                              CLOSED_DATE,
                                              DATA_SOURCE)
    SELECT ACCOUNT_NUMBER,
        CUSTOMER_NUMBER,
        BI_COLLECTABILITY_NPL,
        OUTSTANDING_FIRST_NPL,
        LOSS_DATE,
        CLOSED_DATE,
        DATA_SOURCE
    FROM IFRS_LGD_NPL_ACCOUNT
    WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER
                             FROM TMP_IFRS_LGD_NPL_ACCOUNT)
    UNION
    SELECT ACCOUNT_NUMBER,
        CUSTOMER_NUMBER,
        BI_COLLECTABILITY_NPL,
        OUTSTANDING_FIRST_NPL,
        LOSS_DATE,
        CLOSED_DATE,
        DATA_SOURCE
    FROM TMP_IFRS_LGD_NPL_ACCOUNT;
    COMMIT;

    --INSERT INTO IFRS_LGD_NPL_ACCOUNT
    MERGE INTO IFRS_LGD_NPL_ACCOUNT D
    USING (
            SELECT XX.ACCOUNT_NUMBER,
                B.CUSTOMER_NUMBER,
                B.BI_COLLECTABILITY_NPL,
                B.OUTSTANDING_FIRST_NPL,
                XX.LOSS_DATE,
                XX.CLOSED_DATE ,
                B.DATA_SOURCE
            FROM (
                SELECT ACCOUNT_NUMBER,
                    MIN(LOSS_DATE)LOSS_DATE,
                    MIN(CLOSED_DATE) CLOSED_DATE,
                    MAX(BI_COLLECTABILITY_NPL) BI_COLLECTABILITY_NPL
                FROM TMP_CEK_IFRS_LGD_NPL_ACCOUNT
                GROUP BY ACCOUNT_NUMBER
            )XX
            INNER JOIN TMP_CEK_IFRS_LGD_NPL_ACCOUNT B ON XX.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER
                AND XX.LOSS_DATE    =   B.LOSS_DATE
                AND XX.CLOSED_DATE  =   B.CLOSED_DATE
                AND XX.BI_COLLECTABILITY_NPL = B.BI_COLLECTABILITY_NPL
        )S ON (S.ACCOUNT_NUMBER     =   D.ACCOUNT_NUMBER
                )
    WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_NUMBER         = S.CUSTOMER_NUMBER,
        BI_COLLECTABILITY_NPL   = S.BI_COLLECTABILITY_NPL,
        OUTSTANDING_FIRST_NPL   = S.OUTSTANDING_FIRST_NPL,
        LOSS_DATE               = S.LOSS_DATE,
        CLOSED_DATE             = S.CLOSED_DATE,
        DATA_SOURCE             = S.DATA_SOURCE,
        UPDATEDDATE             = SYSDATE
    WHEN NOT MATCHED THEN
    INSERT (ACCOUNT_NUMBER,
            CUSTOMER_NUMBER,
            BI_COLLECTABILITY_NPL,
            OUTSTANDING_FIRST_NPL,
            LOSS_DATE,
            CLOSED_DATE,
            DATA_SOURCE)
    VALUES (S.ACCOUNT_NUMBER,
            S.CUSTOMER_NUMBER,
            S.BI_COLLECTABILITY_NPL,
            S.OUTSTANDING_FIRST_NPL,
            S.LOSS_DATE,
            S.CLOSED_DATE,
            S.DATA_SOURCE);
    COMMIT;

END;