CREATE OR REPLACE PROCEDURE SP_IFRS_PD_VAS_Z_SCORE (V_EFF_DATE DATE)
AS
	v_mean number;
	v_stddev number;
BEGIN
    SELECT AVG(ME_VAL),
        STDDEV(ME_VAL)
	INTO v_mean, v_stddev
	FROM
	(
        SELECT ME_PERIOD, ME_VAL
        FROM IFRS_MACRO_ECONOMIC A
        WHERE ME_CODE = 'GDP_VOL_M_YOY'
        UNION ALL
        SELECT ME_PERIOD, ME_VAL
        FROM TBLU_MACRO_ECONOMIC_FORECAST B
        WHERE ME_CODE = 'GDP_VOL_M_YOY'
	) A
	WHERE EXTRACT(MONTH FROM A.ME_PERIOD) = 12
	AND EXTRACT(YEAR FROM A.ME_PERIOD) BETWEEN 2007--MIN_FL_YEAR - COUNT_FL_YEAR
	AND EXTRACT(YEAR FROM v_EFF_DATE);

	DELETE IFRS_PD_VAS_ME_PROJECTION
	WHERE EFF_DATE = v_EFF_DATE;

	COMMIT;

	INSERT INTO IFRS_PD_VAS_ME_PROJECTION
	(
		EFF_DATE,
		ME_CODE,
		FL_YEAR,
		PERCENT_GROWTH,
		Z_SCORE
	)
	SELECT v_EFF_DATE EFF_DATE,
		ME_CODE,
		ROW_NUMBER() OVER (ORDER BY EXTRACT(YEAR FROM ME_PERIOD)),
		ME_VAL,
		(ME_VAL - v_mean)/v_stddev Z_SCORE
	FROM TBLU_MACRO_ECONOMIC_FORECAST
	WHERE ME_CODE = 'GDP_VOL_M_YOY'
	AND EXTRACT(MONTH FROM ME_PERIOD) = 12
	AND EXTRACT(YEAR FROM ME_PERIOD) > EXTRACT(YEAR FROM v_EFF_DATE);

	COMMIT;
END;