CREATE OR REPLACE PROCEDURE SP_IFRS_VALIDATION(V_DATE DATE DEFAULT ('1-JAN-1900'))
AS
    V_SPNAME varchar2(500);
    V_CURRDATE DATE;
BEGIN

    IF V_DATE = '1-JAN-1900'
    THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS.IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := V_DATE;
    END IF;

    V_SPNAME := 'SP_IFRS_VALIDATION_PROCESS('''|| TO_CHAR(V_CURRDATE, 'dd-mon-yyyy')  ||''')';
    IFRS.SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME,'REPORT','Y');
END;