CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_SWITCH
AS
  V_CURRDATE   DATE;
  V_PREVDATE   DATE;

BEGIN

    SELECT MAX(CURRDATE),MAX (PREVDATE)
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    INSERT INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_ACCT_SWITCH','');

    --delete first
    DELETE /*+ PARALLEL(12) */ FROM IFRS_ACCT_SWITCH
    WHERE DOWNLOAD_DATE >= V_CURRDATE;

    COMMIT;

    --detect prev acct no
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SWITCH
    ( DOWNLOAD_DATE,
      DATASOURCE,
      MASTERID,
      FACNO,
      CIFNO,
      ACCTNO,
      PREV_ACCTNO,
      PREV_MASTERID,
      CREATEDBY,
      CREATEDDATE,
      PREV_SL_ECF,
      PREV_EIR_ECF,
      PRDCODE,
      BRCODE,
      PRDTYPE,
      PREV_DATASOURCE,
      PREV_FACNO,
      PREV_CIFNO,
      PREV_BRCODE,
      PREV_PRDTYPE,
      PREV_PRDCODE,
      CCY,
      LOAN_AMT,
      PLAFOND
    )
    SELECT /*+ PARALLEL(12) */ V_CURRDATE,
           A.DATA_SOURCE,
           A.MASTERID,
           A.FACILITY_NUMBER,
           A.CUSTOMER_NUMBER,
           A.ACCOUNT_NUMBER,
           A.PREVIOUS_ACCOUNT_NUMBER,
           B.MASTERID,
           'SP_IFRS_ACCT_SWITCH',
           SYSTIMESTAMP,
           'N',
           'N',
           A.PRODUCT_CODE,
           A.BRANCH_CODE,
           A.PRODUCT_TYPE,
           B.DATA_SOURCE,
           B.FACILITY_NUMBER,
           B.CUSTOMER_NUMBER,
           B.BRANCH_CODE,
           B.PRODUCT_TYPE,
           B.PRODUCT_CODE,
           A.CURRENCY,
           A.LOAN_AMT,
           A.PLAFOND
    FROM IFRS_IMA_AMORT_CURR A
    JOIN IFRS_IMA_AMORT_PREV B
      ON A.PREVIOUS_ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
      AND (B.ACCOUNT_NUMBER = B.PREVIOUS_ACCOUNT_NUMBER
            OR NVL(B.PREVIOUS_ACCOUNT_NUMBER,'')='')
      AND A.CURRENCY = B.CURRENCY         -- make sure same currency
    WHERE A.ACCOUNT_NUMBER <> A.PREVIOUS_ACCOUNT_NUMBER
    AND NVL(A.PREVIOUS_ACCOUNT_NUMBER,'') <> '';
    COMMIT;

    --change branch
    INSERT /*+ PARALLEL(12) */ INTO IFRS_ACCT_SWITCH
    ( DOWNLOAD_DATE,
      DATASOURCE,
      MASTERID,
      FACNO,
      CIFNO,
      ACCTNO,
      PREV_ACCTNO,
      PREV_MASTERID,
      CREATEDBY,
      CREATEDDATE,
      PREV_SL_ECF,
      PREV_EIR_ECF,
      PRDCODE,
      BRCODE,
      PRDTYPE,
      PREV_DATASOURCE,
      PREV_FACNO,
      PREV_CIFNO,
      PREV_BRCODE,
      PREV_PRDTYPE,
      PREV_PRDCODE,
      CCY,
      LOAN_AMT,
      PLAFOND
    )
    SELECT /*+ PARALLEL(12) */ V_CURRDATE,
           A.DATA_SOURCE,
           A.MASTERID,
           A.FACILITY_NUMBER,
           A.CUSTOMER_NUMBER,
           A.ACCOUNT_NUMBER,
           B.ACCOUNT_NUMBER,
           B.MASTERID,
           'SP_IFRS_ACCT_SWITCH',
           SYSTIMESTAMP,
           'N',
           'N',
           A.PRODUCT_CODE,
           A.BRANCH_CODE,
           A.PRODUCT_TYPE,
           B.DATA_SOURCE,
           B.FACILITY_NUMBER,
           B.CUSTOMER_NUMBER,
           B.BRANCH_CODE,
           B.PRODUCT_TYPE,
           B.PRODUCT_CODE,
           A.CURRENCY,
           A.LOAN_AMT,
           A.PLAFOND
    FROM IFRS_IMA_AMORT_CURR A
    JOIN IFRS_IMA_AMORT_PREV B
      ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
      AND A.CURRENCY = B.CURRENCY         -- make sure same currency
    WHERE A.BRANCH_CODE <> B.BRANCH_CODE
    AND  B.ACCOUNT_NUMBER NOT IN (SELECT DISTINCT ACCTNO FROM IFRS_ACCT_SWITCH  WHERE DOWNLOAD_DATE = V_CURRDATE);
    COMMIT;


    -- new account method of amort
    MERGE  INTO IFRS_ACCT_SWITCH A
    USING (SELECT X.*, V_CURRDATE CURRDATE
           FROM IFRS_PRODUCT_PARAM X
           ) B
    ON (B.PRD_CODE = A.PRDCODE
             AND B.DATA_SOURCE = A.DATASOURCE
             AND B.PRD_TYPE = A.PRDTYPE
             AND A.CCY = B.CCY
             AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.METHOD =B.AMORT_TYPE;
    COMMIT;

    --ADD LBM SWITCH 20180823
    DELETE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_SWITCH WHERE DOWNLOAD_DATE >= V_CURRDATE;

    COMMIT;

    INSERT /*+ PARALLEL(12) */ INTO IFRS_LBM_ACCT_SWITCH (
    ID,
    DOWNLOAD_DATE,
    FACNO,
    CIFNO,
    ACCTNO,
    BRCODE,
    PRDTYPE,
    PRDCODE,
    DATASOURCE,
    MASTERID,
    PREV_ACCTNO,
    PREV_FACNO,
    PREV_CIFNO,
    PREV_BRCODE,
    PREV_PRDTYPE,
    PREV_PRDCODE,
    PREV_DATASOURCE,
    PREV_MASTERID,
    PREV_SL_ECF,
    PREV_EIR_ECF,
    METHOD,
    CCY,
    LOAN_AMT,
    PLAFOND,
    SW_ADJ_FEE,
    SW_ADJ_COST,
    CREATEDDATE,
    CREATEDBY
    )
    SELECT /*+ PARALLEL(12) */ ID,
    DOWNLOAD_DATE,
    FACNO,
    CIFNO,
    ACCTNO,
    BRCODE,
    PRDTYPE,
    PRDCODE,
    DATASOURCE,
    MASTERID,
    PREV_ACCTNO,
    PREV_FACNO,
    PREV_CIFNO,
    PREV_BRCODE,
    PREV_PRDTYPE,
    PREV_PRDCODE,
    PREV_DATASOURCE,
    PREV_MASTERID,
    PREV_SL_ECF,
    PREV_EIR_ECF,
    METHOD,
    CCY,
    LOAN_AMT,
    PLAFOND,
    SW_ADJ_FEE,
    SW_ADJ_COST,
    CREATEDDATE,
    CREATEDBY
    FROM IFRS_ACCT_SWITCH
    WHERE DOWNLOAD_DATE = V_CURRDATE;
    --END ADD LBM SWITCH 20180823
    COMMIT;

     --detect sl ecf non lbm
    MERGE  INTO IFRS_ACCT_SWITCH A
    USING (SELECT B.MASTERID, V_CURRDATE CURRDATE
           FROM IFRS_ACCT_SL_ECF B
           WHERE NVL(B.AMORTSTOPDATE,NULL) IS NULL AND B.PREVDATE = B.PMTDATE
           ) B
    ON (B.MASTERID = A.PREV_MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.PREV_SL_ECF='Y';
    COMMIT;


    --detect eir ecf non lbm
    MERGE INTO IFRS_ACCT_SWITCH A
    USING (SELECT B.MASTERID, V_CURRDATE CURRDATE
           FROM IFRS_ACCT_EIR_ECF B
           WHERE NVL(B.AMORTSTOPDATE,NULL) IS NULL
           AND B.PREV_PMT_DATE = B.PMT_DATE
           ) B
    ON (B.MASTERID = A.PREV_MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.PREV_EIR_ECF='Y';
    COMMIT;

     --DETECT EIR ECF LBM
    MERGE  INTO IFRS_LBM_ACCT_SWITCH A
    USING (SELECT B.MASTERID, V_CURRDATE CURRDATE
           FROM IFRS_LBM_ACCT_EIR_ECF B
           WHERE NVL(B.AMORTSTOPDATE,NULL) IS NULL AND B.PREV_PMT_DATE = B.PMT_DATE
           ) B
    ON (B.MASTERID = A.PREV_MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.PREV_SL_ECF='Y';
    COMMIT;
    /*End add 20180828*/


    -- SL if revolving flag=Y : ONLY CTBC
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SWITCH
    SET METHOD = 'SL'
    WHERE DOWNLOAD_DATE=V_CURRDATE
    AND MASTERID IN ( SELECT MASTERID FROM IFRS_IMA_AMORT_CURR
                      WHERE DOWNLOAD_DATE=V_CURRDATE AND REVOLVING_FLAG='Y')
    AND DATASOURCE <> 'ACCEPTANCE';
    COMMIT;

   -- NON LBM cancel if method not the same
    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_SWITCH
    SET PREV_SL_ECF = 'X',
    PREV_EIR_ECF = 'X',
    CREATEDBY = 'DIFF_METHOD'
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND ( (PREV_SL_ECF = 'Y' AND METHOD = 'EIR')
    OR (PREV_EIR_ECF = 'Y' AND METHOD = 'SL'));
    COMMIT;

    -- LBM CANCEL IF METHOD NOT THE SAME
     UPDATE /*+ PARALLEL(12) */ IFRS_LBM_ACCT_SWITCH
     SET PREV_SL_ECF = 'X'
      ,PREV_EIR_ECF = 'X'
      ,CREATEDBY = 'DIFF_METHOD'
     WHERE DOWNLOAD_DATE = V_CURRDATE
      AND (
       (
        PREV_SL_ECF = 'Y'
        AND METHOD = 'EIR'
        )
       OR (
        PREV_EIR_ECF = 'Y'
        AND METHOD = 'SL'
        )
       );
    COMMIT;

    -- cancel if new acct already have sl ecf
    MERGE  INTO IFRS_ACCT_SWITCH A
    USING ( SELECT B.MASTERID, V_CURRDATE CURRDATE
            FROM IFRS_ACCT_SL_ECF B
            WHERE NVL(B.AMORTSTOPDATE,'')='' AND B.PREVDATE = B.PMTDATE
          ) B
    ON (B.MASTERID = A.MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
        AND A.MASTERID <> A.PREV_MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.PREV_SL_ECF='X'
    ,A.PREV_EIR_ECF='X'
    ,A.CREATEDBY='SL_ECF_EXIST';
    COMMIT;


   -- cancel if new acct already have eir ecf
    MERGE  INTO IFRS_ACCT_SWITCH A
    USING (SELECT B.MASTERID, V_CURRDATE CURRDATE
           FROM IFRS_ACCT_EIR_ECF B
           WHERE NVL(B.AMORTSTOPDATE,'')=''
           AND B.PREV_PMT_DATE = B.PMT_DATE
          ) B
    ON (B.MASTERID = A.MASTERID
        AND A.DOWNLOAD_DATE = B.CURRDATE
        AND A.MASTERID <> A.PREV_MASTERID
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.PREV_SL_ECF = 'X',
        A.PREV_EIR_ECF = 'X',
        A.CREATEDBY = 'EIR_ECF_EXIST';
    COMMIT;


    -- update cost fee summ to new switch acct no
    MERGE  INTO IFRS_ACCT_COST_FEE_SUMM A
    USING ( SELECT B.*
            FROM IFRS_ACCT_SWITCH B
            JOIN IFRS_PRC_DATE_AMORT C
            ON C.CURRDATE = B.DOWNLOAD_DATE
            WHERE B.PREV_SL_ECF = 'Y' OR B.PREV_EIR_ECF = 'Y'
          ) B
    ON (A.MASTERID = B.PREV_MASTERID
        AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
       )
    WHEN MATCHED THEN
    UPDATE
    SET A.SW_MASTERID = B.MASTERID,
        A.BRCODE = B.BRCODE,
        A.CIFNO = B.CIFNO,
        A.FACNO = B.FACNO,
        A.ACCTNO = B.ACCTNO,
        A.DATASOURCE = B.DATASOURCE;
    COMMIT;


    UPDATE /*+ PARALLEL(12) */ IFRS_ACCT_COST_FEE_SUMM
    SET MASTERID = SW_MASTERID
    WHERE DOWNLOAD_DATE = V_CURRDATE
    AND SW_MASTERID IN (SELECT MASTERID
                        FROM IFRS_ACCT_SWITCH
                        WHERE DOWNLOAD_DATE = V_CURRDATE);
    COMMIT;

    INSERT INTO IFRS_AMORT_LOG ( DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES( V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_ACCT_SWITCH','');

    COMMIT;
END;