CREATE OR REPLACE PROCEDURE SP_IFRS_LIFETIME2310
AS
V_CURRDATE DATE;
V_PREVDATE DATE;

BEGIN

    SELECT CURRDATE, PREVDATE
    INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_DATE_DAY1;

    DELETE IFRS_LIFETIME_DETAIL WHERE DOWNLOAD_DATE >= V_CURRDATE;
    DELETE IFRS_LIFETIME_HEADER WHERE DOWNLOAD_DATE >= V_CURRDATE;

    COMMIT;

    -- REVOLVING_FLAG 0

    INSERT INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD        ,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CEIL((MONTHS_BETWEEN(RESERVED_DATE_8, A.LOAN_START_DATE)))LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.DPD_START_DATE,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE AND
          A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 0
          AND DATA_SOURCE = 'ILS'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);

    COMMIT;

    INSERT INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD        ,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CEIL((MONTHS_BETWEEN(RESERVED_DATE_8, A.LOAN_START_DATE)))LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB ,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.DPD_START_DATE,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE AND
          A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 0
          AND DATA_SOURCE = 'CRD'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);

    COMMIT;
    -- REVOLVING_FLAG 1

    INSERT INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CASE WHEN RESERVED_DATE_7 IS NOT NULL AND
              RESERVED_DATE_3 IS NOT NULL
              THEN ((12 + CEIL(MONTHS_BETWEEN (RESERVED_DATE_3, RESERVED_DATE_7))))
    ELSE 12 END LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB ,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.RESERVED_DATE_7,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
          --AND A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 1
          AND (RESERVED_DATE_3 IS NOT NULL OR BI_COLLECTABILITY >= '3')
          AND DATA_SOURCE = 'ILS'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);
          COMMIT;

    INSERT INTO IFRS_LIFETIME_DETAIL
    (
      DOWNLOAD_DATE   ,
      ACCOUNT_NUMBER  ,
      DATA_SOURCE     ,
      LOAN_DUE_DATE   ,
      LOAN_START_DATE ,
      LIFETIME_PERIOD,
      GOL_DEB         ,
      SEGMENTATION_ID ,
      REVOLVING_FLAG,
      DAY_PAST_DUE_DATE,
      NPL_DATE,
      END_DATE,
      CUSTOMER_NAME,
      CUSTOMER_NUMBER
    )
    SELECT
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.DATA_SOURCE,
    A.LOAN_DUE_DATE,
    A.LOAN_START_DATE,
    CASE WHEN RESERVED_DATE_7 IS NOT NULL AND RESERVED_DATE_3 IS NOT NULL THEN ((12 + CEIL(MONTHS_BETWEEN (RESERVED_DATE_3, RESERVED_DATE_7))))
                                                 ELSE 12 END LIFETIME,
    (A.RESERVED_VARCHAR_2)GOL_DEB,
    C.SEGMENTATION_ID,
    A.REVOLVING_FLAG,
    A.RESERVED_DATE_7,
    A.RESERVED_DATE_3,
    A.RESERVED_DATE_8,
    A.CUSTOMER_NAME,
    A.CUSTOMER_NUMBER
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_SCENARIO_DATA B ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.LIFETIME_RULE_ID = C.PKID
    WHERE A.DOWNLOAD_DATE = V_CURRDATE
          --AND A.ACCOUNT_STATUS = 'C'
          AND A.REVOLVING_FLAG = 1
          AND (RESERVED_DATE_3 IS NOT NULL OR RESERVED_AMOUNT_4 >= '5')
          AND A.DATA_SOURCE = 'CRD'
          AND A.ACCOUNT_NUMBER NOT IN (SELECT ACCOUNT_NUMBER FROM IFRS_LIFETIME_DETAIL);
          COMMIT;

          UPDATE IFRS_LIFETIME_DETAIL
            SET LIFETIME_PERIOD = CASE WHEN REVOLVING_FLAG = '1' THEN CASE WHEN LIFETIME_PERIOD <= 12 THEN 12 ELSE LIFETIME_PERIOD END
                                       WHEN REVOLVING_FLAG = '0' THEN CASE WHEN LIFETIME_PERIOD <= 12 THEN 12 ELSE LIFETIME_PERIOD END
                                  END
                                       WHERE DOWNLOAD_DATE = V_CURRDATE;COMMIT;


          /*
          INSERT INTO IFRS_LIFETIME_DETAIL_UNP
          SELECT * FROM IFRS_LIFETIME_DETAIL WHERE REVOLVING_FLAG = '1' AND MONTHS_BETWEEN (NPL_DATE, DAY_PAST_DUE_DATE) < 0
                                                AND DOWNLOAD_DATE = V_CURRDATE;COMMIT;


          DELETE IFRS_LIFETIME_DETAIL
          WHERE REVOLVING_FLAG = '1' AND MONTHS_BETWEEN (NPL_DATE, DAY_PAST_DUE_DATE) < 0
                                     AND DOWNLOAD_DATE = V_CURRDATE;COMMIT;
          */

        INSERT INTO IFRS_LIFETIME_HEADER (PKID,
                                          DOWNLOAD_DATE,
                                          LIFETIME_SEGMENT_ID,
                                          LIFETIME_CONFIG_ID,
                                          LIFETIME_SEGMENT,
                                          LIFETIME_PERIOD)
             SELECT 0,
                    V_CURRDATE,
                    B.SEGMENTATION_ID,
                    C.PKID,
                    C.LIFETIME_RULE_NAME,
                    CASE WHEN NVL(LIFETIME_OVERRIDE,0) <> 0 THEN LIFETIME_OVERRIDE ELSE
                    CASE
                       WHEN C.LIFETIME_METHOD = 1 THEN LM1
                       WHEN C.LIFETIME_METHOD = 2 THEN LM2
                       WHEN C.LIFETIME_METHOD = 3 THEN LM3
                    END END
                       LIFETIME_CALCULATION
               FROM  (  SELECT SEGMENTATION_ID,
                              (CEIL (AVG (LIFETIME_PERIOD))) LM1,
                              (ROUND (
                                  PERCENTILE_CONT (0.9) WITHIN GROUP (ORDER BY LIFETIME_PERIOD)))
                                 LM2,
                               (CEIL (AVG (LIFETIME_PERIOD))) LM3
                         FROM IFRS_LIFETIME_DETAIL
                     GROUP BY SEGMENTATION_ID)B
                          JOIN IFRS_LIFETIME_RULES_CONFIG C
                          ON B.SEGMENTATION_ID = C.SEGMENTATION_ID
           ORDER BY B.SEGMENTATION_ID, C.PKID;

        COMMIT;

        UPDATE IFRS_LIFETIME_HEADER
        SET LIFETIME_PERIOD = CASE WHEN LIFETIME_PERIOD < 12 THEN 12 ELSE LIFETIME_PERIOD END WHERE DOWNLOAD_dATE = V_CURRDATE;COMMIT;

       /* MERGE INTO IFRS_LIFETIME_HEADER A
        USING (SELECT D.DOWNLOAD_DATE, C.SEGMENTATION_ID, C.LIFETIME_METHOD, D.SICR_DATE, D.DAY_PAST_DUE_DATE from IFRS_LIFETIME_RULES_CONFIG C JOIN IFRS_LIFETIME_DETAIL D ON C.SEGMENTATION_ID = D.SEGMENTATION_ID WHERE D.DOWNLOAD_DATE = V_CURRDATE) B
        ON (A.LIFETIME_SEGMENT_ID = B.SEGMENTATION_ID AND A.DOWNLOAD_DATE = B.DOWNLOAD_DATE)
        WHEN MATCHED THEN UPDATE
        SET LIFETIME_PERIOD = CASE WHEN B.LIFETIME_METHOD = 3 THEN (1 + (MONTHS_BETWEEN (DAY_PAST_DUE_DATE, SICR_DATE) / 12))
                                   ELSE LIFETIME_PERIOD END;
                                   COMMIT;
*/
    /*
    INSERT INTO IFRS_LIFETIME_HEADER
    (
      PKID,
      LIFETIME_SEGMENT_ID,
      LIFETIME_CONFIG_ID,
      REVOLVING_FLAG
    )
    SELECT 0,
    B.SEGMENTATION_ID,
    B.LIFETIME_RULE_ID,
    B.REVOLVING_FLAG
    FROM IFRS_LIFETIME_DETAIL B
    WHERE B.DOWNLOAD_DATE >= B.CUT_OFF_DATE
    AND DOWNLOAD_DATE = V_CURRDATE
    GROUP BY B.SEGMENTATION_ID, B.PKID, B.REVOLVING_FLAG;

    COMMIT;

         MERGE INTO IFRS_LIFETIME_HEADER A
         USING (SELECT DOWNLOAD_DATE, SEGMENTATION_ID, LIFETIME_RULE_ID,LIFETIME_METHOD, (CEIL(AVG(LIFETIME)))LM1,
                                                            (ROUND(PERCENTILE_CONT(0.9)WITHIN GROUP (ORDER BY LIFETIME)))LM2
                                                            , (1+(MONTHS_BETWEEN(DAY_PAST_DUE_DATE,SICR_DATE)/12))LM3
                                                            FROM IFRS_LIFETIME_DETAIL WHERE DOWNLOAD_DATE = V_CURRDATE
                                                            GROUP BY SEGMENTATION_ID, LIFETIME_RULE_ID,LIFETIME_METHOD, (1+(MONTHS_BETWEEN(DAY_PAST_DUE_DATE,SICR_DATE)/12))) B
         ON (A.LIFETIME_SEGMENT_ID = B.SEGMENTATION_ID AND A.LIFETIME_CONFIG_ID = B.LIFETIME_RULE_ID)
         WHEN MATCHED THEN UPDATE
         SET A.LIFETIME_PERIOD = CASE WHEN  B.LIFETIME_METHOD = 1 THEN LM1
         WHEN                               B.LIFETIME_METHOD = 2 THEN LM2
         WHEN                               B.LIFETIME_METHOD = 3 THEN LM3
         END ;*/

END;