CREATE OR REPLACE PROCEDURE SP_IFRS_LBM_PAYM_CORE_PROC_NOP
AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_VCNT NUMBER(10);
  V_VLOOP2 NUMBER(10);
  V_VCNT2 NUMBER(10);
  V_PARAM_CUT_INT_1ST_PAYMENT NUMBER(10);
  V_PARAM_CALC_TO_LASTPAYMENT NUMBER(10);

BEGIN
    -- BYPASS SP_IFRS_LBM_PAYM_CORE_PROCESS USE THIS SP
    SELECT MAX(CURRDATE)
        , MAX(PREVDATE) INTO V_CURRDATE, V_PREVDATE
    FROM IFRS_PRC_DATE_AMORT;

    SELECT CASE WHEN COMMONUSAGE = 'Y' THEN 1 ELSE 0 END
    INTO V_PARAM_CALC_TO_LASTPAYMENT
    FROM TBLM_COMMONCODEHEADER
    WHERE COMMONCODE = 'SCM005';

    SELECT CASE WHEN COMMONUSAGE = 'Y' THEN 1 ELSE 0 END
    INTO V_PARAM_CUT_INT_1ST_PAYMENT
    FROM TBLM_COMMONCODEHEADER
    WHERE COMMONCODE = 'SCM006';

    -- PRORATE INT AMOUNT FROM PAYM SCHD CORE SO IT MATCH WITH GOALSEEK WHICH USING I_DAYS
    -- PARAM_CUT_INT_1ST_PAYMENT := 0 ==> DISABLE INTEREST  : 1==> ENABLE INTEREST
    v_PARAM_CUT_INT_1ST_PAYMENT := V_PARAM_CUT_INT_1ST_PAYMENT;
    -- CALC ECF BACK TO LAST PAYMENT DATE
    -- PARAM_CALC_TO_LASTPAYMENT := 0 ==> DISABLE CALC TO LAST PAYMENT DATE  : 1==> ENABLE CALC TO LAST PAYMENT DATE
    v_PARAM_CALC_TO_LASTPAYMENT := V_PARAM_CALC_TO_LASTPAYMENT;

    --CALC_FROM_LASTPAYMDATE
    --PARAM_CUT_INT
    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'START','SP_IFRS_LBM_PAYM_CORE_PROCESS','');

    COMMIT;

    UPDATE /*+ PARALLEL(8) */ IFRS_LBM_PAYM_CORE
    SET EIR1 = 12
        ,EIR2 = 12.1;
    COMMIT;


    INSERT /*+ PARALLEL(8) */ INTO IFRS_LBM_ACCT_EIR_PAYM (
        MASTERID
        ,DOWNLOAD_DATE
        ,N_LOAN_AMT
        ,N_INT_RATE
        ,STARTAMORTDATE
        ,ENDAMORTDATE
        ,GRACEDATE
        ,ISGRACE
        ,PREV_PMT_DATE
        ,PMT_DATE
        ,I_DAYS
        ,COUNTER
        ,N_OSPRN_PREV
        ,N_INSTALLMENT
        ,N_PRN_PAYMENT
        ,N_INT_PAYMENT
        ,N_INT_PAYMENT_ORG
        ,N_OSPRN
        ,DISB_PERCENTAGE
        ,DISB_AMOUNT
        ,PLAFOND
        ,PERIOD
        ,INTCALCCODE
        ,PAYMENTCODE
        ,PAYMENTTERM
        )
    /*  BCA DISABLE BPI ,SPECIAL_FLAG --- BPI FLAG ONLY CTBC */
    SELECT /*+ PARALLEL(8) */ A.MASTERID
        ,V_CURRDATE AS DOWNLOAD_DATE
        ,MAX(A.OS_PRN_PREV) OVER (PARTITION BY A.MASTERID)
        ,
        --B.INTEREST_RATE, REMARKS FOR MULTITIER 20160428
        A.INT_RATE
        ,--FOR MULTITIER --20160428
        V_CURRDATE AS STARTAMORTDATE
        ,MAX(A.PMT_DATE) OVER (PARTITION BY A.MASTERID)
        ,NVL(A.GRACE_DATE, V_CURRDATE) AS GRACEDATE
        ,CASE
            WHEN A.GRACE_DATE IS NOT NULL
                THEN 'Y'
            ELSE 'N'
            END AS ISGRACE
        ,A.PREV_PMT_DATE
        ,A.PMT_DATE
        ,A.I_DAYS
        ,A.COUNTER
        ,A.OS_PRN_PREV
        ,(A.PRN_AMT + A.INT_AMT) AS INSTALLMENT
        ,A.PRN_AMT
        ,A.INT_AMT
        ,A.INT_AMT
        ,A.OS_PRN
        ,A.DISB_PERCENTAGE
        ,A.DISB_AMOUNT
        ,A.PLAFOND
        ,MAX(A.COUNTER) OVER (PARTITION BY A.MASTERID)
        ,ICC AS INTCALCCODE
        ,'-' PAYMENTCODE
        ,'-' PAYMENTTERM
    /*  BCA DISABLE BPI ,A.SPECIAL_FLAG --- BPI FLAG ONLY CTBC */
    FROM IFRS_LBM_PAYM_CORE A
    LEFT JOIN IFRS_IMA_AMORT_CURR B ON B.MASTERID = A.MASTERID;

    COMMIT;

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'DEBUG','SP_IFRS_LBM_PAYM_CORE_PROCESS','INSERT TO EIR PAYM');

    INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE,DTM,OPS,PROCNAME,REMARK)
    VALUES (V_CURRDATE,SYSTIMESTAMP,'END','SP_IFRS_LBM_PAYM_CORE_PROCESS','');

    COMMIT;

END;