CREATE OR REPLACE PROCEDURE SP_IFRS_NOMINATIVE(v_DOWNLOADDATECUR  DATE DEFAULT ('1-JAN-1900'),
                                               v_DOWNLOADDATEPREV DATE DEFAULT ('1-JAN-1900')) AS
  V_CURRDATE DATE;
  V_PREVDATE DATE;
  V_SPNAME   VARCHAR2(150);
  V_RUNNING_MODE NUMBER := 0;
BEGIN

    EXECUTE IMMEDIATE 'alter session enable parallel dml';

    IF v_DOWNLOADDATECUR = '1-JAN-1900'
    THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATECUR;
    END IF;

    IF v_DOWNLOADDATEPREV = '1-JAN-1900'
    THEN
        SELECT CURRDATE INTO V_PREVDATE FROM IFRS_PRC_DATE;
    ELSE
        V_PREVDATE := v_DOWNLOADDATEPREV;
    END IF;
-- LEO
    SELECT CASE WHEN B.MAX_DATE IS NULL OR A.MAX_DATE > B.MAX_DATE THEN 0 ELSE 1 END
    INTO V_RUNNING_MODE
    FROM
        (
        SELECT MAX(NVL(END_DATE, START_DATE)) MAX_DATE
        FROM IFRS_STATISTIC
        WHERE DOWNLOAD_DATE = V_CURRDATE
        AND SP_NAME LIKE 'SP_IFRS_NOMINATIVE_TO_IMA(%'
    ) A
    JOIN
    (
        SELECT MAX(NVL(END_DATE, START_DATE)) MAX_DATE
        FROM IFRS_STATISTIC
        WHERE DOWNLOAD_DATE = V_CURRDATE
        AND SP_NAME LIKE 'SP_IFRS_NOMINATIVE_TO_IMA_PR%'
    ) B
    ON 1 = 1;

    V_SPNAME := 'SP_IFRS_DELETE_NOMINATIVE(' || '''' || TO_CHAR(V_CURRDATE,'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    IF V_RUNNING_MODE = 0 THEN
        V_SPNAME := 'SP_IFRS_INSERT_GTMP_FROM_IMA(' || '''' || TO_CHAR(V_CURRDATE,'dd-mon-yyyy') || '''' || ')';
        SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

        V_SPNAME := 'SP_IFRS_INSERT_GTMP_IMA_PREV(' || '''' || TO_CHAR(V_PREVDATE,'dd-mon-yyyy') || '''' || ')';
        SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');
    ELSE
        V_SPNAME := 'SP_IFRS_INSRT_GTMP_FROM_IMA_PR(' || '''' || TO_CHAR(V_CURRDATE,'dd-mon-yyyy') || '''' || ')';
        SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

        V_SPNAME := 'SP_IFRS_INSRT_GTMP_IMA_PREV_PR(' || '''' || TO_CHAR(V_PREVDATE,'dd-mon-yyyy') || '''' || ')';
        SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');
    END IF;

    V_SPNAME := 'SP_IFRS_NOMINATIVE_KTP(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    V_SPNAME := 'SP_IFRS_NOMINATIVE_ILS(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    V_SPNAME := 'SP_IFRS_NOMINATIVE_ILS_LIMIT(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    V_SPNAME := 'SP_IFRS_NOMINATIVE_BTRD(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    V_SPNAME := 'SP_IFRS_NOMINATIVE_CARD_W(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    V_SPNAME := 'SP_IFRS_NOMINATIVE_RKN_W(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || ''',' || TO_CHAR(V_RUNNING_MODE) || ')';
    SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

--DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_NOMINATIVE');
--DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_NOMINATIVE',DEGREE=>2);
DBMS_STATS.UNLOCK_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_NOMINATIVE_CUST_STAGE_MAX');
DBMS_STATS.GATHER_TABLE_STATS ( OWNNAME=>'IFRS', TABNAME=>'IFRS_NOMINATIVE_CUST_STAGE_MAX',DEGREE=>2);
--LEO
  V_SPNAME := 'SP_IFRS_UPDATE_NOMINATIVE(' || '''' ||TO_CHAR(V_CURRDATE, 'dd-mon-yyyy') || '''' || ',' || '''' || TO_CHAR(V_PREVDATE, 'dd-mon-yyyy') || '''' || ')';
  SP_IFRS_EXEC_AND_LOG_PROCESS(V_SPNAME, 'NOM', 'Y');

    DELETE /*+ PARALLEL(8) */ IFRS_NOMINATIVE_EXCEPTION WHERE REPORT_DATE = V_CURRDATE;
    COMMIT;

    INSERT /*+ PARALLEL(8) */ INTO IFRS_NOMINATIVE_EXCEPTION
    SELECT /*+ PARALLEL(8) */ * FROM IFRS_NOMINATIVE
    WHERE REPORT_DATE = V_CURRDATE
    AND ECL_TOTAL_CCY  <> RESERVED_AMOUNT_4;
    COMMIT;

  --DELETE IFRS_NOMINATIVE WHERE REPORT_DATE = V_CURRDATE;
  --COMMIT;

  --SP_IFRS_INSERT_GTMP_FROM_IMA(V_CURRDATE);
  --SP_IFRS_INSERT_GTMP_IMA_PREV(V_PREVDATE);

  --SP_IFRS_NOMINATIVE_KTP(V_CURRDATE, V_PREVDATE);
  --SP_IFRS_NOMINATIVE_ILS(V_CURRDATE, V_PREVDATE);
  --SP_IFRS_NOMINATIVE_BTRD(V_CURRDATE, V_PREVDATE);
  --SP_IFRS_NOMINATIVE_CARD_W(V_CURRDATE, V_PREVDATE);
  --SP_IFRS_NOMINATIVE_RKN_W(V_CURRDATE, V_PREVDATE);

END;