CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_UPDATE_STAGE (
   v_ECLID           NUMBER DEFAULT (0),
   v_DOWNLOADDATE    DATE DEFAULT NULL)
AS
   v_RULEID   NUMBER (10);
BEGIN
   SP_IFRS_GENERATE_RULE ('STAGE');
   SP_IFRS_RULE_DATA (v_DOWNLOADDATE);


   BEGIN
      SELECT DISTINCT SICR_RULE_ID
        INTO v_RULEID
        FROM IFRS_ECL_MODEL_CONFIG
       WHERE ECL_MODEL_ID = v_ECLID;
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         v_RULEID := 0;
   END;

   UPDATE IFRS_MASTER_ACCOUNT
      SET CR_STAGE = NULL
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE;

   COMMIT;

   MERGE INTO IFRS_MASTER_ACCOUNT A
        USING (  SELECT DOWNLOAD_DATE,
                        CUSTOMER_NUMBER,
                        MAX (RULE_TYPE) AS CR_STAGE
                   FROM GTMP_IFRS_SCENARIO_DATA
                  WHERE RULE_ID = v_RULEID
                        AND (ACCOUNT_STATUS = 'A'
                             OR (    DATA_SOURCE = 'CRD'
                                 AND ACCOUNT_STATUS = 'C'
                                 AND OUTSTANDING > 0))
               --        AND GROUP_SEGMENT != 'BANK_BTRD'
               GROUP BY DOWNLOAD_DATE, CUSTOMER_NUMBER) B
           ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
               AND A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER)
   WHEN MATCHED
   THEN
      UPDATE SET A.CR_STAGE = B.CR_STAGE;

   COMMIT;

   UPDATE IFRS_MASTER_ACCOUNT
      SET CR_STAGE = '1'
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE AND (GROUP_SEGMENT = 'BANK_BTRD');

   COMMIT;

   UPDATE IFRS_MASTER_ACCOUNT
      SET CR_STAGE = '1'
    WHERE     DOWNLOAD_DATE = v_DOWNLOADDATE
          AND DATA_SOURCE = 'LIMIT'
          AND CR_STAGE IS NULL;

   COMMIT;



   -----    CR-021 OVERRIDE STAGE 21 JUNE 2021
   MERGE INTO IFRS_MASTER_ACCOUNT A
        USING (SELECT DISTINCT CUSTOMER_NUMBER
                 FROM IFRS_MASTER_ACCOUNT
                WHERE (GROUP_SEGMENT IN
                          ('COMMERCIAL',
                           'COMMERCIAL BG',
                           'CORPORATE',
                           'CORPORATE BG')
                       AND DATA_SOURCE = 'ILS'
                       AND BI_COLLECTABILITY = '1'
                       AND RESERVED_FLAG_4 = 1)
                      AND DOWNLOAD_DATE = v_DOWNLOADDATE
                      AND CUSTOMER_NUMBER NOT IN
                             (SELECT CUSTOMER_NUMBER FROM TBLU_WORSTCASE_LIST)) B
           ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
               AND A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
               AND A.GROUP_SEGMENT IN
                      ('COMMERCIAL',
                       'COMMERCIAL BG',
                       'CORPORATE',
                       'CORPORATE BG')
               AND A.DATA_SOURCE = 'ILS'
               AND A.BI_COLLECTABILITY = '1'
               AND A.RESERVED_FLAG_4 = 1)
   WHEN MATCHED
   THEN
      UPDATE SET CR_STAGE = 1;

   COMMIT;

   ----- END OF CR-021 OVERRIDE STAGE 21 JUNE 2021

   -----    OVERRIDE STAGE WC TO STAGE 2 -- 31 MARCH 2022

   MERGE INTO IFRS_MASTER_ACCOUNT A
        USING TBLU_WORSTCASE_LIST B
           ON (A.DOWNLOAD_DATE = B.DOWNLOAD_DATE
               AND A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER)
   WHEN MATCHED
   THEN
      UPDATE SET CR_STAGE = 2
              WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE AND A.CR_STAGE = 1;

   COMMIT;

   -----    END OF OVERRIDE STAGE WC TO STAGE 2 -- 31 MARCH 2022


   MERGE INTO IFRS_MASTER_ACCOUNT A
        USING (SELECT DISTINCT A.CUSTOMER_NUMBER, B.STAGE_OVERRIDE
                 FROM    IFRS_STAGE_OVERRIDE_H A
                      JOIN
                         IFRS_STAGE_OVERRIDE_D B
                      ON A.PKID = B.MASTERID AND A.IGNORE_OVERRIDE = 0) B
           ON (A.DOWNLOAD_DATE = v_DOWNLOADDATE
               AND A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER)
   WHEN MATCHED
   THEN
      UPDATE SET CR_STAGE = B.STAGE_OVERRIDE;

   COMMIT;

   UPDATE IFRS_MASTER_ACCOUNT
      SET CR_STAGE = NULL
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
          AND TRIM (NVL (PRODUCT_CODE, '-')) NOT IN
                 (SELECT PRD_CODE FROM IFRS_MASTER_PRODUCT_PARAM);

   COMMIT;
END;