CREATE OR REPLACE PROCEDURE SP_LBM_SYNC_PAYM_CORE
AS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE IFRS_LBM_PAYM_CORE_SRC';

  COMMIT;

	INSERT INTO IFRS_LBM_PAYM_CORE_SRC
	SELECT B.*
	FROM (
		SELECT *
		FROM IFRS_IMA_AMORT_CURR
		WHERE (
				STAFF_LOAN_FLAG = 'Y'
				OR BELOW_MARKET_FLAG = 1
				)
		) A
	LEFT JOIN IFRS_PAYM_CORE_SRC B ON A.MASTERID = B.MASTERID;

  COMMIT;
END;