CREATE OR REPLACE PROCEDURE SP_UPD_HEADER_RAL
AS
    V_EFF_DATE date;
    V_MAXDATE date;
BEGIN

V_EFF_DATE := '30-Jun-2021';

V_MAXDATE := '28-Feb-2011';


WHILE V_MAXDATE <= V_EFF_DATE LOOP

    INSERT INTO IFRS_PPYMT_HEADER_RAL
    (
        DOWNLOAD_DATE,
        SEGMENTATION_ID,
        SEGMENTATION_NAME,
        PREPAYMENT_RULE_ID,
        PREPAYMENT_RULE_NAME,
        AVERAGE_SMM,
        PREPAYMENT_RATE,
        DURATION
    )
    SELECT
        V_MAXDATE DOWNLOAD_DATE,
        A.SEGMENTATION_ID,
        NVL(C.SEGMENT, '-') SEGMENTATION_NAME,
        NVL(D.PKID,0) PREPAYMENT_RULE_ID,
        NVL(D.PREPAYMENT_RULE_NAME, '-') PREPAYMENT_RULE_NAME,
        AVG(A.SMM)AVERAGE_SMM ,
        ROUND(1-POWER((1-AVG(A.SMM)),
            CASE WHEN A.INCREMENTS = 1  THEN 12
                 WHEN A.INCREMENTS = 3  THEN 4
                 WHEN A.INCREMENTS = 6  THEN 2
                 WHEN A.INCREMENTS = 12 THEN 1
            END),4
        ) PREPAYMENT_RATE,
        CASE WHEN A.INCREMENTS = 1  THEN 12
             WHEN A.INCREMENTS = 3  THEN 4
             WHEN A.INCREMENTS = 6  THEN 2
             WHEN A.INCREMENTS = 12 THEN 1
        END DURATION
    FROM IFRS_PPYMT_DTL_RAL A
    LEFT JOIN IFRS_MSTR_SEGMENT_RULES_HEADER C
      ON A.SEGMENTATION_ID = C.PKID
    LEFT JOIN IFRS_PREPAYMENT_RULES_CONFIG D
      ON C.PKID = D.SEGMENTATION_ID
    WHERE A.DOWNLOAD_DATE <= V_MAXDATE
        AND D.AVERAGE_METHOD = 'Simple'
        AND A.SMM >= 0
        AND A.DOWNLOAD_dATE <= V_MAXDATE
        AND A.DURATION = 12
    GROUP BY
        A.SEGMENTATION_ID,
        C.SEGMENT,
        D.PKID,
        D.PREPAYMENT_RULE_NAME,
        A.INCREMENTS;

    COMMIT;

    V_MAXDATE := ADD_MONTHS(V_MAXDATE,1);

END LOOP;

END;