CREATE OR REPLACE PROCEDURE TEST_UPDATE_PP4
AS
    V_CURRDATE DATE;
    V_PREVDATE DATE;

   BEGIN

       FOR LOOP_COUNTER IN 1..2
    LOOP

            SELECT CURRDATE, PREVDATE
            INTO V_CURRDATE, V_PREVDATE
            FROM IFRS_DATE_DAY1;

            INSERT INTO IFRS_MASTERID
                            (
                            PKID,
                            MASTER_ACCOUNT_CODE
                            )
    SELECT DISTINCT 0, ACCOUNT_NUMBER FROM IFRS_MASTER_ACCOUNT_MONTHLY
    WHERE DOWNLOAD_DATE = '30-NOV-2018'
    AND ACCOUNT_NUMBER NOT IN (SELECT MASTER_ACCOUNT_CODE FROM IFRS_MASTERID);
    COMMIT;

    MERGE INTO IFRS_MASTER_ACCOUNT_MONTHLY A
        USING ( SELECT DISTINCT PKID,MASTER_ACCOUNT_CODE FROM IFRS_MASTERID) B
        ON (A.DOWNLOAD_DATE = V_CURRDATE AND A.ACCOUNT_NUMBER = B.MASTER_ACCOUNT_CODE)
        WHEN MATCHED THEN
        UPDATE
        SET A.MASTERID = B.PKID;
    COMMIT;

        UPDATE IFRS_DATE_DAY1
        SET CURRDATE = ADD_MONTHS(CURRDATE,1),
            PREVDATE = ADD_MONTHS(PREVDATE,1);
            COMMIT;
    END LOOP;
    END;