CREATE OR REPLACE PROCEDURE USPI_VARIABLE_SELECTION (v_MODEL_ID NUMBER)
AS
BEGIN
    --Move all results from BCA_MacroEconomic.R to permanent table
    DELETE IFRS_ME_DERIVED_VARIABLE
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO IFRS_ME_DERIVED_VARIABLE
    SELECT * FROM IFRS_ME_DERIVED_VARIABLE_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE IFRS_INDEPENDENT_VARIABLE
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO IFRS_INDEPENDENT_VARIABLE
    SELECT * FROM IFRS_INDEPENDENT_VARIABLE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_MODEL_FILTER_DTL
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_MODEL_FILTER_DTL
    SELECT * FROM R_MODEL_FILTER_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_MODEL_FILTER_CORTEST
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_MODEL_FILTER_CORTEST
    SELECT * FROM R_MODEL_FILTER_CORTEST_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_MODEL_FILTER_DTL_FULL
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_MODEL_FILTER_DTL_FULL
    SELECT * FROM R_MODEL_FILTER_DTL_FULL_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_ADF_TEST_DTL
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_ADF_TEST_DTL
    SELECT * FROM R_ADF_TEST_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;


    --Move all results from do_variable_clustering.R to permanent table
    DELETE R_VARCLUS_MASTER
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_VARCLUS_MASTER
    SELECT * FROM R_VARCLUS_MASTER_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_VARCLUS_GRAND_SUMM
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_VARCLUS_GRAND_SUMM
    SELECT * FROM R_VARCLUS_GRAND_SUMM_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_VARCLUS_CLUSTER_SUMM
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_VARCLUS_CLUSTER_SUMM
    SELECT * FROM R_VARCLUS_CLUSTER_SUMM_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_VARCLUS_INTER_CLUST_CORR
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_VARCLUS_INTER_CLUST_CORR
    SELECT * FROM R_VARCLUS_INTER_CLUST_CORR_PEN
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    DELETE R_VARCLUS_CLUSTER_DTL
    WHERE MODEL_ID = v_MODEL_ID;
--    COMMIT;

    INSERT INTO R_VARCLUS_CLUSTER_DTL
    SELECT * FROM R_VARCLUS_CLUSTER_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;
    COMMIT;
END;