CREATE OR REPLACE PROCEDURE USPI_MODEL_SELECTION (v_MODEL_ID NUMBER)
AS
BEGIN
    --Move all results to permanent table from
    --1.run_linear_regression_model.R
    --2.run_ME_In_Sample_Test.R
    --3.run_ME_Out_Of_Sample_Test.R
    --4.PD_FL_Model.R
    --5.PD_FL_Calc_Predicted_PD.R
    --6.PD_FL_Term_Structure_Calc.R

    DELETE R_ME_MODEL_SCENARIO
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_MULT_LINEAR_REGR_RESULT
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_MULT_LINEAR_REGR_COEF
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_LINREG_STATS
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_LINREG_VIF_DTL
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_IN_SMPL_ME_DTL
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_IN_SAMPLE_DTL
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_IN_SAMPLE
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_OUT_SMPL_ME_DTL
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_OUT_SAMPLE_DTL
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_BACKTEST_OUT_SAMPLE
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE IFRS_ME_DERIVED_FORCST_VAR
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_FITTED_ODR
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_SCALING_FACTOR
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_PD_PIT
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_PD_CUMULATIVE
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_PD_TERM_STRUCTURE
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE R_LGD_TERM_STRUCTURE
    WHERE MODEL_ID = v_MODEL_ID;

    DELETE IFRS_PD_TERM_STRUCTURE
    WHERE EFF_DATE = (SELECT DISTINCT EFF_DATE FROM R_PD_TERM_STRUCTURE_PEN WHERE MODEL_ID = v_MODEL_ID)
    AND MODEL_ID = v_MODEL_ID;

    DELETE IFRS_PD_TERM_STRUCTURE
    WHERE EFF_DATE = (SELECT DISTINCT EFF_DATE FROM R_PD_TERM_STRUCTURE_PEN WHERE MODEL_ID = v_MODEL_ID AND PD_RULE_ID = 1)
    AND PD_RULE_ID = 23;

    DELETE IFRS_LGD_TERM_STRUCTURE
    WHERE EFF_DATE = (SELECT DISTINCT EFF_DATE FROM R_LGD_TERM_STRUCTURE_PEN WHERE MODEL_ID = v_MODEL_ID)
    AND LGD_RULE_ID = (SELECT DISTINCT LGD_RULE_ID FROM R_LGD_TERM_STRUCTURE_PEN WHERE MODEL_ID = v_MODEL_ID);

    DELETE IFRS_LGD_TERM_STRUCTURE
    WHERE EFF_DATE = (SELECT DISTINCT EFF_DATE FROM R_LGD_TERM_STRUCTURE_PEN WHERE MODEL_ID = v_MODEL_ID AND LGD_RULE_ID = 2)
    AND LGD_RULE_ID IN (38,39);

    INSERT INTO R_ME_MODEL_SCENARIO
    SELECT * FROM R_ME_MODEL_SCENARIO_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_MULT_LINEAR_REGR_RESULT
    SELECT * FROM R_MULT_LINEAR_REGR_RESULT_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_MULT_LINEAR_REGR_COEF
    SELECT * FROM R_MULT_LINEAR_REGR_COEF_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_LINREG_STATS
    SELECT * FROM R_LINREG_STATS_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_LINREG_VIF_DTL
    SELECT * FROM R_LINREG_VIF_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_IN_SMPL_ME_DTL
    SELECT * FROM R_BACKTEST_IN_SMPL_ME_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_IN_SAMPLE_DTL
    SELECT * FROM R_BACKTEST_IN_SAMPLE_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_IN_SAMPLE
    SELECT * FROM R_BACKTEST_IN_SAMPLE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_OUT_SMPL_ME_DTL
    SELECT * FROM R_BACKTEST_OUT_SMPL_ME_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_OUT_SAMPLE_DTL
    SELECT * FROM R_BACKTEST_OUT_SAMPLE_DTL_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_BACKTEST_OUT_SAMPLE
    SELECT * FROM R_BACKTEST_OUT_SAMPLE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO IFRS_ME_DERIVED_FORCST_VAR
    SELECT * FROM IFRS_ME_DERIVED_FORCST_VAR_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_FITTED_ODR
    SELECT * FROM R_FITTED_ODR_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_SCALING_FACTOR
    SELECT * FROM R_SCALING_FACTOR_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_PD_PIT
    SELECT * FROM R_PD_PIT_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_PD_CUMULATIVE
    SELECT * FROM R_PD_CUMULATIVE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_PD_TERM_STRUCTURE
    SELECT * FROM R_PD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO R_LGD_TERM_STRUCTURE
    SELECT * FROM R_LGD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID;

    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM R_PD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID
    AND MODEL_SEQ = (SELECT SELECTED_MODEL_SEQ FROM IFRS_FL_MODEL_VAR WHERE PKID = v_MODEL_ID)
    ORDER BY FL_YEAR, BUCKET_ID;

    --PD Internal
    INSERT INTO IFRS_PD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        PD_RULE_ID,
        PD_RULE_NAME,
        MODEL_ID,
        BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT
        EFF_DATE,
        BASE_DATE,
        23 PD_RULE_ID,
        'PD BANK - INTERNAL' PD_RULE_NAME,
        0 MODEL_ID,
        'BR9_1' BUCKET_GROUP,
        BUCKET_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        PD,
        PRODUCTION_PD,
        OVERRIDE_PD,
        PRC_FLAG,
        TM_TYPE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM R_PD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID
    AND MODEL_SEQ = (SELECT SELECTED_MODEL_SEQ FROM IFRS_FL_MODEL_VAR WHERE PKID = v_MODEL_ID)
    AND PD_RULE_ID = 1
    UNION ALL
    SELECT EFF_DATE,
    BASE_DATE,
    23 PD_RULE_ID,
    'PD BANK - INTERNAL' PD_RULE_NAME,
    0 MODEL_ID,
    'BR9_1' BUCKET_GROUP,
    12 BUCKET_ID,
    FL_SEQ,
    FL_YEAR,
    FL_MONTH,
    FL_DATE,
    AVG(PD),
    AVG(PRODUCTION_PD),
    AVG(OVERRIDE_PD),
    PRC_FLAG,
    TM_TYPE,
    CREATEDBY,
    CREATEDDATE,
    CREATEDHOST,
    UPDATEDBY,
    UPDATEDDATE,
    UPDATEDHOST
    FROM R_PD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID
    AND MODEL_SEQ = (SELECT SELECTED_MODEL_SEQ FROM IFRS_FL_MODEL_VAR WHERE PKID = v_MODEL_ID)
    AND PD_RULE_ID = 1
    AND BUCKET_ID < 8
    GROUP BY
    EFF_DATE,
    BASE_DATE,
    MODEL_ID,
    FL_SEQ,
    FL_YEAR,
    FL_MONTH,
    FL_DATE,
    PRC_FLAG,
    TM_TYPE,
    CREATEDBY,
    CREATEDDATE,
    CREATEDHOST,
    UPDATEDBY,
    UPDATEDDATE,
    UPDATEDHOST
    ORDER BY FL_YEAR, BUCKET_ID;

    INSERT INTO IFRS_LGD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        LGD_RULE_ID,
        LGD_RULE_NAME,
        --MODEL_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        LGD,
        PRODUCTION_LGD,
        OVERRIDE_LGD,
        PRC_FLAG,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT EFF_DATE,
        ADD_MONTHS(EFF_DATE,-12),
        LGD_RULE_ID,
        LGD_RULE_NAME,
        --MODEL_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        LGD,
        PRODUCTION_LGD,
        OVERRIDE_LGD,
        PRC_FLAG,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM R_LGD_TERM_STRUCTURE_PEN
    WHERE MODEL_ID = v_MODEL_ID
    AND MODEL_SEQ = (SELECT SELECTED_MODEL_SEQ FROM IFRS_FL_MODEL_VAR WHERE PKID = v_MODEL_ID)
    ORDER BY FL_YEAR;

    INSERT INTO IFRS_LGD_TERM_STRUCTURE
    (
        EFF_DATE,
        BASE_DATE,
        LGD_RULE_ID,
        LGD_RULE_NAME,
        --MODEL_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        LGD,
        PRODUCTION_LGD,
        OVERRIDE_LGD,
        PRC_FLAG,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT EFF_DATE,
        ADD_MONTHS(EFF_DATE,-12),
        B.PKID LGD_RULE_ID,
        B.LGD_RULE_NAME,
        --MODEL_ID,
        FL_SEQ,
        FL_YEAR,
        FL_MONTH,
        FL_DATE,
        0.45 LGD,
        0.45 PRODUCTION_LGD,
        0.45 OVERRIDE_LGD,
        PRC_FLAG,
        A.CREATEDBY,
        A.CREATEDDATE,
        A.CREATEDHOST,
        A.UPDATEDBY,
        A.UPDATEDDATE,
        A.UPDATEDHOST
    FROM R_LGD_TERM_STRUCTURE_PEN A
    CROSS JOIN IFRS_LGD_RULES_CONFIG B
    WHERE A.MODEL_ID = v_MODEL_ID
    AND A.MODEL_SEQ = (SELECT SELECTED_MODEL_SEQ FROM IFRS_FL_MODEL_VAR WHERE PKID = v_MODEL_ID)
    AND A.LGD_RULE_ID = 2
    AND B.PKID IN (38,39)
    ORDER BY LGD_RULE_ID, FL_YEAR;

    COMMIT;

    SP_IFRS_INSERT_TERM_STRUCTUREC (v_MODEL_ID);
END;