CREATE OR REPLACE PROCEDURE  USPS_TRMODULENONEIRCURRENT
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_DATE DATE;
    v_MASTERID NUMBER(18);
BEGIN

    v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
    v_MASTERID:= TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));

    OPEN Cur_out FOR
        SELECT DOWNLOAD_DATE AS PERIOD,
            PMTDATE AS PMT_DATE,
            COALESCE (N_AMORT_COST, 0) + COALESCE (N_AMORT_FEE, 0) AS "AMORTIZATION_TOTAL",
            COALESCE (N_UNAMORT_COST, 0) + COALESCE (N_UNAMORT_FEE, 0) AS "UNAMORT_AMT_TOTAL",
            COALESCE (N_AMORT_COST, 0) AS "AMORT_TXN_COST",
            COALESCE (N_AMORT_FEE, 0) AS "AMORT_ORG_FEE",
            COALESCE (N_UNAMORT_FEE, 0) AS "UNAMORT_ORG_FEE",
            COALESCE (N_UNAMORT_COST, 0) AS "UNAMORT_TXN_COST"
        FROM IFRS_ACCT_SL_ECF
        WHERE MASTERID = v_MASTERID
            AND DOWNLOAD_DATE = v_DATE
        ORDER BY DOWNLOAD_DATE DESC,
            PMTDATE ASC;

END;