CREATE OR REPLACE PROCEDURE USPS_BGMODULEEIRHISTORY (
   V_DDATE_MAID VARCHAR2 DEFAULT ' ',
   Cur_out OUT SYS_REFCURSOR
)
AS
   v_DATE DATE;
   v_DATE2 DATE;
   v_MASTERID NUMBER(18);
BEGIN

   v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
   v_MASTERID:= TO_NUMBER(SUBSTR(V_DDATE_MAID,11,INSTR(V_DDATE_MAID,'*',1)-11));

   SELECT MAX (DOWNLOAD_DATE) INTO v_DATE2
   FROM IFRS_ACCT_EIR_ECF
   WHERE MASTERID = v_MASTERID AND DOWNLOAD_DATE <= v_DATE;

   IF(v_DATE2 IS NULL) THEN
    v_DATE2 := '01-JAN-1900';
   END IF;


    OPEN Cur_out FOR
    SELECT PMT_DATE AS "PERIOD",
            DOWNLOAD_DATE,
            COALESCE (N_PRN_PAYMENT, 0) AS "PRINCIPAL",
            COALESCE (N_INT_PAYMENT, 0) AS "INTEREST",
            COALESCE (N_OSPRN, 0) AS "OUTSTANDING",
            COALESCE (N_INT_RATE, 0) AS "INT_RATE",
            COALESCE (N_EFF_INT_RATE, 0) AS "EFF_INT_RATE",
            COALESCE (N_EFF_INT_AMT, 0) AS "EIR_AMOUNT",
            COALESCE (N_AMORT_AMT, 0) AS "AMORT_AMT_TOTAL",
            COALESCE (N_UNAMORT_AMT, 0) AS "UNAMORT_AMT_TOTAL",
            COALESCE (N_FAIRVALUE, 0) AS "CARR_AMT",
            COALESCE (N_COST_AMORT_AMT, 0) AS "AMORT_TXN_COST",
            COALESCE (N_FEE_AMORT_AMT, 0) AS "AMORT_ORG_FEE",
            COALESCE (N_FEE_UNAMORT_AMT, 0) AS "UNAMORT_ORG_FEE",
            COALESCE (N_COST_UNAMORT_AMT, 0) AS "UNAMORT_TXN_COST",
            CASE
                WHEN NOCF_OSPRN IS NOT NULL THEN COALESCE (NOCF_OSPRN, 0)
                ELSE COALESCE (N_OSPRN, 0)
            END
                AS "NOCF_OSPRN",
            CASE
                WHEN NOCF_PRN_PAYMENT IS NOT NULL
                THEN
                    COALESCE (NOCF_PRN_PAYMENT, 0)
                    - COALESCE (NOCF_EFF_INT_AMT, 0)
                ELSE
                    COALESCE (N_PRN_PAYMENT, 0)
            END
                AS "NOCF_PRN_PAYMENT",
            CASE
                WHEN NOCF_INT_RATE IS NOT NULL
                THEN
                    COALESCE (NOCF_INT_RATE, 0)
                ELSE
                    COALESCE (N_INT_RATE, 0)
            END
                AS "NOCF_INT_RATE",
            COALESCE (NOCF_AMORT_AMT, 0) AS "NOCF_AMORT_AMT",
            CASE
                WHEN NOCF_EFF_INT_AMT IS NOT NULL
                THEN
                    COALESCE (NOCF_EFF_INT_AMT, 0)
                ELSE
                    COALESCE (N_INT_PAYMENT, 0)
            END
                AS "NOCF_EFF_INT_AMT"
        FROM IFRS_ACCT_EIR_ECF
        WHERE MASTERID = v_MASTERID AND DOWNLOAD_DATE < v_DATE2
    ORDER BY DOWNLOAD_DATE, PMT_DATE ASC;
END;