CREATE OR REPLACE PROCEDURE USPS_UPLOADPENDINGAPPROVAL
(
    v_userID IN VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN Cur_out FOR
    SELECT A.PKID UPLOADID,
        MAPPINGNAME,
        U.FULLNAME UploadedBy,
        A.CREATEDDATE UploadedDate
    FROM TBLT_UPLOAD_POOL A
        JOIN TBLM_MAPPINGRULEHEADER_NEW B ON A.MAPPINGID = B.PKID
        LEFT JOIN TBLM_REPORTTO R ON A.CREATEDBY = R.USERID
        LEFT JOIN TBLM_USER U ON A.CREATEDBY = U.USERID
    WHERE NVL(REPORTTO, A.CREATEDBY) = v_userID
        AND STATUS = 'PENDING'
    ORDER BY UploadedDate DESC;

END;