CREATE OR REPLACE PROCEDURE USPS_ECL_MODEL_SUMMARY
(
      V_ECL_MODEL_ID number default 0,
      V_ECL_PERIOD DATE default '1900-01-01',
      Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN Cur_out FOR

    SELECT (A.SUB_SEGMENT || '|' ||  A.BUCKET_ID || '|' ||  A.CR_STAGE || '|' || A.PF_SEGMENT_ID) AS PKID,
    A.CR_STAGE, A.DOWNLOAD_DATE, B.ECL_MODEL_NAME, A.SUB_SEGMENT, A.BUCKET_ID,
    NVL(C.BUCKET_NAME, 'BR12') BUCKET_NAME, SUM(A.OUTSTANDING) AS OUTSTANDING,
    SUM(A.ECL_AMOUNT_FINAL) AS ECL_AMOUNT
    FROM ifrs_ecl_result_header A
    JOIN ifrs_ecl_model_header B
    ON A.ECL_MODEL_ID = B.PKID
    LEFT JOIN ifrs_bucket_detail C
    ON A.BUCKET_ID = C.BUCKET_ID
    AND A.BUCKET_GROUP = C.BUCKET_GROUP
    WHERE A.ECL_MODEL_ID = V_ECL_MODEL_ID
    AND A.DOWNLOAD_DATE = V_ECL_PERIOD
    GROUP BY A.CR_STAGE, A.DOWNLOAD_DATE, B.ECL_MODEL_NAME,
    A.SUB_SEGMENT, A.BUCKET_ID, C.BUCKET_NAME,
    (A.SUB_SEGMENT || '|' ||  A.BUCKET_ID || '|' ||  A.CR_STAGE || '|' || A.PF_SEGMENT_ID)
    ORDER BY A.SUB_SEGMENT, A.BUCKET_ID, A.CR_STAGE;

END;