CREATE OR REPLACE PROCEDURE USPS_LIST_ECL_MULTIPLIER
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
     SELECT D.PKID, CASE WHEN C.EFFECTIVE_DATE IS NULL THEN LAST_DAY(SYSDATE) ELSE C.EFFECTIVE_DATE END AS "EFFECTIVE_DATE", C.DATA_SOURCE, D.SUB_SEGMENT, CASE WHEN C.MULTIPLIER IS NULL THEN 1 ELSE C.MULTIPLIER END "MULTIPLIER",
    CASE WHEN C.REMARKS IS NULL THEN '' ELSE C.REMARKS END AS "REMARKS", C.CREATEDDATE, D.PKID AS "PKID_SEGMENT"
   FROM(
    SELECT A.PKID, A.EFFECTIVE_DATE, A.DATA_SOURCE, A.SUB_SEGMENT, A.RULE_ID, A.MULTIPLIER, A.REMARKS, A.CREATEDDATE FROM IFRS_ECL_MULTIPLIER A JOIN (
   SELECT MAX(SUB_SEGMENT), MAX(CREATEDDATE), MAX(PKID) AS PKID FROM IFRS_ECL_MULTIPLIER GROUP BY SUB_SEGMENT)B
   ON A.PKID = B.PKID) C RIGHT JOIN IFRS_MSTR_SEGMENT_RULES_HEADER D
   ON C.RULE_ID = D.PKID AND C.SUB_SEGMENT = D.SUB_SEGMENT AND D.SEGMENT_TYPE = 'PORTFOLIO_SEG'
   WHERE D.SEGMENT_TYPE = 'PORTFOLIO_SEG' AND D.IS_DELETED = 0 ORDER BY C.CREATEDDATE ASC;

END;