CREATE OR REPLACE PROCEDURE USPS_ECL_LGD_TERM_STRUCTURE
(
    V_ECL_PERIOD DATE DEFAULT '1900-01-01',
    V_BUCKET_ID NUMBER DEFAULT 0,
    V_ECL_MODEL_ID NUMBER DEFAULT 0,
    V_PF_SEGMENT_ID NUMBER DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT DISTINCT C.LGD_MODEL_ID, A.FL_YEAR, ROUND(A.OVERRIDE_LGD, 6) AS OVERRIDE_LGD
    FROM IFRS_ECL_MODEL_CONFIG C
    JOIN IFRS_ECL_RESULT_HEADER B
    ON C.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    AND B.ECL_MODEL_ID = C.ECL_MODEL_ID
    AND B.PF_SEGMENT_ID = C.PF_SEGMENT_ID
    JOIN IFRS_LGD_TERM_STRUCTURE A
    ON A.LGD_RULE_ID = C.LGD_MODEL_ID
    AND A.EFF_DATE = C.PD_EFF_DATE
    WHERE C.ECL_MODEL_ID = V_ECL_MODEL_ID
    AND C.DOWNLOAD_DATE = V_ECL_PERIOD
    AND C.PF_SEGMENT_ID = V_PF_SEGMENT_ID
    ORDER BY C.LGD_MODEL_ID, A.FL_YEAR;

END;