CREATE OR REPLACE PROCEDURE USPS_CCF_MODEL_STATISTICS
(
    V_CCF_MODEL_ID NUMBER DEFAULT 0,
    V_CCF_PERIOD DATE DEFAULT '1900-01-01',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT DISTINCT(A.CCF_RULE_ID || '_' || B.FACILITY_NUMBER) AS PKID,
    A.DOWNLOAD_DATE, B.FACILITY_NUMBER,
    B.CUSTOMER_NUMBER, B.CUSTOMER_NAME,
    A.SEGMENTATION, B.FIRST_NPL_DATE,
    B.OS_PREV, B.CCF_RESULT, B.CURRENCY,
    SUM(B.OS_CUR) AS OUTSTANDING, B.LIMIT_CUR
    FROM IFRS_CCF_HEADER A
    JOIN IFRS_CCF_DETAIL_PROCESS B
    ON B.SEGMENTATION_ID = A.SEGMENTATION_ID
    WHERE A.DOWNLOAD_DATE = V_CCF_PERIOD
    AND B.FIRST_NPL_DATE <= V_CCF_PERIOD
    AND A.CCF_RULE_ID = V_CCF_MODEL_ID
    GROUP BY (A.CCF_RULE_ID || '_' || B.FACILITY_NUMBER),
    A.DOWNLOAD_DATE, B.FACILITY_NUMBER,
    B.LIMIT_CUR, B.CUSTOMER_NUMBER, B.CUSTOMER_NAME,
    A.SEGMENTATION, B.FIRST_NPL_DATE,
    B.OS_PREV, B.CCF_RESULT, B.CURRENCY
    ORDER BY A.DOWNLOAD_DATE DESC;

END;