CREATE OR REPLACE PROCEDURE USPS_ECL_ASSET(CUR_OUT OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN CUR_OUT FOR
    SELECT *
      FROM (SELECT A.ASET_KEUANGAN AS CODE,
                   A.ASET_KEUANGAN AS DESCRIPTION
          FROM (SELECT DISTINCT ASET_KEUANGAN
              FROM IFRS_MOVE_MAP_SEGMENT_ASETUANG
              WHERE ASET_KEUANGAN IS NOT NULL) A

          UNION
        SELECT A.TRA AS CODE,
               A.TRA || ' (TRA)' AS DESCRIPTION
          FROM (SELECT DISTINCT TRA
              FROM IFRS_MOVE_MAP_SEGMENT_ASETUANG
              WHERE TRA IS NOT NULL) A) B
      ORDER BY B.CODE;
  END;