CREATE OR REPLACE PROCEDURE USPS_PD_CMB_FL_MODEL (
    v_pd_rule_id number,
    v_eff_date date,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN Cur_out FOR

    SELECT DISTINCT D.FL_MODEL_NAME AS "Description" , E.MODEL_ID || '_' || D.SELECTED_MODEL_SEQ AS "Code"
    FROM  IFRS_FL_MODEL_VAR D
    JOIN (SELECT DISTINCT * FROM IFRS_PD_TERM_STRUCTURE) E
    ON E.PD_RULE_ID = D.DEPENDENT_VAR_VALUE
    AND D.DEPENDENT_VAR_TYPE = 'PD'
    AND E.MODEL_ID = D.PKID
    WHERE D.DEPENDENT_VAR_VALUE = TO_CHAR(v_pd_rule_id)
    AND E.EFF_DATE = TO_CHAR(v_eff_date,'dd MON yyyy')
    AND D.STATUS = 1; /*APPROVED*/

END;