CREATE OR REPLACE PROCEDURE  uspS_ApprovalPendUserID
(
    V_USERID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN Cur_out FOR
    SELECT
    A.STATUS,
    A.createdby,
    B.USERNAME,
    R.REPORTTO As APPROVER--,C.USERNAME as Approver
   FROM TBLT_APPROVALHEADER A
 INNER JOIN TBLM_USER B
    ON A.createdby=B.USERID
 INNER JOIN TBLM_REPORTTO R
    on R.USERID=B.USERID
 INNER JOIN tblm_user C
  on R.USERID=C.USERID --and A.createdby=R.USERID
 WHERE A.STATUS NOT IN ('A','R') AND A.STATUS IN ('P') AND R.REPORTTO=V_USERID;

 END;