CREATE OR REPLACE PROCEDURE uspS_LookupSegidLT
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT PKID AS "SEGMENTATION_ID",
            SUB_SEGMENT AS "Segment"
        FROM IFRS_MSTR_SEGMENT_RULES_HEADER
        WHERE SEGMENT_TYPE = UPPER (LTRIM (RTRIM('LIFETIME_SEG')))
        ORDER BY SEGMENT;

END;