CREATE OR REPLACE PROCEDURE USPS_ECL_MODEL_DETAILS
(
    V_ECL_SEGMENT VARCHAR DEFAULT 'SEGMENT',
    V_ECL_BUCKET_ID NUMBER DEFAULT 0,
    V_ECL_STAGE NUMBER DEFAULT 0,
    V_ECL_PERIOD DATE DEFAULT '1900-01-01',
    V_ECL_MODEL_ID NUMBER DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT A.MASTERID,
    A.DOWNLOAD_DATE,
    A.ACCOUNT_NUMBER,
    A.CUSTOMER_NUMBER,
    A.CUSTOMER_NAME,
    A.PRODUCT_CODE || ' - ' || C.PRD_DESC AS PRODUCT_CODE,
    A.CR_STAGE,
    A.INTEREST_RATE,
    NVL(ROUND(A.EIR,28), A.INTEREST_RATE) AS EIR,
    A.CURRENCY,
    A.OUTSTANDING,
    A.ECL_AMOUNT_FINAL AS ECL_AMOUNT,
    D.EAD_AMOUNT
    FROM IFRS_ECL_RESULT_DETAIL A
    LEFT JOIN IFRS_MASTER_PRODUCT_PARAM C
    ON NVL(A.DATA_SOURCE, ' ') = NVL(C.DATA_SOURCE, ' ')
    AND NVL(A.PRODUCT_CODE, ' ') = NVL(C.PRD_CODE, ' ')
    LEFT JOIN IFRS_ECL_RESULT_DETAIL_CALC  D
    ON A.ECL_MODEL_ID = D.ECL_MODEL_ID
    AND A.DOWNLOAD_DATE = D.DOWNLOAD_DATE
    AND A.MASTERID = D.MASTERID
    AND D.COUNTER_PAYSCHD = 1
    WHERE A.DOWNLOAD_DATE = V_ECL_PERIOD
    AND A.ECL_MODEL_ID = V_ECL_MODEL_ID
    AND A.SUB_SEGMENT = V_ECL_SEGMENT
    AND A.BUCKET_ID = V_ECL_BUCKET_ID
    AND A.CR_STAGE = V_ECL_STAGE;

END;