CREATE OR REPLACE PROCEDURE USPS_WORSTCASE_HEADER
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT DISTINCT
            MAX(DOWNLOAD_DATE) AS DOWNLOAD_DATE,
            CUSTOMER_NUMBER,
            ROUND(PERCENTAGE, 6) PERCENTAGE,
            MAX(UPLOADDATE) AS UPLOADDATE
        FROM TBLU_WORSTCASE_LIST
        GROUP BY
            CUSTOMER_NUMBER,
            PERCENTAGE
        ORDER BY UPLOADDATE DESC,
            CUSTOMER_NUMBER;

END;