CREATE OR REPLACE PROCEDURE USPS_ECL_PD_TERM_STRUCTURE
(
    V_ECL_PERIOD DATE DEFAULT '1900-01-01',
    V_BUCKET_ID NUMBER DEFAULT 0,
    V_ECL_MODEL_ID NUMBER DEFAULT 0,
    V_PF_SEGMENT_ID NUMBER DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT DISTINCT A.FL_YEAR, ROUND(A.OVERRIDE_PD, 6) AS OVERRIDE_PD, A.BUCKET_ID
    FROM IFRS_ECL_MODEL_CONFIG C
    JOIN IFRS_ECL_RESULT_HEADER B
    ON C.DOWNLOAD_DATE = B.DOWNLOAD_DATE
    AND B.ECL_MODEL_ID = C.ECL_MODEL_ID
    AND B.PF_SEGMENT_ID = C.PF_SEGMENT_ID
    JOIN IFRS_PD_TERM_STRUCTURE A
    ON A.PD_RULE_ID = C.PD_MODEL_ID
    AND A.EFF_DATE = C.PD_EFF_DATE
    WHERE A.BUCKET_ID = V_BUCKET_ID
    AND B.ECL_MODEL_ID = V_ECL_MODEL_ID
    AND C.DOWNLOAD_DATE = V_ECL_PERIOD
    AND C.PF_SEGMENT_ID = V_PF_SEGMENT_ID
    AND A.TM_TYPE = 'YEAR';

END;