CREATE OR REPLACE PROCEDURE USPS_TRMODULECOLLIMPAIR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_DATE DATE;
    v_MASTERID NUMBER(18);
BEGIN

    v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
    v_MASTERID := TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));

    OPEN Cur_out FOR
        SELECT DOWNLOAD_DATE AS "PERIOD",
            ACCOUNT_NUMBER,
            CURRENCY,
            'C' AS "IMPAIRMENT_FLAG",
            DAY_PAST_DUE AS "DPD",
            BI_COLLECTABILITY,
            CR_STAGE,
            EAD_AMOUNT,
            ECL_AMOUNT,
            CA_UNWINDING_AMOUNT,
            COALESCE(BEGINNING_BALANCE, 0) AS "BEGIN_BALANCE",
            COALESCE(CHARGE_AMOUNT, 0) AS "CHARGE",
            COALESCE(WRITEBACK_AMOUNT, 0) AS "WRITEBACK",
            COALESCE(ENDING_BALANCE, 0) AS "ENDING_BALANCE"
        FROM IFRS_MASTER_ACCOUNT_MONTHLY A
        WHERE IMPAIRED_FLAG = 'C' AND IS_IMPAIRED = 1
            AND MASTERID = v_MASTERID
            AND DOWNLOAD_DATE <= v_DATE
        ORDER BY PERIOD,
            MASTERID,
            IMPAIRMENT_FLAG,
            DPD,
            BI_COLLECTABILITY;

END;