CREATE OR REPLACE PROCEDURE USPS_TRMODULEINDVIMPAIR
(
   V_DDATE_MAID VARCHAR2 DEFAULT ' ',
   Cur_out OUT SYS_REFCURSOR
)
AS
    v_DATE DATE;
    v_MASTERID NUMBER(18);
BEGIN

    v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
    v_MASTERID := TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));

    OPEN Cur_out FOR
        SELECT A.DOWNLOAD_DATE AS "PERIOD",
            A.ACCOUNT_NUMBER AS "ACCOUNT_NUMBER",
            A.CURRENCY AS CURRENCY,
            'I' AS "IMPAIR_FLAG" ,
            A.BI_COLLECTABILITY AS "BI_COLLECTABILITY",
            CASE WHEN C.DISCOUNT_RATE <> 0 THEN
                ROUND (C.DISCOUNT_RATE, 6)
            WHEN C.EIR <> 0 THEN
                ROUND (C.EIR, 6)
            WHEN C.INTEREST_RATE <> 0 THEN
                ROUND (C.INTEREST_RATE, 6)
            END AS "INTEREST_RATE",
            COALESCE (A.EAD_AMOUNT, 0) AS "EAD_AMOUNT",
            COALESCE (C.ESTIMATED_AMOUNT, 0) AS "TOTAL_ESTIMATED_CASHFLOW",
            COALESCE (B.PV_AMOUNT, 0) AS "PV_ESTIMATED_CASHFLOW",
            COALESCE (A.ECL_AMOUNT, 0) AS "INDIVIDUAL_PROVISION",
            COALESCE (BEGINNING_BALANCE, 0) AS "BEGINNING_BALANCE",
            COALESCE (CHARGE_AMOUNT, 0) AS "CHARGE",
            COALESCE (WRITEBACK_AMOUNT, 0) AS "WRITEBACK",
            COALESCE (ENDING_BALANCE, 0) AS "ENDING_BALANCE"
        FROM IFRS_MASTER_ACCOUNT_MONTHLY A
            JOIN IFRS_IA_OVERRIDEH B ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
            JOIN
            (
                SELECT OVERRIDEID,
                    SUM (ESTIMATED_AMOUNT) AS ESTIMATED_AMOUNT,
                    MAX (DISCOUNT_RATE) AS DISCOUNT_RATE,
                    MAX (EIR) AS EIR,
                    MAX (INTEREST_RATE) AS INTEREST_RATE
                FROM TBLT_PAYMENTEXPECTED
                GROUP BY OVERRIDEID
            ) C ON B.PKID = C.OVERRIDEID
        WHERE A.MASTERID = v_MASTERID
            AND A.DOWNLOAD_DATE <= v_DATE;

END;