CREATE OR REPLACE PROCEDURE  USPS_FUNDMODULETOTALTRANS
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_DATE DATE;
    v_MASTERID NUMBER(18);
BEGIN

    v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
    v_MASTERID := TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));

    OPEN Cur_out FOR
        SELECT ABS(AMOUNT_FEE + AMORT_FEE) UNAMORT_FEE  ,
            ABS(AMORT_FEE) AMORT_FEE  ,
            ABS(AMOUNT_COST + AMORT_COST) UNAMORT_COST  ,
            ABS(AMORT_COST) AMORT_COST
        FROM IFRS_LI_ACCT_COST_FEE_SUMM
        WHERE MASTERID = v_MASTERID
            AND DOWNLOAD_DATE = v_DATE;

END;