CREATE OR REPLACE PROCEDURE  USPS_LGD_CHART_TERM_STRUCTURE
(
    V_PERIOD DATE DEFAULT '1900-01-01',
    V_ModelId NUMBER DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT A.FL_DATE, ROUND(A.OVERRIDE_LGD, 6) AS OVERRIDE_LGD, 'LGD' AS BUCKET_ID
    FROM IFRS_LGD_TERM_STRUCTURE A
--    JOIN IFRS_LGD_RULES_CONFIG B
--  ON A.LGD_RULE_ID = B.PKID
    WHERE A.LGD_RULE_ID=V_ModelId
    AND A.EFF_DATE=V_PERIOD;


END;