CREATE OR REPLACE PROCEDURE USPS_CCF_MODEL_SUMMARY
(
    V_CCF_MODEL_ID NUMBER DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
--Perbaikan 8 Oktober 2025 - Menu Impairment Report, CCF Analysis *100
    OPEN Cur_out FOR
        SELECT  DISTINCT(A.CCF_RULE_ID || '_' || A.DOWNLOAD_DATE) AS PKID,
            A.DOWNLOAD_DATE,
            C.CCF_RULE_NAME,
            A.SEGMENTATION,
            ROUND(A.CCF_RATE, 28)*100 AS CCF_RATE,
            COUNT(DISTINCT B.ACCOUNT_NUMBER) AS TOTAL_ACCOUNT,
            COUNT(DISTINCT B.FACILITY_NUMBER) AS TOTAL_FACILITY,
            SUM(NVL(B.OS_CUR,0)) AS OUTSTANDING
        FROM IFRS_CCF_HEADER A
            LEFT JOIN IFRS_CCF_DETAIL B ON B.SEGMENTATION_ID = A.SEGMENTATION_ID
            JOIN IFRS_CCF_RULES_CONFIG C ON C.PKID = A.CCF_RULE_ID
        WHERE A.CCF_RULE_ID = V_CCF_MODEL_ID
        GROUP BY A.DOWNLOAD_DATE,
            C.CCF_RULE_NAME,
            A.SEGMENTATION,
            A.CCF_RATE,
            (A.CCF_RULE_ID || '_' || A.DOWNLOAD_DATE);


END;