CREATE OR REPLACE PROCEDURE USPS_LOANMODULEJOURNALIMPAIR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
    SELECT DOWNLOAD_DATE AS "Download Date",
           ACCOUNT_NUMBER AS "Account Number",
           GL_ACCOUNT AS "GL Account",
           JOURNAL_TYPE AS "Journal Type",
           JOURNAL_DESC AS "Description",
           CURRENCY AS "Currency",
           TXN_TYPE AS "DB/CR Flag",
           AMOUNT AS "Original Amount",
           REVERSAL_FLAG AS "Reversal Flag"
        FROM IFRS_IMP_JOURNAL_DATA
        WHERE ACCOUNT_NUMBER = SUBSTR(V_DDATE_MAID,18,LENGTH(RTRIM(V_DDATE_MAID)))
        AND DOWNLOAD_DATE <= TO_CHAR(SUBSTR(V_DDATE_MAID, 1, 10), 111)
    ORDER BY  DOWNLOAD_DATE DESC, REVERSAL_FLAG DESC, AMOUNT DESC, CURRENCY ASC, JOURNAL_TYPE DESC, TXN_TYPE DESC;

END;