CREATE OR REPLACE PROCEDURE USPS_WORSTCASE_DETAIL
(
    v_CUSTOMER_NUMBER IN VARCHAR2,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT
            DOWNLOAD_DATE,
            CUSTOMER_NUMBER,
            ROUND(PERCENTAGE, 6) PERCENTAGE,
            UPLOADDATE
        FROM TBLU_WORSTCASE_LIST
        WHERE CUSTOMER_NUMBER = v_CUSTOMER_NUMBER
        GROUP BY
            DOWNLOAD_DATE,
            CUSTOMER_NUMBER,
            PERCENTAGE,
            UPLOADDATE
        ORDER BY UPLOADDATE DESC,
            CUSTOMER_NUMBER;

END;