CREATE OR REPLACE PROCEDURE USPS_STAGE_MASTER
(
    V_VALUE VARCHAR2 DEFAULT ' ',
    V_DOWNLOAD_DATE DATE  DEFAULT '01-JAN-1900',
    V_FIELD VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
        IF(V_FIELD = 'detail') THEN
                 OPEN  Cur_out FOR
                 SELECT ACCOUNT_NUMBER, CR_STAGE, CUSTOMER_NAME, CUSTOMER_NUMBER, BUCKET_ID, FACILITY_NUMBER,DATA_SOURCE, DAY_PAST_DUE, BI_COLLECTABILITY FROM IFRS_MASTER_ACCOUNT
                 WHERE CUSTOMER_NUMBER = V_VALUE AND DOWNLOAD_DATE = V_DOWNLOAD_DATE;
        ELSIF(V_FIELD = 'Customer Number') THEN
                 OPEN  Cur_out FOR
                 SELECT CUSTOMER_NUMBER, CUSTOMER_NAME, CR_STAGE, BUCKET_ID, FACILITY_NUMBER, DATA_SOURCE, DAY_PAST_DUE, BI_COLLECTABILITY FROM IFRS_MASTER_ACCOUNT
                 WHERE CUSTOMER_NUMBER LIKE '%' || V_VALUE ||'%' AND DOWNLOAD_DATE = V_DOWNLOAD_DATE  AND (ACCOUNT_STATUS IS NULL OR ACCOUNT_STATUS != 'C');
        ELSE
                 OPEN  Cur_out FOR
                 SELECT CUSTOMER_NUMBER, CUSTOMER_NAME, CR_STAGE, BUCKET_ID, FACILITY_NUMBER, DATA_SOURCE, DAY_PAST_DUE, BI_COLLECTABILITY FROM IFRS_MASTER_ACCOUNT
                 WHERE CUSTOMER_NAME LIKE '%' || V_VALUE ||'%' AND DOWNLOAD_DATE = V_DOWNLOAD_DATE  AND (ACCOUNT_STATUS IS NULL OR ACCOUNT_STATUS != 'C');
        END IF;
END;