CREATE OR REPLACE PROCEDURE USPS_DBR_EIR_IFRS9_DTLONE (
    v_DownloadDate  VARCHAR2 DEFAULT ' ',
    v_AmortMethod   VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
   OPEN Cur_out FOR
        SELECT DISTINCT PRODUCT_CODE,
            SUM (INITIAL_FEE_CCY)  AS "INITIAL_FEE",
            SUM (INITIAL_COST_CCY) AS "INITIAL_COST",
            SUM (UNAMORT_FEE_AMT_CCY)  AS "UNAMORT_FEE",
            SUM (UNAMORT_COST_AMT_CCY) AS "UNAMORT_COST",
            SUM (AMORT_FEE_CCY)    AS "AMORT_FEE",
            SUM (AMORT_COST_CCY)   AS "AMORT_COST",
            SUM (AMORT_FEE_MTD_CCY) AS "MTD_AMORT_FEE",
            SUM (AMORT_COST_MTD_CCY) AS "MTD_AMORT_COST",
            SUM (AMORT_FEE_YTD_CCY) AS "YTD_AMORT_FEE",
            SUM (AMORT_COST_YTD_CCY) AS "YTD_AMORT_COST"
        FROM IFRS_NOMINATIVE A
        JOIN IFRS_MASTER_PRODUCT_PARAM B
            ON A.PRODUCT_CODE = B.PRD_CODE
            AND A.DATA_SOURCE = B.DATA_SOURCE
        WHERE DOWNLOAD_DATE = TO_DATE (v_DownloadDate, 'dd-MON-yyyy' )
            AND UPPER(A.AMORT_TYPE) = UPPER(V_AmortMethod)
        GROUP BY PRODUCT_CODE
        HAVING SUM (INITIAL_FEE_CCY) <> 0 --AND SUM(INITIAL_COST) <> 0
            OR SUM (INITIAL_COST_CCY) <> 0
        ORDER BY PRODUCT_CODE;
END;