CREATE OR REPLACE PROCEDURE  USPS_APPLICATIONLOGBYJOBID
(
    v_JobId IN NUMBER,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN  Cur_out FOR
    SELECT THREADID,JOBID
    FROM TBLT_APPLICATIONLOG
    WHERE JOBID = v_JobId;

END;