CREATE OR REPLACE PROCEDURE  USPS_R_PD_TERM_STRUCT_CHART
(
    v_MODEL_ID NUMBER,
    v_MODEL_SEQ NUMBER,
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_status NUMBER(10);
BEGIN
    SELECT STATUS
    INTO v_status
    FROM IFRS_FL_MODEL_VAR
    WHERE PKID = v_MODEL_ID;

    IF v_status = 1 THEN
        OPEN Cur_out FOR
        SELECT 'Y' || FL_YEAR AS FL_YEAR, ROUND(OVERRIDE_PD *100, 6) AS MPD, C.BUCKET_NAME
            FROM R_PD_TERM_STRUCTURE A
            INNER JOIN IFRS_BUCKET_HEADER B
            ON A.BUCKET_GROUP = B.BUCKET_GROUP
            INNER JOIN IFRS_BUCKET_DETAIL C
            ON B.PKID = C.BUCKET_HEADER_ID
            AND A.BUCKET_ID = C.BUCKET_ID
            WHERE MODEL_ID = v_MODEL_ID
            AND MODEL_SEQ = v_MODEL_SEQ
            ORDER BY FL_YEAR, C.BUCKET_ID;
    ELSE
        OPEN Cur_out FOR
        SELECT 'Y' || FL_YEAR AS FL_YEAR, ROUND(OVERRIDE_PD * 100, 6) AS MPD, C.BUCKET_NAME
            FROM R_PD_TERM_STRUCTURE_PEN A
            INNER JOIN IFRS_BUCKET_HEADER B
            ON A.BUCKET_GROUP = B.BUCKET_GROUP
            INNER JOIN IFRS_BUCKET_DETAIL C
            ON B.PKID = C.BUCKET_HEADER_ID
            AND A.BUCKET_ID = C.BUCKET_ID
            WHERE MODEL_ID = v_MODEL_ID
            AND MODEL_SEQ = v_MODEL_SEQ
            ORDER BY FL_YEAR, C.BUCKET_ID;
    END IF;

END;