CREATE OR REPLACE PROCEDURE  USPS_LIFETIME_CMB_MODEL
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        select PKID, LIFETIME_RULE_NAME
        from IFRS_LIFETIME_RULES_CONFIG;

END;