CREATE OR REPLACE PROCEDURE USPS_LOOKUPMACROSOURCE
(
    Cur_out      OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT 'UPLOAD' AS ME_SOURCE, 'Upload' AS "Source Data" FROM DUAL
        ORDER BY ME_SOURCE DESC;

END;