CREATE OR REPLACE PROCEDURE  USPS_BRMODULEINITIALCOST
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
	Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
    SELECT ACCTNO,
        CASE WHEN FLAG_REVERSE = 'Y' THEN
            ABS (AMOUNT) * - 1
        ELSE
            ABS (AMOUNT)
        END AS AMOUNT_COST,
        IACF.CCY,
        DOWNLOAD_DATE,
        IACF.TRX_CODE,
		--TRANSACTION_TYPE,
		TRANSACTION_DESC
    FROM IFRS_ACCT_COST_FEE IACF
		JOIN IFRS_MASTER_TRANSACTION_PARAM ITP ON IACF.TRX_CODE = ITP.TRX_CODE
    WHERE FLAG_CF = 'C'
        AND STATUS IN ('PRO', 'PNL', 'ACT')
        AND SRCPROCESS = 'TRAN_DAILY'
        AND MASTERID = TO_NUMBER(SUBSTR (V_DDATE_MAID, 11, LENGTH(RTRIM (V_DDATE_MAID))))
        AND DOWNLOAD_DATE <= TO_DATE (SUBSTR (V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');

END;