CREATE OR REPLACE PROCEDURE  uspS_LookupSegmentationidL
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT PKID AS "SEGMENTATION_ID",SEGMENT AS "Segment" from IFRS_MSTR_SEGMENT_RULES_HEADER --where SEGMENT_TYPE = 'CCF_SEGMENT'
        ORDER BY SEGMENT;

END;