CREATE OR REPLACE PROCEDURE  USPS_TFMODULECONTRACTATTR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT NVL(TO_CHAR (IMA.DOWNLOAD_DATE, 'dd-MON-yyyy'), '-') DOWNLOAD_DATE,
            MASTERID,
            IMA.AMORT_TYPE,
            BTB_FLAG,
            MARKET_RATE,
            TC2.DESCRIPTION AS INTEREST_CALCULATION_CODE,
            BELOW_MARKET_FLAG,
            IMA.DATA_SOURCE,
            CUSTOMER_NUMBER,
            CUSTOMER_NAME,
            FACILITY_NUMBER,
            ACCOUNT_NUMBER,
            PREVIOUS_ACCOUNT_NUMBER,
            NVL(ACCOUNT_STATUS, '') || ' - ' || TC.DESCRIPTION AS ACCOUNT_STATUS,
            INTEREST_RATE,
            INTEREST_ACCRUED,
            PRODUCT_GROUP,
            DAY_PAST_DUE,
            POCI_FLAG,
            REMAINING_TENOR,
            JF_FLAG,
            IMPAIRED_FLAG,
            RESTRUCTURE_FLAG,
            REVOLVING_FLAG,
            TENOR,
            NVL(RESERVED_VARCHAR_10,'') AS RESERVED_VARCHAR_10,
            PRODUCT_TYPE,
            PRODUCT_CODE,
            P.PRD_DESC,
            B.BRANCH_NAME,
            IMA.BRANCH_CODE,
            NVL(IMA.RESERVED_VARCHAR_11,'') AS RESERVED_VARCHAR_11,
            NVL(IMA.RESERVED_VARCHAR_2,'') || ' - ' || TC1.DESCRIPTION  as RESERVED_VARCHAR_2,
            NVL(IMA.RESERVED_VARCHAR_3,'') AS RESERVED_VARCHAR_3,
            NVL(IMA.RESERVED_VARCHAR_12,'') AS RESERVED_VARCHAR_12,
            CURRENCY,
            EXCHANGE_RATE,
            PRODUCT_ENTITY,
            STAFF_LOAN_FLAG,
            NVL(OUTSTANDING,0) AS OUTSTANDING,
            NVL(OUTSTANDING_WO,0) AS OUTSTANDING_WO,
            NVL(PLAFOND,0) AS PLAFOND,
            NVL(PLAFOND_CASH,0) AS PLAFOND_CASH,
            NVL(TO_CHAR (IMA.NEXT_INT_PAYMENT_DATE, 'dd-MON-yyyy'), '-') NEXT_INT_PAYMENT_DATE,
            NVL(TO_CHAR (IMA.LOAN_START_DATE, 'dd-MON-yyyy'), '-') LOAN_START_DATE,
            NVL(TO_CHAR (IMA.LOAN_DUE_DATE, 'dd-MON-yyyy'), '-') LOAN_DUE_DATE,
            NVL(TO_CHAR (IMA.LOAN_START_DATE, 'dd-MON-yyyy'), '-') LOAN_START_DATE,
            NVL(TO_CHAR (IMA.NEXT_PAYMENT_DATE, 'dd-MON-yyyy'), '-') NEXT_PAYMENT_DATE,
            NVL(TO_CHAR (IMA.LOAN_START_AMORTIZATION, 'dd-MON-yyyy'), '-') LOAN_START_AMORTIZATION,
            NVL(TO_CHAR (IMA.LOAN_END_AMORTIZATION, 'dd-MON-yyyy'), '-') LOAN_END_AMORTIZATION,
            PAYMENT_CODE,
            PAYMENT_TERM,
            INTEREST_CALCULATION_CODE,
            'A' IAS_CLASS,
            IMA.AMORT_TYPE,
            EIR,
            NVL(FAIR_VALUE_AMOUNT,0) AS FAIR_VALUE_AMOUNT,
            NVL(INITIAL_UNAMORT_TXN_COST,0) AS INITIAL_UNAMORT_TXN_COST,
            NVL(INITIAL_UNAMORT_ORG_FEE,0) AS INITIAL_UNAMORT_ORG_FEE,
            NVL(UNAMORT_COST_AMT,0) AS UNAMORT_COST_AMT,
            NVL(UNAMORT_FEE_AMT,0) AS UNAMORT_FEE_AMT,
            BI_COLLECTABILITY,
            IMA.IFRS9_CLASS,
            INITIAL_OUTSTANDING,
            IMA.CR_STAGE,
            CASE WHEN IMA.OUTSTANDING <> 0
                THEN NVL(IMA.OUTSTANDING, 0)
                ELSE 0
            END OUTSTANDING_PRINCIPAL,
            NVL(EAD_AMOUNT,0) AS EAD_AMOUNT,
            NVL(ECL_AMOUNT,0) AS ECL_AMOUNT
        FROM IFRS_MASTER_ACCOUNT IMA
            LEFT JOIN IFRS_MASTER_PRODUCT_PARAM P ON IMA.PRODUCT_CODE=P.PRD_CODE
            LEFT JOIN IFRS_MASTER_BRANCH B ON IMA.BRANCH_CODE = B.BRANCH_NUM AND IMA.DOWNLOAD_DATE = B.DOWNLOAD_DATE
            LEFT JOIN (SELECT * FROM TBLM_COMMONCODEDETAIL WHERE COMMONCODE = 'B95')TC ON TC.VALUE1 = IMA.ACCOUNT_STATUS
            LEFT JOIN (SELECT * FROM TBLM_COMMONCODEDETAIL WHERE COMMONCODE = 'B202')TC1 ON TC1.VALUE1 = IMA.RESERVED_VARCHAR_2
            LEFT JOIN (SELECT * FROM TBLM_COMMONCODEDETAIL WHERE COMMONCODE = 'AP_ICC')TC2 ON TC2.VALUE1 = IMA.INTEREST_CALCULATION_CODE
        WHERE IMA.MASTERID = SUBSTR(V_DDATE_MAID,11,INSTR(V_DDATE_MAID,'*',1)-11)
            AND IMA.DOWNLOAD_DATE = TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10),'yyyy/MM/dd');

END;