CREATE OR REPLACE PROCEDURE  uspS_LookupSegmentName
(Cur_out          OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN Cur_out FOR
   SELECT
   PKID AS "SEGMENT_CODE",
   SEGMENT AS "DESC"
   FROM IFRS_MSTR_SEGMENT_RULES_HEADER
   WHERE SEGMENT_TYPE = 'CCF_SEGMENT';

END;