CREATE OR REPLACE PROCEDURE USPS_PD_VAS_HEADER
(
    v_eff_date    date,
    v_pd_rule_id  number,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    SELECT  DISTINCT PD_MODEL, "PERIOD", SEGMENTATION, BUCKET_GROUP,
            Y.DESCRIPTION AS CALC_METHOD, PD_METHOD, POPULATION_MONTH,
            INCREMENT_PERIOD, HISTORICAL_MONTH, EXPECTED_LIFE
    FROM(
            SELECT B.PD_RULE_NAME AS PD_MODEL, A.EFF_DATE AS "PERIOD",
            C.SUB_SEGMENT AS SEGMENTATION, B.BUCKET_GROUP, B.CALC_METHOD ,
            D.DESCRIPTION AS PD_METHOD, B.POPULATION_MONTH, B.INCREMENT_PERIOD,
            B.HISTORICAL_DATA AS HISTORICAL_MONTH, B.EXPECTED_LIFE
            FROM IFRS_PD_VAS_CORRELATION A
            JOIN IFRS_PD_RULES_CONFIG B
            ON A.PD_RULE_ID	= B.PKID
            JOIN IFRS_MSTR_SEGMENT_RULES_HEADER C
            ON C.SEGMENT_TYPE = 'PD_SEG'
            AND C.PKID = B.SEGMENTATION_ID
            JOIN TBLM_COMMONCODEDETAIL D
            ON D.COMMONCODE	= 'B13'
            AND B.PD_METHOD = D.VALUE1
            WHERE A.PD_RULE_ID = v_pd_rule_id
            AND A.EFF_DATE = v_eff_date
    ) X
    JOIN TBLM_COMMONCODEDETAIL Y
    ON Y.COMMONCODE	= 'B91'
    AND X.CALC_METHOD = Y.VALUE1;

END;