CREATE OR REPLACE PROCEDURE  USPS_LGD_RECOVERYANALYSIS_DD
(
    V_ACCOUNTNUMBER varchar2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
    select B.PKID, B.PAYMENT_DATE, B.ACCOUNT_NUMBER, B.RECOVERY_AMOUNT
    from ifrs_lgd A
    join ifrs_lgd_data_detail B on (A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER)
    WHERE (A.ACCOUNT_NUMBER = V_ACCOUNTNUMBER)
    ORDER BY B.PAYMENT_DATE asc;
END;