CREATE OR REPLACE PROCEDURE USPS_BGMODULEFEECOST
(
     V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
    --@MASTER_ACCOUNT_ID VARCHAR(100)=''
)
AS
BEGIN
 OPEN Cur_out FOR
    SELECT
        ABS(AMOUNT_FEE + AMORT_FEE) UNAMORT_FEE,
        ABS(AMORT_FEE) AMORT_FEE,
        ABS(AMOUNT_COST + AMORT_COST) UNAMORT_COST,
        ABS(AMORT_COST) AMORT_COST
    FROM IFRS_ACCT_COST_FEE_SUMM IACFST
   WHERE
    IACFST.MASTERID = TO_NUMBER(SUBSTR(V_DDATE_MAID,11,INSTR(V_DDATE_MAID,'*',1)-11))
        AND IACFST.DOWNLOAD_DATE = TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10),'yyyy/MM/dd');
END;