CREATE OR REPLACE PROCEDURE USPS_TRMODULEJOURNALIMPAIR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
    SELECT DOWNLOAD_DATE,
           ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
           GL_ACCOUNT,
           JOURNAL_TYPE,
           JOURNAL_DESC,
           CURRENCY,
           TXN_TYPE AS DB_CR,
           AMOUNT,
           REVERSAL_FLAG AS REVERSE
        FROM IFRS_IMP_JOURNAL_DATA
        WHERE ACCOUNT_NUMBER = SUBSTR(V_DDATE_MAID, 11, LENGTH(RTRIM(V_DDATE_MAID)))
            AND DOWNLOAD_DATE <= TO_CHAR(SUBSTR(V_DDATE_MAID, 1, 10), 111)
    ORDER BY  DOWNLOAD_DATE DESC, REVERSAL_FLAG DESC, AMOUNT DESC, CURRENCY ASC, JOURNAL_TYPE DESC, TXN_TYPE DESC;

END;