CREATE OR REPLACE PROCEDURE USPS_GET_FL_HEADER_BY_CODE
(
    V_ME_CODE varchar2,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT *
        FROM TBLM_MACRO_ECONOMIC
        WHERE ME_CODE = V_ME_CODE;

END;