CREATE OR REPLACE PROCEDURE  USPS_JOBDPARAM
(
  v_HeaderID IN NUMBER DEFAULT NULL,
  Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN  Cur_out FOR
    SELECT *
    FROM TBLT_SERVICEJOBSDETAIL
    WHERE HeaderID = v_HeaderID;

END;