CREATE OR REPLACE PROCEDURE USPS_GET_PREPAYMENT_SUMMARY
(
    V_RuleId Number DEFAULT 0,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

    Select  SEGMENTATION_ID || '_' ||  DURATION || '_' || DOWNLOAD_DATE || '_'  as PKID,
            DOWNLOAD_DATE as PERIOD,
            PREPAYMENT_RULE_ID as PREPAYMENT_ID,
            PREPAYMENT_RULE_NAME as PREPAYMENT_NAME,
            SEGMENTATION_NAME as PREPAYMENT_SEGMENT,
            NVL(PREPAYMENT_RATE,0) * 100 as PREPAYMENT_RATE
            from IFRS_PREPAYMENT_HEADER
            Where PREPAYMENT_RULE_ID = V_RuleId;

END;