CREATE OR REPLACE PROCEDURE  USPS_GET_PREPAYMENT_NAME
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        select PREPAYMENT_RULE_ID, PREPAYMENT_RULE_NAME
        from IFRS_PREPAYMENT_HEADER
        group by PREPAYMENT_RULE_ID,PREPAYMENT_RULE_NAME
        order by PREPAYMENT_RULE_NAME;

END;