CREATE OR REPLACE PROCEDURE USPS_ECL_SUBSEGMENT_ALL(CUR_OUT OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN CUR_OUT FOR
    SELECT A.SUB_SEGMENT AS CODE,
           A.SUB_SEGMENT AS DESCRIPTION
      FROM (SELECT /*+ PARALLEL(auto) */ DISTINCT SUB_SEGMENT
          FROM IFRS_MOVE_MAP_SEGMENT_ASETUANG
          WHERE SUB_SEGMENT IS NOT NULL) A;
  END;