CREATE OR REPLACE PROCEDURE USPS_PD_MIG_HEADER
(
    v_eff_date    date,
    v_pd_rule_id  number,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

            SELECT B.PD_RULE_NAME AS PD_MODEL, A.EFF_DATE AS "PERIOD",
            C.SUB_SEGMENT AS SEGMENTATION, B.BUCKET_GROUP, E.DESCRIPTION AS CALC_METHOD ,
            D.DESCRIPTION AS PD_METHOD, B.POPULATION_MONTH, B.INCREMENT_PERIOD,
            B.HISTORICAL_DATA AS HISTORICAL_MONTH, B.EXPECTED_LIFE
            FROM IFRS_PD_MIG_ODR A
            JOIN IFRS_PD_RULES_CONFIG B
            ON A.PD_RULE_ID    = B.PKID
            JOIN IFRS_MSTR_SEGMENT_RULES_HEADER C
            ON C.SEGMENT_TYPE = 'PD_SEG'
            AND C.PKID = B.SEGMENTATION_ID
            LEFT JOIN TBLM_COMMONCODEDETAIL D
            ON D.COMMONCODE    = 'B13'
            AND B.PD_METHOD = D.VALUE1
            LEFT JOIN TBLM_COMMONCODEDETAIL E
            ON E.COMMONCODE    = 'B91'
            AND B.CALC_METHOD = E.VALUE1
            WHERE A.PD_RULE_ID = v_pd_rule_id
            AND A.EFF_DATE = v_eff_date;


END;