CREATE OR REPLACE PROCEDURE  USPS_DBR_EIR_IFRS9_DTLTWO(
   v_DownloadDate       VARCHAR2 DEFAULT ' ',
   v_AmortMethod         VARCHAR2 DEFAULT ' ',
   Cur_out           OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN Cur_out FOR
    SELECT TO_CHAR (DOWNLOAD_DATE, 'dd-MON-yyyy') AS DOWNLOAD_DATE,
        V_AmortMethod,
        PRODUCT_CODE,
        ACCOUNT_NUMBER,
        SUM(INITIAL_FEE) AS "INITIAL_FEE",
        SUM(INITIAL_COST) AS "INITIAL_COST",
        SUM(UNAMORT_FEE) AS "UNAMORT_FEE",
        SUM(UNAMORT_COST) AS "UNAMORT_COST",
        SUM(AMORT_FEE) AS "AMORT_FEE",
        SUM(AMORT_COST) AS "AMORT_COST",
        SUM(AMORT_FEE_MTD) AS "AMORT_FEE_MTD",
        SUM(AMORT_COST_MTD) AS "AMORT_COST_MTD",
        SUM(AMORT_FEE_YTD) AS "AMORT_FEE_YTD",
        SUM(AMORT_COST_YTD) AS "AMORT_COST_YTD"
    FROM IFRS_NOMINATIF_MONTHLY
    WHERE
    --CONVERT(VARCHAR(6), DOWNLOAD_DATE, 112) = CONVERT(VARCHAR(6), @DownloadDate, 112)
     DOWNLOAD_DATE=TO_DATE (v_DownloadDate, 'dd-MON-yyyy' )
    --TO_CHAR (DOWNLOAD_DATE, 'dd-MON-yyyy')= TO_CHAR (V_DOWNLOAD_DATE, 'dd-MON-yyyy')
        --AND PRODUCT_CODE = V_ProductCode
        AND UPPER(AMORT_TYPE) = UPPER(V_AmortMethod)
    GROUP BY ACCOUNT_NUMBER,
        DOWNLOAD_DATE,
        PRODUCT_CODE
    HAVING SUM(INITIAL_FEE) <> 0
        OR SUM(INITIAL_COST) <> 0
        --AND SUM(INITIAL_COST) > 0
    ORDER BY ACCOUNT_NUMBER;

END;