CREATE OR REPLACE PROCEDURE USPS_LOANMODULEINDVIMPAIR
(
   V_DDATE_MAID VARCHAR2 DEFAULT ' ',
   Cur_out OUT SYS_REFCURSOR
)
AS
    v_DATE DATE;
    v_MASTERID NUMBER(18);
BEGIN

    v_DATE := TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd');
    v_MASTERID := TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));

    --FILLER SCRIPT. TO BE REPLACED
    OPEN Cur_out FOR
    SELECT A.DOWNLOAD_DATE AS "Period",
        A.ACCOUNT_NUMBER AS "Account Number",
        A.CURRENCY AS "Currency",
        A.EIR AS "EIR",
        A.BI_COLLECTABILITY AS "BI Collectability",
        --A.INTEREST_RATE AS "INTEREST_RATE",
        A.EAD_AMOUNT AS "EAD_AMOUNT",
        COALESCE(BEGINNING_BALANCE, 0) AS "Beginning Balance",
        COALESCE(CHARGE_AMOUNT, 0) AS "Charge",
        COALESCE(WRITEBACK_AMOUNT, 0) AS "Write Back",
        COALESCE(ENDING_BALANCE, 0) AS "Ending Balance"
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    --JOIN IFRS_IMP_IA_MASTER B ON A.FACILITY_NUMBER = B.FACILITY_NUMBER
    WHERE A.DOWNLOAD_DATE BETWEEN ADD_MONTHS(v_DATE, -12) AND v_DATE
          AND A.MASTERID = v_MASTERID
          AND A.IMPAIRED_FLAG = 'I'
          ORDER BY DOWNLOAD_DATE DESC;

    /*
    SELECT A.DOWNLOAD_DATE AS "PERIOD",
        A.ACCOUNT_NUMBER AS "ACCOUNT_NUMBER",
        CURRENCY AS CURRENCY,
        'I' AS "IMPAIR_FLAG" ,
        BI_COLLECTABILITY AS "BI_COLLECTABILITY",
        ROUND (B.INTEREST_RATE, 6) AS "INTEREST_RATE",
        COALESCE (EAD_AMOUNT, 0) AS "EAD_AMOUNT",
        COALESCE (TTL_GROSS_PROCEED, 0) AS "TOTAL_ESTIMATED_CASHFLOW",
        COALESCE (TTL_NPV, 0) AS "PV_ESTIMATED_CASHFLOW",
        COALESCE (A.ECL_AMOUNT, 0) AS "INDIVIDUAL_PROVISION",
        COALESCE (BEGINNING_BALANCE, 0) AS "BEGINNING_BALANCE",
        COALESCE (CHARGE, 0) AS "CHARGE",
        COALESCE (WRITEBACK, 0) AS "WRITEBACK",
        COALESCE (ENDING_BALANCE, 0) AS "ENDING_BALANCE"
    FROM IFRS_MASTER_ACCOUNT_MONTHLY A
    JOIN IFRS_IMP_IA_MASTER B ON A.FACILITY_NUMBER = B.FACILITY_NUMBER
    WHERE A.DOWNLOAD_DATE <= TO_CHAR (SUBSTR(V_DDATE_MAID, 1, 10), 111)
      AND A.MASTER_ACCOUNT_ID = SUBSTR(V_DDATE_MAID, 11, LENGTH(RTRIM(V_DDATE_MAID)));
    */

END;