CREATE OR REPLACE PROCEDURE USPS_DISASTERLOAN_DETAIL
(
    v_ACCOUNT_NUMBER IN VARCHAR2,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT DISTINCT
            DOWNLOAD_DATE,
            ACCOUNT_NUMBER,
            ROUND(ECL_AMOUNT, 6) ECL_AMOUNT,
            REMARKS,
            UPLOADDATE
        FROM TBLU_DISASTER_LOAN
        WHERE ACCOUNT_NUMBER = v_ACCOUNT_NUMBER
        ORDER BY
            UPLOADDATE DESC,
            ACCOUNT_NUMBER;

END;