CREATE OR REPLACE PROCEDURE USPS_MAPPINGRULE_SINGLE
(
    v_PKID in number default null,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

OPEN  Cur_out FOR
        SELECT A.PKID,
        MAPPINGNAME,
        MAPPINGDESCRIPTION,
        B.DESCRIPTION MAPPINGTYPEDESCRIPTION,
        FILETYPE,
        C.DESCRIPTION || ' (.' || FILETYPE || ')' FILETYPEDESCRIPTION,
        TABLEDESTINATION,
        KEYHISTORY,
        NEEDAPPROVAL,
        FILENAME
    FROM TBLM_MAPPINGRULEHEADER_NEW A
        LEFT JOIN TBLM_COMMONCODEDETAIL B ON A.MAPPINGTYPE = B.VALUE1
            AND B.COMMONCODE = 'AP030'
        LEFT JOIN TBLM_COMMONCODEDETAIL C ON A.FILETYPE = C.VALUE1
            AND C.COMMONCODE = 'AP031'
    WHERE A.PKID = v_PKID;

END;