CREATE OR REPLACE PROCEDURE USPS_DISASTERLOAN_HEADER
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT DISTINCT
            MAX(DOWNLOAD_DATE) DOWNLOAD_DATE,
            ACCOUNT_NUMBER,
            ROUND(ECL_AMOUNT, 6) ECL_AMOUNT,
            REMARKS,
            MAX(UPLOADDATE) AS UPLOADDATE
        FROM TBLU_DISASTER_LOAN
        GROUP BY
            ACCOUNT_NUMBER,
            ECL_AMOUNT,
            REMARKS
        ORDER BY
            UPLOADDATE DESC,
            ACCOUNT_NUMBER;

END;