CREATE OR REPLACE PROCEDURE  uspS_LookupSegmentationid
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT PKID AS "SEGMENTATION_ID",SUB_SEGMENT AS "Segment" from IFRS_MSTR_SEGMENT_RULES_HEADER where SEGMENT_TYPE = 'CCF_SEG'
        ORDER BY SEGMENT;

END;