CREATE OR REPLACE PROCEDURE USPS_BGMODULEJOURNALEIR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
    SELECT DOWNLOAD_DATE,
        ACCTNO AS ACCOUNT_NUMBER,
        FLAG_CF,
        GLNO AS GL_ACCOUNT, --GLNO + '-' + BRANCH + '-00' AS GL_ACCOUNT,  --> SMI
        CASE WHEN JOURNALCODE = 'AMORT' THEN
            JOURNALCODE
        ELSE
            JOURNALCODE2
        END AS JOURNAL_TYPE,
        JOURNAL_DESC,
        CCY,
        DRCR AS DB_CR,
        REVERSE,
        N_AMOUNT AS AMOUNT,
        MASTERID AS MASTER_ACCOUNT_ID
    FROM IFRS_ACCT_JOURNAL_DATA A
    WHERE A.MASTERID = TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, LENGTH(RTRIM(V_DDATE_MAID))))
        AND DOWNLOAD_DATE <= TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10), 'yyyy/MM/dd')
    ORDER BY  DOWNLOAD_DATE DESC, REVERSE DESC, N_AMOUNT DESC, CCY ASC, JOURNALCODE DESC, DRCR DESC,
     NOREF ASC;

END;