CREATE OR REPLACE PROCEDURE  USPS_R_VARCLUS_CLUSTER_DTL (
    v_MODEL_ID NUMBER,
    v_CLUS_NO NUMBER,
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_status NUMBER(10);
BEGIN
    SELECT STATUS
    INTO v_status
    FROM IFRS_FL_MODEL_VAR_PEN
    WHERE PKID = v_MODEL_ID;

    IF v_status = 1 THEN
        OPEN Cur_out FOR
        SELECT A.PKID,
        A.MODEL_ID,
        A.CLUS_NO,
        A.VAR_NAME,
        ROUND(A.PRIN_COMP1,6) PRIN_COMP1,
        ROUND(A.PRIN_COMP2,6) PRIN_COMP2,
        ROUND(A.RSQRD_OWN,6) RSQRD_OWN,
        ROUND(A.RSQRD_NEXT,6) RSQRD_NEXT,
        ROUND(A.RSQRD_RATIO,6) RSQRD_RATIO,
        ROUND(A.VAR_INDX,6) VAR_INDX
        FROM R_VARCLUS_CLUSTER_DTL A
        WHERE MODEL_ID = v_MODEL_ID AND CLUS_NO = v_CLUS_NO;
    ELSE
        OPEN Cur_out FOR
        SELECT A.PKID,
        A.MODEL_ID,
        A.CLUS_NO,
        A.VAR_NAME,
        ROUND(A.PRIN_COMP1,6) PRIN_COMP1,
        ROUND(A.PRIN_COMP2,6) PRIN_COMP2,
        ROUND(A.RSQRD_OWN,6) RSQRD_OWN,
        ROUND(A.RSQRD_NEXT,6) RSQRD_NEXT,
        ROUND(A.RSQRD_RATIO,6) RSQRD_RATIO,
        ROUND(A.VAR_INDX,6) VAR_INDX
        FROM R_VARCLUS_CLUSTER_DTL_PEN A
        WHERE MODEL_ID = v_MODEL_ID AND CLUS_NO = v_CLUS_NO;
    END IF;


END;