CREATE OR REPLACE PROCEDURE USPS_IA_HISTORY_PERCENTAGE (
    v_customer_number varchar2,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR

        SELECT ACCOUNT_NUMBER || '_' || TO_CHAR(PKID) AS PKID, ACCOUNT_NUMBER,
        IMPAIRED_FLAG, OVERRIDE_DATE, EFFECTIVE_DATE, UPLOADID,
        TO_CHAR(SUM(ESTIMATED_CF_PERCENT)) || '%'  AS PERCENTAGE
        FROM
            (
                SELECT DISTINCT C.ACCOUNT_NUMBER, C.IMPAIRED_FLAG, A.CREATEDDATE AS OVERRIDE_DATE,
                A.EFFECTIVE_DATE, B.ESTIMATED_CF_PERCENT, A.PKID, B.UPLOADID
                FROM IFRS_IA_OVERRIDEH_HIST A
                JOIN IFRS_IA_OVERRIDED_HIST C
                ON A.PKID = C.OVERRIDEID
                JOIN TBLU_DCF_DETAIL B
                ON A.PKID = B.OVERRIDEID
                AND A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
                WHERE A.CUSTOMER_NUMBER = v_customer_number
            ) X
        GROUP BY ACCOUNT_NUMBER || '_' || TO_CHAR(PKID), ACCOUNT_NUMBER,
                 IMPAIRED_FLAG, OVERRIDE_DATE, EFFECTIVE_DATE, UPLOADID
        ORDER BY ACCOUNT_NUMBER, EFFECTIVE_DATE DESC;

END;