CREATE OR REPLACE PROCEDURE  USPS_FUNDMODULEEVENTCHANGES
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
    v_MASTERID NUMBER(18);
    v_ACCNUM VARCHAR(50);
BEGIN

    v_MASTERID := TO_NUMBER(SUBSTR(V_DDATE_MAID, 11, INSTR(V_DDATE_MAID, '*', 1) - 11));
    v_ACCNUM := TO_CHAR(SUBSTR(V_DDATE_MAID, INSTR(V_DDATE_MAID, '*', 1) + 1, LENGTH(V_DDATE_MAID)));

    OPEN Cur_out FOR
        SELECT ACCOUNT_NUMBER,
            TO_CHAR(EFFECTIVE_DATE, 'yyyy/MM/dd') || V_MASTERID || '*' || v_ACCNUM as DDATE_MAID,
            EFFECTIVE_DATE,
            EVENT_ID,
            REMARKS,
            BEFORE_VALUE,
            AFTER_VALUE
        FROM IFRS_EVENT_CHANGES
        WHERE MASTERID = v_MASTERID
        ORDER BY EFFECTIVE_DATE ASC;

END;