CREATE OR REPLACE PROCEDURE  uspS_LookupDefaultRule
(
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT PKID AS "DEFAULT_RULE_ID",RULE_NAME AS "Default Rule" from IFRS_SCENARIO_RULES_HEADER --where RULE_TYPE = 'DEFAULT_RULE'
        ORDER BY RULE_NAME;

END;