CREATE OR REPLACE PROCEDURE USPS_BGMODULEVALCURRAMT
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
    --@MASTER_ACCOUNT_ID VARCHAR(100)=''
)
AS
BEGIN

    OPEN Cur_out FOR
    SELECT
        NVL(TO_CHAR (IACE.DOWNLOAD_DATE, 'dd-MON-yyyy'), '-') DOWNLOAD_DATE,
        PMT_DATE,
        N_PRN_PAYMENT,
        N_INT_PAYMENT,
        N_OSPRN,
        N_INT_RATE,
        N_EFF_INT_RATE,
        N_EFF_INT_AMT,
        N_UNAMORT_AMT,
        N_AMORT_AMT,
        N_FAIRVALUE,
        N_FEE_AMORT_AMT,
        N_COST_AMORT_AMT,
        N_FEE_UNAMORT_AMT,
        N_COST_UNAMORT_AMT
    FROM IFRS_ACCT_EIR_ECF IACE
    WHERE
    IACE.MASTERID = TO_NUMBER(SUBSTR(V_DDATE_MAID,11,INSTR(V_DDATE_MAID,'*',1)-11))
        AND IACE.DOWNLOAD_DATE = TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10),'yyyy/MM/dd');
   --    ORDER BY PMT_DATE
END;