CREATE OR REPLACE PROCEDURE  USPS_GETACOHEADER
(
    V_MACODE VARCHAR2,
    Cur_out OUT SYS_REFCURSOR
)
AS
    V_CURRDATE DATE;
BEGIN

    SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;

    OPEN Cur_out FOR
        SELECT IMA.DOWNLOAD_DATE AS DOWNLOAD_DATE,
            IMA.MASTER_ACCOUNT_CODE,
            IMA.CUSTOMER_NUMBER,
            IMA.CUSTOMER_NAME,
            IMA.ACCOUNT_NUMBER,
            IMP.PRD_DESC AS PRODUCT_DESC,
            NVL(ACO.EFFECTIVE_DATE, NVL(SPPI.EFFECTIVE_DATE, IMA.DOWNLOAD_DATE)) AS EFFECTIVE_DATE,
            NVL(BM.BMID, 0) AS BMID,
            NVL(ACO.BMRESULT, IMA.BM_RESULT) AS BMRESULT,
            NVL(BMRS.DESCRIPTION, ' ') AS BMRESULTNAME,
            NVL(ACO.PKID, NVL(SPPI.PKID, 0)) AS SPPIID,
            NVL(ACO.SPPINAME, NVL(SPPI.SPPINAME, ' ')) AS SPPINAME,
            NVL(ACO.SPPIRESULT, NVL(SPPI.SPPIRESULT, IMA.SPPI_RESULT)) AS SPPIRESULT,
            NVL(SPPIRS.DESCRIPTION, ' ') AS SPPIRESULTNAME,
            NVL(ACO.TEMPLATEID, NVL(SPPI.TEMPLATEID, 0)) AS TEMPLATEID,
            NVL(SPPI.PRODUCT_CODE, IMA.PRODUCT_CODE) AS PRODUCTCODE,
            NVL(ACO.OVERRIDEFLAG, NVL(SPPI.OVERRIDEFLAG, 0)) AS OVERRIDEFLAG,
            NVL(ACO.OVERRIDERESULT, NVL(SPPI.OVERRIDERESULT, ' ')) AS OVERRIDERESULT,
            NVL(ACO.REMARK, NVL(SPPI.REMARK, ' ')) AS REMARK
        FROM IFRS_MASTER_ACCOUNT IMA
            JOIN IFRS_MASTER_PRODUCT_PARAM IMP
                ON IMA.PRODUCT_CODE = IMP.PRD_CODE
            LEFT JOIN IFRS_AC_OVERRIDE ACO
                ON IMA.MASTER_ACCOUNT_CODE = ACO.MASTER_ACCOUNT_CODE
                    AND ACO.STATUS = 1
            LEFT JOIN IFRS_AC_SPPI_HEADER SPPI
                ON SPPI.PRODUCT_CODE LIKE  '%' || IMA.PRODUCT_CODE || '%'
                    AND SPPI.STATUS = 1
            LEFT JOIN TBLM_COMMONCODEDETAIL SPPIRS
                ON NVL(ACO.SPPIRESULT, NVL(SPPI.SPPIRESULT, IMA.SPPI_RESULT)) = SPPIRS.VALUE1
                    AND SPPIRS.COMMONCODE = 'B38'
            LEFT JOIN IFRS_AC_BM_HEADER BM
                ON IMA.BM_RESULT = BM.BMRESULT
                    AND BM.STATUS = 1
            LEFT JOIN TBLM_COMMONCODEDETAIL BMRS
                ON NVL(ACO.BMRESULT, NVL(BM.BMRESULT, IMA.BM_RESULT)) = BMRS.VALUE1
                    AND BMRS.COMMONCODE = 'B39'
        WHERE IMA.DOWNLOAD_DATE = V_CURRDATE
            AND IMA.ACCOUNT_STATUS = 'A'
            AND IMA.MASTER_ACCOUNT_CODE = V_MACODE;

END;