CREATE OR REPLACE PROCEDURE USPS_MEDERIVED_H(
    v_MODEL_ID number,
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN Cur_out FOR
    SELECT
        A.ME_CODE, B.ME_DESC
    FROM IFRS_INDEPENDENT_VARIABLE_PEN A
    JOIN TBLM_MACRO_ECONOMIC B
    ON A.ME_CODE = B.ME_CODE
    AND A.MODEL_ID = v_MODEL_ID
    ORDER BY B.ME_DESC;

END;