CREATE OR REPLACE PROCEDURE  USPS_JOBASSEMBLY
(
  v_Name IN VARCHAR2 DEFAULT NULL,
  Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN  Cur_out FOR
    SELECT * FROM TBLM_JOBSACTIVATOR WHERE NAME = v_Name;

END;