CREATE OR REPLACE PROCEDURE  USPS_TRMODULECONTRACTATTR
(
    V_DDATE_MAID VARCHAR2 DEFAULT ' ',
    Cur_out OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN Cur_out FOR
        SELECT NVL(TO_CHAR (IMA.DOWNLOAD_DATE, 'dd-MON-yyyy'), '-') DOWNLOAD_DATE,
            IMA.AMORT_TYPE,
            IMA.PRODUCT_ENTITY,
            IMA.DATA_SOURCE,
            CUSTOMER_NAME,
            CUSTOMER_NUMBER,
            FACILITY_NUMBER,
            ACCOUNT_NUMBER,
            NVL(ACCOUNT_STATUS, '') || ' - ' || TC.DESCRIPTION AS ACCOUNT_STATUS,
            NVL(TO_CHAR (IMA.LOAN_START_DATE, 'dd-MON-yyyy'), '-') LOAN_START_DATE,
            NVL(TO_CHAR (IMA.LOAN_DUE_DATE, 'dd-MON-yyyy'), '-') LOAN_DUE_DATE,
            NVL(TO_CHAR (IMA.NEXT_PAYMENT_DATE, 'dd-MON-yyyy'), '-') NEXT_PAYMENT_DATE,
            IMA.BRANCH_CODE,
            B.BRANCH_NAME,
            PRODUCT_GROUP,
            PRODUCT_CODE,
            PRODUCT_TYPE,
            P.PRD_DESC,
            CURRENCY,
            EXCHANGE_RATE,
            IMA.IFRS9_CLASS,
            INTEREST_RATE,
            NVL(INITIAL_OUTSTANDING,0) AS INITIAL_OUTSTANDING,
            NVL(OUTSTANDING,0) AS OUTSTANDING,
            NVL(FAIR_VALUE_AMOUNT,0) AS FAIR_VALUE_AMOUNT,
            NVL(EAD_AMOUNT,0) AS EAD_AMOUNT,
            NVL(ECL_AMOUNT,0) AS ECL_AMOUNT,
            IMA.CR_STAGE,
            TENOR,
            REMAINING_TENOR,
            BI_COLLECTABILITY,
            NVL(IMA.RESERVED_VARCHAR_12,'') AS RESERVED_VARCHAR_12,
            NVL(IMA.RESERVED_VARCHAR_5,'') AS RESERVED_VARCHAR_5,
            NVL(IMA.RESERVED_AMOUNT_4,0) AS RESERVED_AMOUNT_4,
            NVL(IMA.RESERVED_FLAG_1,0) AS RESERVED_FLAG_1,
            NVL(IMA.RESERVED_AMOUNT_3,0) AS RESERVED_AMOUNT_3,
            NVL(IMA.RESERVED_AMOUNT_2,0) AS RESERVED_AMOUNT_2,
            NVL(MARKET_RATE,0) AS MARKET_AMOUNT,
            NVL(IMA.RESERVED_AMOUNT_5,0) AS RESERVED_AMOUNT_5,
            NVL(IMA.RESERVED_FLAG_2,0) AS RESERVED_FLAG_2,
            NVL(IMA.RESERVED_FLAG_4,0) AS RESERVED_FLAG_4,
            NVL(IMA.RESERVED_VARCHAR_1,'') AS RESERVED_VARCHAR_1,
            NVL(IMA.RESERVED_AMOUNT_8,0) AS RESERVED_AMOUNT_8,
            NVL(IMA.RESERVED_FLAG_3,0) AS RESERVED_FLAG_3,
            NVL(IMA.RESERVED_AMOUNT_7,0) AS RESERVED_AMOUNT_7,
            NVL(TO_CHAR (IMA.RESERVED_DATE_1, 'dd-MON-yyyy'), '-') RESERVED_DATE_1,
            NVL(IMA.RESERVED_VARCHAR_1,'') AS RESERVED_VARCHAR_3,
            NVL(IMA.RESERVED_VARCHAR_1,'') AS RESERVED_VARCHAR_1,
            NVL(INITIAL_UNAMORT_TXN_COST,0) AS INITIAL_UNAMORT_TXN_COST,
            NVL(INITIAL_UNAMORT_ORG_FEE,0) AS INITIAL_UNAMORT_ORG_FEE,
            NVL(UNAMORT_COST_AMT,0) AS UNAMORT_COST_AMT,
            NVL(UNAMORT_FEE_AMT,0) AS UNAMORT_FEE_AMT,
            NVL(IMA.RESERVED_VARCHAR_2,'') || ' - ' || TC1.DESCRIPTION  as RESERVED_VARCHAR_2,
            INTEREST_ACCRUED
        FROM IFRS_MASTER_ACCOUNT IMA
            LEFT JOIN IFRS_MASTER_PRODUCT_PARAM P ON IMA.PRODUCT_CODE=P.PRD_CODE
            LEFT JOIN IFRS_MASTER_BRANCH B ON IMA.BRANCH_CODE = B.BRANCH_NUM AND IMA.DOWNLOAD_DATE = B.DOWNLOAD_DATE
            LEFT JOIN (SELECT * FROM TBLM_COMMONCODEDETAIL WHERE COMMONCODE = 'B95')TC ON TC.VALUE1 = IMA.ACCOUNT_STATUS
            LEFT JOIN (SELECT * FROM TBLM_COMMONCODEDETAIL WHERE COMMONCODE = 'B202')TC1 ON TC1.VALUE1 = IMA.RESERVED_VARCHAR_2
        WHERE IMA.MASTERID = SUBSTR(V_DDATE_MAID,11,INSTR(V_DDATE_MAID,'*',1)-11)
            AND IMA.DOWNLOAD_DATE = TO_DATE(SUBSTR(V_DDATE_MAID, 1, 10),'yyyy/MM/dd');

END;