CREATE OR REPLACE PROCEDURE  USPU_UPDATEMEJOBS
(
    V_PKID number default 0,
    V_Status number default 0
)
AS
BEGIN
    INSERT INTO TBLT_SERVICEJOBSHEADER(JOBNAME, STATUS, CREATEDBY, CREATEDDATE, CREATEDHOST)
    SELECT 'RUN_LINEAR_REGRESSION' AS JOBNAME, DESCRIPTION AS STATUS,  'SYSTEM' AS CREATEDBY,  SYSDATE AS CREATEDDATE,  'SYSTEM' AS  CREATEDHOST
    FROM TBLM_COMMONCODEDETAIL
    WHERE COMMONCODE = 'B129' AND VALUE1 = '1';
END;