CREATE OR REPLACE PROCEDURE USPU_UPDATE_ECLSTATUS
(
    V_PKID number default 0,
    V_Status number default 0
)
AS
BEGIN
    UPDATE IFRS_ECL_MODEL_HEADER SET RUN_STATUS = V_Status
    WHERE PKID = V_PKID;
    UPDATE IFRS_ECL_MODEL_HEADER SET LAST_RUN_DATE = SYSDATE()
    WHERE PKID = V_PKID;
    COMMIT;
END;