CREATE OR REPLACE PROCEDURE USPU_R_MODEL_FILTER_DTL_VS (
    v_MODEL_ID NUMBER
)
AS
BEGIN
    UPDATE R_MODEL_FILTER_DTL_PEN A
    SET A.VARIABLE_SELECTION = 0
    WHERE MODEL_ID = v_MODEL_ID;
    COMMIT;
END;