CREATE OR REPLACE PROCEDURE X_SP_IFRS_INSERT(v_DOWNLOADDATE DATE DEFAULT NULL,
                                             v_DATASOURCE   VARCHAR2 DEFAULT 'ALL') AS
  v_QUERY VARCHAR2(32000);
BEGIN
  DBMS_OUTPUT.put_line(v_DOWNLOADDATE);
END;