CREATE OR REPLACE PROCEDURE X_SP_IFRS_INSERT_2(v_DOWNLOADDATECUR  DATE DEFAULT ('1-JAN-1900'),
                                               v_DOWNLOADDATEPREV DATE DEFAULT ('1-JAN-1900')) AS
  v_QUERY VARCHAR2(32000);
BEGIN
  DBMS_OUTPUT.put_line(v_DOWNLOADDATECUR);
  DBMS_OUTPUT.put_line(v_DOWNLOADDATEPREV);
END;