---- DROP PROCEDURE SP_IFRS_LOG_AMORT;

CREATE OR REPLACE PROCEDURE SP_IFRS_LOG_AMORT (
	IN P_DOWNLOAD_DATE DATE DEFAULT NULL::DATE,
	IN P_OPS VARCHAR(100) DEFAULT NULL,
	IN P_PROCNAME VARCHAR(200) DEFAULT NULL,
	IN P_REMARK VARCHAR(200) DEFAULT NULL)
LANGUAGE PLPGSQL AS $$
BEGIN
	INSERT INTO IFRS_AMORT_LOG (DOWNLOAD_DATE, DTM, OPS, PROCNAME, REMARK) VALUES (P_DOWNLOAD_DATE, CLOCK_TIMESTAMP(), P_OPS, P_PROCNAME, P_REMARK);
END;
$$;
