CREATE OR REPLACE FUNCTION PSAK413.FUTIL_PV(
    V_I   IN NUMBER,   -- BUNGA
    V_N   IN NUMBER,   -- N MONTH
    V_PMT IN NUMBER    -- NOMINAL
) RETURN NUMBER
IS
    V_PV NUMBER(32,6);
BEGIN
    V_PV := V_PMT * (1 / POWER(1 + V_I, V_N));
    RETURN V_PV;
END FUTIL_PV;
/
