CREATE OR REPLACE PROCEDURE IFRS9_BCA.SP_IFRS_EAD_PROCESS_BCA (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE     DEFAULT NULL,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    ----------------------------------------------------------------
    -- VARIABLES
    ----------------------------------------------------------------
    V_SP_NAME     VARCHAR2(100) := 'SP_IFRS_EAD_PROCESS_BCA';
    V_OWNER       VARCHAR2(30);
    V_CURRDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);
    V_COUNT         NUMBER;

    -- DYNAMIC SQL (USE VARCHAR2 LARGE)
    V_STR_QUERY     VARCHAR2(32767);

    -- TABLE NAMES (UNQUALIFIED PARTS)
    V_TABLEINSERT1  VARCHAR2(100);
    V_TABLEINSERT2  VARCHAR2(100);
    V_TABLESELECT1  VARCHAR2(100);
    V_TABLECONFIG   VARCHAR2(100);


    -- CURSOR
    TYPE REF_CURSOR IS REF CURSOR;
    C_RULE        REF_CURSOR;

    -- FETCH VARIABLES
    V_RULE_ID     VARCHAR2(250);
    V_RULE_TYPE VARCHAR2(25);
    V_TABLE_NAME  VARCHAR2(100);
    V_PD_RULES_QRY_RESULT CLOB;


    -- MISC
    V_RETURNROWS    NUMBER := 0;
    V_RETURNROWS2   NUMBER := 0;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);
    V_RUNID         VARCHAR2(30);
    V_SYSCODE       VARCHAR2(10);
    V_PRC           VARCHAR2(5);
    V_EOM           DATE;
    V_FOM           DATE;

    -- RESULT QUERY
    V_QUERYS        CLOB;


BEGIN

    ----------------------------------------------------------------
    -- GET OWNER
    ----------------------------------------------------------------
    SELECT USERNAME INTO V_OWNER FROM USER_USERS;

    ----------------------------------------------------------------
    -- INSERT VCURRDATE DETERMINATION IF NULL
    ----------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        BEGIN
            SELECT CURRDATE INTO V_CURRDATE FROM IFRS9_BCA.IFRS_PRC_DATE_AMORT;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20010, 'IFRS_PRC_DATE_AMORT has no CURRDATE row');
        END;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_RUNID := NVL(P_RUNID, 'P_00000_0000');
    V_SYSCODE := NVL(P_SYSCODE, '0');
    V_MODEL_ID := V_SYSCODE;
    V_PRC := NVL(P_PRC, 'P');
    V_EOM := LAST_DAY(V_CURRDATE);
    V_FOM := TRUNC(V_CURRDATE) - (TO_NUMBER(TO_CHAR(V_CURRDATE,'DD')) - 1);
    ----------------------------------------------------------------
    -- TABLE DETERMINATION
    ----------------------------------------------------------------
    IF V_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'IFRS_EAD_RESULT_' || V_RUNID;
        V_TABLESELECT1 := 'IFRS_MASTER_ACCOUNT_' || V_RUNID;
        V_TABLECONFIG := 'IFRS_ECL_MODEL_CONFIG_' || V_RUNID;
    ELSE 
        V_TABLEINSERT1 := 'IFRS_EAD_RESULT';
        V_TABLESELECT1 := 'IFRS_MASTER_ACCOUNT';
        V_TABLECONFIG := 'IFRS_ECL_MODEL_CONFIG';
    END IF;

    IFRS9_BCA.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, V_RUNID, TO_NUMBER(SYS_CONTEXT('USERENV','SESSIONID')), SYSDATE);
    COMMIT;

    ----------------------------------------------------------------
    -- PRE-PROCESSING SIMULATION TABLES
    ----------------------------------------------------------------
    IF V_PRC = 'S' THEN
        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT1 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.IFRS_EAD_RESULT WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;

        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLESELECT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLESELECT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLESELECT1 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.IFRS_MASTER_ACCOUNT WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
    END IF;
    COMMIT;

    ----------------------------------------------------------------
    -- MAIN PROCESSING
    ----------------------------------------------------------------

    ----------------------------------------------------------------
    -- CLEAR TEMP TABLES
    ----------------------------------------------------------------
    
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.TMP_IFRS_IMA_EAD';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MIN_MAX';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING';
    ----------------------------------------------------------------

    V_STR_QUERY := 'SELECT COUNT(*) FROM USER_PART_TABLES WHERE TABLE_NAME = ''' || V_TABLEINSERT1 || '''';
    EXECUTE IMMEDIATE V_STR_QUERY INTO V_COUNT;

    IF V_COUNT > 0 THEN

        EXECUTE IMMEDIATE 
        'ALTER TABLE ' || V_OWNER || '.' || V_TABLEINSERT1 || ' TRUNCATE PARTITION DOWNLOAD_DATE_' || TO_CHAR(V_CURRDATE,'YYYY_MM');

    ELSE

        EXECUTE IMMEDIATE 
        'DELETE FROM ' || V_OWNER || '.' || V_TABLEINSERT1 || ' WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';

    END IF;



    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_IMA_EAD
   (
    DOWNLOAD_DATE,
    MASTERID,
    CURRENCY,
    EXCHANGE_RATE,
    ECL_MODEL_ID,
    CR_STAGE,
    DATA_SOURCE,
    SEGMENT_RULE_ID,
    EAD_RULE_ID,
    EAD_SEGMENT,
    CCF_RULE_ID,
    PREPAYMENT_RULE_ID,
    LIFETIME_PERIOD,
    LOAN_START_DATE,
    LOAN_DUE_DATE,
    NEXT_PAYMENT_DATE,
    LAST_PAYMENT_DATE,
    UNUSED_AMOUNT,
    OUTSTANDING,
    REVOLVING_FLAG,
    EAD_BALANCE,
    UNAMORT_FEE_AMT,
    MARKET_AMOUNT,
    INTEREST_ACCRUED,
    COMMITMENT_FLAG
    )
    SELECT A.DOWNLOAD_DATE,
           A.MASTERID,
           A.CURRENCY,
           A.EXCHANGE_RATE,
           ' || V_MODEL_ID || ' AS ECL_MODEL_ID,
           CR_STAGE,
           A.DATA_SOURCE,
           A.SEGMENT_RULE_ID,
           C.EAD_MODEL_ID AS EAD_RULE_ID,
           H.SUB_SEGMENT AS EAD_SEGMENT,
           C.CCF_RULES_ID,
           C.PREPAYMENT_RULES_ID,
           CASE WHEN ROUND(MONTHS_BETWEEN(A.LOAN_DUE_DATE, TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''))) <= 0 THEN 1 ELSE ROUND((MONTHS_BETWEEN(A.LOAN_DUE_DATE, TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')))) END AS LIFETIME,
           A.LOAN_START_DATE,
           A.LOAN_DUE_DATE,
           A.NEXT_PAYMENT_DATE,
           A.LAST_PAYMENT_DATE,
           CASE WHEN A.CR_STAGE = ''3'' AND NOT (A.DATA_SOURCE = ''BTRD'' OR (A.DATA_SOURCE = ''ILS'' AND A.PRODUCT_CODE LIKE ''B%'')) THEN 0 --CCF ONLY APPLIED TO STAGE 1 AND 2
                WHEN A.DATA_SOURCE = ''ILS'' AND A.PRODUCT_CODE LIKE ''B%'' THEN A.OUTSTANDING
                WHEN D.SUM_OUTSTANDING = 0 AND D.UNUSED_AMOUNT > 0 THEN ((D.UNUSED_AMOUNT * NVL(A.EXCHANGE_RATE, 1)) / D.NOA)/ NVL(A.EXCHANGE_RATE, 1)
                WHEN D.SUM_OUTSTANDING > 0 AND D.UNUSED_AMOUNT > 0 THEN (NVL(A.OUTSTANDING,0) * NVL(A.EXCHANGE_RATE, 1)/ D.SUM_OUTSTANDING) * (D.UNUSED_AMOUNT * NVL(A.EXCHANGE_RATE, 1)) / NVL(A.EXCHANGE_RATE, 1)
                WHEN NVL(A.RESERVED_AMOUNT_2,0) > 0 AND A.DATA_SOURCE = ''CRD'' THEN NVL(A.RESERVED_AMOUNT_2,0)
                ELSE 0
           END AS UNUSED_AMOUNT,
           CASE WHEN A.DATA_SOURCE = ''ILS'' AND A.PRODUCT_CODE LIKE ''B%'' THEN 0 ELSE NVL(A.OUTSTANDING,0) END AS OUTSTANDING,
           NVL(A.REVOLVING_FLAG,0) REVOLVING_FLAG,
           B.EAD_BALANCE,
           A.UNAMORT_FEE_AMT,
           A.RESERVED_AMOUNT_13 AS MARKET_AMOUNT,
           CASE WHEN A.BI_COLLECTABILITY IN (''3'',''4'',''5'',''C'') THEN 0
                ELSE
                    CASE WHEN A.DATA_SOURCE = ''KTP'' AND NVL(A.RESERVED_AMOUNT_9,0) > 0 THEN NVL(A.RESERVED_AMOUNT_9,0) -- TREASURY - EFFECTIVE INTEREST ACCRUE
                         ELSE CASE WHEN A.CR_STAGE <> ''3'' THEN NVL(A.INTEREST_ACCRUED,0) ELSE 0 END
                    END
           END INTEREST_ACCRUED,
           CASE WHEN A.DATA_SOURCE IN (''CRD'',''BTRD'') OR (A.DATA_SOURCE = ''ILS'' AND A.PRODUCT_CODE LIKE ''B%'') THEN 1 ELSE NVL(D.COMMITMENT_FLAG,0) END COMMITMENT_FLAG
    FROM ' || V_OWNER || '.' || V_TABLESELECT1 || ' A
    JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' C ON C.PF_SEGMENT_ID = A.SEGMENT_RULE_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
    JOIN ' || V_OWNER || '.IFRS_EAD_RULES_CONFIG B ON C.EAD_MODEL_ID=B.PKID
    JOIN ' || V_OWNER || '.IFRS_MSTR_SEGMENT_RULES_HEADER H ON B.SEGMENTATION_ID=H.PKID
    LEFT JOIN (
          SELECT D1.DOWNLOAD_DATE, D1.ACCOUNT_NUMBER AS FACILITY_NUMBER, D1.RESERVED_AMOUNT_14 AS UNUSED_AMOUNT,
                SUM(NVL(D2.OUTSTANDING, 0) * NVL(D2.EXCHANGE_RATE,0)) AS SUM_OUTSTANDING,
                COUNT(1) AS NOA, MAX(D1.COMMITTED_FLAG) COMMITMENT_FLAG
            FROM ' || V_OWNER || '.' || V_TABLESELECT1 || ' D1
            JOIN ' || V_OWNER || '.' || V_TABLESELECT1 || ' D2
              ON D1.ACCOUNT_NUMBER = D2.FACILITY_NUMBER
             AND D1.DOWNLOAD_DATE = D2.DOWNLOAD_DATE
           WHERE D1.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND D1.DATA_SOURCE = ''LIMIT''
           GROUP BY D1.DOWNLOAD_DATE, D1.ACCOUNT_NUMBER, D1.RESERVED_AMOUNT_14
    ) D
    ON A.FACILITY_NUMBER = D.FACILITY_NUMBER
    AND A.DOWNLOAD_DATE = D.DOWNLOAD_DATE
    WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND C.ECL_MODEL_ID = ' || V_MODEL_ID || '
    AND (A.ACCOUNT_STATUS = ''A'' OR (A.DATA_SOURCE = ''CRD'' AND A.ACCOUNT_STATUS = ''C'' AND A.OUTSTANDING > 0))
    AND NOT ((A.DATA_SOURCE = ''BTRD'' AND RESERVED_FLAG_1 = 0) OR (A.DATA_SOURCE IN(''PBMM'', ''KTP'') AND A.SEGMENT = ''PBMM'' AND A.RESERVED_FLAG_1 = 0) OR A.DATA_SOURCE = ''LIMIT'')
    AND NVL(A.IS_IMPAIRED,0) = 1

    UNION ALL

    SELECT A.DOWNLOAD_DATE,
           A.MASTERID,
           A.CURRENCY,
           A.EXCHANGE_RATE,
           ' || V_MODEL_ID || ' AS ECL_MODEL_ID,
           A.CR_STAGE,
           A.DATA_SOURCE,
           A.SEGMENT_RULE_ID,
           C.EAD_MODEL_ID AS EAD_RULE_ID,
           H.SUB_SEGMENT AS EAD_SEGMENT,
           C.CCF_RULES_ID,
           C.PREPAYMENT_RULES_ID,
           CASE WHEN NVL(A.LOAN_DUE_DATE,''1-JAN-1900'') > TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') THEN ROUND(MONTHS_BETWEEN(A.LOAN_DUE_DATE, TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''))) ELSE 12 END AS LIFETIME,
           A.LOAN_START_DATE,
           A.LOAN_DUE_DATE,
           A.NEXT_PAYMENT_DATE,
           A.LAST_PAYMENT_DATE,
           CASE WHEN A.CR_STAGE = ''3'' AND NOT (A.DATA_SOURCE = ''BTRD'' OR (A.DATA_SOURCE = ''ILS'' AND A.PRODUCT_CODE LIKE ''%B'')) THEN 0 --CCF ONLY APPLIED TO STAGE 1 AND 2
                WHEN A.DATA_SOURCE = ''LIMIT'' THEN NVL(A.RESERVED_AMOUNT_14,0)
                WHEN A.DATA_SOURCE IN(''PBMM'', ''KTP'') AND A.SEGMENT = ''PBMM'' THEN NVL(A.RESERVED_AMOUNT_14,0)
                ELSE NVL(A.OUTSTANDING, 0)
           END AS UNUSED_AMOUNT,
           0 AS OUTSTANDING,
           NVL(A.REVOLVING_FLAG,0) REVOLVING_FLAG,
           B.EAD_BALANCE,
           A.UNAMORT_FEE_AMT,
           A.RESERVED_AMOUNT_13 AS MARKET_AMOUNT,
           0 AS INTEREST_ACCRUED,
           CASE WHEN DATA_SOURCE = ''LIMIT'' THEN A.COMMITTED_FLAG ELSE 1 END AS COMMITMENT_FLAG
    FROM ' || V_OWNER || '.' || V_TABLESELECT1 || ' A
    JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' C ON C.PF_SEGMENT_ID = A.SEGMENT_RULE_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
    JOIN ' || V_OWNER || '.IFRS_EAD_RULES_CONFIG B ON C.EAD_MODEL_ID=B.PKID
    JOIN ' || V_OWNER || '.IFRS_MSTR_SEGMENT_RULES_HEADER H ON B.SEGMENTATION_ID=H.PKID
    WHERE A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND C.ECL_MODEL_ID = ' || V_MODEL_ID || '
    AND A.ACCOUNT_STATUS = ''A''
    AND ((A.DATA_SOURCE IN(''BTRD'',''LIMIT'') AND A.RESERVED_FLAG_1 = 0) OR (A.DATA_SOURCE IN(''PBMM'', ''KTP'') AND A.SEGMENT = ''PBMM'' AND A.RESERVED_FLAG_1 = 0))
    AND NVL(A.IS_IMPAIRED,0) = 1';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX ' || V_OWNER || '.IDX_IFRS_PAYM_SCHD_ALL_3';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1418 THEN   -- INDEX DOES NOT EXIST
                RAISE;
            END IF;
    END;

    EXECUTE IMMEDIATE '
    CREATE INDEX ' || V_OWNER || '.IDX_IFRS_PAYM_SCHD_ALL_3
    ON ' || V_OWNER || '.IFRS_PAYM_SCHD_ALL
    (DOWNLOAD_DATE, MASTERID, PMTDATE)
    NOLOGGING';
    

    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS DOWNLOAD_DATE,
        A.MASTERID,
        TO_DATE(''' || TO_CHAR(V_EOM,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS PMTDATE,
        A.OUTSTANDING OSPRN,
        0 PRINCIPAL,
        0 INTEREST,
        1 COUNTER
    FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD A
    WHERE CR_STAGE IN (''1'',''3'')
    AND DATA_SOURCE NOT IN (''BTRD'',''KTP'',''RKN'')';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MAX';


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MAX(MASTERID, CR_STAGE)
    SELECT A.MASTERID, A.CR_STAGE
    FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD A
    JOIN ' || V_OWNER || '.BCA_TMP B
    ON A.MASTERID = B.MASTERID
    AND A.CR_STAGE = ''2''
    GROUP BY A.MASTERID, A.CR_STAGE';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    FROM
    (
        SELECT TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS DOWNLOAD_DATE,
            MASTERID,
            PMTDATE,
            OSPRN,
            PRINCIPAL,
            INTEREST,
            ROW_NUMBER() OVER (PARTITION BY MASTERID ORDER BY PMTDATE, COUNTER) COUNTER,
            CR_STAGE
        FROM
        (
            SELECT
                A.MASTERID,
                TO_DATE(''' || TO_CHAR(V_EOM,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS PMTDATE,
                A.OUTSTANDING OSPRN,
                0 PRINCIPAL,
                0 INTEREST,
                1 COUNTER,
                B.CR_STAGE
            FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD A
            JOIN ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MAX B
            ON A.MASTERID = B.MASTERID
            UNION ALL
            SELECT
                A.MASTERID,
                A.PMTDATE,
                A.OSPRN,
                A.PRINCIPAL,
                A.INTEREST,
                A.COUNTER,
                B.CR_STAGE
            FROM ' || V_OWNER || '.BCA_TMP A
            JOIN ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MAX B
            ON A.MASTERID = B.MASTERID
            AND A.PMTDATE > TO_DATE(''' || TO_CHAR(V_EOM,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
        )
    ) A';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    EXECUTE IMMEDIATE 'DROP INDEX ' || V_OWNER || '.IDX_IFRS_PAYM_SCHD_ALL_3';


    V_STR_QUERY := 'MERGE INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP A
    USING
    (
        SELECT A.MASTERID,
            A.COUNTER,
            CASE WHEN B.OUTSTANDING - SUM(CASE WHEN A.COUNTER = 1 THEN 0 ELSE A.PRINCIPAL END) OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER ASC) < 0 THEN
                0
            ELSE
                B.OUTSTANDING - SUM(CASE WHEN A.COUNTER = 1 THEN 0 ELSE A.PRINCIPAL END) OVER (PARTITION BY A.MASTERID ORDER BY A.COUNTER ASC)
            END AS NEW_OS
        FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP A
        JOIN ' || V_OWNER || '.TMP_IFRS_IMA_EAD B
        ON A.MASTERID = B.MASTERID
    ) B
    ON (A.MASTERID = B.MASTERID AND A.COUNTER = B.COUNTER)
    WHEN MATCHED THEN
    UPDATE SET
        A.OSPRN = B.NEW_OS';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MIN_MAX
    (
        MASTERID,
        MIN_PMTDATE,
        MAX_PMTDATE
    )
    SELECT MASTERID,
        MIN(PMTDATE) MIN_PMTDATE,
        MAX(PMTDATE) MAX_PMTDATE
    FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    GROUP BY MASTERID';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
    (
        DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    )
    SELECT DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    WHERE MASTERID IN
    (
        SELECT A.MASTERID
        FROM
        (
            SELECT MASTERID, COUNT(*) AS COUNT_A
            FROM (SELECT DISTINCT MASTERID, PMTDATE FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP)
            GROUP BY MASTERID
        ) A
        JOIN
        (
            SELECT MASTERID, MONTHS_BETWEEN(MAX_PMTDATE, MIN_PMTDATE) + 1 AS COUNT_A
            FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MIN_MAX
        ) B
        ON (A.MASTERID = B.MASTERID AND A.COUNT_A != B.COUNT_A)
    )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
    (
        DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    )
    SELECT A.DOWNLOAD_DATE,
        A.MASTERID,
        C.PMTDATE,
        A.OSPRN,
        0 PRINCIPAL,
        0 INTEREST,
        0 COUNTER
    FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING A
    JOIN ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING B
    ON A.MASTERID = B.MASTERID
    AND A.COUNTER = B.COUNTER - 1
    JOIN
    (
        SELECT ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), ROWNUM-1) PMTDATE,
            ROWNUM MONTHS
        FROM DUAL
        CONNECT BY ROWNUM <=
        (
            SELECT MONTHS_BETWEEN(MAX(PMTDATE), MIN(PMTDATE)) + 1
            FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
        )
    ) C
    ON C.PMTDATE > A.PMTDATE AND C.PMTDATE < B.PMTDATE
    ORDER BY A.MASTERID, C.PMTDATE';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'MERGE INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING A
    USING
    (
        SELECT ROW_NUMBER() OVER (PARTITION BY MASTERID ORDER BY PMTDATE,COUNTER) AS NEW_COUNTER,
            MASTERID,
            PMTDATE,
            COUNTER
        FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
    ) B
    ON (A.MASTERID = B.MASTERID AND A.PMTDATE = B.PMTDATE)
    WHEN MATCHED THEN
    UPDATE SET
        A.COUNTER = B.NEW_COUNTER
    WHERE A.COUNTER = B.COUNTER';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    V_STR_QUERY := 'DELETE FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
    WHERE COUNTER > 12
    AND MASTERID IN
    (SELECT MASTERID FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD WHERE CR_STAGE = ''1'')';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'DELETE FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    WHERE MASTERID IN
    (
        SELECT DISTINCT MASTERID
        FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MISSING
    )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    (
        DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    )
    SELECT DOWNLOAD_DATE,
        MASTERID,
        PMTDATE,
        OSPRN,
        PRINCIPAL,
        INTEREST,
        COUNTER
    FROM TMP_IFRS_PAYM_SCHD_MISSING';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP
    (
    DOWNLOAD_DATE,
    MASTERID,
    PMTDATE,
    OSPRN,
    PRINCIPAL,
    INTEREST,
    COUNTER
    )
    SELECT  TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS DOWNLOAD_DATE,
            A.MASTERID,
            ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), (G.MONTHS-1)) AS PMTDATE,
            A.OUTSTANDING AS OSPRN,
            0 AS  PRINCIPAL,
            0 AS INTEREST,
            ROW_NUMBER() OVER (PARTITION BY A.MASTERID ORDER BY G.MONTHS)
    FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD A
    INNER JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' F ON A.DOWNLOAD_DATE = F.DOWNLOAD_DATE AND A.ECL_MODEL_ID = F.ECL_MODEL_ID AND A.SEGMENT_RULE_ID = F.PF_SEGMENT_ID AND A.EAD_RULE_ID = F.EAD_MODEL_ID
    LEFT JOIN ' || V_OWNER || '.IFRS_LIFETIME_HEADER L ON F.LT_EFF_DATE =L.DOWNLOAD_DATE AND F.LT_RULE_ID=L.LIFETIME_CONFIG_ID
    LEFT JOIN (
        SELECT ROWNUM MONTHS FROM DUAL
        CONNECT BY ROWNUM <=
        (
            SELECT MAX(LIFETIME_PERIOD)
            FROM ' || V_OWNER || '.IFRS_LIFETIME_HEADER A
            JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' B
            ON A.LIFETIME_CONFIG_ID = B.LT_RULE_ID
            AND A.DOWNLOAD_DATE = B.LT_EFF_DATE
            AND B.ECL_MODEL_ID = ' || V_MODEL_ID || '
            AND B.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_EOM,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
        )
    ) G ON ((NVL(A.REVOLVING_FLAG,0) = 1 AND A.CR_STAGE = ''1'' AND G.MONTHS <= 1) OR (A.CR_STAGE > ''1'' AND NVL(A.REVOLVING_FLAG,0) = 1 AND G.MONTHS <= NVL(L.LIFETIME_PERIOD, 12))
             OR (NVL(A.REVOLVING_FLAG,0) = 0 AND G.MONTHS <= LEAST(CASE WHEN L.LIFETIME_PERIOD < 12 THEN 12 ELSE L.LIFETIME_PERIOD END, CASE WHEN A.CR_STAGE = ''1'' AND A.LIFETIME_PERIOD >=12 THEN 12 ELSE A.LIFETIME_PERIOD END)))
    OR (A.DATA_SOURCE IN (''BTRD'') AND G.MONTHS <= NVL(A.LIFETIME_PERIOD, 12) )
    OR (A.DATA_SOURCE IN (''KTP'') AND A.NEXT_PAYMENT_DATE IS NOT NULL
        AND G.MONTHS <= (ROUND((MONTHS_BETWEEN(A.LOAN_DUE_DATE, A.NEXT_PAYMENT_DATE)))/ ROUND((MONTHS_BETWEEN(A.NEXT_PAYMENT_DATE, A.LAST_PAYMENT_DATE)))) + 1  )
    OR (A.DATA_SOURCE IN (''PBMM'',''KTP'') AND A.NEXT_PAYMENT_DATE IS NULL AND G.MONTHS <= (CASE WHEN F.SEGMENT = ''PBMM'' THEN 12 ELSE LEAST(CASE WHEN L.LIFETIME_PERIOD = 0 THEN 12 ELSE L.LIFETIME_PERIOD END, A.LIFETIME_PERIOD) END))
    OR (A.DATA_SOURCE IN (''RKN'') AND G.MONTHS <= NVL(A.LIFETIME_PERIOD, 1))
    WHERE F.ECL_MODEL_ID = ' || V_MODEL_ID || '
    AND NOT EXISTS (SELECT * FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP C WHERE A.MASTERID=C.MASTERID)';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


   V_STR_QUERY := 'MERGE INTO ' || V_OWNER || '.TMP_IFRS_IMA_EAD X
    USING(
    SELECT C.DOWNLOAD_DATE,C.MASTERID,C.SEGMENT_RULE_ID,C.EAD_SEGMENT,D.PKID CCF_RULE_ID FROM (
    SELECT A.*, B.SEGMENTATION_ID FROM
    (SELECT * FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD
    ) A
    JOIN ' || V_OWNER || '.IFRS_CCF_RULES_CONFIG B
    ON A.CCF_RULE_ID = B.PKID ) C
    JOIN (SELECT * FROM ' || V_OWNER || '.IFRS_CCF_RULES_CONFIG WHERE ACTIVE_FLAG = 1) D
    ON C.SEGMENTATION_ID = D.SEGMENTATION_ID )Y
    ON (X.MASTERID = Y.MASTERID)
    WHEN MATCHED THEN UPDATE
    SET X.CCF_RULE_ID = Y.CCF_RULE_ID';

    EXECUTE IMMEDIATE V_STR_QUERY;  
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TABLEINSERT1 || '
    (
    PKID,
    DOWNLOAD_DATE,
    MASTERID,
    CURRENCY,
    EXCHANGE_RATE,
    ECL_MODEL_ID,
    CR_STAGE,
    EAD_RULE_ID,
    EAD_SEGMENT,
    CCF_RULE_ID,
    PREPAYMENT_RULE_ID,
    UNUSED_AMOUNT,
    REVOLVING_FLAG,
    MARKET_AMOUNT,
    INTEREST_ACCRUED,
    CCF_RATE,
    CCF_AMOUNT,
    PREPAYMENT_RATE,
    PREPAYMENT_AMOUNT,
    OUTSTANDING,
    UNAMORT_FEE_COST,
    FAIRVALUE,
    PMTDATE,
    EAD_AMOUNT,
    COUNTER,
    MAX_COUNTER,
    CREATEDDATE,
    CREATEDBY
    )
    SELECT 
            0,
            A.DOWNLOAD_DATE,
            A.MASTERID,
            A.CURRENCY,
            A.EXCHANGE_RATE,
            ' || V_MODEL_ID || ' AS ECL_MODEL_ID,
            A.CR_STAGE,
            A.EAD_RULE_ID,
            A.EAD_SEGMENT,
            A.CCF_RULE_ID,
            A.PREPAYMENT_RULE_ID,
            NVL(A.UNUSED_AMOUNT,0) AS UNUSED_AMOUNT,
            A.REVOLVING_FLAG,
            A.MARKET_AMOUNT,
            CASE WHEN COALESCE(E.COUNTER,1)=1 AND A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN A.INTEREST_ACCRUED ELSE 0 END AS INTEREST_ACCRUED,
            B.CCF_RATE,
            CASE
                WHEN A.CCF_RULE_ID IS NOT NULL
                    AND ((F.CCF_REVOLVING_FLAG LIKE ''%'' || A.REVOLVING_FLAG || ''%'' )  AND
                        (F.CCF_COMMITED_FLAG LIKE ''%'' || A.COMMITMENT_FLAG || ''%''))
                THEN (B.CCF_RATE*A.UNUSED_AMOUNT)
                ELSE 0
            END AS CCF_AMOUNT,
            C.PREPAYMENT_RATE,
            CASE WHEN (CASE  WHEN A.EAD_BALANCE LIKE ''CV%'' OR ((A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE ''%UNAMORT_FEE_COST%'' AND A.EAD_BALANCE NOT LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN (''2'', ''3'')  THEN 0 ELSE COALESCE(C.PREPAYMENT_RATE,0) END) < 0 THEN 0
            ELSE
            (CASE  WHEN A.EAD_BALANCE LIKE ''CV%'' OR ((A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END+COALESCE(A.UNAMORT_FEE_AMT,0) ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE ''%UNAMORT_FEE_COST%'' AND A.EAD_BALANCE NOT LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN (''2'', ''3'')  THEN 0 ELSE COALESCE(C.PREPAYMENT_RATE,0) END) END AS PREPAYMENT_AMOUNT,
            CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END AS OUTSTANDING,
            CASE WHEN A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''CV%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%''
                 THEN COALESCE(A.UNAMORT_FEE_AMT,0)
                 ELSE 0 END AS UNAMORT_FEE_COST,
            CASE  WHEN A.EAD_BALANCE LIKE ''CV%''
                      OR ((A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE ''%UNAMORT_FEE_COST%'' AND A.EAD_BALANCE NOT LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END AS FAIRVALUE,
            E.PMTDATE AS PMTDATE,
            (CASE  WHEN A.EAD_BALANCE LIKE ''CV%'' OR ((A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE ''%UNAMORT_FEE_COST%'' AND A.EAD_BALANCE NOT LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END)
            - (CASE  WHEN A.EAD_BALANCE LIKE ''CV%'' OR ((A.EAD_BALANCE LIKE ''%UNAMORT_FEE_COST%'' OR A.EAD_BALANCE LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN CASE WHEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN A.OUTSTANDING + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE A.OUTSTANDING END ELSE CASE WHEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) > 0 THEN COALESCE(E.OSPRN,A.OUTSTANDING) + COALESCE(A.UNAMORT_FEE_AMT,0) ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END END ELSE 0 END
                  WHEN ((A.EAD_BALANCE NOT LIKE ''%UNAMORT_FEE_COST%'' AND A.EAD_BALANCE NOT LIKE ''%UNAMORT_DISC_PREM%'') AND A.EAD_BALANCE LIKE ''OS%'')
                  THEN CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0 THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END
                  ELSE 0
                  END
            * CASE WHEN A.PREPAYMENT_RULE_ID IS NULL OR A.CR_STAGE IN (''2'', ''3'') THEN 0 ELSE COALESCE(C.PREPAYMENT_RATE,0) END)
            +CASE WHEN A.EAD_BALANCE LIKE ''%ACCRUED_INT%'' AND COALESCE(E.COUNTER,1)=1 AND CASE WHEN A.OUTSTANDING > 0 AND COALESCE(E.OSPRN,A.OUTSTANDING) > 0  THEN CASE WHEN E.OSPRN > A.OUTSTANDING THEN A.OUTSTANDING ELSE COALESCE(E.OSPRN,A.OUTSTANDING) END ELSE 0 END > 0 THEN NVL(A.INTEREST_ACCRUED,0) ELSE 0 END
            +CASE WHEN A.EAD_BALANCE LIKE ''%MARKET_VALUE%'' THEN A.MARKET_AMOUNT ELSE 0 END
            +CASE
                WHEN A.CCF_RULE_ID IS NOT NULL
                    AND ((F.CCF_REVOLVING_FLAG LIKE ''%''|| A.REVOLVING_FLAG || ''%'' )  AND
                        (F.CCF_COMMITED_FLAG LIKE ''%''|| A.COMMITMENT_FLAG || ''%''))
                THEN (B.CCF_RATE*A.UNUSED_AMOUNT)
                ELSE 0
             END AS EAD_AMOUNT,
            ROW_NUMBER() OVER (PARTITION BY A.DOWNLOAD_DATE,A.MASTERID ORDER BY E.COUNTER) AS RN,
            SUM(1) OVER (PARTITION BY A.DOWNLOAD_DATE,A.MASTERID) AS MAX_COUNTER,
            SYSTIMESTAMP,
            ''' || V_SP_NAME || ''' AS SP_NAME
    FROM ' || V_OWNER || '.TMP_IFRS_IMA_EAD A
    INNER JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' F  ON A.DOWNLOAD_DATE = F.DOWNLOAD_DATE AND A.ECL_MODEL_ID = F.ECL_MODEL_ID AND A.SEGMENT_RULE_ID = F.PF_SEGMENT_ID AND A.EAD_RULE_ID = F.EAD_MODEL_ID
    LEFT JOIN ' || V_OWNER || '.IFRS_CCF_HEADER B         ON B.DOWNLOAD_DATE=F.CCF_EFF_DATE AND A.CCF_RULE_ID=B.CCF_RULE_ID
    LEFT JOIN ' || V_OWNER || '.IFRS_PREPAYMENT_HEADER C  ON C.DOWNLOAD_DATE=F.PREPAYMENT_EFF_DATE AND A.PREPAYMENT_RULE_ID=C.PREPAYMENT_RULE_ID
    LEFT JOIN ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_IMP E  ON A.MASTERID=E.MASTERID
    WHERE F.ECL_MODEL_ID = ' || V_MODEL_ID || '';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'MERGE INTO ' || V_OWNER || '.' || V_TABLEINSERT1 || ' A
    USING
    (
        SELECT A2.MASTERID,
		CASE WHEN B2.CR_STAGE = ''3'' THEN
			NVL(D2.LIFETIME_PERIOD, 12)
	    ELSE
			CASE WHEN B2.LIFETIME_PERIOD > 12 THEN 12 ELSE B2.LIFETIME_PERIOD END
		END LIFETIME_PERIOD
		FROM ' || V_OWNER || '.TMP_IFRS_PAYM_SCHD_MIN_MAX A2
        JOIN ' || V_OWNER || '.TMP_IFRS_IMA_EAD B2
        ON A2.MASTERID = B2.MASTERID
		JOIN ' || V_OWNER || '.' || V_TABLECONFIG || ' C2
		ON B2.DOWNLOAD_DATE = C2.DOWNLOAD_DATE
		AND B2.ECL_MODEL_ID = C2.ECL_MODEL_ID
		AND B2.SEGMENT_RULE_ID = C2.PF_SEGMENT_ID
		LEFT JOIN ' || V_OWNER || '.IFRS_LIFETIME_HEADER D2
		ON C2.LT_EFF_DATE = D2.DOWNLOAD_DATE
		AND C2.LT_RULE_ID = D2.LIFETIME_CONFIG_ID
        WHERE
		(
		  B2.CR_STAGE = ''1''
		  OR
		  (B2.CR_STAGE = ''2'' AND B2.LIFETIME_PERIOD >= 12 AND ROUND(MONTHS_BETWEEN(A2.MAX_PMTDATE,TO_DATE(''' || TO_CHAR(V_EOM,'YYYY-MM-DD') || ''',''YYYY-MM-DD''))) < 12)
		  OR
		  (B2.CR_STAGE = ''3'' AND NVL(B2.REVOLVING_FLAG,0) = 1)
		)
    ) B
    ON (A.DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND A.MASTERID = B.MASTERID)
    WHEN MATCHED THEN
        UPDATE SET A.MAX_COUNTER = B.LIFETIME_PERIOD';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    ----------------------------------------------------------------
    -- MAIN PROCESSING
    ----------------------------------------------------------------

    
    DBMS_OUTPUT.PUT_LINE('PROCEDURE ' || V_SP_NAME || ' EXECUTED SUCCESSFULLY.');

    ----------------------------------------------------------------
    -- LOG: CALL EXEC_AND_LOG (ASSUMED SIGNATURE)
    ----------------------------------------------------------------
    V_TABLEDEST := V_OWNER || '.' || V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';

    IFRS9_BCA.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

    ----------------------------------------------------------------
    -- RESULT PREVIEW
    ----------------------------------------------------------------
    V_QUERYS := 'SELECT * FROM ' || V_OWNER || '.' || V_TABLEINSERT1 ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (' || CASE WHEN V_MODEL_ID = '0' THEN '1=1' ELSE 'PD_RULE_ID = ' || V_MODEL_ID END || ')';

    IFRS9_BCA.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        IF C_RULE%ISOPEN THEN
            CLOSE C_RULE;
        END IF;

        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;