CREATE OR REPLACE PROCEDURE IFRS9_BCA.SP_IFRS_ECL_IA_INITIAL_RUN_BCA (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE     DEFAULT NULL,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    ----------------------------------------------------------------
    -- VARIABLES
    ----------------------------------------------------------------
    V_SP_NAME     VARCHAR2(100) := 'SP_IFRS_ECL_IA_INITIAL_RUN_BCA';
    V_OWNER       VARCHAR2(30);
    V_CURRDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);
    V_COUNT         NUMBER;

    -- DYNAMIC SQL (USE VARCHAR2 LARGE)
    V_STR_QUERY     VARCHAR2(32767);

    -- TABLE NAMES (UNQUALIFIED PARTS)
    V_TABLEINSERT1  VARCHAR2(100);
    V_TABLEINSERT2  VARCHAR2(100);
    V_TABLEINSERT3  VARCHAR2(100);
    V_TABLEINSERT4  VARCHAR2(100);
    V_TABLEINSERT5  VARCHAR2(100);
    V_TABLESELECT1  VARCHAR2(100);
    V_TABLECONFIG   VARCHAR2(100);


    -- CURSOR
    TYPE REF_CURSOR IS REF CURSOR;
    C_RULE        REF_CURSOR;

    -- FETCH VARIABLES
    V_RULE_ID     VARCHAR2(250);
    V_RULE_TYPE VARCHAR2(25);
    V_TABLE_NAME  VARCHAR2(100);
    V_PD_RULES_QRY_RESULT CLOB;


    -- MISC
    V_RETURNROWS    NUMBER := 0;
    V_RETURNROWS2   NUMBER := 0;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);
    V_RUNID        VARCHAR2(30);
    V_SYSCODE      VARCHAR2(10);
    V_PRC         VARCHAR2(5);

    -- RESULT QUERY
    V_QUERYS        CLOB;


BEGIN

    ----------------------------------------------------------------
    -- GET OWNER
    ----------------------------------------------------------------
    SELECT USERNAME INTO V_OWNER FROM USER_USERS;

    ----------------------------------------------------------------
    -- INSERT VCURRDATE DETERMINATION IF NULL
    ----------------------------------------------------------------
    IF P_DOWNLOAD_DATE IS NULL THEN
        BEGIN
            SELECT CURRDATE INTO V_CURRDATE FROM IFRS9_BCA.IFRS_PRC_DATE_AMORT;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20010, 'IFRS_PRC_DATE_AMORT HAS NO CURRDATE ROW');
        END;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_RUNID := NVL(P_RUNID, 'P_00000_0000');
    V_SYSCODE := NVL(P_SYSCODE, '0');
    V_MODEL_ID := V_SYSCODE;
    V_PRC := NVL(P_PRC, 'P');

    ----------------------------------------------------------------
    -- TABLE DETERMINATION
    ----------------------------------------------------------------
    IF V_PRC = 'S' THEN 
        V_TABLEINSERT1 := 'TBLT_PAYMENTEXPECTED_' || V_RUNID;
        V_TABLEINSERT2 := 'TBLT_PAYMENTEXPECTEDH_' || V_RUNID;
        V_TABLEINSERT3 := 'IFRS_IA_OVERRIDED_' || V_RUNID;
        V_TABLEINSERT4 := 'IFRS_IA_OVERRIDEH_' || V_RUNID;
        V_TABLEINSERT5 := 'IFRS_IA_OVERRIDEH_HIST_' || V_RUNID;
    ELSE 
        V_TABLEINSERT1 := 'TBLT_PAYMENTEXPECTED';
        V_TABLEINSERT2 := 'TBLT_PAYMENTEXPECTEDH';
        V_TABLEINSERT3 := 'IFRS_IA_OVERRIDED';
        V_TABLEINSERT4 := 'IFRS_IA_OVERRIDEH';
        V_TABLEINSERT5 := 'IFRS_IA_OVERRIDEH_HIST';
    END IF;

    IFRS9_BCA.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, V_RUNID, TO_NUMBER(SYS_CONTEXT('USERENV','SESSIONID')), SYSDATE);
    COMMIT;

    ----------------------------------------------------------------
    -- PRE-PROCESSING SIMULATION TABLES
    ----------------------------------------------------------------
    IF V_PRC = 'S' THEN
        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT1 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.TBLT_PAYMENTEXPECTED WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;


        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT2);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT2;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT2 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.TBLT_PAYMENTEXPECTEDH WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;


        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT3);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT3;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT3 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.IFRS_IA_OVERRIDED WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;


        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT4);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT4;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT4 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;


        -- DROP TABLE IF EXISTS
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT5);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_OWNER || '.' || V_TABLEINSERT5;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_OWNER || '.' || V_TABLEINSERT5 ||
                       ' AS SELECT * FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH_HIST WHERE DOWNLOAD_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AND 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
    END IF;
    COMMIT;

    ----------------------------------------------------------------
    -- MAIN PROCESSING
    ----------------------------------------------------------------

    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TABLEINSERT1 || '
    (
        PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        ESTIMATED_REALIZE_DATE,
        ESTIMATED_PRIN_AMOUNT,
        ESTIMATED_INT_AMOUNT,
        ESTIMATED_COLL_AMOUNT,
        ESTIMATED_AMOUNT,
        DISCOUNT_RATE,
        EIR,
        INTEREST_RATE,
        PV_MONTH,
        PV_AMOUNT,
        ECL_AMOUNT,
        BEGIN_BALANCE,
        INTEREST_UNWINDING,
        ENDING_BALANCE,
        UNWIND_BALANCE,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT
        0 PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        ESTIMATED_REALIZE_DATE,
        ESTIMATED_PRIN_AMOUNT,
        ESTIMATED_INT_AMOUNT,
        ESTIMATED_COLL_AMOUNT,
        ESTIMATED_AMOUNT,
        DISCOUNT_RATE,
        EIR,
        INTEREST_RATE,
        PV_MONTH,
        PV_AMOUNT,
        ECL_AMOUNT,
        BEGIN_BALANCE,
        INTEREST_UNWINDING,
        ENDING_BALANCE,
        UNWIND_BALANCE,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM ' || V_OWNER || '.TBLT_PAYMENTEXPECTED_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = ''C''
        AND RESERVED_DATE_2 = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
    )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TABLEINSERT2 || '
    (
        PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        CURRENCY,
        OUTSTANDING,
        EAD,
        COLLATERAL_AMOUNT,
        PV_AMOUNT,
        ECL_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT 0 PKID,
        OVERRIDEID,
        EFFECTIVE_DATE,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        CURRENCY,
        OUTSTANDING,
        EAD,
        COLLATERAL_AMOUNT,
        PV_AMOUNT,
        ECL_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM ' || V_OWNER || '.TBLT_PAYMENTEXPECTEDH_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = ''C''
        AND RESERVED_DATE_2 = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
    )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TABLEINSERT3 || '
    SELECT * FROM ' || V_OWNER || '.IFRS_IA_OVERRIDED_HIST
    WHERE OVERRIDEID IN
    (
        SELECT PKID FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH_HIST
        WHERE RESERVED_VARCHAR_1 = ''C''
        AND RESERVED_DATE_2 = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
    )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TABLEINSERT4 || '
    SELECT * FROM ' || V_OWNER || '.IFRS_IA_OVERRIDEH_HIST
    WHERE RESERVED_VARCHAR_1 = ''C''
    AND RESERVED_DATE_2 = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    V_STR_QUERY := 'UPDATE ' || V_OWNER || '.' || V_TABLEINSERT5 || '
    SET RESERVED_VARCHAR_1 = NULL,
        RESERVED_DATE_1 = NULL,
        RESERVED_DATE_2 = NULL
    WHERE RESERVED_VARCHAR_1 = ''C''
    AND RESERVED_DATE_2 = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;


    ----------------------------------------------------------------
    -- MAIN PROCESSING
    ----------------------------------------------------------------

    
    DBMS_OUTPUT.PUT_LINE('PROCEDURE ' || V_SP_NAME || ' EXECUTED SUCCESSFULLY.');

    ----------------------------------------------------------------
    -- LOG: CALL EXEC_AND_LOG (ASSUMED SIGNATURE)
    ----------------------------------------------------------------
    V_TABLEDEST := V_OWNER || '.' || V_TABLEINSERT1;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';

    IFRS9_BCA.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

    ----------------------------------------------------------------
    -- RESULT PREVIEW
    ----------------------------------------------------------------
    V_QUERYS := 'SELECT * FROM ' || V_OWNER || '.' || V_TABLEINSERT1 ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (' || CASE WHEN V_MODEL_ID = '0' THEN '1=1' ELSE 'PD_RULE_ID = ' || V_MODEL_ID END || ')';

    IFRS9_BCA.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), V_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        IF C_RULE%ISOPEN THEN
            CLOSE C_RULE;
        END IF;

        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;