CREATE OR REPLACE FUNCTION PSAK413.FN_NORMALIZE_CONDITION (
    P_CONDITION IN VARCHAR2
) RETURN VARCHAR2
AS
    V_RESULT VARCHAR2(4000);
BEGIN
    -- 1. Uppercase semua
    V_RESULT := UPPER(P_CONDITION);

    -- 2. Replace prefix table
    V_RESULT := REPLACE(V_RESULT, 'IFRS_MASTER_ACCOUNT.', 'A.');

    RETURN V_RESULT;
END;