DROP TABLE IF EXISTS IFRS_LIFETIME_OVERRIDE;

CREATE TABLE IF NOT EXISTS IFRS_LIFETIME_OVERRIDE (
  PKID SERIAL PRIMARY KEY,
  LIFETIME_CONFIGURATION VARCHAR(250) NOT NULL,
  SEGMENTATION_ID INT NOT NULL,
  SEGMENTATION VARCHAR(100) NOT NULL,
  DOWNLOAD_DATE DATE NOT NULL,
  LIFETIME_RATE REAL NOT NULL,
  LIFETIME_OVERRIDE REAL NOT NULL,
  CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
  UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE
)