DROP TABLE IF EXISTS IFRS_LIFETIME_RULES_CONFIG;

CREATE TABLE IF NOT EXISTS IFRS_LIFETIME_RULES_CONFIG (
	PKID SERIAL PRIMARY KEY,
	LIFETIME_RULE_NAME VARCHAR(250) NOT NULL,
	SEGMENTATION_ID INT NOT NULL,
	LIFETIME_OVERRIDE REAL DEFAULT 0,
	ACTIVE_FLAG INT DEFAULT 1,
	IS_DELETE INT DEFAULT 0,
	CREATEDBY VARCHAR(50) DEFAULT 'system',
	CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
	CREATEDHOST VARCHAR(50) DEFAULT 'localhost',
	UPDATEDBY VARCHAR(50) NULL,
	UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE,
	UPDATEDHOST VARCHAR(50) NULL
)