CREATE TABLE IF NOT EXISTS SYSTEM_LOG_MAINTENANCE (
    LOG_ID SERIAL PRIMARY KEY,
    DB_NAME TEXT NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DURATION_SECONDS NUMERIC(10,2),
    DB_SIZE TEXT,
    STATUS TEXT,
    MESSAGE TEXT,
    CREATED_AT TIMESTAMP DEFAULT NOW()
);
