DROP TABLE IF EXISTS IFRS_PREPAYMENT_OVERRIDE;

CREATE TABLE IF NOT EXISTS IFRS_PREPAYMENT_OVERRIDE (
  PKID SERIAL PRIMARY KEY,
  PREPAYMENT_CONFIGURATION VARCHAR(250) NOT NULL,
  SEGMENTATION_ID INT NOT NULL,
  SEGMENTATION VARCHAR(100) NOT NULL,
  DOWNLOAD_DATE DATE NOT NULL,
  PREPAYMENT_RATE REAL NOT NULL,
  PREPAYMENT_OVERRIDE REAL NOT NULL,
  CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
  UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE
)