SELECT line, position, text
FROM user_errors
WHERE name = 'SP_IFRS_CCF_RULES_CONFIG'
ORDER BY line;

--ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE ADD SYSCODE_LIFETIME VARCHAR2(22) NOT NULL;

CALL PSAK413.SP_IFRS_LIFETIME_RULES_CONFIG();


--- TRUNCATE TABLE IFRS_LIFETIME_RULES_CONFIG
SELECT * FROM IFRS_LIFETIME_RULES_CONFIG;

--- TRUNCATE TABLE IFRS_LIFETIME_OVERRIDE
SELECT * FROM IFRS_LIFETIME_OVERRIDE;



---- ADD COLUMN IFRS_PREPAYMENT_RULES_CONFIG
ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG ADD SYSCODE_PREPAYMENT VARCHAR2(22) NOT NULL;

--TRUNCATE TABLE IFRS_PREPAYMENT_OVERRIDE

---- ADD COLUMN IFRS_PREPAYMENT_OVERRIDE
ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE ADD SYSCODE_PREPAYMENT VARCHAR2(22) NOT NULL;

--- EXECUTE SP
CALL PSAK413.SP_IFRS_PREPAYMENT_RULES_CONFIG();

--TRUNCATE TABLE IFRS_CCF_RULES_CONFIG

---- ADD COLUMN IFRS_CCF_RULES_CONFIG
ALTER TABLE PSAK413.IFRS_CCF_RULES_CONFIG ADD SYSCODE_CCF VARCHAR2(22) NOT NULL;


---- ADD COLUMN IFRS_CCF_OVERRIDE
ALTER TABLE PSAK413.IFRS_CCF_OVERRIDE ADD SYSCODE_CCF VARCHAR2(22) NOT NULL;

--- EXECUTE SP
CALL PSAK413.SP_IFRS_CCF_RULES_CONFIG();

