/*
---> LIFETIME

--- TRUNCATE TABLE IFRS_LIFETIME_RULES_CONFIG
SELECT * FROM IFRS_LIFETIME_RULES_CONFIG;

--- TRUNCATE TABLE IFRS_LIFETIME_OVERRIDE
SELECT * FROM IFRS_LIFETIME_OVERRIDE;

--- CREATE INDEX
CREATE UNIQUE INDEX UX_IFRS_LIFETIME_RULES ON IFRS_LIFETIME_RULES_CONFIG (SYSCODE_LIFETIME);

---- ADD COLUMN
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE ADD SYSCODE_LIFETIME VARCHAR2(22) NOT NULL;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN CREATEDBY TO CREATED_BY;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN CREATEDDATE TO CREATED_DATE;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN CREATEDHOST TO CREATED_HOST;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN UPDATEDBY TO UPDATED_BY;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN UPDATEDDATE TO UPDATED_DATE;
ALTER TABLE PSAK413.IFRS_LIFETIME_OVERRIDE RENAME COLUMN UPDATEDHOST TO UPDATED_HOST;



--- EXECUTE SP
CALL PSAK413.SP_IFRS_LIFETIME_RULES_CONFIG();




 */


---> PREPAYMENT

--- TRUNCATE TABLE IFRS_LIFETIME_RULES_CONFIG
--SELECT * FROM IFRS_PREPAYMENT_RULES_CONFIG;

--- TRUNCATE TABLE IFRS_LIFETIME_OVERRIDE
--SELECT * FROM IFRS_PREPAYMENT_OVERRIDE;

---- ADD COLUMN IFRS_PREPAYMENT_RULES_CONFIG
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG ADD SYSCODE_PREPAYMENT VARCHAR2(22) NOT NULL;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG RENAME COLUMN CREATEDBY TO CREATED_BY;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG RENAME COLUMN UPDATEDBY TO UPDATED_BY;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG RENAME COLUMN UPDATEDDATE TO UPDATED_DATE;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG DROP COLUMN UPDATEDHOST;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG DROP COLUMN CREATEDHOST;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_RULES_CONFIG RENAME COLUMN IS_DELETE TO IS_DELETED;


---- ADD COLUMN IFRS_PREPAYMENT_OVERRIDE
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE ADD SYSCODE_PREPAYMENT VARCHAR2(22) NOT NULL;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN CREATEDBY TO CREATED_BY;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN CREATEDHOST TO CREATED_HOST;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN UPDATEDBY TO UPDATED_BY;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN UPDATEDDATE TO UPDATED_DATE;
--ALTER TABLE PSAK413.IFRS_PREPAYMENT_OVERRIDE RENAME COLUMN UPDATEDHOST TO UPDATED_HOST;


--- EXECUTE SP
--CALL PSAK413.SP_IFRS_PREPAYMENT_RULES_CONFIG();



