CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_MAA_ENR (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS
    -- Dates / counters
    V_CURRDATE      DATE;
    V_PREVDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);
    V_COUNT         NUMBER;

    -- Dynamic SQL
    V_STR_QUERY     VARCHAR2(32767);

    -- Table names
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEINSERT1  VARCHAR2(100);
    V_TABLEINSERT2  VARCHAR2(100);
    V_TABLESELECT1  VARCHAR2(100);
    V_TABLEPDCONFIG VARCHAR2(100);

    -- misc
    V_RETURNROWS    NUMBER;
    V_RETURNROWS2   NUMBER;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);

    -- result query
    V_QUERYS        CLOB;
BEGIN
    -- set procedure name
    V_SP_NAME := 'SP_IFRS_PD_MAA_ENR';
    
    -- handle default download date
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
          INTO V_CURRDATE
          FROM PSAK413.IFRS_PRC_DATE; 
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    IF P_SYSCODE <> '0' THEN
   		V_MODEL_ID := '1';
    ELSE
    	V_MODEL_ID := '0';
    END IF;

    IF P_PRC = 'S' THEN
        V_TABLEINSERT1  := 'GTMP_PD_RUNNING_CONFIG_' || P_RUNID;
        V_TABLEINSERT2  := 'IFRS_PD_MAA_ENR_' || P_RUNID;
        V_TABLESELECT1  := 'IFRS_PD_MIGRATION_DETAIL_' || P_RUNID;
        V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG_' || P_RUNID;
    ELSE
        V_TABLEINSERT1  := 'GTMP_PD_RUNNING_CONFIG';
        V_TABLEINSERT2  := 'IFRS_PD_MAA_ENR';
        V_TABLESELECT1  := 'IFRS_PD_MIGRATION_DETAIL';
        V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG';
    END IF;

   PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
   COMMIT;
  
   EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TABLEPDCONFIG || '' ; 
	 
    V_STR_QUERY := 'INSERT INTO ' || V_TABLEPDCONFIG || ' (PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)' ||
               'SELECT PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE' || 
					 	' FROM IFRS_PD_RULES_CONFIG ' ||
               'WHERE PD_METHOD = ''MAA'' AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0'' 
               )';
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;

    ----------------------------------------------------------------
    -- PRE-SIMULATION TABLE: create/drop temp tables if P_PRC = 'S'
    ----------------------------------------------------------------
    IF P_PRC = 'S' THEN
        -- drop table if exists
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.GTMP_PD_RUNNING_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;

        -- second table
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEINSERT2);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT2;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_PD_MAA_ENR WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- config
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEPDCONFIG);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.GTMP_IFRS_PD_RULES_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
    END IF;
    COMMIT;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEINSERT1;
   
    COMMIT;

    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 ||
                   ' (PD_RULE_ID, BUCKET_GROUP, HISTORICAL_DATA, ' ||
                   ' CURR_DATE, CUT_OFF_DATE, DEFAULT_RULE_ID, CALC_METHOD, PREV_DATE,INCLUDE_CLOSE) ' ||
                   ' SELECT PKID, BUCKET_GROUP, HISTORICAL_DATA, ' ||
                   ' TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''', ''YYYY-MM-DD''), ' ||
                   ' START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD, ' ||
                   ' LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), -1 * INCREMENT_PERIOD)), ' ||
                   ' INCLUDE_CLOSE ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || '';

   	EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    IF V_MODEL_ID = '0' THEN
        V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||
                       ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';
    ELSE
        -- delete rows in target that match PKs in config (using EXISTS)
        V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' A ' ||
                       ' WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                       ' AND EXISTS (SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B WHERE B.PD_RULE_ID = A.PD_RULE_ID)';
    END IF;
    
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' (' ||
                   ' EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT, CREATEDBY, CREATEDDATE, CREATEDHOST) ' ||
                   ' SELECT B.CURR_DATE, B.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, ' ||
				   ' CASE WHEN B.INCLUDE_CLOSE = 1 AND A.BUCKET_TO = 0 THEN 1 ELSE A.BUCKET_TO END AS BUCKET_TO, SUM(A.CALC_AMOUNT), ' ||
                   '''SP_IFRS_PD_MAA_ENR'', SYSDATE, ''LOCALHOST'' ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_TABLESELECT1 || ' A ' ||
                   ' JOIN ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' B ON A.PD_RULE_ID = B.PD_RULE_ID AND A.CURR_DATE = B.CURR_DATE ' ||
                   ' GROUP BY B.CURR_DATE, B.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, CASE WHEN B.INCLUDE_CLOSE = 1 AND A.BUCKET_TO = 0 THEN 1 ELSE A.BUCKET_TO END';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' (' ||
                   ' EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT, CREATEDBY, CREATEDDATE, CREATEDHOST) ' ||
                   ' SELECT DISTINCT A.CURR_DATE, A.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, B.BUCKET_ID, CASE WHEN A.INCLUDE_CLOSE = 1 AND C.BUCKET_ID = 0 THEN 1 ELSE C.BUCKET_ID END AS BUCKET_TO, 0, ' ||
                   '''SP_IFRS_PD_MAA_ENR_1'', SYSDATE, ''LOCALHOST'' ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT1 || ' A ' ||
                   ' JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_DETAIL B ON A.BUCKET_GROUP = B.BUCKET_GROUP ' ||
                   ' CROSS JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_DETAIL C ' ||
                   ' WHERE C.BUCKET_GROUP = B.BUCKET_GROUP ' ||
                   ' AND A.CUT_OFF_DATE <= A.PREV_DATE ' ||
                   ' AND NOT EXISTS ( ' ||
                   '    SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 || ' D ' ||
                   '    WHERE D.PD_RULE_ID = A.PD_RULE_ID ' ||
                   '      AND D.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ' ||
                   '      AND D.BUCKET_FROM = B.BUCKET_ID ' ||
                   '      AND D.BUCKET_TO = C.BUCKET_ID ' ||
                   ' )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));

    V_TABLEDEST := V_TAB_OWNER || '.' || V_TABLEINSERT2;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_TABLEINSERT2 ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (PD_RULE_ID IN (SELECT PKID FROM ' || V_TABLEPDCONFIG || ') )';

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

END;
/
