CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_MIGRATION_DETAIL (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR(22);
	V_COUNT NUMBER;

    ---- QUERY  
    V_STR_QUERY CLOB;

	---- TABLE LIST 
	V_TABLENAME_MON VARCHAR(100);
    V_TABLEINSERT1 VARCHAR(100);
    V_TABLEINSERT2 VARCHAR(100);
    V_TABLESELECT1 VARCHAR(100);
    V_TABLEPDCONFIG VARCHAR(100);
   	V_TABLEINSERT3 VARCHAR(100);

    ---- CONDITION
    V_RETURNROWS INT;
    V_RETURNROWS2 INT;
    V_TABLEDEST VARCHAR(100);
    V_COLUMNDEST VARCHAR(100);
    V_SP_NAME VARCHAR(100);
    V_OPERATION VARCHAR(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
	
   	V_SP_NAME := 'SP_IFRS_PD_MIGRATION_DETAIL';
   
    IF P_SYSCODE <> '0' THEN
   		V_MODEL_ID := '1';
    ELSE
    	V_MODEL_ID := '0';
    END IF;

    IF P_PRC = 'S' THEN 
        V_TABLENAME_MON := 'TMP_IMAM_' || P_RUNID || '';
        V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG';
        V_TABLEINSERT2 := 'IFRS_PD_MIGRATION_DETAIL_' || P_RUNID || '';
        V_TABLESELECT1 := 'IFRS_PD_SCENARIO_DATA_' || P_RUNID || '';
        V_TABLEINSERT3 := 'TMP_IFRS_PD_RUNNING_DATE_' || P_RUNID || '';
    ELSE 
		V_TABLENAME_MON := 'IFRS_MASTER_ACCOUNT_MONTHLY';
		V_TABLEPDCONFIG := 'GTMP_IFRS_PD_RULES_CONFIG';
        V_TABLEINSERT2 := 'IFRS_PD_MIGRATION_DETAIL';
        V_TABLESELECT1 := 'IFRS_PD_SCENARIO_DATA';
        V_TABLEINSERT3 := 'TMP_IFRS_PD_RUNNING_DATE';
    END IF;
   
   EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TABLEPDCONFIG || '' ; 
	 
    V_STR_QUERY := 'INSERT INTO ' || V_TABLEPDCONFIG || ' (PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)' ||
               'SELECT PKID, SYSCODE_PD, PD_RULE_NAME, SEGMENTATION_ID, PD_METHOD, START_HISTORICAL_DATE,' || 
						'CALC_METHOD, HISTORICAL_DATA, EXPECTED_LIFE, INCLUDE_INDIVIDUAL_ACCOUNT, INCLUDE_WO, INCLUDE_CLOSE, DEFAULT_RATIO_BY, ' ||
						'DEFAULT_RULE_ID, BUCKET_GROUP, ME_CODE, PERIOD_START_DATE, PERIOD_END_DATE, ' ||
					 	'IS_DELETED, INCREMENT_PERIOD, IS_ACTIVE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE' || 
					 	' FROM IFRS_PD_RULES_CONFIG ' ||
               'WHERE PD_METHOD = ''MAA'' AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:p1, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :p2 = ''0'' 
               )';
    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
    EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;

    -------- RECORD RUN_ID --------
   	PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
	COMMIT;
    -------- RECORD RUN_ID --------

	IF P_PRC = 'S' THEN
    	        
    	-- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_TABLEINSERT2);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TABLEINSERT2;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TABLEINSERT2 || ' AS SELECT * FROM IFRS_PD_MAA_MIGRATION_DETAIL WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        
    	-- DROP TABLE IF EXISTS (OWNED BY CURRENT SCHEMA)
        SELECT COUNT(*) INTO V_COUNT
        FROM USER_TABLES
        WHERE TABLE_NAME = UPPER(V_TABLEPDCONFIG);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TABLEPDCONFIG;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TABLEPDCONFIG || ' AS SELECT * FROM IFRS_PD_RULES_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        COMMIT;
    ELSE
    
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TABLEINSERT3 ||'' ;
	    
	    COMMIT;
    
    END IF;

    -------- ====== BODY ======
    -- Insert into GTPC
	V_STR_QUERY := '
    INSERT INTO ' || V_TABLEINSERT3 || ' (PKID, BUCKET_GROUP, HISTORICAL_DATA, CURR_DATE, START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD, PREV_DATE)' ||
    	' SELECT
        PKID, BUCKET_GROUP, HISTORICAL_DATA, 
		TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS CURR_DATE, START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD,
        LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), INCREMENT_PERIOD * -1)) AS PREV_DATE
		FROM '|| V_TABLEPDCONFIG || ' WHERE PD_METHOD = ''MAA'' ';
	EXECUTE IMMEDIATE(V_STR_QUERY);
    COMMIT;

    -- Delete logic
    IF V_MODEL_ID = '0' THEN

	    V_STR_QUERY := '';
	    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TABLEINSERT2 ||' A
	    WHERE A.CURR_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ';
	    EXECUTE IMMEDIATE(V_STR_QUERY);

    ELSE
    
		V_STR_QUERY := '';
	    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TABLEINSERT2 ||' A
	    WHERE EXISTS ( SELECT 1 FROM ' || V_TABLEPDCONFIG || ' B 
					    WHERE A.PD_RULE_ID = B.PKID)
					    AND A.CURR_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ';
	   
	    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
		EXECUTE IMMEDIATE(V_STR_QUERY);
    END IF;
    COMMIT;

    ---- Populate Default Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_IFRS_PD_DEFAULT;

	IF V_COUNT > 0 THEN
	
		EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_DEFAULT';
	END IF;
    COMMIT;

	V_STR_QUERY := '
	INSERT INTO TMP_IFRS_PD_DEFAULT ( 
	 DOWNLOAD_DATE 
	 ,PD_UNIQUE_ID 
	 ,DEFAULT_DATE 
	 ,RULE_ID 
	 )  
	SELECT B.PREV_DATE AS DOWNLOAD_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID 
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID   
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE)  
	 ,A.RULE_ID  
	FROM IFRS_DEFAULT A  
	JOIN ' || V_TABLEINSERT3 || ' B ON A.RULE_ID = B.DEFAULT_RULE_ID  
	WHERE A.DOWNLOAD_DATE = B.PREV_DATE  
	GROUP BY B.PREV_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC'' 
	    ,''COS'' 
	    ,''CVS'' 
	    ) 
	   THEN A.CUSTOMER_NUMBER 
	  WHEN B.CALC_METHOD IN ( 
	    ''ANOA'' 
	    ,''ACA'' 
	    ,''AVS'' 
	    ) 
	   THEN A.MASTERID  
	  WHEN B.CALC_METHOD = ''FNOF'' 
	   THEN A.FACILITY_NUMBER 
	  ELSE A.MASTERID 
	  END 
	 ,RULE_ID 

	UNION  
	
	SELECT B.CURR_DATE AS DOWNLOAD_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID  
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE)  
	 ,A.RULE_ID  
	FROM IFRS_DEFAULT A  
	JOIN ' || V_TABLEINSERT3 || ' B ON A.RULE_ID = B.DEFAULT_RULE_ID  
	WHERE A.DOWNLOAD_DATE BETWEEN B.PREV_DATE AND B.CURR_DATE
	GROUP BY B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID 
	  END  
	 ,RULE_ID'; 
	
	DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);
	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 
	
    ---- Populate WO Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_IFRS_PD_WO;

	IF V_COUNT > 0 THEN
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_WO';
	END IF;
    COMMIT;

	V_STR_QUERY := 'INSERT INTO TMP_IFRS_PD_WO (  
	 DOWNLOAD_DATE  
	 ,PD_UNIQUE_ID  
	 ,WO_DATE  
	 ,PD_RULE_ID  
	 )  
	SELECT B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN TO_CHAR(A.MASTERID)    
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE TO_CHAR(A.MASTERID) 
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE) AS WO_DATE  
	 ,B.PKID  
	FROM IFRS_MASTER_ACCOUNT_WO A  
	CROSS JOIN ' || V_TABLEINSERT3 || ' B  
	WHERE A.DOWNLOAD_DATE <= B.CURR_DATE  
	GROUP BY B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN TO_CHAR(A.MASTERID) 
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE TO_CHAR(A.MASTERID)    
	  END  
	 ,B.PKID';  
	 
	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 

    ---- Populate Current PD Scenario Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_IFRS_PD_SCENARIO_DATA;

	IF V_COUNT > 0 THEN
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_SCENARIO_DATA';
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '	 
	INSERT INTO TMP_IFRS_PD_SCENARIO_DATA (  
	 PERIOD  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,CALC_METHOD  
	 ,CUSTOMER_NUMBER  
	 ,CALC_AMOUNT  
	 ,BUCKET_ID  
	 ,OUTSTANDING  
	 ,ACCOUNT_STATUS  
	 )  
	SELECT A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,MAX(A.CUSTOMER_NUMBER) AS CUSTOMER_NUMBER  
	 ,SUM(A.CALC_AMOUNT) AS CALC_AMOUNT  
	 ,MAX(CASE   
	   WHEN D.PD_UNIQUE_ID IS NOT NULL  
	    OR (  
	     E.PD_UNIQUE_ID IS NOT NULL  
	     )  
	    THEN C.MAX_BUCKET_ID  
	   ELSE A.BUCKET_ID  
	   END) AS BUCKET_ID  
	 ,SUM(A.OUTSTANDING) AS OUTSTANDING  
	 ,A.ACCOUNT_STATUS  
	FROM ' || V_TABLESELECT1 || ' A  
	JOIN ' || V_TABLEINSERT3 || ' B ON A.PD_RULE_ID = B.PKID  
	JOIN VW_IFRS_MAX_BUCKET C ON A.BUCKET_GROUP = C.BUCKET_GROUP  
	LEFT JOIN TMP_IFRS_PD_DEFAULT D ON A.PD_UNIQUE_ID = D.PD_UNIQUE_ID  
	 AND B.DEFAULT_RULE_ID = D.RULE_ID  
	 AND A.PERIOD = D.DOWNLOAD_DATE  
	LEFT JOIN TMP_IFRS_PD_WO E ON A.PD_UNIQUE_ID = E.PD_UNIQUE_ID  
	 AND A.PERIOD = E.DOWNLOAD_DATE  
	 AND A.PD_RULE_ID = E.PD_RULE_ID  
	JOIN IFRS_BUCKET_HEADER F ON A.BUCKET_GROUP = F.BUCKET_GROUP  
	WHERE A.PERIOD = B.CURR_DATE  
	GROUP BY A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,A.ACCOUNT_STATUS';  
	 
 DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));

	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 
    ---- Populate Previous PD Scenario Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_IFRS_PD_SCENARIO_PREV;

	IF V_COUNT > 0 THEN
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_IFRS_PD_SCENARIO_PREV';
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO TMP_IFRS_PD_SCENARIO_PREV (  
	 PERIOD  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,CALC_METHOD  
	 ,CUSTOMER_NUMBER  
	 ,CALC_AMOUNT  
	 ,BUCKET_ID  
	 ,OUTSTANDING  
	 ,ACCOUNT_STATUS  
	 ,IS_CURR_DEFAULT  
	 ,IS_CURR_WO  
	 ) -- CURR WO & DEFAULT UNTUK HANDLE ACCOUNT FULLYPAID TAPI ADA WO / DEFAULT                                
	SELECT A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,MAX(A.CUSTOMER_NUMBER) AS CUSTOMER_NUMBER  
	 ,SUM(A.CALC_AMOUNT) AS CALC_AMOUNT  
	 ,MAX(CASE   
	   WHEN D.PD_UNIQUE_ID IS NOT NULL  
	    THEN C.MAX_BUCKET_ID  
	   ELSE A.BUCKET_ID  
	   END) AS BUCKET_ID  
	 ,SUM(A.OUTSTANDING) AS OUTSTANDING  
	 ,A.ACCOUNT_STATUS  
	 ,MAX(CASE   
	   WHEN E.PD_UNIQUE_ID IS NOT NULL  
	    THEN 1  
	   ELSE 0  
	   END)  
	 ,MAX(CASE   
	   WHEN F.PD_UNIQUE_ID IS NOT NULL  
	    THEN 1  
	   ELSE 0  
	   END)  
	FROM ' || V_TABLESELECT1 || ' A  
	JOIN ' || V_TABLEINSERT3 || ' B ON A.PD_RULE_ID = B.PKID  
	JOIN VW_IFRS_MAX_BUCKET C ON A.BUCKET_GROUP = C.BUCKET_GROUP  
	LEFT JOIN TMP_IFRS_PD_DEFAULT D ON A.PD_UNIQUE_ID = D.PD_UNIQUE_ID  
	 AND B.DEFAULT_RULE_ID = D.RULE_ID  
	 AND A.PERIOD = D.DOWNLOAD_DATE  
	LEFT JOIN TMP_IFRS_PD_DEFAULT E ON A.PD_UNIQUE_ID = E.PD_UNIQUE_ID  
	 AND B.DEFAULT_RULE_ID = E.RULE_ID  
	 AND B.CURR_DATE = E.DOWNLOAD_DATE  
	LEFT JOIN TMP_IFRS_PD_WO F ON A.PD_UNIQUE_ID = F.PD_UNIQUE_ID  
	 AND B.CURR_DATE >= F.DOWNLOAD_DATE  
	 AND A.PD_RULE_ID = F.PD_RULE_ID  
	WHERE A.PERIOD = B.PREV_DATE  
	GROUP BY A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,A.ACCOUNT_STATUS'; 
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	 
    ---- Populate Close Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_PD_CLOSE;

	IF V_COUNT > 0 THEN
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_PD_CLOSE';
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '   
	INSERT INTO TMP_PD_CLOSE  
	 (PD_RULE_ID, DEFAULT_RULE_ID, PD_UNIQUE_ID, PREVDATE, CURRDATE, CALC_METHOD)  
	SELECT A.PD_RULE_ID,B.DEFAULT_RULE_ID,A.PD_UNIQUE_ID, B.PREV_DATE,   
	 LAST_DAY(ADD_MONTHS(B.CURR_DATE,-1)), B.CALC_METHOD  
	FROM TMP_IFRS_PD_SCENARIO_PREV A  
	 JOIN ' || V_TABLEINSERT3 || ' B ON A.PD_RULE_ID = B.PKID  
	  AND A.PERIOD = B.PREV_DATE  
	WHERE NOT EXISTS (  
	  SELECT * 
	  FROM TMP_IFRS_PD_SCENARIO_DATA C  
	  WHERE C.PD_RULE_ID = A.PD_RULE_ID  
	   AND C.PD_UNIQUE_ID = A.PD_UNIQUE_ID  
	   AND C.PERIOD = B.CURR_DATE  
	  FETCH FIRST 1 ROW ONLY
	  )';
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;


	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_DEFAULT_PD';
	COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO GTMP_IFRS_DEFAULT_PD (DOWNLOAD_DATE,PD_RULE_ID,PD_UNIQUE_ID)		    
		SELECT MIN(DOWNLOAD_DATE) AS DOWNLOAD_DATE ,PKID ,CASE   
						    WHEN CF.CALC_METHOD IN (  
						      ''CNOC''  
						      ,''COS''  
						      ,''CVS''  
						      )  
						     THEN ID.CUSTOMER_NUMBER  
						    WHEN CF.CALC_METHOD IN (  
						      ''ANOA''  
						      ,''ACA''  
						      ,''AVS''  
						      )  
						     THEN  
						      ID.MASTERID  
						    WHEN CF.CALC_METHOD = ''FNOF''  
						     THEN ID.FACILITY_NUMBER  
						    ELSE ID.MASTERID 
						    END AS PD_UNIQUE_ID  
		FROM IFRS_DEFAULT ID
		INNER JOIN TMP_IFRS_PD_RUNNING_DATE CF ON ID.RULE_ID = CF.DEFAULT_RULE_ID 
		AND ID.DOWNLOAD_DATE BETWEEN CF.PREV_DATE  AND CF.CURR_DATE 
		GROUP BY PKID,CASE   
						    WHEN CF.CALC_METHOD IN (  
						      ''CNOC''  
						      ,''COS''  
						      ,''CVS''  
						      )  
						     THEN ID.CUSTOMER_NUMBER  
						    WHEN CF.CALC_METHOD IN (  
						      ''ANOA''  
						      ,''ACA''  
						      ,''AVS''  
						      )  
						     THEN  
						      ID.MASTERID  
						    WHEN CF.CALC_METHOD = ''FNOF''  
						     THEN ID.FACILITY_NUMBER  
						    ELSE ID.MASTERID 
						    END';
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;

    ---- Populate Closed Default Data
	SELECT COUNT(*)
	INTO V_COUNT
	FROM TMP_PD_DEFAULT_CLOSE;

	IF V_COUNT > 0 THEN
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_PD_DEFAULT_CLOSE';
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO TMP_PD_DEFAULT_CLOSE (PD_RULE_ID, PD_UNIQUE_ID)  
	SELECT A.PD_RULE_ID,  
	  A.PD_UNIQUE_ID
	  FROM TMP_IFRS_PD_SCENARIO_PREV A
		INNER JOIN TMP_IFRS_PD_RUNNING_DATE B ON A.PD_RULE_ID = B.PKID 
		WHERE EXISTS (
		SELECT 1 FROM  GTMP_IFRS_DEFAULT X
					WHERE X.PD_RULE_ID = A.PD_RULE_ID 
					AND X.PD_UNIQUE_ID = A.PD_UNIQUE_ID 
				    )';

	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;

	   
	/*Start inserting Migration Detail population*/  
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO ' || V_TABLEINSERT2 || ' (  
	  PREV_DATE  
	 ,CURR_DATE  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,BUCKET_FROM  
	 ,BUCKET_TO  
	 ,CALC_AMOUNT  
	 ,CUSTOMER_NUMBER  
	 ,OUTSTANDING  
	 ,CREATEDBY  
	 ,CREATEDDATE  
	 ,CREATEDHOST  
	 )  
	SELECT A.PERIOD PREV_DATE  
	 ,B.PERIOD CURR_DATE  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.BUCKET_ID BUCKET_FROM  
	 ,CASE   
	  WHEN A.BUCKET_ID = D.MAX_BUCKET_ID  
	   THEN D.MAX_BUCKET_ID  
	  WHEN B.ACCOUNT_STATUS = ''C''  
	   AND B.BUCKET_ID <> D.MAX_BUCKET_ID  
	   THEN 0  
	  ELSE B.BUCKET_ID  
	  END BUCKET_TO  
	 ,A.CALC_AMOUNT  
	 ,B.CUSTOMER_NUMBER  
	 ,A.OUTSTANDING  
	 ,''SP_IFRS_PD_MIGRATION_DETAIL''  
	 ,SYSDATE
	 ,''LOCALHOST''  
	FROM TMP_IFRS_PD_SCENARIO_PREV A  
	JOIN TMP_IFRS_PD_SCENARIO_DATA B ON A.PD_RULE_ID = B.PD_RULE_ID  
	 AND A.PD_UNIQUE_ID = B.PD_UNIQUE_ID  
	JOIN ' || V_TABLEINSERT3 || ' C ON A.PD_RULE_ID = C.PKID  
	 AND B.PD_RULE_ID = C.PKID  
	 AND A.PERIOD = C.PREV_DATE  
	 AND B.PERIOD = C.CURR_DATE  
	JOIN VW_IFRS_MAX_BUCKET D ON D.BUCKET_GROUP = A.BUCKET_GROUP  
	 AND D.BUCKET_GROUP = B.BUCKET_GROUP';  
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO ' || V_TABLEINSERT2 || ' (  
	  PREV_DATE  
	 ,CURR_DATE  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,BUCKET_FROM  
	 ,BUCKET_TO  
	 ,CALC_AMOUNT  
	 ,CUSTOMER_NUMBER  
	 ,OUTSTANDING  
	 ,CREATEDBY  
	 ,CREATEDDATE  
	 ,CREATEDHOST  
	 )  
	SELECT  A.PERIOD PREV_DATE  
	 ,B.CURR_DATE  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.BUCKET_ID BUCKET_FROM  
	 ,CASE   
	  WHEN A.BUCKET_ID = D.MAX_BUCKET_ID  
	   OR G.PD_UNIQUE_ID IS NOT NULL   
	   OR A.IS_CURR_DEFAULT = 1  
	   OR (  
	    A.IS_CURR_WO = 1   
	    )  
	   THEN D.MAX_BUCKET_ID  
	  ELSE 0  
	  END BUCKET_TO  
	 ,A.CALC_AMOUNT  
	 ,A.CUSTOMER_NUMBER  
	 ,A.OUTSTANDING  
	 ,''SP_IFRS_PD_MIGRATION_DETAIL_1''  
	 ,SYSDATE
	 ,''LOCALHOST''  
	FROM TMP_IFRS_PD_SCENARIO_PREV A  
	JOIN ' || V_TABLEINSERT3 || ' B ON A.PD_RULE_ID = B.PKID  
	 AND A.PERIOD = B.PREV_DATE  
	JOIN VW_IFRS_MAX_BUCKET D ON D.BUCKET_GROUP = A.BUCKET_GROUP  
	JOIN IFRS_BUCKET_HEADER F ON F.BUCKET_GROUP = A.BUCKET_GROUP  
	LEFT JOIN TMP_PD_DEFAULT_CLOSE G   
	 ON A.PD_RULE_ID = G.PD_RULE_ID  
	  AND A.PD_UNIQUE_ID = G.PD_UNIQUE_ID  
	WHERE NOT EXISTS (  
	  SELECT * 
	  FROM TMP_IFRS_PD_SCENARIO_DATA C  
	  WHERE C.PD_RULE_ID = A.PD_RULE_ID  
	   AND C.PD_UNIQUE_ID = A.PD_UNIQUE_ID  
	   AND C.PERIOD = B.CURR_DATE  
	  FETCH FIRST 1 ROW ONLY
	  )'; 
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	
	/*End inserting Migration Detail population*/ 

    V_TABLEDEST := V_TABLEINSERT2;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
    -------- ====== LOG ======

    -------- ====== RESULT ======
--    V_QUERYS := 'SELECT * FROM ' || V_TABLEINSERT2 || ' WHERE EFF_DATE =TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
--                ' AND (PD_RULE_ID IN (SELECT PKID FROM ' || V_TABLEPDCONFIG || ')) ';
--   		
--    CALL SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
--	COMMIT;
    -------- ====== RESULT ======
EXCEPTION
    WHEN OTHERS THEN
        -- ROLLBACK TO SAFE STATE AND RE-RAISE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR IN SP_IFRS_PD_RULE_DATA: ' || SQLERRM);
        RAISE;

END;
/
