CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_VAS_ZSCORE (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AS
    -- Dates / counters
	
    V_CURRDATE      DATE;
    V_PREVDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);
    V_COUNT         NUMBER;
	V_COUNTER   	NUMBER := 1;
    V_EXPLIFE   	NUMBER := 0;

    -- Dynamic SQL
    V_STR_QUERY     CLOB;

    -- Table names
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_TABLEPDCONFIG VARCHAR2(100);
	V_GTMP_PD_ZSCORE_CONFIG VARCHAR2(100);
    	V_TMP_MEV VARCHAR2(100);
    	V_TMP_AVG_STDEV_ME VARCHAR2(100);
    	V_TMP_PD_VAS_ZSCORE1 VARCHAR2(100);
    	V_IFRS_PD_VAS_ZSCORE VARCHAR2(100);
    	V_IFRS_ME_FORECAST_SCN VARCHAR2(100);
    	V_IFRS_MACRO_ECONOMIC_INTRPOLATE VARCHAR2(100);

    -- misc
    V_RETURNROWS    NUMBER;
    V_RETURNROWS2   NUMBER;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);

    -- result query
    V_QUERYS        CLOB;
BEGIN
    -- set procedure name
    V_SP_NAME := 'SP_IFRS_PD_VAS_ZSCORE';
    
    -- handle default download date
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
          INTO V_CURRDATE
          FROM PSAK413.IFRS_PRC_DATE; 
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    V_MODEL_ID := NVL(P_SYSCODE, '0');

    IF P_PRC = 'S' THEN
    	V_GTMP_PD_ZSCORE_CONFIG := 'GTMP_PD_ZSCORE_CONFIG_' || P_RUNID;
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG_' || P_RUNID;
    	V_TMP_MEV := 'TMP_MEV_' || P_RUNID;
    	V_TMP_AVG_STDEV_ME := 'TMP_AVG_STDEV_ME_' || P_RUNID;
    	V_TMP_PD_VAS_ZSCORE1 := 'TMP_PD_VAS_ZSCORE1_' || P_RUNID;
    	V_IFRS_PD_VAS_ZSCORE := 'IFRS_PD_VAS_ZSCORE_' || P_RUNID;
    	V_IFRS_ME_FORECAST_SCN := 'IFRS_ME_FORECAST_SCN_' || P_RUNID;
    	V_IFRS_MACRO_ECONOMIC_INTRPOLATE := 'IFRS_MACRO_ECONOMIC_INTRPOLATE_' || P_RUNID;
    
    ELSE
        V_GTMP_PD_ZSCORE_CONFIG := 'GTMP_PD_ZSCORE_CONFIG';
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG';
    	V_TMP_MEV := 'TMP_MEV';
    	V_TMP_AVG_STDEV_ME := 'TMP_AVG_STDEV_ME';
    	V_TMP_PD_VAS_ZSCORE1 := 'TMP_PD_VAS_ZSCORE1';
    	V_IFRS_PD_VAS_ZSCORE := 'IFRS_PD_VAS_ZSCORE';
    	V_IFRS_ME_FORECAST_SCN := 'IFRS_ME_FORECAST_SCN';
    	V_IFRS_MACRO_ECONOMIC_INTRPOLATE := 'IFRS_MACRO_ECONOMIC_INTRPOLATE';
    
    END IF;

   PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
   COMMIT;

    ----------------------------------------------------------------
    -- PRE-SIMULATION TABLE: create/drop temp tables if P_PRC = 'S'
    ----------------------------------------------------------------
    IF P_PRC = 'S' THEN
        -- drop table if exists
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TMP_MEV);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TMP_MEV;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TMP_MEV ||
                       ' AS SELECT *  FROM ' || V_TAB_OWNER || '.TMP_MEV WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;

        -- second table
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TMP_AVG_STDEV_ME);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TMP_AVG_STDEV_ME;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TMP_AVG_STDEV_ME ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.TMP_AVG_STDEV_ME WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- table V_TMP_PD_VAS_ZSCORE1
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TMP_PD_VAS_ZSCORE1);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TMP_PD_VAS_ZSCORE1;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TMP_PD_VAS_ZSCORE1 ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.TMP_PD_VAS_ZSCORE1 WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
       	-- table V_IFRS_PD_VAS_ZSCORE
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_IFRS_PD_VAS_ZSCORE);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_PD_VAS_ZSCORE WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
        
        -- config
        SELECT COUNT(*) INTO V_COUNT
        FROM ALL_TABLES
        WHERE OWNER = V_TAB_OWNER
          AND TABLE_NAME = UPPER(V_TABLEPDCONFIG);

        IF V_COUNT > 0 THEN
            V_STR_QUERY := 'DROP TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG;
            EXECUTE IMMEDIATE V_STR_QUERY;
        END IF;

        V_STR_QUERY := 'CREATE TABLE ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG ||
                       ' AS SELECT * FROM ' || V_TAB_OWNER || '.IFRS_PD_RULES_CONFIG WHERE 1=0';
        EXECUTE IMMEDIATE V_STR_QUERY;
    ELSE 
    	EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_PD_ZSCORE_CONFIG';
    	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_MEV';
    	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_AVG_STDEV_ME';
    	EXECUTE IMMEDIATE 'TRUNCATE TABLE TMP_PD_VAS_ZSCORE1';
        
        -- delete existing rows in target for this eff_date and model filter
	    EXECUTE IMMEDIATE 'DELETE FROM IFRS_PD_VAS_ZSCORE WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
	      AND (PD_RULE_ID = ' || V_MODEL_ID || ' OR ' || V_MODEL_ID || ' = 0)';
    END IF;
    COMMIT;
        
-- populate GTMP_PD_ZSCORE_CONFIG
    V_STR_QUERY := ' INSERT INTO ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' (
        PD_RULE_ID, BUCKET_GROUP, INCREMENT_PERIOD, CURR_DATE, CUT_OFF_DATE,
        ME_CODE, CALC_METHOD, EXPECTED_LIFE, PERIOD_START, PERIOD_END
    )
    SELECT
        A.PKID, A.BUCKET_GROUP, A.INCREMENT_PERIOD, TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS CURR_DATE,
        A.CUT_OFF_DATE, A.ME_CODE, A.CALC_METHOD, A.EXPECTED_LIFE,
        LAST_DAY(
            ADD_MONTHS(
                TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD''),
                -1 * A.INCREMENT_PERIOD * A.HISTORICAL_DATA
            )
        ) AS PERIOD_START,
        TO_DATE(''31-12-'' || TO_CHAR(TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD''),''YYYY''), ''DD-MM-YYYY'') AS PERIOD_END
    FROM ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' A
    WHERE NVL(A.ACTIVE_FLAG,0) = 1
      AND A.PD_METHOD = ''VAS''
      AND (A.PKID = ' || V_MODEL_ID || ' OR ' || V_MODEL_ID || ' = 0)';
	
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    -- populate TMP_MEV from IFRS_ME_FORECAST_SCN (distinct)
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_MEV || ' (ME_PERIOD, ME_CODE, SCENARIO_NO, ME_VAL)
    SELECT DISTINCT LAST_DAY(A.ME_PERIOD), A.ME_CODE, A.SCENARIO_NO, A.ME_VALUE
    FROM ' || V_TAB_OWNER || '.' || V_IFRS_ME_FORECAST_SCN || ' A
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
      AND EXISTS (
          SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' B WHERE B.ME_CODE = A.ME_CODE
      )';
    
	EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
	
    -- populate TMP_MEV also from IFRS_MACRO_ECONOMIC_INTRPOLATE for matching ME_CODE/SCENARIO_NO not present yet
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_MEV || ' (ME_PERIOD, ME_CODE, SCENARIO_NO, ME_VAL)
    SELECT LAST_DAY(A.ME_PERIOD), A.ME_CODE, B.SCENARIO_NO, A.ME_VALUE
    FROM ' || V_TAB_OWNER || '.' || V_IFRS_MACRO_ECONOMIC_INTRPOLATE || ' A
    JOIN (SELECT DISTINCT ME_CODE, SCENARIO_NO FROM ' || V_TAB_OWNER || '.' || V_TMP_MEV || ') B ON A.ME_CODE = B.ME_CODE
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
      AND A.ME_PERIOD <= LAST_DAY(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''))
      AND NOT EXISTS (
          SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_TMP_MEV || ' X
          WHERE X.ME_CODE = A.ME_CODE
            AND B.SCENARIO_NO = X.SCENARIO_NO
            AND LAST_DAY(A.ME_PERIOD) = LAST_DAY(X.ME_PERIOD)
      )';
	EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
    -- compute AVG and STDEV per PD_RULE_ID, ME_CODE
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_AVG_STDEV_ME || ' (PD_RULE_ID, ME_CODE, AVG_ME_VAL, STDEV_ME_VAL)
    SELECT
        B.PD_RULE_ID,
        B.ME_CODE,
        AVG(A.ME_VALUE) AS AVG_ME_VAL,
        STDDEV(A.ME_VALUE) AS STDEV_ME_VAL
    FROM ' || V_TAB_OWNER || '.' || V_IFRS_MACRO_ECONOMIC_INTRPOLATE || ' A
    JOIN ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' B ON A.ME_CODE = B.ME_CODE
    WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
      AND A.ME_PERIOD BETWEEN LAST_DAY(ADD_MONTHS(B.PERIOD_START, -1)) AND TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
    GROUP BY B.PD_RULE_ID, B.ME_CODE';
	EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
    -- get expected life (assume same for all rows; original T-SQL used SELECT into variable)
    EXECUTE IMMEDIATE ' SELECT EXPECTED_LIFE 
    FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || '
    WHERE ROWNUM = 1'
    INTO V_EXPLIFE ;

  	-- loop to insert into TMP_PD_EXT_ZSCORE1 with yearly offsets as in original
    WHILE V_COUNTER <= NVL(V_EXPLIFE,0) LOOP
       EXECUTE IMMEDIATE ' INSERT INTO ' || V_TAB_OWNER || '.' || V_TMP_PD_VAS_ZSCORE1 || ' (PD_RULE_ID, ME_CODE, PERIOD, SCENARIO_NO, ME_VAL)
        SELECT B.PD_RULE_ID,
               A.ME_CODE,
               A.ME_PERIOD,
               A.SCENARIO_NO,
               NVL(A.ME_VAL,0)
        FROM ' || V_TAB_OWNER || '.' || V_TMP_MEV || ' A
        JOIN ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' B ON A.ME_CODE = B.ME_CODE
        WHERE A.ME_PERIOD >= B.PERIOD_END
          AND LAST_DAY(ADD_MONTHS(B.PERIOD_END, 12 * ' || V_COUNTER || ')) = A.ME_PERIOD';
  	
        V_COUNTER := V_COUNTER + 1;
    END LOOP;
	COMMIT;
        
    -- recursive CTE to generate periods similar to CTEDATE in T-SQL
    V_STR_QUERY := 'WITH CTEDATE (PD_RULE_ID, PERIOD, INCREMENT_PERIOD, MAXDATE) AS (
        SELECT
            PD_RULE_ID,
            TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS PERIOD,
            INCREMENT_PERIOD,
            LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD''), (EXPECTED_LIFE * INCREMENT_PERIOD))) AS MAXDATE
        FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || '
        UNION ALL
        SELECT
            PD_RULE_ID,
            LAST_DAY(ADD_MONTHS(PERIOD, INCREMENT_PERIOD)),
            INCREMENT_PERIOD,
            MAXDATE
        FROM CTEDATE
        WHERE LAST_DAY(ADD_MONTHS(PERIOD, INCREMENT_PERIOD)) <= MAXDATE
    ),
    CTERN AS (
        SELECT DISTINCT PD_RULE_ID, EXTRACT(YEAR FROM PERIOD) AS YEAR_PERIOD,
               ROW_NUMBER() OVER (PARTITION BY PD_RULE_ID ORDER BY EXTRACT(YEAR FROM PERIOD)) RN
        FROM CTEDATE
        WHERE EXTRACT(YEAR FROM PERIOD) > EXTRACT(YEAR FROM TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD''))
    )
INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE || ' (
        EFF_DATE, BASE_DATE, FL_SEQ, PD_RULE_ID, ME_CODE, SCENARIO_NO,
        ODR, MEAN_ODR, STDEV_ODR, ZSCORE, CREATEDBY, CREATEDDATE
    )
SELECT
        TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS EFF_DATE,
        A.PERIOD AS BASE_DATE,
        F.RN - 1 AS FL_SEQ,
        A.PD_RULE_ID,
        C.ME_CODE,
        C.SCENARIO_NO,
        NVL(D.ME_VAL, C.AVG_VAL) AS ODR,
        E.AVG_ME_VAL AS MEAN_ODR,
        E.STDEV_ME_VAL AS STDEV_ODR,
        0 AS ZSCORE,
        ''SP_IFRS_PD_MAA_ZSCORE'' AS CREATEDBY,
        SYSDATE AS CREATEDDATE
    FROM CTEDATE A
    JOIN ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' B ON A.PD_RULE_ID = B.PD_RULE_ID
    JOIN ' || V_TAB_OWNER || '.' || V_TMP_AVG_STDEV_ME || ' E ON B.PD_RULE_ID = E.PD_RULE_ID
    JOIN (
        SELECT PD_RULE_ID, ME_CODE, SCENARIO_NO, AVG(ME_VAL) AS AVG_VAL
        FROM ' || V_TAB_OWNER || '.' || V_TMP_PD_VAS_ZSCORE1 || '
        GROUP BY PD_RULE_ID, ME_CODE, SCENARIO_NO
    ) C ON B.PD_RULE_ID = C.PD_RULE_ID
       AND B.ME_CODE = C.ME_CODE
    LEFT JOIN ' || V_TAB_OWNER || '.' || V_TMP_PD_VAS_ZSCORE1 || ' D
       ON A.PERIOD = D.PERIOD
      AND B.ME_CODE = D.ME_CODE
      AND C.SCENARIO_NO = D.SCENARIO_NO
      AND B.PD_RULE_ID = D.PD_RULE_ID
    LEFT JOIN CTERN F ON EXTRACT(YEAR FROM A.PERIOD) = F.YEAR_PERIOD
                     AND A.PD_RULE_ID = F.PD_RULE_ID
    WHERE A.PERIOD > TO_DATE(''' || TO_CHAR(V_CURRDATE, 'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';
	
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
     
    -- update ZSCOREs
    EXECUTE IMMEDIATE '
	    UPDATE ' || V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE || ' dest
	       SET dest.ZSCORE = (dest.ODR - dest.MEAN_ODR) / dest.STDEV_ODR
	     WHERE dest.EFF_DATE = :v1
	       AND EXISTS (
	           SELECT 1 
	             FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_ZSCORE_CONFIG || ' b 
	            WHERE dest.PD_RULE_ID = b.PD_RULE_ID
	       )'
    USING V_CURRDATE;
	COMMIT;
    
    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_VAS_ZSCORE ||
                ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                ' AND (PD_RULE_ID = ''' || V_MODEL_ID || ''' OR ''' || V_MODEL_ID || ''' = ''0'')';

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

END;
/
