CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PATCH_DPD_CIF
AS
dtcurr DATE;
dtprev DATE;
BEGIN
	
	dtcurr := '31-DEC-2025';
	 
	WHILE  dtcurr >= '31-JAN-2020' -- '31-DEC-2025'
	LOOP 
		dtprev := ADD_MONTHS(dtcurr, -1);

	
EXECUTE IMMEDIATE 'TRUNCATE TABLE X_PSAK_DPD_CIF';

INSERT INTO X_PSAK_DPD_CIF
(
	 DOWNLOAD_DATE
	,SCIF 
	,MAX_DPD 
)
SELECT 
	 DOWNLOAD_DATE 
	,GLOBAL_CUSTOMER_NUMBER
	,DAY_PAST_DUE
FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE DOWNLOAD_DATE = dtcurr
AND GLOBAL_CUSTOMER_NUMBER IS NOT NULL;


INSERT INTO X_PSAK_DPD_CIF
(
	 DOWNLOAD_DATE
	,SCIF 
	,MAX_DPD 
)
SELECT 
	 DOWNLOAD_DATE 
	,CUSTOMER_NUMBER
	,DAY_PAST_DUE
FROM IFRS_MASTER_ACCOUNT_MONTHLY imam 
WHERE DOWNLOAD_DATE = dtcurr
AND GLOBAL_CUSTOMER_NUMBER IS NULL;


MERGE INTO 	IFRS_MASTER_ACCOUNT_MONTHLY a USING
(
	SELECT 
		 DOWNLOAD_DATE
		,SCIF 
		,MAX_DPD 
	FROM X_PSAK_DPD_CIF 
	WHERE DOWNLOAD_DATE = dtcurr
) dat 
ON 
(
	a.DOWNLOAD_DATE = dat.DOWNLOAD_DATE 
	AND 
	(
		A.GLOBAL_CUSTOMER_NUMBER = dat.SCIF
		OR
		A.CUSTOMER_NUMBER = dat.SCIF
	)
)
WHEN MATCHED THEN UPDATE 
		SET DPD_CIF = dat.MAX_DPD;
		
	dbms_output.put_line(dtcurr||'|'||dtprev);
	dtcurr := last_day(TO_DATE(dtcurr)-1-TO_NUMBER(TO_CHAR(TO_DATE(dtcurr),'DD')));

END LOOP;

END;
/
