DO
$$
DECLARE
	V_PRC VARCHAR(1) DEFAULT 'P';
BEGIN
V_PRC = 'P';

CALL SP_IFRS_IMP_FILL_IMA_PREV_CURR_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_PD_FL_TERM_YEARLY_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_PD_FL_YEAR_TO_MONTH_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_ECL_GENERATE_IMA_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_DEFAULT_RULE_ECL_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_EXEC_RULE_STAGE_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_EAD_TERM_YEARLY_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_EAD_TERM_MONTH_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_ECL_RESULT_DETAIL_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_SYNC_IMA_MONTHLY_ECL(NULL, NULL, V_PRC);
CALL SP_IFRS_IMP_NOMINATIVE_OUTPUT_ECL(NULL, NULL, V_PRC);
END;
$$;