DO
$$
DECLARE
	V_PID BIGINT;
BEGIN
-- ============== PREP ==============
V_PID := (SELECT PG_BACKEND_PID());
RAISE NOTICE 'PROCESS ID ---> %', V_PID;
-- TRUNCATE TABLE IFRS_LOGS_PROCESS;
-- TRUNCATE TABLE IFRS_RESULT_PREVIEW;
-- TRUNCATE TABLE IFRS_RUNNING_LOGS;
---- ============== IMPAIRMENT MONTHLY ==============
CALL SP_IFRS_IMP_SIMULATION_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_INITIAL_CONFIG(NULL, NULL, 'P');
CALL SP_IFRS_IMPI_JOURNAL_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_FILL_IMA_PREV_CURR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_AVG_EIR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_INSERT_DEFAULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_DEFAULT_RULE(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_SCENARIO_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_DEFAULT_RATE(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_CHR_SUMM(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_CHR_RESULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_DETAIL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_ENR(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_AVERAGE(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_MMULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_MAA_RESULT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_YEAR_TO_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_TERM_YEARLY(NULL, NULL, 'P');
CALL SP_IFRS_IMP_PD_FL_YEAR_TO_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_IMP_UPDATE_WO_RECOVERY_PORTFOLIO(NULL, NULL, 'P');
CALL SP_IFRS_IMP_RECOVERY_SCENARIO_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_WO_SCENARIO_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_LGD_SCENARIO_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_LGD_CURE_LGL_DETAIL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_LGD_CURE_LGL_HEADER(NULL, NULL, 'P');
CALL SP_IFRS_IMP_CCF_SCENARIO_DATA(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_CCF_DETAIL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_CCF_HEADER(NULL, NULL, 'P');
CALL SP_IFRS_IMP_ECL_GENERATE_IMA(NULL, NULL, 'P', NULL);
CALL SP_IFRS_IMP_DEFAULT_RULE_ECL(NULL, NULL, 'P', NULL, NULL);
CALL SP_IFRS_IMP_EXEC_RULE_STAGE(NULL, NULL, 'P', NULL);
-- CALL SP_IFRS_IMP_ECL_EAD_RESULT_NONPRK(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_TERM_YEARLY(NULL, NULL, 'P');
-- CALL SP_IFRS_IMP_ECL_EAD_RESULT_PRK(NULL, NULL, 'P');
CALL SP_IFRS_IMP_EAD_TERM_MONTH(NULL, NULL, 'P');
CALL SP_IFRS_ECL_RESULT_DETAIL(NULL, NULL, 'P',NULL);
CALL SP_IFRS_IMP_SYNC_IMA_MONTHLY(NULL, NULL, 'P');
----- NEW -----
CALL SP_IFRS_IMP_JOURNAL_GL(NULL, NULL, 'P');
CALL SP_IFRS_IMP_NOMINATIVE_OUTPUT(NULL, NULL, 'P');
CALL SP_IFRS_IMP_DASHBOARD_DATA(NULL, NULL, 'P');
CALL SP_IFRS_EXCEPTION_REPORT(NULL, NULL, 'P');
---- ============== IMPAIRMENT MONTHLY ==============
END;
$$;