SELECT A.PKID, 
A.PD_NAME AS TM_RULE_NAME,
B.PKID AS SEGMENTATION_ID,
A.PD_METHOD, ----> NEED UPDATE DI TABLE "PdConfiguration"
A.CALCULATION_METHOD AS CALC_METHOD, ----> NEED UPDATE DI TABLE "PdConfiguration"
C.UNIQUE_CODE AS BUCKET_GROUP, ----> NEED UPDATE DI TABLE "GroupBucket"
A.EXPECTED_LIFETIME AS EXPECTED_LIFE, ----> NEED UPDATE DI TABLE "PdConfiguration"
A.WINDOWS_MOVING AS INCREMENT_PERIOD, ----> NEED UPDATE DI TABLE "PdConfiguration"
A.HISTORICAL_DATA, ----> NEED UPDATE DI TABLE "PdConfiguration"
A.EFFECTIVE_END_DATE AS CUT_OFF_DATE, ----> NEED UPDATE DI TABLE "PdConfiguration"
CASE WHEN A.IS_ACTIVE = TRUE THEN 1 ELSE 0 END ACTIVE_FLAG,
0 AS IS_DELETE,
'SYSTEM' AS CREATEDBY,
CURRENT_DATE AS CREATEDDATE,
'LOCALHOST' AS CREATEDHOST,
A.DEFAULT_RATIO_BY, ----> NEED UPDATE DI TABLE "PdConfiguration"
'PENDING' AS RUNNING_STATUS
FROM "PdConfiguration" A
INNER JOIN "Segmentation" B ON A.SEGMENT_CODE = B.SYSCODE_SEGMENTATION
INNER JOIN "GroupBucket" C ON A.BUCKET_CODE = C.SYSCODE_GROUP_BUCKET
WHERE A.PKID = 108 AND A.IS_ACTIVE = TRUE