CREATE OR REPLACE PROCEDURE SP_IFRS_ECL_MODEL_CONFIG(v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
BEGIN

    DELETE FROM IFRS_ECL_MODEL_CONFIG WHERE ECL_MODEL_ID = v_ECLID AND DOWNLOAD_DATE = v_DOWNLOADDATE;
    COMMIT;

    INSERT INTO IFRS_ECL_MODEL_CONFIG(
        DOWNLOAD_DATE,
        ECL_MODEL_ID,
        PF_SEGMENT_ID,
        GROUP_SEGMENT,
        SEGMENT,
        SUB_SEGMENT,
        BUCKET_GROUP,
        EAD_MODEL_ID,
        LT_RULE_ID,
        LT_EFF_DATE,
        SICR_RULE_ID,
        CCF_FLAG,
        CCF_RULES_ID,
        CCF_REVOLVING_FLAG,
        CCF_COMMITED_FLAG,
        CCF_EFF_DATE,
        PREPAYMENT_FLAG,
        PREPAYMENT_RULES_ID,
        PREPAYMENT_EFF_DATE,
        LGD_MODEL_ID,
        LGD_FL_FLAG,
        LGD_FL_MODEL,
        LGD_EFF_STARTTYPE,
        LGD_EFF_STARTMONTH,
        LGD_EFF_DATE,
        PD_MODEL_ID,
        PD_FL_FLAG,
        PD_FL_MODEL,
        PD_EFF_STARTTYPE,
        PD_EFF_STARTMONTH,
        PD_EFF_DATE
    )
    SELECT DISTINCT v_DOWNLOADDATE AS DOWNLOAD_DATE
            ,A.PKID AS ECL_MODEL_ID
            ,F.PF_SEGMENT_ID
            ,H.GROUP_SEGMENT
            ,H.SEGMENT
            ,H.SUB_SEGMENT
            ,G.BUCKET_GROUP
            ,B.EAD_MODEL_ID
            ,F.LT_RULE_ID
            ,F.EFFECTIVE_DATE AS LT_EFF_DATE
            ,F.SICR_RULE_ID
            ,C.CCF_FLAG
            ,CASE WHEN C.CCF_FLAG = 1 THEN C.CCF_RULES_ID END AS CCF_RULES_ID
            ,CASE WHEN C.CCF_FLAG = 1 THEN C.CCF_REVOLVING_FLAG END AS CCF_REVOLVING_FLAG
            ,CASE WHEN C.CCF_FLAG = 1 THEN C.CCF_COMMITED_FLAG END AS CCF_COMMITED_FLAG
            ,B.EFFECTIVE_DATE   AS CCF_EFF_DATE
            ,C.PREPAYMENT_FLAG
            ,CASE WHEN C.PREPAYMENT_FLAG = 1 THEN C.PREPAYMENT_RULES_ID END AS PREPAYMENT_RULES_ID
            ,B.EFFECTIVE_DATE   AS PREPAYMENT_EFF_DATE
            ,D.LGD_MODEL_ID     AS LGD_MODEL_ID
            ,D.FL_FLAG          AS LGD_FL_FLAG
            ,D.FL_MODEL_ID      AS LGD_FL_MODEL
            ,D.LGD_EFF_PERIOD   AS LGD_EFF_STARTTYPE
            ,D.LGD_MONTH        AS LGD_EFF_STARTMONTH
            ,D.LGD_DATE         AS LGD_EFF_DATE
            ,E.PD_MODEL_ID      AS PD_MODEL_ID
            ,E.FL_FLAG          AS PD_FL_FLAG
            ,E.FL_MODEL_ID      AS PD_FL_MODEL
            ,E.PD_EFF_PERIOD    AS PD_EFF_STARTTYPE
            ,E.PD_MONTH         AS PD_EFF_STARTMONTH
            ,E.PD_DATE          AS PD_EFF_DATE
        FROM IFRS_ECL_MODEL_HEADER A
        JOIN IFRS_ECL_MODEL_DETAIL_PF F     ON A.PKID = F.ECL_MODEL_ID
        JOIN IFRS_MSTR_SEGMENT_RULES_HEADER H ON H.PKID = F.PF_SEGMENT_ID AND H.IS_DELETED = 0
        JOIN IFRS_ECL_MODEL_DETAIL_EAD B    ON A.PKID = B.ECL_MODEL_ID AND F.PF_SEGMENT_ID = B.PF_SEGMENT_ID
        JOIN IFRS_EAD_RULES_CONFIG C        ON B.EAD_MODEL_ID = C.PKID AND C.IS_DELETED = 0
        JOIN IFRS_ECL_MODEL_DETAIL_LGD D    ON A.PKID = D.ECL_MODEL_ID AND F.PF_SEGMENT_ID = D.PF_SEGMENT_ID
        JOIN IFRS_ECL_MODEL_DETAIL_PD E     ON A.PKID = E.ECL_MODEL_ID AND F.PF_SEGMENT_ID = E.PF_SEGMENT_ID
        JOIN IFRS_PD_RULES_CONFIG G         ON G.PKID = E.PD_MODEL_ID AND G.IS_DELETED = 0
        WHERE C.IS_DELETED = 0
        AND A.PKID = v_ECLID;

    COMMIT;
END;