CREATE OR REPLACE PROCEDURE SP_IFRS_NOMINATIVE_TO_IMA (v_ECLID NUMBER DEFAULT(0), v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
BEGIN

    /***************************************************
    INITIALIZATION
    ***************************************************/
	UPDATE /*+ PARALLEL(8) */ IFRS_MASTER_ACCOUNT
	SET EAD_AMOUNT          = NULL,
		ECL_AMOUNT          = NULL,
		LIFETIME            = NULL,
		RESERVED_RATE_1     = NULL,
		RESERVED_RATE_2     = NULL,
		RESERVED_RATE_3     = NULL,
		RESERVED_RATE_4     = NULL,
		RESERVED_RATE_5     = NULL,
		RESERVED_RATE_6     = NULL,
		RESERVED_AMOUNT_14  = CASE WHEN DATA_SOURCE <> 'LIMIT' THEN NULL ELSE RESERVED_AMOUNT_14 END,
		RESERVED_AMOUNT_15  = NULL,
		RESERVED_AMOUNT_16  = NULL,
		RESERVED_AMOUNT_18  = NULL,
		RESERVED_AMOUNT_19  = NULL,
		RESERVED_VARCHAR_25 = NULL,
		IA_UNWINDING_AMOUNT = NULL,
		IMPAIRED_FLAG       = NULL
	WHERE DOWNLOAD_dATE = v_DOWNLOADDATE;COMMIT;

    /*****************************************************************************
    UPDATE EAD_AMOUNT, CCF, PREPAYMENT RATE, UNUSED AMOUNT FROM EAD RESULT TO IMA
    ******************************************************************************/
	MERGE INTO IFRS_MASTER_ACCOUNT A
	USING (SELECT MASTERID, EAD_AMOUNT, CCF_RATE, PREPAYMENT_RATE, CCF_AMOUNT, PREPAYMENT_AMOUNT, UNUSED_AMOUNT FROM IFRS_EAD_RESULT WHERE COUNTER = 1 AND DOWNLOAD_DATE = v_DOWNLOADDATE)B
	ON (A.MASTERID = B.MASTERID AND A.DOWNLOAD_DATE = v_DOWNLOADDATE)
	WHEN MATCHED THEN UPDATE
	SET A.EAD_AMOUNT = B.EAD_AMOUNT,
		A.RESERVED_RATE_1 = CCF_RATE*100,
		A.RESERVED_RATE_2 = PREPAYMENT_RATE*100,
		A.RESERVED_RATE_3 = B.CCF_AMOUNT,
		A.RESERVED_RATE_4 = B.PREPAYMENT_AMOUNT,
        A.RESERVED_AMOUNT_14 = CASE WHEN DATA_SOURCE <> 'LIMIT' THEN B.UNUSED_AMOUNT ELSE A.RESERVED_AMOUNT_14 END;
	COMMIT;

    /*******************************************
    COPY AVAILABLE BI AMOUNT FROM LIMIT TO IMA
    ********************************************/
	MERGE INTO IFRS_MASTER_ACCOUNT A
	USING (
		SELECT ACCOUNT_NUMBER,RESERVED_AMOUNT_13,RESERVED_AMOUNT_14,RESERVED_AMOUNT_15,RESERVED_AMOUNT_16 FROM IFRS_MASTER_ACCOUNT WHERE DOWNLOAD_dATE = v_DOWNLOADDATE AND DATA_SOURCE = 'LIMIT'
	)B
	ON (A.FACILITY_NUMBER = B.ACCOUNT_NUMBER AND A.DOWNLOAD_dATE = v_DOWNLOADDATE AND A.DATA_SOURCE IN ('ILS','CRD','KTP','BTRD','PBMM'))
	WHEN MATCHED THEN
		UPDATE SET A.RESERVED_AMOUNT_16 = B.RESERVED_AMOUNT_14 WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE;
	COMMIT;


    /******************************************************************************
    UPDATE ECL AMOUNT, SPECIAL REASON, IMPAIRED FLAG FROM ECL RESULT DETAIL TO IMA
    ******************************************************************************/
	MERGE INTO IFRS_MASTER_ACCOUNT A
	USING (
		SELECT MASTERID, CCF_AMOUNT, PREPAYMENT_AMOUNT, LIFETIME_PERIOD, ECL_AMOUNT_ON_BS, ECL_AMOUNT_OFF_BS, ECL_AMOUNT,
               SPECIAL_REASON,UNUSED_AMOUNT,IMPAIRED_FLAG,ECL_AMOUNT_FINAL,ECL_AMOUNT_ON_BS_FINAL
        FROM IFRS_ECL_RESULT_DETAIL
        WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
        AND ECL_MODEL_ID = V_ECLID
    )B
	ON (A.MASTERID = B.MASTERID AND A.DOWNLOAD_DATE = v_DOWNLOADDATE)
	WHEN MATCHED THEN UPDATE
	SET A.ECL_AMOUNT = B.ECL_AMOUNT,
		A.LIFETIME = B.LIFETIME_PERIOD,
		A.RESERVED_AMOUNT_18 = B.ECL_AMOUNT_ON_BS,
		A.RESERVED_AMOUNT_19 = B.ECL_AMOUNT_OFF_BS,
		A.RESERVED_VARCHAR_25 = B.SPECIAL_REASON,
		A.IMPAIRED_FLAG = B.IMPAIRED_FLAG;
	COMMIT;


    /*****************************************************
    UPDATE IA UNWINDING FROM TBLT_PAYMENTEXPECTED TO IMA
    ******************************************************/
	MERGE into ifrs_master_account C
	using (
		SELECT SUM(UNWIND_BALANCE)UNWIND_BALANCE, A.MASTERID
		FROM (SELECT MAX(OVERRIDEID)OVERRIDE,MASTERID,UNWIND_BALANCE,EFFECTIVE_DATE,ESTIMATED_REALIZE_DATE FROM TBLT_PAYMENTEXPECTED GROUP BY MASTERID, UNWIND_BALANCE, EFFECTIVE_DATE,ESTIMATED_REALIZE_DATE) A
		INNER JOIN (
			SELECT MAX(EFFECTIVE_DATE) AS MAX_EFF_DATE, MASTERID
			FROM TBLT_PAYMENTEXPECTED WHERE EFFECTIVE_DATE <= v_DOWNLOADDATE GROUP BY MASTERID
		) B
		ON A.MASTERID = B.MASTERID
		AND A.EFFECTIVE_DATE = B.MAX_EFF_DATE WHERE ESTIMATED_REALIZE_DATE <= v_DOWNLOADDATE
		GROUP BY A.MASTERID
	) D
	ON (C.MASTERID = D.MASTERID AND C.DOWNLOAD_DATE = v_DOWNLOADDATE AND (C.OUTSTANDING+C.RESERVED_AMOUNT_14)>0)
	WHEN MATCHED THEN UPDATE
	SET C.IA_UNWINDING_AMOUNT = D.UNWIND_BALANCE
	WHERE C.IMPAIRED_FLAG = 'I';
	COMMIT;

    /**********************************************
    UPDATE ECL AMOUNT FINAL TO ECL RESULT DETAIL
    **********************************************/
    MERGE INTO IFRS_ECL_RESULT_DETAIL A
    USING (
        SELECT
            MASTERID,
            NVL(
                CASE
                    WHEN (DATA_SOURCE = 'ILS' AND PRODUCT_CODE LIKE 'B%')
                          OR (DATA_SOURCE IN ('PBMM','KTP') AND NVL(RESERVED_FLAG_1, 0) = 0)
                          OR (DATA_SOURCE = 'BTRD' AND NVL(RESERVED_FLAG_1, 0) = 0)
                    THEN 0
                    ELSE OUTSTANDING
                END, 0)
            + NVL(CASE WHEN NVL(UNAMORT_BENEFIT, UNAMORT_FEE_AMT)> 0 THEN 0 ELSE NVL(UNAMORT_BENEFIT, UNAMORT_FEE_AMT) END , 0)
            + NVL(IA_UNWINDING_AMOUNT, 0)  AS NJUM
        FROM IFRS_MASTER_ACCOUNT WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
    )B
    ON (A.MASTERID = B.MASTERID AND A.DOWNLOAD_DATE = v_DOWNLOADDATE AND A.ECL_MODEL_ID = V_ECLID)
    WHEN MATCHED THEN UPDATE
    SET A.ECL_AMOUNT_ON_BS_FINAL = CASE WHEN A.ECL_AMOUNT_ON_BS < B.NJUM THEN A.ECL_AMOUNT_ON_BS ELSE B.NJUM END,
        A.ECL_AMOUNT_FINAL       = (CASE WHEN A.ECL_AMOUNT_ON_BS < B.NJUM THEN A.ECL_AMOUNT_ON_BS ELSE B.NJUM END) + ECL_AMOUNT_OFF_BS
   WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE;
   COMMIT;

    UPDATE /*+ PARALLEL(8) */ IFRS_ECL_RESULT_DETAIL
    SET ECL_AMOUNT_ON_BS_FINAL = CASE WHEN ECL_AMOUNT_ON_BS_FINAL < 0 THEN 0 ELSE ECL_AMOUNT_ON_BS_FINAL END,
        ECL_AMOUNT_FINAL       = CASE WHEN ECL_AMOUNT_FINAL < 0 THEN 0 ELSE ECL_AMOUNT_FINAL END
        WHERE DOWNLOAD_DATE = V_DOWNLOADDATE
        AND ECL_MODEL_ID = V_ECLID;
        COMMIT;

    /**********************************************
    UPDATE ECL AMOUNT FINAL TO IMA
    **********************************************/
    MERGE INTO IFRS_MASTER_ACCOUNT A
    USING (
        SELECT MASTERID, CCF_AMOUNT, PREPAYMENT_AMOUNT, LIFETIME_PERIOD, ECL_AMOUNT_ON_BS, ECL_AMOUNT_OFF_BS, ECL_AMOUNT,
               SPECIAL_REASON,UNUSED_AMOUNT, IMPAIRED_FLAG,ECL_AMOUNT_FINAL,ECL_AMOUNT_ON_BS_FINAL
        FROM IFRS_ECL_RESULT_DETAIL
        WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
        AND ECL_MODEL_ID = V_ECLID
    )B
    ON (A.MASTERID = B.MASTERID AND A.DOWNLOAD_DATE = v_DOWNLOADDATE)
    WHEN MATCHED THEN UPDATE
        SET A.RESERVED_RATE_5 = B.ECL_AMOUNT_ON_BS_FINAL,
            A.RESERVED_RATE_6 = B.ECL_AMOUNT_FINAL WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE;
    COMMIT;

   /******************************************************************************
    UPDATE ECL RESULT HEADER
   ******************************************************************************/
   MERGE INTO IFRS_ECL_RESULT_HEADER A
   USING(
       SELECT
            DOWNLOAD_DATE, ECL_MODEL_ID, PF_SEGMENT_ID, SUB_SEGMENT,
            DATA_SOURCE, PRODUCT_CODE, BUCKET_GROUP, BUCKET_ID, CR_STAGE,
            SUM(ECL_AMOUNT_FINAL * NVL(EXCHANGE_RATE,1)) AS ECL_AMOUNT_FINAL
        FROM IFRS_ECL_RESULT_DETAIL
        WHERE DOWNLOAD_DATE = v_DOWNLOADDATE
        AND ECL_MODEL_ID = V_ECLID
        GROUP BY
            DOWNLOAD_DATE, ECL_MODEL_ID, PF_SEGMENT_ID, SUB_SEGMENT,
            DATA_SOURCE, PRODUCT_CODE, BUCKET_GROUP, BUCKET_ID, CR_STAGE
   )B
   ON (
        TRIM(A.DOWNLOAD_DATE)          = TRIM(B.DOWNLOAD_DATE) AND
        TRIM(A.ECL_MODEL_ID)           = TRIM(B.ECL_MODEL_ID)  AND
        TRIM(A.PF_SEGMENT_ID)          = TRIM(B.PF_SEGMENT_ID) AND
        TRIM(A.SUB_SEGMENT)            = TRIM(B.SUB_SEGMENT)   AND
        TRIM(A.DATA_SOURCE)            = TRIM(B.DATA_SOURCE)   AND
        TRIM(A.PRODUCT_CODE)           = TRIM(B.PRODUCT_CODE)  AND
        NVL(TRIM(A.BUCKET_GROUP),' ')  = NVL(TRIM(B.BUCKET_GROUP),' ')  AND
        TRIM(A.BUCKET_ID)              = TRIM(B.BUCKET_ID)     AND
        TRIM(A.CR_STAGE)               = TRIM(B.CR_STAGE)
     )
    WHEN MATCHED THEN UPDATE
        SET A.ECL_AMOUNT_FINAL = B.ECL_AMOUNT_FINAL WHERE A.DOWNLOAD_DATE = v_DOWNLOADDATE;
    COMMIT;

    DELETE /*+ PARALLEL(8) */ IFRS_MASTER_ACCOUNT_MONTHLY
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE;
    COMMIT;

    INSERT /*+ PARALLEL(8) */ INTO IFRS_MASTER_ACCOUNT_MONTHLY
    SELECT * FROM IFRS_MASTER_ACCOUNT
    WHERE DOWNLOAD_DATE = v_DOWNLOADDATE;
    COMMIT;

END;