CREATE OR REPLACE PROCEDURE SP_IFRS_GENERATE_RULE_SEGMENT (v_CONSTNAME VARCHAR2 DEFAULT ' ', v_PRC_CODE CHAR DEFAULT 'M')
AS
  v_RULE_ID varchar2(250);
  v_GROUP_SEGMENT varchar2(50);
  v_SEGMENT varchar2(50);
  v_SUB_SEGMENT varchar2(100);
  v_SEGMENT_TYPE varchar2(25);
  v_SEQUENCE number(10);
  v_TABLE_NAME varchar2(30);
  v_OWNER    VARCHAR2(20);

  CURSOR seg1 IS
  SELECT DISTINCT
    B.RULE_ID,
    A.GROUP_SEGMENT,
    A.SEGMENT,
    A.SUB_SEGMENT,
    A.SEGMENT_TYPE,
    A.SEQUENCE,
    B.TABLE_NAME
  FROM IFRS_MSTR_SEGMENT_RULES_HEADER a
  INNER JOIN IFRS_MSTR_SEGMENT_RULES_DETAIL b
  ON A.PKID = B.RULE_ID
  AND (A.SEGMENT_TYPE = v_CONSTNAME OR NVL(v_CONSTNAME, ' ') = ' ')
  WHERE IS_DELETED = 0;


BEGIN
  SELECT USERNAME INTO v_OWNER FROM USER_USERS;

  DBMS_STATS.unlock_table_stats(v_OWNER, 'GTMP_SCENARIO_SEGMENT_GENQUERY');
  DBMS_STATS.DELETE_table_stats(v_OWNER, 'GTMP_SCENARIO_SEGMENT_GENQUERY');
  EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_SCENARIO_SEGMENT_GENQUERY';

  OPEN seg1;
  FETCH seg1 INTO v_RULE_ID, v_GROUP_SEGMENT, v_SEGMENT, v_SUB_SEGMENT, v_SEGMENT_TYPE, v_SEQUENCE, v_TABLE_NAME;
  WHILE seg1%FOUND
  LOOP


    INSERT INTO GTMP_SCENARIO_SEGMENT_GENQUERY (RULE_ID, GROUP_SEGMENT, SEGMENT, SUB_SEGMENT, SEGMENT_TYPE, SEQUENCE, TABLE_NAME, CONDITION, PRC_CODE)
      VALUES (v_RULE_ID, v_GROUP_SEGMENT, v_SEGMENT, v_SUB_SEGMENT, v_SEGMENT_TYPE, v_SEQUENCE, v_TABLE_NAME, FN_GENERATE_RULE_SEGMENT(v_RULE_ID), v_PRC_CODE);

    COMMIT;

    FETCH seg1 INTO v_RULE_ID, v_GROUP_SEGMENT, v_SEGMENT, v_SUB_SEGMENT, v_SEGMENT_TYPE, v_SEQUENCE, v_TABLE_NAME;

  END LOOP;
  CLOSE seg1;
END;