---- DROP PROCEDURE SP_IFRS_ACCT_AMORT_RESTRU;

CREATE OR REPLACE PROCEDURE SP_IFRS_ACCT_AMORT_RESTRU(
    IN P_RUNID VARCHAR(20) DEFAULT 'S_00000_0000',
    IN P_DOWNLOAD_DATE DATE DEFAULT NULL,
    IN P_PRC VARCHAR(1) DEFAULT 'S')
LANGUAGE PLPGSQL AS $$
DECLARE
    ---- DATE
    V_PREVDATE DATE;
    V_CURRDATE DATE;

    ---- QUERY   
    V_STR_QUERY TEXT;

    ---- TABLE LIST       
    V_TABLENAME VARCHAR(100);
    V_TABLEINSERT1 VARCHAR(100);
    V_TABLEINSERT2 VARCHAR(100);
    V_TABLEINSERT3 VARCHAR(100);
    
    ---- CONDITION
    V_RETURNROWS INT;
    V_RETURNROWS2 INT;
    V_TABLEDEST VARCHAR(100);
    V_COLUMNDEST VARCHAR(100);
    V_SPNAME VARCHAR(100);
    V_OPERATION VARCHAR(100);

    ---- RESULT
    V_QUERYS TEXT;

    --- VARIABLE
    V_SP_NAME VARCHAR(100);
    STACK TEXT; 
    FCESIG TEXT;
BEGIN 
    -------- ====== VARIABLE ======
	GET DIAGNOSTICS STACK = PG_CONTEXT;
	FCESIG := substring(STACK from 'function (.*?) line');
	V_SP_NAME := UPPER(LEFT(fcesig::regprocedure::text, POSITION('(' in fcesig::regprocedure::text)-1));

    IF COALESCE(P_PRC, NULL) IS NULL THEN
        P_PRC := 'S';
    END IF;

    IF COALESCE(P_RUNID, NULL) IS NULL THEN
        P_RUNID := 'S_00000_0000';
    END IF;

    IF P_PRC = 'S' THEN 
        V_TABLENAME := 'TMP_IMA_' || P_RUNID || '';
        V_TABLEINSERT1 := 'IFRS_IMA_AMORT_PREV_' || P_RUNID || '';
        V_TABLEINSERT2 := 'IFRS_IMA_AMORT_CURR_' || P_RUNID || '';
        V_TABLEINSERT3 := 'IFRS_IMA_AMORT_RESTRU_' || P_RUNID || '';
    ELSE 
        V_TABLENAME := 'IFRS_MASTER_ACCOUNT';
        V_TABLEINSERT1 := 'IFRS_IMA_AMORT_PREV';
        V_TABLEINSERT2 := 'IFRS_IMA_AMORT_CURR';
        V_TABLEINSERT3 := 'IFRS_ACCT_AMORT_RESTRU';
    END IF;
    
    IF P_DOWNLOAD_DATE IS NULL 
    THEN
        SELECT
            CURRDATE, PREVDATE INTO V_CURRDATE, V_PREVDATE
        FROM
            IFRS_PRC_DATE;
    ELSE        
        V_CURRDATE := P_DOWNLOAD_DATE;
        V_PREVDATE := V_CURRDATE - INTERVAL '1 DAY';
    END IF;
    
    V_RETURNROWS2 := 0;
    -------- ====== VARIABLE ======

    -------- ====== PRE SIMULATION TABLE ======
    IF P_PRC = 'S' THEN
        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'DROP TABLE IF EXISTS ' || V_TABLEINSERT3 || ' ';
        EXECUTE (V_STR_QUERY);

        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || 'CREATE TABLE ' || V_TABLEINSERT3 || ' AS SELECT * FROM IFRS_ACCT_AMORT_RESTRU WHERE 1=0 ';
        EXECUTE (V_STR_QUERY);
    END IF;
    -------- ====== PRE SIMULATION TABLE ======

    -------- ====== BODY ======
    CALL SP_IFRS_LOG_AMORT(V_CURRDATE, 'START', 'SP_IFRS_ACCT_AMORT_RESTRU', '');

    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_TABLEINSERT3 || ' WHERE DOWNLOAD_DATE = ''' || CAST(V_CURRDATE AS VARCHAR(10)) || '''::DATE ';
    EXECUTE (V_STR_QUERY);
    
    ---- INSERT RESTRU IN BTPN
    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'INSERT INTO ' || V_TABLEINSERT3 || ' 
        (
            DOWNLOAD_DATE 
            ,DATA_SOURCE 
            ,MASTERID 
            ,PREV_MASTERID 
            ,ACCOUNT_NUMBER 
            ,PREV_ACCOUNT_NUMBER 
            ,RESTRUCTURE_DATE 
            ,PRODUCT_CODE 
            ,PRODUCT_TYPE 
            ,PRODUCT_GROUP 
            ,BRANCH_CODE 
            ,PREV_BRANCH_CODE 
            ,CIFNO 
            ,CCY 
            ,EIR 
            ,PREV_EIR 
            ,METHOD 
            ,OUTSTANDING 
            ,PREV_UNAMORT_FEE_AMT 
            ,PREV_UNAMORT_COST_AMT 
            ,UNAMORT_FEE_AMT 
            ,UNAMORT_COST_AMT 
            ,ADJ_VALUE 
        ) SELECT 
            A.DOWNLOAD_DATE 
            ,A.DATA_SOURCE 
            ,A.MASTERID 
            ,A.PREVIOUS_ACCOUNT_NUMBER AS PREV_MASTERID 
            ,A.ACCOUNT_NUMBER AS ACCOUNT_NUMBER 
            ,B.ACCOUNT_NUMBER AS PREV_ACCOUNT_NUMBER 
            ,A.RESTRUCTURE_DATE 
            ,A.PRODUCT_CODE 
            ,A.PRODUCT_TYPE 
            ,A.PRODUCT_GROUP 
            ,A.BRANCH_CODE 
            ,B.BRANCH_CODE AS PREV_BRANCH_CODE 
            ,A.CUSTOMER_NUMBER AS CIFNO 
            ,A.CURRENCY AS CCY 
            ,A.EIR 
            ,B.EIR AS PREV_EIR 
            ,A.AMORT_TYPE  AS METHOD 
            ,A.OUTSTANDING 
            ,B.UNAMORT_FEE_AMT AS PREV_UNAMORT_FEE_AMT 
            ,B.UNAMORT_COST_AMT AS PREV_UNAMORT_COST_AMT 
            ,A.UNAMORT_FEE_AMT 
            ,A.UNAMORT_COST_AMT 
            ,0 AS ADJ_VALUE 
        FROM ' || V_TABLEINSERT2 || ' A 
        JOIN ' || V_TABLEINSERT1 || ' B 
        ON A.PREVIOUS_ACCOUNT_NUMBER = B.MASTERID 
        AND A.RESTRUCTURE_DATE = ''' || CAST(V_CURRDATE AS VARCHAR(10)) || '''::DATE 
        AND A.CURRENCY = B.CURRENCY ';
    EXECUTE (V_STR_QUERY);

    GET DIAGNOSTICS V_RETURNROWS = ROW_COUNT;
    V_RETURNROWS2 := V_RETURNROWS2 + V_RETURNROWS;
    V_RETURNROWS := 0;

    V_STR_QUERY := '';
    V_STR_QUERY := V_STR_QUERY || 'UPDATE ' || V_TABLEINSERT3 || ' A 
        SET 
            CNT = B.CNT 
            ,PRORATE_UNAMORT_FEE = CASE WHEN COALESCE(B.TOTAL_OS, 0) = 0 
                THEN A.PREV_UNAMORT_FEE_AMT / B.CNT 
                ELSE A.PREV_UNAMORT_FEE_AMT * (A.OUTSTANDING::FLOAT / B.TOTAL_OS::FLOAT) END 
            ,PRORATE_UNAMORT_COST = CASE WHEN COALESCE(B.TOTAL_OS, 0) = 0 
                THEN A.PREV_UNAMORT_COST_AMT / B.CNT 
                ELSE A.PREV_UNAMORT_COST_AMT * (A.OUTSTANDING::FLOAT / B.TOTAL_OS::FLOAT) END 
        FROM (
            SELECT 
                PREV_MASTERID 
                ,SUM(OUTSTANDING) AS TOTAL_OS 
                ,COUNT(1) AS CNT 
            FROM ' || V_TABLEINSERT3 || ' 
            WHERE DOWNLOAD_DATE = ''' || CAST(V_CURRDATE AS VARCHAR(10)) || '''::DATE 
            GROUP BY PREV_MASTERID 
        ) B 
        WHERE A.PREV_MASTERID = B.PREV_MASTERID 
        AND A.DOWNLOAD_DATE = ''' || CAST(V_CURRDATE AS VARCHAR(10)) || '''::DATE ';
    EXECUTE (V_STR_QUERY);
    ---- END INSERT RESTRU IN BTPN

    ---- END
    CALL SP_IFRS_LOG_AMORT(V_CURRDATE, 'END', 'SP_IFRS_ACCT_AMORT_RESTRU', '');

    RAISE NOTICE 'SP_IFRS_ACCT_AMORT_RESTRU | AFFECTED RECORD : %', V_RETURNROWS2;
    ---------- ====== BODY ======

    -------- ====== LOG ======
    V_TABLEDEST = V_TABLEINSERT3;
    V_COLUMNDEST = '-';
    V_SPNAME = 'SP_IFRS_ACCT_AMORT_RESTRU';
    V_OPERATION = 'INSERT';
    
    CALL SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SPNAME, V_OPERATION, V_RETURNROWS2, P_RUNID);
    -------- ====== LOG ======

    -------- ====== RESULT ======
    V_QUERYS = 'SELECT * FROM ' || V_TABLEINSERT3 || '';
    CALL SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SPNAME, V_RETURNROWS2, P_RUNID);
    -------- ====== RESULT ======

END;

$$;