SELECT REPLACE(REPLACE(REPLACE(PG_GET_INDEXDEF(FORMAT('%I.%I', SCHEMANAME, INDEXNAME)::REGCLASS), ' INDEX ', ' INDEX IF NOT EXISTS ')||';',INDEXNAME,LOWER('NCI_' || 'TEST')),TABLENAME,LOWER('TEST'))
FROM PG_INDEXES
WHERE SCHEMANAME = 'public'
AND TABLENAME = 'ifrs_master_account';

SELECT * FROM PG_INDEXES
WHERE SCHEMANAME = 'public'
AND TABLENAME = 'ifrs_pd_scenario_data';

SELECT F_EOMONTH('2025-03-31'::DATE, 12, 'M', 'PREV')

show work_mem;

-- SET work_mem TO '2000MB'

select pg_reload_conf();

select pg_hba_file_rules();

-- SET work_mem TO '2000MB';

--55.430.744

SELECT google_columnar_engine_recommend();

SELECT database_name, schema_name, relation_name, column_name FROM g_columnar_recommended_columns;

SELECT MASTERID, OUTSTANDING, CAST(OUTSTANDING AS MONEY) AS OUTS FROM TMP_IMA_S_00000_0000 WHERE MASTERID = '1CJVK0_03021CJVK0001_CI'


CREATE INDEX IF NOT EXISTS NCI_IFRS_IMP_PD_FL_TERM_STRUCTURE
ON IFRS_IMP_PD_FL_TERM_STRUCTURE  USING BTREE
(DOWNLOAD_DATE ASC NULLS LAST, PD_EFFECTIVE_DATE ASC NULLS LAST, SCALAR_EFFECTIVE_DATE ASC NULLS LAST, BUCKET_ID ASC NULLS LAST, FL_SEQ ASC NULLS LAST)
TABLESPACE PG_DEFAULT