TRUNCATE TABLE IFRS_LOGS_PROCESS;
TRUNCATE TABLE IFRS_RESULT_PREVIEW;
TRUNCATE TABLE IFRS_RUNNING_LOGS;

CALL SP_IFRS_IMP_SIMULATION_DATA();
CALL SP_IFRS_INITIAL_UPDATE();
CALL SP_IFRS_IMPI_JOURNAL_DATA(); ---- TIDAK ADA RESULT
CALL SP_IFRS_IMP_FILL_IMA_PREV_CURR();
CALL SP_IFRS_IMP_AVG_EIR();
CALL SP_IFRS_IMP_INSERT_DEFAULT();
CALL SP_IFRS_IMP_DEFAULT_RULE();
CALL SP_IFRS_IMP_PD_SCENARIO_DATA();
CALL SP_IFRS_IMP_DEFAULT_RATE();
CALL SP_IFRS_IMP_PD_CHR_SUMM(); ---- DATA PD CHR TIDAK ADA
CALL SP_IFRS_IMP_PD_CHR_RESULT(); ---- DATA PD CHR TIDAK ADA
CALL SP_IFRS_IMP_PD_MAA_DETAIL();
CALL SP_IFRS_IMP_PD_MAA_ENR();
CALL SP_IFRS_IMP_PD_MAA_AVERAGE();
CALL SP_IFRS_IMP_PD_MAA_MMULT();
CALL SP_IFRS_IMP_PD_MAA_RESULT();
CALL SP_IFRS_IMP_PD_TERM_YEARLY();
CALL SP_IFRS_IMP_PD_YEAR_TO_MONTH();
CALL SP_IFRS_IMP_PD_FL_TERM_YEARLY();
CALL SP_IFRS_IMP_PD_FL_YEAR_TO_MONTH();
CALL SP_IFRS_IMP_UPDATE_WO_RECOVERY_PORTFOLIO();
CALL SP_IFRS_IMP_RECOVERY_SCENARIO_DATA();
CALL SP_IFRS_IMP_WO_SCENARIO_DATA();
CALL SP_IFRS_IMP_LGD_SCENARIO_DATA();
CALL SP_IFRS_IMP_LGD_CURE_LGL_DETAIL();
CALL SP_IFRS_IMP_LGD_CURE_LGL_HEADER();
CALL SP_IFRS_IMP_CCF_SCENARIO_DATA();
CALL SP_IFRS_IMP_EAD_CCF_DETAIL();
CALL SP_IFRS_IMP_EAD_CCF_HEADER();
CALL SP_IFRS_IMP_ECL_GENERATE_IMA();
CALL SP_IFRS_IMP_DEFAULT_RULE_ECL();
CALL SP_IFRS_IMP_EXEC_RULE_STAGE();
CALL SP_IFRS_IMP_ECL_EAD_RESULT_NONPRK();
CALL SP_IFRS_IMP_ECL_EAD_RESULT_PRK();
----- TESTING
CALL SP_IFRS_ECL_RESULT_DETAIL();
CALL SP_IFRS_IMP_SYNC_IMA_MONTHLY();