CREATE OR REPLACE PROCEDURE IFRS9_BCA.SP_IFRS_RUNNING_LOG
(
    P_DOWNLOAD_DATE IN DATE DEFAULT NULL,
    P_STORENAME     IN VARCHAR2 DEFAULT NULL,
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_PROCESS_ID    IN NUMBER DEFAULT NULL,
    P_PROCESS_DATE  IN DATE DEFAULT NULL
)
AS
BEGIN
    INSERT INTO IFRS9_BCA.IFRS_RUNNING_LOGS 
    (
        DOWNLOAD_DATE, SP_NAME, RUN_ID, PROCESS_ID, PROCESS_DATE
    )
    VALUES 
    (
        P_DOWNLOAD_DATE,
        P_STORENAME,
        P_RUNID,
        NVL(P_PROCESS_ID, NULL),   -- Atau misal ingin runtime PID → SYS_CONTEXT
        SYSTIMESTAMP
    );
END SP_IFRS_RUNNING_LOG;