CREATE OR REPLACE PROCEDURE IFRS9_BCA.SP_IFRS_EXEC_AND_LOG
(
    P_DOWNLOAD_DATE    IN DATE DEFAULT NULL,
    P_TABLE_DEST       IN VARCHAR2 DEFAULT NULL,
    P_COLUMN_DEST      IN VARCHAR2 DEFAULT NULL,
    P_STORENAME        IN VARCHAR2 DEFAULT NULL,
    P_OPERATION        IN VARCHAR2 DEFAULT NULL,
    P_AFFECTED_RECORD  IN NUMBER DEFAULT NULL,
    P_RUNID            IN VARCHAR2 DEFAULT 'S_00000_0000'
)
AS
BEGIN
    INSERT INTO IFRS9_BCA.IFRS_LOGS_PROCESS
        (DOWNLOAD_DATE,
         TABLE_DEST,
         COLUMN_DEST,
         SP_NAME,
         OPERATION,
         RUN_ID,
         PROCESS_ID,
         AFFECTED_RECORD,
         PROCESS_DATE)
    VALUES
        (P_DOWNLOAD_DATE,
         P_TABLE_DEST,
         P_COLUMN_DEST,
         P_STORENAME,
         P_OPERATION,
         P_RUNID,
         TO_NUMBER(SYS_CONTEXT('USERENV', 'SESSIONID')),  
         P_AFFECTED_RECORD,
         SYSTIMESTAMP);  

END SP_IFRS_EXEC_AND_LOG;