CREATE OR REPLACE FUNCTION F_CNT_DAYS_30_360(
	P_START_DATE DATE,
	P_END_DATE DATE)
    RETURNS INTEGER
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE 
    Y1 INTEGER;
    M1 INTEGER;
    D1 INTEGER;

    Y2 INTEGER;
    M2 INTEGER;
    D2 INTEGER;
BEGIN
    Y1 := EXTRACT(YEAR FROM P_START_DATE);
    M1 := EXTRACT(MONTH FROM P_START_DATE);
    D1 := EXTRACT(DAY FROM P_START_DATE);

    Y2 := EXTRACT(YEAR FROM P_END_DATE);
    M2 := EXTRACT(MONTH FROM P_END_DATE);
    D2 := EXTRACT(DAY FROM P_END_DATE);
    
    IF D1 = 31 THEN
        D1 := 30;
    END IF;

    IF D2 = 31 AND (D1 = 30 OR D1 = 31) THEN 
        D2 := 30;
    END IF;

    RETURN 360 * (Y2 - Y1) + 30 * (M2 - M1) + (D2 - D1);
END;
$BODY$;
