CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_TERM_STRUCTURE (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    -- DATES / COUNTERS
    V_CURRDATE      DATE;
    V_PREVDATE      DATE;
    V_MODEL_ID      NUMBER;
    V_COUNT         NUMBER;

    -- DYNAMIC SQL
    V_STR_QUERY     CLOB;

    -- TABLE NAMES
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_GTMP_PD_TERM_STRUCTURE1  VARCHAR2(100);
    V_IFRS_PD_MAA_MMULT 	VARCHAR2(100);
    V_IFRS_PD_TERM_STRUCTURE  VARCHAR2(100);
    V_TABLEPDCONFIG VARCHAR2(100);

    -- MISC
    V_RETURNROWS    NUMBER;
    V_RETURNROWS2   NUMBER;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);
    V_MONTH_SEQ NUMBER;
    V_MMULT_FIN BINARY_DOUBLE;

    -- RESULT QUERY
    V_QUERYS        CLOB;

    TYPE REF_CURSOR IS REF CURSOR;
    C_RULE REF_CURSOR;

    V_EFF_DATE DATE;
    V_BASE_DATE DATE;
    V_SCENARIO_NO NUMBER;
    V_MODELS_ID VARCHAR2(22);
    V_PD_RULE_ID VARCHAR2(100);
    V_FL_SEQ NUMBER;
    V_INCREMENT_PERIOD NUMBER;
    V_BUCKET_GROUP VARCHAR2(100);
    V_BUCKET_FROM NUMBER;
    V_MMULT NUMBER;
    V_PD_METHOD VARCHAR2(100);
    V_PD_RULE_NAME VARCHAR2(100);
    V_MAX_BUCKET_ID NUMBER;

BEGIN
    -- SET PROCEDURE NAME
    V_SP_NAME := 'SP_IFRS_PD_TERM_STRUCTURE';
    
    -- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
          INTO V_CURRDATE
          FROM PSAK413.IFRS_PRC_DATE; 
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    IF P_SYSCODE <> '0' THEN
   		V_MODEL_ID := 1;
    ELSE
    	V_MODEL_ID := 0;
    END IF;

    IF P_PRC = 'S' THEN
        V_GTMP_PD_TERM_STRUCTURE1 := 'GTMP_IFRS_PD_TERM_STRUCTURE1_' || P_RUNID;
        V_IFRS_PD_MAA_MMULT := 'IFRS_PD_MAA_MMULT_' || P_RUNID;
        V_IFRS_PD_TERM_STRUCTURE := 'IFRS_PD_TERM_STRUCTURE_' || P_RUNID;
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG_' || P_RUNID;
    ELSE
        V_GTMP_PD_TERM_STRUCTURE1 := 'GTMP_IFRS_PD_TERM_STRUCTURE1';
        V_IFRS_PD_MAA_MMULT := 'IFRS_PD_MAA_MMULT';
        V_IFRS_PD_TERM_STRUCTURE := 'IFRS_PD_TERM_STRUCTURE';
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG';
    END IF;

    IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('GTMP_IFRS_PD_TERM_STRUCTURE1', V_GTMP_PD_TERM_STRUCTURE1);
        -- PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_MAA_MMULT', V_IFRS_PD_MAA_MMULT);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_TERM_STRUCTURE', V_IFRS_PD_TERM_STRUCTURE);
        -- PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_RULES_CONFIG', V_TABLEPDCONFIG);
    END IF;
    COMMIT;

    PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
    COMMIT;

    V_STR_QUERY := 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_GTMP_PD_TERM_STRUCTURE1;
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    --------------------------------------------------------------------
    -- DYNAMIC DELETE
    --------------------------------------------------------------------
    V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_TERM_STRUCTURE || ' A ' ||
             'WHERE A.PD_METHOD = ''MAA'' ' ||
             '  AND A.MODEL_ID = 0 ' ||
             '  AND (A.PD_RULE_ID IN (SELECT PKID FROM ' || V_TABLEPDCONFIG || ')) ' ||
             '  AND A.EFF_DATE = :1';

    EXECUTE IMMEDIATE V_STR_QUERY USING V_CURRDATE;
    --------------------------------------------------------------------
    -- CONDITIONAL DELETE
    --------------------------------------------------------------------
    IF V_MODEL_ID = 0 
    THEN
            V_STR_QUERY := ' DELETE FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_TERM_STRUCTURE || ' A
            WHERE A.EFF_DATE  = :1
            AND A.PD_METHOD = ''MAA''
            AND A.MODEL_ID  = 0';
            EXECUTE IMMEDIATE V_STR_QUERY USING V_CURRDATE;
    END IF;
   
    COMMIT;

    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_GTMP_PD_TERM_STRUCTURE1 || '
        (EFF_DATE, BASE_DATE, SCENARIO_NO, MODEL_ID, PD_RULE_ID, FL_SEQ, INCREMENT_PERIOD, BUCKET_GROUP, BUCKET_FROM, MMULT, PD_METHOD,
         PD_RULE_NAME, MAX_BUCKET_ID)
        SELECT A.EFF_DATE, TO_DATE(A.BASE_DATE,''YYYY-MM-DD'') AS BASE_DATE, A.SCENARIO_NO, A.MODEL_ID,
            A.PD_RULE_ID, A.FL_SEQ, B.INCREMENT_PERIOD, A.BUCKET_GROUP, A.BUCKET_FROM, A.MMULT - NVL(D.MMULT,0),
            B.PD_METHOD, B.PD_RULE_NAME, C.MAX_BUCKET_ID
        FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_MMULT || ' A
        JOIN ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' B 
             ON A.PD_RULE_ID = B.PKID
        JOIN ' || V_TAB_OWNER || '.VW_IFRS_MAX_BUCKET C
             ON A.BUCKET_GROUP = C.BUCKET_GROUP
            AND A.BUCKET_TO    = C.MAX_BUCKET_ID
        LEFT JOIN ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_MMULT || ' D
             ON A.PD_RULE_ID = D.PD_RULE_ID
            AND A.MODEL_ID   = D.MODEL_ID
            AND A.SCENARIO_NO = D.SCENARIO_NO
            AND A.EFF_DATE   = D.EFF_DATE
            AND A.BUCKET_FROM = D.BUCKET_FROM
            AND A.BUCKET_TO   = D.BUCKET_TO
            AND A.FL_SEQ      = D.FL_SEQ + 1
        WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')
          AND (A.PD_RULE_ID = B.PKID
               OR (' || V_MODEL_ID || ' = 0 AND B.PD_METHOD = ''MAA'' AND (  
                    UPPER(TRIM(SYSCODE_PD)) IN ( 
                    SELECT UPPER(TRIM(REGEXP_SUBSTR(''' || P_SYSCODE || ''', ''[^;]+'', 1, LEVEL)))
                    FROM DUAL
                    CONNECT BY REGEXP_SUBSTR(''' || P_SYSCODE || ''', ''[^;]+'', 1, LEVEL) IS NOT NULL
                    )
                    OR ''' || P_SYSCODE || ''' = ''0'' 
                )))
        ORDER BY A.BUCKET_FROM, A.FL_SEQ';
	
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;

    V_STR_QUERY := 'SELECT A.EFF_DATE, A.BASE_DATE, A.SCENARIO_NO, A.MODEL_ID, A.PD_RULE_ID, 
	               A.FL_SEQ, A.INCREMENT_PERIOD, A.BUCKET_GROUP, A.BUCKET_FROM, A.MMULT,
	               A.PD_METHOD, A.PD_RULE_NAME, A.MAX_BUCKET_ID
	        FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_TERM_STRUCTURE1 || ' A
	        ORDER BY A.BUCKET_FROM, A.FL_SEQ';
    
	OPEN C_RULE FOR V_STR_QUERY;

	LOOP
		FETCH C_RULE INTO
			V_EFF_DATE,
			V_BASE_DATE,
			V_SCENARIO_NO,
			V_MODELS_ID,
			V_PD_RULE_ID,
			V_FL_SEQ,
			V_INCREMENT_PERIOD,
			V_BUCKET_GROUP,
			V_BUCKET_FROM,
			V_MMULT,
			V_PD_METHOD,
			V_PD_RULE_NAME,
			V_MAX_BUCKET_ID;

		EXIT WHEN C_RULE%NOTFOUND;

        V_MONTH_SEQ := 1;

        WHILE V_MONTH_SEQ <= 12 LOOP

            IF V_MONTH_SEQ = 1 THEN
                V_MMULT_FIN := 1 - POWER(1 - V_MMULT, (V_MONTH_SEQ / 12));
            ELSE
                V_MMULT_FIN := 1 - POWER(1 - V_MMULT, (V_MONTH_SEQ / 12))
                               - (1 - POWER(1 - V_MMULT, ((V_MONTH_SEQ - 1)/12)));
            END IF;

            IF V_BUCKET_FROM = V_MAX_BUCKET_ID THEN
                IF V_MONTH_SEQ = 1 AND V_FL_SEQ = 0 THEN
                    V_MMULT_FIN := 1;
                ELSE
                    V_MMULT_FIN := 0;
                END IF;
            END IF;

            V_STR_QUERY := 'INSERT INTO IFRS_PD_TERM_STRUCTURE (
                EFF_DATE, BASE_DATE, SCENARIO_NO, PD_RULE_ID, PD_METHOD, PD_RULE_NAME, MODEL_ID,
                BUCKET_GROUP, BUCKET_ID, FL_SEQ, FL_YEAR, FL_MONTH, PD, PD_OVERRIDE, CREATEDBY, CREATEDDATE
            ) VALUES (
                :1, :2, :3, :4, :5, :6,
                :7, :8, :9,
                :10,
                :11,
                :12,
                :13, :14,
                ''SP_IFRS_PD_TERM_STRUCTURE'', SYSDATE
            )';

            EXECUTE IMMEDIATE V_STR_QUERY USING V_EFF_DATE, V_BASE_DATE, V_SCENARIO_NO, V_PD_RULE_ID, V_PD_METHOD, V_PD_RULE_NAME,
                V_MODELS_ID, V_BUCKET_GROUP, V_BUCKET_FROM,
                (V_FL_SEQ * 12) + V_MONTH_SEQ - 1,
                ((V_FL_SEQ * 12) / 12) + 1,
                MOD((V_FL_SEQ * 12) + V_MONTH_SEQ - 1, 12) + 1,
                V_MMULT_FIN, V_MMULT_FIN;

            COMMIT;

            V_MONTH_SEQ := V_MONTH_SEQ + 1;
        END LOOP;

    END LOOP;

    CLOSE C_RULE;

    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_PD_TERM_STRUCTURE;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    ----------------------------------------------------------------
    -- RESULT
    ----------------------------------------------------------------
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_TERM_STRUCTURE;

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        IF C_RULE%ISOPEN THEN
            CLOSE C_RULE;
        END IF;

        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;