CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_MIGRATION_DETAIL (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
	---- DATE   
    V_CURRDATE DATE;
    V_PREVDATE DATE;
    V_MODEL_ID VARCHAR(22);
	V_COUNT NUMBER;
	V_OWNER       VARCHAR2(30);

    ---- QUERY  
    V_STR_QUERY CLOB;

	---- TABLE LIST 
	V_IFRS_MASTER_ACCOUNT_MONTHLY VARCHAR(100);
    V_IFRS_PD_MIGRATION_DETAIL VARCHAR(100);
    V_TMP_IFRS_PD_SCENARIO_DATA VARCHAR(100);
    V_TMP_IFRS_PD_RUNNING_DATE VARCHAR(100);
	V_TABLEPDCONFIG VARCHAR(100);
    V_TMP_IFRS_PD_DEFAULT VARCHAR(100);
    V_TMP_IFRS_PD_WO VARCHAR(100);
    V_TMP_IFRS_PD_SCENARIO_PREV VARCHAR(100);
    V_TMP_PD_CLOSE VARCHAR(100);
    V_GTMP_IFRS_DEFAULT_PD VARCHAR(100);
    V_TMP_PD_DEFAULT_CLOSE VARCHAR(100);

    ---- CONDITION
    V_RETURNROWS INT;
    V_RETURNROWS2 INT;
    V_TABLEDEST VARCHAR(100);
    V_COLUMNDEST VARCHAR(100);
    V_SP_NAME VARCHAR(100);
    V_OPERATION VARCHAR(100);

    ---- RESULT
    V_QUERYS CLOB;
BEGIN
    ----------------------------------------------------------------
    -- GET OWNER
    ----------------------------------------------------------------
    SELECT USERNAME INTO V_OWNER FROM USER_USERS;
   
	-- Handle default values for P_DOWNLOAD_DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
        INTO V_CURRDATE
        FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;
	
   	V_SP_NAME := 'SP_IFRS_PD_MIGRATION_DETAIL';
   
    IF P_SYSCODE <> '0' THEN
   		V_MODEL_ID := '1';
    ELSE
    	V_MODEL_ID := '0';
    END IF;

    IF P_PRC = 'S' THEN 
        V_IFRS_MASTER_ACCOUNT_MONTHLY := 'IFRS_MASTER_ACCOUNT_MONTHLY_' || P_RUNID || '';
		V_IFRS_PD_MIGRATION_DETAIL := 'IFRS_PD_MIGRATION_DETAIL_' || P_RUNID || '';
        V_TMP_IFRS_PD_SCENARIO_DATA := 'TMP_IFRS_PD_SCENARIO_DATA' || P_RUNID || '';
        V_TMP_IFRS_PD_RUNNING_DATE := 'TMP_IFRS_PD_RUNNING_DATE_' || P_RUNID || '';
        V_TMP_IFRS_PD_DEFAULT := 'TMP_IFRS_PD_DEFAULT_' || P_RUNID || '';
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG_' || P_RUNID || '';
        V_TMP_IFRS_PD_WO := 'TMP_IFRS_PD_WO_' || P_RUNID || '';
        V_TMP_IFRS_PD_SCENARIO_PREV := 'TMP_IFRS_PD_SCENARIO_PREV_' || P_RUNID || '';
        V_TMP_PD_CLOSE := 'TMP_PD_CLOSE_' || P_RUNID || '';
        V_GTMP_IFRS_DEFAULT_PD := 'GTMP_IFRS_DEFAULT_PD_' || P_RUNID || '';
        V_TMP_PD_DEFAULT_CLOSE := 'TMP_PD_DEFAULT_CLOSE_' || P_RUNID || '';
    ELSE 
		V_IFRS_MASTER_ACCOUNT_MONTHLY := 'IFRS_MASTER_ACCOUNT_MONTHLY';
		V_IFRS_PD_MIGRATION_DETAIL := 'IFRS_PD_MIGRATION_DETAIL';
        V_TMP_IFRS_PD_SCENARIO_DATA := 'TMP_IFRS_PD_SCENARIO_DATA';
        V_TMP_IFRS_PD_RUNNING_DATE := 'TMP_IFRS_PD_RUNNING_DATE';
        V_TMP_IFRS_PD_DEFAULT := 'TMP_IFRS_PD_DEFAULT';
		V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG';
        V_TMP_IFRS_PD_WO := 'TMP_IFRS_PD_WO';
        V_TMP_IFRS_PD_SCENARIO_PREV := 'TMP_IFRS_PD_SCENARIO_PREV';
        V_TMP_PD_CLOSE := 'TMP_PD_CLOSE';
        V_GTMP_IFRS_DEFAULT_PD := 'GTMP_IFRS_DEFAULT_PD';
        V_TMP_PD_DEFAULT_CLOSE := 'TMP_PD_DEFAULT_CLOSE';
    END IF;

	IF P_PRC = 'S' THEN

		PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_MIGRATION_DETAIL', V_IFRS_PD_MIGRATION_DETAIL);
		-- PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_RULES_CONFIG', V_TABLEPDCONFIG);
		PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_IFRS_PD_SCENARIO_DATA', V_TMP_IFRS_PD_SCENARIO_DATA);
		PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_IFRS_PD_RUNNING_DATE', V_TMP_IFRS_PD_RUNNING_DATE);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_IFRS_PD_DEFAULT', V_TMP_IFRS_PD_DEFAULT);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_IFRS_PD_WO', V_TMP_IFRS_PD_WO);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_IFRS_PD_SCENARIO_PREV', V_TMP_IFRS_PD_SCENARIO_PREV);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_PD_CLOSE', V_TMP_PD_CLOSE);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('GTMP_IFRS_DEFAULT_PD', V_GTMP_IFRS_DEFAULT_PD);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('TMP_PD_DEFAULT_CLOSE', V_TMP_PD_DEFAULT_CLOSE);
    ELSE
    
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE ||'' ;
	    
	    COMMIT;
    
    END IF;

    DBMS_OUTPUT.PUT_LINE(V_STR_QUERY);

    -------- RECORD RUN_ID --------
   	PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
	COMMIT;
    -------- RECORD RUN_ID --------

    -------- ====== BODY ======
    -------- INSERT INTO TMP_IFRS_PD_RUNNING_DATE

	V_STR_QUERY := '
    INSERT INTO ' || V_TMP_IFRS_PD_RUNNING_DATE || ' (PKID, BUCKET_GROUP, HISTORICAL_DATA, CURR_DATE, START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD, PREV_DATE)' ||
    	' SELECT
        PKID, BUCKET_GROUP, HISTORICAL_DATA, 
		TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') AS CURR_DATE, START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD,
        LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), INCREMENT_PERIOD * -1)) AS PREV_DATE
		FROM '|| V_TABLEPDCONFIG || ' WHERE PD_METHOD = ''MAA'' AND (  
                 UPPER(TRIM(SYSCODE_PD)) IN ( 
                   SELECT UPPER(TRIM(REGEXP_SUBSTR(:1, ''[^;]+'', 1, LEVEL)))
                   FROM DUAL
                   CONNECT BY REGEXP_SUBSTR(:2, ''[^;]+'', 1, LEVEL) IS NOT NULL
                 )
                 OR :3 = ''0'' 
               )';

	EXECUTE IMMEDIATE(V_STR_QUERY) USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
    COMMIT;

    ---- DELETE LOGIC
    IF V_MODEL_ID = '0' THEN

	    V_STR_QUERY := '';
	    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_IFRS_PD_MIGRATION_DETAIL ||' A
	    WHERE A.CURR_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ';
	    EXECUTE IMMEDIATE(V_STR_QUERY);

    ELSE
    
		V_STR_QUERY := '';
	    V_STR_QUERY := V_STR_QUERY || 'DELETE FROM ' || V_IFRS_PD_MIGRATION_DETAIL ||' A
	    WHERE EXISTS ( SELECT 1 FROM ' || V_TABLEPDCONFIG || ' B 
					    WHERE A.PD_RULE_ID = B.PKID
						AND B.PD_METHOD = ''MAA'' AND (  
							UPPER(TRIM(B.SYSCODE_PD)) IN ( 
							SELECT UPPER(TRIM(REGEXP_SUBSTR(:1, ''[^;]+'', 1, LEVEL)))
							FROM DUAL
							CONNECT BY REGEXP_SUBSTR(:2, ''[^;]+'', 1, LEVEL) IS NOT NULL
							)
							OR :3 = ''0'' 
						))
					    AND A.CURR_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ';
						
		EXECUTE IMMEDIATE(V_STR_QUERY) USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
    END IF;
    COMMIT;

    ---- POPULATE DEFAULT DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_DEFAULT || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
		EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.'|| V_TMP_IFRS_PD_DEFAULT || '';
	END IF;
    COMMIT;

	V_STR_QUERY := '
	INSERT INTO ' || V_OWNER || '.' || V_TMP_IFRS_PD_DEFAULT || ' ( 
	 DOWNLOAD_DATE 
	 ,PD_UNIQUE_ID 
	 ,DEFAULT_DATE 
	 ,RULE_ID 
	 )  
	SELECT B.PREV_DATE AS DOWNLOAD_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID 
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID   
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE)  
	 ,A.RULE_ID  
	FROM IFRS_DEFAULT A  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.RULE_ID = B.DEFAULT_RULE_ID  
	WHERE A.DOWNLOAD_DATE = B.PREV_DATE  
	GROUP BY B.PREV_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC'' 
	    ,''COS'' 
	    ,''CVS'' 
	    ) 
	   THEN A.CUSTOMER_NUMBER 
	  WHEN B.CALC_METHOD IN ( 
	    ''ANOA'' 
	    ,''ACA'' 
	    ,''AVS'' 
	    ) 
	   THEN A.MASTERID  
	  WHEN B.CALC_METHOD = ''FNOF'' 
	   THEN A.FACILITY_NUMBER 
	  ELSE A.MASTERID 
	  END 
	 ,RULE_ID 

	UNION  
	
	SELECT B.CURR_DATE AS DOWNLOAD_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID  
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE)  
	 ,A.RULE_ID  
	FROM IFRS_DEFAULT A  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.RULE_ID = B.DEFAULT_RULE_ID  
	WHERE A.DOWNLOAD_DATE BETWEEN B.PREV_DATE AND B.CURR_DATE
	GROUP BY B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN A.MASTERID
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE A.MASTERID 
	  END  
	 ,RULE_ID'; 
	
	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 
	
    ---- POPULATE WO DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO;
	END IF;
    COMMIT;

	V_STR_QUERY := 'INSERT INTO ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO || ' (  
	 DOWNLOAD_DATE  
	 ,PD_UNIQUE_ID  
	 ,WO_DATE  
	 ,PD_RULE_ID  
	 )  
	SELECT B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN TO_CHAR(A.MASTERID)    
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE TO_CHAR(A.MASTERID) 
	  END AS PD_UNIQUE_ID  
	 ,MIN(A.DOWNLOAD_DATE) AS WO_DATE  
	 ,B.PKID  
	FROM IFRS_MASTER_ACCOUNT_WO A  
	CROSS JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B  
	WHERE A.DOWNLOAD_DATE <= B.CURR_DATE  
	GROUP BY B.CURR_DATE  
	 ,CASE   
	  WHEN B.CALC_METHOD IN (  
	    ''CNOC''  
	    ,''COS''  
	    ,''CVS''  
	    )  
	   THEN A.CUSTOMER_NUMBER  
	  WHEN B.CALC_METHOD IN (  
	    ''ANOA''  
	    ,''ACA''  
	    ,''AVS''  
	    )  
	   THEN TO_CHAR(A.MASTERID) 
	  WHEN B.CALC_METHOD = ''FNOF''  
	   THEN A.FACILITY_NUMBER  
	  ELSE TO_CHAR(A.MASTERID)    
	  END  
	 ,B.PKID';  
	 
	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 

    ---- POPULATE CURRENT PD SCENARIO DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
        EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA;
    END IF;
    COMMIT;

        V_STR_QUERY := '';
        V_STR_QUERY := V_STR_QUERY || '	 
        INSERT INTO ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' (  
        PERIOD  
        ,PD_RULE_ID  
        ,BUCKET_GROUP  
        ,PD_UNIQUE_ID  
        ,CALC_METHOD  
        ,CUSTOMER_NUMBER  
        ,CALC_AMOUNT  
        ,BUCKET_ID  
        ,OUTSTANDING  
        ,ACCOUNT_STATUS  
        )  
        SELECT A.PERIOD  
        ,A.PD_RULE_ID  
        ,A.BUCKET_GROUP  
        ,A.PD_UNIQUE_ID  
        ,A.CALC_METHOD  
        ,MAX(A.CUSTOMER_NUMBER) AS CUSTOMER_NUMBER  
        ,SUM(A.CALC_AMOUNT) AS CALC_AMOUNT  
        ,MAX(CASE   
        WHEN D.PD_UNIQUE_ID IS NOT NULL  
            OR (  
            E.PD_UNIQUE_ID IS NOT NULL  
            )  
            THEN C.MAX_BUCKET_ID  
        ELSE A.BUCKET_ID  
        END) AS BUCKET_ID  
        ,SUM(A.OUTSTANDING) AS OUTSTANDING  
        ,A.ACCOUNT_STATUS  
        FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' A  
        JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.PD_RULE_ID = B.PKID  
        JOIN VW_IFRS_MAX_BUCKET C ON A.BUCKET_GROUP = C.BUCKET_GROUP  
        LEFT JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_DEFAULT || ' D ON A.PD_UNIQUE_ID = D.PD_UNIQUE_ID  
        AND B.DEFAULT_RULE_ID = D.RULE_ID  
        AND A.PERIOD = D.DOWNLOAD_DATE  
        LEFT JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO || ' E ON A.PD_UNIQUE_ID = E.PD_UNIQUE_ID  
        AND A.PERIOD = E.DOWNLOAD_DATE  
        AND A.PD_RULE_ID = E.PD_RULE_ID  
        JOIN IFRS_BUCKET_HEADER F ON A.BUCKET_GROUP = F.BUCKET_GROUP  
        WHERE A.PERIOD = B.CURR_DATE  
        GROUP BY A.PERIOD  
        ,A.PD_RULE_ID  
        ,A.BUCKET_GROUP  
        ,A.PD_UNIQUE_ID  
        ,A.CALC_METHOD  
        ,A.ACCOUNT_STATUS';

	EXECUTE IMMEDIATE(V_STR_QUERY); 
	COMMIT; 

    ---- POPULATE PREVIOUS PD SCENARIO DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV;
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || ' (  
	 PERIOD  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,CALC_METHOD  
	 ,CUSTOMER_NUMBER  
	 ,CALC_AMOUNT  
	 ,BUCKET_ID  
	 ,OUTSTANDING  
	 ,ACCOUNT_STATUS  
	 ,IS_CURR_DEFAULT  
	 ,IS_CURR_WO  
	 )                               
	SELECT A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,MAX(A.CUSTOMER_NUMBER) AS CUSTOMER_NUMBER  
	 ,SUM(A.CALC_AMOUNT) AS CALC_AMOUNT  
	 ,MAX(CASE   
	   WHEN D.PD_UNIQUE_ID IS NOT NULL  
	    THEN C.MAX_BUCKET_ID  
	   ELSE A.BUCKET_ID  
	   END) AS BUCKET_ID  
	 ,SUM(A.OUTSTANDING) AS OUTSTANDING  
	 ,A.ACCOUNT_STATUS  
	 ,MAX(CASE   
	   WHEN E.PD_UNIQUE_ID IS NOT NULL  
	    THEN 1  
	   ELSE 0  
	   END)  
	 ,MAX(CASE   
	   WHEN F.PD_UNIQUE_ID IS NOT NULL  
	    THEN 1  
	   ELSE 0  
	   END)  
	FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' A  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.PD_RULE_ID = B.PKID  
	JOIN VW_IFRS_MAX_BUCKET C ON A.BUCKET_GROUP = C.BUCKET_GROUP  
	LEFT JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_DEFAULT || ' D ON A.PD_UNIQUE_ID = D.PD_UNIQUE_ID  
	 AND B.DEFAULT_RULE_ID = D.RULE_ID  
	 AND A.PERIOD = D.DOWNLOAD_DATE  
	LEFT JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO || ' E ON A.PD_UNIQUE_ID = E.PD_UNIQUE_ID  
	 AND B.DEFAULT_RULE_ID = E.PD_RULE_ID  
	 AND B.CURR_DATE = E.DOWNLOAD_DATE  
	LEFT JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_WO || ' F ON A.PD_UNIQUE_ID = F.PD_UNIQUE_ID  
	 AND B.CURR_DATE >= F.DOWNLOAD_DATE  
	 AND A.PD_RULE_ID = F.PD_RULE_ID  
	WHERE A.PERIOD = B.PREV_DATE  
	GROUP BY A.PERIOD  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.CALC_METHOD  
	 ,A.ACCOUNT_STATUS'; 

	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	 
    ---- POPULATE CLOSE DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_PD_CLOSE || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_PD_CLOSE;
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '   
	INSERT INTO ' || V_OWNER || '.' || V_TMP_PD_CLOSE || '  
	 (PD_RULE_ID, DEFAULT_RULE_ID, PD_UNIQUE_ID, PREVDATE, CURRDATE, CALC_METHOD)  
	SELECT A.PD_RULE_ID,B.DEFAULT_RULE_ID,A.PD_UNIQUE_ID, B.PREV_DATE,   
	 LAST_DAY(ADD_MONTHS(B.CURR_DATE,-1)), B.CALC_METHOD  
	FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || ' A  
	 JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.PD_RULE_ID = B.PKID  
	  AND A.PERIOD = B.PREV_DATE  
	WHERE NOT EXISTS (  
	  SELECT * 
	  FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' C  
	  WHERE C.PD_RULE_ID = A.PD_RULE_ID  
	   AND C.PD_UNIQUE_ID = A.PD_UNIQUE_ID  
	   AND C.PERIOD = B.CURR_DATE  
	  FETCH FIRST 1 ROW ONLY
	  )';
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;


	EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_GTMP_IFRS_DEFAULT_PD;
	COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || '
	INSERT INTO ' || V_OWNER || '.' || V_GTMP_IFRS_DEFAULT_PD || ' (DOWNLOAD_DATE,PD_RULE_ID,PD_UNIQUE_ID)		    
		SELECT MIN(DOWNLOAD_DATE) AS DOWNLOAD_DATE ,PKID ,CASE   
						    WHEN CF.CALC_METHOD IN (  
						      ''CNOC''  
						      ,''COS''  
						      ,''CVS''  
						      )  
						     THEN ID.CUSTOMER_NUMBER  
						    WHEN CF.CALC_METHOD IN (  
						      ''ANOA''  
						      ,''ACA''  
						      ,''AVS''  
						      )  
						     THEN  
						      ID.MASTERID  
						    WHEN CF.CALC_METHOD = ''FNOF''  
						     THEN ID.FACILITY_NUMBER  
						    ELSE ID.MASTERID 
						    END AS PD_UNIQUE_ID  
		FROM IFRS_DEFAULT ID
		INNER JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' CF ON ID.RULE_ID = CF.DEFAULT_RULE_ID 
		AND ID.DOWNLOAD_DATE BETWEEN CF.PREV_DATE  AND CF.CURR_DATE 
		GROUP BY PKID,CASE   
						    WHEN CF.CALC_METHOD IN (  
						      ''CNOC''  
						      ,''COS''  
						      ,''CVS''  
						      )  
						     THEN ID.CUSTOMER_NUMBER  
						    WHEN CF.CALC_METHOD IN (  
						      ''ANOA''  
						      ,''ACA''  
						      ,''AVS''  
						      )  
						     THEN  
						      ID.MASTERID  
						    WHEN CF.CALC_METHOD = ''FNOF''  
						     THEN ID.FACILITY_NUMBER  
						    ELSE ID.MASTERID 
						    END';
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;

    ---- POPULATE CLOSED DEFAULT DATA
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || V_OWNER || '.' || V_TMP_PD_DEFAULT_CLOSE || '' INTO V_COUNT;

	IF V_COUNT > 0 THEN
	
	    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_OWNER || '.' || V_TMP_PD_DEFAULT_CLOSE;
	END IF;
    COMMIT;

	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO ' || V_OWNER || '.' || V_TMP_PD_DEFAULT_CLOSE || ' (PD_RULE_ID, PD_UNIQUE_ID)  
	SELECT A.PD_RULE_ID,  
	  A.PD_UNIQUE_ID
	  FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || ' A
		INNER JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.PD_RULE_ID = B.PKID 
		WHERE EXISTS (
		SELECT 1 FROM  ' || V_OWNER || '.' || V_GTMP_IFRS_DEFAULT_PD || ' X
					WHERE X.PD_RULE_ID = A.PD_RULE_ID 
					AND X.PD_UNIQUE_ID = A.PD_UNIQUE_ID 
				    )';

	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;

	   
	---- START INSERTING MIGRATION DETAIL POPULATION  
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO ' || V_OWNER || '.' || V_IFRS_PD_MIGRATION_DETAIL || ' (  
	  PREV_DATE  
	 ,CURR_DATE  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,BUCKET_FROM  
	 ,BUCKET_TO  
	 ,CALC_AMOUNT  
	 ,CUSTOMER_NUMBER  
	 ,OUTSTANDING  
	 ,CREATEDBY  
	 ,CREATEDDATE  
	 ,CREATEDHOST  
	 )  
	SELECT A.PERIOD PREV_DATE  
	 ,B.PERIOD CURR_DATE  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.BUCKET_ID BUCKET_FROM  
	 ,CASE   
	  WHEN A.BUCKET_ID = D.MAX_BUCKET_ID  
	   THEN D.MAX_BUCKET_ID  
	  WHEN B.ACCOUNT_STATUS = ''C''  
	   AND B.BUCKET_ID <> D.MAX_BUCKET_ID  
	   THEN 0  
	  ELSE B.BUCKET_ID  
	  END BUCKET_TO  
	 ,A.CALC_AMOUNT  
	 ,B.CUSTOMER_NUMBER  
	 ,A.OUTSTANDING  
	 ,''SP_IFRS_PD_MIGRATION_DETAIL''  
	 ,SYSDATE
	 ,''LOCALHOST''  
	FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || ' A  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' B ON A.PD_RULE_ID = B.PD_RULE_ID  
	 AND A.PD_UNIQUE_ID = B.PD_UNIQUE_ID  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' C ON A.PD_RULE_ID = C.PKID  
	 AND B.PD_RULE_ID = C.PKID  
	 AND A.PERIOD = C.PREV_DATE  
	 AND B.PERIOD = C.CURR_DATE  
	JOIN VW_IFRS_MAX_BUCKET D ON D.BUCKET_GROUP = A.BUCKET_GROUP  
	 AND D.BUCKET_GROUP = B.BUCKET_GROUP';  
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	
	V_STR_QUERY := '';
	V_STR_QUERY := V_STR_QUERY || ' 
	INSERT INTO ' || V_OWNER || '.' || V_IFRS_PD_MIGRATION_DETAIL || ' (  
	  PREV_DATE  
	 ,CURR_DATE  
	 ,PD_RULE_ID  
	 ,BUCKET_GROUP  
	 ,PD_UNIQUE_ID  
	 ,BUCKET_FROM  
	 ,BUCKET_TO  
	 ,CALC_AMOUNT  
	 ,CUSTOMER_NUMBER  
	 ,OUTSTANDING  
	 ,CREATEDBY  
	 ,CREATEDDATE  
	 ,CREATEDHOST  
	 )  
	SELECT  A.PERIOD PREV_DATE  
	 ,B.CURR_DATE  
	 ,A.PD_RULE_ID  
	 ,A.BUCKET_GROUP  
	 ,A.PD_UNIQUE_ID  
	 ,A.BUCKET_ID BUCKET_FROM  
	 ,CASE   
	  WHEN A.BUCKET_ID = D.MAX_BUCKET_ID  
	   OR G.PD_UNIQUE_ID IS NOT NULL   
	   OR A.IS_CURR_DEFAULT = 1  
	   OR (  
	    A.IS_CURR_WO = 1   
	    )  
	   THEN D.MAX_BUCKET_ID  
	  ELSE 0  
	  END BUCKET_TO  
	 ,A.CALC_AMOUNT  
	 ,A.CUSTOMER_NUMBER  
	 ,A.OUTSTANDING  
	 ,''SP_IFRS_PD_MIGRATION_DETAIL_1''  
	 ,SYSDATE
	 ,''LOCALHOST''  
	FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_PREV || ' A  
	JOIN ' || V_OWNER || '.' || V_TMP_IFRS_PD_RUNNING_DATE || ' B ON A.PD_RULE_ID = B.PKID  
	 AND A.PERIOD = B.PREV_DATE  
	JOIN VW_IFRS_MAX_BUCKET D ON D.BUCKET_GROUP = A.BUCKET_GROUP  
	JOIN IFRS_BUCKET_HEADER F ON F.BUCKET_GROUP = A.BUCKET_GROUP  
	LEFT JOIN ' || V_OWNER || '.' || V_TMP_PD_DEFAULT_CLOSE || ' G   
	 ON A.PD_RULE_ID = G.PD_RULE_ID  
	  AND A.PD_UNIQUE_ID = G.PD_UNIQUE_ID  
	WHERE NOT EXISTS (  
	  SELECT * 
	  FROM ' || V_OWNER || '.' || V_TMP_IFRS_PD_SCENARIO_DATA || ' C  
	  WHERE C.PD_RULE_ID = A.PD_RULE_ID  
	   AND C.PD_UNIQUE_ID = A.PD_UNIQUE_ID  
	   AND C.PERIOD = B.CURR_DATE  
	  FETCH FIRST 1 ROW ONLY
	  )'; 
	EXECUTE IMMEDIATE(V_STR_QUERY);
	COMMIT;
	
	---- END INSERTING MIGRATION DETAIL POPULATION

    V_TABLEDEST := V_IFRS_PD_MIGRATION_DETAIL;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
    
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
    -------- ====== LOG ======

    V_QUERYS := 'SELECT * FROM ' || V_OWNER || '.' || V_IFRS_PD_MIGRATION_DETAIL;

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;