CREATE OR REPLACE PROCEDURE PSAK413.SP_IFRS_PD_MAA_ENR (
    P_RUNID         IN VARCHAR2 DEFAULT 'S_00000_0000',
    P_DOWNLOAD_DATE IN DATE,
    P_SYSCODE       IN VARCHAR2 DEFAULT '0',
    P_PRC           IN VARCHAR2 DEFAULT 'S'
)
AUTHID CURRENT_USER
AS
    -- DATES / COUNTERS
    V_CURRDATE      DATE;
    V_PREVDATE      DATE;
    V_MODEL_ID      VARCHAR2(22);
    V_COUNT         NUMBER;

    -- DYNAMIC SQL
    V_STR_QUERY     VARCHAR2(32767);

    -- Table names
    V_TAB_OWNER     CONSTANT VARCHAR2(30) := 'PSAK413';
    V_GTMP_PD_RUNNING_CONFIG VARCHAR2(100);
    V_IFRS_PD_MAA_ENR VARCHAR2(100);
    V_IFRS_PD_MIGRATION_DETAIL  VARCHAR2(100);
    V_TABLEPDCONFIG VARCHAR2(100);

    -- MISC
    V_RETURNROWS    NUMBER;
    V_RETURNROWS2   NUMBER;
    V_TABLEDEST     VARCHAR2(100);
    V_COLUMNDEST    VARCHAR2(100);
    V_SP_NAME       VARCHAR2(100);
    V_OPERATION     VARCHAR2(100);

    -- RESULT QUERY
    V_QUERYS        CLOB;
BEGIN
    -- SET PROCEDURE NAME
    V_SP_NAME := 'SP_IFRS_PD_MAA_ENR';
    
    -- HANDLE DEFAULT DOWNLOAD DATE
    IF P_DOWNLOAD_DATE IS NULL THEN
        SELECT CURRDATE
          INTO V_CURRDATE
          FROM PSAK413.IFRS_PRC_DATE; 
    ELSE
        V_CURRDATE := P_DOWNLOAD_DATE;
    END IF;

    IF P_SYSCODE <> '0' THEN
   		V_MODEL_ID := '1';
    ELSE
    	V_MODEL_ID := '0';
    END IF;

    IF P_PRC = 'S' THEN
        V_GTMP_PD_RUNNING_CONFIG := 'GTMP_PD_RUNNING_CONFIG_' || P_RUNID;
        V_IFRS_PD_MAA_ENR := 'IFRS_PD_MAA_ENR_' || P_RUNID;
        V_IFRS_PD_MIGRATION_DETAIL := 'IFRS_PD_MIGRATION_DETAIL_' || P_RUNID;
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG_' || P_RUNID;
    ELSE
        V_GTMP_PD_RUNNING_CONFIG := 'GTMP_PD_RUNNING_CONFIG';
        V_IFRS_PD_MAA_ENR := 'IFRS_PD_MAA_ENR';
        V_IFRS_PD_MIGRATION_DETAIL := 'IFRS_PD_MIGRATION_DETAIL';
        V_TABLEPDCONFIG := 'IFRS_PD_RULES_CONFIG';
    END IF;

    IF P_PRC = 'S' THEN
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('GTMP_PD_RUNNING_CONFIG', V_GTMP_PD_RUNNING_CONFIG);
        PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_MAA_ENR', V_IFRS_PD_MAA_ENR);
        -- PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_MIGRATION_DETAIL', V_IFRS_PD_MIGRATION_DETAIL);
        -- PSAK413.SP_IFRS_CREATE_TABLE_SIMULATE('IFRS_PD_RULES_CONFIG', V_TABLEPDCONFIG); 
    END IF;
    COMMIT;

   PSAK413.SP_IFRS_RUNNING_LOG(V_CURRDATE, V_SP_NAME, P_RUNID, 0, SYSDATE);
   COMMIT;


    ----------------------------------------------------------------
    -- PRE-SIMULATION TABLE: CREATE/DROP TEMP TABLES IF P_PRC = 'S'
    ----------------------------------------------------------------

    EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TAB_OWNER || '.' || V_GTMP_PD_RUNNING_CONFIG;
   
    COMMIT;

    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_GTMP_PD_RUNNING_CONFIG ||
                   ' (PD_RULE_ID, BUCKET_GROUP, HISTORICAL_DATA, ' ||
                   ' CURR_DATE, CUT_OFF_DATE, DEFAULT_RULE_ID, CALC_METHOD, PREV_DATE,INCLUDE_CLOSE) ' ||
                   ' SELECT PKID, BUCKET_GROUP, HISTORICAL_DATA, ' ||
                   ' TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''', ''YYYY-MM-DD''), ' ||
                   ' START_HISTORICAL_DATE, DEFAULT_RULE_ID, CALC_METHOD, ' ||
                   ' LAST_DAY(ADD_MONTHS(TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD''), -1 * INCREMENT_PERIOD)), ' ||
                   ' INCLUDE_CLOSE ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_TABLEPDCONFIG || ' WHERE PD_METHOD = ''MAA'' AND (  
                        UPPER(TRIM(SYSCODE_PD)) IN ( 
                        SELECT UPPER(TRIM(REGEXP_SUBSTR(:1, ''[^;]+'', 1, LEVEL)))
                        FROM DUAL
                        CONNECT BY REGEXP_SUBSTR(:2, ''[^;]+'', 1, LEVEL) IS NOT NULL
                        )
                        OR :3 = ''0'' 
                    )';

   	EXECUTE IMMEDIATE V_STR_QUERY USING P_SYSCODE, P_SYSCODE, P_SYSCODE;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    IF V_MODEL_ID = '0' THEN
        V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR ||
                       ' WHERE EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')';
    ELSE
        -- DELETE ROWS IN TARGET THAT MATCH PKS IN CONFIG (USING EXISTS)
        V_STR_QUERY := 'DELETE FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR || ' A ' ||
                       ' WHERE A.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'')' ||
                       ' AND EXISTS (SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_RUNNING_CONFIG || ' B WHERE B.PD_RULE_ID = A.PD_RULE_ID)';
    END IF;
    
    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
    
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR || ' (' ||
                   ' EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT, CREATEDBY, CREATEDDATE, CREATEDHOST) ' ||
                   ' SELECT B.CURR_DATE, B.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, ' ||
				   ' CASE WHEN B.INCLUDE_CLOSE = 1 AND A.BUCKET_TO = 0 THEN 1 ELSE A.BUCKET_TO END AS BUCKET_TO, SUM(A.CALC_AMOUNT), ' ||
                   '''SP_IFRS_PD_MAA_ENR'', SYSDATE, ''LOCALHOST'' ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MIGRATION_DETAIL || ' A ' ||
                   ' JOIN ' || V_TAB_OWNER || '.' || V_GTMP_PD_RUNNING_CONFIG || ' B ON A.PD_RULE_ID = B.PD_RULE_ID AND A.CURR_DATE = B.CURR_DATE ' ||
                   ' GROUP BY B.CURR_DATE, B.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, A.BUCKET_FROM, CASE WHEN B.INCLUDE_CLOSE = 1 AND A.BUCKET_TO = 0 THEN 1 ELSE A.BUCKET_TO END';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));
    
    V_STR_QUERY := 'INSERT INTO ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR || ' (' ||
                   ' EFF_DATE, BASE_DATE, PD_RULE_ID, BUCKET_GROUP, BUCKET_FROM, BUCKET_TO, CALC_AMOUNT, CREATEDBY, CREATEDDATE, CREATEDHOST) ' ||
                   ' SELECT DISTINCT A.CURR_DATE, A.PREV_DATE, A.PD_RULE_ID, A.BUCKET_GROUP, B.BUCKET_ID, CASE WHEN A.INCLUDE_CLOSE = 1 AND C.BUCKET_ID = 0 THEN 1 ELSE C.BUCKET_ID END AS BUCKET_TO, 0, ' ||
                   '''SP_IFRS_PD_MAA_ENR_1'', SYSDATE, ''LOCALHOST'' ' ||
                   ' FROM ' || V_TAB_OWNER || '.' || V_GTMP_PD_RUNNING_CONFIG || ' A ' ||
                   ' JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_DETAIL B ON A.BUCKET_GROUP = B.BUCKET_GROUP ' ||
                   ' CROSS JOIN ' || V_TAB_OWNER || '.IFRS_BUCKET_DETAIL C ' ||
                   ' WHERE C.BUCKET_GROUP = B.BUCKET_GROUP ' ||
                   ' AND A.CUT_OFF_DATE <= A.PREV_DATE ' ||
                   ' AND NOT EXISTS ( ' ||
                   '    SELECT 1 FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR || ' D ' ||
                   '    WHERE D.PD_RULE_ID = A.PD_RULE_ID ' ||
                   '      AND D.EFF_DATE = TO_DATE(''' || TO_CHAR(V_CURRDATE,'YYYY-MM-DD') || ''',''YYYY-MM-DD'') ' ||
                   '      AND D.BUCKET_FROM = B.BUCKET_ID ' ||
                   '      AND D.BUCKET_TO = C.BUCKET_ID ' ||
                   ' )';

    EXECUTE IMMEDIATE V_STR_QUERY;
    COMMIT;
	DBMS_OUTPUT.PUT_LINE(SUBSTR(V_STR_QUERY, 1, 30000));

    V_TABLEDEST := V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR;
    V_COLUMNDEST := '-';
    V_OPERATION := 'INSERT';
 
    PSAK413.SP_IFRS_EXEC_AND_LOG(V_CURRDATE, V_TABLEDEST, V_COLUMNDEST, V_SP_NAME, V_OPERATION, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;  
   
    V_QUERYS := 'SELECT * FROM ' || V_TAB_OWNER || '.' || V_IFRS_PD_MAA_ENR;

    PSAK413.SP_IFRS_RESULT_PREV(V_CURRDATE, V_QUERYS, V_SP_NAME, NVL(V_RETURNROWS2,0), P_RUNID);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20001,'ERROR IN ' || V_SP_NAME || ' : ' || SQLERRM);
END;