IFRS_PD_RULE_DATA
TMP_PD
TMP_IFRS_SCN_GENERATE_QUERY
TMP_IFRS_MASTER_ACCOUNT_PD
TMP_PD_DATE_RUN
IFRS_SEGMENTATION_MAPPING
TMP_SCENARIO_DATA
IFRS_PD_SCENARIO_DATA
IFRS_PD_MIGRATION_DETAIL
TMP_IFRS_PD_SCENARIO_DATA
TMP_IFRS_PD_RUNNING_DATE
TMP_IFRS_PD_DEFAULT
TMP_IFRS_PD_WO
TMP_IFRS_PD_SCENARIO_PREV
TMP_PD_CLOSE
GTMP_IFRS_DEFAULT_PD
TMP_PD_DEFAULT_CLOSE
GTMP_PD_RUNNING_CONFIG
IFRS_PD_MAA_ENR
GTMP_PD_RUNNING_ENR_SUM
IFRS_PD_MAA_ENR_SUM
GTMP_PD_FLOWRATE_CONFIG
IFRS_PD_MAA_FLOWRATE
GTMP_PD_FLOW_SUM_CONFIG
IFRS_PD_MAA_FLOWRATE_SUM
TMP_PD_BUCKET
TMP_PD_TOTAL
GTMP_PD_ODR_CONFIG
IFRS_PD_MAA_ODR
GTMP_PD_RUNNING_SMOOTH_CONFIG
IFRS_PD_MAA_FLOWRATE_SMOOTH
IFRS_PD_LINEST_SMOOTHING
GTMP_LOGIT_ODR
GTMP_SMOOTHING_BASE
GTMP_PD_BASE
GTMP_PD_RESULT
GTMP_SMOOTH
IFRS_PD_MAA_MMULT_MONTHLY
GTMP_RUNNING_PD_MAA_MMULT
TMP_IFRS_MMULT_SEQ
IFRS_PD_MAA_MMULT
GTMP_IFRS_PD_TERM_STRUCTURE1
IFRS_PD_TERM_STRUCTURE
IFRS_PD_VAS_MPD
IFRS_PD_VAS_TTC
GTMP_PD_ZSCORE_CONFIG
TMP_MEV
TMP_AVG_STDEV_ME
TMP_PD_VAS_ZSCORE1
IFRS_PD_VAS_ZSCORE
IFRS_ME_FORECAST_SCN
IFRS_MACRO_ECONOMIC_INTRPOLATE


---- CONFIG
IFRS_PD_RULES_CONFIG



---- SELECT
IFRS_MASTER_ACCOUNT_MONTHLY
IFRS_BUCKET_HEADER
VW_IFRS_MAX_BUCKET



-- PD_METHOD = ''MAA'' AND (  
--     UPPER(TRIM(SYSCODE_PD)) IN ( 
--     SELECT UPPER(TRIM(REGEXP_SUBSTR(:1, ''[^;]+'', 1, LEVEL)))
--     FROM DUAL
--     CONNECT BY REGEXP_SUBSTR(:2, ''[^;]+'', 1, LEVEL) IS NOT NULL
--     )
--     OR :3 = ''0'' 
-- )

-- --CALL PSAK413.SP_IFRS_PD_RULE_DATA('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_TM_SCENARIO_DATA('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MIGRATION_DETAIL('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_ENR('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_ENR_SUM('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_FLOWRATE('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_FLOWRATE_SUM('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_ODR('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_FLOWRATE_SMOOTH('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_MMULT_MONTHLY('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_MAA_MMULT('P_11111_2222',NULL,'0','P');
-- --CALL PSAK413.SP_IFRS_PD_TERM_STRUCTURE('P_11111_2222',NULL,'0','P');


-- CALL PSAK413.XXX('P_11111_2222',NULL,'0','P');
-- CALL PSAK413.XXX('S_11111_2222',NULL,'0','S');
