---- DROP PROCEDURE SP_IFRS_UPDATE_PRC_DATE;

CREATE OR REPLACE PROCEDURE SP_IFRS_UPDATE_PRC_DATE (
	IN P_CURRDATE DATE DEFAULT NULL::DATE,
	IN P_PREVDATE TEXT DEFAULT NULL::DATE,
	IN BATCH_STATUS TEXT DEFAULT 'RUNNING')
LANGUAGE PLPGSQL AS $$
DECLARE
	V_STR_QUERY TEXT;
BEGIN
	IF P_CURRDATE IS NULL
	THEN
		---- UPDATE PRC DATE
		V_STR_QUERY := '';
		V_STR_QUERY := V_STR_QUERY || 'UPDATE IFRS_PRC_DATE
		SET BATCH_STATUS = ''' || BATCH_STATUS || ''' ';
		EXECUTE (V_STR_QUERY);
	ELSE
		V_STR_QUERY := '';
		V_STR_QUERY := V_STR_QUERY || 'UPDATE IFRS_PRC_DATE
		SET CURRDATE = ''' || P_CURRDATE || '''::DATE + INTERVAL ''1 day'',
		PREVDATE = ''' || P_PREVDATE || '''::DATE + INTERVAL ''1 day'' ';
		EXECUTE (V_STR_QUERY);
	END IF;
END;
$$;