---- DROP PROCEDURE SP_IFRS_BATCH_LOG_DETAILS;

CREATE OR REPLACE PROCEDURE SP_IFRS_BATCH_LOG_DETAILS (
	IN DOWNLOAD_DATE DATE DEFAULT NULL::DATE,
    IN BATCH_ID INT DEFAULT NULL::INT,
    IN BATCH_ID_HEADER INT DEFAULT NULL::INT,
    IN BATCH_NAME VARCHAR(10) DEFAULT NULL::VARCHAR(10),
    IN PROCESS_NAME VARCHAR(100) DEFAULT NULL::VARCHAR(100),
    IN START_DATE DATE DEFAULT NULL::DATE,
    IN END_DATE DATE DEFAULT NULL::DATE,
    IN CREATEDBY VARCHAR(50) DEFAULT NULL::VARCHAR(50),
    IN COUNTER INT DEFAULT NULL::INT,
    IN REMARKS VARCHAR(100) DEFAULT NULL::VARCHAR(100))
LANGUAGE PLPGSQL AS $$
BEGIN
	INSERT INTO IFRS_BATCH_LOG_DETAILS (
        DOWNLOAD_DATE,
        BATCH_ID,
        BATCH_ID_HEADER,
        BATCH_NAME,
        PROCESS_NAME,
        START_DATE,
        END_DATE,
        CREATEDBY,
        COUNTER,
        REMARKS
    ) VALUES (
        DOWNLOAD_DATE,
        BATCH_ID,
        BATCH_ID_HEADER,
        BATCH_NAME,
        PROCESS_NAME,
        START_DATE,
        END_DATE,
        CREATEDBY,
        COUNTER,
        REMARKS
    );
END;
$$;
