DO
$$
DECLARE
	V_PID BIGINT;
BEGIN
-- ============== PREP ==============
V_PID := (SELECT PG_BACKEND_PID());
RAISE NOTICE 'PROCESS ID ---> %', V_PID;
TRUNCATE TABLE IFRS_LOGS_PROCESS;
TRUNCATE TABLE IFRS_RESULT_PREVIEW;
TRUNCATE TABLE IFRS_RUNNING_LOGS;
-- ============== PREP ==============
-- ============== CALCULATION AMORTIZATION ==============

-- ============== #PREP ==============
CALL SP_IFRS_IMP_SIMULATION_DATA(); -- 0
-- ============== #PREP ==============
----- #1
CALL SP_IFRS_AMT_SYNC_BEFORE_PROCESS();
CALL SP_IFRS_AMT_PROCESS_TRAN_DAILY();
CALL SP_IFRS_AMT_ACCT_SWITCH();
CALL SP_IFRS_AMT_GENERATE_PAYM_SCHD();
CALL SP_IFRS_AMT_CALC_ACCT_EIR();
CALL SP_IFRS_AMT_ACCT_LBM_PROCESS(); ---- BUG FIXING
CALL SP_IFRS_AMT_ACCT_SL_PROCESS(); ---- BUG FIXING
CALL SP_IFRS_AMT_JOURNAL_RPT();
-- ============== CALCULATION AMORTIZATION ==============
END;
$$;