CALL SP_IFRS_IMP_SIMULATION_DATA();
-- #1
CALL SP_IFRS_RESET_AMT_PRC();
CALL SP_IFRS_SYNC_PRODUCT_PARAM();
CALL SP_IFRS_SYNC_TRANS_PARAM();
CALL SP_IFRS_SYNC_JOURNAL_PARAM();
CALL SP_IFRS_SYNC_UPLOAD_TRAN_DAILY();
CALL SP_IFRS_AC_SYNC_LIST_VALUE();
CALL SP_IFRS_INITIAL_UPDATE();
CALL SP_IFRS_EXEC_RULE();
-- #2
CALL SP_IFRS_FILL_IMA_AMORT_PREV_CURR();
CALL SP_IFRS_ACCT_AMORT_RESTRU();
CALL SP_IFRS_ACCT_CLOSED();
CALL SP_IFRS_PROCESS_TRAN_DAILY();
CALL SP_IFRS_COST_FEE_STATUS();
CALL SP_IFRS_ACCT_COST_FEE_SUMM();
-- #3
CALL SP_IFRS_ACCT_SWITCH();
CALL SP_IFRS_ACCT_SL_SWITCH();
CALL SP_IFRS_ACCT_EIR_SWITCH();
CALL SP_IFRS_ACCT_EIR_ACF_PMTDT();
CALL SP_IFRS_ACCT_EIR_ECF_EVENT();
-- #4
-- CALL SP_IFRS_ACCT_SWITCH
-- CALL SP_IFRS_ACCT_SL_SWITCH
-- CALL SP_IFRS_ACCT_EIR_SWITCH
-- CALL SP_IFRS_ACCT_EIR_ACF_PMTDT
-- CALL SP_IFRS_ACCT_EIR_ECF_EVENT