DROP VIEW IF EXISTS VW_LBM_LAST_EIR_CF_PREV;

CREATE VIEW VW_LBM_LAST_EIR_CF_PREV AS

SELECT MASTERID
	,DOWNLOAD_DATE
	,SEQ
FROM IFRS_LBM_ACCT_EIR_COST_FEE_PREV
WHERE ID IN (
		SELECT MAX(ID) ID
		FROM IFRS_LBM_ACCT_EIR_COST_FEE_PREV
		GROUP BY MASTERID
		)