DROP VIEW IF EXISTS VW_SOURCE_LGD_RULES_CONFIG;
CREATE VIEW VW_SOURCE_LGD_RULES_CONFIG
AS
SELECT * FROM (
	SELECT PKID
	,DEFAULT_RULE_ID
	,LGD_RULE_NAME
	,SEGMENTATION_ID
	,LGD_METHOD
	,LGW_HISTORICAL_DATA
	,WORKOUT_PERIOD
	,MIN_VALUE
	,MAX_VALUE
	,CUT_OFF_DATE
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST
	,LAG_1MONTH_FLAG
	,RUNNING_STATUS FROM VW_LGD_RULES_CONFIG
	EXCEPT
	SELECT PKID
	,DEFAULT_RULE_ID
	,LGD_RULE_NAME
	,SEGMENTATION_ID
	,LGD_METHOD
	,LGW_HISTORICAL_DATA
	,WORKOUT_PERIOD
	,MIN_VALUE
	,MAX_VALUE
	,CUT_OFF_DATE
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST
	,LAG_1MONTH_FLAG
	,RUNNING_STATUS FROM IFRS_LGD_RULES_CONFIG
) CHECK_LGD_RULES_CONFIG