DROP VIEW IF EXISTS VW_SOURCE_CCF_RULES_CONFIG;
CREATE VIEW VW_SOURCE_CCF_RULES_CONFIG
AS
SELECT * FROM (
	SELECT PKID
	,CCF_RULE_NAME
	,SEGMENTATION_ID
	,CALC_METHOD
	,AVERAGE_METHOD
	,DEFAULT_RULE_ID
	,CUT_OFF_DATE
	,CCF_OVERRIDE
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST
	,LAG_1MONTH_FLAG
	,RUNNING_STATUS FROM VW_CCF_RULES_CONFIG
	EXCEPT
	SELECT PKID
	,CCF_RULE_NAME
	,SEGMENTATION_ID
	,CALC_METHOD
	,AVERAGE_METHOD
	,DEFAULT_RULE_ID
	,CUT_OFF_DATE
	,CCF_OVERRIDE
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST
	,LAG_1MONTH_FLAG
	,RUNNING_STATUS FROM IFRS_CCF_RULES_CONFIG
) CHECK_CCF_RULES_CONFIG