DROP VIEW IF EXISTS VW_LAST_SL_CF_PREV;

CREATE VIEW VW_LAST_SL_CF_PREV AS
SELECT MASTERID
	,DOWNLOAD_DATE
	,SEQ
FROM IFRS_ACCT_SL_COST_FEE_PREV
WHERE ID IN (
		SELECT MAX(ID) ID
		FROM IFRS_ACCT_SL_COST_FEE_PREV
		GROUP BY MASTERID
		);