DROP VIEW IF EXISTS VW_SOURCE_EAD_RULES_CONFIG;

CREATE VIEW VW_SOURCE_EAD_RULES_CONFIG
AS
SELECT * FROM (
	SELECT PKID
	,EAD_RULE_NAME
	,SEGMENTATION_ID
	,EAD_BALANCE
	,CCF_FLAG
	,CCF_RULES_ID
	,PREPAYMENT_FLAG
	,PREPAYMENT_RULES_ID
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST FROM VW_EAD_RULES_CONFIG
	EXCEPT
	SELECT PKID
	,EAD_RULE_NAME
	,SEGMENTATION_ID
	,EAD_BALANCE
	,CCF_FLAG
	,CCF_RULES_ID
	,PREPAYMENT_FLAG
	,PREPAYMENT_RULES_ID
	,ACTIVE_FLAG
	,IS_DELETE
	,CREATEDBY
	,CREATEDDATE
	,CREATEDHOST FROM IFRS_EAD_RULES_CONFIG
) CHECK_EAD_RULES_CONFIG;