DROP VIEW IF EXISTS VW_SOURCE_MASTER_EXCHANGE_RATE;

CREATE VIEW VW_SOURCE_MASTER_EXCHANGE_RATE
AS
SELECT * FROM (
SELECT PKID
,DOWNLOAD_DATE
,CURRENCY
,CURRENCY_DESC
,RATE_AMOUNT
,MAINTAIN_DATE FROM VW_MASTER_EXCHANGE_RATE
EXCEPT
SELECT PKID
,DOWNLOAD_DATE
,CURRENCY
,CURRENCY_DESC
,RATE_AMOUNT
,MAINTAIN_DATE FROM IFRS_MASTER_EXCHANGE_RATE
) CHECK_MASTER_EXCHANGE_RATE;