
DROP VIEW IF EXISTS VW_LAST_EIR_CF_PREV_YEST;

CREATE VIEW VW_LAST_EIR_CF_PREV_YEST AS

SELECT MASTERID, DOWNLOAD_DATE, MAX(SEQ) SEQ
FROM IFRS_ACCT_EIR_COST_FEE_PREV
WHERE DOWNLOAD_DATE  =  (SELECT PREVDATE FROM IFRS_PRC_DATE_AMORT)
GROUP BY MASTERID, DOWNLOAD_DATE