DROP VIEW IF EXISTS VW_CCF_OVERRIDE;
CREATE VIEW VW_CCF_OVERRIDE
AS
SELECT DISTINCT B.PKID,
B.PKID AS "ccf rule id",
B.CCF_RULE_NAME AS "ccf_configuration", 
A.DOWNLOAD_DATE AS "download date", 
CASE UPPER(B.AVERAGE_METHOD)
	WHEN 'WEIGHTED' THEN
		A.WEIGHTED_AVG_CCF
	WHEN 'SIMPLE' THEN
		A.SIMPLE_AVG_CCF
END AS "ccf rate", 
B.CCF_OVERRIDE AS "ccf override"
FROM IFRS_EAD_CCF_HEADER A
INNER JOIN IFRS_CCF_RULES_CONFIG B ON A.CCF_RULE_ID = B.PKID
WHERE A.DOWNLOAD_DATE = (SELECT CURRDATE FROM IFRS_PRC_DATE)
AND B.IS_DELETE = 0 AND B.ACTIVE_FLAG = 1;