DROP VIEW IF EXISTS VW_LGD_FL_OVERRIDE;
CREATE VIEW VW_LGD_FL_OVERRIDE
AS
SELECT A.DOWNLOAD_DATE AS "Effective Date"
,B.LGD_RULE_NAME AS "LGD Rule Name"
,C.SEGMENT AS "Segmentation"
,A.FL_SEQ AS "FL Sequence"
,A.FL_YEAR AS "FL Year"
,A.FL_MONTH AS "FL Month"
,A.LGD AS "LGD Rate System"
,0 AS "LGD Rate Override"
FROM IFRS_LGD_TERM_STRUCTURE A
INNER JOIN IFRS_LGD_RULES_CONFIG B ON A.LGD_RULE_ID = B.PKID
INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER C ON B.SEGMENTATION_ID = C.PKID
AND C.ACTIVE_FLAG = 1 AND C.IS_DELETE = 0
WHERE B.ACTIVE_FLAG = 1 AND B.IS_DELETE = 0
