 DROP VIEW IF EXISTS VW_IFRS_ECL_MODEL_HEADER;

CREATE VIEW VW_IFRS_ECL_MODEL_HEADER 
AS
 SELECT A.PKID,
    A.ECL_CONFIGURATION_NAME AS ECL_MODEL_NAME,
    NULL::DATE AS DATA_DATE,
        CASE A.IS_ACTIVE
            WHEN TRUE THEN '1'::TEXT
            ELSE '0'::TEXT
        END AS ACTIVE_STATUS,
    NULL::TEXT AS RUN_STATUS,
    0 AS IS_DELETE,
    A.CREATED_BY AS CREATEDBY,
    A.CREATED_DATE AS CREATEDDATE,
    A.CREATED_HOST AS CREATEDHOST,
    A.UPDATED_BY AS UPDATEDBY,
    A.UPDATED_DATE AS UPDATEDDATE,
    A.UPDATED_HOST AS UPDATEDHOST
   FROM ( SELECT ECLCONFIGURATION.PKID,
            ECLCONFIGURATION.ECL_CONFIGURATION_NAME,
            ECLCONFIGURATION.IS_ACTIVE,
            ECLCONFIGURATION.CREATED_BY,
            ECLCONFIGURATION.CREATED_DATE,
            ECLCONFIGURATION.CREATED_HOST,
            ECLCONFIGURATION.UPDATED_BY,
            ECLCONFIGURATION.UPDATED_DATE,
            ECLCONFIGURATION.UPDATED_HOST
           FROM DBLINK('WORKFLOW_NTT_IMPAIRMENT'::TEXT, '
		SELECT PKID,
		ECL_CONFIGURATION_NAME ,
		IS_ACTIVE ,
		CREATED_BY ,
		CREATED_DATE ,
		CREATED_HOST ,
		UPDATED_BY ,
		UPDATED_DATE,
		UPDATED_HOST
		FROM "EclConfiguration" '::TEXT) ECLCONFIGURATION(PKID BIGINT, ECL_CONFIGURATION_NAME CHARACTER VARYING, IS_ACTIVE BOOLEAN, CREATED_BY CHARACTER VARYING, CREATED_DATE TIMESTAMP WITHOUT TIME ZONE, CREATED_HOST CHARACTER VARYING, UPDATED_BY CHARACTER VARYING, UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE, UPDATED_HOST CHARACTER VARYING)) A;