DROP VIEW IF EXISTS VW_IFRS_ECL_MODEL_DETAIL_PD;

CREATE VIEW VW_IFRS_ECL_MODEL_DETAIL_PD
AS

 SELECT A.PKID,
    A.SYSCODE_ECL_CONFIGURATION AS ECL_MODEL_ID,
    A.SYSCODE_SEGMENTATION AS SEGMENTATION_ID,
    A.SYSCODE_PD_CONFIG AS PD_MODEL_ID,
    NULL::BIGINT AS ME_MODEL_ID,
    A.EFFECTIVE_DATE AS EFF_DATE_OPTION,
    0 AS IS_DELETE,
    A.CREATED_BY AS CREATEDBY,
    A.CREATED_DATE AS CREATEDDATE,
    A.CREATED_HOST AS CREATEDHOST,
    A.UPDATED_BY AS UPDATEDBY,
    A.UPDATED_DATE AS UPDATEDDATE,
    A.UPDATED_HOST AS UPDATEDHOST,
    NULL::TEXT AS SCALAR_EFF_DATE_OPTION,
    CURRENT_DATE AS SCALAR_EFF_DATE
   FROM ( SELECT ECLPDMODEL.PKID,
            ECLPDMODEL.SYSCODE_ECL_CONFIGURATION,
            ECLPDMODEL.SYSCODE_SEGMENTATION,
            ECLPDMODEL.SYSCODE_PD_CONFIG,
            ECLPDMODEL.EFFECTIVE_DATE,
            ECLPDMODEL.CREATED_BY,
            ECLPDMODEL.CREATED_DATE,
            ECLPDMODEL.CREATED_HOST,
            ECLPDMODEL.UPDATED_BY,
            ECLPDMODEL.UPDATED_DATE,
            ECLPDMODEL.UPDATED_HOST
           FROM dblink('workflow_ntt_impairment'::TEXT, '
			SELECT A.PKID,
				MAX(B.PKID) AS SYSCODE_ECL_CONFIGURATION,
				MAX(C.PKID) AS SYSCODE_SEGMENTATION,
				MAX(D.PKID) AS SYSCODE_PD_CONFIG,
				MAX(A.EFFECTIVE_DATE),
				A.CREATED_BY,
				A.CREATED_DATE, 
				A.CREATED_HOST, 
				A.UPDATED_BY, 
				A.UPDATED_DATE, 
				A.UPDATED_HOST
			FROM "EclPdModel" A
			LEFT JOIN "EclConfiguration" B ON A.SYSCODE_ECL_CONFIGURATION = B.SYSCODE_ECL_CONFIGURATION
			LEFT JOIN "Segmentation" C ON A.CODE_SEGMENTATION = c.SYSCODE_SEGMENTATION
			LEFT JOIN "PdConfiguration" D ON A.CODE_PD_CONFIGURATION = D.SYSCODE_PD_CONFIG
			GROUP BY A.PKID,
				A.CREATED_BY,
				A.CREATED_DATE, 
				A.CREATED_HOST, 
				A.UPDATED_BY, 
				A.UPDATED_DATE, 
				A.UPDATED_HOST'::TEXT) ECLPDMODEL(PKID BIGINT, SYSCODE_ECL_CONFIGURATION BIGINT, SYSCODE_SEGMENTATION BIGINT, SYSCODE_PD_CONFIG BIGINT, EFFECTIVE_DATE CHARACTER VARYING, CREATED_BY CHARACTER VARYING, CREATED_DATE TIMESTAMP WITHOUT TIME ZONE, CREATED_HOST CHARACTER VARYING, UPDATED_BY CHARACTER VARYING, UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE, UPDATED_HOST CHARACTER VARYING)) A;