DROP VIEW IF EXISTS VW_PD_FL_OVERRIDE;
CREATE VIEW VW_PD_FL_OVERRIDE
AS
SELECT DISTINCT A.PD_EFFECTIVE_DATE AS "Effective Date"
,A.SCALAR_EFFECTIVE_DATE AS "FL Date"
,B.TM_RULE_NAME AS "PD Rule Name"
,A.PD_RULE_ID AS "Pd Rule ID"
,A.FL_SEQ AS "FL Sequence"
,A.FL_YEAR AS "FL Year"
,A.FL_MONTH AS "FL Month"
,A.PD_RATE AS "PD Rate System"
,0 AS "PD Rate Override"
FROM IFRS_IMP_PD_FL_TERM_STRUCTURE A
INNER JOIN IFRS_PD_RULES_CONFIG B ON A.PD_RULE_ID = B.PKID
WHERE B.ACTIVE_FLAG = 1 AND B.IS_DELETE = 0 
