DROP VIEW IF EXISTS VW_IFRS_ECL_MODEL_DETAIL_EAD;

CREATE VIEW VW_IFRS_ECL_MODEL_DETAIL_EAD
AS
SELECT A.PKID
,A.SYSCODE_ECL_CONFIGURATION AS ECL_MODEL_ID
,A.CODE_SEGMENTATION AS SEGMENTATION_ID
,A.CODE_LGD_CONFIG AS EAD_MODEL_ID
,0 AS IS_DELETE
,A.CREATED_BY AS CREATEDBY
,A.CREATED_DATE AS CREATEDDATE
,A.CREATED_HOST AS CREATEDHOST
,A.UPDATED_BY AS UPDATEDBY
,A.UPDATED_DATE AS UPDATEDDATE
,A.UPDATED_HOST AS UPDATEDHOST
,NULL AS CCF_MODEL_ID
,NULL AS CCF_EFF_DATE_OPTION
,A.CCF_DATE AS CCF_EFF_DATE
		FROM (
		SELECT * FROM DBLINK('WORKFLOW_NTT_IMPAIRMENT','
			SELECT A.PKID,
					MAX(B.PKID) AS SYSCODE_ECL_CONFIGURATION,
					MAX(C.PKID) AS CODE_SEGMENTATION,
					MAX(D.PKID) AS CODE_EAD_CONFIG,
					A.CREATED_BY,
					A.CREATED_DATE, 
					A.CREATED_HOST, 
					A.UPDATED_BY, 
					A.UPDATED_DATE, 
					A.UPDATED_HOST,
					A.CCF_DATE
			FROM "ECLEADMODEL" A
			LEFT JOIN "ECLCONFIGURATION" B ON A.SYSCODE_ECL_CONFIGURATION = B.SYSCODE_ECL_CONFIGURATION
			LEFT JOIN "SEGMENTATION" C ON A.CODE_SEGMENTATION = C.SYSCODE_SEGMENTATION
			LEFT JOIN "EADCONFIGURATION" D ON A.CODE_EAD_CONFIGURATION = D.SYSCODE_EAD_CONFIG
			WHERE A.IS_ACTIVE = TRUE
			GROUP BY A.PKID,
					A.CREATED_BY,
					A.CREATED_DATE, 
					A.CREATED_HOST, 
					A.UPDATED_BY, 
					A.UPDATED_DATE, 
					A.UPDATED_HOST,
					A.CCF_DATE')
			ECLPDMODEL(PKID BIGINT,
						SYSCODE_ECL_CONFIGURATION BIGINT,
						CODE_SEGMENTATION BIGINT,
						CODE_LGD_CONFIG BIGINT,
						CREATED_BY CHARACTER VARYING, 
						CREATED_DATE TIMESTAMP WITHOUT TIME ZONE, 
						CREATED_HOST CHARACTER VARYING, 
						UPDATED_BY CHARACTER VARYING, 
						UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE, 
						UPDATED_HOST CHARACTER VARYING,
						CCF_DATE TIMESTAMP WITHOUT TIME ZONE)
			) A