DROP VIEW IF EXISTS VW_MASTER_EXCHANGE_RATE;

CREATE VIEW VW_MASTER_EXCHANGE_RATE AS
SELECT * FROM dblink('workflow_ntt_parameter','SELECT PKID
,DOWNLOAD_DATE
,CURRENCY
,CURRENCY_DESC
,RATE_AMOUNT
,MAINTAIN_DATE FROM (
SELECT A.SYSCODE_EXCHANGE_RATE,
A.PKID,
A.DTE_EFFT::DATE AS DOWNLOAD_DATE,
UPPER(A.CDE_BASE_CURR) AS CURRENCY,
UPPER(A.CDE_QUO_CURR) AS CURRENCY_DESC,
A.AMT_BID AS RATE_AMOUNT,
CASE WHEN A.UPDATED_DATE IS NULL THEN A.CREATED_DATE ELSE A.UPDATED_DATE END MAINTAIN_DATE
FROM "MstExchangeRate" A
WHERE A.IS_ACTIVE = TRUE
ORDER BY A.DTE_EFFT::DATE ASC
) IFRS_MASTER_EXCHANGE_RATE') AS MASTER_EXCHANGE_RATE(
PKID BIGINT
,DOWNLOAD_DATE DATE
,CURRENCY CHARACTER VARYING(3)
,CURRENCY_DESC CHARACTER VARYING(100)
,RATE_AMOUNT NUMERIC
,MAINTAIN_DATE TIMESTAMP WITHOUT TIME ZONE);