DROP VIEW IF EXISTS VW_LIFETIME_OVERRIDE;
CREATE VIEW VW_LIFETIME_OVERRIDE
AS
SELECT DISTINCT COALESCE(C.LIFETIME_RULE_NAME, B.SUB_SEGMENT) AS LIFETIME_RULE_NAME, 
B.PKID AS "segmentation_id",
A.GROUP_SEGMENT AS "segmentation",
A.DOWNLOAD_DATE,
A.LIFETIME AS "lifetime_rate",
0 AS "lifetime_override"
FROM TMP_IFRS_ECL_IMA A
INNER JOIN IFRS_MSTR_SEGMENT_RULES_HEADER B ON A.GROUP_SEGMENT = B.GROUP_SEGMENT   
LEFT JOIN IFRS_LIFETIME_RULES_CONFIG C ON A.SEGMENTATION_ID = B.PKID
WHERE A.DOWNLOAD_DATE = (SELECT CURRDATE FROM IFRS_PRC_DATE)
AND B.IS_DELETE = 0 AND B.ACTIVE_FLAG = 1;