DROP VIEW IF EXISTS VW_PREPAYMENT_OVERRIDE;

CREATE VIEW VW_PREPAYMENT_OVERRIDE
AS
SELECT DISTINCT B.PKID, B.PREPAYMENT_RULE_NAME AS "prepayment_configuration",
B.SEGMENTATION_ID AS "segmentation_id", 
A.SEGMENT AS "segmentation", 
A.DOWNLOAD_DATE, 
0 AS "prepayment_rate", 
COALESCE(PREPAYMENT_OVERRIDE,0) AS "prepayment_override"
FROM IFRS_MASTER_ACCOUNT A
INNER JOIN IFRS_PREPAYMENT_RULES_CONFIG B ON A.SEGMENTATION_ID = B.SEGMENTATION_ID
LEFT JOIN IFRS_PREPAYMENT_OVERRIDE C ON A.SEGMENTATION_ID = C.SEGMENTATION_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
WHERE A.DOWNLOAD_DATE = (SELECT CURRDATE FROM IFRS_PRC_DATE)
AND B.IS_DELETE = 0 AND B.ACTIVE_FLAG = 1;