DROP VIEW IF EXISTS VW_LGD_RULES_CONFIG CASCADE;

CREATE VIEW VW_LGD_RULES_CONFIG AS
SELECT * FROM dblink('workflow_ntt_impairment','SELECT * FROM (
SELECT A.PKID,
A.DEFAULT_RULE_ID,
A.LGD_RULE_NAME,
A.SEGMENTATION_ID,
A.LGD_METHOD,
A.LGW_HISTORICAL_DATA,
A.WORKOUT_PERIOD,
A.MIN_VALUE,
A.MAX_VALUE,
A.CUT_OFF_DATE, 
CASE WHEN B.IS_ACTIVE = TRUE THEN 1 ELSE 0 END ACTIVE_FLAG,
0 AS IS_DELETE,
''SYSTEM'' AS CREATEDBY,
CURRENT_DATE AS CREATEDDATE,
''LOCALHOST'' AS CREATEDHOST,
1 AS LAG_1MONTH_FLAG,
''PENDING'' AS RUNNING_STATUS FROM (
SELECT A.SYSCODE_LGD_CONFIG AS SYSCODE_LGD_CONFIG,
MAX(A.PKID) AS PKID,
MAX(B.PKID) AS DEFAULT_RULE_ID,
MAX(UPPER(A.LGD_NAME)) AS LGD_RULE_NAME,
MAX(C.SYSCODE_SEGMENTATION) AS SEGMENT_CODE,
MAX(C.PKID) AS SEGMENTATION_ID,
MAX(UPPER(A.LGD_METHOD)) AS LGD_METHOD,
MAX(A.HISTORICAL_DATA) AS LGW_HISTORICAL_DATA,
MAX(A.WORKOUT_PERIOD) AS WORKOUT_PERIOD,
MAX(A.LGD_MIN) AS MIN_VALUE,
MAX(A.LGD_MAX) AS MAX_VALUE,
MAX(A.EFFECTIVE_END_DATE::DATE) AS CUT_OFF_DATE
FROM "LgdConfiguration" A
LEFT JOIN "DefaultCriteria" B ON A.DEFAULT_CRITERIA_CODE = B.SYSCODE_DEFAULT_CRITERIA
LEFT JOIN "Segmentation" C ON A.SEGMENT_CODE = C.SYSCODE_SEGMENTATION
GROUP BY A.SYSCODE_LGD_CONFIG
) A
INNER JOIN "LgdConfiguration" B ON A.PKID = B.PKID
WHERE B.IS_ACTIVE = TRUE
) AS IFRS_LGD_RULES_CONFIG') AS LGD_RULES_CONFIG(PKID BIGINT
,DEFAULT_RULE_ID BIGINT
,LGD_RULE_NAME CHARACTER VARYING(250)
,SEGMENTATION_ID BIGINT
,LGD_METHOD CHARACTER VARYING(50)
,LGW_HISTORICAL_DATA SMALLINT
,WORKOUT_PERIOD SMALLINT
,MIN_VALUE DOUBLE PRECISION
,MAX_VALUE DOUBLE PRECISION
,CUT_OFF_DATE DATE
,ACTIVE_FLAG INTEGER
,IS_DELETE INTEGER
,CREATEDBY CHARACTER VARYING(36)
,CREATEDDATE TIMESTAMP WITHOUT TIME ZONE
,CREATEDHOST CHARACTER VARYING(30)
,LAG_1MONTH_FLAG INTEGER
,RUNNING_STATUS CHARACTER VARYING(20));