DROP VIEW IF EXISTS VW_CCF_OVERRIDE;
CREATE VIEW VW_CCF_OVERRIDE
AS
SELECT DISTINCT B.PKID,
B.PKID AS CCF_RULE_ID,
B.CCF_RULE_NAME AS CCF_CONFIGURATION, 
A.DOWNLOAD_DATE AS DOWNLOAD_DATE, 
CASE UPPER(B.AVERAGE_METHOD)
	WHEN 'WEIGHTED' THEN
		A.WEIGHTED_AVG_CCF
	WHEN 'SIMPLE' THEN
		A.SIMPLE_AVG_CCF
END AS CCF_RATE, 
COALESCE(C.CCF_OVERRIDE, 0) AS CCF_OVERRIDE
FROM IFRS_EAD_CCF_HEADER A
INNER JOIN IFRS_CCF_RULES_CONFIG B ON A.CCF_RULE_ID = B.PKID
LEFT JOIN IFRS_CCF_OVERRIDE C ON A.CCF_RULE_ID = C.CCF_RULE_ID AND A.DOWNLOAD_DATE = C.DOWNLOAD_DATE
WHERE A.DOWNLOAD_DATE = (SELECT CURRDATE FROM IFRS_PRC_DATE)
AND B.IS_DELETE = 0 AND B.ACTIVE_FLAG = 1;