CREATE OR REPLACE PROCEDURE SP_IFRS_INSERT_DCF(v_UploadId IN number)
AS
BEGIN
    INSERT INTO TBLU_DCF_INFO
    (
        OVERRIDEID,
        FILENAME,
        UPLOAD_STATUS,
        CUSTOMER_NUMBER,
        UPLOADBY,
        UPLOADDATE,
        UPLOADHOST,
        APPROVEDBY,
        APPROVEDDATE,
        APPROVEDHOST
    )
    SELECT DISTINCT B.PKID OVERRIDEID,
        C.FILENAME,
        C.STATUS UPLOAD_STATUS,
        B.CUSTOMER_NUMBER,
        A.UPLOADBY,
        A.UPLOADDATE,
        A.UPLOADHOST,
        A.APPROVEDBY,
        A.APPROVEDDATE,
        A.APPROVEDHOST
    FROM TBLU_DCF_BULK A
    JOIN IFRS_IA_OVERRIDEH B
    ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
    AND A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
    AND A.UPLOADID = v_UploadId
    JOIN TBLT_UPLOAD_POOL C
    ON A.UPLOADID = C.PKID;

    INSERT INTO TBLU_DCF_DETAIL
    (
        UPLOADID,
        OVERRIDEID,
        ROW_NUMBER,
        CUSTOMER_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        ESTIMATED_REALIZE_DATE,
        ESTIMATED_CF_PERCENT,
        DISCOUNT_RATE_TRS,
        DISCOUNT_RATE_TRF,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT DISTINCT v_UploadId,
        B.OVERRIDEID,
        A.ROW_NUMBER,
        A.CUSTOMER_NUMBER,
        B.ACCOUNT_NUMBER,
        B.MASTERID,
        A.EXPECTED_PERIOD,
        A.EXPECTED_CF_PERCENT,
        A.DISCOUNT_RATE_TRS,
        A.DISCOUNT_RATE_TRF,
        B.CREATEDBY,
        B.CREATEDDATE,
        B.CREATEDHOST,
        B.UPDATEDBY,
        B.UPDATEDDATE,
        B.UPDATEDHOST
    FROM
    (
        SELECT ROW_NUMBER() OVER(ORDER BY A2.CUSTOMER_NUMBER, A2.EXPECTED_PERIOD) ROW_NUMBER, A2.*
        FROM TBLU_DCF_BULK A2
        WHERE A2.UPLOADID = v_UploadId
    ) A
    JOIN IFRS_IA_OVERRIDED B
    ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
    JOIN IFRS_IA_OVERRIDEH C
    ON A.EFFECTIVE_DATE = C.EFFECTIVE_DATE
    AND B.OVERRIDEID = C.PKID
    ORDER BY A.ROW_NUMBER, B.ACCOUNT_NUMBER;

    COMMIT;
END;