CREATE OR REPLACE PROCEDURE  SP_IFRS_INITIAL_IA_OVERRIDE(v_UploadId IN number)
AS
BEGIN
    DELETE TBLU_DCF_INFO
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;

    DELETE TBLU_DCF_DETAIL A
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;

    DELETE TBLT_PAYMENTEXPECTED
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;

    DELETE TBLT_PAYMENTEXPECTEDH
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;

    DELETE IFRS_IA_OVERRIDED
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;

    DELETE FROM IFRS_IA_OVERRIDEH A
    WHERE EFFECTIVE_DATE IN
    (
        SELECT EFFECTIVE_DATE FROM TBLU_DCF_BULK B
        WHERE UPLOADID = v_UploadId
    );

    COMMIT;
END;