CREATE OR REPLACE PROCEDURE SP_IFRS_INSERT_IA_OVERRIDE(v_UploadId IN number, v_DOWNLOADDATE DATE DEFAULT('1-JAN-1900'))
AS
    v_CURRDATE DATE;
    v_QUERY VARCHAR2(32000);
    v_STR_SQL_RULE VARCHAR2(32000);
BEGIN
    IF v_DOWNLOADDATE = '1-JAN-1900' THEN
        SELECT CURRDATE INTO V_CURRDATE FROM IFRS_PRC_DATE;
    ELSE
        V_CURRDATE := v_DOWNLOADDATE;
    END IF;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE GTMP_IFRS_MASTER_ACCOUNT';

    INSERT INTO GTMP_IFRS_MASTER_ACCOUNT
    (
        PKID,
        DOWNLOAD_DATE,
        MASTERID,
        MASTER_ACCOUNT_CODE,
        DATA_SOURCE,
        GLOBAL_CUSTOMER_NUMBER,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        PREVIOUS_ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        INTEREST_RATE,
        MARKET_RATE,
        PRODUCT_GROUP,
        PRODUCT_TYPE,
        PRODUCT_CODE,
        PRODUCT_ENTITY,
        GL_CONSTNAME,
        BRANCH_CODE,
        BRANCH_CODE_OPEN,
        CURRENCY,
        EXCHANGE_RATE,
        INITIAL_OUTSTANDING,
        OUTSTANDING,
        OUTSTANDING_IDC,
        OUTSTANDING_JF,
        OUTSTANDING_BANK,
        OUTSTANDING_PASTDUE,
        PLAFOND,
        PLAFOND_CASH,
        INTEREST_ACCRUED,
        INSTALLMENT_AMOUNT,
        UNUSED_AMOUNT,
        DOWN_PAYMENT_AMOUNT,
        JF_FLAG,
        LOAN_START_DATE,
        LOAN_DUE_DATE,
        LOAN_START_AMORTIZATION,
        LOAN_END_AMORTIZATION,
        INSTALLMENT_GRACE_PERIOD,
        NEXT_PAYMENT_DATE,
        NEXT_INT_PAYMENT_DATE,
        LAST_PAYMENT_DATE,
        FIRST_INSTALLMENT_DATE,
        TENOR,
        REMAINING_TENOR,
        PAYMENT_CODE,
        PAYMENT_TERM,
        INTEREST_CALCULATION_CODE,
        INTEREST_PAYMENT_TERM,
        RESTRUCTURE_DATE,
        RESTRUCTURE_FLAG,
        POCI_FLAG,
        STAFF_LOAN_FLAG,
        BELOW_MARKET_FLAG,
        BTB_FLAG,
        COMMITTED_FLAG,
        REVOLVING_FLAG,
        IAS_CLASS,
        IFRS9_CLASS,
        BM_RESULT,
        SPPI_RESULT,
        AMORT_TYPE,
        EIR_STATUS,
        ECF_STATUS,
        EIR,
        EIR_AMOUNT,
        FAIR_VALUE_AMOUNT,
        INITIAL_UNAMORT_TXN_COST,
        INITIAL_UNAMORT_ORG_FEE,
        UNAMORT_COST_AMT,
        UNAMORT_FEE_AMT,
        UNAMORT_BENEFIT,
        DAILY_AMORT_AMT,
        UNAMORT_AMT_TOTAL_JF,
        UNAMORT_FEE_AMT_JF,
        UNAMORT_COST_AMT_JF,
        ORIGINAL_COLLECTABILITY,
        BI_COLLECTABILITY,
        DAY_PAST_DUE,
        DPD_START_DATE,
        DPD_ZERO_COUNTER,
        NPL_DATE,
        NPL_FLAG,
        DEFAULT_DATE,
        DEFAULT_FLAG,
        WRITEOFF_FLAG,
        WRITEOFF_DATE,
        OUTSTANDING_WO,
        IMPAIRED_FLAG,
        IS_IMPAIRED,
        GROUP_SEGMENT,
        SEGMENT,
        SUB_SEGMENT,
        CR_STAGE,
        LIFETIME,
        EAD_RULE_ID,
        EAD_SEGMENT,
        EAD_AMOUNT,
        LGD_RULE_ID,
        LGD_SEGMENT,
        PD_RULE_ID,
        PD_SEGMENT,
        BUCKET_GROUP,
        BUCKET_ID,
        RATING_CODE,
        ECL_12_AMOUNT,
        ECL_LIFETIME_AMOUNT,
        ECL_AMOUNT,
        CA_UNWINDING_AMOUNT,
        IA_UNWINDING_AMOUNT,
        IA_UNWINDING_SUM_AMOUNT,
        BEGINNING_BALANCE,
        ENDING_BALANCE,
        WRITEBACK_AMOUNT,
        CHARGE_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_VARCHAR_6,
        RESERVED_VARCHAR_7,
        RESERVED_VARCHAR_8,
        RESERVED_VARCHAR_9,
        RESERVED_VARCHAR_10,
        RESERVED_VARCHAR_11,
        RESERVED_VARCHAR_12,
        RESERVED_VARCHAR_13,
        RESERVED_VARCHAR_14,
        RESERVED_VARCHAR_15,
        RESERVED_VARCHAR_16,
        RESERVED_VARCHAR_17,
        RESERVED_VARCHAR_18,
        RESERVED_VARCHAR_19,
        RESERVED_VARCHAR_20,
        RESERVED_VARCHAR_21,
        RESERVED_VARCHAR_22,
        RESERVED_VARCHAR_23,
        RESERVED_VARCHAR_24,
        RESERVED_VARCHAR_25,
        RESERVED_VARCHAR_26,
        RESERVED_VARCHAR_27,
        RESERVED_VARCHAR_28,
        RESERVED_VARCHAR_29,
        RESERVED_VARCHAR_30,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_AMOUNT_6,
        RESERVED_AMOUNT_7,
        RESERVED_AMOUNT_8,
        RESERVED_AMOUNT_9,
        RESERVED_AMOUNT_10,
        RESERVED_AMOUNT_11,
        RESERVED_AMOUNT_12,
        RESERVED_AMOUNT_13,
        RESERVED_AMOUNT_14,
        RESERVED_AMOUNT_15,
        RESERVED_AMOUNT_16,
        RESERVED_AMOUNT_17,
        RESERVED_AMOUNT_18,
        RESERVED_AMOUNT_19,
        RESERVED_AMOUNT_20,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_RATE_6,
        RESERVED_RATE_7,
        RESERVED_RATE_8,
        RESERVED_RATE_9,
        RESERVED_RATE_10,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_FLAG_6,
        RESERVED_FLAG_7,
        RESERVED_FLAG_8,
        RESERVED_FLAG_9,
        RESERVED_FLAG_10,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        RESERVED_DATE_6,
        RESERVED_DATE_7,
        RESERVED_DATE_8,
        RESERVED_DATE_9,
        RESERVED_DATE_10,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT
        PKID,
        DOWNLOAD_DATE,
        MASTERID,
        MASTER_ACCOUNT_CODE,
        DATA_SOURCE,
        GLOBAL_CUSTOMER_NUMBER,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        PREVIOUS_ACCOUNT_NUMBER,
        ACCOUNT_STATUS,
        INTEREST_RATE,
        MARKET_RATE,
        PRODUCT_GROUP,
        PRODUCT_TYPE,
        PRODUCT_CODE,
        PRODUCT_ENTITY,
        GL_CONSTNAME,
        BRANCH_CODE,
        BRANCH_CODE_OPEN,
        CURRENCY,
        EXCHANGE_RATE,
        INITIAL_OUTSTANDING,
        OUTSTANDING,
        OUTSTANDING_IDC,
        OUTSTANDING_JF,
        OUTSTANDING_BANK,
        OUTSTANDING_PASTDUE,
        PLAFOND,
        PLAFOND_CASH,
        INTEREST_ACCRUED,
        INSTALLMENT_AMOUNT,
        UNUSED_AMOUNT,
        DOWN_PAYMENT_AMOUNT,
        JF_FLAG,
        LOAN_START_DATE,
        LOAN_DUE_DATE,
        LOAN_START_AMORTIZATION,
        LOAN_END_AMORTIZATION,
        INSTALLMENT_GRACE_PERIOD,
        NEXT_PAYMENT_DATE,
        NEXT_INT_PAYMENT_DATE,
        LAST_PAYMENT_DATE,
        FIRST_INSTALLMENT_DATE,
        TENOR,
        REMAINING_TENOR,
        PAYMENT_CODE,
        PAYMENT_TERM,
        INTEREST_CALCULATION_CODE,
        INTEREST_PAYMENT_TERM,
        RESTRUCTURE_DATE,
        RESTRUCTURE_FLAG,
        POCI_FLAG,
        STAFF_LOAN_FLAG,
        BELOW_MARKET_FLAG,
        BTB_FLAG,
        COMMITTED_FLAG,
        REVOLVING_FLAG,
        IAS_CLASS,
        IFRS9_CLASS,
        BM_RESULT,
        SPPI_RESULT,
        AMORT_TYPE,
        EIR_STATUS,
        ECF_STATUS,
        EIR,
        EIR_AMOUNT,
        FAIR_VALUE_AMOUNT,
        INITIAL_UNAMORT_TXN_COST,
        INITIAL_UNAMORT_ORG_FEE,
        UNAMORT_COST_AMT,
        UNAMORT_FEE_AMT,
        UNAMORT_BENEFIT,
        DAILY_AMORT_AMT,
        UNAMORT_AMT_TOTAL_JF,
        UNAMORT_FEE_AMT_JF,
        UNAMORT_COST_AMT_JF,
        ORIGINAL_COLLECTABILITY,
        BI_COLLECTABILITY,
        DAY_PAST_DUE,
        DPD_START_DATE,
        DPD_ZERO_COUNTER,
        NPL_DATE,
        NPL_FLAG,
        DEFAULT_DATE,
        DEFAULT_FLAG,
        WRITEOFF_FLAG,
        WRITEOFF_DATE,
        OUTSTANDING_WO,
        IMPAIRED_FLAG,
        IS_IMPAIRED,
        GROUP_SEGMENT,
        SEGMENT,
        SUB_SEGMENT,
        CR_STAGE,
        LIFETIME,
        EAD_RULE_ID,
        EAD_SEGMENT,
        EAD_AMOUNT,
        LGD_RULE_ID,
        LGD_SEGMENT,
        PD_RULE_ID,
        PD_SEGMENT,
        BUCKET_GROUP,
        BUCKET_ID,
        RATING_CODE,
        ECL_12_AMOUNT,
        ECL_LIFETIME_AMOUNT,
        ECL_AMOUNT,
        CA_UNWINDING_AMOUNT,
        IA_UNWINDING_AMOUNT,
        IA_UNWINDING_SUM_AMOUNT,
        BEGINNING_BALANCE,
        ENDING_BALANCE,
        WRITEBACK_AMOUNT,
        CHARGE_AMOUNT,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        RESERVED_VARCHAR_3,
        RESERVED_VARCHAR_4,
        RESERVED_VARCHAR_5,
        RESERVED_VARCHAR_6,
        RESERVED_VARCHAR_7,
        RESERVED_VARCHAR_8,
        RESERVED_VARCHAR_9,
        RESERVED_VARCHAR_10,
        RESERVED_VARCHAR_11,
        RESERVED_VARCHAR_12,
        RESERVED_VARCHAR_13,
        RESERVED_VARCHAR_14,
        RESERVED_VARCHAR_15,
        RESERVED_VARCHAR_16,
        RESERVED_VARCHAR_17,
        RESERVED_VARCHAR_18,
        RESERVED_VARCHAR_19,
        RESERVED_VARCHAR_20,
        RESERVED_VARCHAR_21,
        RESERVED_VARCHAR_22,
        RESERVED_VARCHAR_23,
        RESERVED_VARCHAR_24,
        RESERVED_VARCHAR_25,
        RESERVED_VARCHAR_26,
        RESERVED_VARCHAR_27,
        RESERVED_VARCHAR_28,
        RESERVED_VARCHAR_29,
        '' RESERVED_VARCHAR_30,
        RESERVED_AMOUNT_1,
        RESERVED_AMOUNT_2,
        RESERVED_AMOUNT_3,
        RESERVED_AMOUNT_4,
        RESERVED_AMOUNT_5,
        RESERVED_AMOUNT_6,
        RESERVED_AMOUNT_7,
        RESERVED_AMOUNT_8,
        RESERVED_AMOUNT_9,
        RESERVED_AMOUNT_10,
        RESERVED_AMOUNT_11,
        RESERVED_AMOUNT_12,
        RESERVED_AMOUNT_13,
        RESERVED_AMOUNT_14,
        RESERVED_AMOUNT_15,
        RESERVED_AMOUNT_16,
        RESERVED_AMOUNT_17,
        RESERVED_AMOUNT_18,
        RESERVED_AMOUNT_19,
        RESERVED_AMOUNT_20,
        RESERVED_RATE_1,
        RESERVED_RATE_2,
        RESERVED_RATE_3,
        RESERVED_RATE_4,
        RESERVED_RATE_5,
        RESERVED_RATE_6,
        RESERVED_RATE_7,
        RESERVED_RATE_8,
        RESERVED_RATE_9,
        RESERVED_RATE_10,
        RESERVED_FLAG_1,
        RESERVED_FLAG_2,
        RESERVED_FLAG_3,
        RESERVED_FLAG_4,
        RESERVED_FLAG_5,
        RESERVED_FLAG_6,
        RESERVED_FLAG_7,
        RESERVED_FLAG_8,
        RESERVED_FLAG_9,
        RESERVED_FLAG_10,
        RESERVED_DATE_1,
        RESERVED_DATE_2,
        RESERVED_DATE_3,
        RESERVED_DATE_4,
        RESERVED_DATE_5,
        RESERVED_DATE_6,
        RESERVED_DATE_7,
        RESERVED_DATE_8,
        RESERVED_DATE_9,
        RESERVED_DATE_10,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM IFRS_MASTER_ACCOUNT
    WHERE DOWNLOAD_DATE = v_CURRDATE
    AND CUSTOMER_NUMBER IN
    (
        SELECT A.CUSTOMER_NUMBER
        FROM TBLU_DCF_BULK A
        WHERE UPLOADID = v_UploadId
    );

    COMMIT;

    /* ===========================================================================
       Only calculate IA for borrowers that is change:
       Outstanding or Discount Rate or Expected Period or Expected CF Percent
       =========================================================================== */
    UPDATE GTMP_IFRS_MASTER_ACCOUNT
    SET RESERVED_VARCHAR_30 = 'ACCOUNT DETAIL UNCHANGED'
    WHERE ACCOUNT_NUMBER NOT IN
    (
        SELECT A.ACCOUNT_NUMBER
        FROM GTMP_IFRS_MASTER_ACCOUNT A
        JOIN TBLU_DCF_BULK B
        ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
        JOIN
        (
            SELECT A2.CUSTOMER_NUMBER, A2.EXPECTED_PERIOD, A2.EXPECTED_CF_PERCENT
            FROM TBLU_DCF_BULK A2
            JOIN
            (
                SELECT CUSTOMER_NUMBER, MAX(UPLOADID) UPLOADID
                FROM TBLU_DCF_BULK
                WHERE UPLOADID < v_UploadId
                GROUP BY CUSTOMER_NUMBER
            ) B2
            ON A2.CUSTOMER_NUMBER = B2.CUSTOMER_NUMBER
            AND A2.UPLOADID = B2.UPLOADID
        ) C
        ON B.CUSTOMER_NUMBER = C.CUSTOMER_NUMBER
        JOIN IFRS_IA_OVERRIDED D
        ON A.MASTERID = D.MASTERID
        JOIN
        (
            SELECT MASTERID, MAX(OVERRIDEID) OVERRIDEID
            FROM IFRS_IA_OVERRIDED
            GROUP BY MASTERID
        ) E
        ON D.OVERRIDEID = E.OVERRIDEID
        AND D.MASTERID = E.MASTERID
        WHERE B.UPLOADID = v_UploadId
        AND (A.OUTSTANDING != D.OUTSTANDING OR A.INTEREST_RATE != D.INTEREST_RATE OR B.EXPECTED_PERIOD != C.EXPECTED_PERIOD OR B.EXPECTED_CF_PERCENT != C.EXPECTED_CF_PERCENT)
		UNION --New IA Customers / Accounts
		SELECT A.ACCOUNT_NUMBER
		FROM GTMP_IFRS_MASTER_ACCOUNT A
        JOIN TBLU_DCF_BULK B
        ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
        WHERE B.UPLOADID = v_UploadId
		AND A.ACCOUNT_NUMBER NOT IN
		(SELECT DISTINCT ACCOUNT_NUMBER FROM IFRS_IA_OVERRIDED)
		UNION --Already overrided to CA in previous month
		SELECT A.ACCOUNT_NUMBER
        FROM GTMP_IFRS_MASTER_ACCOUNT A
        JOIN TBLU_DCF_BULK B
        ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
        WHERE B.UPLOADID = v_UploadId
		AND A.CUSTOMER_NUMBER IN
		(SELECT DISTINCT CUSTOMER_NUMBER FROM IFRS_IA_OVERRIDEH_HIST WHERE RESERVED_DATE_2 = ADD_MONTHS(V_CURRDATE, -1))
    );

    COMMIT;

    --Additional IA filter for EOM/ECL process
    IF v_CURRDATE = LAST_DAY(v_CURRDATE) THEN
        SP_IFRS_GENERATE_RULE('THRESHOLD');

        SELECT PD_RULES_QRY_RESULT
        INTO v_STR_SQL_RULE
        FROM GTMP_IFRS_SCENARIO_GEN_QUERY;

        v_QUERY := 'DELETE GTMP_IFRS_MASTER_ACCOUNT A WHERE NOT(' || v_STR_SQL_RULE || ') OR OUTSTANDING <= 0 OR ACCOUNT_STATUS != ''A''';

        EXECUTE IMMEDIATE v_QUERY;
        COMMIT;

        UPDATE GTMP_IFRS_MASTER_ACCOUNT
        SET IMPAIRED_FLAG = 'I'
        WHERE DOWNLOAD_DATE = v_CURRDATE;
    END IF;


    INSERT INTO IFRS_IA_OVERRIDEH
    (
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        DOWNLOAD_DATE,
        OVERRIDE_DATE,
        EFFECTIVE_DATE,
        CURRENCY,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        IMPAIRED_FLAG,
        ECL_AMOUNT,
        PV_AMOUNT,
        STATUS,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT DISTINCT A.CUSTOMER_NUMBER,
        MAX(NVL(A.CUSTOMER_NAME, ' ')),
        v_CURRDATE,
        TRUNC(SYSDATE) AS OVERRIDE_DATE,
        B.EFFECTIVE_DATE,
        ' ' CURRENCY,
        MAX(NVL(CR_STAGE, ' ')),
        MAX(NVL(BI_COLLECTABILITY,' ')),
        MAX(NVL(A.PRODUCT_ENTITY, 'C')),
        MAX(NVL(A.RATING_CODE, ' ')),
        MAX(NVL(A.IMPAIRED_FLAG, 'C')),
        0 ECL_AMOUNT,
        0 PV_AMOUNT,
        0 STATUS,
        B.UPLOADBY,
        B.UPLOADDATE,
        B.UPLOADHOST,
        B.APPROVEDBY,
        B.APPROVEDDATE,
        B.APPROVEDHOST
    FROM GTMP_IFRS_MASTER_ACCOUNT A
    JOIN TBLU_DCF_BULK B
    ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
    AND A.RESERVED_VARCHAR_30 IS NULL
    AND B.UPLOADID = v_UploadId
    GROUP BY A.CUSTOMER_NUMBER,
        B.EFFECTIVE_DATE,
        B.UPLOADBY,
        B.UPLOADDATE,
        B.UPLOADHOST,
        B.APPROVEDBY,
        B.APPROVEDDATE,
        B.APPROVEDHOST;

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDEH_HIST
    (
        PKID,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        DOWNLOAD_DATE,
        OVERRIDE_DATE,
        EFFECTIVE_DATE,
        CURRENCY,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        IMPAIRED_FLAG,
        ECL_AMOUNT,
        PV_AMOUNT,
        STATUS,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT PKID,
        CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        DOWNLOAD_DATE,
        OVERRIDE_DATE,
        EFFECTIVE_DATE,
        CURRENCY,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        IMPAIRED_FLAG,
        ECL_AMOUNT,
        PV_AMOUNT,
        STATUS,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM IFRS_IA_OVERRIDEH
    WHERE EFFECTIVE_DATE IN
    (
        SELECT EFFECTIVE_DATE FROM TBLU_DCF_BULK B
        WHERE UPLOADID = v_UploadId
    );

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDED
    (
        OVERRIDEID,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        EIR,
        INTEREST_RATE,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        DAY_PAST_DUE,
        IMPAIRED_FLAG,
        EAD_AMOUNT,
        OUTSTANDING,
        DATA_SOURCE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT DISTINCT
        C.PKID AS OVERRIDEID,
        C.CUSTOMER_NUMBER,
        A.FACILITY_NUMBER,
        A.ACCOUNT_NUMBER,
        A.MASTERID,
        NVL(A.CURRENCY,' '),
        NVL(A.EIR,0),
        NVL(A.INTEREST_RATE,0),
        NVL(A.CR_STAGE, ' '),
        NVL(A.BI_COLLECTABILITY, ' '),
        A.PRODUCT_ENTITY,
        NVL(A.RATING_CODE, ' '),
        NVL(A.DAY_PAST_DUE,0),
        'I' IMPAIRED_FLAG,
        NVL(A.OUTSTANDING, 0),
        NVL(A.OUTSTANDING, 0),
        A.DATA_SOURCE,
        B.UPLOADBY,
        B.UPLOADDATE,
        B.UPLOADHOST,
        B.APPROVEDBY,
        B.APPROVEDDATE,
        B.APPROVEDHOST
    FROM GTMP_IFRS_MASTER_ACCOUNT A
    JOIN TBLU_DCF_BULK B
    ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
    AND A.RESERVED_VARCHAR_30 IS NULL
    AND B.UPLOADID = v_UploadId
    JOIN IFRS_IA_OVERRIDEH C
    ON A.CUSTOMER_NUMBER = C.CUSTOMER_NUMBER
    --AND NVL(A.PRODUCT_ENTITY, ' ') = NVL(C.PRODUCT_ENTITY, ' ')
    AND B.EFFECTIVE_DATE = C.EFFECTIVE_DATE;

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDED
    (
        OVERRIDEID,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        EIR,
        INTEREST_RATE,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        DAY_PAST_DUE,
        IMPAIRED_FLAG,
        EAD_AMOUNT,
        OUTSTANDING,
        DATA_SOURCE,
        RESERVED_VARCHAR_1,
        RESERVED_VARCHAR_2,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT DISTINCT
        C.PKID AS OVERRIDEID,
        D.CUSTOMER_NUMBER,
        D.FACILITY_NUMBER,
        D.ACCOUNT_NUMBER,
        D.MASTERID,
        D.CURRENCY,
        D.EIR,
        D.INTEREST_RATE,
        A.CR_STAGE,
        A.BI_COLLECTABILITY,
        A.PRODUCT_ENTITY,
        A.RATING_CODE,
        A.DAY_PAST_DUE,
        D.IMPAIRED_FLAG,
        D.EAD_AMOUNT,
        D.OUTSTANDING,
        D.DATA_SOURCE,
        A.RESERVED_VARCHAR_30 RESERVED_VARCHAR_1,
        D.OVERRIDEID RESERVED_VARCHAR_2,
        D.CREATEDBY,
        D.CREATEDDATE,
        D.CREATEDHOST,
        D.UPDATEDBY,
        D.UPDATEDDATE,
        D.UPDATEDHOST
    FROM GTMP_IFRS_MASTER_ACCOUNT A
    JOIN TBLU_DCF_BULK B
    ON A.CUSTOMER_NUMBER = B.CUSTOMER_NUMBER
    AND A.RESERVED_VARCHAR_30 = 'ACCOUNT DETAIL UNCHANGED'
    AND B.UPLOADID = v_UploadId
    JOIN IFRS_IA_OVERRIDEH C
    ON A.CUSTOMER_NUMBER = C.CUSTOMER_NUMBER
    --AND NVL(A.PRODUCT_ENTITY, ' ') = NVL(C.PRODUCT_ENTITY, ' ')
    AND B.EFFECTIVE_DATE = C.EFFECTIVE_DATE
    JOIN
    (
        SELECT A2.*
        FROM IFRS_IA_OVERRIDED A2
        JOIN
        (
            SELECT A3.CUSTOMER_NUMBER, MAX(A3.OVERRIDEID) MAX_OVERRIDEID
            FROM IFRS_IA_OVERRIDED A3
            JOIN GTMP_IFRS_MASTER_ACCOUNT B3
            ON A3.CUSTOMER_NUMBER = B3.CUSTOMER_NUMBER
            AND B3.RESERVED_VARCHAR_30 IS NULL
            JOIN TBLU_DCF_BULK D3
            ON A3.CREATEDDATE < D3.UPLOADDATE
            AND B3.CUSTOMER_NUMBER = D3.CUSTOMER_NUMBER
            AND D3.UPLOADID = v_UploadId
            GROUP BY A3.CUSTOMER_NUMBER
        ) B2
        ON A2.CUSTOMER_NUMBER = B2.CUSTOMER_NUMBER
        AND A2.OVERRIDEID = B2.MAX_OVERRIDEID
    ) D
    ON A.MASTERID = D.MASTERID;

    COMMIT;

    INSERT INTO IFRS_IA_OVERRIDED_HIST
    (
        PKID,
        OVERRIDEID,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        EIR,
        INTEREST_RATE,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        DAY_PAST_DUE,
        IMPAIRED_FLAG,
        EAD_AMOUNT,
        OUTSTANDING,
        DATA_SOURCE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    )
    SELECT PKID,
        OVERRIDEID,
        CUSTOMER_NUMBER,
        FACILITY_NUMBER,
        ACCOUNT_NUMBER,
        MASTERID,
        CURRENCY,
        EIR,
        INTEREST_RATE,
        CR_STAGE,
        BI_COLLECTABILITY,
        PRODUCT_ENTITY,
        RATING_CODE,
        DAY_PAST_DUE,
        IMPAIRED_FLAG,
        EAD_AMOUNT,
        OUTSTANDING,
        DATA_SOURCE,
        CREATEDBY,
        CREATEDDATE,
        CREATEDHOST,
        UPDATEDBY,
        UPDATEDDATE,
        UPDATEDHOST
    FROM IFRS_IA_OVERRIDED
    WHERE OVERRIDEID IN
    (
        SELECT A.PKID FROM IFRS_IA_OVERRIDEH A
        JOIN TBLU_DCF_BULK B
        ON A.EFFECTIVE_DATE = B.EFFECTIVE_DATE
        AND B.UPLOADID = v_UploadId
    );

    COMMIT;
END;